### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [microsoft/DeepSpeed#1002]
Hi,

On a note related to #325, I have added a conda recipe: https://github.com/conda-forge/staged-recipes/pull/14699

But there seems to be a weird bug related to ninja: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=307963&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1431

Any help and/or insight would be appreciated!

Cheers,
Sarthak

**Comment by hadim** [comment]
I would also be interested in getting deepspeed in conda forge including with the CUDA extensions.

Having it there is convenient since conda-forge will automatically take care of any rebuild for new versions of Python and CUDA.

**Comment by hadim** [comment]
See another attempt at https://github.com/conda-forge/staged-recipes/pull/21708
