### ISSUE TITLE
Compared to mindspore (the complete automatic parallel/distributed training from the low level operators graph)?

### ISSUE THREAD

**Issue by ghosthamlet** [microsoft/DeepSpeed#1011]
Has anyone used mindspore (https://github.com/mindspore-ai/mindspore), it seems like mindspore has parallel/distributed training implemented deep in its own deeplearning framework C++ core: 
![mindspore](https://user-images.githubusercontent.com/758325/116357400-040fb680-a82f-11eb-8ede-0371a9aafd07.png)

So Mindspore should have very high performance and much less train code to change,  and it has most distributed training methods(Maybe no ZeRO CPU/NVMe offload) like DeepSpeed. 

By the way, mindspore has successful used to train a 200B model: https://www.reddit.com/r/MachineLearning/comments/myr072/d_huawei_just_announced_that_they_trained_a_200/?sort=new

Can DeepSpeed learn something from Mindspore?

**Comment by jeffra** [comment]
Thanks @ghosthamlet for the pointer, we are aware of the work and have been looking into it further. As with many systems in this space I am sure there are interesting things to be learned from it! :) Will close for now but if you or others have interesting learnings feel free to re-open.
