### ISSUE TITLE
https://github.com/microsoft/DeepSpeed/pull/1012

### ISSUE THREAD

**Issue by jywu-msft** [microsoft/DeepSpeed#1029]
I think that PR has a bug.
we're seeing the below error since yesterday
    self.training_dataloader = self.deepspeed_io(training_data)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 164, in __init__
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 845, in deepspeed_io
    self.training_dataloader = self.deepspeed_io(training_data)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 845, in deepspeed_io
    if not (is_map_style_dataset(dataset) or is_iterable_style_dataset(dataset)):
NameError: name 'is_map_style_dataset' is not defined
    if not (is_map_style_dataset(dataset) or is_iterable_style_dataset(dataset)):
NameError: name 'is_map_style_dataset' is not defined

shouldn't https://github.com/cli99/DeepSpeed/blob/2f1cd3d3efd7308351786a9e8bd0a0555161f3eb/deepspeed/runtime/engine.py#L864
`if not (is_map_style_dataset(dataset) or is_iterable_style_dataset(dataset)):`
have been
`if not (self.is_map_style_dataset(dataset) or self.is_iterable_style_dataset(dataset)):`

**Comment by cli99** [comment]
@jywu-msft Thanks a lot for pointing this out. It's a typo and I am fixing it in https://github.com/microsoft/DeepSpeed/pull/1032.

**Comment by huanvo88** [comment]
Hello I am using v0.3.16 and still encounter this error. Will this be fixed in the next release? (It has been a while since release 0.3.16)

**Comment by tjruwase** [comment]
@huanvo88, apologies that you are still having this issue. Is it possible to check the master branch for this issue?

**Comment by huanvo88** [comment]
Thanks for the reply. Yes it seems the issue is fixed in the master branch, however not in the latest release, and since I installed using pip I did not have the fix.

**Comment by tjruwase** [comment]
Okay, thanks for confirming that issue is resolved in master branch. We will work on pushing a pip release soon.
