### ISSUE TITLE
Cannot run a test model in notebook

### ISSUE THREAD

**Issue by SuperSpaceEye** [microsoft/DeepSpeed#1030]
I try to use deepspeed in notebook with test model, but it doesn't work.
I use
cuda 11.1
pytorch is 1.8.1
windows

Code:
```
#%%
import torch
import deepspeed
import os
import json
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '9868'
os.environ['RANK'] = "0"
os.environ['LOCAL_RANK'] = "0"
os.environ['WORLD_SIZE'] = "1"
#%%
class NeuralNetwork(torch.nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = torch.nn.Flatten()
        self.out = torch.nn.Sequential(
            torch.nn.Linear(784,10),
            torch.nn.SELU()
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.out(x)
        return logits

test_model = NeuralNetwork()
test_model.cuda()
#%%
torch.distributed.init_process_group(backend="gloo")
#%%
deepspeed.init_distributed("gloo")
device = torch.device("cuda", 0)

#%%

with open("config2.json") as file:
    config = json.load(file)
model_engine, optimizer, _, _ = deepspeed.initialize(model=test_model,
                                                     config_params=config,
                                                     model_parameters=test_model.parameters(),
                                                     dist_init_required=True)
```

Error:
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-10-727186ce21f1> in <module>
      4                                                      config_params=config,
      5                                                      model_parameters=test_model.parameters(),
----> 6                                                      dist_init_required=True)

E:\programs\Anaconda\lib\site-packages\deepspeed\__init__.py in initialize(args, model, optimizer, model_parameters, training_data, lr_scheduler, mpu, dist_init_required, collate_fn, config_params)
    123                                  dist_init_required=dist_init_required,
    124                                  collate_fn=collate_fn,
--> 125                                  config_params=config_params)
    126     else:
    127         assert mpu is None, "mpu must be None with pipeline parallelism"

E:\programs\Anaconda\lib\site-packages\deepspeed\runtime\engine.py in __init__(self, args, model, optimizer, model_parameters, training_data, lr_scheduler, mpu, dist_init_required, collate_fn, config_params, dont_change_device)
    161 
    162         # Configure distributed model
--> 163         self._configure_distributed_model(model)
    164 
    165         see_memory_usage(f"DeepSpeed Engine: After configure distributed model")

E:\programs\Anaconda\lib\site-packages\deepspeed\runtime\engine.py in _configure_distributed_model(self, model)
    592 
    593         if not self.amp_enabled():
--> 594             self._broadcast_model()
    595 
    596     # Configure optimizer

E:\programs\Anaconda\lib\site-packages\deepspeed\runtime\engine.py in _broadcast_model(self)
    568                 dist.broadcast(p,
    569                                self.broadcast_src_rank,
--> 570                                group=self.data_parallel_group)
    571 
    572     def _configure_distributed_model(self, model):

E:\programs\Anaconda\lib\site-packages\torch\distributed\distributed_c10d.py in broadcast(tensor, src, group, async_op)
   1045         return work
   1046     else:
-> 1047         work.wait()
   1048 
   1049 

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.`

Config:
```
{
  "train_batch_size": 1
}
```

What do i do wrong?

**Comment by SuperSpaceEye** [comment]
I just needed to put 
```
test_model.requires_grad_(False)
```
before initializing.

**Comment by SamsTheGreatest** [comment]
Obtaining the same error when trying to train the model with `gloo`

> RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.`

`test_model.requires_grad_(False)` doesn't help as training is needed. Refer to the issue above, mentioned by @stas00 for more details on this.
