### ISSUE TITLE
deepspeed activation checkpointing fails with python 3.8

### ISSUE THREAD

**Issue by g-karthik** [microsoft/DeepSpeed#1057]
High-level (since @tjruwase is familiar with this) repro steps:
- use the following environment: nvcr.io/nvidia/pytorch:21.03-py3, install deepspeed from source and Hugging Face transformers from PyPI
- take the latest Hugging Face transformers code for GPT-2 (`modeling_gpt2.py`), replace `torch.utils.checkpoint` with `deepspeed.checkpointing.checkpoint`
- train any GPT-2 model with deepspeed (but no `partition_activations` etc., just plain checkpointing with `num_checkpoints` = your model's `n_layers`)

Error stack trace:
```
  File "modeling_gpt2.py", line 270, in forward
    outputs = checkpoint(
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 682, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 486, in forward
    outputs = run_function(*inputs_cuda)
  File "modeling_gpt2.py", line 266, in custom_forward
    return module(*inputs, use_cache, output_attentions)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 290, in forward
    attn_outputs = self.attn(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 226, in forward
    query, key, value = self.c_attn(hidden_states).split(self.split_size, dim=2)
  File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 491, in split
    return super(Tensor, self).split(split_size, dim)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
```

With pytorch's checkpointing, this works fine.

Also note that this only happens with python 3.8. I've earlier used deepspeed's checkpointing (default with no activation partitioning etc.) just fine with python 3.6. @tjruwase just a reminder to also take a look at that earlier issue re: activation partitioning not working.

**Comment by g-karthik** [comment]
@tjruwase Could you please help with this? What is the recommended version of python, pytorch and NCCL to use with DeepSpeed? Can I use the above mentioned NGC base image? Clearly DeepSpeed seems to fail with python 3.8 as seen in the above reported experiment.

Also related to this upgrade (and a more severe performance issue that I flagged to @jeffra): https://github.com/microsoft/DeepSpeed/issues/733#issuecomment-837082169 I would be really grateful to get this resolved ASAP, because this is a severe regression in performance with an upgrade.

**Comment by g-karthik** [comment]
@jeffra About the severe regression in `backward_inner` time, I have an update.

It seems to happen only with DeepSpeed versions > v0.3.12. I downgraded to v0.3.12 from the latest DeepSpeed and the `backward_inner` times are so much more reasonable now.

So the gist seems to be that it isn't an NCCL upgrade issue, but rather a DeepSpeed issue.

**Comment by regisss** [comment]
When using activation checkpointing, why returning [here](https://github.com/microsoft/DeepSpeed/blob/2076bf2311c5ce0bcf0e795e94d58e1c5650c6e2/deepspeed/runtime/activation_checkpointing/checkpointing.py#L756) the only element of the list instead of a tuple of length 1?
Having a tuple as the output in any case would ensure consistency of the output type. The current implementation raises an error with Transformers' GPT2 [here](https://github.com/huggingface/transformers/blob/799cea64ac1029d66e9e58f18bc6f47892270723/src/transformers/models/gpt2/modeling_gpt2.py#L900) because it expects a tuple.

I'm happy to open a PR to return a tuple in any case if it makes sense.

**Comment by loadams** [comment]
Hi @g-karthik - is this still an issue, apologies there were no responses before.  If you are still hitting and issue, please open a new issue and link this one and we can prioritize taking a look.

@regisss - if you still believe this is useful, please submit a PR and we will review.  Thanks!
