### ISSUE TITLE
ZeRO Infinity Paper - Question

### ISSUE THREAD

**Issue by sudarshanintel** [microsoft/DeepSpeed#1075]
Hi,
Few Questions on the recent paper- ZeRO-Infinity: Breaking the GPU Memory Wall for Extreme Scale Deep Learning..Tagging few authors of paper, who can help. @ShadenSmith @samyam 

1) This table below was from Paper. For 5T, 10T, 20T model, there is mp=4,4,8. What is mp dimension actually means here? Is this model parallel 4? I presume in this paper, we are running Zero-Stage 3 with Nvme/CPU offload, which is completely data parallel with Optimizer/gradient/parameter split. In Zero Stage3, Parameter of each layer is already split and kept in different nvme blocks and loaded. So not sure what exactly model parallel means, since we have already chopped each layer parameter and bringing them into gpu from different nvme blocks?
![image](https://user-images.githubusercontent.com/39003181/118307853-e28a1c80-b508-11eb-8cb8-00538080bca8.png)

2) nvdia does support gpu direct storage. So what is the reason for loading parameters from nvme to cpu and then to gpu..Why gpu direct storage was not used to load data directly from nvme to gpu memory?

**Comment by tjruwase** [comment]
@sudarshanintel, thanks for your questions. 

1. mp does mean model parallelism. ZeRO stage 3 can be combined with model parallelism for large hidden dimensions (>= 18K) to fit the model or improve performance. 

2. We did not have access to gpu direct storage in our development environment. But we are now exploring it for the obvious performance and implementation benefits.

**Comment by sudarshanintel** [comment]
@tjruwase : 
 In current approach as in paper- each layer is already split (kind of mp here already) and brought into different parts of gpu memory, then we do all gather in fwd pass..Each gpu holds only part of each layer..This is already different from initial Zero-Stage3 implementation when each gpu is responsible for 1 full layer...Not clear to me how is mp applied in infinity with Zero- Satge3. Can you explain the flow little bit more with mp ?..For example with mp-4, are we doing megatron kind of parallelism (tensor slicing?)first and then do Zero-3 within each MP.. (High-level flow would help)

**Comment by tjruwase** [comment]
> For example with mp-4, are we doing megatron kind of parallelism (tensor slicing?)first and then do Zero-3 within each MP.

Yes, this is correct. This form of mp has always being compatible with ZeRO, from stage 1 to infinity.

**Comment by jeffra** [comment]
@sudarshanintel, please re-open if not resolved.
