### ISSUE TITLE
Distilling with DeepSpeed

### ISSUE THREAD

**Issue by StellaAthena** [microsoft/DeepSpeed#1083]
I am interested in using DeepSpeed for distilling, a context in which I need to build multiple models simultaneously. If I naively instantiate two models with DeepSpeed, will that cause problems with how DeepSpeed distributed across GPUs? In particular, would it be best to specify which GPUs each model should be launched on separately?

**Comment by tjruwase** [comment]
If I understand correctly, you intend to use a single deepspeed invocation to instantiate two models simultaneously. If so, it should work but each GPU will have load both models, as you will have number of replicas of each model as number of GPUs (assuming data parallelism alone). Currently, gpu inclusion/exclusion is specified at the launch point. 

You can also take a look at #154 in case it is relevant.
