### ISSUE TITLE
need an API to gather gradients

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#1098]
At the moment it's not possible to gather sharded gradients and some users need to be able to do that as can be seen from:

https://github.com/huggingface/transformers/issues/11850

So a new API, perhaps similar to `GatheredParameters` needs to be added, unless you can think of other ways.

@samyam, @tjruwase 

Tagging the user who requested this feature: @EarthXP

**Comment by pingzhili** [comment]
Does `safe_get_full_grad` meet this need? https://deepspeed.readthedocs.io/en/latest/zero3.html#deepspeed.utils.safe_get_full_grad

**Comment by stas00** [comment]
Indeed, that feature has been fulfilled! Thank you for finding this old PR, @pingzhili

**Comment by pingzhili** [comment]
Google led me to this issue, rather than the deepspeed doc. Hope no one will be as foolish as me, spending an entire afternoon trying to implement a feature that deepspeed already has, lol

**Comment by stas00** [comment]
Yeah, that would be very brave of you!

FWIW, we have been using this feature for about 6 months now - it works great (though it's only good for debug or occasional call during training as it's expensive due to `gather`)

**Comment by pingzhili** [comment]
Yes, many thanks to you all!

By the way, here's a related question about the order of `gathering` gradient and `engine.step`. 

In my zero-1 setting, I find that `safe_get_full_grad` returns the same results before and after the `step`, except for the last accumulation boundary step (where it returns None). However, consider the warning in the document, _for zero1 and zero2, gradient lookup must be called after `backward` and before `step`_. 

So, could I trust the grad returned by `safe_get_full_grad` after `engine.step()`?

(Plus, the reason why I care about this is that I need to do some pruning staff each time after parameter updating, which replies on the gradient info. )

**Comment by stas00** [comment]
My memory is a bit foggy about the details right now, but if I remember correctly we analysed the scopes where we know the grads to be correct and outside of those scopes we either weren't certain or we were certain that the outcome is indeterminate due to many moving parts - as in some unrelated features enabled/disabled.

In other words it's possible that you get the correct grads in a wider scope than the one defined in the doc.

I'm sure that as more users start using this new API it'll be defined better. AFAIK, our m4 team at HF has been the only one using it and we were using it in this scope defined by the doc.
