### ISSUE TITLE
Need a way to shuffle batches from deepspeed trainloader

### ISSUE THREAD

**Issue by byrd106** [microsoft/DeepSpeed#1106]
There doesn't appear to be a way to specify in deepspeed config or function arguments, a way to shuffle batches from training loader that deepspeed initialize returns.

**Comment by tjruwase** [comment]
@byrd106, this is correct and sorry for that inconvenience. Unfortunately, we have not spent much time on the data loader. However, you don't need to pass a dataloader to deepspeed, and so you can use your favorite dataloader.

**Comment by tjruwase** [comment]
@byrd106, is this still an issue, or is it okay to close?
