### ISSUE TITLE
Does ZeRO-3 work with torch.optim.Adam?

### ISSUE THREAD

**Issue by vasudevgupta7** [microsoft/DeepSpeed#1108]
Hey,

Does DeepSpeed ZeRO stage-3 work with `torch.optim.Adam`?

When I am using `deepspeed.ops.adam.DeepCPUAdam` with offloading optimizer states, my code works perfectly. But when I use torch.optim.Adam, I get some error saying beta2 referenced before initialising.

Thanks!

**Comment by stas00** [comment]
when reporting Issues please always provide:
1. the full backtrace . 
2. the environment details 

But I think I know what you're talking about, please see:
https://github.com/pytorch/pytorch/issues/55740

This is a refactoring bug in pytorch-1.8.1

Do you still have the problem if you use pt-1.8.0?

**Comment by vasudevgupta7** [comment]
@stas00, thank you so much for the reply. It's working perfectly when working with torch-1.7.1.

**Comment by stas00** [comment]
awesome! 

pt-1.9.0 should be out shortly as well.
