### ISSUE TITLE
Inference transformer issue with sequence length >1024

### ISSUE THREAD

**Issue by opherlieber** [microsoft/DeepSpeed#1125]
Hi,

I'm trying to use DeepSpeedTransformerInference, and am getting the following error whenever the sequence length is higher than 1024:
RuntimeError: CUDA error: too many resources requested for launch

For sequence lengths up to 1024 it works great, including with much larger batch sizes.

This is some minimal code which reproduces the error:

```
import torch
from deepspeed.ops.transformer.inference.transformer_inference import DeepSpeedInferenceConfig, DeepSpeedTransformerInference

hidden = 512
batch = 1
seqlen = 2048

config = DeepSpeedInferenceConfig(
    hidden_size=hidden,
    heads=32,
    fp16=True,
    num_hidden_layers=8)

layers = [DeepSpeedTransformerInference(config).half().cuda().requires_grad_(False) for i in range(8)]

inputs = torch.rand([batch, seqlen, hidden], device="cuda", dtype=torch.half)
input_mask = torch.ones([batch, seqlen], device="cuda", dtype=torch.half)
x = inputs
for i, layer in enumerate(layers):
    print(i)
    x = layer(x, input_mask=input_mask)

```

Thanks

**Comment by RezaYazdaniAminabadi** [comment]
Hi @opherlieber 

Thanks for reporting this.
I will work on this to solve the issue soon. By the way, can you tell me what model architecture is this for? I see you are just creating the layers on your own with some random dimensions, or is it related to some model specification?
Thanks,
Reza

**Comment by opherlieber** [comment]
Thanks a lot for the support!
The dimensions here are just for the example, I have various architectures I'd like to try and apply this too.

Can you also maybe give some info about the 'specialized_mode' ? It looks like it fuses/optimizes the ops for the case of decoding with past K/V values, but It seems I'm missing the 'InferenceSpecializedBuilder' to get it enabled. Is there any plan to release this, and do you have any numbers about how much it helps?

Thanks

**Comment by RezaYazdaniAminabadi** [comment]
Hi @opherlieber,

I believe this [PR ](https://github.com/microsoft/DeepSpeed/pull/1114) should fix the issue you were seeing with larger sequence-length.

The specialized kernels are the high-performance version of the inference kernels that fuse the operations at deeper level, such as combining all the attention part in just one kernel as you mentioned (you can find more information in our [inference-blog](https://www.microsoft.com/en-us/research/blog/deepspeed-accelerating-large-scale-model-inference-and-training-via-system-optimizations-and-compression/)). The benefit of performance improvement varies based on network's architectures/dimensions (50% to 2x speedup over the current version of the inference kernels). We are working on a plan to release the code in near future.

Thanks,
Reza

**Comment by opherlieber** [comment]
Works great, thanks!
