### ISSUE TITLE
Init confusion with Zero 3

### ISSUE THREAD

**Issue by Moldoteck** [microsoft/DeepSpeed#1138]
Should I use 
```
with deepspeed.zero.Init():
    model = Dummy()
```
or maybe 

```
model = Dummy()
model,_,_,_=deepspeed.initialize(model=self.model, optimizer=self.optimizer, lr_scheduler=self.scheduler, model_parameters=[{'params': self.model.parameters()}], config='./modules/ds_config.json')
```
or both?
```
with deepspeed.zero.Init():
    model = Dummy()
    model,_,_,_=deepspeed.initialize(model=self.model, optimizer=self.optimizer, lr_scheduler=self.scheduler, model_parameters=[{'params': self.model.parameters()}], config='./modules/ds_config.json')
```

**Comment by stas00** [comment]
`zero.Init()` context is only used during the instantiation of your model under zero3, therefore:

Under zero3:
```
with deepspeed.zero.Init():
    model = Dummy()

ds_engine,_,_,_=deepspeed.initialize(model=model, ...)
```

Under zero2:

```
model = Dummy()
ds_engine,_,_,_=deepspeed.initialize(model=model, ...)
```

**Comment by Moldoteck** [comment]
> 
> 
> `zero.Init()` context manager is only used during the instantiation of your model under zero3, therefore:
> 
> Under zero3:
> 
> ```
> with deepspeed.zero.Init():
>     model = Dummy()
> 
> ds_engine,_,_,_=deepspeed.initialize(model=model, ...)
> ```
> 
> Under zero2:
> 
> ```
> model = Dummy()
> ds_engine,_,_,_=deepspeed.initialize(model=model, ...)
> ```

Thank you for the clarification!
Taking into the account that cpu_offload will be moved to zero3, that means that i should prefer first option

**Comment by stas00** [comment]
> Taking into the account that cpu_offload will be moved to zero3, that means that i should prefer first option

cpu offloading works in zero2 and zero3, it was just renamed to `offload_optimizer` in zero2 to match zero3. Please see examples of both side by side:

* https://github.com/huggingface/transformers/blob/master/tests/deepspeed/ds_config_zero2.json
* https://github.com/huggingface/transformers/blob/master/tests/deepspeed/ds_config_zero3.json

**Comment by Moldoteck** [comment]
Thank you for insights
