### ISSUE TITLE
[Question]: Does DeepSpeed only for GPU clusters?

### ISSUE THREAD

**Issue by dclong** [microsoft/DeepSpeed#114]
Does DeepSpeed also work for a cluster of VMs without GPUs?

**Comment by ShadenSmith** [comment]
Hello! Thank you for your interest in DeepSpeed.

DeepSpeed is GPU-only at this time. However, more generality is on our roadmap: https://github.com/microsoft/DeepSpeed/issues/89 . Pull requests always are welcome!

**Comment by dclong** [comment]
@ShadenSmith Thank you very much for the information!
