### ISSUE TITLE
 'NoneType' object has no attribute 'opt'

### ISSUE THREAD

**Issue by AngThanos** [microsoft/DeepSpeed#1153]
Hi there, I'm trying to use DeepSpeed and sparse_self_attention.py but I encountered the error as shown in the attached image. It also gives the error: CUDA: Error- invalid ptx.

Please help me fix that. Thanks. 

![1111111111111111111111](https://user-images.githubusercontent.com/41022754/121510239-9ea80b80-ca11-11eb-92b4-5473e46e0c85.PNG)

**Comment by AngThanos** [comment]
It sometimes also triggers an error: No module named 'sparse_attn' as shown in the picture below. 
Please help me with this error. My gcc version is 7.5.0 and I use google colab.
![Uploading 123123.PNG…]()

**Comment by RezaYazdaniAminabadi** [comment]
Hi @AngThanos 

Can you show me the ds_report results?
Thanks,
Reza

**Comment by AngThanos** [comment]
Dear Reza,

this is my ds_report. Thanks.
![sample](https://user-images.githubusercontent.com/41022754/121609750-bbc6f380-ca7e-11eb-985e-185afdbd9440.PNG)

**Comment by RezaYazdaniAminabadi** [comment]
Thanks for running this. 
Can you please reinstall the torch to have the same cuda version as the nvcc?

**Comment by AngThanos** [comment]
I've installed the same version for the torch cuda and nvcc version. However, after loading sparse_attn, the program still stuck at error CUDA: Error- invalid ptx as shown in the txt file.
![1](https://user-images.githubusercontent.com/41022754/121662867-045acd00-cad0-11eb-9bac-8505edbddd9f.PNG)
[New Text Document (3).txt](https://github.com/microsoft/DeepSpeed/files/6637235/New.Text.Document.3.txt)

**Comment by AngThanos** [comment]
I figured out that DeepSpeed can not load sparse_attn on P100 GPUs of google colab. This module can successfully load on Tesla V100 of google colab instead.
