### ISSUE TITLE
Errors on inference tutorial

### ISSUE THREAD

**Issue by hyunwoongko** [microsoft/DeepSpeed#1158]
I ran the example in the tutorial [here](https://www.deepspeed.ai/tutorials/inference-tutorial/), but I get an error. 
![image](https://user-images.githubusercontent.com/38183241/121793052-659cb080-cc36-11eb-9ba7-821852400428.png)

First of all, if `dist.init_process_group("nccl", rank=local_rank, world_size=world_size)` was not set, 
an error occurred. So I added this line, and this bug has been fixed. Now with below code it works fine on single GPU.

```python
# Filename: gpt-neo-2.7b-generation.py
import os
import deepspeed
import torch
import torch.distributed as dist
import transformers
from transformers import pipeline

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

dist.init_process_group("nccl", rank=local_rank, world_size=world_size)
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B', device=local_rank)

deepspeed.init_inference(generator.model,
                         mp_size=world_size,
                         dtype=torch.float,
                         replace_method='auto')

string = generator("DeepSpeed is", num_beams=5, repeation_penalty=2.0, no_repeat_ngram_size=4,  min_length=50)
if torch.distributed.get_rank() == 0:
    print(string)
```

![image](https://user-images.githubusercontent.com/38183241/121793108-d643cd00-cc36-11eb-8109-cb5190c92936.png)

However, when I try the same thing in multi-GPU, the following error occurs. What's the problem?

![image](https://user-images.githubusercontent.com/38183241/121793117-f1aed800-cc36-11eb-9732-95f923f75fcd.png)

**Comment by RezaYazdaniAminabadi** [comment]
Hi @hyunwoongko 

Thanks for trying this out and reporting the issue. I will update the inference tutorial to fix this issue.
Meanwhile, could you please try our example [here](https://github.com/microsoft/DeepSpeedExamples/blob/25d73cf73fb3dc66faefa141b7319526555be9fc/inference/huggingface/gpt-neo.py)?  I have tried it out on 2 gpus and it runs fine on my side:
![image](https://user-images.githubusercontent.com/44502768/121939947-70247c00-cd02-11eb-8450-bfdf4c57abc2.png)

Thanks,
Reza

**Comment by hyunwoongko** [comment]
I corrected the mistakes in the tutorial document correctly and PR.

https://github.com/microsoft/DeepSpeed/pull/1157

Thanks !

**Comment by RezaYazdaniAminabadi** [comment]
Thanks @hyunwoongko.
I will review the PR and merge it soon 👍
