### ISSUE TITLE
zero_to_fp32.py seems exporting a wrong model

### ISSUE THREAD

**Issue by BitVoyage** [microsoft/DeepSpeed#1165]
Zero Stage 2
**a** loads exported FP32 model
**b** loads 'mp_rank_00_model_states.pt'
states of a and b is ** entirely different**
![image](https://user-images.githubusercontent.com/10386094/122274612-50b16d00-cf15-11eb-80d0-40ad0a6f590a.png)

Only **embeddings** is near
![image](https://user-images.githubusercontent.com/10386094/122275426-417eef00-cf16-11eb-88ef-823db738656b.png)

I try to finetune model, **b** model works and **a** model seems like scratch

**Comment by mpjlu** [comment]
@tjruwase, we also find the same problem.

**Comment by tjruwase** [comment]
@BitVoyage and @mpjlu, thanks for reporting this issue. Apologies for the late response. 

I can take a closer look next week. Can you please share a bit more details to repro on my side? Thanks!

@stas00, for awareness.

**Comment by mpjlu** [comment]
I tested on DeepSpeed version v0.4.0, cuda 10.2, and pytorch 1.8.1 
you can train a model with zero 1 or 2, then using  zero_to_fp32.py in the checkpoint folder to get  FP32 weight.
The FP16 weight can load from 'mp_rank_00_model_states.pt', 
Then compare the value of the same Tensor.
Thanks @tjruwase

**Comment by stas00** [comment]
Please retest with `deepspeed=0.4.3` - as some problems were fixed in `zero_to_fp32.py` in the latest version. Thank you!

**Comment by BitVoyage** [comment]
@stas00 still got wrong model weights
![image](https://user-images.githubusercontent.com/10386094/126098428-98c7a112-4105-45d5-a091-561889eed2c3.png)
My deepspeed config is:
![image](https://user-images.githubusercontent.com/10386094/126098477-6267e6dd-c611-4bf3-9a50-c982f5f11c8c.png)

**Comment by stas00** [comment]
Thank you for retesting with the latest deepspeed, @BitVoyage. I will write some more detailed tests and get back to you.

**Comment by stas00** [comment]
I confirm that zero2 fp32 recovery is broken in the latest deepspeed, 

Zero3 works fine.

I will work on fixing it and writing better tests.

**Comment by stas00** [comment]
Please verify that things work with https://github.com/microsoft/DeepSpeed/pull/1240

You will need to re-create the checkpoint anew for the test.

**Comment by xycforgithub** [comment]
Hi there,
I'm experiencing the same problem on Deepspeed 0.4.5 (after the above fix). Has the problem been solved?
Loading  'mp_rank_00_model_states.pt':
>>> states['module']['deberta.encoder.layer.0.output.dense.weight']
tensor([[-0.0211,  0.0068,  0.0206,  ...,  0.0057,  0.0316,  0.0256],
        [ 0.0273,  0.0141,  0.0118,  ..., -0.0122,  0.0054,  0.0010],
        [ 0.0479, -0.0237, -0.0604,  ..., -0.0340, -0.0183,  0.0691],
        ...,
        [ 0.0270, -0.0231,  0.0218,  ...,  0.0563,  0.0641, -0.0094],
        [-0.0563, -0.0837, -0.0427,  ...,  0.0242, -0.0132, -0.0512],
        [-0.0012,  0.0064,  0.0465,  ...,  0.0219,  0.0259, -0.0281]],
       device='cuda:0', dtype=torch.float16)

Loading the exported weights:
(Pdb) self.deberta.encoder.layer[0].output.dense.weight
Parameter containing:
tensor([[ 0.0207, -0.0448,  0.0022,  ...,  0.0406, -0.0338, -0.0174],
        [-0.0577, -0.0648,  0.0404,  ...,  0.0108, -0.0167, -0.0100],
        [ 0.0548,  0.0063,  0.0024,  ...,  0.0311,  0.0249,  0.0167],
        ...,
        [-0.0081,  0.0194, -0.0266,  ..., -0.0269, -0.0002,  0.0257],
        [ 0.0202, -0.0002,  0.0831,  ..., -0.0008, -0.0094,  0.0258],
        [-0.0320,  0.0529, -0.0259,  ...,  0.0117, -0.0292, -0.0064]],
       device='cuda:0', dtype=torch.float16, requires_grad=True)
