### ISSUE TITLE
Deployment using Deepspeed Inference

### ISSUE THREAD

**Issue by hyunwoongko** [microsoft/DeepSpeed#1175]
Hello. Is there any way to use inference engine and a web server application like Flask together?

**Comment by hyunwoongko** [comment]
When I experimented, I could start the server by setting the port of each rank differently, but inference does not work.

**Comment by hyunwoongko** [comment]
![ezgif-7-bad264dc8ea2](https://user-images.githubusercontent.com/38183241/122672184-2c9ba780-d205-11eb-8ac1-65243cbc9ba8.gif)

I implemented it myself over the weekend. I solved it through simple mutex handling and changing deepspeed.launch.runner from sub-process-based to multi-process-based. I will close the issue.

**Comment by LinglingGreat** [comment]
Hello, I'm interested in it. Can you explain how you did it? Thanks.

**Comment by hyunwoongko** [comment]
I released it https://github.com/tunib-ai/parallelformers .

**Comment by tohtana** [comment]
@LinglingGreat @hyunwoongko 

As posted on #1669, we are developing a new feature to access DeepSpeed Inference engine via RESTful APIs and just submitted a [PR](https://github.com/microsoft/DeepSpeed-MII/pull/154). The feature is a part of [DeepSpeed-MII](https://github.com/microsoft/DeepSpeed).

Please feel free to try it and join the discussion.
