### ISSUE TITLE
TypeError: FP16_DeepSpeedZeroOptimizer is not an Optimizer

### ISSUE THREAD

**Issue by Colanim** [microsoft/DeepSpeed#118]
I'm trying to use 1-Cycle scheduler, but I meet the following error :

> TypeError: FP16_DeepSpeedZeroOptimizer is not an Optimizer

---

Here is my configuration file :

```
{
    "train_batch_size": 64,
    "train_micro_batch_size_per_gpu": 1,
    "gradient_accumulation_steps": 16,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 3e-05,
            "betas": [
                0.9,
                0.999
            ],
            "eps": 1e-8,
            "weight_decay": 0.01
        }
    },
    "gradient_clipping": 0.1,
    "scheduler": {
        "type": "OneCycle",
        "params": {
            "cycle_first_step_size": 16000,
            "cycle_first_stair_count": 8000,
            "decay_step_size": 16000,
            "cycle_min_lr": 1e-06,
            "cycle_max_lr": 3e-05,
            "decay_lr_rate": 1e-07,
            "cycle_min_mom": 0.85,
            "cycle_max_mom": 0.99,
            "decay_mom_rate": 0.0
        }
    },
    "zero_optimization": true,
    "disable_allgather": true,
    "fp16": {
        "enabled": true,
        "loss_scale": 0,
        "min_loss_scale": 1
    }
}
```

When using another Scheduler (with FP16), I meet no problem.

**Comment by jeffra** [comment]
Thanks for reporting this bug. We will take a look at this as soon as possible. I just created two test cases that reproduce the error (one with ZeRO and one with FP16 but no ZeRO).

https://github.com/microsoft/DeepSpeed/blob/jeffra/onecycle_bug/tests/unit/test_fp16.py#L147-L246

**Comment by Colanim** [comment]
Note : I have the same error when I try the same configuration and `LRRangeTest` as scheduler.

**Comment by Colanim** [comment]
I'm still meeting this issue in `deepspeed/deepspeed:latest`. How should I update the docker image to pull latest code from source ?

**Comment by jeffra** [comment]
Hmm, it should be updated. Can you tell us this info from inside your docker container?

`python -c 'import deepspeed; print("deepspeed info:", deepspeed.__version__, deepspeed.__git_branch__, deepspeed.__git_hash__)'`

**Comment by Colanim** [comment]
My bad, I didn't pull the latest image..

After doing `docker pull deepspeed/deepspeed:latest`, it's working 👍
