### ISSUE TITLE
DeepSpeed hangs when used with transformers

### ISSUE THREAD

**Issue by SamsTheGreatest** [microsoft/DeepSpeed#1182]
When GPTNeoForCausalLM to fine-tune GPTNeoForCausalLM, transformers.TrainingArguments is being used, where deepspeed is specified. I am attempting to replicate [this](https://github.com/dredwardhyde/gpt-neo-fine-tuning-example.git). When running transformers.TrainingArguments we get:

`[2021-06-24 06:40:34,408] [INFO] [distributed.py:47:init_distributed] Initializing torch distributed with backend: nccl`

Then running transformers.Trainer **gets stuck** at:
`[2021-06-24 06:40:39,103] [INFO] [logging.py:60:log_dist] [Rank 0] DeepSpeed info: version=0.3.13, git-hash=unknown, git-branch=unknown
[2021-06-24 06:40:39,118] [INFO] [engine.py:77:_initialize_parameter_parallel_groups] data_parallel_size: 1, parameter_parallel_size: 1`

Information about versions:
```gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

Cuda compilation tools, release 10.1, V10.1.243



ds_report
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires one of the following commands '['llvm-config', 'llvm-config-9']', but it does not exist!
 [WARNING]  sparse_attn requires the 'cmake' command, but it does not exist!
 [WARNING]  sparse_attn requires CUDA version 10.1+, does not currently support >=11 or <10.1
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/jovyan/anaconda3/envs/esemala/lib/python3.7/site-packages/torch']
torch version .................... 1.8.1+cu111
torch cuda version ............... 11.1
nvcc version ..................... 10.1
deepspeed install path ........... ['/home/jovyan/anaconda3/envs/esemala/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.3.13, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.7, cuda 10.1

```

Is it possible to find the source of the problem?

**Comment by tjruwase** [comment]
@SamsTheGreatest, are you still having this issue?

**Comment by loadams** [comment]
Hi @SamsTheGreatest - this should be resolved in later versions of DeepSpeed and transformers.  If you are still having this issue, please re-open this issue and let us know a repro case with both DeepSpeed and transformers versions and we would be happy to take a look.
