### ISSUE TITLE
Question about bucket

### ISSUE THREAD

**Issue by huangyanjuner** [microsoft/DeepSpeed#1186]
Hello, I am reading the zero2.py code. I learned from DDP's paper that the bucketing strategy pays much attention to the gradient reducing order. As you known, the reducing order must be the same across all processes, otherwise, AllReduce contents might mismatch, resulting in incorrect reduction result or coredump. However, Autograd engine is a parallel graph execution engine, which would cause different gradients ready order among processes. DDP leverages Parameter-to-Bucket Mapping, index inside Bucket and index between Buckets together to maker sure the strict order when "AllReduce". As DeepSpeed, I am wandering how it works to handle the bucket? Thanks a lot.

**Comment by samyam** [comment]
@huangyanjuner The gradient order is different across processes only if the forward graph is different across process. AutoGrad computes the gradients in a sequential and deterministic order as long as the training is strictly data parallel, ie. all process take the exact same code path. In this scenario, the gradient order will be consistent. This is the underlying assumption in DeepSpeed ZeRO-2.  We do not currently support cases where two different data parallel process are taking different code paths in ZeRO-2 as we have not seen cases where this is necessary for multi-billion parameter training enabled by ZeRO-2. Please do let us know if you have scenarios where this is necessary.

**Comment by jeffra** [comment]
@huangyanjuner, please re-open if not resolved.
