### ISSUE TITLE
Install fails on Windows

### ISSUE THREAD

**Issue by jfb54** [microsoft/DeepSpeed#1189]
Using PyTorch 1.9, Cuda 11.1, Windows 10, Python 3.6.7

(venv) E:\>pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.4.1.tar.gz (445 kB)
    ERROR: Command errored out with exit status 1:
     command: 'e:\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-c2ug4_ge\\deepspeed_eb7683ca68d140f88cf1945a64a53ac6\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-c2ug4_ge\\deepspeed_eb7683ca68d140f88cf1945a64a53ac6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-lqik7o82'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-c2ug4_ge\deepspeed_eb7683ca68d140f88cf1945a64a53ac6\
    Complete output (12 lines):
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-c2ug4_ge\deepspeed_eb7683ca68d140f88cf1945a64a53ac6\setup.py", line 158, in <module>
        create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
      File "C:\Users\User\AppData\Local\Temp\pip-install-c2ug4_ge\deepspeed_eb7683ca68d140f88cf1945a64a53ac6\setup.py", line 150, in create_dir_symlink
        os.remove(dest)
    PermissionError: [WinError 5] Access is denied: '.\\deepspeed\\ops\\csrc'
    DS_BUILD_OPS=1
     [WARNING]  async_io requires the libraries: ['libaio-dev'] but are missing. Can be fixed by: `apt install libaio-dev`.
     [WARNING]  async_io requires the libraries: ['libaio-dev'] but are missing. Can be fixed by: `apt install libaio-dev`.
    Install Ops={'cpu_adam': False, 'fused_adam': 1, 'fused_lamb': 1, 'sparse_attn': 1, 'transformer': 1, 'stochastic_transformer': 1, 'async_io': False, 'transformer_inference': 1, 'utils': 1, 'quantizer': 1}
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kuznetsoffandrey** [comment]
The same problem with me. Did you find solution?

**Comment by jfb54** [comment]
I didn't find a solution. The only workaround I found was to use Linux (which does install fine). However, I prefer to debug my code locally on a Windows machine before sending it off to a GPU cluster.

**Comment by dannyfriar** [comment]
Same problem here on Windows 10

**Comment by garrethcline** [comment]
I am also getting the same problem on windows 10

**Comment by dnyari** [comment]
Same here, on Windows 10. Is there any update on this?

**Comment by ikcikoR** [comment]
Same issue, also Windows 10

**Comment by mrwyattii** [comment]
We are working on updating our installation. A common problem we found is that users on Windows that did not use administrative privilege when building would run into issues with the symlinks. We are working on removing the symlinks (along with other improvements): #4323 

If you are still seeing this error, we highly recommend running on WSL instead of the base Windows OS.

**Comment by FurkanGozukara** [comment]
> We are working on updating our installation. A common problem we found is that users on Windows that did not use administrative privilege when building would run into issues with the symlinks. We are working on removing the symlinks (along with other improvements): #4323
> 
> If you are still seeing this error, we highly recommend running on WSL instead of the base Windows OS.

It is ironic that Microsoft is Windows developer and we still can't install on Windows

![image](https://github.com/microsoft/DeepSpeed/assets/19240467/4e19d513-1571-4bbc-8783-313b9072926a)

**Comment by MontyFlange** [comment]
what does WSL mean ?

**Comment by mrwyattii** [comment]
> what does WSL mean ?

WSL is Windows Subsystem for Linux: https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by jomayeri** [comment]
Please check out the latest version of DeepSpeed for Windows compatibility.
