### ISSUE TITLE
README : Missing list of supported Schedulers

### ISSUE THREAD

**Issue by Colanim** [microsoft/DeepSpeed#119]
In the README about JSON configuration, the list of supported Schedulers is missing :

https://github.com/microsoft/DeepSpeed/blob/master/docs/config_json.md#scheduler-parameters

Currently, only 3 schedulers are supported, right ?

From : https://microsoft.github.io/DeepSpeed/docs/htmlfiles/api/full/pt/deepspeed_lr_schedules.m.html

* `LRRangeTest`
* `OneCycle`
* `WarmupLR`

**Comment by tjruwase** [comment]
Thanks for catching this missing list. 

If possible, can you submit a pull request?
