### ISSUE TITLE
One-Bit Adam is not compatible with Zero 2?

### ISSUE THREAD

**Issue by BitVoyage** [microsoft/DeepSpeed#1197]
One-Bit Adam with Zero 1 works fine
But Zero2 run error:
`File "/data/miniconda3/envs/env-3.6.8/lib/python3.6/site-packages/deepspeed/runtime/zero/stage2.py", line 1570, in has_overflow_partitioned_grads_serial`
`File "/data/miniconda3/envs/env-3.6.8/lib/python3.6/site-packages/deepspeed/runtime/zero/stage2.py", line 1577, in has_overflow`
 `for j, grad in enumerate(self.averaged_gradients[i]):`
 ` TypeError: 'NoneType' object is not iterable`

**Comment by jeffra** [comment]
We don’t have full support for composing 1-bit with zero-*. Zero 2 which partitions gradients especially would have difficulties here since 1-bit handles gradients in a different way than zero.

**Comment by ParamsRaman** [comment]
@jeffra adding to this.. I am curious to know if 1-bit + zero-* support is in your work plan? if so any estimate of the timeline (weeks, months?) Also curious to know how much of an effort it is to enable this? Thanks,

**Comment by loadams** [comment]
Closing this issue as it is stale.
