### ISSUE TITLE
deepspeed_light.py bug: 'global_step' should be 'global_steps' in _load_checkpoint()

### ISSUE THREAD

**Issue by LiweiPeng** [microsoft/DeepSpeed#120]
In the following line, it seems to me that 'global_step' should be 'global_steps'. If so, can you fix it?

https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/pt/deepspeed_light.py#L983

deepspeed_states = [
            'module',
            'optimizer',
            'csr_tensor_module_names',
            'skipped_steps',
            'global_step'
        ]

**Comment by ShadenSmith** [comment]
Thanks for the bug report! I just submitted a PR.

**Comment by tjruwase** [comment]
@ShadenSmith can we close this issue?

**Comment by ShadenSmith** [comment]
Ah sorry, not yet. There's a working PR that's missing unit tests. I'll get back to it ASAP.
