### ISSUE TITLE
Can the cuda kernels be used for GPT like models?

### ISSUE THREAD

**Issue by ghosthamlet** [microsoft/DeepSpeed#1200]
I just saw dense transformer kernels and Sparse attentions was used in Bert model, can they be used for GPT like models?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @ghosthamlet 

Yes, they can be both used in the GPT-based models. We are working on preparing an example for this soon.

Thanks,
Reza

**Comment by ghosthamlet** [comment]
Thanks.

**Comment by benathi** [comment]
Any updates on examples of GPT-based models with sparse attention kernels? :)
