### ISSUE TITLE
Model with ZeRO-1 converges worse than model without ZeRO-1 

### ISSUE THREAD

**Issue by MichaelEk** [microsoft/DeepSpeed#1217]
![Screenshot from 2021-07-12 12-45-29](https://user-images.githubusercontent.com/1654957/125267033-17e79680-e30f-11eb-81a8-dca0564b14bc.png)

This result was obtained when training Megatron LM from the examples.

Here is DS configuration:
`
{
    "train_batch_size": 32,
    "train_micro_batch_size_per_gpu":1,
    "steps_per_print":10,
    "prescale_gradients":false,
    "gradient_clipping":1.0,
    "wall_clock_breakdown":false,
    "fp16": {
        "enabled":true,
        "loss_scale":0
    },
    "zero_optimization": {
        "stage":1
    },
    "gradient_predivide_factor": 1,
    "zero_allow_untested_optimizer": true
}
`

We use apex Lamb as optimizer.

**Comment by MichaelEk** [comment]
![Screenshot from 2021-07-12 13-41-02](https://user-images.githubusercontent.com/1654957/125274650-d78c1680-e316-11eb-8fd3-86fb533f4a54.png)

Model with ZeRO-1 coverges even worse with Adam

**Comment by MichaelEk** [comment]
Additional moment: we use PipelineModule model, but pp_world_size = 1

**Comment by tjruwase** [comment]
@MichaelEk, thanks for reporting this issue. In general LAMB is not expected to play well with ZeRO. However, your observation is surprising for Adam since it works and is well tested. Can you please check to see if same issue occurs without pipeline?

**Comment by tjruwase** [comment]
@MichaelEk, just wanted to check whether you had any update on this issue?

**Comment by ShadenSmith** [comment]
I wonder if #1263  fixed the issue?

**Comment by MichaelEk** [comment]
No. This fix didn't help. Also it has no effect on ZeRO-1 because of that condition:
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/engine.py#L917

Later I will try to set round_robin_gradients=true from my code

**Comment by MichaelEk** [comment]
Hi! [This PR](https://github.com/microsoft/DeepSpeed/pull/1264) fixes this issue. However, it will not work correctly for non-ZeRO optimizers.
