### ISSUE TITLE
question about how to reproduce BERT Pre-training

### ISSUE THREAD

**Issue by weberxie** [microsoft/DeepSpeed#1226]
Hi team, We are very impressive on your great work, especially about the ZeRO-Infinity!

I was trying to reproduce the BERT Pre-traning especially to enable the ZeRO-Infinity.  But the [tutorial](https://www.deepspeed.ai/tutorials/bert-pretraining/#reproducing-fastest-bert-training-results-with-deepspeed) confused me that, there is no declaration of the preprocesstion. It seems very different from the BERT of DeepLearningExamples. So, anyone can tell me how can I download and preprocess the data, to successfully reproduce the results?

Thanks.

**Comment by tjruwase** [comment]
@weberxie, unfortunately the bing_bert dataset is not publicly available. But there other options, please see [here ](https://github.com/microsoft/DeepSpeedExamples/issues/8) if any work for you.

**Comment by weberxie** [comment]
@tjruwase Thank you for your kind response.
