### ISSUE TITLE
close FP16 in my custom code

### ISSUE THREAD

**Issue by TianhaoFu** [microsoft/DeepSpeed#1228]
Hi , I wonder know can i close FP16 in my custom code? Because I found some code can not run in FP16 like 
```
torch.index_select
```

Thanks

**Comment by tjruwase** [comment]
@TianhaoFu, thanks for using deepspeed. Unfortunately, I don't understand the question. Can you please clarify what you mean by `close`? Can you share a code example that works without deepspeed?

**Comment by tjruwase** [comment]
@TianhaoFu, is this still a problem or can this issue be closed? Thanks!

**Comment by loadams** [comment]
Closing this issue.  Please re-open if you have any additional questions.
