### ISSUE TITLE
DeepSpeed cannot move Tensor on remote server to GPU.

### ISSUE THREAD

**Issue by TriLoo** [microsoft/DeepSpeed#1231]
My hostfile is writen as below:

``` text
localhost slots=8
192.168.10.101 slots=8
```

Then I launch a deepspeed script to run, but the program cannot move tensors to GPU, for example code:

``` python
batch = torch.rand((5, 30))
batch = batch.to(model.device)
```

where `model` is a DeepSpeedEngine. If I use only `localhost` in the hostfile, it can work, but if I include the remote server (`192.168.10.101`) into hostfile, looks like the tensor cannot be moved to GPU  on that server!

update 1: looks like after this [line](https://github.com/microsoft/DeepSpeed/blob/810394636aeee8302c87fa1a5c213d3fb87132dc/deepspeed/runtime/engine.py#L688), tensors cannot be moved to gpu using `to(device)`.

my deepspeed config json:

``` json
{
    "train_micro_batch_size_per_gpu" : 32,
    "gradient_accumulation_steps" : 1,
    "optimizer": {
        "type": "AdamW",
        "params": {
          "lr": 1e-5,
          "eps": 1e-6
        }
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_max_lr": 1e-5,
            "warmup_num_steps": 200,
            "total_num_steps" : 1000
        }
    },
    "fp16": {
        "enabled" : true
    },
    "checkpoint": {
        "tag_validation": "Ignore"
    },
    "zero_optimization": {
        "stage": 0,
        "cpu_offload": false
    },
    "wall_clock_breakdown": false
}

```

my environment:

os: centos 7.6
python: 3.8.5
gcc: 7.3.1
gpu: v100
gpu driver: 455.32.00 
cuda: 11.1
deepspeed: 0.4.3
torch: 1.8.1+cu111

any advices ? thanks

**Comment by tjruwase** [comment]
@TriLoo, sorry, I don't fully understand the problem. 

Can you please share a simple script and command line to reproduce the error?

**Comment by TriLoo** [comment]
> @TriLoo, sorry, I don't fully understand the problem.
> 
> Can you please share a simple script and command line to reproduce the error?

sure, my python scripts is as below:

``` python
# -*- coding: utf-8 -*-

import argparse
import torch
from transformers import BertConfig, BertModel
import deepspeed as ds

def get_model():
    config = BertConfig()
    model = BertModel(config)
    return model


def train(args):
    ds.init_distributed(dist_backend='nccl')
    model = get_model()
    param_optimizer = list(model.named_parameters())
    no_decay = ['bias', 'LayerNorm.bias', 'LayerNorm.weight']
    optimizer_grouped_parameters = [
        {'params': [p for n, p in param_optimizer if
                    not any(nd in n for nd in no_decay)],
        'weight_decay': args.weight_decay},
        {'params': [p for n, p in param_optimizer if
                    any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
    ]
    model, _, _, _ = ds.initialize(args=args, model=model, model_parameters=optimizer_grouped_parameters)
    args.local_rank = model.local_rank
    args.device = model.device
    model.to(args.device)
    batch = torch.rand((3, 30))
    batch = batch.to(args.device)           # <<< stuck here 

    print('Done.')


def parse_args():
    parser = argparse.ArgumentParser(description="bert ds pretrain")
    parser.add_argument('--local_rank', type=int, default=0, help='local rank value')
    parser.add_argument('--weight_decay', type=float, default=0.001, help='weight decay value')
    parser = ds.add_config_arguments(parser)
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    train(args)

if __name__ == '__main__':
    main()
```

this program get struck in `batch.to(args.device)` this line and cannot move to the `print()`.

my launch script is as below:

`
deepspeed --master_port 9996 --hostfile "../ds_configs/hostfile" try_ds2.py --deepspeed --deepspeed_config "../ds_configs/bert.json"
`

where the hostfile content is:

```
localhost slots=8
192.168.10.101 slots=8
```

and bert.json:

```
{
    "train_micro_batch_size_per_gpu" : 32,
    "gradient_accumulation_steps" : 1,
    "optimizer": {
        "type": "AdamW",
        "params": {
          "lr": 1e-5,
          "eps": 1e-6
        }
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_max_lr": 1e-5,
            "warmup_num_steps": 200,
            "total_num_steps" : 1000
        }
    },
    "fp16": {
        "enabled" : true
    },
    "checkpoint": {
        "tag_validation": "Ignore"
    },
    "zero_optimization": {
        "stage": 0,
        "cpu_offload": false
    },
    "wall_clock_breakdown": false
}
```

if there is any unclear, please let me know. thanks

**Comment by tjruwase** [comment]
Thanks for sharing these details. One more question, are you able to do passwordless ssh to `192.168.10.101` from localhost? One way to test this is through this following command:
```bash
PDSH_RCMD_TYPE='ssh' pdsh -w 192.168.10.101 hostname
```

**Comment by TriLoo** [comment]
@tjruwase 
Yes, I can.

I finally find out the reasons which cause the model cannot be broadcasted to other servers. The NCCL environments looks like should be set properly.

Could you add the configs of NCCL used in multi-node multi-gpu training ? thanks.

**Comment by tjruwase** [comment]
Can you check out this [link](https://www.deepspeed.ai/getting-started/#multi-node-environment-variables)?

**Comment by TriLoo** [comment]
got it, thanks.
