### ISSUE TITLE
Question about the ZeRO-Infinity paper

### ISSUE THREAD

**Issue by weberxie** [microsoft/DeepSpeed#1245]
Hi team, I'm reading the ZeRO-Infinity paper in depth. 

I have a question about section 3 - MEMORY REQUIREMENTS, why the optimizer states consist of FP32 gradients? According to my understanding, in the backward process, the gradients are computed in FP16 and are directly used to update the parameters. So why do we need to store gradients in FP32?

Thanks.

**Comment by tjruwase** [comment]
@weberxie, thanks for your question. The answer is that in mixed-precision training, while the model maintains fp16 parameters and gradients, the optimizer computes in fp32 and so maintains fp32 parameters (a.k.a., master weights) and gradients (and first and second moments in the case of Adam). The optimizer computes in fp32 to avoid precision loss, and then updated fp32 parameters are copied into model's fp16 parameters for the next forward pass.

**Comment by weberxie** [comment]
@tjruwase Thanks for your response, I'll verify it with a demo model.

**Comment by Zijie-Tian** [comment]
And I think the CPU cannot calculate the FP16 data type, which is also one reason.
