### ISSUE TITLE
Runtime error when enable memory-centric-tiled-linear

### ISSUE THREAD

**Issue by weberxie** [microsoft/DeepSpeed#1255]
Hi team,

I'm running the [example](https://github.com/microsoft/DeepSpeedExamples/blob/25d73cf73fb3dc66faefa141b7319526555be9fc/Megatron-LM-v1.1.5-ZeRO3/examples/ds_pretrain_gpt2-zero3.sh) on 8 * 40GB A100 Node,

the configurations are 

<img width="653" alt="Screen Shot 2021-07-28 at 8 48 35 PM" src="https://user-images.githubusercontent.com/3942083/127324796-14439be1-f272-4901-9d8e-3d4fbe48bf06.png">

and the stacktrace is

<img width="1226" alt="Screen Shot 2021-07-28 at 8 41 53 PM" src="https://user-images.githubusercontent.com/3942083/127324847-b7e5cb23-9b5e-4ebe-bc95-1cf976abee07.png">

it seems that the args --memory-centric-tiled-linear and --tile-factor are the root cause. So Anyone can help me to fix this problems? Thanks.

**Comment by weberxie** [comment]
Can anyone help me look at this problem? Thanks in advance!

**Comment by tjruwase** [comment]
@weberxie, apologies for the delayed response. I can take a look at this. Can you please confirm that the issue also occurs with 1-gpu run?

**Comment by weberxie** [comment]
@tjruwase Thanks for your response. 

After change the MP_SIZE to 1 and DLTS_NUM_GPU_PER_WORKER to 1, this issue will not occur by it will OOM at optimizer stage at the 2nd step.

**Comment by tjruwase** [comment]
@weberxie, thanks for trying that out. Can you please reduce your model size to get past the OOM. You can cut the number of layers in half for example.

**Comment by weberxie** [comment]
@tjruwase thanks for your advice, it passed the OOM after reduced the model size.

**Comment by weberxie** [comment]
> so does that mean the runtime error does not show with 1-gpu? 

yes.

I'll try 2-GPU and 4-GPU, and shall i set the MP_SIZE according to the number of GPU?

**Comment by weberxie** [comment]
@tjruwase When MP_SIZE is 1, it will run successfully Whether using 2 GPUs or 4 GPUs. but it will throw the same Runtime error when MP_SIZE is 2 and 2 GPUs or MP_SIZE is 4 and 4 GPUs.

**Comment by tjruwase** [comment]
@weberxie, thanks for the providing these data points. It does confirm that the tensor splitting of these flags are responsible. I will take a closer look.

**Comment by tjruwase** [comment]
@weberxie, I am able to repro this issue on my side. Thanks for providing the repro guidance.
