### ISSUE TITLE
Example of One-Step Delayed Parameter Update

### ISSUE THREAD

**Issue by fumihwh** [microsoft/DeepSpeed#1260]
I saw DPU is introduced in [paper](https://arxiv.org/pdf/2101.06840.pdf)
But I can't find any related source code in repo.
Is there any example for using DPU rightly? Thanks.

**Comment by minjiazhang** [comment]
Hi fumihwh,

The DPU code is not committed to the main branch. You can find it here: https://github.com/jren73/delay_param_update.git.

Best,
Minjia

**Comment by fumihwh** [comment]
@minjiazhang Thanks! I'll try it first.

**Comment by taehyunzzz** [comment]
@fumihwh Hi, did you manage to see the parallelization effect of weight update with forward&backward?
