### ISSUE TITLE
Memory bandwidth in paper : what was the method of measuring?

### ISSUE THREAD

**Issue by anijmlt** [microsoft/DeepSpeed#1262]
![image](https://user-images.githubusercontent.com/37815929/127546610-69489f65-4708-4a4f-80bf-5b49ffce86fa.png)
Table 2b in the paper shows the achievable memory bandwidths/GPU when one and multiple GPUs access that memory. What was the method used to measure these numbers?
Also, what leads to the reduction in the bandwidths/GPU shown - specifically CPU memory bandwidth/GPU reduces to 1/4th and NVMe bw to 1/8th that of when one GPU alone accesses these. If there are 16 GPUs why is the reduction not 1/16th?

**Comment by tjruwase** [comment]
@anijmlt, thanks for your question. Please see #1137.

**Comment by anijmlt** [comment]
Thank you. This answers my question.
