### ISSUE TITLE
Support flops profiling for RNN layers with packed input

### ISSUE THREAD

**Issue by karthikradhakrishnan96** [microsoft/DeepSpeed#1268]
Hello,     
 
 We are using deepspeed flops profiler to benchmark some of our models. The profiling works fine for transformer based models, but fails for RNN-based models when packed sequences are used. 
 
 Seems like the rnn flops profiling code (https://github.com/microsoft/DeepSpeed/blob/6ec84967eda5b51d7d80dbbafe623764a0c41773/deepspeed/profiling/flops_profiler/profiler.py#L725) does not account for inputs being packed sequences (Expects input to have shape attribute). Would it be possible to add support for packed sequences? I can help with the implementation if required. 
 
 As far as I can tell, the implementation seems straightforward: if the batch was of lengths [4,3,2], it seems to be doing 2 timesteps with batch size 3, 1 timestep with batch size 2, 1 timestep with batch size 1 => 4+3+2 (https://github.com/pytorch/pytorch/blob/1a93b96815b5c87c92e060a6dca51be93d712d09/aten/src/ATen/native/RNN.cpp#L502)
 
 Thank you!

**Comment by cli99** [comment]
Hi @karthikradhakrishnan96, 
Thank you for bringing up this issue. We should support packed sequences as input to RNN modules. It would be great if you can help with the implementation.

Yes, the "batch_sizes" after packing for the batch data with length[4, 3, 2] would be [3, 3, 2, 1].
