### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by zhihao-chen** [microsoft/DeepSpeed#1270]
Why i set the parameters value was "auto" in config file, the type error will occur?
For example:
`File "run_ner_crf.py", line 518, in <module>
    main()
  File "run_ner_crf.py", line 467, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "run_ner_crf.py", line 174, in train
    model.step()
  File "/data/chenzhihao/.conda/envs/pytorch/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1338, in step
    self._take_model_step(lr_kwargs)
  File "/data/chenzhihao/.conda/envs/pytorch/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1257, in _take_model_step
    if self.gradient_clipping() > 0.0:
TypeError: '>' not supported between instances of 'str' and 'float'
`

**Comment by tjruwase** [comment]
@zhihao-chen, can you please provide more context, such as 
1) Why are you using "auto"? 
2) Are you running with HF?
3) Your ds_config

Thanks!

**Comment by zhihao-chen** [comment]
Thanks for your reply. Yes, i'm running with huggingface, so i refer the configuration file of https://huggingface.co/transformers/main_classes/deepspeed.html.
eg:
{     "fp16": {         "enabled": "auto",         "loss_scale": 0,         "loss_scale_window": 1000,         "initial_scale_power": 16,         "hysteresis": 2,         "min_loss_scale": 1     },     "optimizer": {         "type": "AdamW",         "params": {             "lr": "auto",             "betas": "auto",             "eps": "auto",             "weight_decay": "auto"         }     },     "scheduler": {         "type": "WarmupLR",         "params": {             "warmup_min_lr": "auto",             "warmup_max_lr": "auto",             "warmup_num_steps": "auto"         }     },     "zero_optimization": {         "stage": 3,         "offload_optimizer": {             "device": "cpu",             "pin_memory": true         },         "offload_param": {             "device": "cpu",             "pin_memory": true         },         "overlap_comm": true,         "contiguous_gradients": true,         "sub_group_size": 1e9,         "reduce_bucket_size": "auto",         "stage3_prefetch_bucket_size": "auto",         "stage3_param_persistence_threshold": "auto",         "stage3_max_live_parameters": 1e9,         "stage3_max_reuse_distance": 1e9,         "stage3_gather_fp16_weights_on_model_save": true     },     "gradient_accumulation_steps": "auto",     "gradient_clipping": "auto",     "steps_per_print": 2000,     "train_batch_size": "auto",     "train_micro_batch_size_per_gpu": "auto",     "wall_clock_breakdown": false }




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月3日(星期二) 凌晨2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/DeepSpeed] TypeError: &#39;&gt;&#39; not supported between instances of &#39;str&#39; and &#39;float&#39; (#1270)





 
@zhihao-chen, can you please provide more context, such as
  
Why are you using "auto"?
 
Are you running with HF?
 
Your ds_config
  
Thanks!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tjruwase** [comment]
@zhihao-chen, thanks for sharing the json config. Can you also share the command line to help repro the issue? Thanks.

**Comment by zhihao-chen** [comment]
No problem.&nbsp;
eg:
deepspeed --include localhost:1 run_ner_crf.py \
&nbsp; --deepspeed=$CONFIG_DIR/ds_config.json \
&nbsp; --model_type=bert \
&nbsp; --model_name_or_path=$BERT_BASE_DIR \
&nbsp; --task_name=$TASK_NAME \
&nbsp; --do_train \
&nbsp; --do_eval \
&nbsp; --do_lower_case \
&nbsp; --data_dir=$DATA_DIR/${TASK_NAME}/ \
&nbsp; --train_max_seq_length=512 \
&nbsp; --eval_max_seq_length=512 \
&nbsp; --per_gpu_train_batch_size=32 \
&nbsp; --per_gpu_eval_batch_size=32 \
&nbsp; --learning_rate=3e-5 \
&nbsp; --crf_learning_rate=1e-3 \
&nbsp; --num_train_epochs=30.0 \
&nbsp; --gradient_accumulation_steps=3 \
&nbsp; --logging_steps=500 \
&nbsp; --save_steps=500 \
&nbsp; --output_dir=$OUTPUR_DIR/${TASK_NAME}_output/ \
&nbsp; --overwrite_output_dir \
&nbsp; --seed=42





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月9日(星期一) 晚上10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/DeepSpeed] TypeError: &#39;&gt;&#39; not supported between instances of &#39;str&#39; and &#39;float&#39; (#1270)





 
@zhihao-chen, thanks for sharing the json config. Can you also share the command line to help repro the issue? Thanks.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tjruwase** [comment]
@zhihao-chen, can you please share the value of the variables `$TASK_NAME`, `$DATA_DIR`, and `$BERT_BASE_DIR`?

**Comment by tjruwase** [comment]
Closing for lack of response. Please re-open if needed.

**Comment by w32zhong** [comment]
Same issue, the "auto" is needed to be compatible to HF Trainer.
