### ISSUE TITLE
Is it possible to use ZeRO independently?

### ISSUE THREAD

**Issue by FRAOTIAC** [microsoft/DeepSpeed#1275]
Hi, Thanks for the hardwork. 
I found that deepspeed need to build its own engine, which is inconvenient for users that using other frameworks like  mmdetection. Any chance to use ZeRO independently?

**Comment by tjruwase** [comment]
@FRAOTIAC, thanks for your interest. Unfortunately, using ZeRO independently is not currently possible. But we are thinking along these lines to improve modularity within DeepSpeed, especiallly for components like ZeRO. Can you share more on how you would like to use ZeRO, perhaps there is another way.

**Comment by FRAOTIAC** [comment]
@tjruwase Hi, I've found [ZeroRedundanceOptimizer](https://pytorch.org/tutorials/recipes/zero_redundancy_optimizer.html)  in the pytorch, and says it comes from deepspeed. Looks to have the same function? If that's the case, I think it solves my problem.

**Comment by tjruwase** [comment]
@FRAOTIAC, that seems to be an implementation of the ZeRO stage 1, which partitions optimizer state across the ranks to reduce memory consumption. If that provides sufficient memory savings for your scenario then it would be the best option for you.

**Comment by FRAOTIAC** [comment]
@tjruwase, Thanks for the clarification. Stage 1 is not quite enough in small model and I intended to use stage 2, but the cost to migrate seems too much for me. Hopefully it will be easier to embed in pytorch to use.

**Comment by tjruwase** [comment]
@FRAOTIAC, I see. Sorry I can't help much now. But, please keep us updated on how it goes in case other users later have similar needs.
