### ISSUE TITLE
how does DeepSpeed guarantee the order of tracing on all ranks?

### ISSUE THREAD

**Issue by zarzen** [microsoft/DeepSpeed#1277]
Hi there,

I am wondering how DS guarantees all ranks launch collective communications with the same order?
as far as I know, the hooks injected in the pytorch module are not guaranteed to be triggerred in a determinstic order. 
So I thought tracing procedure on different ranks could result in different order.

**Comment by samyam** [comment]
@zarzen in general if all ranks follow the same code path, all the communication collectives in that code path will also follow the same order. The hooks are just inject collectives at deterministic places in the pre-determined code path. As long as the underlying assumption that all data parallel ranks follow the same code path holds, the hooks will be triggered in deterministically.
