### ISSUE TITLE
[Feature Request] Add a `use_env` flag in the `deepspeed` launcher

### ISSUE THREAD

**Issue by sgugger** [microsoft/DeepSpeed#1291]
PyTorch provides a `--use_env` flag in its dsitributed launcher, and if it's activated, does not pass `--local_rank` to the children processes (it sets it as an environment variable). It would be great if the DeepSpeed launcher could provide the same option so we don't have to manually add this `local_rank` argument to the children processes in existing scripts.

**Comment by tjruwase** [comment]
@sgugger, thanks for sharing this request. It sounds like a very useful feature. We will take a closer look at the pytorch support.

**Comment by stas00** [comment]
fyi, torch-1.9 switched to torch elastic launcher, 
https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py
and deprecated `--use_env` and it'll be removed, see:
https://pytorch.org/elastic/0.2.1/train_script.html

Deprecation note:
https://github.com/pytorch/pytorch/blob/39ec1da935fb475aefe50ed64e8d2aec5ba0c901/torch/distributed/run.py#L25-L27

**Comment by tjruwase** [comment]
@stas00, thanks for sharing this critical information

**Comment by sgugger** [comment]
Yes indeed. Note that `use_env` is deprecated to become `True` (so no `--local_rank` will be passed to the script, only the env variable `LOCAL_RANK`). 

I don't know how DeepSpeed deals with breaking changes, but if you want to stay consistent with the PyTorch launcher, at some point you have to get to removing that `--local_rank` variable passed to the script, since the env variable is properly set. In the short term, having the `--use_env` flag allows me to launch scripts designed for PyTorch and DeepSpeed without adding that `local_rank` in the arguments. If you are interested, I can make a quick PR to add it.

**Comment by stas00** [comment]
@jeffra, could we please revisit this issue as this is a problem for all HF Transformers example scripts.

We are trying to drop support for `--local_rank` since pytorch performs the equivalent of `--use_env` by default since several versions. But we are stuck with needing to accept `--local_rank` because the deepspeed launcher sets it.

We are requesting to either:

1. add `deepspeed --use_env` which will set the env vars and not pass `--local_rank` as this is how pytorch launcher used to do it.
2. add another new command line flag if you prefer that would do the same.

Thank you!

**Comment by jeffra** [comment]
Thanks for bringing this back up @stas00, `--use_env` would be great. I think we actually added support for this in a slightly different flag via this PR: https://github.com/microsoft/DeepSpeed/pull/1690. It adds a few options to our launcher `--no_local_rank` i think would work in your case though.

Side note, I think we need to add launcher documentation to our read-the-docs page (https://deepspeed.readthedocs.io/en/latest/). Currently the only way to discover this flag would be via `deepspeed --help`.

**Comment by sgugger** [comment]
Thanks @jeffra. Just tested locally and it works great with this flag, so closing the issue.
