### ISSUE TITLE
DeepSpeed install in Mac

### ISSUE THREAD

**Issue by g-karthik** [microsoft/DeepSpeed#130]
I was able to successfully install DeepSpeed in my cloud instance.

Additionally, I want to be able to install DeepSpeed in my Mac. This is to ensure that my PyCharm IDE can recognize all the utilities from DeepSpeed when I integrate it into my code. How do I do that? I don't think the installation script is compatible with Macs.

**Comment by jeffra** [comment]
We're currently testing a python-only version of DeepSpeed that disables the cuda/cpp requirements for this case (Lamb and FusedAdam are not supported in this mode). Feel free and give it a try as a preview here: https://github.com/microsoft/DeepSpeed/tree/jeffra/python_only_version

This branch also allows support for installing without any CUDA devices (i.e. cpu_only), one big thing to note though is all fp16 related features do not work in this case since PyTorch does not support fp16 on cpu.

Feel free to give it a try and let us know if it solves your problem or if you run into issues along the way. We are still testing this branch so beware :)

We added a cpu-only [requirements file](https://github.com/microsoft/DeepSpeed/blob/jeffra/python_only_version/requirements_cpu_only.txt). Also you can install DeepSpeed without cuda/cpp support locally on your machine with `./install.sh --python_only`.

**Comment by g-karthik** [comment]
@jeffra I faced a bunch of dependency issues along the way, so it wasn't as simple as just running the `install.sh` from your branch, but I think I managed to resolve them to the point that eventually it seems to have installed.

I'll try to integrate DeepSpeed into my code on my IDE next, and let you know if I face any issues. Thanks!

**Comment by ShadenSmith** [comment]
Hi @g-karthik  that's great that you got DeepSpeed working! Can you share your experience with the dependency issues? If it's something we can reasonably achieve with DeepSpeed, we'd love to make it available on more platforms.

On that topic, it may be easier to install DeepSpeed using `conda`. We are testing out a [conda package](https://anaconda.org/deepspeed/deepspeed) and should update our documentation in the next few days. It requires `pytorch` and some other packages in the `conda-forge` channel, so you may need something like `conda install deepspeed -c deepspeed -c pytorch -c conda-forge`.

If you have the chance to try out the conda installation, we'd love to hear your experience as well.

**Comment by g-karthik** [comment]
`tensorflow-gpu` and `psutil` were causing a lot of trouble, I don't remember what I did to resolve them though, but I vaguely remember doing some kind of downgrade/upgrade of CUDA versions and now I'm getting the error `CUDA driver version is insufficient for CUDA runtime version` whenever I use `fp16` with apex (no DeepSpeed).

**Comment by g-karthik** [comment]
@ShadenSmith so I tried to run the following on my cloud instance to try and re-install DeepSpeed (I suspect I messed up my CUDA runtime + CUDA driver compatibility when trying to install using `install.sh`):

`conda install deepspeed -c deepspeed -c pytorch -c conda-forge `

It just keeps saying `Solving environment: \` and does not proceed further.

**Comment by g-karthik** [comment]
@ShadenSmith did you get a chance to look at this?

Also, what is the recommended CUDA driver and runtime versions to run `install.sh` against?

**Comment by jeffra** [comment]
I'll let Shaden respond to the conda related question. However, I can help answer the driver question. We're currently running Driver Version: 410.104  CUDA Version: 10.0.

If you are running in a cloud environment I would checkout our [azure instructions](https://www.deepspeed.ai/tutorials/azure/) to launch a VM, docker container, etc. If you're not running on azure you should be able to get the NVIDIA NGC 19.11.3 image that is similar to this one https://azuremarketplace.microsoft.com/en-us/marketplace/apps/nvidia.ngc_azure_17_11?tab=Overview on your favorite cloud provider. Once you have that you can get use our docker container to get the right environment setup, see: https://github.com/microsoft/DeepSpeed#installation

**Comment by g-karthik** [comment]
Hey @jeffra thanks for the info!

I just uninstalled apex and deepspeed from my cloud instance, and attempted to do a fresh install. I ran the following command with the latest master branch code: `./install.sh -k` The logs for this installation seemed fine.

However, when I try to run my client script, I get the following error:

```
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 40, in __init__
    fused_adam_cuda = importlib.import_module("fused_adam_cuda")
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

This `libcudart.so.10.2` thing seems to suggest that the version of apex pointed to by the `install.sh` is only compatible with 10.2 -- do you have any ideas on what's going on?

**Comment by ShadenSmith** [comment]
Hi @g-karthik, the latest commit of Apex is not API-compatible with the one we are pointing to. Apex does not use versioning, so we use a submodule pointing to specific commits to enforce that. Catching up with Apex HEAD is a work in progress.

I agree that error suggests that Apex was compiled with 10.2. Were you working from a source directory that you had previously used to build+install? Apex could have reused some build files from that. I'd recommend uninstalling the latest Apex you have, clearing `deepspeed/third_party/apex/{build,dist}`, and installing DeepSpeed with a fresh `./install.sh` to make sure you have the right Apex version.

On the conda issue:

I don't have access to a Mac, so investigation is hard on my end. Do you have a CUDA-enabled PyTorch already installed on that system? PyTorch's website suggests that CUDA is only available on Macs if [installed from source](https://pytorch.org/get-started/locally/). Assuming those are installed and working, you could try to install the remaining prerequisites and see if there are any issues?
```
nvidia-ml-py3
tqdm
psutil
tensorboardx ==1.8
tensorflow-gpu
```
If the DeepSpeed conda installation still hangs after that, the issue must be on our package's end and I'll do some more reading. In the meantime I should tag our existing package as Linux only until we test other platforms.

**Comment by g-karthik** [comment]
@ShadenSmith The conda installation was not working on my Linux-based cloud instance, I didn't try on my Mac.

As for apex - the above error came after I had installed apex as part of DeepSpeed's installer script. I uninstalled apex and DeepSpeed after that, and then 1) installed apex fresh from apex's GitHub, 2) installed DeepSpeed alone fresh using `./install.sh -k -d`.

Doing 1 and 2 seems to have fixed the error. So it looks like DeepSpeed is indeed compatible with the latest apex. But it would be good if you can confirm this.

**Comment by ShadenSmith** [comment]
Just installing DeepSpeed will not test the Apex interfaces, only the ability to import it. Your training will crash on certain code paths.

I believe the error that you're seeing is due to it linking with a version compiled against CUDA toolkit 10.2, which is newer than what you are running on there. You should:

1. Uninstall Apex (you might need `sudo pip -H uninstall apex` if it's from an old DeepSpeed `install.sh`).
2. Ensure the build directories are clean under `DeepSpeed/third_party/apex/{build,dist}/`
3. A fresh `./install.sh` should build you the correct Apex commit with whatever CUDA toolkit that environment has. For PyTorch 1.2 that should be `cudatoolkit=10.0`, and for PyTorch >=1.3 that should be `cudatoolkit=10.1`.

**Comment by g-karthik** [comment]
Right, but what I don't understand is how did 10.2 come into the picture in
the first place? My cloud instance does not have 10.2 at all.

**Comment by ShadenSmith** [comment]
> @ShadenSmith The conda installation was not working on my Linux-based cloud instance, I didn't try on my Mac.

Oh, weird. I've tested that on a few Linux instances. Can you first confirm that you are able to install PyTorch from conda there? That should be `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch` if you haven't before.

**Comment by g-karthik** [comment]
PyTorch comes pre-built in that instance, it's a standard AWS Deep Learning AMI instance, with a packaged conda environment called `pytorch_p36`. I simply activate that environment when needed.

**Comment by g-karthik** [comment]
@jeffra @ShadenSmith 

Can you guys share the current stable command(s) to install DeepSpeed on a Mac/CPU with no CUDA devices? The `python_only_version` branch that you pointed to earlier seems to be deleted now.

Is the conda package you referred to being kept up-to-date with the latest changes in the source?

This is just so I can keep the source on my laptop IDE (I use a virtualenv with PyCharm) pristine and up-to-date with the latest, so I can easily browse new DeepSpeed features/updates/breaking changes and integrate them to my code.

**Comment by ShadenSmith** [comment]
Hi @g-karthik, sorry for the trouble with the missing branch. We must have removed it while cleaning up after the latest release. That branch was way behind, especially after the refactoring in v0.3.

@jeffra has been hard at work on our build system. Can you try installing DeepSpeed like this? `DS_BUILD_CUDA=0 pip install .` 

The build flag is parsed in our `setup.py` to disable building the CUDA extensions. It's a short hop away from enabling FP32 training on the CPU 😊.

We have no Macs available to try ourselves. I imagine you'll run into the dependency issues that you mentioned before (e.g., `psutils`). Any documentation you can provide on that front would be a major help so we can improve the process in the future!

The conda package is not maintained, but that's one of my top priorities now that the pipeline parallelism engine is released.

**Comment by g-karthik** [comment]
@ShadenSmith gotcha, I tried installing by running `DS_BUILD_CUDA=0 ./install.sh -d -k` and it said I needed `cpufeature`. I tried installing that, and it gave me a "duplicate symbol for architecture" error which seems to be a known issue https://github.com/robbmcleod/cpufeature/issues/1 and there's a pending pull request https://github.com/robbmcleod/cpufeature/pull/2 to fix it at the moment.

**Comment by g-karthik** [comment]
@ShadenSmith okay that got fixed, I have the following error when running the above command now:

```
1 location(s) to search for versions of clang-format:
* https://pypi.org/simple/clang-format/
Fetching project page and analyzing links: https://pypi.org/simple/clang-format/
Getting page https://pypi.org/simple/clang-format/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/clang-format/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/clang-format/ HTTP/1.1" 200 701
Updating cache with response from "https://pypi.org/simple/clang-format/"
Caching due to etag
  Skipping link: none of the wheel's tags match: py2-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/e3/71/db01cf5d188d0669af9cfd9f5cf8cfb47898df6ad5c86bc008ab3b73d327/clang_format-6.0.1-py2-none-manylinux1_x86_64.whl#sha256=1b71b62346e281f96aa9d45a8892427ce1eae7783c24ac0e1efbab1d5340748d (from https://pypi.org/simple/clang-format/)
  Skipping link: none of the wheel's tags match: py2-none-manylinux1_x86_64, py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/16/60/65c642879f290c4233ac75d7f91038509750347271cd135a62cf0b86019c/clang_format-6.0.1-py2.py3-none-manylinux1_x86_64.whl#sha256=8028c358d0838e83ea85254bedba846f2106348406c9cdc4f2724779704eedca (from https://pypi.org/simple/clang-format/)
  Skipping link: none of the wheel's tags match: py2-none-manylinux1_x86_64, py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/17/28/feeb87d11c17d4734763db4c0a1a6939448f0c11a1713fac142e8dd2f107/clang_format-7.1.0-py2.py3-none-manylinux1_x86_64.whl#sha256=32629996956b3e34494a926a76835e3371f10c2823c3078f5fbef08bfebbaae7 (from https://pypi.org/simple/clang-format/)
  Skipping link: none of the wheel's tags match: py2-none-manylinux1_x86_64, py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/37/66/75e3c14f22c8a7a02c7e337547e29d42bed516ba8067fdef87d3d9346e52/clang_format-8.0.1-py2.py3-none-manylinux1_x86_64.whl#sha256=d3d0d62281ace883bc6e4188f949308b8f2e4f6de8fac463e5abd1ae02c03db6 (from https://pypi.org/simple/clang-format/)
  Skipping link: none of the wheel's tags match: py2-none-manylinux1_x86_64, py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/25/f2/d989afaf8a91385f18fd06e6202644be0bc3a1d14548c18a8ece4911e005/clang_format-9.0.0-py2.py3-none-manylinux1_x86_64.whl#sha256=085342f9e238c9b03a019e20ec23f242f8795a3cca9296ab2427b1dea45e7014 (from https://pypi.org/simple/clang-format/)
Given no hashes to check 0 links for project 'clang-format': discarding no candidates
ERROR: Could not find a version that satisfies the requirement clang-format (from deepspeed)
ERROR: No matching distribution found for clang-format
```

**Comment by g-karthik** [comment]
@ShadenSmith okay I managed to get the installation working by commenting out `clang-format` from `requirements-dev.txt`. I also explicitly set the torch version in `requirements.txt` to 1.4 (since my virtualenv already had 1.4 and for some reason, the installer was trying to uninstall 1.4 and install 1.2 despite the file saying `>=1.2`) and set tensorboardX to 1.9 (since my virtualenv had 1.9 already, and a quick look through the DeepSpeed source suggests that y'all can bump safely to 1.9 too).

I think you could change the `install.sh` to show different errors when basic tests fail versus when the installation itself fails.

For example, I got the following conflicting error message at the end of the installation:

```
......
......
Successfully installed deepspeed-0.3.0+4fef478 tensorboardX-1.9 torchvision-0.5.0
Removed build tracker: '/private/var/folders/yf/dvfk4pps6ndd5xx1q5fw5mm9ssqdt8/T/pip-req-tracker-jp7hzynz'
Traceback (most recent call last):
  File "basic_install_test.py", line 19, in <module>
    raise err
  File "basic_install_test.py", line 16, in <module>
    import deepspeed
  File "/path/to/my/venv/lib/python3.6/site-packages/deepspeed/__init__.py", line 9, in <module>
    from .runtime.engine import DeepSpeedEngine
  File "/path/to/my/venv/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 10, in <module>
    import apex
ModuleNotFoundError: No module named 'apex'
Error on line 243
Fail to install deepspeed
```

Clearly, deepspeed was installed successfully but it still says failed because the basic install test failed due to unavailability of apex on my Mac.

Also, can you share where exactly the `DS_BUILD_CUDA=0` is being parsed during an execution of `install.sh` with this flag set? Also, I used the `-d` and `-k` flags when running `install.sh`, so why was it trying to uninstall torch 1.4 and install torch 1.2 in the first place? I thought I shouldn't have needed to touch any file in the `/requirements` directory if I used `-d` and `-k`, but in fact I had to in order to get this to install fine.

**Comment by g-karthik** [comment]
@ShadenSmith @jeffra sorry to bombard you with so many questions/observations, but here's one more!

For my GPU jobs, I have always installed DeepSpeed in my Dockerfile like this:
```
# Install DeepSpeed from source
RUN mkdir /tmp/deepspeed && \
    cd /tmp/deepspeed && \
    git clone https://github.com/microsoft/DeepSpeed.git && \
    cd DeepSpeed && \
    ./install.sh -k -r && \
    rm -rf /tmp/deepspeed
```

This has worked for me and my distributed jobs with Kubernetes (where I must note that I do NOT use the `deepspeed` launcher, I use regular python with the `--deepspeed` and `--deepspeed_mpi` flags and let `mpi4py` do the magic as described in one of the docs) in the past. Here's one example from my logs on Sep 12 where DeepSpeed info gets printed at the very start of the job before the MPI settings get "discovered":
```
Sat Sep 12 07:36:30 2020<stdout>:[2020-09-12 07:36:30,796] [INFO] [__init__.py:104:initialize] DeepSpeed info: version=0.3.0+6deac82, git-hash=6deac82, git-branch=master
```

After y'all announced the ZeRO-Offload feature last week, I re-built my Docker image without changing the above RUN command, but I also added the following two lines:

```
# Upgrade pip because DeepSpeed install.sh uses --use-feature arg
RUN pip install --upgrade pip

# Install cpufeature for DeepSpeed
RUN pip install cpufeature
```

When I kick off my train jobs now with this newly built Docker image, the jobs seem to just be stuck and don't even print the DeepSpeed info shown previously like git-hash, etc. Do y'all know what's going on?

My Dockerfile also contains other commands: the one I think may be relevant to the above issue is the installation of OpenMPI 4.0.0. Note that this has worked fine for me with `version=0.3.0+6deac82, git-hash=6deac82`. Do I need a newer version of OpenMPI?
