### ISSUE TITLE
[Kubernetes YAML for multi-node training using PDSH runner]

### ISSUE THREAD

**Issue by Gforky** [microsoft/DeepSpeed#1334]
**Is your feature request related to a problem? Please describe.**

I'm confused about how to write a Kubernetes YAML related to multi-node training using PDSH runner. Since after I read about the implementation of PDSH runner, I noticed that there should be one node to run the pdsh script, so this node should be the initial container in a, for example, PyTorch job cluster? Please correct me if I'm wrong.

**Describe the solution you'd like**

Is there any plan to provide a native runner, that each worker in the cluster run the same script, same we manually run the multi-node PyTorch training using torch.distributed.launcher?
Or maybe there is already some guidance about writing YAML files for all the existed runners?

**Describe alternatives you've considered**

I've found another issue about submitting multi-node training job in Kubernetes using mpirun, which not compatible in my use case.

**Comment by jeffra** [comment]
Hi @Gforky, are you able to launch non-deepspeed jobs with Kubernetes + `torch.distributed.launcher`? If so you should be able to train with deepspeed as well but just not using our launcher. Our launcher is primarily useful in interactive cluster environments where you have direct ssh access to all nodes.

**Comment by Gforky** [comment]
> Hi @Gforky, are you able to launch non-deepspeed jobs with Kubernetes + `torch.distributed.launcher`? If so you should be able to train with deepspeed as well but just not using our launcher. Our launcher is primarily useful in interactive cluster environments where you have direct ssh access to all nodes.

Ok, I see, I was misunderstood that the deepspeed launcher is the pre-request for running deepspeed task. Thanks for your clarification @jeffra
