### ISSUE TITLE
Out of memory problem [BUG]

### ISSUE THREAD

**Issue by MantasLukauskas** [microsoft/DeepSpeed#1342]
Have the problem with Google Cloud Platform VM and DeepSpeed. I am training Hugginface GPT-J model, VM have 120 GB of disk memory and then DeepSpeed try to save the model to another disk it appears to that disk but run out of memory in disk Python installed, I think DeepSpeed caching something to save full model, is it possible to cache it to another disk than installed?

Input/Output error

- GPU: 2xT4
- RAM: 180 GB
- Disk memory 120 GB

**Comment by tjruwase** [comment]
@MantasLukauskas, thanks for reporting this error. Can you clarify if this error occurs during checkpoint saving or during regular training? Can you provide more details, such as the json config, command-line, and log showing error, so that we can try a repro?

**Comment by loadams** [comment]
Closing as this issue is stale.  If you are still hitting this issue, please open a new issue and link this one.  Thanks!
