### ISSUE TITLE
AttributeError: module 'deepspeed' has no attribute 'init_inference'

### ISSUE THREAD

**Issue by bartczernicki** [microsoft/DeepSpeed#1346]
Doing basic inference on a Windows Azure VM with CUDA. Not sure if this is a Windows issue (?)
Deepspeed version 0.3.16   

This code below throws error...
ds_engine = deepspeed.init_inference(model,
                                 mp_size=2,
                                 dtype=torch.half,
                                 checkpoint=None,
                                 replace_method='auto')

The library is installed correctly, but using Intellisence in VSCode...you can't see the init_inference method. What is the issue?

**Comment by bartczernicki** [comment]
I double checked this and this method is on the Linux version of the Python deepspeed package. So, the question is why is this inference not enabled on Windows?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @bartczernicki 

Thanks for mentioning this issue. Can I ask how you install deepspeed on Windows?
We have an instruction [here](https://github.com/microsoft/DeepSpeed/blob/master/README.md) under the installation section. Is this what you've tried?
Thanks,
Reza

**Comment by loadams** [comment]
Hi @bartczernicki - hopefully you were able to work past this, but if you're still having issues with this, could you make a new issue and link this one and we can take a look?  Thanks!

**Comment by TommyTunaToro** [comment]
Did you guys find a solution yet?
