### ISSUE TITLE
[BUG]  Module names GPT2ModelPipe & ParallelTransformerLayerPipe is hardcoded in deepspeed

### ISSUE THREAD

**Issue by DanielHesslow** [microsoft/DeepSpeed#1347]
In multiple places in the deepspeed code there exist hardcoded checks such as:
`if self.module.__class__.__name__ == 'GPT2ModelPipe':`
or 
`all('ParallelTransformerLayerPipe' in f.__class__.__name__ for f in funcs)`
In order to make the examples work.

This means that it is not possible to integrate deepspeed into an existing codebase by looking at the examples or documentation, one needs to thoroughly read the deepspeed code and then name the modules exactly as stated above to get the desired behavior.
To my knowledge this peculiarity is not documented anywhere.

This has been previously noted for checkpointing here: #688 

But it is also necessary in order to send the boolean attention masks across pipeline stages. If one attempts to send the attention masks as described in the tutorial but having the wrong module name, deepspeed will deadlock on the backward pass. I believe this is due to NACL not correctly handing boolean tensor but such workaround should happen in deepspeed, or in the very least there should be warnings. 

This should either be _clearly_ documented, especially in the examples, or better yet, fixed. 

Thanks

**Comment by hyunwoongko** [comment]
I think this is a problem. We need to provide a more flexible API.

**Comment by hyunwoongko** [comment]
https://github.com/microsoft/DeepSpeed/pull/1399 I opened PR.

**Comment by hyunwoongko** [comment]
https://github.com/microsoft/DeepSpeed/pull/139 This PR is merged. could you check?

**Comment by DanielHesslow** [comment]
Thanks, from looking at the code this appear to solve the issue. Though the conversion of boolean tensors is seemingly only done on the last tensor (as that is the attention mask in GPT2ModelPipe). With current implementation I think has_bool_tensor should probably be renamed to last_tensor_is_bool or smth. A perhaps better alternatives is to let the user provide a list of which tensors are boolean.

Unfortunately I don't have the time atm to properly test the fix, I'll close the isssue for now and and I'll reopen it later if there are any remaining problems.

And again, thanks for the quick fix :)
