### ISSUE TITLE
zero optimizer static loss scale is not working

### ISSUE THREAD

**Issue by LiweiPeng** [microsoft/DeepSpeed#138]
the static loss scale in FP16_DeepSpeedZeroOptimizer is not working. One fix is to add at
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/pt/deepspeed_zero_optimizer.py#L188
self.loss_scaler = LossScaler(static_loss_scale) 

Also, change the following line
from deepspeed.pt.loss_scaler import DynamicLossScaler, LossScaler

Can you take a look at this issue? Thanks.

**Comment by ShadenSmith** [comment]
Thanks for catching this and recommending a fix! I submitted a PR to address this bug. Please let me know if you see any issues.
