### ISSUE TITLE
[BUG] get_workspace_size will overflow with long seq_len

### ISSUE THREAD

**Issue by delock** [microsoft/DeepSpeed#1386]
**Describe the bug**
Under seq_len 2048, BS=8, heads=32, get_workspace_size will return negative value in get_workspace_size

**To Reproduce**
In function to compute workspace size, when seq_len =2048, maxBatchSize=8, num of heads=32, in the function below:
https://github.com/microsoft/DeepSpeed/blob/master/csrc/transformer/ds_transformer_cuda.cpp#L22
The value of workSpacesize will overflow and get a negative number

**Expected behavior**
workSpacesize and return value should use size_t to avoid overflow.

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by RezaYazdaniAminabadi** [comment]
Hi @delock,

Thanks for reporting this issue on the transformer kernels. Can I ask what hidden-dimension you are using here?
I will send a PR to fix this issue soon.

Thanks,
Reza

**Comment by delock** [comment]
> Hi @delock,
> 
> Thanks for reporting this issue on the transformer kernels. Can I ask what hidden-dimension you are using here?
> I will send a PR to fix this issue soon.
> 
> Thanks,
> Reza

Hi Reza, hidden dimension I use to reproduce this issue is 3072, thanks!

**Comment by RezaYazdaniAminabadi** [comment]
Hi @delock 

Have you tested this PR with the dimension that you mentioned?
Thanks,
Reza

**Comment by delock** [comment]
Hi Reza, I'll check the PR in my environment this week to see whether the bug had gone away.
Thanks,
Guokai

**Comment by delock** [comment]
> Hi @delock
> 
> Have you tested this PR with the dimension that you mentioned? Thanks, Reza

Yes, with the PR workspace size would not overflow with the hidden size 3072 and batch size 8.   Thanks!
