### ISSUE TITLE
[BUG] Dataloader length is wrong when batch size > 1

### ISSUE THREAD

**Issue by roywei** [microsoft/DeepSpeed#1390]
**Describe the bug**
The dataloader length is set to length of data sampler here: https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/dataloader.py#L71

This is wrong when batch size is > 1
Data loader actual length should be sampler length divided by batch size.

This caused me quite a confusion when debug a training problem when I try to print the number of steps trained.

**To Reproduce**
print the dataset length, data sampler length and data loader length of any training example

**Expected behavior**
Training a model on 2 nodes with 8 GPUs each.
Given 11788 training images, batch size per gpu is 3.
Distributed data sampler should shared the data on 16 gpus, len is 737
when batch size is 3, then data loader length is 246
```
[1,0]<stdout>:data loader len:  246
[1,0]<stdout>:sampler len:  737
[1,0]<stdout>:data set len:  11788
```
**ds_report output**

wrong output:
```
[1,0]<stdout>:data loader len:  737
[1,0]<stdout>:sampler len:  737
[1,0]<stdout>:data set len:  11788
```

I will try to raise a PR soon.
Thanks

**Comment by loadams** [comment]
Closing as stale since the corresponding PR was closed as well.  If folks are still hitting this, please re-open and we can take a look.
