### ISSUE TITLE
[REQUEST] MOE with ZERO stage 3 support 

### ISSUE THREAD

**Issue by cicirori** [microsoft/DeepSpeed#1392]
**Is your feature request related to a problem? Please describe.**
Hi, I'm trying the new MOE feature from deepspeed, but I found that it doesn't work with zero stage 3. I'd like to know what cause them not to work both, and if there are any plans to support in the future. Thanks for your reply!

**Comment by MichaelEk** [comment]
+
Currently, there is no convenient way to train a model with MoE with distributed parameters and optimizer states, except for ZeRO-2+MP. However, MP is worse than ZeRO-3 due to synchronicity.

**Comment by cicirori** [comment]
thanks!
