### ISSUE TITLE
[BUG] error: Unable to pre-compile async_io, when compiling DeepSpeed from source

### ISSUE THREAD

**Issue by chaoyanghe** [microsoft/DeepSpeed#1401]
**Describe the bug**
```
RUN rm -rf ${STAGE_DIR}/DeepSpeed
RUN git clone https://github.com/Distributed-AI/DeepSpeed.git ${STAGE_DIR}/DeepSpeed
##Commit in which the AMI has been build
RUN cd /tmp/DeepSpeed && git checkout master
RUN rm ${STAGE_DIR}/DeepSpeed/requirements/requirements-sparse_attn.txt && touch ${STAGE_DIR}/DeepSpeed/requirements/requirements-sparser_attn.txt
## We have to do this otherwise bdist install Python 1.7
RUN rm ${STAGE_DIR}/DeepSpeed/requirements/requirements.txt && touch ${STAGE_DIR}/DeepSpeed/requirements/requirements.txt
ENV DS_BUILD_OPS=1 
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0"
RUN cd ${STAGE_DIR}/DeepSpeed && sudo DS_BUILD_OPS=1 TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0" pip install -v ./

```

error:
```
Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_xkfovpj/setup.py", line 135, in <module>
        abort(f"Unable to pre-compile {op_name}")
      File "/tmp/pip-req-build-_xkfovpj/setup.py", line 43, in abort
        assert False, msg
    AssertionError: Unable to pre-compile async_io
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
    DS_BUILD_OPS=1
     [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
     [WARNING]  async_io: please install the libaio-dev package with apt
     [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
     [WARNING]  One can disable async_io with DS_BUILD_AIO=0
     [ERROR]  Unable to pre-compile async_io
```

**Comment by tjruwase** [comment]
@chaoyanghe, thanks for reporting this error. 

Can you try installing `libaio-dev`. For example on Ubuntu, you would do `sudo apt install libaio-dev`.

**Comment by tjruwase** [comment]
@chaoyanghe, can you please confirm whether or not the proposed solution worked for you? Thanks.

**Comment by affanmehmood** [comment]
Hey @tjruwase, I found and installed libaio on windows, but this error persists.

**Comment by affanmehmood** [comment]
Thanks for responding @tjruwase. I've opened up this issue for windows. #1769

**Comment by balangate6202** [comment]
python setup.py
Setting ds_accelerator to cuda (auto detect)
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0'
[WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
DS_BUILD_OPS=1
test.c
LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  One can disable async_io with DS_BUILD_AIO=0
 [ERROR]  Unable to pre-compile async_io
