### ISSUE TITLE
[QUESTION] Why do zero and offload have dependencies?

### ISSUE THREAD

**Issue by cicirori** [microsoft/DeepSpeed#1403]
Hi, according to the documentation, turning on optimizer offload requires that zero stage 2 be turned on at the same time, and turning on parameters offload requires zero stage 3. I'd like to know why, because as I understand it offload and zero should be two separate features. thanks for your reply!

**Comment by tjruwase** [comment]
@cicirori, thanks for the question. 

Yes, you are correct that offload and zero are conceptually separate. However, inside DeepSpeed they are dependent in the sense that Offload is built on ZeRO, while ZeRO can run without Offload. It is possible to implement Offload without ZeRO, but that is not the case today in DeepSpeed. Does that help?

**Comment by tjruwase** [comment]
@cicirori, if you don't have additional questions, is it okay to close this issue? Thanks.
