### ISSUE TITLE
[BUG] fp16 weights in model_states.pt does not match fp32 weights extracted using zero_to_fp32.py

### ISSUE THREAD

**Issue by eelxpeng** [microsoft/DeepSpeed#1412]
Hi, after training the checkpoint folder contains one `model_states.pt` file and multiple `optim_states.pt` files. One can use `zero_to_fp32.py` [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/utils/zero_to_fp32.py) to extract fp32 weights from the optim_states.pt files. As I checked when using Zero Stage 2, fp16 weights (the weights in key `module`) in `model_states.pt` does not match fp32 weights extracted using zero_to_fp32.py, not precision different, but very different. @stas00 @tjruwase . 

**Update of the Bug:**
I finally found that the script `zero_to_fp32.py` only works if the parameter groups passed into optimizer has only one param group. If there are two or more parameter groups, the script leads to either `ValueError: consumed 66 numels out of 71 - something is wrong` or the extracted fp32 weights does not match fp16 weights. Further digging into deepspeed stage 2 code [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage2.py#L248), I find that the partitioning of parameters is done in a param group wise manner, i.e. one rank actually gets one slice of all param groups. The script `zero_to_fp32.py` makes the assumption that there is only one param group, hence it introduces bug. To resolve the bug, the script has to take consideration of param groups to correctly reconstruct the fp32 parameters.

Here is a reproduce of the bug:
```
import os
import torch
from torch.utils.data import Dataset, DataLoader
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.plugins import DeepSpeedPlugin
from deepspeed.ops.adam import FusedAdam


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 64), batch_size=2)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)
        return loss

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)
        return loss

    def configure_optimizers(self):
        no_decay = ["bias"]
        params_decay = [
            p for n, p in self.named_parameters() if not any(nd in n for nd in no_decay)
        ]
        params_nodecay = [
            p for n, p in self.named_parameters() if any(nd in n for nd in no_decay)
        ]
        optim_groups = [
            {
                "params": params_decay,
                "weight_decay": 0.01,
            },
            {"params": params_nodecay, "weight_decay": 0.0},
        ]
        return torch.optim.SGD(optim_groups, lr=0.1)
        #return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=4)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=4)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=4)

    model = BoringModel()
    checkpoint_callback = ModelCheckpoint(
        dirpath='tests/checkpoints',
        save_last=True,
        every_n_train_steps=5,
    )
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        gpus=-1,
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        precision=16,
        accelerator='ddp',
        max_epochs=10,
        plugins=[DeepSpeedPlugin(stage=2)],
        weights_summary=None,
        callbacks=[checkpoint_callback],
    )
    trainer.fit(model)
    trainer.test(model, test_dataloaders=test_data)

if __name__ == '__main__':
    run()
```

After the run, use `zero_to_fp32.py` in checkpoint folder to extract the fp32 weights leads to this error `ValueError: consumed 66 numels out of 71 - something is wrong`.

**Comment by stas00** [comment]
It's very hard to do anything with your report since you're not telling us about which setup you are using and how we could reproduce your problem. At the very least you need to specify whether this is ZeRO2 or 3 that you are having the trouble with. and whether you're using the master branch since several bugs were recently fixed.

There is definitely some edge case issue with ZeRO2 at the moment, we are trying to reproduce it which would then can be fixed, but I think ZeRO3 should be working quite well in master.

**Comment by eelxpeng** [comment]
@stas00 Thanks for the reply. I have made detailed modification to the above the bug report. Please see the updated one.

**Comment by stas00** [comment]
Great! That's much better, @eelxpeng 

I just made a fix for taking care of the world_size correctly https://github.com/microsoft/DeepSpeed/pull/1422 but I don't think this is the fix that your situation needs.

It's very likely you're onto something with param groups.

I think all my tests have been with a single param group as you have flagged. So let me try to write another test with multiple param groups so that the problem could be reproduced!

**Comment by stas00** [comment]
Yeah, I changed the test to include param groups and z3 works, but z2 breaks. Great. Much appreciating your input. 

Let's see now what I'm doing wrong.

**Comment by stas00** [comment]
It's somewhat mindboggling in z2. In z3 each param is padded so it's easy to reconstruct, in z2 sometimes it's padding something it's not.

e.g. if I build 4 1-element params on world_size=2

it creates:

```
tensor([-0.8050,  0.8590, -0.0472,  0.8955], grad_fn=<CatBackward>)
tensor([0., 0., 0., 0.], grad_fn=<CatBackward>)
```

so reconstruct it I have to take a slice from each and then narrow it to the shape of [1]

but now, let's do the same 8 1-element params on world_size=2

and it still uses 8 elements in total:
```
tensor([ 0.0413, -0.6292,  0.3938,  0.2581], grad_fn=<CatBackward>)
tensor([-0.6224, -0.2222,  0.9233, -0.8687], grad_fn=<CatBackward>)
```
but now we have 8 params of the shape of [1]

I can't quite figure out the logic.

If I'm not mistaken Z2 is a one way street, it creates the partitions and saves it as is and when it reloads fp32 weights it does the same thing it creates the same partitions and copies the data into it from the saved partition - it never rebuilds the state dict elements.

In the case of a single param group as you said there is no slicing so it's just concat the partitioned together and then narrow into each param according to the shape. But in the case of multiple params there is no map on how they were sliced and where padding was inserted.

If you have bright ideas I'm all ears.

**Comment by eelxpeng** [comment]
It should be noted that `single_partition_of_fp32_groups` is a list of flat tensors, where each element corresponds to each param group, instead of a single flat tensor. And the padding happens for each param group individually. So I think it makes sense to treat each param group separately. Here is my temporary solution:
```
fp32_flat_groups = [
        state_dicts[i]['optimizer_state_dict'][fp32_groups_key] for i in range(len(state_dicts))
    ]

num_param_groups = len(fp32_flat_groups[0])
merged_single_partition_of_fp32_groups = []
for i in range(num_param_groups):
    merged_partitions = [ sd[i] for sd in fp32_flat_groups]
    full_single_fp32_vector = torch.cat(merged_partitions, 0)
    merged_single_partition_of_fp32_groups.append(full_single_fp32_vector)
```
The tricky thing is one has to infer the `param_shapes` in each param group. But I don't think this is available without knowing  what are the param groups. In my case, I divided the `param_shapes` dictionary based on param groups of my training code (of course following the same param order), and then reconstruct the fp32 weights following your original conversion code for each param group.

Hope that may help.

**Comment by stas00** [comment]
The `param_shapes` key of the saved dict I added specifically to be able to reconstructs the params - it wasn't there in the original code. See: 

https://github.com/microsoft/DeepSpeed/blob/0457bb1cb661c4783712489b529317437e086bc7/deepspeed/runtime/engine.py#L2432-L2469

So perhaps for z2 it can be saved in such a way that it'll be easy to reconstruct?

**Comment by eelxpeng** [comment]
I see. I definitely think that z2 should be saved in such a way that it'll be easy to reconstruct. `param_shapes` should be a list of ordered dictionaries, not just one ordered dictionary, where each dictionary corresponds to each param group. Then the weights can be reconstructed easily.

**Comment by eelxpeng** [comment]
So the above function should be revised as follows:
```
    param_group_shapes = []
    cnt = 0
    numel = 0

    # zero2 started using a round_robin_fp16_groups which is a shuffled version of fp16_groups -
    # if we don't use it, we get parameters ordered incorrectly
    if hasattr(self.optimizer, "round_robin_fp16_groups"):
        fp16_groups = self.optimizer.round_robin_fp16_groups
    else:
        fp16_groups = self.optimizer.fp16_groups

    for fp16_group in fp16_groups:
        param_shape = OrderedDict()
        for param in fp16_group:
            cnt += 1
            numel += param.ds_numel if hasattr(param, "ds_numel") else param.numel()
            shape = param.ds_shape if hasattr(param, "ds_shape") else param.shape
            if param not in self.param_names:
                raise ValueError(f"failed to find optimizer param in named params")
            name = self.param_names[param]
            param_shapes[name] = shape

            # uncomment to debug zero_to_fp32.py problems
            # if self.global_rank == 0: print(f"saving param {name} {shape} (numel={shape.numel()})")
        param_group_shapes.append(param_shape)
    # if self.global_rank == 0: print(f"Total saved {numel} numels in {cnt} params")

    return param_group_shapes
```
Do you think that's right? @stas00

**Comment by eelxpeng** [comment]
See this pr as an initial solution: https://github.com/microsoft/DeepSpeed/pull/1424 .
