### ISSUE TITLE
difference with launch_attn_softmax_backward_v2 and launch_attn_softmax_backward

### ISSUE THREAD

**Issue by hyunwoongko** [microsoft/DeepSpeed#1413]
What is the difference between the two kernels?

Thanks

**Comment by RezaYazdaniAminabadi** [comment]
Hi @hyunwoongko 

You always ask the interesting (and challenging) questions. The v2 is doing the reduction of the partial sums inside warp while the other version it is across threads of a block. We have seen that for small sequence lengths the v2 is faster, but if we use larger sequence length we have to use the other version, as we are limited by the number of registers. Currently, this part of launching these two kernels is not specified. If you are interested, we can work to support this.
Thanks,
Reza

**Comment by hyunwoongko** [comment]
> We have seen that for small sequence lengths the v2 is faster, but if we use larger sequence length we have to use the other version.

Thanks for kind answer! Then, how long is the sequence length that V2 can handle? Of course, it will depend on the hidden size. I want to know the general case. (like GPT2-1.5B)

Thanks.

**Comment by hyunwoongko** [comment]
And did you check my message on Slack? I think it would be good to decide a meeting time.
p.s. @stas00 @jaketae want to meet together.

Thanks.

**Comment by hyunwoongko** [comment]
Oh I found this line https://github.com/microsoft/DeepSpeed/blob/master/csrc/transformer/softmax_kernels.cu#L575
