### ISSUE TITLE
ds_report shows no info about mpi or nccl, or cuda capabilities

### ISSUE THREAD

**Issue by surak** [microsoft/DeepSpeed#1449]
It's hard to check if DS supports NCCL and MPI, when there's no info about it on ds_report.

`ds_report` actually reporting what was used and what is recognized w.r.t. CUDA, MPI, NCCL.

**Comment by awan-10** [comment]
Hi @surak, 

We rely on torch distributed so NCCL or MPI versions will be the same as those. 

Torch version and CUDA version are reported by ds_report as follows.

![image](https://user-images.githubusercontent.com/9065216/139919651-078401f4-f711-4071-abbd-91f3f7cbbd5a.png)

We welcome PRs so any suggestions you have to improve ds_report, please share with us here or in a PR :)
