### ISSUE TITLE
[Question] Fused Kernels for Inference 

### ISSUE THREAD

**Issue by zgerrard** [microsoft/DeepSpeed#1464]
Hi, after looking at the code I noticed that all functions for inference in CUDA are unfused. Also, there is no InferenceSpecializedBuilder that is supposed to build Specialized Transformer that uses the fused kernels, as mentioned in the blogpost: https://www.microsoft.com/en-us/research/blog/deepspeed-accelerating-large-scale-model-inference-and-training-via-system-optimizations-and-compression/

Please, could you tell me if I am missing something or the support for fused kernels for inference was removed?

@RezaYazdaniAminabadi

**Comment by jeffra** [comment]
Closing, keep an eye out for updates related to releasing specialized kernel binaries.
