### ISSUE TITLE
[BUG] Memory Leak Using ZeRO stage3 without Checkpointing

### ISSUE THREAD

**Issue by ConnollyLeon** [microsoft/DeepSpeed#1465]
**Describe the bug**
When using ZeRO-3 to train model without checkpointing intermediate activation values, I find out that the post_sub_module_forward_function is not working correctly. It do partition the param.data, but the memory consumption remains the same. 

This is probably due to the inner implementation of PyTorch, which creates a ref of param.data to keep its corresponding intermediate activation values.

**To Reproduce**
Training Any model without applying checkpointing trick. 
set see_memory_usage force to True.

**Expected behavior**
The memory should decrease after executing release_sub_module function.

**ds_report output**
Please run `ds_report` to give us details about your setup.
ninja installed
torch 1.9.1+cu102
deepspeed 0.5.4

**Screenshots**

**System info (please complete the following information):**
 - OS:  Ubuntu 18.04
 - GPU count and types: 8 GPU V100 in one machine
 - Python version 3.7.4
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
deepspeed launcher

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by jeffra** [comment]
Closing, please re-open if you have further issues or questions.

**Comment by ConnollyLeon** [comment]
@samyam Wow, that's incredible, Thanks a lot.
I am trying to train a BERT-like model, so Linear layer is fair enough for me.
