### ISSUE TITLE
[Question] Permission denied error on slurm based systems

### ISSUE THREAD

**Issue by PythaGorilla** [microsoft/DeepSpeed#1475]
I tried to run deepspeed on a slurm based node (compute canada). But it always throws a "Permission denied" error whenever "deepspeed" command (in bash) is used. However, I can successfully run the "python -m deepspeed.env_report" command and get the correct report. Could you please help me find out why this error occurs? Thanks a lot.

**Comment by yyy-Apple** [comment]
I guess you need to use `chmod`. At least for me, that solved the problem.

**Comment by PythaGorilla** [comment]
> Hi @PythaGorilla, are you able to launch processes with `python -m torch.distributed.launch` from https://pytorch.org/docs/stable/distributed.html

yes, i can run it without problem.

**Comment by PythaGorilla** [comment]
> I guess you need to use `chmod`. At least for me, that solved the problem.
Thanks, @yyy-Apple. Could you elaborate on what file or folder to `chmod`?

**Comment by yyy-Apple** [comment]
You should make `path/to/bin/deepseed` executable

**Comment by yyy-Apple** [comment]
@PythaGorilla You should make `path/to/bin/deepspeed` executable.

**Comment by PythaGorilla** [comment]
@yyy-Apple  Thanks, it worked!
