### ISSUE TITLE
[Question] How to use deepspeed to run: python -m package.run

### ISSUE THREAD

**Issue by gitsybws** [microsoft/DeepSpeed#1495]
Launching training need replace python -m torch.distributed.launch with deepspeed: 
`original cmd: python -m torch.distributed.launch --nproc_per_node=8 <client_entry.py> <client args>`
-->
`deepspeed --num_gpus=8 <client_entry.py> <client args> --deepspeed ds_config.json`

But my original command line looked as following: 
```
python -m torch.distributed.launch \
    --nproc_per_node=8 -- \
    python -m package.client_entry \
    <client args>
```
python run library module as a script.

Is there a way for deepspeed to start this command?

**Comment by jeffra** [comment]
DeepSpeed is also compatible with `torch.distributed.launch`, you are not required to use our launcher. Closing but feel free to re-open if you still have an issue here.
