### ISSUE TITLE
[BUG]Sparse Attention MatMul bugs

### ISSUE THREAD

**Issue by btyu** [microsoft/DeepSpeed#1513]
**Describe the bug**
Hi, I'm using the sparse attention matmul. I think I met some bugs: the dimension of matmul result is not as expected.

**To Reproduce**
Run the following code.

```python
import torch
from deepspeed.ops.sparse_attention.matmul import MatMul as matmul

B, H, L, D = 4, 8, 1024, 512
block = 16
device = 'cuda:2'
requires_grad = False

a = torch.rand((B, H, L, D), dtype=torch.float32, device=device, requires_grad=requires_grad)
b = torch.rand((B, H, L, D), dtype=torch.float32, device=device, requires_grad=requires_grad)

layout = torch.randint(0, 2, (H, L // block, L // block))

dot = matmul(layout, block, 'sdd', trans_a=False, trans_b=True)
c = dot(a, b)

assert c.shape[1] == layout.sum(), (c.shape[1], layout.sum().item())
```

**Expected behavior**
The assertion at the last line should always succeed.

**ds_report output**
The assertion tends to fail (yet sometimes succeed) with the output like this:

```
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_30700/3882726527.py in <module>
----> 1 assert c.shape[1] == layout.sum(), (c.shape[1], layout.sum().item())

AssertionError: (16452, 16446)
```

**Comment by RezaYazdaniAminabadi** [comment]
Hi @btyu 

Thanks for reporting this issue, I did use your script and I can repro this. I will look into this and find the source of problem.

Best,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
Hi @btyu, 

Can you please try this PR on your side and see if the issue is resolved?
Thanks,
Reza

**Comment by btyu** [comment]
Hi @RezaYazdaniAminabadi .
I tested the PR. The problem hardly appears now, except only once when I set ``block_size=32`` so far. And, when I set ``block_size > 128``, e.g. 256, the ``c.shape[1]`` will be 0. So I am wondering whether it can support ``block_size > 128``?

I am testing more cases as well as using it in my model. I will report to you once I get something new.

Thanks

**Comment by btyu** [comment]
The problem is still here when setting `block_size=32`, but it works fine with `block_size=16, 64, 128`. 

Thanks
