### ISSUE TITLE
[BUG] 'NoneType' object has no attribute 'reserve_partitioned_swap_space' with params offloading to nvme enabled

### ISSUE THREAD

**Issue by dredwardhyde** [microsoft/DeepSpeed#1543]
**Describe the bug**
Exception
**'NoneType' object has no attribute 'reserve_partitioned_swap_space' with params offloading to nvme enabled**

**To Reproduce**
**With this configuration:**
```json
{
  "train_batch_size": 15,
  "fp16": {
    "enabled": true,
    "min_loss_scale": 1,
    "opt_level": "O3"
  },
  "zero_optimization": {
    "stage": 3,
    "offload_param": {
      "device": "nvme",
      "nvme_path": "/home/deepschneider/deepspeed",
      "buffer_count": 5,
      "buffer_size": 1e8,
      "max_in_cpu": 1e9
    },
    "offload_optimizer": {
      "device": "nvme",
      "nvme_path": "/home/deepschneider/deepspeed",
      "buffer_count": 4,
      "pipeline_read": false,
      "pipeline_write": false,
      "pin_memory": true
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "contiguous_gradients": true,
    "overlap_comm": true,
    "aio": {
      "block_size": 1048576,
      "queue_depth": 8,
      "thread_count": 1,
      "single_submit": false,
      "overlap_events": true
    }
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": 5e-05,
      "betas": [
        0.9,
        0.999
      ],
      "eps": 1e-08
    }
  },
  "scheduler": {
    "type": "WarmupLR",
    "params": {
      "warmup_min_lr": 0,
      "warmup_max_lr": 5e-05,
      "warmup_num_steps": 100
    }
  }
}
```
**I'm getting the following exception**
![Screenshot from 2021-11-09 23-14-03](https://user-images.githubusercontent.com/8986329/140997822-0e545c5a-7716-4070-9164-ca2504c5ad1f.png)

**This configuration works fine:**
```json
{
  "train_batch_size": 15,
  "fp16": {
    "enabled": true,
    "min_loss_scale": 1,
    "opt_level": "O3"
  },
  "zero_optimization": {
    "stage": 3,
    "offload_optimizer": {
      "device": "nvme",
      "nvme_path": "/home/deepschneider/deepspeed",
      "buffer_count": 4,
      "pipeline_read": false,
      "pipeline_write": false,
      "pin_memory": true
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "contiguous_gradients": true,
    "overlap_comm": true,
    "aio": {
      "block_size": 1048576,
      "queue_depth": 8,
      "thread_count": 1,
      "single_submit": false,
      "overlap_events": true
    }
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": 5e-05,
      "betas": [
        0.9,
        0.999
      ],
      "eps": 1e-08
    }
  },
  "scheduler": {
    "type": "WarmupLR",
    "params": {
      "warmup_min_lr": 0,
      "warmup_max_lr": 5e-05,
      "warmup_num_steps": 100
    }
  }
}
```

![image](https://user-images.githubusercontent.com/8986329/140998482-88e9788c-4d1b-497d-86b6-bf52b701219a.png)

**Expected behavior**
Both configurations should work fine.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
sparse_attn ............ [YES] ...... [OKAY]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
async_io ............... [YES] ...... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
quantizer .............. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch']
torch version .................... 1.10.0+cu113
torch cuda version ............... 11.3
nvcc version ..................... 11.3
deepspeed install path ........... ['/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.5.6+43e6432, 43e6432, cpu-adam/fix-scalar-compile
deepspeed wheel compiled w. ...... torch 1.10, cuda 11.3
```

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU: 1xA6000
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]: no
 - Python version: 3.8.10

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
Huggingface Trainer

**Comment by tjruwase** [comment]
Thanks for opening a new issues. Can you also share the command-line to run?

**Comment by dredwardhyde** [comment]
Well, you can run [this](https://github.com/dredwardhyde/gpt-neo-fine-tuning-example/blob/main/gpt_j_deepspeed.py) script from the repo, here is the [requirements.txt](https://github.com/dredwardhyde/gpt-neo-fine-tuning-example/blob/main/requirements.txt) file
I used Huggingface Trainer, so I'm not sure about cmd

**Comment by tjruwase** [comment]
@dredwardhyde, thanks I am able to repro this issue, thanks for the help. I will keep you updated with progress.

**Comment by tjruwase** [comment]
@dredwardhyde, can you please test the PR?

**Comment by dredwardhyde** [comment]
@tjruwase I think it works absolutely fine now, thank you!
![image](https://user-images.githubusercontent.com/8986329/141448318-6c50d4f2-f6b3-4742-8bdd-1c69c0271d7c.png)
![Screenshot from 2021-11-12 12-57-39](https://user-images.githubusercontent.com/8986329/141448341-a354a9fb-d625-4266-92c0-b1e50e67e373.png)

**Comment by tjruwase** [comment]
@dredwardhyde, thanks for the update. 

I am curious if you are able to successfully run your model e2e. On my V100-32GB, it OOM'd in the first backward pass. I traced that to high memory usage because [model construction](https://github.com/dredwardhyde/gpt-neo-fine-tuning-example/blob/bfb27192d194aebaab3e0b85fe987180000b00bc/gpt_j_deepspeed.py#L15) without [zero.Init](https://deepspeed.readthedocs.io/en/latest/zero3.html#deepspeed.zero.Init) context manager. Is that your experience?

**Comment by dredwardhyde** [comment]
@tjruwase yeah, this is exactly what I've got
So it's not possible to run this model using Huggingface Trainer, right?

**Comment by dredwardhyde** [comment]
@tjruwase ah, ok, I'll try [this](https://huggingface.co/transformers/main_classes/deepspeed.html#constructing-massive-models) approach, thank you so much for the help!

**Comment by tjruwase** [comment]
@dredwardhyde, thanks for confirming your experience. Actually, this 6B model should easily run using Huggingface Trainer with the parameter and optimizer offload configurations. I think a few things could help:

1. The model is constructed as fp32. Is this intentional?
2. [zero.Init](https://deepspeed.readthedocs.io/en/latest/zero3.html#deepspeed.zero.Init) context manager should be used during model construction to ensure that the parameters are offloaded to cpu or nvme. 

We can help with getting this finetuning working, so can you please open a new issue for that purpose. Thanks.

**Comment by dredwardhyde** [comment]
@tjruwase thank you, tomorrow I'll try to use **torch.float16** and **zero.init** as described in [this](https://huggingface.co/transformers/main_classes/deepspeed.html#constructing-massive-models) guide
I'll open a new issue if I get any errors)

**Comment by tjruwase** [comment]
@dredwardhyde, please see this [HF guide](https://github.com/huggingface/transformers/blob/c37573806ab3526dd805c49cbe2489ad4d68a9d7/docs/source/main_classes/deepspeed.rst#non-trainer-deepspeed-integration) as well. I am confused now but it seems you should not use zero.Init() directly because your script is [constructing the model](https://github.com/dredwardhyde/gpt-neo-fine-tuning-example/blob/bfb27192d194aebaab3e0b85fe987180000b00bc/gpt_j_deepspeed.py#L14-L15) outside the HF Trainer.
