### ISSUE TITLE
How can I use ZERO with GCC 4.8.5 and CentOS7

### ISSUE THREAD

**Issue by EeyoreLee** [microsoft/DeepSpeed#1559]
I use ZERO to train my model. It is efficient and easy to use. But it can't work when I use it with CentOS7 with GCC 4.8.5 . Cause it must build extension module utils.so which need GCC 5 or higher. �Is there any method than don't need to use utils.so or GCC(such as utils.py ) because the GCC is not allowed to be upgraded for some reason. Forgive me for not being fluent in english and Thanks vvvvery much !!!!!!

**Comment by tjruwase** [comment]
@EeyoreLee, did you find a solution to this problem?

**Comment by EeyoreLee** [comment]
> @EeyoreLee, did you find a solution to this problem?

Sorry,I tried many methods but still couldn't solve it .  Maybe I can change the `utils.so` to `utils.o` in other env with GCC 5+ , then migrate over . But for some reason, I didn’t have time to try .
