### ISSUE TITLE
The change of largest_partitioned_param_numel looks to be fixed, regarding of ds_numel, not numel().

### ISSUE THREAD

**Issue by mrgomdev** [microsoft/DeepSpeed#1561]
The change uses tensor.numel() for retrieving the sizes. However, if we already built the model in the context of deepspeed.zero.Init(), tensor.numel() or tensor.data get pointing only the placeholder, after partitioning and offloading the original tensor into ds_tensor and ds_numel, accordingly. In some cases, this can cause some problems, including the initialization of a deepspeed model engine after deepspeed.zero.Init(). Please check out this situation and confirm the change is valid.

The original version, self.fp16_partitioned_groups_flat_numel [seems that it got retrieved from ds_numel. ](The change uses tensor.numel() for retrieving the sizes. However, if we already built the model in the context of deepspeed.zero.Init(), tensor.numel() or tensor.data get pointing only the placeholder, after partitioning and offloading the original tensor into ds_tensor and ds_numel, accordingly. In some cases, this can cause some problems, including the initialization of a deepspeed model engine after deepspeed.zero.Init(). Please check out this situation and confirm the change is valid.

The original version, self.fp16_partitioned_groups_flat_numel seems that it got retrieved from ds_numel. https://github.com/microsoft/DeepSpeed/blob/7567c76c05626c5acd8b5700bedfc412c55d5354/deepspeed/runtime/zero/stage3.py#L1151)

_Originally posted by @mrgomdev in https://github.com/microsoft/DeepSpeed/pull/1150#issuecomment-962951822_

**Comment by tjruwase** [comment]
@mrgomdev, thanks for raising this issue. I will take a closer look. Are you currently seeing a problem with this code?

**Comment by mrgomdev** [comment]
Of course.

I can report a case caused by this issue.
When training massive minGPT model with zero-infinity for nvme as the remote device to offload, the code deciding the size of buffer refers `largest_partitioned_param_numel`. However, the change from PR #1150  , the buffer size gets restricted only by the total size of placeholders for offloading, not the actual size. This cuased crash using the buffer. Replacing `tensor.numel()` with `tensor.ds_numel` fixed our case.

**Comment by tjruwase** [comment]
Since you have fix already. Do you mind sharing both the repro and a PR? We will greatly appreciation the contribution.

**Comment by mrgomdev** [comment]
The previous version (with tensor.numel()) seems to be working for the scenario using CPU Offload, regardless of whether deepspeed.zero.Init() is used or not. The latter version (with tensor.ds_numel fixes the error occured in the scenario using both NVMe Offload and deepspeed.zero.Init(). My colleague reported these two cases to me, but I'm not sure which change is the correct one for the intention of the code. (1) Revert the PR #1150  (2) Replace tensor.numel() with tensor.ds_numel if ds_numel exists (3) Replace it only when using both NVMe Offload and deepspeed.zero.Init().

**Comment by tjruwase** [comment]
@mrgomdev, can you please try this fix for `largest_partitioned_param_numel` computation?
```python
        largest_partitioned_param_numel = max([
            max([max(tensor.numel(), tensor.ds_numel) for tensor in fp16_partitioned_group])
            for fp16_partitioned_group in self.fp16_partitioned_groups
        ])
```

**Comment by mrgomdev** [comment]
Recently I have been out of the project using deepspeed and huge NN models bacause of some external reasons. I asked my colleague to try that fix and check out if the change makes expected difference compared to the original one. He would answer to it soon.
In my opinion, it looks reasonable, while AttributeError does not happen. If happen, my colleague would suggest and test some defensive changes for that.

**Comment by tjruwase** [comment]
@mrgomdev, sounds good. I pushed #1623. It would be great if you colleague could help to test it. Also, if your colleague is willing to share the test cases, we could include them in the unit tests. Thanks!
