### ISSUE TITLE
[BUG] error: identifier "THCudaCheck" is undefined

### ISSUE THREAD

**Issue by jeyblu** [microsoft/DeepSpeed#1584]
**Describe the bug**
Error encountered building deepspeed.
>error: identifier "THCudaCheck" is undefined

**To Reproduce**
1. git clone https://github.com/microsoft/DeepSpeed.git
2. cd deepspeed
3. Build deepspeed as described in [documentation](https://www.deepspeed.ai/tutorials/advanced-install): `DS_BUILD_FUSED_LAMB=1 python setup.py build_ext bdist_wheel`
4. Error encountered
    >csrc/lamb/fused_lamb_cuda_kernel.cu(467): error: identifier "THCudaCheck" is undefined
    >csrc/lamb/fused_lamb_cuda_kernel.cu(351): warning: variable "threads" was declared but never referenced

**Expected behavior**

**ds_report output**
> 
> DeepSpeed C++/CUDA extension op report
> 
> NOTE: Ops not installed will be just-in-time (JIT) compiled at
>       runtime if needed. Op compatibility means that your system
>       meet the required dependencies to JIT install the op.
> 
> JIT compiled ops requires ninja
> ninja .................. [OKAY]
> 
> op name ................ installed .. compatible
> 
> cpu_adam ............... [NO] ....... [OKAY]
> cpu_adagrad ............ [NO] ....... [OKAY]
> fused_adam ............. [NO] ....... [OKAY]
> fused_lamb ............. [NO] ....... [OKAY]
> sparse_attn ............ [NO] ....... [OKAY]
> transformer ............ [NO] ....... [OKAY]
> stochastic_transformer . [NO] ....... [OKAY]
> async_io ............... [NO] ....... [OKAY]
> transformer_inference .. [NO] ....... [OKAY]
> utils .................. [NO] ....... [OKAY]
> quantizer .............. [NO] ....... [OKAY]
> 
> DeepSpeed general environment info:
> torch install path ............... ['/home/bduser/anaconda3/envs/deepspeed/lib/python3.8/site-packages/torch']
> torch version .................... 1.11.0a0+gitb46c89d
> torch cuda version ............... 11.4
> nvcc version ..................... 11.4
> deepspeed install path ........... ['/home/bduser/anaconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed']
> deepspeed info ................... 0.5.8+8220674, 8220674, master
> deepspeed wheel compiled w. ...... torch 1.11, cuda 11.4

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count and types: dgx2
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version 3.8.2
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by avolkov1** [comment]
Will anyone follow up on this?

**Comment by avolkov1** [comment]
I seem to have fixed it by patching:
```
sed -i 's/THCudaCheck/C10_CUDA_CHECK/g' csrc/lamb/fused_lamb_cuda_kernel.cu
```
and installing from source.
Per PR here: https://github.com/microsoft/DeepSpeed/pull/1725/files

**Comment by jeffra** [comment]
@jeyblu are you still seeing this issue? @avolkov1 are you also on torch 1.11?

We're currently seeing some pre-compile issues on torch nightly builds, not sure if this is related or not, see: https://github.com/microsoft/DeepSpeed/issues/1625 and https://github.com/pytorch/pytorch/issues/69666.

Can you try JIT compiling fused lamb in this case? you can try this quickly via this script:

```python
import deepspeed
deepspeed.ops.op_builder.FusedLambBuilder().load()
```

**Comment by avolkov1** [comment]
Yes, using pytorch 1.11.
I installed deepspeed in container: nvcr.io/nvidia/pytorch:22.01-py3
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-01.html#rel_22-01

I had to set: `TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0 8.6+PTX"` and replace THCudaCheck with C10_CUDA_CHECK.
Also, `pip install triton==1.0.0`, and then DeepSpeed compiled and installed from source version 0.5.10
https://github.com/microsoft/DeepSpeed/archive/refs/tags/v0.5.10.tar.gz
```
DS_BUILD_OPS=1 pip install . --global-option="build_ext" --global-option="-j8"
```
I haven't run it yet. I'll test it soon.

**Comment by tridao** [comment]
I'm running into the same issue: I'm on pytorch 1.11 using the same container nvcr.io/nvidia/pytorch:22.01-py3, and compiling deepspeed fails with:
```csrc/lamb/fused_lamb_cuda_kernel.cu(467): error: identifier "THCudaCheck" is undefined```

**Comment by loadams** [comment]
This seems to be due to Torch and Cuda versions, but seems resolved now.  If folks are still hitting this, please open a new issue and link this one and we can take a look.
