### ISSUE TITLE
Using PyCharm and its debugger along with DS

### ISSUE THREAD

**Issue by hpourmodheji** [microsoft/DeepSpeed#1586]
Hi,

Can we train a model with the DS optimizer using PyCharm and its Debugger feature?

Best,

Hossein

**Comment by ckddls1321** [comment]
Hello. I just share my experiment details. 
For usage of deepspeed command, please refer to https://www.deepspeed.ai/tutorials/

When you deepspeed in PyCharm, you can refer to deepspeed/launcher/multinode_runner.py 
It's same way to use torch.distributed.launch.
Please add Interpreter options : -m deepspeed.launcher.launch --world_info=<encoded utf-8 of node and GPU dictionary> --node_rank=0 --master_addr=<localhost or IP> --master_port=4242

The way to make world info that encoded string that include node and GPU information. 
Resource information is a dictionary like : {'192.168.0.5' : [0,1,2,3,4,5,6,7]}
https://github.com/microsoft/DeepSpeed/blob/a637cc2cd508381d79a522c98fef0d4e747ef28f/deepspeed/launcher/runner.py#L261

After that you can train a model with the DS optimizer using Pycharm with Single Node.

**Comment by hpourmodheji** [comment]
Thanks, Changln, for your informative comments. Actually, I can "run" the training on PyCharm using DS optimizer. Have you tried the "debugger" as well? Do you have any experience with using PyCharm debugger along with DS optimizer?

**Comment by ckddls1321** [comment]
Yes. Actually PyCharm Debugger does not successfully debug all sub-process, you can debug into one of sub-process and find out details inside when training models with DS optimizer. But in my experience, debugging during forward and backward, it would be hard to catch exact point due to large variables holds on model side (debugger really slow sometimes). 
For example, if you stop your all sub-process during forward or backward at your debug point, training process may failed to keep continue train iteration. 

Also, I found that --local_rank argument that pass over to launcher may failed to start pycharm debugger. 
Please pass over local_rank as environment variable by modifying source code when you debug.

**Comment by cli99** [comment]
Seems that PyCharm debugger has problems dealing with multiprocessing in general. Here are some relevant tickets,https://youtrack.jetbrains.com/issue/PY-39489, https://youtrack.jetbrains.com/issue/PY-37366m which are not resolved yet.

**Comment by kehuanfeng** [comment]
> Seems that PyCharm debugger has problems dealing with multiprocessing in general. Here are some relevant tickets,https://youtrack.jetbrains.com/issue/PY-39489, https://youtrack.jetbrains.com/issue/PY-37366m which are not resolved yet. As @ckddls1321 pointed out, using pytorch profiler or nsight sys is usually easier. Here is a tutorial to use pytorch profiler with DS. https://www.deepspeed.ai/tutorials/pytorch-profiler/

hi @cli99 , I am trying to use the way you mentioned above, but neither is working proper for me, could you please point me out?
1. When I use pytorch profiler and save the tracing information into json file, the trace for each gpu or each parallel process is in seperete file, so it's not possible to anaylze them as a whole.
2. When I use nsight, like 'nsys profile deepspeed <other args>', the report file doesn't contain cuda trace information.

**Comment by haorannlp** [comment]
> Yes. Actually PyCharm Debugger does not successfully debug all sub-process, you can debug into one of sub-process and find out details inside when training models with DS optimizer. But in my experience, debugging during forward and backward, it would be hard to catch exact point due to large variables holds on model side (debugger really slow sometimes). For example, if you stop your all sub-process during forward or backward at your debug point, training process may failed to keep continue train iteration.
> 
> Also, I found that --local_rank argument that pass over to launcher may failed to start pycharm debugger. Please pass over local_rank as environment variable by modifying source code when you debug.
> 
> Additionally, sometimes it would be better to profile details rather then debugging DS optimizer. You can visualize how DS optimizer actually work through PyTorch profiler or NSight System.

set '--no_local_rank'
