### ISSUE TITLE
wall_clock_breakdown disable failed in moe layer

### ISSUE THREAD

**Issue by PeiqiWang** [microsoft/DeepSpeed#1594]
**Describe the bug**
The wall_clock_breakdown flag cannot be disabled in moe layer

**Bugs in code**
The self.wall_clock_breakdown is a method, which should called by `self.wall_clock_breakdown`. Here it is always `True`.

https://github.com/microsoft/DeepSpeed/blob/d14baad9401bc1de8c982c1b3590d91108c4bbf1/deepspeed/runtime/engine.py#L1017
https://github.com/microsoft/DeepSpeed/blob/d14baad9401bc1de8c982c1b3590d91108c4bbf1/deepspeed/runtime/engine.py#L1021

**Comment by tjruwase** [comment]
@PeiqiWang, thanks for reporting this bug. Do you mind contributing a PR? Thanks!

**Comment by PeiqiWang** [comment]
#1596
