### ISSUE TITLE
[loss OVERFLOW] Several Issues

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#1599]
**Describe the bug**

Splitting of from https://github.com/microsoft/DeepSpeed/pull/1593

This Issue documents multiple issues wrt OVERFLOW event

1. ZeRO2 OVERFLOW goes from `initial_scale_power` set in config to the one where it gets resolved or can't be resolved in one step (compared to zero3 where it reduces the power one step at a time and reports each decrement) As you can see in https://github.com/microsoft/DeepSpeed/pull/1593#issue-789881585 I get the report of power 1 right away when `initial_scale_power=16` 
```
OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 1, reducing to 1
```

2. ZeRO3 OVERFLOW  has a one-off issue: `Attempted loss scale: 65536, reducing to 65536` - i.e it's not scaling the first time around.

3. Both ZeRO2 and ZeRO3 should probably assert if:
   a. loss is `nan` - related: https://github.com/microsoft/DeepSpeed/issues/931 
   b. `Attempted loss scale: 1, reducing to 1` happens - clearly this is broken.
   
   since it's impossible to recover from either. But Deepspeed optimizer skips the step and gets stuck in the above scaling

**Comment by stas00** [comment]
Here is another reported issue where a user reports this endless loop that can't resolve overflow and where I think Deepspeed ought to assert:
https://github.com/huggingface/transformers/issues/14834

**Comment by Quentin-Anthony** [comment]
This has been resolved in https://github.com/microsoft/DeepSpeed/pull/1958

**Comment by stas00** [comment]
yes, definitely #3 was resolved - not sure about the rest

**Comment by Quentin-Anthony** [comment]
> yes, definitely item 3 was resolved - not sure about the rest

Gotcha. I think item 1 has been resolved since the loss overflow logic has been unified between Zero-1/2. 

As for item 2 the reason such messages are printing is because of fp16 [hysteresis ](https://www.deepspeed.ai/docs/config-json/#fp16-training-options). I agree it's confusing, so I just made a PR to clarify those messages in https://github.com/microsoft/DeepSpeed/pull/3008.

Now loss overflow logs look like:

```
...
OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 65536, but hysteresis is 3. Reducing hysteresis to 2
OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 65536, but hysteresis is 2. Reducing hysteresis to 1
OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 65536, reducing to 32768
OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 32768, reducing to 16384
...
```
