### ISSUE TITLE
Make FP16_DeepSpeedZeroOptimizer a sub-class of torch.optim.Optimizer?

### ISSUE THREAD

**Issue by g-karthik** [microsoft/DeepSpeed#160]
Could you please make `FP16_DeepSpeedZeroOptimizer` a sub-class of `torch.optim.Optimizer`?

Looking at the code, it feels like the effort should be minimal, since most of the methods in `Optimizer` have been overriden anyway.

It's just `add_param_group(self, param_group)` from `Optimizer` that won't work with this sub-class until some changes are made to the sub-class I think.

The benefits of making this optimizer a sub-class of `Optimizer` are immense -- it will ensure easy interoperability with client-side code that leverages standard PyTorch frameworks like [ignite](https://github.com/pytorch/ignite).

Right now, I get the following error:
```
    tb_logger.attach(trainer, log_handler=OptimizerParamsHandler(optimizer), event_name=Events.ITERATION_STARTED)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/contrib/handlers/tensorboard_logger.py", line 147, in __init__
    super(OptimizerParamsHandler, self).__init__(optimizer, param_name, tag)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/contrib/handlers/base_logger.py", line 56, in __init__
    "but given {}".format(type(optimizer)))
TypeError: Argument optimizer should be of type torch.optim.Optimizer, but given <class 'deepspeed.pt.deepspeed_zero_optimizer.FP16_DeepSpeedZeroOptimizer'>

```

I see a related issue https://github.com/microsoft/DeepSpeed/issues/118 but it's not clear to me whether this has been fixed, since the code still says the optimizer is a sub-class of a regular object.

**Comment by tjruwase** [comment]
F16_DeepSpeedZeroOptimizer is meant to be a wrapper to "true" optimizers that are subclass of torch.optim.Optimizer. In that sense it is similar to apex's [fp16_optimizer](https://github.com/NVIDIA/apex/tree/master/apex/fp16_utils). We think it is important to maintain this clean separation between optimizer-wrappers and optimizers. But, we certainly see the point you are making, and actually went down that path for a while.

**Comment by tjruwase** [comment]
Closing, please reopen if needed.
