### ISSUE TITLE
[Docs] Azure tutorial on Deepspeed webpage contains no hyperlink to .sh files mentioned and used

### ISSUE THREAD

**Issue by trancenoid** [microsoft/DeepSpeed#1630]
The Deepspeed tutorial [page](https://www.deepspeed.ai/tutorials/azure/) on Azure references to multiple .sh files, but the files are not referenced to the Deepspeed [repo](https://github.com/microsoft/DeepSpeed/tree/master/azure).

**Comment by jeffra** [comment]
Hi @trancenoid, sorry for confusion. The script’s referenced there are here: https://github.com/microsoft/DeepSpeed/tree/master/azure

However, we do recommend using AzureML for an easier experience than using raw VMs like we do in our original tutorial.

**Comment by jeffra** [comment]
Please re-open if you have further questions/concerns.
