### ISSUE TITLE
[BUG] DeepSpeedCPUAdam wrong result after calling step

### ISSUE THREAD

**Issue by zgsbughammer** [microsoft/DeepSpeed#1643]
Hi, there. 

Lately we used deepspeed to speed up our model training but often got unexpected **cuda invalid resource handle error** once cpu offload is enabled. We finally narrowed down this problem to DeepSpeedCPUAdam's step method after making some efforts. So we tried to adapt code [here](https://github.com/microsoft/DeepSpeed/blob/master/tests/perf/adam_test1.py) to the following 
```
import torch
from deepspeed.ops.adam import DeepSpeedCPUAdam
import time

device = 'cpu'
model_size = 1 * 1024**2
param1 = torch.nn.Parameter(torch.ones(model_size, device=device))
param_fp16_1 = torch.nn.Parameter(torch.ones(model_size,
                                             dtype=torch.half,
                                             device='cuda:0'))
param = torch.nn.Parameter(torch.ones(model_size, device=device))
param_fp16 = torch.nn.Parameter(torch.ones(model_size,
                                           dtype=torch.half,
                                           device='cuda:0'))

optimizer = DeepSpeedCPUAdam([param1, param], lr=0.01)
# torch.set_num_threads(128)
param1.grad = torch.ones(model_size, device=device)
param.grad = torch.ones(model_size, device=device)
avg = 0
for i in range(2):
    start = time.time()
    optimizer.step(fp16_param_groups=[param_fp16_1, param_fp16])
    stop = time.time()
    avg += (stop - start)
    param1.grad = torch.ones(model_size, device=device) * 2
    param.grad = torch.ones(model_size, device=device) * 2
    print('cpu param1: ', param1)
    print('gpu param_fp16_1: ', param_fp16_1.float())
    print('cpu param: ', param)
    print('gpu param_fp16: ', param_fp16.float())
print("Elapsed Time is ", avg / 100)
```
to see if this [step](https://github.com/microsoft/DeepSpeed/blob/8bbf081ad83fbc75f85087856e34d2344577edae/csrc/adam/cpu_adam.cpp#L235) method functions as expected in the latest release but got the following results:

```
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
Time to load cpu_adam op: 0.6612434387207031 seconds
Adam Optimizer #0 is created with AVX512 arithmetic capability.
Config: alpha=0.010000, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
cpu param1:  Parameter containing:
tensor([0.9900, 0.9900, 0.9900,  ..., 0.9900, 0.9900, 0.9900],
       requires_grad=True)
gpu param_fp16_1:  tensor([0.9902, 0.9902, 0.9902,  ..., 0.9902, 0.9902, 0.9902], device='cuda:0',
       grad_fn=<ToCopyBackward0>)
cpu param:  Parameter containing:
tensor([0.9900, 0.9900, 0.9900,  ..., 0.9900, 0.9900, 0.9900],
       requires_grad=True)
gpu param_fp16:  tensor([0.9902, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000], device='cuda:0',
       grad_fn=<ToCopyBackward0>)
cpu param1:  Parameter containing:
tensor([0.9803, 0.9803, 0.9803,  ..., 0.9803, 0.9803, 0.9803],
       requires_grad=True)
gpu param_fp16_1:  tensor([0.9805, 0.9805, 0.9805,  ..., 0.9805, 0.9805, 0.9805], device='cuda:0',
       grad_fn=<ToCopyBackward0>)
cpu param:  Parameter containing:
tensor([0.9803, 0.9803, 0.9803,  ..., 0.9803, 0.9803, 0.9803],
       requires_grad=True)
gpu param_fp16:  tensor([0.9805, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000], device='cuda:0',
       grad_fn=<ToCopyBackward0>)
Elapsed Time is  0.0007363009452819824

```
apparently param_fp16 on gpu is not updated correctly as param_fp16_1 on gpu as only the first element is updated. and params on cpu side looks good to me.  so i suspect that something wrong with https://github.com/microsoft/DeepSpeed/blob/8bbf081ad83fbc75f85087856e34d2344577edae/csrc/adam/cpu_adam.cpp#L235. 

could you help to explain this strange behavior and maybe correct us in terms of possible wrong use? Or a quick fix is appreciated if this is indeed a bug. 

Anyway, looking forward to your attention, thanks.
@jeffra

**Comment by zgsbughammer** [comment]
FYI, torch adam with the same settings shows that:
```
tensor([0.9900, 0.9900, 0.9900,  ..., 0.9900, 0.9900, 0.9900],
       requires_grad=True)
Parameter containing:
tensor([0.9900, 0.9900, 0.9900,  ..., 0.9900, 0.9900, 0.9900],
       requires_grad=True)
Parameter containing:
tensor([0.9803, 0.9803, 0.9803,  ..., 0.9803, 0.9803, 0.9803],
       requires_grad=True)
Parameter containing:
tensor([0.9803, 0.9803, 0.9803,  ..., 0.9803, 0.9803, 0.9803],
       requires_grad=True)
Parameter containing:
tensor([0.9705, 0.9705, 0.9705,  ..., 0.9705, 0.9705, 0.9705],
       requires_grad=True)
Parameter containing:
tensor([0.9705, 0.9705, 0.9705,  ..., 0.9705, 0.9705, 0.9705],
       requires_grad=True)
Parameter containing:
tensor([0.9606, 0.9606, 0.9606,  ..., 0.9606, 0.9606, 0.9606],
       requires_grad=True)
Parameter containing:
tensor([0.9606, 0.9606, 0.9606,  ..., 0.9606, 0.9606, 0.9606],
       requires_grad=True)
Parameter containing:
tensor([0.9506, 0.9506, 0.9506,  ..., 0.9506, 0.9506, 0.9506],
       requires_grad=True)
Parameter containing:
tensor([0.9506, 0.9506, 0.9506,  ..., 0.9506, 0.9506, 0.9506],
       requires_grad=True)
Elapsed Time is  0.00023775577545166016
```

**Comment by RezaYazdaniAminabadi** [comment]
Hi @zgsbughammer 

Thanks for pointing this use-case.
The problem is in the way that you are passing the fp16 parameters to the step function for the kernels to copy data from master parameters. Instead of providing a list of parameters, you need to pass a list of list of parameters (just change `[param_fp16_1, param_fp16] to [[param_fp16_1, param_fp16]]`).
The CPU-Adam optimizer works on a group of parameters. Each group can contain a list of parameters (https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/ops/adam/cpu_adam.py#L172). 
Since, you were passing only a list of data, the first call to the kernel could receive the correct pointer (param_fp16_1[0][0].data_ptr()), however, the second call is getting its pointer as param_fp16_1[0][1].data_ptr(), which is the second element of the first parameter tensor, therefore it will rewrite the same data as in the first call of the kernel plus only one element of second tensor (param_fp16[0][0]).

Thanks,
Reza

**Comment by zgsbughammer** [comment]
@RezaYazdaniAminabadi  Thanks for your quick reply!  
I can get your point according to code here 
https://github.com/pytorch/pytorch/blob/c463d5009868e53ec07e90d0097c30c55280eef2/torch/optim/optimizer.py#L18
obviously torch optimizer organizes params in groups internally. But I still think it would be nicer by making `fp16_param_groups`
consistent with `model_params` https://github.com/microsoft/DeepSpeed/blob/752319c782ee57d9ed02cfadab8bca6e319301ea/deepspeed/ops/adam/cpu_adam.py#L77 passed in the constructor. and some necessary checking routines like https://github.com/pytorch/pytorch/blob/c463d5009868e53ec07e90d0097c30c55280eef2/torch/optim/optimizer.py#L47
does maybe help.

**Comment by RezaYazdaniAminabadi** [comment]
@zgsbughammer 
Thanks for the good suggestion. I have added a PR to address this. Please try it and see if it works on your side.
For the other part of the issue, I look forward to a reproable test to fix it.
Thanks,
Reza

**Comment by tjruwase** [comment]
@zgsbughammer, are you still an issue or can this be closed? Thanks!

**Comment by zgsbughammer** [comment]
@tjruwase Thanks for ur attention, will close
