### ISSUE TITLE
More  flexible port number for distributed training

### ISSUE THREAD

**Issue by boru-roylu** [microsoft/DeepSpeed#1656]
https://github.com/microsoft/DeepSpeed/blob/d93d924a77a3f6a427aad7f1e7d83be9b62d9fb3/deepspeed/constants.py#L9

```python
import os
MASTER_PORT = os.environ['MASTER_PORT']
TORCH_DISTRIBUTED_DEFAULT_PORT = int(MASTER_PORT) if MASTER_PORT else 29500 
```

**Comment by yeegnauh** [comment]
why closed?
i need this feature!!! 
i have tried `deepspeed --master_port 29501`, but still `TORCH_DISTRIBUTED_DEFAULT_PORT = 29500` take effect.

**Comment by jijivski** [comment]
> why closed? i need this feature!!! i have tried `deepspeed --master_port 29501`, but still `TORCH_DISTRIBUTED_DEFAULT_PORT = 29500` take effect.

see https://github.com/microsoft/DeepSpeed/issues/191#issuecomment-1612197919, you should put msater_port before .py

deepspeed --master_port 12345 src/train_biencoder.py --deepspeed ds_config.json instead of deepspeed src/train_biencoder.py --deepspeed ds_config.json  --master_port 12345 did the trick.

worked for me

**Comment by tjruwase** [comment]
@jijivski, can you please share more details of why `--master_port` does not work for you? It would be helpful to share a stack trace, log, and repro steps. Thanks!

**Comment by jijivski** [comment]
Sorry for the late reply and thanks for your kindness. I just found that setting the port to 0 didn't work (someone told me that 0 port should not be used here). But it worked fine after I changed it to another one like 29595.

**Comment by jijivski** [comment]
> [@jijivski](https://github.com/jijivski), can you please share more details of why `--master_port` does not work for you? It would be helpful to share a stack trace, log, and repro steps. Thanks!
Sorry for the late reply and thanks for your kindness. I just found that setting the port to 0 didn't work (someone told me that 0 port should not be used here). But it worked fine after I changed it to another one like 29595.
