### ISSUE TITLE
MoE top1gating not considering capacity when use_rts=False

### ISSUE THREAD

**Issue by chenyu-jiang** [microsoft/DeepSpeed#1658]
Hi,

In the top1gating function, it looks like that dropping tokens that exceeds expert capacity (L232) only happens when use_rts=True:

https://github.com/microsoft/DeepSpeed/blob/d93d924a77a3f6a427aad7f1e7d83be9b62d9fb3/deepspeed/moe/sharded_moe.py#L218-L235

While when generating `locations1_sc` the capacity value is directly used:
https://github.com/microsoft/DeepSpeed/blob/d93d924a77a3f6a427aad7f1e7d83be9b62d9fb3/deepspeed/moe/sharded_moe.py#L261

Will this be a problem? For example, the following code will produce a error:
```python
import torch
import deepspeed
from deepspeed.moe.sharded_moe import top1gating

# all 5 tokens have highest weight on the first expert
logits = torch.Tensor([[1, 0, 0, 0]]*5)

top1gating(logits, 1.0, 4, use_rts=False)
```
output:
```
Traceback (most recent call last):
  File "reproduce.py", line 8, in <module>
    top1gating(logits, 1.0, 4, use_rts=False)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/moe/sharded_moe.py", line 239, in top1gating
    locations1_sc = F.one_hot(locations1_s, num_classes=capacity).float()
RuntimeError: Class values must be smaller than num_classes.
```

Thanks!

**Comment by RezaYazdaniAminabadi** [comment]
Hi @chenyu-jiang 

Yes, you are right the logic is not correct when use-rts is False. I will send a PR shortly to fix this.
Thanks,
Reza
