### ISSUE TITLE
[REQUEST] Plugin with DL model

### ISSUE THREAD

**Issue by jahidhasanlinix** [microsoft/DeepSpeed#1671]
https://github.com/hongzimao/decima-sim
would you like to instruct me how to integrate this above deep learning model into your pipeline. Moreover, how can I integrate or plug it with your frameworks?

**Comment by loadams** [comment]
Closing as this looks to be a stale issue.  The above doesn't appear to be a deep leaning model, but we recommend taking a look at the Getting started section or tutorials in our repo if you are curious to run some models with DeepSpeed.
