### ISSUE TITLE
Does deepspeed support torch 1.3.1 version ?

### ISSUE THREAD

**Issue by jiangxiluning** [microsoft/DeepSpeed#172]

**Comment by ShadenSmith** [comment]
Hi @jiangxiluning, at this moment DeepSpeed is officially tested only on torch 1.2. Unofficially, we have tested through 1.4 and have not encountered issues. We're working to expand our testing infrastructure and officially support more versions of PyTorch.

In the meantime if you'd like to run on 1.3, the easiest way today is to just install DeepSpeed through conda. This should work on Linux:
```bash
conda install deepspeed pytorch=1.3.1 cudatoolkit=10.1 -c deepspeed -c pytorch -c conda-forge
```
Our conda package is also part of the infrastructure that we are expanding, so it's not frequently updated yet. Hopefully within the next week or so it will be a first-class way of installing DeepSpeed and we will officially support more versions.

If you'd like to install from source, you just need to update the version constraints in `requirements.txt` and then install with `./install.sh`. From memory, you can remove all of the version constraints except `tensorboardX` and then constrain `torch==1.3.1`.

If you run DeepSpeed with torch 1.3.1, please let us know if you run into any issues!

**Comment by ShadenSmith** [comment]
Closing the issue, please re-open and if you run into any issues.

**Comment by jiangxiluning** [comment]
@ShadenSmith Thank you, I will try it .

**Comment by Jie-Yuan** [comment]
Does deepspeed support torch 1.4 version ?

**Comment by ShadenSmith** [comment]
Hi @Jie-Yuan, at this moment DeepSpeed is officially tested only on torch 1.2. Unofficially, we have tested through 1.4 and have not encountered issues. We're working to expand our testing infrastructure and officially support more versions of PyTorch.
