### ISSUE TITLE
[REQUEST] Propagate error when using PDSH launcher 

### ISSUE THREAD

**Issue by jerrymannil** [microsoft/DeepSpeed#1722]
**Is your feature request related to a problem? Please describe.**
The default behavior of [PDSH launcher](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/launcher/multinode_runner.py#L69) is to return 0, even if some of the nodes returned with error.
So to determine if the deepspeed run succeeded, we will have to look at the logs coming from the nodes.

**Describe the solution you'd like**
[PDSH](https://linux.die.net/man/1/pdsh) provides '-S' option to return the the largest of the remote command return values.
We can provide this option with the pdsh launcher in deepspeed.

**Comment by jerrymannil** [comment]
I have tested this locally and the error is propagated as expected.
I can submit a fix, if this is OK.

**Comment by jeffra** [comment]
Excellent observation, thank you @jerrymannil. I don't think we had seen this flag to `pdsh` previously, please do submit a PR and we'll merge it quickly. Thank you :)

**Comment by jerrymannil** [comment]
PR #1994 created
