### ISSUE TITLE
[BUG] TypeError: cannot assign 'torch.HalfTensor' as parameter 'attn_ob' (torch.nn.Parameter or None expected)

### ISSUE THREAD

**Issue by callzhang** [microsoft/DeepSpeed#1729]
**Describe the bug**
GPT-Neo init_inference error

**To Reproduce**
```python
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import deepspeed, torch

model_name = 'EleutherAI/gpt-neo-125M'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, pad_token_id=tokenizer.eos_token_id).eval()
deepspeed.init_inference(model, dtype=torch.half, replace_method='auto', replace_with_kernel_inject=True)

# TypeError: cannot assign 'torch.HalfTensor' as parameter 'attn_ob' (torch.nn.Parameter or None expected)
```

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/stardust/anaconda3/lib/python3.8/site-packages/torch']
torch version .................... 1.9.0+cu111
torch cuda version ............... 11.1
nvcc version ..................... 11.4
deepspeed install path ........... ['/home/stardust/anaconda3/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.5.8, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.9, cuda 11.1
```

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU count and types: RTX3090
 - Interconnects: None
 - Python version: 3.8.11
 - Any other relevant info about your setup

**Comment by callzhang** [comment]
Seems I used 0.5.6 in notebook and updates to 0.5.8 solved this issue.

**Comment by callzhang** [comment]
Seems I used 0.5.6 in notebook and updates to 0.5.8 solved this issue.

**Comment by haluptzok** [comment]
I hit the same issue - very similar situation - except I have GPTNeo2.7B - running on a v100 - with latest version of deepspeed and torch

DeepSpeed C++/CUDA extension op report
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/datadrive/patrickh/.local/lib/python3.8/site-packages/torch']
torch version .................... 1.10.2+cu102
torch cuda version ............... 10.2
nvcc version ..................... 10.2
deepspeed install path ........... ['/datadrive/patrickh/.local/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.5.10, unknown, unknown
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0

**Comment by RezaYazdaniAminabadi** [comment]
Hi,

I will send a PR to fix this soon
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
Hi @haluptzok and @callzhang,

can you please try this [PR](https://github.com/microsoft/DeepSpeed/pull/1724) to see if it solves the issue?
Thanks,
Reza
