### ISSUE TITLE
DeepSpeed Examples Should Use DeepSpeed Launcher

### ISSUE THREAD

**Issue by arashashari** [microsoft/DeepSpeed#175]
Currently BingBertSquad is not using DeepSpeed Launcher.
All examples should use the launcher.

**Comment by jeffra** [comment]
https://github.com/microsoft/DeepSpeedExamples/blob/master/BingBertSquad/run_squad_deepspeed.sh#L22

**Comment by tjruwase** [comment]
@arashashari  Thanks for creating this issue, but it really belongs in [DeepSpeedExamples](https://github.com/microsoft/DeepSpeedExamples/issues/11).
