### ISSUE TITLE
[REQUEST] Can I manually change global batch size with checkpoints?

### ISSUE THREAD

**Issue by observerw** [microsoft/DeepSpeed#1796]
As far as I know, deepspeed does not currently support dynamic batch size, but for some reason, I urgently need to use this feature now. So could I achieve a dynamic batch size like effect by using a batch size and saving the checkpoint, then manually changing the batch size in the run script and re-running it? If possible, how should I do this?

**Comment by floatshadow** [comment]
I guess Megatron Fork by DeepSpeed Group may help somehow [Link](https://github.com/microsoft/Megatron-DeepSpeed/blob/3704a0a0dadb40a97a3c273c59f30318c34a5af4/megatron/training.py#L716)

**Comment by observerw** [comment]
> I guess Megatron Fork by DeepSpeed Group may help somehow [Link](https://github.com/microsoft/Megatron-DeepSpeed/blob/3704a0a0dadb40a97a3c273c59f30318c34a5af4/megatron/training.py#L716) Seems it aimed at solving Megatron-LM's `--ramp-up-batch-size` cmd argument.

Thanks for the suggestion, I forgot that this parameter existed in Megatron-deepspeed, Your reminder helped me a lot😂

Fortunately, in my tests, the manual checkpoint to change the batch size also worked correctly. One thing to note is that Megatron-deepspeed only supports iteration-based training, so first we need to set the `--train-samples` to equivalent `--train-iters`. Then, since megatron's lr-scheduler is sample-based, if you use megatron's scheduler, you need to change `--lr-warmup-iters` and `--lr-decay-iters` at the same time as you change the batch size. For example, when your `-global-batch-size` is expanded by a factor of n, then all your `iter`-related parameters need to be shrunk by a factor of n.

I hope my experience can help people with the same needs as me.😄

**Comment by floatshadow** [comment]
indeed deepspeed support checkpoint too. 
I remember Megatron-DeepSpeed Fork replace megatron's checkpoint with `deepspeed.checkpoint` module.
