### ISSUE TITLE
Add representation method to optimizer like pytorch optimizer

### ISSUE THREAD

**Issue by kouml** [microsoft/DeepSpeed#180]
Just an Idea, so Don't hesitate to close if you disagree and priority is so low.

I suggest that optimizer should have `__repr__`  method like[ pytorch's optimizer](https://github.com/pytorch/pytorch/blob/master/torch/optim/optimizer.py#L63) to see the parameters of optimizer human-readable.

**Comment by tjruwase** [comment]
Thanks. This is a good idea. Do you mind contributing a PR? Otherwise, we will keep this open until we get some spare cycles to devote to it.

**Comment by kouml** [comment]
No, I will PR later.
