### ISSUE TITLE
[REQUEST] Extraneous param validation in config

### ISSUE THREAD

**Issue by jbloxham** [microsoft/DeepSpeed#1809]
**Is your feature request related to a problem? Please describe.**
I've had a few times where I've thought I've been configuring DeepSpeed to do something, but it turns out that I misspelled a field name in the config. Ideally, DeepSpeed should be able to detect when this happens.

**Describe the solution you'd like**
When a `DeepSpeedConfig` is created from a dictionary, it should validate that all keys in that dictionary are actually recognized. If not, it should ideally raise an error, or at least surface a loud warning.

**Describe alternatives you've considered**
Client-side validation of config is hard because DeepSpeed is a rapidly evolving project.

**Additional context**
:pray:

**Comment by loadams** [comment]
Hi @jbloxham - this should be supported more now but will be better once we get PyDantic v2 updated so we can validate those fields.
