### ISSUE TITLE
[BUG]: Deepspeed build fails on rocm , error in hipify 

### ISSUE THREAD

**Issue by bmedishe** [microsoft/DeepSpeed#1816]
**Describe the bug**
**hipify_extra_files_only** argument used in op_builder/builder.py not present in https://github.com/ROCmSoftwarePlatform/hipify_torch/blob/master/hipify/hipify_python.py or pytorch/torch/utils/hipify/hipify_python.py 

**To Reproduce**
`git clone https://github.com/microsoft/DeepSpeed.git`
`DS_BUILD_FUSED_ADAM=1 DS_BUILD_FUSED_LAMB=1 DS_BUILD_CPU_ADAM=1 DS_BUILD_TRANSFORMER=1 DS_BUILD_STOCHASTIC_TRANSFORMER=1 DS_BUILD_UTILS=1 ./install.sh --allow_sudo`
 See error

**_Total number of replaced kernel launches: 2
Traceback (most recent call last):
  File "setup.py", line 161, in <module>
    builder.hipify_extension()
  File "/var/lib/jenkins/DeepSpeed_up/op_builder/builder.py", line 625, in hipify_extension
    hipify_extra_files_only=True,
TypeError: hipify() got an unexpected keyword argument 'hipify_extra_files_only'_**

**Expected behavior**
hipify files with no error 

**Screenshots**

**System info (please complete the following information):**
 rocm_arch gfx906

**Docker context**
docker : rocm/pytorch:latest-base  
pytorch installed from source (https://github.com/pytorch/pytorch)

**Comment by bmedishe** [comment]
@jithunnair-amd  @jeffra

**Comment by jeffra** [comment]
Hi @bmedishe, I will let @jithunnair-amd confirm but i believe the docker image you are using doesn't have the latest pytorch-amd changes. I just tested it as well and don't see torch installed for some reason.

Can you try this image instead? I will update our documentation to better guide new AMD users.
`rocm/pytorch:rocm5.0.1_ubuntu18.04_py3.7_pytorch_1.10.0`

**Comment by bmedishe** [comment]
Thank you @jeffra , I will try with the above mentioned image

**Comment by jeffra** [comment]
I just discovered that this image that i just linked to is missing one piece for our kernels to compile correctly. I will discuss with @jithunnair-amd offline on how to update the images to fix this. In the meantime, you'll need to copy the following files from our repo to your rocm source:

```
cp -a csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups.h /opt/rocm/include/hip/hcc_detail/hip_cooperative_groups.h
cp -a csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups.h /opt/rocm/include/hip/hcc_detail/amd_hip_cooperative_groups.h
cp -a csrc/includes/patch/hip/hcc_detail/hip_cooperative_groups_helper.h /opt/rocm/include/hip/hcc_detail/hip_cooperative_groups_helper.h
```

**Comment by jeffra** [comment]
For the time being I have pushed a new docker image based on the one i linked earlier but that includes deepspeed v0.6.0 and the patched coop groups files. You can pull it from here: `deepspeed/deepspeed:v060_rocm5.0.1_ubuntu18.04_py3.7_pytorch_1.10.0`

**Comment by jeffra** [comment]
Feel free to reopen if still an issue
