### ISSUE TITLE
[REQUEST] Why ep_size should be less than world_size?

### ISSUE THREAD

**Issue by Satan012** [microsoft/DeepSpeed#1838]
def _create_expert_and_data_parallel(ep_size):
    """
        Create expert and data parallel groups.

        Note: Caller of this function is responsible to check if the groups already exist.

        Example - E + D parallel
        world_size = 16
        expert_parallel_size = 2 # number of experts in same group
        expert_data_parallel_group = [0,2,4,6,8,10,12,14], [1,3,5,7,9,11,13,15] - all reduce is only on MoE params
        expert_parallel_group = [0, 1], [2,3], [4,5], [6,7], [8,9] - no all reduce, but all to all
        data_parallel_group = [0,1,...,15] - all reduce is only on non-MoE
    """
    assert torch.distributed.is_initialized()

    log_dist(f'Creating expert and data parallel groups with size {ep_size}', ranks=[0])
    world_size = torch.distributed.get_world_size()
    rank = torch.distributed.get_rank()

    expert_parallel_size_ = min(ep_size, world_size)

**Comment by awan-10** [comment]
Thank you for reporting this. We have removed this in this PR: https://github.com/microsoft/DeepSpeed/pull/2074
