### ISSUE TITLE
Do I have to use MOE in a distributed environment？

### ISSUE THREAD

**Issue by drxmy** [microsoft/DeepSpeed#1872]
I exchange the FFN in BART with MOE.  When the model run , it says "Default process group has not been initialized, please make sure to call init_process_group".  I am new to deepspeed. I think this has something to do with distributed environment. 

Any advice would be appreciate. Thank you.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @drxmy,

Can you try initializing the group before creating your model?
`deepspeed.utils.groups.initialize(ep_size=torch.distributed.get_world_size())`

Thanks,
Reza

**Comment by jeffra** [comment]
@drxmy, you should be able to use `deepspeed.utils.init_distributed()`. In a recent update to MoE (v0.6.0+) this groups.initialize function was deprecated and you shouldn't need to use it anymore.

**Comment by drxmy** [comment]
Thank both of you! I will give it a try.
