### ISSUE TITLE
[BUG] `pip install deepspeed==0.6.2` raises `ModuleNotFoundError: No module named 'op_builder'`

### ISSUE THREAD

**Issue by akihironitta** [microsoft/DeepSpeed#1918]
**Describe the bug**
I'd like to report a possible bug in the installation of `0.6.2` in particular.

**To Reproduce**
```console
$ # === from the host ===
$ docker pull pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.11
$ docker run --rm -it --gpus all --ipc host pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.11
$ # === within the container ===
$ pip list | grep -e deepspeed -e torch
deepspeed                     0.6.1
torch                         1.11.0+cu113
torchmetrics                  0.8.0
torchtext                     0.12.0
torchvision                   0.12.0+cu113
$ pip uninstall deepspeed -y
$ pip install deepspeed==0.6.2
Collecting deepspeed==0.6.2
  Downloading deepspeed-0.6.2.tar.gz (542 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.4/542.4 KB 19.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-brk5ad19/deepspeed_e004efb3362a460e85f320ebf0a47444/setup.py", line 35, in <module>
          from op_builder import ALL_OPS, get_default_compute_capabilities, OpBuilder
      ModuleNotFoundError: No module named 'op_builder'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

FYI, installing other versions succeeds.
```console
$ pip install deepspeed==0.6.1  # or other versions I've tried
```

**Expected behavior**
Successful installation with no error raised.
```
pip install deepspeed==0.6.2
```

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**
Please refer to the commands above or to our CI run: https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=69269&view=logs&j=3afc50db-e620-5b81-6016-870a6976ad29&t=96e63b50-ac1f-5745-9558-05f9481cd089&l=17

**System info (please complete the following information):**
 - OS: `Linux ad93fadeb85f 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version: 3.7
 - Any other relevant info about your setup

**Launcher context**
n/a

**Docker context**
```
docker pull pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.11
```

**Additional context**
Encountered this issue while working on https://github.com/PyTorchLightning/pytorch-lightning/issues/12881.

**Comment by akihironitta** [comment]
My current workaround is cloning the repository and run `pip install .` as done in https://github.com/PyTorchLightning/pytorch-lightning/pull/12373/commits/42bb05ddbe0b2df29ba32331c4a9631d00a089cc

**Comment by jeffra** [comment]
Yikes, we are seeing this now as well. Something went wrong with the latest 0.6.2 release. We are investigating right now and will probably pull this release and push a new one today. Installing from source seems to resolve the issue for now luckily.

**Comment by akihironitta** [comment]
Confirmed 0.6.3 works. Thank you for deploying the fix quickly.

**Comment by silvacarl2** [comment]
I am seeing the exact same error on Ubuntu 22.04

**Comment by KurtFeynmanGodel** [comment]
Any fix for this issue?

> @jeffra when I install it via `DS_BUILD_OPS=1 pip install deepspeed`, it still shows the same error
> 
> Collecting deepspeed Using cached deepspeed-0.6.5.tar.gz (567 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [16 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/tmp/pip-install-yzov2mdg/deepspeed_6ba447bdc13945b09054de7e8edfceac/setup.py", line 152, in abort(f"Unable to pre-compile {op_name}") File "/tmp/pip-install-yzov2mdg/deepspeed_6ba447bdc13945b09054de7e8edfceac/setup.py", line 48, in abort assert False, msg AssertionError: Unable to pre-compile sparse_attn DS_BUILD_OPS=1 [WARNING] cpu_adam attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information. [WARNING] cpu_adam attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information. [WARNING] cpu_adagrad attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information. [WARNING] cpu_adagrad attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information. [WARNING] please install triton==1.0.0 if you want to use sparse attention [WARNING] One can disable sparse_attn with DS_BUILD_SPARSE_ATTN=0 [ERROR] Unable to pre-compile sparse_attn [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

Seeing the same thing. Any fix for this issue?

**Comment by brurpo** [comment]
Same issue on windows, 0.8.3

**Comment by eureka336** [comment]
same in ubuntu,22.04

**Comment by kacecarol** [comment]
sam issue on windows, 0.12.6 3070Ti laptop. Forever No module named 'op_builder'
