### ISSUE TITLE
1.5B gpt2 training with zero enabled got "CUDA out of memory" on Nividia V100 (32GB)

### ISSUE THREAD

**Issue by lwdhw1987** [microsoft/DeepSpeed#192]
In the Megatron tutorial I found you can train 1.5B gpt2 with zero enabled on V100(32GB)，But I tried and got "CUDA out of memory" with the same configuration,  Could you help me check my configuration 

My enviroment and test output  :
root@localhost186:Megatron-LM# nvidia-smi
Fri Apr 17 03:56:54 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:2D:00.0 Off |                    0 |
| N/A   41C    P0    55W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:32:00.0 Off |                    0 |
| N/A   40C    P0    54W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:5B:00.0 Off |                    0 |
| N/A   41C    P0    58W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:5F:00.0 Off |                    0 |
| N/A   38C    P0    55W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  Off  | 00000000:B5:00.0 Off |                    0 |
| N/A   40C    P0    56W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  Off  | 00000000:BE:00.0 Off |                    0 |
| N/A   37C    P0    55W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  Off  | 00000000:DF:00.0 Off |                    0 |
| N/A   41C    P0    56W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  Off  | 00000000:E7:00.0 Off |                    0 |
| N/A   40C    P0    55W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
root@localhost186:Megatron-LM#

root@localhost186:Megatron-LM# cat scripts/ds_config.json
{
  "train_batch_size": 256,
  "gradient_accumulation_steps": 1,
  "steps_per_print": 10,
  "zero_optimization": true,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.00015,
      "max_grad_norm": 1.0
    }
  },

  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  "wall_clock_breakdown": true
}

root@localhost186:Megatron-LM# cat scripts/ds_pretrain_gpt2_model_parallel.sh
#! /bin/bash

# Change for multinode config
MASTER_ADDR=localhost
MASTER_PORT=6000
MP_SIZE=1

script_path=$(realpath $0)
script_dir=$(dirname $script_path)

config_json="$script_dir/ds_config.json"
gpt_options=" \
       --model-parallel-size ${MP_SIZE} \
       --num-layers 48 \
       --hidden-size 1600 \
       --num-attention-heads 16 \
       --batch-size 32 \
       --seq-length 1024 \
       --max-position-embeddings 1024 \
       --train-iters 105 \
       --resume-dataloader \
       --train-data webtext \
       --lazy-loader \
       --tokenizer-type GPT2BPETokenizer \
       --split 949,50,1 \
       --distributed-backend nccl \
       --lr 0.00015 \
       --no-load-optim \
       --lr-decay-style cosine \
       --weight-decay 1e-2 \
       --clip-grad 1.0 \
       --warmup .01 \
       --checkpoint-activations \
       --fp16 \
       --deepspeed \
       --deepspeed_config ${config_json} \
"

run_cmd="deepspeed.pt --num_nodes 1 --num_gpus 8  pretrain_gpt2.py $@ ${gpt_options}"
echo ${run_cmd}
eval ${run_cmd}

Traceback (most recent call last):
  File "pretrain_gpt2.py", line 676, in <module>
    main()
  File "pretrain_gpt2.py", line 653, in main
    timers, args)
  File "pretrain_gpt2.py", line 413, in train
    args, timers)
  File "pretrain_gpt2.py", line 363, in train_step
    lm_loss = forward_step(data_iterator, model, args, timers)
  File "pretrain_gpt2.py", line 287, in forward_step
    labels)
  File "/home/p00306424/DeepSpeed/DeepSpeedExamples/Megatron-LM/mpu/cross_entropy.py", line 109, in vocab_parallel_cross_entropy
    return _VocabParallelCrossEntropy.apply(vocab_parallel_logits, target)
  File "/home/p00306424/DeepSpeed/DeepSpeedExamples/Megatron-LM/mpu/cross_entropy.py", line 40, in forward
    exp_logits = logits.exp()
RuntimeError: CUDA out of memory. Tried to allocate 6.14 GiB (GPU 2; 31.75 GiB total capacity; 22.29 GiB already allocated; 2.73 GiB free; 27.89 GiB reserved in total by PyTorch)

**Comment by tjruwase** [comment]
@lwdhw1987 Thanks for using DeepSpeed. 

The problem here is that you are using a very large per-step batch size (i.e., micro batch size) of 32 per GPU. This is much larger than can be supported for data parallelism (DP) degree of 8. The way ZeRO works is that the micro batch size grows with the DP degree (See Table 1 in [paper](https://arxiv.org/pdf/1910.02054.pdf)). The tutorial uses DP degree of 64, which is why micro batch size of 32 is possible. For DP=8, can you try a lower micro batch size such as 8 or lower?
