### ISSUE TITLE
[BUG] Multi-Node Address in Use Error

### ISSUE THREAD

**Issue by Sanger2000** [microsoft/DeepSpeed#1923]
**Describe the bug**
I am running deepspeed on AWS Sagemaker over 4 machines with 4V100's each (their p3.8xlarge's). I use a custom docker image in order to run deepspeed (Sagemaker does not natively support deepspeed).

The command used is:

`deepspeed --hostfile=hostfile.txt --master_port=29600 main.py`

What I believe happens, is that for $$m$$ machines with $$n$$ GPU's each, instead of starting $$m*n$$ processes, deepspeed starts $$m^2*n$$. Each machine shows that deepspeed is running 16 processes, but these are all unique processes resulting in 64 being run at the same time. 

I verified that it was actually 64, and not just 16 with the logs being output to each machine, since the logs differed (only one of the machines did not error). I also printed out time.time() at the same point in the code, and obtained different results for what should have been the same process on the logs of the different machines.

Running the same exact code on just 1 machine works perfectly fine, the issue is when performing distributed training. As a preface, algo-1 is the hostname of the machine that fails.

The exact error log is:
algo-1: Traceback (most recent call last):
algo-1:   File "main.py", line 191, in <module>
algo-1:     main(args)
algo-1:   File "main.py", line 185, in main
algo-1:     trainer = DeepspeedTrainer(model, train_dataset, valid_dataset, args)
algo-1:   File "/cursor-ml/cad_ml/train/train_deepspeed.py", line 28, in __init__
algo-1:     super().__init__(model, train_dataset, valid_dataset, args)
algo-1:   File "/cursor-ml/cad_ml/train/train.py", line 31, in __init__
algo-1:     self.setup()
algo-1:   File "/cursor-ml/cad_ml/train/train_deepspeed.py", line 37, in setup
algo-1:     self.engine, _, __, ___ = deepspeed.initialize(
algo-1:   File "/root/anaconda3/envs/cursor-ml/lib/python3.8/site-packages/deepspeed/__init__.py", line 119, in initialize
algo-1:     engine = DeepSpeedEngine(args=args,
algo-1:   File "/root/anaconda3/envs/cursor-ml/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 233, in __init__
algo-1:     init_distributed(dist_backend=self.dist_backend)
algo-1:   File "/root/anaconda3/envs/cursor-ml/lib/python3.8/site-packages/deepspeed/utils/distributed.py", line 49, in init_distributed
algo-1:     torch.distributed.init_process_group(backend=dist_backend,
algo-1:   File "/root/anaconda3/envs/cursor-ml/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 576, in init_process_group
algo-1:     store, rank, world_size = next(rendezvous_iterator)
algo-1:   File "/root/anaconda3/envs/cursor-ml/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 229, in _env_rendezvous_handler
algo-1:     store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
algo-1:   File "/root/anaconda3/envs/cursor-ml/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 157, in _create_c10d_store
algo-1:     return TCPStore(
algo-1: RuntimeError: Address already in use
 
**To Reproduce**
1. Start a sagemaker job on 4 ml.p3.8xlarge instances
2. Run `deepspeed --hostfile=hostfile.txt --master_port=29600 main.py` given a standard training loop

**Expected behavior**
I expect the training script to properly execute

**ds_report output**
Please run `ds_report` to give us details about your setup.
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
async_io ............... [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/root/anaconda3/envs/cursor-ml/lib/python3.8/site-packages/torch']
torch version .................... 1.10.2+cu102
torch cuda version ............... 10.2
nvcc version ..................... 10.0
deepspeed install path ........... ['/root/anaconda3/envs/cursor-ml/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.5.10, unknown, unknown
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - 4 machines with 4 V100's each
 - I believe four machines with 10 GB/s bandwidth
 - Python 3.8.12

**Launcher context**
I am using the Deepspeed launcher.

**Docker context**
I believe it resembles the Deepspeed [dockerfile](https://github.com/microsoft/DeepSpeed/blob/master/docker/Dockerfile), but with a few additional changes.

**Comment by tjruwase** [comment]
@Sanger2000, can you please:

1. Share the contents of hostfile.txt 
2. Run with this command:   `deepspeed --num_nodes 4 --num_gpus 4  --hostfile=hostfile.txt --master_port=29600  main.py`

**Comment by Sanger2000** [comment]
hosfile.txt is:
```
algo-1 slots=4
algo-2 slots=4
algo-3 slots=4
algo-4 slots=4
```

Running with that command gives the same error.

**Comment by tjruwase** [comment]
@Sanger2000, thanks for sharing these results. This is quite mysterious and could be tricky to unravel since we don't have the environment to repro. Here are some thoughts

1. Can you share this portion of your logs for failing (4-node) and suceeding (1-node) runs?
<img width="592" alt="image" src="https://user-images.githubusercontent.com/4271600/165958361-7c7bba12-bd32-424a-a96f-1e10c9eabb72.png">

2. Can you fix `--num_gpus 1` and run with `--num_nodes` for 1, 2, 4? Share the corresponding log snippet from (1) for these 4 runs. Perhaps, that could shed some light.

@jeffra  and @mrwyattii  FYI

**Comment by Sanger2000** [comment]
## 1
For the succeeding 1-node run:
```
[2022-04-28 04:19:02,152] [INFO] [launch.py:96:main] WORLD INFO DICT: {'algo-1': [0, 1, 2, 3, 4, 5, 6, 7]}
[2022-04-28 04:19:02,152] [INFO] [launch.py:102:main] nnodes=1, num_local_procs=8, node_rank=0
[2022-04-28 04:19:02,153] [INFO] [launch.py:115:main] global_rank_mapping=defaultdict(<class 'list'>, {'algo-1': [0, 1, 2, 3, 4, 5, 6, 7]})
[2022-04-28 04:19:02,153] [INFO] [launch.py:116:main] dist_world_size=8
[2022-04-28 04:19:02,153] [INFO] [launch.py:118:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
```

For the failing 4-node run, on machine 1, we have 4 sets of these logs in the following order:
```
algo-3: [2022-04-29 01:22:48,031] [INFO] [launch.py:96:main] WORLD INFO DICT: {'algo-1': [0, 1, 2, 3], 'algo-2': [0, 1, 2, 3], 'algo-3': [0, 1, 2, 3], 'algo-4': [0, 1, 2, 3]}
algo-3: [2022-04-29 01:22:48,032] [INFO] [launch.py:102:main] nnodes=4, num_local_procs=4, node_rank=2
algo-3: [2022-04-29 01:22:48,032] [INFO] [launch.py:115:main] global_rank_mapping=defaultdict(<class 'list'>, {'algo-1': [0, 1, 2, 3], 'algo-2': [4, 5, 6, 7], 'algo-3': [8, 9, 10, 11], 'algo-4': [12, 13, 14, 15]})
algo-3: [2022-04-29 01:22:48,032] [INFO] [launch.py:116:main] dist_world_size=16
algo-3: [2022-04-29 01:22:48,032] [INFO] [launch.py:118:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
```

```
algo-2: [2022-04-29 01:22:48,133] [INFO] [launch.py:96:main] WORLD INFO DICT: {'algo-1': [0, 1, 2, 3], 'algo-2': [0, 1, 2, 3], 'algo-3': [0, 1, 2, 3], 'algo-4': [0, 1, 2, 3]}
algo-2: [2022-04-29 01:22:48,133] [INFO] [launch.py:102:main] nnodes=4, num_local_procs=4, node_rank=1
algo-2: [2022-04-29 01:22:48,133] [INFO] [launch.py:115:main] global_rank_mapping=defaultdict(<class 'list'>, {'algo-1': [0, 1, 2, 3], 'algo-2': [4, 5, 6, 7], 'algo-3': [8, 9, 10, 11], 'algo-4': [12, 13, 14, 15]})
algo-2: [2022-04-29 01:22:48,133] [INFO] [launch.py:116:main] dist_world_size=16
algo-2: [2022-04-29 01:22:48,133] [INFO] [launch.py:118:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
```

```
algo-4: [2022-04-29 01:22:48,162] [INFO] [launch.py:96:main] WORLD INFO DICT: {'algo-1': [0, 1, 2, 3], 'algo-2': [0, 1, 2, 3], 'algo-3': [0, 1, 2, 3], 'algo-4': [0, 1, 2, 3]}
algo-4: [2022-04-29 01:22:48,162] [INFO] [launch.py:102:main] nnodes=4, num_local_procs=4, node_rank=3
algo-4: [2022-04-29 01:22:48,162] [INFO] [launch.py:115:main] global_rank_mapping=defaultdict(<class 'list'>, {'algo-1': [0, 1, 2, 3], 'algo-2': [4, 5, 6, 7], 'algo-3': [8, 9, 10, 11], 'algo-4': [12, 13, 14, 15]})
algo-4: [2022-04-29 01:22:48,162] [INFO] [launch.py:116:main] dist_world_size=16
algo-4: [2022-04-29 01:22:48,162] [INFO] [launch.py:118:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
```

```
algo-1: [2022-04-29 01:22:48,359] [INFO] [launch.py:96:main] WORLD INFO DICT: {'algo-1': [0, 1, 2, 3], 'algo-2': [0, 1, 2, 3], 'algo-3': [0, 1, 2, 3], 'algo-4': [0, 1, 2, 3]}
algo-1: [2022-04-29 01:22:48,359] [INFO] [launch.py:102:main] nnodes=4, num_local_procs=4, node_rank=0
algo-1: [2022-04-29 01:22:48,360] [INFO] [launch.py:115:main] global_rank_mapping=defaultdict(<class 'list'>, {'algo-1': [0, 1, 2, 3], 'algo-2': [4, 5, 6, 7], 'algo-3': [8, 9, 10, 11], 'algo-4': [12, 13, 14, 15]})
algo-1: [2022-04-29 01:22:48,360] [INFO] [launch.py:116:main] dist_world_size=16
algo-1: [2022-04-29 01:22:48,360] [INFO] [launch.py:118:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
```

On each of the other machines (2-4), they have identical logs (though with different orderings of algo-1, 2, 3, 4).

## 2
Would you like for me to run all of these commands with the 4 machines housing 4 GPUs each or any with a single machine?

**Comment by tjruwase** [comment]
@Sanger2000, thanks for sharing these results. One clarification, please. Can you please confirm that in all cases you only do one invocation of deepspeed and only on algo-1?

**Comment by tjruwase** [comment]
For (2), please run each of the 3 commands from algo-1 only.

**Comment by tjruwase** [comment]
@Sanger2000, did you make any progress here? Thanks!

**Comment by Sanger2000** [comment]
> @Sanger2000, thanks for sharing these results. One clarification, please. Can you please confirm that in all cases you only do one invocation of deepspeed and only on algo-1?

I see, I assumed that I needed to invoke deepspeed on all machines. If I just ran the deepspeed command from the rank 0 machine, would this solve my problem?

I can try this first before running set of commands you suggested. As an additional clarification, for each of the commands you asked for, should I allocate the corresponding number of additional nodes for passwordless ssh access (num_nodes 1 - just algo-1 is running, num_nodes 2 - algo-1 has access to algo-2, num_nodes 3 algo-1 has access to algo-2, algo-3, algo-4).

**Comment by tjruwase** [comment]
> I see, I assumed that I needed to invoke deepspeed on all machines. If I just ran the deepspeed command from the rank 0 machine, would this solve my problem?

Oh yes, you are only supposed to execute deepspeed on one of the machines, not all of them. Launching on all of them would explain the issues you are having.

**Comment by tjruwase** [comment]
@Sanger2000, do you have any updates on this issue? Thanks!

**Comment by Sanger2000** [comment]
Hey @tjruwase, running deepspeed from a single machine rather than all at the same time solved this issue.

Thanks!
