### ISSUE TITLE
[BUG] No Model Parameters Specified with Latest Release

### ISSUE THREAD

**Issue by jmwoloso** [microsoft/DeepSpeed#1926]
**Describe the bug**

**To Reproduce**
1. Install `deepspeed==0.6.3`
2. Launch the job from the command-line via ptl
3. Monitor logs for model specifications
4. See error (Deepspeed reports 0 trainable parameters and 0 parameters overall)

**Expected behavior**
I expect model parameters to be reported in the logging

**This is (correct) output from running the same code using `deepspeed==0.5.10`**
![image](https://user-images.githubusercontent.com/7530947/165984678-b06585fa-9083-4413-99a6-ba9ac1f14ef8.png)

**ds_report output**
```
ds_report
/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/xgboost/compat.py:93: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/torch']
torch version .................... 1.11.0+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed install path ........... ['/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.6.3, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.11, cuda 11.3
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7530947/165982585-3eca168c-61f9-464f-af92-3e5b369e346b.png)

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]: Ubuntu 18.04
 - GPU count and types [e.g. two machines with x8 A100s each]: 1 Node - 4 V100s (Azure `NC24s_v3` Compute Instance in AMLS)
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]: N/A
 - Python version: `3.8.10`
 - Any other relevant info about your setup: `deepspeed==0.5.10` correctly displays parameter info

**Launcher context**
```
PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32 TOKENIZERS_PARALLELISM="true" python run_ptl.py --accelerator=gpu --devices=4 --strategy="deepspeed_stage_3" --precision=16 --batch_size=1 --max_epochs=1 --model_architecture="distilbert-base-uncased" --max_seq_length=512 --num_workers=24 --pin_memory=True --distributed_backend=deepspeed_stage_3 --accumulate_grad_batches=8
```

**Docker context**
I am using docker but I cannot share the image

**Additional context**
This works in `deepspeed==0.5.10`. I haven't tried any of the other `0.6.x` releases because they contain a [bug](#1878) that was just fixed in the latest version. The referenced issue also has the same (reproducible) code that I'm using for this issue if you need it.

**Comment by jessecambon** [comment]
I'm also seeing this behaviour with `strategy="deepspeed_stage_3"` and `strategy="deepspeed_stage_3_offload"`. However, `strategy="deepspeed_stage_2"` and `strategy="deepspeed_stage_1"` show the number of parameters.

**Comment by tjruwase** [comment]
@SeanNaren, is this printout from Lightning?

**Comment by jessecambon** [comment]
FYI a similar issue is posted in lightning here https://github.com/PyTorchLightning/pytorch-lightning/issues/12130

**Comment by tjruwase** [comment]
@jessecambon, thanks for sharing that link. I see that the issue went stale in lightning. Hopefully, @SeanNaren can provide more context.

**Comment by SeanNaren** [comment]
Apologies for the late response here, this is a Lightning issue (doesn't have anything to do with DeepSpeed). 

@tjruwase I'll sync offline with you on how we potentially could try to resolve this!

**Comment by jmwoloso** [comment]
thank you both for looking @tjruwase @SeanNaren! we can close this if you're tracking it elsewhere.
