### ISSUE TITLE
[BUG] DeepSpeed command is not installing

### ISSUE THREAD

**Issue by knagrecha** [microsoft/DeepSpeed#1927]
I installed deepspeed with pip3 install deepspeed. However none of the commands (e.g. ds_report, deepspeed script.py) work. I get the following error:

ds_report: command not found
deepspeed: command not found.

I'm running this on an EC2 instance with an A10G GPU.

I have tried installing from the repo directly as well and still encounter this error. As I understand it, the deepspeed command is critical to using this framework, and running scripts with python directly is not advised. Does anyone know why the command is not working for me?

**Comment by knagrecha** [comment]
Can't believe I didn't figure this out immediately...I just had to add the bin directory to path.

**Comment by jokerjoey** [comment]
Hi, may I know which bin directory you added in your path?
