### ISSUE TITLE
Can't run ZeRO on single GPU with windows11[BUG]

### ISSUE THREAD

**Issue by Sagivfer** [microsoft/DeepSpeed#1928]
Hi,
been trying to implement ZeRO and stumbled into this loop:
1) Tried a configuration with Zero optimization with an Adam optimizer. It raised the error:
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

2) After reading through the code, found out it is raised if we don't allow AMP. I then added amp in the config file. Then I got the error:
AssertionError: Amp and ZeRO are not currently compatible, please use (legacy) fp16 mode which performs similar to amp opt_mode=O2

3) In response to that I added fp16 and got the error:
ValueError: torch.float32 is enabled but the following parameters have dtype that is not torch.float32: [<different nn.modules with half percision>]

4) I then removed amp and got back to the start with the in place thing...

I'm running the code on notebook with:
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "9994"  # modify if RuntimeError: Address already in use
os.environ["RANK"] = "0"
os.environ["LOCAL_RANK"] = "0"
os.environ["WORLD_SIZE"] = "1"

I'm also initializing a distributed backhand with
deepspeed.init_distributed(dist_backend='gloo')

I'm doing so because I'm running it on windows 11.

Have a single gpu, Python 3.7,  

Here are the configurations with the errors alongside them.
Thank you for the help in advance.

![no_amp_no_fp16](https://user-images.githubusercontent.com/61480454/166104559-ba52a2eb-1bda-4e7c-86be-85b3fa061bdb.png)
![amp_fp16](https://user-images.githubusercontent.com/61480454/166104562-c97bb8c9-6a92-46e5-945a-5dad0933cc18.png)
![no_amp_fp16](https://user-images.githubusercontent.com/61480454/166104563-ee204349-07a0-40ef-a3f7-6f3e0d586d3e.png)

**Comment by loadams** [comment]
Hi @Sagivfer - sorry for the very late reply.  Is this something you are still struggling with?  

If so, two suggestions, one, could you try again with the latest DeepSpeed that way it would be easier for all of us to debug?  And two, if you are on Windows, its much easier to use WSL if possible since then you are able to use all features of DeepSpeed.  Though we know this isn't an option for all users, it can help some.

Thanks!

**Comment by loadams** [comment]
@Sagivfer - closing issue as it is stale.  If you are still encountering this, please re-open this issue and I'll gladly take a look.
