### ISSUE TITLE
[Question] What is the non-deprecated alternative for "cpu_offload"?

### ISSUE THREAD

**Issue by Pringled** [microsoft/DeepSpeed#1935]
**Environment details**
python 3.8
deepspeed==0.6.1
pytorch-lightning==1.6.0

**Problem description**
I have been trying to fit a large model into memory in pytorch lightning using deepspeed. When I set my config with "cpu_offload": True, I get a substantial decrease in used memory (and increase to epoch time) as expected. However, as "cpu_offload" is deprecated, I tried to use "offload_optimizer", as recommended in https://www.deepspeed.ai/docs/config-json/, but it doesn't seem to do anything. Am I missing something?

Relevant part of my configs:

**With cpu_offload**
    "zero_optimization": {
        "stage": 2,
       "allgather_partitions": True,
       "allgather_bucket_size": 1e7,
       "reduce_scatter": True,
       "reduce_bucket_size": 1e7,
        "overlap_comm": True,
        "contiguous_gradients": True,
        "cpu_offload": True
    },
    
**With offload_optimizer**
    "zero_optimization": {
        "stage": 2,
       "allgather_partitions": True,
       "allgather_bucket_size": 1e7,
       "reduce_scatter": True,
       "reduce_bucket_size": 1e7,
        "overlap_comm": True,
        "contiguous_gradients": True,
    },
  "offload_optimizer": {
    "device": "cpu",
    "pin_memory": True,
    "buffer_count": 4,
    "fast_init": False
  },

**Comment by tjruwase** [comment]
@Pringled, thanks for raising this issue. Can you try moving the "offload_optimizer" entry into the "zero_optimization" one?

**Comment by tjruwase** [comment]
@Pringled, more specifically should look like 
```json
 "zero_optimization" : {
  ...
      "offload_optimizer": {
          "device": "cpu",
          "pin_memory": True,
          "buffer_count": 4,
         "fast_init": False
    },
    ....
}

**Comment by Pringled** [comment]
That was indeed the issue, thank you for the quick reply!

**Comment by tjruwase** [comment]
Thanks for quickly confirming resolution. This issue has it clear that the docs is confusing by not explicitly showing that "offload_optimizer" is a subfield of "zero_optimization". So that needs to be fixed.
