### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hjkrt92** [microsoft/DeepSpeed#1937]
**Describe the bug**
subprocess.CalledProcessError: Command '['hostname -I']' returned non-zero exit status 1
I met the CalledProcessError.
I installed MPI and mpi4py.
 what's the problem and what should i do?
what's mean ['hostname -I']
It's my first time try to do deepspeed. 

**ds_report output**
 [WARNING]  sparse_attn requires the 'cmake' command, but it does not exist!
 [WARNING]  sparse_attn requires CUDA version 10.1+, does not currently support >=11 or <10.1
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
 [WARNING]  async_io requires the libraries: ['libaio-dev'] but are missing.
async_io ............... [NO] ....... [NO]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['D:\\meta2\\venv\\lib\\site-packages\\torch']
torch version .................... 1.11.0+cu113
torch cuda version ............... 11.3
nvcc version ..................... 11.4
deepspeed install path ........... ['D:\\meta2\\venv\\lib\\site-packages\\deepspeed']
deepspeed info ................... 0.3.16, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.11, cuda 11.3

**Screenshots**
import deepspeed

deepspeed.init_distributed()

'"hostname -I"'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
Traceback (most recent call last):
  File "D:/meta2/GROWTH2.py", line 18, in <module>
    deepspeed.init_distributed()
  File "D:\meta2\venv\lib\site-packages\deepspeed\utils\distributed.py", line 42, in init_distributed
    mpi_discovery(distributed_port=distributed_port, verbose=verbose)
  File "D:\meta2\venv\lib\site-packages\deepspeed\utils\distributed.py", line 67, in mpi_discovery
    result = subprocess.check_output(hostname_cmd, shell=True)
  File "D:\python\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "D:\python\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['hostname -I']' returned non-zero exit status 1.

**System info (please complete the following information):**
 - OS: [window10 64bit]
 - GPU count and types [v100]
 - Python version 3.7

**Comment by hjkrt92** [comment]
Thanks!

**Comment by tjruwase** [comment]
@hjkrt92, can this issue be closed? Thanks!

**Comment by jeffra** [comment]
@hjkrt92, please re-open if this is still an issue. Thank you :)
