### ISSUE TITLE
How to use other optimizers not in deepspeed？

### ISSUE THREAD

**Issue by GlacierMelt** [microsoft/DeepSpeed#196]
Like ranger, Radam, etc.

**Comment by ShadenSmith** [comment]
Thank you for your interest in DeepSpeed!

There are two ways to specify an optimizer.

The first and most flexible method is to simply initialize your own optimizer of choice and supply it to `deepspeed.initialize()`. There's more documentation on that [here](https://deepspeed.readthedocs.io/en/latest/deepspeed.html#deepspeed.initialize). For example:

```python
 model_engine, my_optimizer, __, __ = deepspeed.initialize(args=cmd_args, 
                                                           model=net,
                                                           optimizer=my_optimizer)
```

The second method is to specify it in your DeepSpeed JSON configuration file. There is more discussion on that [here](https://www.deepspeed.ai/docs/config-json/#optimizer-parameters). Optimizers specified here should be importable via [torch.optim](https://pytorch.org/docs/stable/optim.html).

**Comment by tjruwase** [comment]
@GlacierMelt Also see #153 for details on the support.

**Comment by GlacierMelt** [comment]
Oh, I got it. Thanks.
