### ISSUE TITLE
partition the model

### ISSUE THREAD

**Issue by milad1378yz** [microsoft/DeepSpeed#1976]
Hi, I have a question and is: how does DeepSpeed partition the model into subparts? (especially in [inference](https://www.deepspeed.ai/tutorials/inference-tutorial/) mode)

**Comment by jeffra** [comment]
Hi @milad1378yz, we recently put out a paper diving into more details of our inference approaches. Please take a look if you're interested: https://arxiv.org/abs/2207.00032.

Feel free to re-open if you have further questions, etc.
