### ISSUE TITLE
Megatron-LM BERT

### ISSUE THREAD

**Issue by sj6077** [microsoft/DeepSpeed#200]
I left an issue here(https://github.com/microsoft/DeepSpeedExamples/issues/18). 
There's a BERT tutorial using Bing BERT but not the Megatron-LM version. 
Is there any big difference between BERT and GPT2 of Megatron-LM?

**Comment by jeffra** [comment]
I don't think we have (officially) added DeepSpeed to Megatron's version of Bert. I think I have heard some folks who have done this though. There shouldn't be anything fundamentally preventing DeepSpeed from running with Megatron BERT though so give it a try and let us know if you run into any issues or have questions :) Would absolutely welcome a PR into our examples repo!

**Comment by jeffra** [comment]
Will respond to your issue directly in the other thread.

**Comment by sj6077** [comment]
@jeffra Thanks!
