### ISSUE TITLE
[BUG] Unable to access the model passed to engine using dot operator

### ISSUE THREAD

**Issue by vishalghor** [microsoft/DeepSpeed#2023]
**Describe the bug**
I believe when passing various arguments to a call as init, one would like to reference or use the passed argument such as model which is a torch.nn.module type for either using it view the model params and analyse and optimizer for similar purpose.
But if one tries to access the model as engine.model it enters into a infinite recursion-error due to getattr
**To Reproduce**
1. Create a class which inherits DeepspeedEngine
2. Pass the arg/kwargs which include the model, optimizers etc.
3. create an object of the new class and using that try to access nn_model = engine.model
New class:

```
class DeepSpeedEngineWrapper(DeepSpeedEngine):
    """
    Wrapper over deepspeed.DeepSpeedEngine object
    *** REferenced from huggin_Face/accelerate***
    """

    def __init__(self,*args,model=model,**kwargs):
        DeepSpeedEngine.__init__(self,*args,model=model,**kwargs)
```
Error trace: 

```
----> 3 nn_model = engine.model#__dict__['_modules']#taaumodel#getmodel()
      4 if isinstance(tmodel, torch.nn.Module):
      5     print("True")

~/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py in __getattr__(self, name)
    431             _module = self.__dict__['module']
    432         if name in dir(self):
--> 433             return getattr(self, name)
    434         elif name in dir(_module):
    435             return getattr(_module, name)

... last 1 frames repeated, from the frame below ...

~/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py in __getattr__(self, name)
    431             _module = self.__dict__['module']
    432         if name in dir(self):
--> 433             return getattr(self, name)
    434         elif name in dir(_module):
    435             return getattr(_module, name)

RecursionError: maximum recursion depth exceeded while calling a Python object

```
**Expected behavior**
Usual expected behaviour is it returning the nn.Module obj .

**ds_report output**
NA

**Screenshots**
NA
**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by mrwyattii** [comment]
Hi @vishalghor , please take a look at https://github.com/microsoft/DeepSpeed/blob/c87f6ee209e2fed141ac4e2e28d4169f159ea487/deepspeed/runtime/engine.py#L172

You will see that `DeepSpeedEngine` is inheriting from `torch.nn.modules.Module`. This class does not have a `model` attribute. You can see all the attributes/methods it has using your Engine Wrapper setup:
```python
import torch
import deepspeed

class TinyModel(torch.nn.Module):

    def __init__(self):
        super(TinyModel, self).__init__()

        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

class Wrapper(deepspeed.DeepSpeedEngine):
    def __init__(self, **kwargs):
        print(kwargs)
        super().__init__(args=None, **kwargs)

model = TinyModel()
ds_config = {
    "train_micro_batch_size_per_gpu": 1,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 1e-4
        }
    },
}
engine = Wrapper(model=model,
                 model_parameters=model.parameters(),
                 config=ds_config)

print(dir(engine))
```

For example, printing `engine.forward` shows:
```
<bound method instrument_w_nvtx.<locals>.wrapped_fn of Wrapper(
  (module): TinyModel(
    (linear1): Linear(in_features=100, out_features=200, bias=True)
    (activation): ReLU()
    (linear2): Linear(in_features=200, out_features=10, bias=True)
    (softmax): Softmax(dim=None)
  )
)>
```

**Comment by vishalghor** [comment]
@mrwyattii thank you for the explanation. So inorder to save the model,load a model, or access the state_dict can users just do engine.state_dict? Is this correct?

**Comment by mrwyattii** [comment]
Correct, but depending on what you want to do you may find it more convenient to use the `load_checkpoint` and `save_checkpoint` methods of `DeepSpeedEngine`. You may find some helpful examples in the DeepSpeedExamples repo, like this one: https://github.com/microsoft/DeepSpeedExamples/blob/master/HelloDeepSpeed/train_bert_ds.py
