### ISSUE TITLE
DeepSpeed with SLURM

### ISSUE THREAD

**Issue by thechargedneutron** [microsoft/DeepSpeed#2025]
Hi, I am trying to run DeepSpeed on SLURM with multiple nodes and multiple GPUs on each node. I was referring to this example [here](https://nlp.stanford.edu/mistral/tutorials/deepspeed.html). I am not sure how we can specify the address of all the machines that will be allotted to me when submitting a SLURM script.

I have my task.sbatch file as this

```
#SBATCH --nodes=2
#SBATCH --gpus-per-node=8

deepspeed --num_gpus 8 --num_nodes 2 finetune.py --config conf/tutorial-gpt2-micro.yaml
```

I have two questions
1. How do I know addresses of machines when specifying the deepspeed parameters?
2. Why do we need to set lr, scheduler etc. in the config files when the Trainer in the code already has those parameters set for single machine multi-GPU training through Huggingface transformers?

I am a beginner to SLURM based systems so sorry if there is an easy way to specify the addresses. And if there is a SLURM based example of deepspeed, please point me to that.

Thanks in advance!

**Comment by mrwyattii** [comment]
Hi @thechargedneutron I have not run DeepSpeed with SLURM and don't have access to a cluster running SLURM to try it out. Could you start an interactive session and try launching DeepSpeed? If you share the output, I might be able to help you.

To launch an interactive session you will need to do something like:
`salloc --nodes 2 --gpus-per-node 8` (but you may need to refer to system-specific slurm configs to get the correct command for an interactive job)

**Comment by stas00** [comment]
I couldn't make it work with the `deepspeed` launcher, but it's working just fine with torch's launcher, please see how we launch it here:
Please see https://github.com/bigscience-workshop/bigscience/blob/master/train/tr11-176B-ml/tr11-176B-ml.slurm

**Comment by thechargedneutron** [comment]
@stas00 Thanks! Torch's launcher is working perfectly fine! I can now run multi-gpu multi-node code with deepspeed optimization (feeling powerful!). Thanks @mrwyattii @jeffra

**Comment by thechargedneutron** [comment]
@stas00 The above given slurm script is working fine with huggingface trainer but now if I want to try native pytorch trainer, I am running into issues. 

With DistributedDataParallel, it gives an error `Default process group has not been initialized`. I can see MASTER_ADDR and MASTER_PORT and other variables required to run DistributedDataParallel but that does not seem to be enough. I already looked at the instructions  [here](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) and didn't understand what we exactly need to do for SLURM systems.

If I simply try DataParallel instead, the code starts running but now all the processes (8 processes) are using a single GPU and the other 7 GPUs are remaining vacant.

My code (Vanilla pytorch)
```
model = MyModel()
model = DataParallel(model).cuda() # OR model = DistributedDataParallel(model).cuda
```

**Comment by dyyoungg** [comment]
> I couldn't make it work with the `deepspeed` launcher, but it's working just fine with torch's launcher, please see how we launch it here:
> 
> https://github.com/bigscience-workshop/bigscience/blob/7ccf7e42577fe71e88cf8bed3b9ca965c7afb8f7/train/tr11-176B-ml/tr11-176B-ml.slurm#L172-L217

Thanks for the helpful scripts! I follow the  script but encounter some problems.
I use a test.py file to test the multi-node GPUs on slurm, the following is the file content
```
import fcntl
def printflock(*args, **kwargs):
    """
    non-interleaved print function for using when printing concurrently from many processes,
    like the case under torch.distributed
    """
    with open(__file__, "r") as fh:
        fcntl.flock(fh, fcntl.LOCK_EX)
        try:
            print(*args, **kwargs)
        finally:
            fcntl.flock(fh, fcntl.LOCK_UN)

if __name__ == "__main__":

    import torch.distributed as dist
    import torch
    import os
    local_rank = int(os.environ["LOCAL_RANK"])
    torch.cuda.set_device(local_rank)
    dist.init_process_group("nccl")

    world_size = dist.get_world_size()
    rank = dist.get_rank()
    printflock(f"This is a very long message from rank {rank} (world_size={world_size})")
```
and the test .sh file 
```
#!/bin/bash
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=9901

torchrun --nproc_per_node 8 --nnodes 2 --node_rank $SLURM_PROCID \
        --master_addr $MASTER_ADDR --master_port $MASTER_PORT \
        test.py 
```
I use the following "srun" instruction to launch the script test.sh in terminal
```
srun -p XXX  -n 16 --ntasks-per-node=8 --gres=gpu:8  test.sh 
```
The error reported by the torch is as follows
```
File "xxx/env/miniconda3.10/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 611, in _assign_worker_ranks
    my_role_info = role_infos[group_rank]
IndexError: list index out of range
```
However, the terminal can still output the correct rank infomation
```
This is a very long message from rank 0 (world_size=16)
This is a very long message from rank 5 (world_size=16)
This is a very long message from rank 13 (world_size=16)
This is a very long message from rank 1 (world_size=16)
This is a very long message from rank 14 (world_size=16)
This is a very long message from rank 8 (world_size=16)
This is a very long message from rank 11 (world_size=16)
This is a very long message from rank 6 (world_size=16)
This is a very long message from rank 12 (world_size=16)
This is a very long message from rank 10 (world_size=16)
This is a very long message from rank 7 (world_size=16)
This is a very long message from rank 15 (world_size=16)
This is a very long message from rank 2 (world_size=16)
This is a very long message from rank 3 (world_size=16)
This is a very long message from rank 4 (world_size=16)
This is a very long message from rank 9 (world_size=16)
```

When I try to use deepspeed launcher with the following .sh file 
```
function makehostfile() {
perl -e '$slots=split /,/, $ENV{"SLURM_STEP_GPUS"};
$slots=8 if $slots==0; # workaround 8 gpu machines
@nodes = split /\n/, qx[scontrol show hostnames $ENV{"SLURM_JOB_NODELIST"}];
print map { "$b$_ slots=$slots\n" } @nodes'
}
makehostfile > hostfile

deepspeed --num_gpus 16  --num_nodes 2 --hostfile hostfile test.py
``` 
It raise runtime error like this 
```
RuntimeError: Using hostfile at hostfile but host=SH-IDC1-10-198-34-35 was not reachable via ssh. If you are running with a single node please remove hostfile or setup passwordless ssh.
```
I don't know the reasons for the failures in starting DeepSpeed and TorchRun. It appears that DeepSpeed is failing due to SSH permission issues, but I'm unsure about the cause of the failure in starting TorchRun. On a single node, all commands work fine, but these problems occur when using multiple nodes on slurm.

**Comment by stas00** [comment]
you have unrelated issues here.

1. `srun -n 16` is most likely wrong, it should be `-n 1` - you have one task per node, not 16. the one task is the launcher
2. re: ds it gave you the error - it can't access `host=SH-IDC1-10-198-34-35` via ssh - you must have passwordless ssh working for this approach to work. that is you should be able to ssh to the compute nodes w/o a password.
3. `deepspeed --num_gpus 16` is wrong as well - should be 8, not 16
```
$ deepspeed -h | grep -A2 num_nodes
  --num_gpus NUM_GPUS, --num_accelerators NUM_GPUS
                        Max number of GPUs to use on each node, will use [0:N) GPU ids on each node. (default: -1)
```

The since evolved script is here https://github.com/stas00/ml-engineering/blob/master/debug/torch-distributed-gpu-test.py (though yours is perfectly fine too) - so let me know what it'd help for me to add there to make it easier to run it in the future.

**Comment by lzy37ld** [comment]
@stas00 
Why I simply run the code below, the output is 0,0.  I would expect they to be 0,1? Since normally if you want to run in multinode, you should run the:
torch.distributed.run --node_rank 0
torch.distributed.run --node_rank 1


#!/bin/bash
#SBATCH --job-name=test-nodes        # name
#SBATCH --nodes=2                    # nodes
#SBATCH --ntasks-per-node=1          # crucial - only 1 task per dist per node!
#SBATCH --cpus-per-task=10           # number of cores per tasks
#SBATCH --time 0:05:00               # maximum execution time (HH:MM:SS)
#SBATCH --output=%x-%j.out           # output file name

srun echo $SLURM_PROCID

**Comment by mhy9989** [comment]
> @stas00 Thanks! Torch's launcher is working perfectly fine! I can now run multi-gpu multi-node code with deepspeed optimization (feeling powerful!). Thanks @mrwyattii @jeffra

I'm also using slurm to run multi-GPU multi-node code with Deepspeed optimizations, but it doesn't start properly. Can you provide a sbatch script? I would like to refer to it. Thanks

**Comment by stas00** [comment]
Please see this example https://github.com/stas00/ml-engineering/blob/master/slurm/example.slurm - replace `torch-distributed-gpu-test.py` with your program and its parameters and it should just work.

**Comment by lzy37ld** [comment]
> regardless of SLURM or not SLURM you need explicitly initialize the dist env as per doc you linked to.
> 
> i.e, you must have `dist.init_process_group` in your code as per doc.
> 
> If it's something else please supply a short script that reproduces the problem (removing bits unrelated to it)
> 
> You can also use this diagnostic script as your template for a dist script https://github.com/stas00/toolbox/blob/master/pytorch/torch-distributed-gpu-test.py

@stas00 , Thanks for this great explanation! But why I could not find 'dist.init_process_group' in huggingface transformer repo? I try to find where does it do the initialization, but could not find it.

**Comment by stas00** [comment]
`dist` is `torch.distributed` - I'm not sure why you're looking for it in HF transformers repo as it has nothing to do with HF transformers. Unless I misunderstood why you were searching for it there.

**Comment by lzy37ld** [comment]
@stas00 The reason I ask is I am using torchrun or deepspeed, accelerate, etc, which are some tools for distributed training. So that means we also would have dist.init_process_group during this distributed training? Is there anyplace I misunderstood?

**Comment by stas00** [comment]
it's not the launchers that do that. the launchers only launch the actual processes doing the work.

You're also confusing launchers with the programs, which is very easy to do, as it's actually quite confusing. Let's clarify things:

- `deepspeed` program is a launcher. Deepspeed library is where the distributed is invoked.
- `accelerate` program is a launcher. Accelerate library is where the distributed is invoked.
- `torchrun` program is a launcher. If you don't use a special training framework you need to invoke it yourself as you can see in https://github.com/stas00/ml-engineering/blob/b1182d88994a9ef0781d95ace31a14f13518b781/debug/torch-distributed-gpu-test.py#L74

And you want to read this:
https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group

I hope it's now more clear.

**Comment by lzy37ld** [comment]
Thanks for this clarification!
yes @stas00 , 
"torchrun program is a launcher. If you don't use a special training framework you need to invoke it yourself as you can see in https://github.com/stas00/ml-engineering/blob/b1182d88994a9ef0781d95ace31a14f13518b781/debug/torch-distributed-gpu-test.py#L74
"
I also checked this script before and that's actually one reason why I ask about where to find dist. init_process_group in HF transformer repo. As you mentioned, deepspeed and accelerate are launchers where the distributed training are invoked. Torchrun is a launcher as well but needs you to invoke it manually. In your scripts, you add dist. init_process_group to build the connection between gpus, so I am asking in HF, say torchrun --nproc_per_node 2 examples/languague_modeling.py, how did they achieve the connection between gpus? torchrun would launch two process but how do they connect? That's what I am looking for. As for accelerate for example, there is a place to do that:
https://github.com/huggingface/accelerate/blob/54403875295905c4afb4a9435508e5262a9998c5/src/accelerate/state.py#L180

**Comment by stas00** [comment]
HF transformers examples are all using the HF Trainer (or at least they used to), which is the training loop which sorts all of this for you. https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py

Recently its innards got replaced with routines from Accelerate, so to the outside it still uses the same API, but on the inside it delegates almost everything to Accelerate.

And as you noticed Accelerate calls the dist init.

**Comment by sorenwacker** [comment]
Is there an example somewere that contains all necessary files in one folder?
