### ISSUE TITLE
[BUG] GPT-J InferenceEngine outputs diverging from base GPT-J

### ISSUE THREAD

**Issue by joehoover** [microsoft/DeepSpeed#2048]
**Describe the bug**
The GPT-J InferenceEngine returns low-quality outputs that diverge from the base model.

**UPDATE**

I rolled back to the versions we have in production and confirmed that GPT-J and GPT-J InferenceEngine return identical outputs. I have not tested any later versions, so I can't provide any info, at the moment, about when the bug was introduced (or where it's caused exists).

Specifically, I observed identical outputs running roughly the same code as below in a container with: 

```
# Base container
pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel

transformers==4.15 
deepspeed==0.5.10
```

**To Reproduce**

1. Install packages:
```bash
pip3 install torch==1.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
pip install transformers==4.20.1
pip install deepspeed==0.6.5
```

2. Run the following:

```python
import os
import deepspeed
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

# Get local gpu rank from torch.distributed/deepspeed launcher
local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

model = AutoModelForCausalLM.from_pretrained(
    "EleutherAI/gpt-j-6B", revision="float16", torch_dtype=torch.float16, low_cpu_mem_usage=True
)
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, device=0)

pipe(
    "All happy families are alike, but ",
    do_sample=False,
)

# Note, depending on your device, you might need to clear GPU cache to initialize the inf engine.
model = deepspeed.init_inference(model,
                                 mp_size=1,
                                 dtype=torch.float16,
                                 replace_method='auto',
                                 replace_with_kernel_inject=True)

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, device=0)
pipe(
    "All happy families are alike, but ",
    do_sample=False,
)
```
**Expected behavior**
With `do_sample=False`, these outputs should be identical. Further, the repetition of new lines seems pathological. Testing across various other inputs, I noticed similar degraded outputs from the inference engine. 

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch']
torch version .................... 1.11.0+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.1
deepspeed install path ........... ['/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.6.5, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.11, cuda 10.2
```

**System info (please complete the following information):**
 - OS: AWS SageMaker Notebook instance
 - GPU count and types: 1 Nvidia 16GB T4 GPU.
 - Python version: 3.8

**Launcher context**
No launcher, just running in a notebook. 

**Additional context**
I believe that this exact code was working until recently; however, I'm not sure that I ever explicitly tested output equality. I can say that output quality definitely seems degraded. 

**UPDATE:**

I believe I've isolated the surface-level cause of the divergence.

The initial behavior I observed replicates reliably when `low_cpu_mem_usage=True` is used to load the pretrained model. E.g.:

from transformers import AutoTokenizer, pipeline, GPTJForCausalLM
import torch
import deepspeed

model = GPTJForCausalLM.from_pretrained(
   "EleutherAI/gpt-j-6B", 
   revision="float16", 
   torch_dtype=torch.float16,
   low_cpu_mem_usage=True # low cpu usage set true here
)

tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B", revision="float16")

model = deepspeed.init_inference(model,
                                 mp_size=1,
                                 dtype=torch.float16,
                                 replace_method='auto',
                                 replace_with_kernel_inject=True)

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, device=0)

pipe(
    "All happy families are alike, but ",
    do_sample=False,
)
reliably returns: [{'generated_text': 'All happy families are alike, but --\n\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\nw\nw\n'}]

However, using a model loaded with low_cpu_mem_usage=False, reliably returns `[{'generated_text': 'All happy families are alike, but \nevery unhappy family is unhappy in its own way.\n\n—LEWIS CARROLL\n\n## **THE BEGINNING**\n\nLet the conversation begin...\n\nFollow the Penguin'}]`

**UPDATE 2:**

I also observe divergence outputs when I export them model with torch (e.g. `torch.save()`) and load it with `torch.load()`.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @joehoover ,

I ran this with the master branch and I see the following output:
`
[{'generated_text': 'All happy families are alike, but each unhappy family is unhappy in its own way.\n\n—Leo Tolstoy\n\nI’m not sure if I’m a happy person. I’m not sure if I'}]`

I also see the same output when running several times with `do_sample=False`.
Can you please test this on your side with the latest deepspeed branch and see if the issue persists?
Thanks,
Reza

**Comment by joehoover** [comment]
Hey @RezaYazdaniAminabadi , thanks for looking into this. 

Something seems weird...are you using the fp16 weights? The issue I described above aside, I'm getting consistently different results from you even from the baseline model. 

```
model = AutoModelForCausalLM.from_pretrained(
    model_dir, 
    revision="float16", 
    torch_dtype=torch.float16, 
    low_cpu_mem_usage=True
)

tokenizer = AutoTokenizer.from_pretrained(model_dir)

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, device=0)

pipe(
    "All happy families are alike, but ",
    do_sample=False,
)
```

Returns: 

> [{'generated_text': 'All happy families are alike, but  \nevery unhappy family is unhappy in its own way.\n\n—LEWIS CARROLL\n\n## **THE BEGINNING**\n\nLet the conversation begin...\n\nFollow the Penguin'}]

I also installed DeepSpeed from main and observed the same output as above. 

I'm going to run some of the GPT-J Transformers unit tests and see if I they pass. I'll follow up here and let you know what I find.

**Comment by PanQiWei** [comment]
Hi, I was also came into the similar problem that GPT-J with deepspeed generated worse than the original one. While the different is that when using the prompt above (`All happy families are alike, but `) or any other prompts whose tokens length are short, I can always get the exactly same outputs of the original one and the deepspeed one, but once I increase the length of the prompt, the divergence appears and the repetition of single character begins.

The environment of mine is: <br>
`python`==3.8.11
`pytorch`==1.11.0
`transformers`==4.16.0
`deepspeed`==0.6.5
`CUDA`=11.3
`GPU`=A30

**Comment by joehoover** [comment]
@PanQiWei , could you share a reproducible code chunk? I'd like to see if we're getting the same outputs and if I can reproduce your observations. 

Also, just to confirm, you observe this specifically when you increase the length of the _prompt_, but not when you generate more tokens, given a prompt?

**Comment by PyxAI** [comment]
I also encountered similar results given long prompts, example output is the lovely string:
`​ ­   � re  A p first _- long m ex`

**Comment by lokoppakmsft** [comment]
@joehoover , @PyxAI, @PanQiWei the issue related to low_cpu_mem_usage is root caused and you can look at the fix here https://github.com/microsoft/DeepSpeed/pull/2489. Could you please try it on your side and confirm if the issue is fixed?
