### ISSUE TITLE
`ds_report` command shows `[FAIL] nvcc missing`

### ISSUE THREAD

**Issue by fade-color** [microsoft/DeepSpeed#2055]
I am getting `nvcc missing` when executing `ds_report` instruction
But `nvcc --version` can print the following information:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```
`nvidia-smi` shows：
```
NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4
```
My environment is `pytorch==1.7.1+cu110` and `deepspeed==0.6.5`
I would like to know what is causing this error? Thanks!

**Comment by LiangYuHai** [comment]
Same problem. And output shows "RuntimeError: Unable to proceed, no GPU resources available"
NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4  
My environment is pytorch==1.12.1+cu11.4 and deepspeed==0.9.0
