### ISSUE TITLE
SLURM support

### ISSUE THREAD

**Issue by MannyKayy** [microsoft/DeepSpeed#207]
Hi,

Great work !

It would be useful to have inbuilt support for multi-node training on SLURM managed clusters, similar to [Pytorch-Lightning](https://pytorch-lightning.readthedocs.io/en/latest/slurm.html).

**Comment by ShadenSmith** [comment]
Hi @MannyKayy, this is an interesting idea. Off the top of my head I'm not sure of what changes we'd need to support SLURM. DeepSpeed already supports [launching via MPI](https://www.deepspeed.ai/getting-started/#mpi-compatibility), so I _think_ it should work today if you treat it as a typical MPI job. Do please let us know if you have a chance to try it out and how it goes!

**Comment by ShadenSmith** [comment]
Closing for now. Please reopen if there you encounter an issues :-).
