### ISSUE TITLE
Local rank conflict when training on multi-node multi-gpu cluster using deepspeed

### ISSUE THREAD

**Issue by jessecambon** [microsoft/DeepSpeed#2078]
Cross-posting this bug report as I am using deepspeed (0.6.5) within pytorch lightning: 

https://github.com/Lightning-AI/lightning/issues/13567

**Comment by tjruwase** [comment]
@jessecambon, is this still an issue? Thanks!

**Comment by jessecambon** [comment]
@tjruwase it's resolved. Running with an MPIConfiguration required environmental variables adjustments : https://github.com/Lightning-AI/lightning/issues/13639#issuecomment-1185956230
