### ISSUE TITLE
[BUG] can't install with ROCm

### ISSUE THREAD

**Issue by stalkerg** [microsoft/DeepSpeed#2080]
It happened just during `pip install` for deepspeed-0.6.5:

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ruwdavjo/deepspeed_caadfe808785436583e97206db673e2c/setup.py", line 39, in <module>
          rocm_version = OpBuilder.installed_rocm_version()
        File "/tmp/pip-install-ruwdavjo/deepspeed_caadfe808785436583e97206db673e2c/op_builder/builder.py", line 192, in installed_rocm_version
          with open('/opt/rocm/.info/version-dev', 'r') as file:
      FileNotFoundError: [Errno 2] No such file or directory: '/opt/rocm/.info/version-dev'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

I have ROCm but it is installed into the system, not into `/opt/rocm` and I have no `version-dev` file. ROCm PyTorch is working fine. 
It's Gentoo Linux.

**Comment by mrwyattii** [comment]
@stalkerg thanks for bringing this to our attention. It seems that we expect ROCm to be installed at `/opt/rocm/` [here](https://github.com/microsoft/DeepSpeed/blob/73b5d9833a113c47758fbe9f8538614ce34ea95e/op_builder/builder.py#L192)

I'll look into how we can avoid assuming the install location and add a fix. In the meantime, if you modify the path on the file:line I linked to and point it to your rocm install location, it should fix the problem.

**Comment by mrwyattii** [comment]
@stalkerg could you please try again with #2093 ?
```
git clone https://github.com/microsoft/DeepSpeed.git && cd DeepSpeed
git pull origin pull/2093/head
pip install .
```

**Comment by stalkerg** [comment]
Thanks! But looks like it will not work because I am installing https://pytorch.org/get-started/locally/ 
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.1.1
```
and it contains ROCm libraries but without `.info/version-dev` file or any `dev` or `debug` information. I also have no ROCM_HOME. 
Because it's now the official way to install PyTorch with ROCm probably we can check the PyTorch version. Currently, I have `torch==1.12.0+rocm5.1.1`

**Comment by mrwyattii** [comment]
@stalkerg sorry I missed that part in your original post. I'll update the PR with this in mind. Thanks!

**Comment by mrwyattii** [comment]
@stalkerg could you tell me if running `from torch.utils.cpp_extension import ROCM_HOME` causes an error with your install? Is `ROCM_HOME` just `None`?

**Comment by stalkerg** [comment]
@mrwyattii 
it shows empty string:
```
>>> from torch.utils.cpp_extension import ROCM_HOME
>>> print(ROCM_HOME)

>>> 
```

**Comment by stalkerg** [comment]
Also your way in PR looks like working fine:
```
>>> import torch
>>> torch.__version__.split("rocm")[1]
'5.1.1'
```

**Comment by mrwyattii** [comment]
Thanks for testing that for me. I'll get this PR merged
