### ISSUE TITLE
Why the MoE layer forces the input hidden dimenstion the same as the output hidden dimension?

### ISSUE THREAD

**Issue by hobbitlzy** [microsoft/DeepSpeed#2096]
![image](https://user-images.githubusercontent.com/35392624/178932761-6bc58f0e-9154-4c60-97b5-df0213bc4e57.png)
I notice a problem when I read the [tutorial](https://www.deepspeed.ai/tutorials/mixture-of-experts/) of MoE. As the figure shows, it says the input dimension must be equal to the output dimension. This absolutely imports complexity for many DNNs, and I don't understand why this is necessary. In my view, the output dimension is supposed to be easily set at will?

**Comment by awan-10** [comment]
@ykim362 -- I know its a very old issue but do you mind explaining this here?

**Comment by ykim362** [comment]
I think this is because the initial implementation is based on the NLP applications following GShard and Switch. We have a certain tensor dimension assumption - batch, sequence length at the beginning of input tensors.

**Comment by mhjabreel** [comment]
Hi,

I have fixed this issue in this PR https://github.com/microsoft/DeepSpeed/pull/2530/files.
