### ISSUE TITLE
Question: How to do multi-node inference?

### ISSUE THREAD

**Issue by asaparov** [microsoft/DeepSpeed#2112]
I was wondering how to perform multi-node inference in DeepSpeed? The high-level descriptions of Zero and DeepSpeed Inference indicate that it is supported, but the examples I've found so far are only of multi-node _training_.

I really appreciate any tips or pointers!

**Comment by lanking520** [comment]
You can follow this: https://www.deepspeed.ai/tutorials/inference-tutorial/。 But multi-node inference is broken from my side: https://github.com/microsoft/DeepSpeed/issues/2113

**Comment by asaparov** [comment]
Maybe I'm mistaken but isnt #2113 related to multi-GPU inference on a single node? The tutorial does cover that case but I couldn't find any tutorials or examples for doing inference with multiple GPUs split across multiple nodes.

**Comment by asaparov** [comment]
I was able to get deepspeed to perform inference instead of training in the multi-node setting on SLURM, but I ran into a different error. I'll open a different issue for that (#2119).

**Comment by jens5588** [comment]
@asaparov Can you show me how to set up ssh files on SLURM? Have problem with passwordless ssh

**Comment by asaparov** [comment]
My slurm script looked something like:
```
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST") # Getting the node names
nodes_array=($nodes)

# create the hostfile
hostfile="$(TMPDIR='/directory/for/hostfile/' mktemp)"
for ((i = 0; i < $SLURM_JOB_NUM_NODES; i++)); do
  node_i=${nodes_array[$i]}
  echo "WRITING WORKER $i at $node_i to $hostfile"
  echo "$node_i slots=$gpus_per_node" >> $hostfile
done

echo "FINISHED WRITING hostfile $hostfile:"
cat $hostfile

# run deepspeed
echo 'RUNNING deepspeed'
deepspeed --hostfile=$hostfile Megatron-DeepSpeed/scripts/inference/bloom-ds-inference.py --name bigscience/bloom
```

I had to make two changes to disable ssh's strict host key checking: In `deepspeed/launcher/runner.py`:
```
--- a/deepspeed/launcher/runner.py
+++ b/deepspeed/launcher/runner.py
@@ -360,7 +360,7 @@ def main(args=None):
         first_host = list(active_resources.keys())[0]
         try:
             subprocess.check_call(
-                f'ssh -o PasswordAuthentication=no {first_host} hostname',
+                f'ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no {first_host} hostname',
                 stderr=subprocess.DEVNULL,
                 stdout=subprocess.DEVNULL,
                 shell=True)
@@ -372,7 +372,7 @@ def main(args=None):
     if not args.master_addr:
         assert multi_node_exec
         first_host = list(active_resources.keys())[0]
-        hostname_cmd = [f"ssh {first_host} hostname -I"]
+        hostname_cmd = [f"ssh -o StrictHostKeyChecking=no {first_host} hostname -I"]
         result = subprocess.check_output(hostname_cmd, shell=True)
         args.master_addr = result.decode('utf-8').split()[0]
         logger.info(f"Using IP address of {args.master_addr} for node {first_host}")
```
and in the PDSHRunner class:
```
--- a/deepspeed/launcher/multinode_runner.py
+++ b/deepspeed/launcher/multinode_runner.py
@@ -60,6 +60,7 @@ class PDSHRunner(MultiNodeRunner):

     def get_cmd(self, environment, active_resources):
         environment['PDSH_RCMD_TYPE'] = 'ssh'
+        environment['PDSH_SSH_ARGS_APPEND'] = '-o StrictHostKeyChecking=no'

         active_workers = ",".join(active_resources.keys())
         logger.info("Running on the following workers: %s" % active_workers)
```

In addition, since we ran deepspeed in a singularity container, I had to modify `pdsh_cmd_args` in the `PDSHRunner` class so that, instead of launching deepspeed directly, it would run the singularity script, which in turn would launch deepspeed. But if you're not using a container, this should not be a problem.

**Comment by jens5588** [comment]
@asaparov Thanks a lot for sharing your scripts. I have tried your solution and change two lines in runner.py (we are not using container). The node was not reachable via ssh.
subprocess.CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no haicn1801 hostname' returned non-zero exit status 255
haicn1801 was the first node of two nodes.

**Comment by jens5588** [comment]
@asaparov Thanks a lot for sharing the scripts with me. I have solved the ssh problem with loading a system module ssh_wrapper

**Comment by liuzhili-ya** [comment]
@jens5588 @asaparov  Can  deepspeed zero-inference support zero-3  on multi-nodes?  if so，we can inference a large mode by multi-nodes.  But I run DeepspeedExample  with zero-0 or zero-3 on multi-nodes，every node always load the whole  mode in gpu RAM.  Did I have some mistake?
