### ISSUE TITLE
Bad performance when there are lots of optim_groups (for example, using layer-wise learning rate)

### ISSUE THREAD

**Issue by BlinkDL** [microsoft/DeepSpeed#2125]
DeepSpeed is much slower when there are lots of optim_groups in FusedAdam.

For example, when you are using layer-wise learning rate for a model with 100+ layers.

In that case, you will see 100+ "partitions" in each "Rank", and the training speed is much worse.

**Comment by tjruwase** [comment]
@BlinkDL, can you provide details to repro?

**Comment by loadams** [comment]
Closing as stale.  @BlinkDL - if this still impacts you, please let us know and we would be happy to take a look, same to anyone else who might hit this, please open a new issue and link this one and we would be happy to take a look.
