### ISSUE TITLE
Can DeepSpeed partition the model before loading?

### ISSUE THREAD

**Issue by lanking520** [microsoft/DeepSpeed#2163]
**Describe the bug**

OOM on CPU when running GPU = 8. My GPU have 16GB memory each (128GB memory total) and my CPU memory is 488GB. However, I am trying to load a large GPT2 model with 80GB size. In this case, after creating 8 processes using DeepSpeed launcher, the system goes OOM after 20 min. 

It is clear the issue is 80 * 8 process = CPU 640GB memory needed. So I am wondering if there is a way to partition the model before loading: To break it to 8 partiitons (each with 10GB) and we won't have the same issue here.

**To Reproduce**
I am running with 8 GPU instance with V100. 

You can just create a config that is large enough for 80GB model size and it will reproduce.

```python
import os
import deepspeed
import torch
from transformers import pipeline

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

config = GPT2Config.from_pretrained("config.json")
model = GPT2LMHeadModel(config)
model.half()
tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.float,
                                           replace_method='auto',
					   replace_with_kernel_inject=True)

generator = pipeline(task='text-generation', model=model, tokenizer=tokenizer, device=local_rank)

string = generator("DeepSpeed is", do_sample=True, min_length=50)
if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(string)
```

```
deepspeed --num_gpus 8 test.py
```

**Expected behavior**

Should be just normal?

**ds_report output**

```
# ds_report
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
async_io ............... [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch']
torch version .................... 1.11.0+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed install path ........... ['/usr/local/lib/python3.8/dist-packages/deepspeed']
deepspeed info ................... 0.6.7, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.11, cuda 11.3
```

**Comment by SihengLi99** [comment]
Hi, I also meet this problem.
I have 8v100 which is enough to load OPT-66b to GPU after partition.
However, the deepspeed.init__inference needs to load the OPT-66b in cpu in each process.
This results CPU OOM.

How did you solve this problem ?

Thanks,
Siheng

**Comment by lanking520** [comment]
DeepSpeed cannot partition the model before loading it full. This means you will have to have a machine with cpu memory that is num_GPU * model_size in order to load on num_GPU processes. @RezaYazdaniAminabadi do you know if we can partition the model and save it before loading?

**Comment by SihengLi99** [comment]
Hi，I have found a method ！https://github.com/tunib-ai/parallelformers Just
have a try !

Qing Lan ***@***.***> 于2022年8月11日周四 22:43写道：

**Comment by lanking520** [comment]
@SihengLi99 Could you share the script you try to run with? Not sure how to use that

**Comment by SihengLi99** [comment]
You can try the example given by parrallelformers in their github, it is
fine!

Qing Lan ***@***.***> 于2022年8月13日周六 05:35写道：

**Comment by Lechatelia** [comment]
@lanking520 Hey.
 I am having the same problem. How did you solve this?

**Comment by lanking520** [comment]
@Lechatelia since 0.8.2, most of the FP16 model sharding is fairly stable. You can shard the model to fp16 and load using DeepSpeed (FP16/INT8)

**Comment by Lechatelia** [comment]
> @Lechatelia since 0.8.2, most of the FP16 model sharding is fairly stable. You can shard the model to fp16 and load using DeepSpeed (FP16/INT8)

Thanks for your reply.
Do you mean to use the numerical precision of fp16 when initializing a model instance on the CPU? 
I think this will save half of the memory cost. But the same problem will be faced with a larger model.
