### ISSUE TITLE
[Bug] RuntimeError: expected input to be on cuda

### ISSUE THREAD

**Issue by trajepl** [microsoft/DeepSpeed#2186]
**Describe the bug**
When I try to run the Megatron deepspeed example(https://github.com/microsoft/Megatron-DeepSpeed/tree/main/examples) with latest master branch of deepspeed, I met following error:
![image](https://user-images.githubusercontent.com/13343117/183005422-b4b7890a-0bb2-47c8-b03b-572f7807211b.png)

**To Reproduce**
1. Go to '[Megatron Example](https://github.com/microsoft/Megatron-DeepSpeed/tree/main/examples)'
2. Install latest DeepSpeed(0.7.0+9dcfb93a) & Megatron(0.5.1)
3. Prepare the data: 
 - bash dataset/download_books.sh
 - bash dataset/download_vocab.sh
5. Start the training:
 bash examples/azure/run-benchmark-model.sh

The env I used is:
1 node/ 8GPUs, A100. 

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/13343117/183005761-c8bf7957-3978-4519-a638-cb85ae004260.png)

DS_CONFIG:
![image](https://user-images.githubusercontent.com/13343117/183005828-05dccd62-96ee-440a-bb15-976b65bd10fa.png)

**System info (please complete the following information):**
 - ubuntu2004-cu115-py38-torch1110
 - 1 machines with x8 A100s each

**Comment by hibagus** [comment]
I have the same issue as yours and I suggested a temporary fix on their Megatron-DeepSpeed github.
https://github.com/microsoft/Megatron-DeepSpeed/pull/71

**Comment by trajepl** [comment]
> I have the same issue as yours and I suggested a temporary fix on their Megatron-DeepSpeed github. [microsoft/Megatron-DeepSpeed#71](https://github.com/microsoft/Megatron-DeepSpeed/pull/71)

Thanks @hibagus. Good catch here. Also I got the fix from @awan-10 where we can change the `CPU_OPTIM` to `--cpu-optimizer` from `""`. It would be like for the [file ](https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/azure/run-benchmark-model.sh#:~:text=%23%20Set%20to,CPU_OPTIM%3D%22%20%22) 
```sh
OFFLOAD_DEVICE="none"
CPU_OPTIM=" --cpu-optimizer"
```
