### ISSUE TITLE
[REQUEST] Is there any document to illustrate the configuration for using multiple NVMe SSD.

### ISSUE THREAD

**Issue by luckyq** [microsoft/DeepSpeed#2195]
I have eight NVMe SSD but one GPU in the server. 
From the configuration file, I didn't see the example for using multiple SSDs.

How do I add the other NVMe ssds in the configuration.

Here is the current configuration.
`"zero_optimization": {
    "stage": 3,
    "overlap_comm":true,
    
    "offload_optimizer":{
      "device": "nvme",
      "nvme_path": "/mnt/nvme0",
      "pin_memory": true,
      "buffer_count":8,
      "fast_init":true,
      "pipeline_read":true,
      "pipeline_write":true,
      "pipeline":true
    },
 
    "aio":{
      "block_size":1048576,
      "overlap_events":true,
      "queue_depth":16,
      "single_submit":false,
      "thread_count":2
    },

    "reduce_bucket_size": 50000000
  },`

**Comment by hibagus** [comment]
Usually, multiple NVME SSD can be combined into a single RAID 0 (striping) device. Then, you mount that RAID volume and use it for offloading with ZeRO-3. I see noticeable improvements by going to multiple NVME SSDs.

**Comment by luckyq** [comment]
> Usually, multiple NVME SSD can be combined into a single RAID 0 (striping) device. Then, you mount that RAID volume and use it for offloading with ZeRO-3. I see noticeable improvements by going to multiple NVME SSDs.

Thanks. I have tried it. It works.

**Comment by tjruwase** [comment]
@hibagus, thanks for resolving this issue!
