### ISSUE TITLE
InferenceEngine problem with data parrallel [BUG]

### ISSUE THREAD

**Issue by SihengLi99** [microsoft/DeepSpeed#2200]
Hi, I try to use deepspeed.init_inference() with data parrallel.
But, I find the tensors are brodcasted in the forward pass of InferenceEngine.
![image](https://user-images.githubusercontent.com/75015153/183575681-e1a52a93-ba4f-4f06-bc48-584f7c23f65c.png)

It is confused for me and I need some help to know more in depth.

Thanks!

**Comment by SihengLi99** [comment]
In addition, how to set the mpu args in deepspeed.init_inference ?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @SihengLi99 
Inference-engine is designed to only support tensor-slicing model-parallelism. We are in the process of adding more parallelism to it. Regarding the mpu, if you don't have such object you can pass it as None and the engine will create a model-parallel group to partition the model for you.
Hope this helps answer your question.
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
Closing the issue due to staleness. Please open if this is still an issue.
Thanks,
Reza
