### ISSUE TITLE
[BUG] GPT2 inference example problems from deepspeed version 0.6.2 to 0.7.0 

### ISSUE THREAD

**Issue by appleeji** [microsoft/DeepSpeed#2251]
**Describe the bug**
GPT2 based on the example outputs incorrect results from deepspeed version 0.6.2 to 0.7.0 (I used the gpt2 model for a quick experiment, but the same trend was also observed with the gpt2-neo model.)

**To Reproduce**
gpu A100 80G X 8
torch==1.10.0a0+ecc3718
transformers==4.21.1
deepspeed==0.6.2 ~ 0.7.0
```
# Filename: gpt-neo-2.7b-generation.py
import os
import deepspeed
import torch
from transformers import pipeline

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))
generator = pipeline('text-generation', model='gpt2',
                     device=local_rank)



generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.float,
                                           replace_method='auto',
                                           replace_with_kernel_inject=True)

string = generator("DeepSpeed is", do_sample=False, min_length=50)
if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(string)
```
`deepspeed --num_gpus 2 gpt-neo-2.7b-generation.py`

**Result**
Outputs from running gpt-neo-2.7b-generation.py
- deepspeed==0.6.0, deepspeed==0.6.1
   - `DeepSpeed is a new feature that allows you to set the speed of your car to a certain speed.\n\nThe speed of your car is determined by the speed of the car's engine. The speed of your car is determined by the speed of`
- deepspeed==0.6.3, deepspeed==0.6.4, deepspeed==0.6.5, deepspeed==0.6.6
   - `DeepSpeed is"""""""""""""""""""""""""""""""""""""""""""""""`
- deepspeed==0.6.7, deepspeed==0.7.0
   -  `DeepSpeed is as as as as as as as as as as as as as as as as in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in`

**Comment by RezaYazdaniAminabadi** [comment]
Hi @appleeji 

Yes, that is true that 0.7 is giving the wrong result. But this has been fixed in the latest master branch of DeepSpeed. Here is what I see by using DeepSpeed master:
`[{'generated_text': "DeepSpeed is a new feature that allows you to set the speed of your car to a certain speed.\n\nThe speed of your car is determined by the speed of the car's engine. The speed of your car is determined by the speed of"}]`
The new changes will be upstreamed soon.
Thanks,
Reza
