### ISSUE TITLE
ZeRO-2 per-epoch training time significantly slower than ZeRO-1

### ISSUE THREAD

**Issue by dkavaler** [microsoft/DeepSpeed#226]
Thank you very much for this fantastic work.

I have already implemented ZeRO-1 on top of my existing model pipeline and experienced a significant reduction in training time and memory usage. I am trying to use ZeRO-2 and have a few questions.

For ZeRO-1, I use the following configuration on a system with 8 GPUs (so `gradient_accumulation_steps` should be 1):

```json
{
  "train_batch_size": 128,
  "train_micro_batch_size_per_gpu": 16,
  "steps_per_print": 1000,
  "dump_state": true,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 2e-4,
      "weight_decay": 0.01,
      "bias_correction": false
    }
  },
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "initial_scale_power": 4
  },
  "zero_optimization": {
    "stage": 1
  },
  "gradient_clipping": 0.1
}
```

The per-epoch training time is about ~35 minutes for a small model I am testing.

When updating to use ZeRO-2, _i.e._:

```json
{
  "train_batch_size": 128,
  "train_micro_batch_size_per_gpu": 16,
  "steps_per_print": 1000,
  "dump_state": true,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 2e-4,
      "weight_decay": 0.01,
      "bias_correction": false
    }
  },
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "initial_scale_power": 4
  },
  "zero_optimization": {
    "stage": 2
  },
  "gradient_clipping": 0.1
}
```

With no changes in other parameters, the per-epoch training time is about 1 hour.

In addition, I see no significant GPU memory savings according to `nvidia-smi` when using ZeRO-2 vs. ZeRO-1.

Questions:

1. Is the purported lack of memory savings just due to `nvidia-smi` being a poor gauge of memory performance?
2. Is the reduction in per-epoch training time expected due to the changes in memory optimization?

**Comment by jeffra** [comment]
How big is you model in terms of number of parameters? Can you attach the log files for the two runs? Also can you turn on the wall clock breakdown deepspeed config? https://www.deepspeed.ai/docs/config-json/#logging

**Comment by dkavaler** [comment]
Apologies for the delayed response, did not have access to my machine.

The underlying model has 26,275,840 trained parameters.

Attached are log files for both configs (with wall clock breakdown added).

[test_deepspeed_only_zero1.log](https://github.com/microsoft/DeepSpeed/files/4684076/test_deepspeed_only_zero1.log)
[test_deepspeed_only_zero2.log](https://github.com/microsoft/DeepSpeed/files/4684078/test_deepspeed_only_zero2.log)

With these settings, GPUs are nearly maxed in memory according to nvidia-smi (~14GB of 16GB available).

**Comment by samyam** [comment]
@dkavaler  Could you try the following configuration for zero-2

  "zero_optimization": {
    "stage": 2,
    "contiguous_gradients" : false
    }

And log the wallclock breakdown. This should fix the issue. If not can you then try the following:

  "zero_optimization": {
    "stage": 2,
    "contiguous_gradients" : false,
    "reduce_bucket_size": 27000000
    }

**Comment by dkavaler** [comment]
@samyam Thank you very much, setting `contiguous_gradients` to false worked! I am getting a speedup and memory reduction now (caveat: I've only tested for 100 steps) using stage 2 vs. stage 1 now.

As a note, `contiguous_gradients` is specified as false by default in the [documentation](https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training), but it [appears in code](https://github.com/microsoft/DeepSpeed/blob/f2ac7eafd54c49acb8981650637dedd939e96c14/deepspeed/pt/deepspeed_zero_config.py#L54) that it is true by default.

**Comment by jeffra** [comment]
Thanks @dkavaler! Glad that your all fixed up now, we see that contiguous_gradients helps improve performance in larger model sizes but we are observing it hurting performance for smaller models. In terms of the documentation/code we just merged in a PR fixing this actually: https://github.com/microsoft/DeepSpeed/pull/239

I'll close for now, please re-open if you see any further issues here.
