### ISSUE TITLE
[BUG] "if name in all_reduce_linears: TypeError: argument of type 'ABCMeta' is not iterable" when passing "replace_with_kernel_inject=False" in init_inference

### ISSUE THREAD

**Issue by puneeshkhanna** [microsoft/DeepSpeed#2265]
**Describe the bug**
 replace_with_kernel_inject=False givng error as below:
File "DeepSpeed/deepspeed/module_inject/replace_module.py", line 784, in replace_wo_policy
    return _replace_module(module)
  File "DeepSpeed/deepspeed/module_inject/replace_module.py", line 781, in _replace_module
    _replace_module(child, name)
  File "DeepSpeed/deepspeed/module_inject/replace_module.py", line 781, in _replace_module
    _replace_module(child, name)
  File "DeepSpeed/deepspeed/module_inject/replace_module.py", line 776, in _replace_module
    linear_policies[child.__class__](child,
  File "DeepSpeed/deepspeed/module_inject/replace_module.py", line 637, in _replace
    if name in all_reduce_linears:
TypeError: argument of type 'ABCMeta' is not iterable

**To Reproduce**
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-2.7B', device=device, framework="pt")

generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.float,
                                           replace_method='auto',
                                           #replace_with_kernel_inject=True,
					                       replace_with_kernel_inject=False,
                                           device_str=device_str)

string = generator("DeepSpeed is", do_sample=True, min_length=10, max_length=20)
if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(string)

**Expected behavior**
Crash should not happen

**System info (please complete the following information):**
 - OS: Ubuntu20.04
 - GPU count and types : 1

**Comment by RezaYazdaniAminabadi** [comment]
Hi @puneeshkhanna,
The problem is that you are using the init_inference without kernel-injection and in that case you need to pass an injection-policy. I will add a PR that gives an assert that `replace_method` cannot be 'auto' in this case.
Please refer to the [inference-tutorial ](https://www.deepspeed.ai/tutorials/inference-tutorial/)to add the right policy for running the model. 
Thanks,
Reza

**Comment by puneeshkhanna** [comment]
Thanks @RezaYazdaniAminabadi for your quick response.

When I used as below then it works. I think need to specify injection policy for all reduce linear layers.

generator.model = deepspeed.init_inference(generator.model,
mp_size=world_size,
dtype=torch.float,
replace_method='auto',
replace_with_kernel_inject=False,
injection_policy={GPTNeoBlock: ('attention.out_proj', 'mlp.c_proj'))

However above works for GPT neo. 
When I try similar thing for bloom then it fails. Can you please suggest injection_policy for bloom ?

(22): BloomBlock(
    (input_layernorm): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
    (self_attention): BloomAttention(
      (query_key_value): Linear(in_features=2048, out_features=6144, bias=True)
      (dense): Linear(in_features=2048, out_features=2048, bias=True)
      (attention_dropout): Dropout(p=0.0, inplace=False)
    )
    (post_attention_layernorm): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
    (mlp): BloomMLP(
      (dense_h_to_4h): Linear(in_features=2048, out_features=8192, bias=True)
      (dense_4h_to_h): Linear(in_features=8192, out_features=2048, bias=True)
      (gelu_impl): BloomGelu()
    )
  )

**Comment by RezaYazdaniAminabadi** [comment]
Use this for BLOOM:
```
generator.model = deepspeed.init_inference(generator.model,
mp_size=world_size,
dtype=torch.float,
replace_with_kernel_inject=False,
injection_policy={BloomBlock: ('self_attention.dense', 'mlp.dense_4h_to_h'))
```
Alternatively, you can pass the `replace_method` as `'auto'` and `replace_with_kernel_inject` as `True` for the kernels to run the model.
Thanks,
Reza

**Comment by puneeshkhanna** [comment]
Thanks it works now. Got it.
