### ISSUE TITLE
[BUG] If there are some "\n" in my prompt, deepspeed inference went to wrong result

### ISSUE THREAD

**Issue by yingapple** [microsoft/DeepSpeed#2277]
Hey, Could you please tell me what is going wrong?

my prompt:
"""I'm a Coca Cola, 
        user: do you like pepsi?
        Coca Cola: no, pepsi taste disgusting.
        I'm a potato, 
        user: what can you do? 
        potato: I can turn into delicious potato chips.
        I'm a computer,
        user: are you hot? 
        computer: yes, I am so hot, because you are playing computer games!
        I'm a pen,
        user: are you going to dry? 
        pen: yes, because you used me too much.
        I'm a cup, 
        user: who are you? 
        cup: """

Generation result:  cup: \n Re to D Re Re Rep E e C l andity_ Re Re Re Re Re E"

**Expected behavior**
For pure transformers, it should return just like "I'm a cup, user: what can you do?"
And if i remove the "\n",  the result seems right.
I am using opt-13b model.

**ds_report output**
![image](https://user-images.githubusercontent.com/4669452/187678667-5af8c8ab-e9ce-42c4-b9a2-692a6fce3c4e.png)

**Comment by RezaYazdaniAminabadi** [comment]
Hi @yingapple

Can you try this [PR ](https://github.com/microsoft/DeepSpeed/pull/2212)and see if it resolves your issue?
Thanks.
Reza

**Comment by yingapple** [comment]
> Hi @yingapple
> 
> Can you try this [PR ](https://github.com/microsoft/DeepSpeed/pull/2212)and see if it resolves your issue? Thanks. Reza

Thanks, I will try it soon.

**Comment by yingapple** [comment]
> Hi @yingapple
> 
> Can you try this [PR ](https://github.com/microsoft/DeepSpeed/pull/2212)and see if it resolves your issue? Thanks. Reza

I found it works. Thanks! Howerver, I get an other question when I use batch input for inference. Just the first input of the batch is right. The last output are all wrong. could you please tell me what's going wrong?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @yingapple 

Can you please open another issue regarding this? 
I have an idea how to solve it. Let's first merge this, and then we get to the other issue.
Thanks,
Reza

**Comment by yingapple** [comment]
> Hi @yingapple
> 
> Can you please open another issue regarding this? I have an idea how to solve it. Let's first merge this, and then we get to the other issue. Thanks, Reza

Sure! Thank you!
