### ISSUE TITLE
[Question] about compression.helper.convert_conv1d_to_linear

### ISSUE THREAD

**Issue by xk503775229** [microsoft/DeepSpeed#2294]
hi，when i use compression (zero_quant method), I found that we need to change conv1d to linear in GPT model. I just want to figure out this action. could you tail me why need to do this action ?

model = convert_conv1d_to_linear(model, Conv1D)

![image](https://user-images.githubusercontent.com/18070856/188534256-e6cb0a93-7ce6-4d94-add1-7a4e32b83cc5.png)

**Comment by xiaoxiawu-microsoft** [comment]
Hi, thanks for your question. 

The reason we need to covert the cov1d module to linear is that since the two are the same. And  our library supports compression mainly on linear module not on covn1d.  

Let us know if this helps :)

**Comment by yaozhewei** [comment]
Looks like Xiaoxia has resolved the issue
