### ISSUE TITLE
[BUG] assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"

### ISSUE THREAD

**Issue by archieCanada** [microsoft/DeepSpeed#2337]
**Describe the bug**

When I run End-to-End GPT NEO 2.7B Inference using code in the tutorial https://www.deepspeed.ai/tutorials/inference-tutorial/ I receive the following Error:

assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)".

**System info (please complete the following information):**
 - 2 x NVIDIA V100 Volta (32G HBM2 memory)
 - 80 GB CPU RAM

**Comment by macabdul9** [comment]
How did you fix it? @archieCanada
