### ISSUE TITLE
PipelineModule and LayerSpec for CIFAR10 training

### ISSUE THREAD

**Issue by bruno-darochac** [microsoft/DeepSpeed#2388]
Hi, I'm trying to use the PipelineModule to construct my training network.

As your tutorial (https://www.deepspeed.ai/tutorials/pipeline/) shows, I've tried to separate in layers my training. But I'm not sure if I've correctly understand how to perform that.

Basically I went from a classical CIFAR10 Network class : 

```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
```

To a Pipeline decription using LayerSpec : 
```python
def join_layers(vision_model):
    layers = [
        vision_model.conv1,
        F.relu,
        vision_model.pool,
        vision_model.conv2,
        F.relu,
        vision_model.pool,
        lambda x: x.view(-1, 16 * 5 * 5),
        vision_model.fc1,
        F.relu,
        vision_model.fc2,
        F.relu,
        vision_model.fc3
    ]
    return layers
```

But it seems blocked at the `deepspeed_initialize`call. What I don't understand in your tutorial is how did you manage to tell what you should put in the `LayerSpec` and what you shouldn't and is there any case where it is not possible to do it (for exemple on my forward function how I can specifiy the use of `view` or any other special things).

Because when I give a look at the PipelineModule I (don't know if it is right) understand that he will interpret the layers given and prepare the forward func for the training. Therefore I would be able to use the `train_batch()` func on my model_engine to make the training.

Those problems appear on torch 1.13 and cuda 11.7

Sorry in advance if it is maybe trivial and I just don't get it ^^''

**Comment by Otabiel** [comment]
I've figure this problem by disabling in the deepspeed config file the fp16 option. And now the training goes well.

But I've got a special comportment that I don't understand. If i take as example your cifar [example](https://github.com/microsoft/DeepSpeedExamples/tree/master/cifar), if I launch it and got in my environement two GPUs it will run two subprocess who will make the exact same job. 

Now if I run it with my pipeline version, I can observe the same comportement for the begging and the end, but the training is made only once. So my question is why I've two subprocess of my program but my training seems to be correctly managed between the two GPUs...
