### ISSUE TITLE
Zero2 save pytorch_model.bin.index.json

### ISSUE THREAD

**Issue by ZeyiLiao** [microsoft/DeepSpeed#2396]
**Describe the bug**
Hi, when I used huggingface trainer with ZeRO2 , it saved some file named `pytorch_model.bin.index.json`, I just don't know how to load it for inference.
I tried 
```
T5ForConditionalGeneration.from_pretrained('<path-to-checkpoint>') 
```
and it reported that it can not find pytorch_model.bin. (ZeRO3 can work and it saved pytorch_model.bin)

**Expected behavior**
Successfully load the ckpt.

**ds_report output**
<img width="988" alt="image" src="https://user-images.githubusercontent.com/97815464/194185015-f2f12b1e-264f-4742-8eca-6c81abaa088c.png">

**Comment by lekurile** [comment]
Hi @ZeyiLiao,

I'm curious on how ZeRO3 worked and ZeRO2 did not. Can you please provide a reproduction script showing how the training and inference is done for both ZeRO2 and ZeRO3? 

Thanks,
Lev

**Comment by lekurile** [comment]
Closing the issue for now, but feel free to re-open this in the future!

**Comment by ZeyiLiao** [comment]
Hi @lekurile , I think I figure that out! But still have a quick question about how to change pytorch_model.bin.index into a normal pytorch_model.bin to save memory.
