### ISSUE TITLE
[Help] About ZERO 3 model saving and loading

### ISSUE THREAD

**Issue by XiaoqingNLP** [microsoft/DeepSpeed#2413]
**Is your feature request related to a problem? Please describe.**

1. after saving the zero 3 model, there is successful loading several times, but occasionally there is a shape that some weights in the saved model have a shape of 0, resulting in a mismatch when loading, why is this?
2. I want to do model parameter merging after saving the model in zero 3 so that I can load the model inference in fewer machines, is it enough to concat the parameters in zero_pp_rank_0_mp_rank_00_model_states.pt into the desired mp dimensions?

**Comment by nijkah** [comment]
Hello @XiaoqingNLP. I am also troubleshooting about saving ZeRO 3 models.
It may be different from your issue. 

I am trying to test the `DeepSpeedEngine.save_checkpoint`.
I found that the below config changing `"stage=3"` cannot normally save the model's weights.
https://github.com/microsoft/DeepSpeedExamples/blob/master/cifar/ds_config.json

Although files are saved, it has empty tensors for modules as follows.
```
>>> import torch
>>> torch.load('zero_pp_rank_0_mp_rank_00_model_states.pt')
{'module': OrderedDict([('conv1.weight', tensor([], device='cuda:0', dtype=torch.float16)), ('conv1.bias', tensor([], device='cuda:0', dtype=torch.float16)), ('conv2.weight', tensor([], device='cuda:0', dtype=torch.float16)), ('conv2.bias', tensor([], device='cuda:0', dtype=torch.float16)), ('fc1.weight', tensor([], device='cuda:0', dtype=torch.float16)), ('fc1.bias', tensor([], device='cuda:0', dtype=torch.float16)), ('fc2.weight', tensor([], device='cuda:0', dtype=torch.float16)), ('fc2.bias', tensor([], device='cuda:0', dtype=torch.float16)), ('fc3.weight', tensor([], device='cuda:0', dtype=torch.float16)), ('fc3.bias', tensor([], device='cuda:0', dtype=torch.float16))]), 'buffer_names': [], 'optimizer': None, 'param_shapes': [OrderedDict([('conv1.weight', torch.Size([6, 3, 5, 5])), ('conv1.bias', torch.Size([6])), ('conv2.weight', torch.Size([16, 6, 5, 5])), ('conv2.bias', torch.Size([16])), ('fc1.weight', torch.Size([120, 400])), ('fc1.bias', torch.Size([120])), ('fc2.weight', torch.Size([84, 120])), ('fc2.bias', torch.Size([84])), ('fc3.weight', torch.Size([10, 84])), ('fc3.bias', torch.Size([10]))])], 'lr_scheduler': {'last_batch_iteration': 5110}, 'sparse_tensor_module_names': set(), 'skipped_steps': 14, 'global_steps': 5125, 'global_samples': 82000, 'dp_world_size': 4, 'mp_world_size': 1, 'ds_config': 'ds_config.json', 'ds_version': '0.7.3', 'checkpoint_step': 1999}
>>> torch.load('zero_pp_rank_1_mp_rank_00_model_states.pt')
{'module': OrderedDict([('conv1.weight', tensor([], device='cuda:1', dtype=torch.float16)), ('conv1.bias', tensor([], device='cuda:1', dtype=torch.float16)), ('conv2.weight', tensor([], device='cuda:1', dtype=torch.float16)), ('conv2.bias', tensor([], device='cuda:1', dtype=torch.float16)), ('fc1.weight', tensor([], device='cuda:1', dtype=torch.float16)), ('fc1.bias', tensor([], device='cuda:1', dtype=torch.float16)), ('fc2.weight', tensor([], device='cuda:1', dtype=torch.float16)), ('fc2.bias', tensor([], device='cuda:1', dtype=torch.float16)), ('fc3.weight', tensor([], device='cuda:1', dtype=torch.float16)), ('fc3.bias', tensor([], device='cuda:1', dtype=torch.float16))]), 'buffer_names': [], 'optimizer': None, 'param_shapes': [OrderedDict([('conv1.weight', torch.Size([6, 3, 5, 5])), ('conv1.bias', torch.Size([6])), ('conv2.weight', torch.Size([16, 6, 5, 5])), ('conv2.bias', torch.Size([16])), ('fc1.weight', torch.Size([120, 400])), ('fc1.bias', torch.Size([120])), ('fc2.weight', torch.Size([84, 120])), ('fc2.bias', torch.Size([84])), ('fc3.weight', torch.Size([10, 84])), ('fc3.bias', torch.Size([10]))])], 'lr_scheduler': {'last_batch_iteration': 5110}, 'sparse_tensor_module_names': set(), 'skipped_steps': 14, 'global_steps': 5125, 'global_samples': 82000, 'dp_world_size': 4, 'mp_world_size': 1, 'ds_config': 'ds_config.json', 'ds_version': '0.7.3', 'checkpoint_step': 1999}
```

Can I ask you to share the experiment setting you tested?

**Comment by XiaoqingNLP** [comment]
@nijkah Our problem is quite similar, I also found out that the weights I saved, some of them also have a shape of 0; you can try zero_to_fp32.py

**Comment by tjruwase** [comment]
@XiaoqingNLP, apologies for the delay. Is this still an issue?

**Comment by nijkah** [comment]
@XiaoqingNLP Sorry for the late response. 
In my experiments, none of the model weights were saved in the `zero_pp_*_model_states.pt`.
I think there can be one that has a shape of 0 if the model is not split evenly.

In most cases, it was enough to consolidate the split model weights using [`zero_to_fp32.py`](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/utils/zero_to_fp32.py) to me.

Is there any further issue?

**Comment by XiaoqingNLP** [comment]
@tjruwase @nijkah Thanks for your reply, I solved the problem after some attempts as I understood it.

**Comment by tjruwase** [comment]
@XiaoqingNLP, I am very happy to hear that. In that case, I will close this issue. Please feel free to (re)open if needed.

**Comment by Shaukat-Hussain** [comment]
Hi experts, I am relatively new to experiencing deepspeed library, just wanted to know when the files are already saved in pytorch_model.bin and a bunch of JSON files and a text file. what is the significance of global_stepXXX directory and files inside this directory  zero_pp_rank_0_mp_rank_00_model_states.pt , it really takes up a huge space and most of the time makes the disk full causing model training to crash in the middle. thanks in advance.

**Comment by tjruwase** [comment]
@Shaukat-Hussain, global_stepXXX contains the checkpoint after XXX iteration. One way to reduce the number of these folders is to increase the checkpointing interval. The `*.pt` are the various checkpoint states.

**Comment by Shaukat-Hussain** [comment]
> 

Thank you for your prompt response!

**Comment by Quan-Sun** [comment]
@XiaoqingNLP Hi, XiaoqingNLP. I got the same problem that the saved model has params with a shape of 0. Could you please share your solutions?

**Comment by mynewstart** [comment]
> @XiaoqingNLP Hi, XiaoqingNLP. I got the same problem that the saved model has params with a shape of 0. Could you please share your solutions?

I have same problem, have you solved?

**Comment by SihengLi99** [comment]
I have the same problem
