### ISSUE TITLE
[BUG] Fix proposal for FLOPS

### ISSUE THREAD

**Issue by bruno-darochac** [microsoft/DeepSpeed#2414]
Hi, I was trying to use flops profiler and I found a problem. 

When in the forward pass of my nn I have a call to a pool method, there is a miss match between torch parameters for pool methods and your wrapped method in `profiling/flops_profiler/profiler.py`  `_pool_flops_compute`.

In torch the call is like : 
```python
def forward(self, input: Tensor):
        return F.max_pool2d(input, self.kernel_size, self.stride,
                            self.padding, self.dilation, ceil_mode=self.ceil_mode,
                            return_indices=self.return_indices)
```

And in your profiler is : 
```python
def _pool_flops_compute(input,
                        kernel_size,
                        stride=None,
                        padding=0,
                        ceil_mode=False,
                        count_include_pad=True,
                        divisor_override=None,):
```

In your method the `dilation` and `return_indices` are missing. To verifiy if that was the problem, I just treid to add them by my self as : 

```python
def _pool_flops_compute(input,
                        kernel_size,
                        stride=None,
                        padding=0,
                        dilation=None,
                        ceil_mode=False,
                        count_include_pad=True,
                        divisor_override=None,
                        return_indices=None):
```
And after that my training works fine. I've tried to make a PR with a branch that I've created called "flops_wrapper_modif" but I didn't have the necessary right to make a proposal, so I've made this issue to inform you of that possible modification.

In my environment I have : 
- torch v.1.12.1
- deepspeed v.0.7.3

**Comment by cli99** [comment]
Hi @bruno-darochac, thanks for pointing this out. Made this PR https://github.com/microsoft/DeepSpeed/pull/2443 to fix it.
