### ISSUE TITLE
Inference Megatron GPT2 ERROR.

### ISSUE THREAD

**Issue by cdj0311** [microsoft/DeepSpeed#2421]
Hi,
   I have trained a GPT2 model with Megatron-LM, however, I get an error when inference with deepspeed, such as: 
```
Traceback (most recent call last):
  File "ds_inference.py", line 19, in <module>
    model = deepspeed.init_inference(
  File "/home/python3.8/site-packages/deepspeed/__init__.py", line 305, in init_inference
    engine = InferenceEngine(model,
  File "/home/python3.8/site-packages/deepspeed/inference/engine.py", line 145, in __init__
    self._apply_injection_policy(
  File "/home/python3.8/site-packages/deepspeed/inference/engine.py", line 342, in _apply_injection_policy
    replace_transformer_layer(client_module,
  File "/home/python3.8/site-packages/deepspeed/module_inject/replace_module.py", line 848, in replace_transformer_layer
    checkpoint = checkpoint_dict['checkpoints']
TypeError: 'MegatronSDLoader' object is not subscriptable
```

   The scripts:
```
import torch
import torch.distributed as dist
import deepspeed
from transformers.deepspeed import HfDeepSpeedConfig
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer
config = AutoConfig.from_pretrained("config.json")

ds_config = {
    "fp16": {
        "enabled": True,
    },
    "train_micro_batch_size_per_gpu": 1,
    "wall_clock_breakdown": False,
}
dschf = HfDeepSpeedConfig(ds_config)
model = AutoModelForCausalLM.from_config(config, torch_dtype=torch.float16)
model = model.eval()

model = deepspeed.init_inference(
    model,
    mp_size=1,
    dtype=torch.float16,
    replace_with_kernel_inject=True,
    checkpoint="./checkpoint.json",
)
```

The checkpoint.json as follows:
```
{
    "type": "Megatron",
      "version": 0.0,
      "checkpoints": [
          "mp_rank_00/model_optim_rng.pt"
      ]
}
```

How can I solve it?

Thanks!

**Comment by awan-10** [comment]
@cdj0311 -- Thanks for reporting the issue? We will take a look at this but can you please share the exact version/code (or GitHub link) of the Megatron framework you used to train the model? We have different versions so I want to ensure we reproduce your issue with the right version. Also, if its possible to share the checkpoint file (if its not too large or private), we maybe able to reproduce/fix the issue faster.

**Comment by cdj0311** [comment]
> @cdj0311 -- Thanks for reporting the issue? We will take a look at this but can you please share the exact version/code (or GitHub link) of the Megatron framework you used to train the model? We have different versions so I want to ensure we reproduce your issue with the right version. Also, if its possible to share the checkpoint file (if its not too large or private), we maybe able to reproduce/fix the issue faster.

Thanks for your reply!
deepspeed version=0.7.4
megatron-lm=3.0 (https://github.com/NVIDIA/Megatron-LM)
The checkpoint file is too large to share .

**Comment by awan-10** [comment]
@cdj0311 - I tried to reproduce the issue on our end but I am having some difficulty as I don't see an inference example on the NVIDIA/Megatron repo anymore. They have moved to some inference server. I will spend more time to reproduce this from an older branch/fork. Meanwhile, I tried this approach to convert a Megatron model to HuggingFace model and it worked for me for their default GPT-345m checkpoint. Details are here: https://huggingface.co/nvidia/megatron-gpt2-345m. Can you try this method on your end?
