### ISSUE TITLE
Bloom int8 quantization

### ISSUE THREAD

**Issue by rhenry-nv** [microsoft/DeepSpeed#2434]
Hi, 

I was taking a look at the bloom int8 model [here](https://huggingface.co/microsoft/bloom-deepspeed-inference-int8/tree/main) and I am just trying to understand the shapes of the scales for each weight. 

For example, if I load `tp_00_00.pt` and look at the weight `transformer.h.1.attention.attn_ow` or `transformer.h.7.mlp.inter_w`, I see the scale shape is [32, 3]. Why is this the case?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @rhenry-nv,

That's a good question. We are using this checkpoint to run both on 4-way parallel and 8-way parallel GPU setup. The first 32 elements are the scales when running on 4-GPU and the second 2 groups of 32 scales are used when running on 8 GPU in which case the weights are sharded between two GPU ranks. Hope this answers your question.
Best,
Reza

**Comment by rhenry-nv** [comment]
Hi @RezaYazdaniAminabadi,

Thank you so much for the clear explanation. I am marking as closed.
