### ISSUE TITLE
What's the use of synchronization in activation checkpointing?

### ISSUE THREAD

**Issue by afcruzs** [microsoft/DeepSpeed#2439]
There's a few sync points in activation checkpointing, which [is enabled by a flag](https://deepspeed.readthedocs.io/en/latest/activation-checkpointing.html). Can you elaborate when is that useful or on what scenarios *must* be enabled? Native pytorch's activation checkpointing or the vainilla MegatronLM doesn't seem to have it
- https://github.com/microsoft/DeepSpeed/blob/afdc72879f66c419ee02d32decf07185506bff85/deepspeed/runtime/activation_checkpointing/checkpointing.py#L514
- https://github.com/microsoft/DeepSpeed/blob/afdc72879f66c419ee02d32decf07185506bff85/deepspeed/runtime/activation_checkpointing/checkpointing.py#L604
- https://github.com/microsoft/DeepSpeed/blob/afdc72879f66c419ee02d32decf07185506bff85/deepspeed/runtime/activation_checkpointing/checkpointing.py#L631
- https://github.com/microsoft/DeepSpeed/blob/afdc72879f66c419ee02d32decf07185506bff85/deepspeed/runtime/activation_checkpointing/checkpointing.py#L732

**Comment by samyam** [comment]
Hi @afcruzs, 

For majority of the cases, this does not need to be enabled. 

The cases where we found it useful to have this synchronization is for extremely massive models, with large batch sizes, running very close to the memory limit. Our empirical evaluation showed that in these scenarios having synchronizations can have the following impact:

i) speeding up the training 
ii) avoiding OOMs. 

We did not do a deep study of this behavior, but our conjecture at the time of adding this feature is that the synchronization reduces memory pressure by avoiding memory allocations until the previous computation is done. This results in slightly lower memory usage and therefore also faster memory allocation in presence of memory fragmentation, which often is a problem when running very close to the memory llimit.

**Comment by afcruzs** [comment]
Thank you @samyam very interesting! Does this mean that adding the sync point would, presumably, give time for the previous computation to release memory that would be used after the sync point? or am I reading it incorrectly?

**Comment by samyam** [comment]
@afcruzs you are reading it correct. That is my conjecture on why at the limit, we were seeing faster performance and OOM avoidance when we added the synchronization.

**Comment by afcruzs** [comment]
Thank you for sharing that :)
