### ISSUE TITLE
[Question] MoE: Why exp_counts have to be moved to CPU?

### ISSUE THREAD

**Issue by clumsy** [microsoft/DeepSpeed#2444]
For top-k gating decision `exp_counts` is unconditionally moved to CPU, e.g. [here](https://github.com/microsoft/DeepSpeed/blob/7d113633e4cd0e430d4a07cb78ee700b3c03423f/deepspeed/moe/sharded_moe.py#L211).

I can't find why would this be required. Perhaps a comment can be added somewhere if not already mentioned.
If not required this seems like a minor but an overhead.

**Comment by clumsy** [comment]
Is there anywhere I can read about the idea behind this? Thanks!

**Comment by ranzhejiang** [comment]
This issue has been solved, now `exp_counts` is no need to moved to CPU.

**Comment by tjruwase** [comment]
@ranzhejiang, thanks for the update. Closing!
