### ISSUE TITLE
[BUG] Does Zeros optimizations works on windows? any eta when it will?

### ISSUE THREAD

**Issue by mhnoni** [microsoft/DeepSpeed#2453]
I'm getting the below error when I use deepspeed on windows with py10/torch1.12.1+cu113, 
Tried stage 2 and 3 to offload to the CPU with the default settings. 

  File "C:\Users\MH\AppData\Local\Programs\Python\Python310\lib\subprocess.py",
line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Thanks!

**Comment by jeffra** [comment]
Are you trying to use this for training a model or inference? If so, can you open a new issue with the specific template and provide the requested details there (about your environment, etc)?

**Comment by mhnoni** [comment]
> Are you trying to use this for training a model or inference? If so, can you open a new issue with the specific template and provide the requested details there (about your environment, etc)?

yes, for training a model, is it supported yet on windows? if no so I don't have to open a new bug report ticket. 

Thanks!
