### ISSUE TITLE
[QUESTION] Cuda graph support for word size > 1

### ISSUE THREAD

**Issue by cyang49** [microsoft/DeepSpeed#2456]
Hi, I noticed that when the `enable_cuda_graph` flag is set to True, the program halts due to the check of world size > 1 and model parallelism used. What is the reason that cuda graph cannot be used in the model parallel scenario? Thanks

**Comment by jeffra** [comment]
@cyang49, we don't currently support this. @molly-smith, let's add an assert to that users know that we don't support this case.

**Comment by mrwyattii** [comment]
> @cyang49, we don't currently support this. @molly-smith, let's add an assert to that users know that we don't support this case.

@jeffra we already have an assert for this: https://github.com/microsoft/DeepSpeed/blob/3432c740e99cab9e78c67b59ca3c53d49e4b29b7/deepspeed/inference/engine.py#L172

**Comment by cyang49** [comment]
Hi, I saw the code with assertion. Can you say a few words about why? Is it a feature to be implemented or is there some inherent incompatibility for Cuda graph with MP? Thanks
