### ISSUE TITLE
[BUG]Call torch.cuda.synchronize each time to reduce gradients in ZeRO Stage2

### ISSUE THREAD

**Issue by li-yi-dong** [microsoft/DeepSpeed#2463]
**Describe the bug**
When training with Stage2, I noticed that `DeepSpeedZeroOptimizer` would synchronize the whole GPU before each time to launch a new `reduce`:
```Python
def average_tensor(self, tensor):
    if self.overlap_comm:
        torch.cuda.synchronize()
        stream = self.reduction_stream
    else:
        stream = torch.cuda.current_stream()

    with torch.cuda.stream(stream):
        if not self.reduce_scatter:
            self.gradient_reduction_w_predivide(tensor)
            return
        ...
```
Timeline:
![image](https://user-images.githubusercontent.com/73142299/199200577-f180dc45-011d-4e51-95a0-789c721609d9.png)

This reduces the opportunity for overlapping of the communication and hurts the performance a lot.
Why this synchronization is needed? Is it possible to remove it?

**Comment by samyam** [comment]
Hi @li-yi-dong, the synchronize ensures that the `tensor` that we are about to reduce in the `average_tensor` already has the gradients in it. Without the synchronization, the reduction of the `tensor` can initiate on the reduction stream without the results of the gradient calculation being placed in the `tensor` by the current stream. 

Essentially what is happening is as follows:

```
with torch.cuda.stream(torch.cuda.current_stream()):
    tensor.copy_(compute_gradients())

#Ensure the compute gradients and copy complete before the reduction on a different stream
torch.cuda.synchronize()

with torch.cuda.stream(self.reduction_stream):
    dist.reduce(tensor)
```
    
The actual overlapping happens between the reduction and the next gradient computation happening later in the backward pass. 

Please let me know if you have any further questions.

**Comment by li-yi-dong** [comment]
> Hi @li-yi-dong, the synchronize ensures that the `tensor` that we are about to reduce in the `average_tensor` already has the gradients in it. Without the synchronization, the reduction of the `tensor` can initiate on the reduction stream without the results of the gradient calculation being placed in the `tensor` by the current stream.
> 
> Essentially what is happening is as follows:
> 
> ```
> with torch.cuda.stream(torch.cuda.current_stream()):
>     tensor.copy_(compute_gradients())
> 
> #Ensure the compute gradients and copy complete before the reduction on a different stream
> torch.cuda.synchronize()
> 
> with torch.cuda.stream(self.reduction_stream):
>     dist.reduce(tensor)
> ```
> 
> The actual overlapping happens between the reduction and the next gradient computation happening later in the backward pass.
> 
> It should be possible to remove the synchronization by placing a cuda event in the current stream after the gradient calculation and just waiting for this on the reduction stream. This will block the reduction stream until the gradient is computed, but it will not block the current stream and might allow for better overlap. We would be happy to take a PR on this :)
> 
> Please let me know if you have any further questions.

Thanks a lot for the insight! @samyam 
As for the improvement, we can launch an `event` at the end of `copy_grads_in_partition`, like:
```Python
def copy_grads_in_partition(self, param):
    if self.cpu_offload:

        if self.gradient_accumulation_steps > 1:
            self.async_accumulate_grad_in_cpu_via_gpu(param)

        if self.is_gradient_accumulation_boundary:
            self.set_norm_for_param_grad_in_gpu(param)

            self.update_overflow_tracker_for_param_grad(param)

            self.async_inplace_copy_grad_to_fp32_buffer_from_gpu(param)

        torch.cuda.Event()

        return
    #print(f"ID {self.get_param_id(param)} grad norm {param.grad.norm()}")
    if self.grads_in_partition is None:
        self.grads_in_partition_offset = 0
        total_size = 0
        for group in self.params_in_partition:
            for param_in_partition in group:
                total_size += param_in_partition.numel()

        see_memory_usage(f"before copying {total_size} gradients into partition")
        self.grads_in_partition = torch.empty(int(total_size),
                                                dtype=self.dtype,
                                                device=torch.cuda.current_device())
        see_memory_usage(f"after copying {total_size} gradients into partition")

    # The allreduce buffer will be rewritten. Copy the gradients in partition to a new buffer
    new_grad_tensor = self.grads_in_partition.view(-1).narrow(
        0,
        self.grads_in_partition_offset,
        param.numel())
    new_grad_tensor.copy_(param.grad.view(-1))
    param.grad.data = new_grad_tensor.data.view_as(param.grad)
    #print(f"Grad norm after copy to contiguous_buffer {param.grad.data.norm()}")
    self.grads_in_partition_offset += param.numel()

    torch.cuda.Event()
```

Then synchronize this `event` at the beginning of `average_tensor`?
Maybe I can start a PR 🙃

**Comment by jeffra** [comment]
Yes please, a PR would be wonderful :) Thank you @li-yi-dong
