### ISSUE TITLE
[REQUEST] Does DeepSpeed support ONNX export and Triton Inference Server?

### ISSUE THREAD

**Issue by stevezheng23** [microsoft/DeepSpeed#2465]
Hi team, QQ: does `deepspeed` support the followings,
- Convert HuggingFace BERT/RoBERTa models to `int8` precision directly
- If yes, can the converted model be exported to ONNX format directly?
- If so, can the exported ONNX model loaded correctly using Triton Inference Server?

**Comment by awan-10** [comment]
Can you kindly provide a concrete example to show what you are trying to achieve?

**Comment by cmikeh2** [comment]
Please re-open this issue if this is something still important to you.
