### ISSUE TITLE
[BUG]Will cause Tensor contiguous bug in model_compression. need add contiguous after weight transpose

### ISSUE THREAD

**Issue by hudengjunai** [microsoft/DeepSpeed#2490]
https://github.com/microsoft/DeepSpeed/blob/521d329b975de97ec0b52395f02bb32466b8dc35/deepspeed/compression/helper.py#L275

**Comment by hudengjunai** [comment]
change to 
```
new_module.weight.data = old_module.weight.data.t().contiguos()
```

**Comment by yaozhewei** [comment]
Hi, 

Do you like to create a PR to help fix this?
