### ISSUE TITLE
Info message when importing deepspeed: Redirects are currently not supported in Windows or MacOs

### ISSUE THREAD

**Issue by awaelchli** [microsoft/DeepSpeed#2492]
**Describe the bug**

When importing deepspeed, the torch distributed backend is printing a message

```
NOTE: Redirects are currently not supported in Windows or MacOs
```

**To Reproduce**
1. `pip install deepspeed==0.7.4` and torch 1.13
2. `import deepspeed`

**Expected behavior**

The info message is confusing. It is not clear what the user should do, or whether they can ignore the message.
The message seems to be caused by importing `torch.distributed.run` or torchelastic.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn cuda is not available from torch
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/Users/adrian/miniconda3/envs/lightning/lib/python3.9/site-packages/torch']
torch version .................... 1.13.0
torch cuda version ............... None
torch hip version ................ None
nvcc version .....................  [FAIL] cannot find CUDA_HOME via torch.utils.cpp_extension.CUDA_HOME=None 
deepspeed install path ........... ['/Users/adrian/miniconda3/envs/lightning/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.7.4, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.13, cuda 0.0

```

**Screenshots**
None.

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] MacOS 12.4
 - GPU count and types [e.g. two machines with x8 A100s each] M1
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB] N/A
 - Python version 3.10
 - Any other relevant info about your setup: torch 1.13

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

No

**Docker context**
Are you using a specific docker image that you can share?

None

**Additional context**

I am not 100% where this issues should be resolved, in deepspeed or in PyTorch. I'm raising it here to bring awareness. I investigated this because I noticed this warning in [Lightning](https://github.com/Lightning-AI/) when importing the package, and I tracked it down to deepspeed, which we import when available.

**Comment by jomayeri** [comment]
DeepSpeed uses redirects from Pytorch for logging when elastic training is enabled in the ds_config. This is [not supported](https://discuss.pytorch.org/t/what-does-note-redirects-are-currently-not-supported-in-windows-or-macos-mean-in-pytorch/143319) in Pytorch for Windows and MacOS.

I'll look at what can be done to make the issue clearer to the user.

**Comment by awaelchli** [comment]
@jomayeri Thank you. I do understand that the warning can be useful, but probably shouldn't be triggered at import time, only when the user calls the relevant functions. 

Note that the warning also triggers if one just imports 
```py
from torch.distributed import run
```

I think that if deepspeed makes the torchelastic-related imports lazy, this issue should be solved.

**Comment by jomayeri** [comment]
Closing for now.  Will reopen if it becomes an issue again once DeepSpeed is available on these platforms.
