### ISSUE TITLE
Fail (OOM) to train model whose parameter size larger than GPU memory capacity

### ISSUE THREAD

**Issue by zhiqi-0** [microsoft/DeepSpeed#2497]
Hi team, I want to use Zero (Stage-3 + offload) optimizations to train a model whose parameter size is larger than GPU memory capacity. However, I got OOM error as deepspeed requires the model to totally reside inside the GPU, see code here (that's where the OOM occurs):

https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/engine.py#L1056

```
            self.module.to(self.device)
```

Is there any way to solve this issue?

**Comment by tjruwase** [comment]
@zhiqi-0, with offload deepspeed does not require entire model to fit inside the GPU. Please see the following
https://deepspeed.readthedocs.io/en/latest/zero3.html#constructing-massive-models

**Comment by zhiqi-0** [comment]
Great thanks @tjruwase! I can train the model now.

Just a double confirmation for correct usage, I initialize the model with the following code:

```py
zero3_config = {
   ...,
  "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.00015,
            "betas": [0.9, 0.95]
        }
    },
   ...,
}

with deepspeed.zero.Init(config_dict_or_path=zero3_config):
    model = MyModel()

model, _, _, _ = deepspeed.initialize(
      model=model,
      model_parameters=model.parameters(),
      dist_init_required=False,
      config=zero3_config,
)
```

Is this the correct way to use deepspeed?  The configuration is passed double time in `zero.Init` and `deepspeed.initialize`.

**Comment by tjruwase** [comment]
Yes, configuration needs to be passed twice for this case. You may also find the following links useful for configuring offloading

1. https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
2. https://www.deepspeed.ai/tutorials/zero-offload/
3. https://www.deepspeed.ai/tutorials/zero/#training-trillion-scale-models-with-zero-infinity

**Comment by zhiqi-0** [comment]
Thanks a lot!
