### ISSUE TITLE
[BUG] CUDA OOM error when loading opt-30b

### ISSUE THREAD

**Issue by Tianwei-She** [microsoft/DeepSpeed#2520]
**Describe the bug**
I got CUDA OOM error when loading model `facebook/opt-30b`, however the model can be successfully loaded onto GPUs with huggingface transformers.

```
RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 3; 22.20 GiB total capacity; 21.47 GiB already allocated; 16.06 MiB free; 21.47 GiB reserved in total by
PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2022-11-17 22:47:34,890] [INFO] [launch.py:289:sigkill_handler] Killing subprocess 88730
[2022-11-17 22:47:34,912] [INFO] [launch.py:289:sigkill_handler] Killing subprocess 88731
[2022-11-17 22:47:34,930] [INFO] [launch.py:289:sigkill_handler] Killing subprocess 88732
[2022-11-17 22:47:34,930] [INFO] [launch.py:289:sigkill_handler] Killing subprocess 88733
[2022-11-17 22:47:34,955] [INFO] [launch.py:289:sigkill_handler] Killing subprocess 88734
[2022-11-17 22:47:34,973] [INFO] [launch.py:289:sigkill_handler] Killing subprocess 88735
[2022-11-17 22:47:34,991] [INFO] [launch.py:289:sigkill_handler] Killing subprocess 88736
[2022-11-17 22:47:35,060] [INFO] [launch.py:289:sigkill_handler] Killing subprocess 88737
```

**To Reproduce**

I ran `deepspeed --num_gpus 8 test_deepspeed.py`

```
# deepspeed_test.py
import os

import deepspeed
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

model_name = "facebook/opt-30b"

local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.add_special_tokens({"pad_token": "[PAD]"})
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto")

model = deepspeed.init_inference(
    model,
    mp_size=world_size,
    dtype=model.dtype,
    replace_method="auto",
    replace_with_kernel_inject=True,
)

test = "test prompt"
max_new_tokens = 100

generator = pipeline(task="text-generation", model=model, tokenizer=tokenizer, device=local_rank)

result = generator(test, do_sample=True, max_new_tokens=max_new_tokens)

if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(result)
```
torch                     1.12.1+cu116
deepspeed                 0.7.4
transformers              4.22.2 

**Expected behavior**
My expectation was if the model can be loaded to GPU with hugginface, it should be able to work with deepspeed inference. Or if there's any clear documentation about how to load large models, it'll help clarify things a lot.

**ds_report output**
Please run `ds_report` to give us details about your setup.
![image](https://user-images.githubusercontent.com/33010862/202580194-24c456b7-9cd4-4533-804a-bdc1b21539b0.png)

**System info (please complete the following information):**
 - GPU count and types: a `g5.48xlarge` EC2 instance, with 8 A10G gpus.

**Comment by lanking520** [comment]
Also facing similar issues

**Comment by lanking520** [comment]
@RezaYazdaniAminabadi thanks for the fix. Is this bug introduced by DeepSpeed or HuggingFace changed the model signature in 4.23 and on?

**Comment by lanking520** [comment]
https://github.com/microsoft/DeepSpeed/pull/2541

**Comment by RezaYazdaniAminabadi** [comment]
Hi @lanking520,

No this should not be related to HF. It was related to this PR which you mentioned in your last message. The problem is it was not injecting the kernels in this case and therefore it was not parallelizing the model.
Thanks,
Reza

**Comment by jeffra** [comment]
@lanking520 and @Tianwei-She please re-open if you're still seeing an issue.
