### ISSUE TITLE
`deepspeed.comm.barrier()` has different signatures/behaviour from `torch.distributed.barrier()`

### ISSUE THREAD

**Issue by HeyangQin** [microsoft/DeepSpeed#2543]
https://github.com/microsoft/DeepSpeed/blob/4abf637f96cd36d450125a38a15d21df1cf0b8db/deepspeed/comm/comm.py#L456-L458

It seems the `deepspeed.comm.barrier()` has different signatures/behaviour from `torch.distributed.barrier()`. Is this intended?

reference: torch.distributed.barrier() https://github.com/pytorch/pytorch/blob/07dd2fe6c32948e5ca0a2871e5eb31602a9684cf/torch/distributed/distributed_c10d.py#L3182

Also, is `monitored_barrier()` supported in `deepspeed.comm`? Thanks!

**Comment by jeffra** [comment]
@Quentin-Anthony can you take a look at this? I think the `barrier` function signature needs to support `barrier(group=GroupMember.WORLD, async_op=False, device_ids=None)`

**Comment by Quentin-Anthony** [comment]
@jeffra -- Sure! 

I can also add `monitored_barrier()` support for you, @HeyangQin

**Comment by jeffra** [comment]
Awesome, thank you @Quentin-Anthony!

**Comment by Quentin-Anthony** [comment]
@HeyangQin -- I've created a PR at https://github.com/microsoft/DeepSpeed/pull/2570. Can you test it and ensure this works for you?

**Comment by HeyangQin** [comment]
@Quentin-Anthony That's exactly what I need. Thank you!
