### ISSUE TITLE
Code from DS inference examples do not replace T5 Block in T5 [BUG]

### ISSUE THREAD

**Issue by StochasticRomanAgeev** [microsoft/DeepSpeed#2549]
**Describe the bug**

After successful conversion of Flan T5 small to DS inference on T4 (g4dn.xlarge) T5Block module is still there, so there is now speedup.

**To Reproduce**

```python
from transformers import pipeline
import transformers
import deepspeed
import torch
import os
from transformers.models.t5.modeling_t5 import T5Block

local_rank = 0
world_size = 1

pipe = pipeline("text2text-generation", model="google/t5-v1_1-small", device=local_rank)

# The inpjection_policy shows two things:
#   1. which layer module we need to add Tensor-Parallelism
#   2. the name of several linear layers: a) attention_output (both encoder and decoder),
#       and b) transformer output

pipe.model = deepspeed.init_inference(
    pipe.model,
    mp_size=world_size,
    dtype=torch.float,
    injection_policy={T5Block: ('SelfAttention.o', 'EncDecAttention.o', 'DenseReluDense.wo')}
)

print(pipe.model)

pipe.device = torch.device(f'cuda:{local_rank}')
output = pipe("Is this review positive or negative? Review: this is the best cast iron skillet you will ever buy")

if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(output)
```

**Expected behavior**

I expect replacing T5 block with it's optimized version as it is done with the same code (except injection_policy) for Bert model

**ds_report output**

--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ubuntu/beam_search/venv/lib/python3.8/site-packages/torch']
torch version .................... 1.13.0+cu116
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed install path ........... ['/home/ubuntu/beam_search/venv/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.7.6+4abf637f, 4abf637f, master
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.6

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - 1x T4
 - Python 3.8.10
 - T4 (g4dn.xlarge) standard gpu image with pytorch 1.13

**Comment by molly-smith** [comment]
Hi @StochasticRomanAgeev , I ran your script and I see that T5Block injection policy is working as expected. Can you share what you see printed by your script? Thanks.

**Comment by molly-smith** [comment]
Closing. Please reopen if issues still exist.

**Comment by Wenhan-Tan** [comment]
Hi @molly-smith , I have a quick question. In this case, will this injection policy get you speedup on both single and multiple GPUs? Or is this injection policy only used for merging partial results across model-parallel ranks?

**Comment by molly-smith** [comment]
Hi @Wenhan-Tan, you will only see speedup on multiple GPUs. Performance should be more or less the same on single GPUs.
