### ISSUE TITLE
[BUG] DeepSpeed gives different results as Huggingface for greedy text generation

### ISSUE THREAD

**Issue by anselmwang** [microsoft/DeepSpeed#2576]
**Describe the bug**
I compared DeepSpeed Inference with Huggingface Accelerate inference with [Huggingface team's speed test code](https://github.com/anselmwang/transformers-bloom-inference/tree/fix-deadlock) (I only fix a small deadlock issue)

This is a greedy text generation task, the result should be same, but it is not.

**To Reproduce**
python 3.7.7

```bash
git clone https://github.com/anselmwang/transformers-bloom-inference/
cd transformers-bloom-inference
git checkout fix-deadlock

pip install --upgrade pip
pip install transformers>=4.21.3 accelerate>=0.12.0
pip install deepspeed>=0.7.3
python bloom-inference-scripts/bloom-accelerate-inference.py --name bigscience/bloom --batch_size 1 --benchmark
deepspeed --num_gpus 16 bloom-inference-scripts/bloom-ds-inference.py --name bigscience/bloom --batch_size 1 --benchmark
```

The result of HF Accelerate
![image](https://user-images.githubusercontent.com/7410579/205742293-688ebe6f-6d0f-4fed-8004-75b3828bbf3f.png)

The result of DeepSpeed
![image](https://user-images.githubusercontent.com/7410579/205742353-34d5b730-a918-4f86-b01d-8955a6f07d83.png)

**Expected behavior**
Results should be same.

**ds_report output**
Please run `ds_report` to give us details about your setup.
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report                                                                                              
--------------------------------------------------                                                                                 
NOTE: Ops not installed will be just-in-time (JIT) compiled at                    
      runtime if needed. Op compatibility means that your system                                                                                          
      meet the required dependencies to JIT install the op.                                                         
--------------------------------------------------
JIT compiled ops requires ninja                                                                                                              
ninja .................. [OKAY]                                                            
--------------------------------------------------
op name ................ installed .. compatible                                                                        
--------------------------------------------------        
cpu_adam ............... [NO] ....... [OKAY]            
cpu_adagrad ............ [NO] ....... [OKAY]                                                             
fused_adam ............. [NO] ....... [OKAY]                                                                      
fused_lamb ............. [NO] ....... [OKAY]                                                                       
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/torch']
torch version .................... 1.13.0+cu117
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed install path ........... ['/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.7.6, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7
```
**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU count and types: 1 node with 16x V100.
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 ```
transformers             4.25.1
accelerate               0.15.0
deepspeed                0.7.6
torch                    1.13.0
```
 - Python version: 3.7.7
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?
Not use docker
**Additional context**

The original Huggingface team's code use padding_right for such a generation task. there is a warning to use padding left. But this should not affect the result. Here is the padding code
`    input_tokens = tokenizer.batch_encode_plus(inputs, return_tensors="pt", padding=True)`

**Comment by RezaYazdaniAminabadi** [comment]
Hi @anselmwang,

I am wondering if this is due to different precision used between these two. If I understand correctly, you are doing inference with bf16 on the accelerate whereas using half-precision on the DeepSpeed side. Unfortunately, DeepSpeed-Inference does not support bf16, but can you please confirm if the issue is resolved with changing the dtype to half on the accelerate side?
Thanks,
Reza

**Comment by anselmwang** [comment]
@RezaYazdaniAminabadi , you are absolutely right. 

Accelerate script by default uses bl16, although my GPUs are V100 which don't support bf16. There are no clear errors, but the generated text is weird.

After using float16 for Accelerate script, it generates exactly same texts as DeepSpeed script.

Thanks a lot for your advice, it saves me days of work!
