### ISSUE TITLE
[BUG] Incomplete PipelineModule Documentation

### ISSUE THREAD

**Issue by jordan-schneider** [microsoft/DeepSpeed#2577]
**Describe the bug**
There is no argument documentation for the `checkpointable_layers` argument of `deepspeed.runtime.pipe.module.PipelineModule`'s `__init__()` function.

It seems like `checkpointable_layers` is `List[str]` of layer class names which mask off certain layers from checkpoint contention. How does this sound?

checkpointable_layers (list, optional): A list of `layer.__class__.__name__` values for layers that can be checkpointed. Checkpointable layers may not be checkpointed. Defaults to ``None`` which does no additional filtering.

**Comment by jomayeri** [comment]
Thanks for pointing this out. I have created a PR to update the docs.
