### ISSUE TITLE
[BUG] CUDA OOM when there is enough CPU+GPU RAM (350M model -> 40GB A100, BS=1)

### ISSUE THREAD

**Issue by briancy02** [microsoft/DeepSpeed#2595]
**Describe the bug**
I went from using Colab Pro+ to a DGX server. Before I could train a 350M model with a high batch size but even with A100s on the DGX Im not able to do any training for 350M (even with batch size of 1) due to Cuda OOM issue. I do not understand what may be the cause because A100 40GB is more than enough to train a 350M model. I am wondering if there may be anything wrong with the environment because I ported over the code from colab to this new system and I am getting this erorr....

**To Reproduce**
1. Portion of Training script
`model_engine, optimizer, _, _ = deepspeed.initialize(config=DEEPSPEED_CONFIG, model=model, model_parameters=model_parameters)`
`DEEPSPEED_CONFIG = \
{
    'fp16': {'enabled': True, 'loss_scale': 0, 'loss_scale_window': 1000, 'initial_scale_power': 12, 'hysteresis': 2, 'min_loss_scale': 1},
    'optimizer': {'type': 'AdamW', 'params': {'lr': 1e-05, 'betas': [0.9, 0.999], 'eps': 1e-08, 'weight_decay': 0.0}},
    'scheduler': {'type': 'WarmupLR', 'params': {'warmup_min_lr': 0, 'warmup_max_lr': 1e-05, 'warmup_num_steps': 100}},
    "zero_optimization": {
       "stage": 0,
       "contiguous_gradients": True,
       "offload_optimizer": {'device':'cpu', 'pin_memory':False},
    },
    'train_batch_size': 4,
    'train_micro_batch_size_per_gpu': 1,
    'gradient_accumulation_steps': 4,
    'mp_size': 1,
 }`

2. See error
`  File "/home/briancy2/miniconda3/envs/yield/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 309, in __init__
    self._setup_for_real_optimizer()
  File "/home/briancy2/miniconda3/envs/yield/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 355, in _setup_for_real_optimizer
    self._create_fp32_partitions()
  File "/home/briancy2/miniconda3/envs/yield/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 767, in _create_fp32_partitions
    self.device).clone().float().detach())
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.33 GiB (GPU 0; 39.59 GiB total capacity; 1.41 GiB already allocated; 854.19 MiB free; 1.72 GiB re
served in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management a
nd PYTORCH_CUDA_ALLOC_CONF`

**Expected behavior**
No Cuda OOM error

**ds_report output**

`--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
--------------------------------------------------
No CUDA runtime is found, using CUDA_HOME='/home/briancy2/miniconda3/envs/yield'
DeepSpeed general environment info:
torch install path ............... ['/home/briancy2/miniconda3/envs/yield/lib/python3.10/site-packages/torch']
torch version .................... 1.13.0
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed install path ........... ['/home/briancy2/miniconda3/envs/yield/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.7.6, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.6`

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [1 A100 GPU - DGX server]
 - Python 3.10

**Launcher context**
I was using deepspeed launcher

**Additional context**

**Comment by briancy02** [comment]
I think it was an issue on the GPU cluster Im using not with deepspeed

**Comment by lavaaa7** [comment]
> I think it was an issue on the GPU cluster Im using not with deepspeed

Did you solve the problem? I'm facing similar problem here
