### ISSUE TITLE
[BUG] Model paralization is not working for the new model. 

### ISSUE THREAD

**Issue by PoodleWang** [microsoft/DeepSpeed#2596]
**Describe the bug**
  from collections import defaultdict, Counter
  from concurrent.futures import ThreadPoolExecutor, as_completed
  from typing import List, Union, Iterable, Dict
  
  import numpy as np
  import torch
  from transformers import AutoTokenizer, AutoModelForCausalLM, CodeGenConfig,pipeline
  from transformers.models.codegen.modeling_codegen import CodeGenAttention, CodeGenBlock
  import deepspeed
  import re
  import json
  import copy
  import os
   tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-16B-mono")
   injection_policy={CodeGenBlock: ('mlp.fc_out', "attn.out_proj")}

   local_rank = int(os.getenv('LOCAL_RANK', '0'))
   world_size = int(os.getenv('WORLD_SIZE', '2'))
   generator = pipeline('text-generation', model='Salesforce/codegen-16B-mono',tokenizer=tokenizer,
                        device=local_rank)
    #model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-6B-mono")
    generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.half,
                                           injection_policy=injection_policy)

    # If I use the 'auto', it is the same output
   #runtimeError: CUDA out of memory. Tried to allocate 376.00 MiB (GPU 0; 79.35 GiB total capacity; 66.21 GiB already 
   #allocated; 163.19 MiB free; 74.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting 
   #max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and 
   #PYTORCH_CUDA_ALLOC_CONF
    # generator.model = deepspeed.init_inference(generator.model,
    #                                       mp_size=world_size,
    #                                       dtype=torch.half,
    #                                      replace_method='auto',
    #					   replace_with_kernel_inject=True)
     sample = generator(problems[key]["prompt"], max_length=512, do_sample=True,
                                        temperature=0.8, top_p=0.95,
                                        pad_token_id=tokenizer.eos_token_id, num_return_sequences=100)

   

command:  deepspeed --num_gpus 2 [script.py]
**System info (please complete the following information):**
two gpus A100-80G 

**Docker context**
Deepspeed 0.76

**Output**
RuntimeError: CUDA out of memory. Tried to allocate 434.00 MiB (GPU 0; 79.35 GiB total capacity; 58.11 GiB already allocated; 123.19 MiB free; 74.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2022-12-11 10:18:25,118] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 32127
[2022-12-11 10:18:25,119] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 32128
[2022-12-11 10:18:25,934] [ERROR] [launch.py:324:sigkill_handler] ['/usr/bin/python3', '-u', '/opt/tiger/genius/benchmark/generate.py', '--local_rank=1'] exits with return code = 1

**Comment by molly-smith** [comment]
Hi @PoodleWang, turns out model parallelization is not supported for codegen at this time.
