### ISSUE TITLE
[BUG]AttributeError: module 'deepspeed' has no attribute 'ops'

### ISSUE THREAD

**Issue by SiTu1O** [microsoft/DeepSpeed#2597]
![image](https://user-images.githubusercontent.com/62015400/206899168-b5c8292e-f5d1-4f5e-af4d-f51009a747be.png)
--2022/12/11

**Comment by jeffra** [comment]
Hi @SiTu1O, this should be fixed in 0.7.7. It's not pushed to pypi yet but can you try installing via `pip install git+https://github.com/microsoft/deepspeed.git`?

**Comment by jeffra** [comment]
@SiTu1O, please re-open if you're still seeing this issue.
