### ISSUE TITLE
[BUG] pydantic DeepSpeedConfigModel has no validator for <class:object>

### ISSUE THREAD

**Issue by Lavenderjiang** [microsoft/DeepSpeed#2609]
**Describe the bug**
During ```from deepspeed.inference.config import DtypeEnum```, got error 
```
 File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 456, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 670, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 715, in find_validators
RuntimeError: no validator found for <class 'object'>, see `arbitrary_types_allowed` in Config
```

**To Reproduce**
1. Simple inference script to reproduce ```from deepspeed.inference.config import DtypeEnum```
2. pydantic 1.8.2, deepspeed 0.8.0+384f17b

**Expected behavior**
successful import with no error

**ds_report output**
cannot produce due to the same import error

**System info (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server 7.9 (Maipo)
 - GPU count and types: one machine with 8 A100s, three machines with 8 A100s each
 - Hugging Face Transformers 4.19.2, no accelerate
 - Python version 3.8.13

**Comment by Lavenderjiang** [comment]
There are many errors like this that can be fixed with adding ```arbitrary_types_allowed = True``` for the pydantic baseclass (see this Pydantic [issue](https://github.com/pydantic/pydantic/issues/3320)). However, there are many child class of the base class, and adding this option one by one does not seem like the best solution. Did I have a package version mismatch?

**Comment by molly-smith** [comment]
Hi @Lavenderjiang, try updating pydantic with `pip install pydantic --upgrade`

**Comment by peterbaldridge** [comment]
I've tried updating pydantic and I'm still getting that error. Any help would be appreciated :)
