### ISSUE TITLE
[REQUEST] efficiently deal with frozen weights during training

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#2615]
**Is your feature request related to a problem? Please describe.**

This is a need for HF `accelerate` and `m4` projects.

We have more and more situations where a large part of the model that's being trained is frozen. 

At the moment the only way to emulate frozen weights in deepspeed is to create a param group with `lr=0`, which works but a huge amount of memory is wasted to allocate states that aren't being trained (grads too?) and the compute is wasted too.

**Describe the solution you'd like**

Ideally, if `requires_grad == False` those weights shouldn't be in the optimizer and not allocating any optim state/grad memory.

Thank you!

@tjruwase 

@pacman100 - would you like to add/expand anything to this request?

**Comment by pacman100** [comment]
Current workaround is to create a param_group with all the frozen parameters and set the lr=0, an example is shown below:
```
if getattr(accelerator.state, "deepspeed_plugin", None) is not None:
        optimizer_grouped_parameters = [
            {
                "params": [p for p in model.parameters() if p.requires_grad],
                "lr": lr
            },
            {
                "params": [p for p in model.parameters() if not p.requires_grad],
                "lr": 0
            },
        ]
        
        for param in model.parameters():
            param.requires_grad = True
        optimizer = torch.optim.AdamW(optimizer_grouped_parameters)
```

Below are the screenshots of memory usage (in MB) when using DS Stage 3 (GPU: 65 GB, CPU: 327 GB :exploding_head:) with CPU offloading vs plain PyTorch (GPU: 56 GB, CPU: 3 GB). The model is MT0-XXL (13B params) and is using LoRA for parameter efficient fine-tuning.

`Plain Pytorch`
<img width="1512" alt="Screenshot 2022-12-09 at 4 51 13 PM" src="https://user-images.githubusercontent.com/13534540/208633163-2b775f0a-9c0c-494a-8349-3f2d0b96e185.png">

`DS ZeRO-3 with CPU offloading`
<img width="1510" alt="Screenshot 2022-12-09 at 4 42 15 PM" src="https://user-images.githubusercontent.com/13534540/208633188-08682f13-fbe4-4f18-b88e-9225f0a7ce3e.png">

**Request**:  Efficiently deal with frozen weights during training such that large models could be offloaded on CPUs/sharded across GPUs properly with storage of the optimizer state only for the trainable parameters, e.g., we can see that using plain PyTorch, mt0-xxl (13B params) model takes up 56GB on GPU, now, it would be really helpful if one could do CPU offloading such that training could work on a 16GB or 24GB GPU and rest being offloaded to CPU.

**Comment by tjruwase** [comment]
@pacman100, this is a great demo of the issue. Could you please share the repro steps?

**Comment by tjruwase** [comment]
@stas00, @pacman100 please try out the linked PR.

**Comment by pacman100** [comment]
Hello @tjruwase, 

I tried the PR and it works great! Thanks a lot :smile:, DeepSpeed team rocks:sparkles::rocket:. Now, DeepSpeed ZeRO-3 with CPU offloading works as expected and the GPU memory usage is down from 65GB to 22GB and CPU usage is down from 327GB to 52GB (before PR vs after). For comparison, plain PyTorch takes (GPU: 56 GB, CPU: 3 GB) memory, so memory savings = 2.54X (before/after)  on GPU and now would fit on consumer GPUs with 24GB GPU memory.

![Screenshot 2022-12-28 at 12 23 11 PM](https://user-images.githubusercontent.com/13534540/209774725-ce3e5f1f-0ec6-4d4a-aef6-ebebc7fd2312.png)

**Comment by yuvalkirstain** [comment]
@stas00 @pacman100 is this already integrated into accelerate? 
If not, can somehow use this feature while using accelerate (e.g. pip installing the PR)?

**Comment by pacman100** [comment]
Hello @yuvalkirstain, yes, you can just get this working by installing the corresponding PR. 

Hello @stas00, I believe the PR would be really beneficial as it doesn't require users to make all those changes similar to the plain PyTorch case making their lives simpler.

**Comment by stas00** [comment]
Just to clarify I'm not arguing against merging the DS PR, I was just thinking that perhaps HF Trainer and Accelerate should do that in the first place before creating the optimizer.

Is there any reason why one would want frozen params in the optimizer?

**Comment by tjruwase** [comment]
We plan to merge this PR as we have had internal requests as well.

**Comment by mayank31398** [comment]
Awesome catch. However, I was able to get around this behaviour by having a separate deepspeed.initialize() on bloom and the prompt vocab for prompt tuning. But this had made code handling a bit harder.

Thanks a lot for this one :)
