### ISSUE TITLE
[BUG] Using AVX512 for CPU-Offload

### ISSUE THREAD

**Issue by taehyunzzz** [microsoft/DeepSpeed#2618]
Hi, I have a question on AVX512 support for CPU-offload.
My server configuration shows that it is capable of using AVX512, but I found that CPUAdam uses AVX2, instead.
Training message explicitly prints out CPUAdam uses AVX2 instead of AVX512 from [this code](https://github.com/microsoft/DeepSpeed/blob/7e2103f8e2c9a4e1be6c3aaa7929f765eb5dd7a4/csrc/adam/cpu_adam.cpp#L150).

Looked into where \_\_AVX512\_\_ and \_\_AVX256\_\_ are defined and found [this](https://github.com/microsoft/DeepSpeed/blob/7e2103f8e2c9a4e1be6c3aaa7929f765eb5dd7a4/op_builder/builder.py#L404).

In the above code, "cpu_info['flags']" looks for 'avx512' but not for 'avx512f', 'avx512dq', 'avx512cd', 'avx512ow', or 'avx512vl'. 
I do not know what these different types of avx512 are, but am curious if they cannot be used for CPU-Offload with AVX512 support.

My machine shows :
`/proc/cpuinfo:641:flags         : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities`
for `grep avx /proc/cpuinfo`, which includes different types of avx512 ('f', 'dq', and so on).
My feeling says that the machine has some sort of AVX512 support, but it just does not have the \_\_AVX512\_\_ flag.

I was wondering if builder.py needs modification.
Thanks

**Comment by cmikeh2** [comment]
Hi @taehyunzzz ,

Thanks for reporting this. The `avx512f` flag should encapsulate all the instructions that we are using, so your CPU should have support for the optimizer. I have created a PR (https://github.com/microsoft/DeepSpeed/pull/2621) to address this. If you could try this and validate (I don't currently have any AVX512F CPUs available) that would be great! You may need to clean your build cache if you've already built the ops. The location for this would be printed any time the a JIT builder is triggered. Thanks!

**Comment by taehyunzzz** [comment]
Cool! I will try it out and come back with results

**Comment by taehyunzzz** [comment]
Unfortunately, build shows the following error:
![image](https://user-images.githubusercontent.com/33646149/208214007-a1774b0a-4416-4027-ac7f-eac60064e3f4.png)

**Comment by taehyunzzz** [comment]
Trying to work around this error by casting _mm256_loadu_ps(x) to (__m256i) in [here](https://github.com/microsoft/DeepSpeed/blob/aeda7f9f8c5bdaee318e7b6094279484d41c659c/csrc/includes/simd.h#L24)

so 
`
_mm512_cvtph_ps(_m256_loadu_ps(x))
` 
becomes
`
_mm512_cvtph_ps((__m256i)_m256_loadu_ps(x))
`

**Comment by cmikeh2** [comment]
Just pushed a commit on the PR with a fix along those lines you suggested. Please feel free to try!

**Comment by taehyunzzz** [comment]
![image](https://user-images.githubusercontent.com/33646149/208222106-46065fd9-7da6-4928-a1dd-e92feca9defd.png)
Works like a charm! Thanks!
