### ISSUE TITLE
AssertionError: "nvme_path" in DeepSpeed Config cannot be None if remote device is nvme

### ISSUE THREAD

**Issue by asifehmad** [microsoft/DeepSpeed#2624]
Hi, 
I am using _DataCrunch.io_ remote server with 1xA100 GPU to train a model using zero stage 3. The training works well when I offload optimizers and parameters to CPUs, and I face this error ; `AssertionError: "nvme_path" in DeepSpeed Config cannot be None if remote device is nvme` when I offload the parameters to nvme. The error refers to this line of the script I am using: https://github.com/asifehmad/clm_modeltuning/blob/main/tuned3.py#L130

The whole error is:

Traceback (most recent call last):

  File "tuned3.py", line 339, in main
    tokenizer, model = load_model_and_tokenizer(cfg)
  File "tuned3.py", line 130, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 463, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 2271, in from_pretrained
    init_contexts = [deepspeed.zero.Init(config_dict_or_path=deepspeed_config())] + init_contexts
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 682, in __init__
    self._validate_remote_device(remote_device, _ds_config)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 731, in _validate_remote_device
    assert ds_config.zero_config.offload_param.nvme_path is not None, \
AssertionError: "nvme_path" in DeepSpeed Config cannot be None if remote device is nvme

**The _accelerate env_ I am using is:**

- `Accelerate` version: 0.15.0
- Platform: Linux-5.4.0-124-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: fp16
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: None
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 4, 'gradient_clipping': 1.0, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'nvme', 'zero3_init_flag': True, 'zero3_save_16bit_model': True, 'zero_stage': 3}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None

Any help in this regard will be highly appreciated.

Thanks,

**Comment by asifehmad** [comment]
> Can you try setting the `nvme_path` field in the `offload_param` section of the ds_config.

Hi, thanks for responding. I am generating the `ds_config` using `accelerate config` command, and there is no such option to set the `nvme_path`.

**Comment by jomayeri** [comment]
You can add a DeepSpeed config file in accelerate as shown [here](https://huggingface.co/docs/accelerate/usage_guides/deepspeed#deepspeed-config-file). In that configuration json it will be possible to set the `nvme_path`.

**Comment by jomayeri** [comment]
Closing the issue for now. Feel free to reopen if you have any more questions.
