### ISSUE TITLE
[BUG] Engine Initialization Fails Without Message

### ISSUE THREAD

**Issue by dogacancolak** [microsoft/DeepSpeed#2632]
**Describe the bug**
Trying to `deepspeed.initialize` a basic model, but it fails without any warnings or messages.  This is the only output I'm getting related to the error:
```
[2022-12-20 21:34:12,476] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 6920
[2022-12-20 21:34:12,477] [ERROR] [launch.py:324:sigkill_handler] ['/usr/local/bin/python', '-u', 'client_script.py', '--local_rank=0', '--deepspeed_config=ds_config.json'] exits with return code = -7
```

I used a debugger to spot where the error occurs.  From `initialize`, it goes to `_configure_distributed_model()` ([this line in DeepSpeedEngine](https://github.com/microsoft/DeepSpeed/blob/3b3ba3c2566a66d651393028af6c923b32eeffaa/deepspeed/runtime/engine.py#L287)). From there, it eventually goes to [`_broadcast_model`](https://github.com/microsoft/DeepSpeed/blob/3b3ba3c2566a66d651393028af6c923b32eeffaa/deepspeed/runtime/engine.py#L1096). Finally, it calls [`dist.broadcast`](https://github.com/microsoft/DeepSpeed/blob/3b3ba3c2566a66d651393028af6c923b32eeffaa/deepspeed/runtime/engine.py#L1007) and that's where it fails. NOTE: My deepspeed version (0.7.7) does not exactly match the code in the links. 

**To Reproduce**
This is my `client_script.py`:
```python
import argparse
import deepspeed
import torch.nn as nn

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(3, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 1)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))

def main():
    parser = argparse.ArgumentParser(description='Demo')
    parser.add_argument('--local_rank', type=int)
    parser = deepspeed.add_config_arguments(parser)
    args = parser.parse_args()

    model_engine, optimizer, _, _ = deepspeed.initialize(args=args, model=ToyModel())

if __name__ == '__main__':
    main()
```

`ds_config.json`:
```json
{
  "train_micro_batch_size_per_gpu": 1,
  "steps_per_print": 1,
  "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 0.00015
        }
    }
}
```

Running with this command: `deepspeed --num_gpus=1 client_script.py --deepspeed_config=ds_config.json`.

I'm not using any hostfiles, running single node.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.9/site-packages/torch']
torch version .................... 1.13.0+cu117
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.4
deepspeed install path ........... ['/usr/local/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.7.7, unknown, unknown
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
```

**System info (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - 1 machine, running single GPU.
 - Python 3.9.13
- CUDA 11.4

**Comment by jeffra** [comment]
I might try two different things:

1. The `broadcast` here is leveraging pytorch + NCCL. You can try another NCCL test like this: https://gist.github.com/jeffra/b5e80466b4c86be00ea3b6f130fb7a36 that uses torch+nccl together. If that doesn't work then I would then try the nvidia nccl tests that do not use torch: https://github.com/nvidia/nccl-tests
2. I notice your `nvcc` version is 11.4 but torch was built with cuda 11.7. Ideally you want these versions aligned or at least have a newer version of nvcc than torch was built with.

**Comment by dogacancolak** [comment]
1. The first linked code failed in a similar way (this time return code -9). When I tried  `NCCL_SHM_DISABLE=1 ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4` the Nvidia NCCL test passed. Does this imply I have a problem with torch?
2. I'm getting this warning when I run deepspeed, so I assumed it was fine. `Installed CUDA version 11.4 does not match the version torch was compiled with 11.7 but since the APIs are compatible, accepting this combination`. I'm using my company's prebuilt images but if you really think the problem is stemming from here I can try aligning the versions as well.

**Comment by dogacancolak** [comment]
Update: I downgraded my torch to a version built with cuda 11.3 (11.4 wasn't available for torch). The updated ds_report:
```
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.9/site-packages/torch']
torch version .................... 1.12.1+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.4
deepspeed install path ........... ['/usr/local/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.7.7, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.3
```
I tried running your script again. It failed in the same way

**Comment by dogacancolak** [comment]
More updates: Even though your script didn't work, I realized my script now works (after downgrading torch) for single node.

However, when I include a hostfile, and I run with two nodes, I get this (`NCCL_DEBUG=INFO`):
```
ddp-0: ddp-0:8381:8381 [0] NCCL INFO Bootstrap : Using eth0:10.106.71.59<0>
ddp-0: ddp-0:8381:8381 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ddp-0: ddp-0:8381:8381 [0] NCCL INFO NET/IB : No device found.
ddp-0: ddp-0:8381:8381 [0] NCCL INFO NET/Socket : Using [0]eth0:10.106.71.59<0>
ddp-0: ddp-0:8381:8381 [0] NCCL INFO Using network Socket
ddp-0: NCCL version 2.10.3+cuda11.3
ddp-0: ddp-0:8381:8438 [0] bootstrap.cc:75 NCCL WARN Message truncated : received 988 bytes instead of 984
ddp-0: ddp-0:8381:8438 [0] NCCL INFO bootstrap.cc:413 -> 3
ddp-0: ddp-0:8381:8438 [0] NCCL INFO init.cc:672 -> 3
ddp-0: ddp-0:8381:8438 [0] NCCL INFO init.cc:904 -> 3
ddp-0: ddp-0:8381:8438 [0] NCCL INFO group.cc:72 -> 3 [Async thread]
ddp-0: Traceback (most recent call last):
ddp-0:   File "//scripts/basic_deepspeed.py", line 76, in <module>
ddp-0:     train(cli_args)
ddp-0:   File "//scripts/basic_deepspeed.py", line 17, in train
ddp-0:     model_engine, optimizer, _, _ = deepspeed.initialize(args=args,
ddp-0:   File "/usr/local/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
ddp-0:     engine = DeepSpeedEngine(args=args,
ddp-0:   File "/usr/local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 290, in __init__
ddp-0:     self._configure_distributed_model(model)
ddp-0:   File "/usr/local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1106, in _configure_distributed_model
ddp-0:     self._broadcast_model()
ddp-0:   File "/usr/local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1021, in _broadcast_model
ddp-0:     dist.broadcast(p,
ddp-0:   File "/usr/local/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 126, in log_wrapper
ddp-0:     return func(*args, **kwargs)
ddp-0:   File "/usr/local/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 231, in broadcast
ddp-0:     return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
ddp-0:   File "/usr/local/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 70, in broadcast
ddp-0:     return torch.distributed.broadcast(tensor=tensor,
ddp-0:   File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1197, in broadcast
ddp-0:     work = group.broadcast([tensor], opts)
ddp-0: RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, internal error, NCCL version 2.10.3
ddp-0: ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption

**Comment by dogacancolak** [comment]
Hello again @jeffra. I made sure that the [NCCL tests work for any number of nodes and GPUs](https://github.com/NVIDIA/nccl-tests/issues/125) using commands such as:
`mpirun -x NCCL_SHM_DISABLE=1 -x NCCL_DEBUG=INFO -H ddp-0,ddp-1 -np 2 ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4`.

Now I'm back to DeepSpeed. I'm running your code with `deepspeed --num_gpus <N> all_reduce_bench_v2.py`, but it fails with any number of GPUs (even 1). Here's the output when number of gpus is 2. 
```
/ > deepspeed --num_gpus=2 scripts/all_reduce_bench_v2.py
[2023-01-03 18:27:06,026] [WARNING] [runner.py:179:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-01-03 18:27:06,136] [INFO] [runner.py:508:main] cmd = /usr/local/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 scripts/all_reduce_bench_v2.py
[2023-01-03 18:27:07,796] [INFO] [launch.py:135:main] 0 NCCL_DEBUG=INFO
[2023-01-03 18:27:07,796] [INFO] [launch.py:135:main] 0 NCCL_SHM_DISABLE=1
[2023-01-03 18:27:07,796] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-01-03 18:27:07,796] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-01-03 18:27:07,796] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-01-03 18:27:07,796] [INFO] [launch.py:162:main] dist_world_size=2
[2023-01-03 18:27:07,796] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2023-01-03 18:27:10,028] [INFO] [comm.py:654:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[W socket.cpp:401] [c10d] The server socket cannot be initialized on [::]:29500 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
0 data size: 6.0 GB
[2023-01-03 18:27:18,819] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 1691
[2023-01-03 18:27:18,820] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 1692
[2023-01-03 18:27:18,953] [ERROR] [launch.py:324:sigkill_handler] ['/usr/local/bin/python', '-u', 'scripts/all_reduce_bench_v2.py', '--local_rank=1'] exits with return code = -9
```
What might be the reason?

**Comment by jeffra** [comment]
I do see for some reason it's trying to use an IPv6 address as the `master_addr`. Can you try passing `--master_addr 127.0.0.1` into the launch with only 1 node?

Also, I notice in your mpirun version you are setting `NCCL_SHM_DISABLE=1`, is this required for your environment? If so, you'll want to pass it in the deepspeed version as well, such as: `NCCL_SHM_DISABLE=1 deepspeed --num_gpus <N> all_reduce_bench_v2.py`

The NCCL tests you are running are not using torch at all, so there is also a difference between the runs. You can try using the torch.distributed launcher for 2 gpus but i'd suspect you'll see the same NCCL issue for some reason.

**Comment by dogacancolak** [comment]
Some digging around, and the line that fails in `all_reduce_bench_v2.py` is `mat = torch.rand(N, M, dtype=torch.float32).cuda(local_rank)`

**Comment by dogacancolak** [comment]
Turns out the problem is with our machine memory limits. Running `dmesg`, I saw `Memory cgroup out of memory`. When I increased the memory limit the problem got fixed. If there's a way to print a helpful error message, it could be helpful for others in the future.

Thank you @jeffra for offering insight!

**Comment by stas00** [comment]
the cgroups oom killer just culls the process so the process has no way of telling the user anything.

so the symptom is "Killed" in the log - sometimes the system adds an additional message, but most of the systems I've run into it's just a single word "Killed".

**Comment by zaoshuizaoqishentihao** [comment]
NCCL backend in DeepSpeed not yet implemented，deepspeed use torch.distribute，采用的是torch.TorchBackend，在TorchBackend.broadcast的torch.distributed.broadcast时出问题，需要async_op=True，我这安装async_io，ds_report发现async_io OK，就解决问题了
