### ISSUE TITLE
[BUG] RuntimeError: still have inflight params while fine-tuning Wav2Vec2

### ISSUE THREAD

**Issue by Ar4ikov** [microsoft/DeepSpeed#2651]
**Describe the bug**
Hello!

I'd trying to fine-tune a Transformers Wav2Vec2Model for audio classification task, so I started with implementing a new class with `pytorch_lightning`.

https://gist.github.com/Ar4ikov/d3ac666144e176225283c06c2754a3f5#file-wav2vec2_1b_pl_dp-py-L117

There are two weird things after the train started.

1. If using >1 gpus, train freezes for ever. Nothing is changing.
2. If using 1 gpu, train starting, but suddenly stops with RuntimeError at first training step.

Traceback: https://gist.github.com/Ar4ikov/ee7f4daf48ee1b30f7b72b78c0d76220

I don't realize at end what is *inflight* params and how that happens with DP

I've found 3 different issues in a branch of https://github.com/microsoft/DeepSpeed/issues?q=is%3Aissue+inflight+is%3Aclosed
but all of them consider the problem with saving fp16 model stage (not training stage).

**To Reproduce**
1. Go to the first file in issue (gist link)
2. Run it with python filename.py
3. Wait...
4. See error on training stage.

**Expected behavior**
The model needs to be in training stage.

**ds_report output**
<img width="584" alt="Снимок экрана 2022-12-27 в 01 37 07" src="https://user-images.githubusercontent.com/20085792/209586819-637862e1-3273-4e38-9fea-9a314ec3d32a.png">

**System info (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - GPUS:
   - 1 node with 2x RTX 3090 
 - 500mbit connection, R9 5900X, 128 GB DDR4 
 - Python 3.10.8
 - Deepspeed version: 0.7.7
 - Pytorch Lightning version: 1.8.6

**Launch context**
Using `pytorch_lightning` that has `deepspeed` strategy integrated in itself. Launching lightning Trainer with DeepSpeedStrategy

**Comment by GuanhuaWang** [comment]
Hi @Ar4ikov , thx for raising this issue, could you also share the details of how to launch the job (either using lightning or deepspeed)?

**Comment by Ar4ikov** [comment]
Well, for this code sample:

> https://gist.github.com/Ar4ikov/d3ac666144e176225283c06c2754a3f5#file-wav2vec2_1b_pl_dp-py-L117

I'd just run it with `$CONDA_HOME wav2vec2_1b_pl_dp.py`, nothing else, because my code sample does not provide any case of `accelerate` usage. 
What if I would run it with `accelerate`? So yeah, that's the question, because I've already attempted to do that. But model hadn't trained as well (static loss and acc for 4 or 5 epochs). And I really don't know how to train this with `accelerate` correctly.

**Comment by GuanhuaWang** [comment]
Hi @Ar4ikov , thx for provding additional cmd info. I can reproduce it now. It seems to be an incapability issue between pytorch_lightning and deepspeed. 

One quick fix for now is if you change [line282](https://gist.github.com/Ar4ikov/d3ac666144e176225283c06c2754a3f5#file-wav2vec2_1b_pl_dp-py-L282) `stage=3` to `stage=2`, it seems work on my side. Let me know if it also works on yours.

**Comment by Ar4ikov** [comment]
Probably should start today. I will post here the results 😄

**Comment by Ar4ikov** [comment]
Okay, let's make some conclusions:

Tried to run this script with ZeRO Stage 2 instead of 3
* With ≥2 devices training does not works and still doesn't run, processes becomes dead.
* With 1 GPU I realize, that 24GB of VRAM looks sus (screenshot). 
<img width="487" alt="Снимок экрана 2023-01-31 в 15 35 43" src="https://user-images.githubusercontent.com/20085792/215761472-59c5a686-6c32-4041-9a78-385e2b8df410.png">

**Comment by GuanhuaWang** [comment]
Hi @Ar4ikov , thx for the update. 

I tried both 1,2,4 gpus, it seems work on my side. The GPU I use is v100, each has 32GB ram.
