### ISSUE TITLE
[REQUEST] Intel GPU Support?

### ISSUE THREAD

**Issue by stanleyshly** [microsoft/DeepSpeed#2656]
Currently, both Nvidia and AMD GPUs are supported through CUDA and ROCm. How that Intel GPUs are supported in Pytorch as well: [article link](https://www.intel.com/content/www/us/en/developer/articles/technical/introducing-intel-extension-for-pytorch-for-gpus.html#gs.m5rbfq), are there any plans to add DeepSpeed support to Intel GPUs as well?

**Comment by tjruwase** [comment]
@stanleyshly, thanks for your question. Intel GPU support is in progress #2221.

**Comment by tjruwase** [comment]
Closing after linking to related PR. Please re-open as appropriate.
