### ISSUE TITLE
Issue when installing and running

### ISSUE THREAD

**Issue by Shikamaru5** [microsoft/DeepSpeed#2659]
So as far as I can tell I've installed deepspeed, however I'm trying to use accelerate to run this and it seems it's trying to call:

      import deepspeed.ops.transformer as transformer_inference

 Which then brings up the error:

    AttributeError: module 'deepspeed' has no attribute 'ops'

I found an issue relating to this, the exact title was the attribute error, and it was closed because a response was given to try and use the line pip install git+https://github.com/microsoft/deepspeed.git
When I ran that I got this:

      line 41, in installed_cuda_version                                                                         
            assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"                                                                             
        AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)

Idk if they are similar issues but whatever it is I really don't understand what the issue is. I'm trying to use wsl2 to run this and maybe that's the problem? Any help would really be appreciated.

**Comment by hivaze** [comment]
`CUDA_HOME` is your OS environment variable, you need to set it with path to your CUDA installation (check `/usr/local/cuda/` folder) and in my experience WSL is always bad choice for CUDA related stuff...
