### ISSUE TITLE
[BUG]embedding is not splited while inference using gpt2

### ISSUE THREAD

**Issue by katitizhou** [microsoft/DeepSpeed#2680]
**Describe the bug**
deepspeed --num_gpus 2 inference-test.py --name gpt2
I modify the inference-test.py  cause i  do not want to use the .cu files. It seems that GPT2 embedding is not splited into two gpus cause i got an error "RuntimeError: shape '[1, 7, 6, 64]' is invalid for input of size 5376".  How to set the right  injection_policy to split wte  and wpe for GPT2? 
![image](https://user-images.githubusercontent.com/122268336/211286703-24e1fcce-b7b2-47a3-8f11-5db0fa0f99d2.png)

![image](https://user-images.githubusercontent.com/122268336/211285124-2463ed02-94a2-4269-89cc-94bcab7e825d.png)

`if args.ds_inference:
    pipe.model = deepspeed.init_inference(pipe.model,
                                    dtype=data_type,
                                    mp_size=world_size,
                                    # replace_with_kernel_inject=True,
                                    replace_with_kernel_inject=False,
                                    injection_policy={GPT2Block:('attention.out_proj','mlp.c_proj')},
                                    max_out_tokens=args.max_tokens,
                                    **ds_kwargs
                                    )`

**To Reproduce**
modify inference-test.py:
`if args.ds_inference:
    pipe.model = deepspeed.init_inference(pipe.model,
                                    dtype=data_type,
                                    mp_size=world_size,
                                    # replace_with_kernel_inject=True,
                                    replace_with_kernel_inject=False,
                                    injection_policy={GPT2Block:('attention.out_proj','mlp.c_proj')},
                                    max_out_tokens=args.max_tokens,
                                    **ds_kwargs
                                    )`

run :
deepspeed --num_gpus 2 inference-test.py --name gpt2
**Expected behavior**
gpt2 2 tp can run

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**
![image](https://user-images.githubusercontent.com/122268336/211285987-ce0a211c-09f3-467f-a3a7-7b06c8c2d968.png)

**System info (please complete the following information):**
transformers              4.21.2  
deepspeed                 0.7.7

**Comment by katitizhou** [comment]
What is the right way to set  injection_policy to split wte and wpe for GPT2?  I found no relevant examples for this question

**Comment by molly-smith** [comment]
Hi @katitizhou, GPT2 is not supported for tensor parallelism without kernel injection. You can split gpt2 across multiple GPUs by setting kernel injection to True and removing injection policy.
