### ISSUE TITLE
GPTJ DeepSpeed Inference Crashes After A Number Of Runs[BUG]

### ISSUE THREAD

**Issue by mallorbc** [microsoft/DeepSpeed#2696]
**Describe the bug**
With the current version of DeepSpeed inference, it works great for the first couple of runs, is 2-3x faster than vanilla PyTorch and gives good results.

However, after a couple of dozens of runs, the model will error out and require a reload in order to work again.

Error messages that one receives are like the following:

```Floating point exception (core dumped)```
```OverflowError: out of range integral type conversion attempted```

The behavior(when it happens and how often) is similar to DeepSpeed-MII, which makes sense since it uses DeepSpeed.

**To Reproduce**
I have a repo with a DockerFile and scripts the can recreate the bug.  See the repo [here](https://github.com/mallorbc/Finetune_GPTNEO_GPTJ6B)
1. Build and run the docker image
2. Navigate to ```/workspace/inference/benchmark```
3. Run ```python benchmark_deepspeed.py```
4. After a certain number of runs the model will crash

**Expected behavior**
The model should be faster(which it is) and give good results(which it does), but it shouldn't crash after N runs.
**ds_report output**
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
sparse_attn ............ [YES] ...... [OKAY]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
async_io ............... [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
quantizer .............. [YES] ...... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
spatial_inference ...... [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch']
torch version .................... 1.13.1+cu117
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed install path ........... ['/usr/local/lib/python3.8/dist-packages/deepspeed']
deepspeed info ................... 0.7.7+2076bf23, 2076bf23, HEAD
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7

**System info (please complete the following information):**
 - Ubuntu 20.04
 - One A100 80GB

Package                  Version
------------------------ --------------
accelerate               0.15.0
aiohttp                  3.8.3
aiosignal                1.3.1
appdirs                  1.4.4
async-timeout            4.0.2
asyncio                  3.4.3
attrs                    22.2.0
certifi                  2022.12.7
charset-normalizer       2.1.1
click                    8.1.3
datasets                 2.8.0
deepspeed                0.7.7+2076bf23
deepspeed-mii            0.0.5+487aff1
dill                     0.3.6
docker-pycreds           0.4.0
filelock                 3.9.0
frozenlist               1.3.3
fsspec                   2022.11.0
gitdb                    4.0.10
GitPython                3.1.30
grpcio                   1.51.1
grpcio-tools             1.51.1
hjson                    3.1.0
huggingface-hub          0.11.1
idna                     3.4
multidict                6.0.4
multiprocess             0.70.14
ninja                    1.11.1
numpy                    1.24.1
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.0
pandas                   1.5.2
pathtools                0.1.2
Pillow                   9.4.0
pip                      20.0.2
protobuf                 4.21.12
psutil                   5.9.4
py-cpuinfo               9.0.0
pyarrow                  10.0.1
pydantic                 1.10.4
python-dateutil          2.8.2
pytz                     2022.7
PyYAML                   6.0
regex                    2022.10.31
requests                 2.28.1
responses                0.18.0
sentry-sdk               1.12.1
setproctitle             1.3.2
setuptools               45.2.0
six                      1.16.0
smmap                    5.0.0
tokenizers               0.13.2
torch                    1.13.1
torchaudio               0.13.1
torchvision              0.14.1
tqdm                     4.64.1
transformers             4.25.1
triton                   1.0.0
typing-extensions        4.4.0
urllib3                  1.26.14
wandb                    0.13.8
wheel                    0.34.2
xxhash                   3.2.0
yarl                     1.8.2

**Docker context**
See the DockerFile in the repo I shared

**Additional context**
Potentially related issues:
https://github.com/microsoft/DeepSpeed-MII/issues/130
https://github.com/microsoft/DeepSpeed/issues/1925

Potetential PR:
https://github.com/microsoft/DeepSpeed/pull/1930

More info:
I have built DeepSpeed from that PR, master, 0.7.7 and #2554 .  None of those fixed the issue.

**Comment by mallorbc** [comment]
The original programs I gave for reproducing originally gave an empty string for input(which should be valid).  However, after changing it to have a nonempty string the behavior seems to be what I expected.  I now believe this issue could be thought of as an extension to this one https://github.com/microsoft/DeepSpeed/issues/2644

**Comment by mrwyattii** [comment]
@mallorbc have you tried with #2669 ? I just ran your code with that branch and I'm not seeing this error pop up. Please let me know if you have a chance to try it. Thanks

**Comment by mrwyattii** [comment]
Closing, please reopen if the PR does not address your problem.
