### ISSUE TITLE
[Question] What does inference_cuda_module.pad_transform_fp16 do ?

### ISSUE THREAD

**Issue by tchaton** [microsoft/DeepSpeed#2710]
Hey there,

I am going through the DeepSpeedDiffusersAttentionFunction and I confused by the following operation ( https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/ops/transformer/inference/diffusers_attention.py#L100
):

```python
query, key, value = inference_cuda_module.pad_transform_fp16(query, key, value, config.heads, do_flash_attn)
```

Would it be possible to have the pure PyTorch counterpart ?

**Comment by tchaton** [comment]
I am also getting this error when trying to re-use the module with https://github.com/HazyResearch/flash-attention:

```
inference_cuda_module.pad_transform_fp16(query.contiguous(), key.contiguous(), value.contiguous(), self.heads, do_flash_attn)
*** RuntimeError: The specified pointer resides on host memory and is not registered with any CUDA device
```

**Comment by cmikeh2** [comment]
Hi @tchaton,

To address your two questions individually:

> Would it be possible to have the pure PyTorch counterpart ?

The primary purpose of this function is performing the traditional head transpose for attention:
``` python
x = x.view((batch, sequence, heads, head_size))
x_out = x.permute(0,2,1,3)
```
The function also will optionally pad in the `sequence` or `head_size` dimension based on the conditional `do_flash_attn` to match some restrictions that the Triton flash attention implementation in DeepSpeed has. It is unlikely that the HazyResearch flash attention implementation has the same restrictions, so I would tend to believe that any padding needed there (if at all) would be different. 

> I am also getting this error when trying to re-use the module with https://github.com/HazyResearch/flash-attention:

This function expects to be called as part of a sequence of DeepSpeed kernels. This means that it is pulling its output pointer from an allocation of scratch memory space that is only called when the DeepSpeed `allocate_workspace` method is. If that function hasn't been called it will pulling in an offset from a `nullptr` triggering the unregistered pointer error.

**Comment by cmikeh2** [comment]
Please re-open if you have any further questions on this!
