### ISSUE TITLE
[QUESTION] Learning about DeepSpeed configuration options?

### ISSUE THREAD

**Issue by vittorio-perera** [microsoft/DeepSpeed#2720]
Hi I was wondering if there are any resources to learn more about all the configuration options DeepSpeed offers. I am aware of [this](https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training) page but it "only" describe each parameter. I am trying to learn how changing these parameters will affect the training and how to set them optimally based on the model and HW I am using. (For instance from [this issue](https://github.com/microsoft/DeepSpeed/issues/467) I learned I might want to reduce `allgather_bucket_size` and `reduce_bucket_size` for "smaller" models). Thanks 😄!

**Comment by tjruwase** [comment]
@vittorio-perera, perhaps the DeepSpeed autotuner could help: 
https://github.com/microsoft/DeepSpeedExamples/tree/master/autotuning

**Comment by vittorio-perera** [comment]
@tjruwase thanks for the reply. I spent some time looking at autotuning but it only partially answer my question. While it can help me find optimal values it doesn't provide me any better understanding.  I also noticed that all the example provided run on HuggingFace scripts (e.g., `run_clm.py` or `run_clue.py`). Are the any example of using the tool with "native" DeepSpeed code (i.e., code w/ `deepspeed.intialize()`)? Actually, any script showing a full example of training with DeepSpeed would be super helpful! Thanks 😄

**Comment by tjruwase** [comment]
We have end-to-end examples in our [DeepSpeedExamples](https://github.com/microsoft/DeepSpeedExamples) repo. Some good starter examples are: 
1. Training:  [HelloDeepSpeed](https://github.com/microsoft/DeepSpeedExamples/tree/master/HelloDeepSpeed), [cifar](https://github.com/microsoft/DeepSpeedExamples/tree/master/cifar), and [bing_bert](https://github.com/microsoft/DeepSpeedExamples/tree/master/bing_bert)
2. FineTuning: [BingBertGlue](https://github.com/microsoft/DeepSpeedExamples/tree/master/BingBertGlue) and [BingBertSquad](https://github.com/microsoft/DeepSpeedExamples/tree/master/BingBertSquad)
3. Inference: [HF](https://github.com/microsoft/DeepSpeedExamples/tree/master/inference/huggingface)

More advanced examples include [Megatron-DeepSpeed](https://github.com/microsoft/Megatron-DeepSpeed) and [BigScience](https://github.com/bigscience-workshop/Megatron-DeepSpeed). 

You might also find our [tutorials page](https://www.deepspeed.ai/tutorials/), which references some of the above examples, a useful resource.

**Comment by vittorio-perera** [comment]
Thanks @tjruwase ! I'll close the issue as it will take me some time to go through all this
