### ISSUE TITLE
[BUG] Loading MoE Checkpint with load_optimizer_states=False should tolerate missing optim_state files

### ISSUE THREAD

**Issue by clumsy** [microsoft/DeepSpeed#2737]
**Describe the bug**
Even though not loaded into optimizer state dict for MoE model with `load_optimizer_states=False` the current code attempts to load the files at https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/engine.py#L2843, but they could be (intentionally or not) missing.
The only workaround right now is to use `load_module_only` which is not ideal if we want to load LR scheduler states for example.

**To Reproduce**
1. Delete `optim_state` files from the checkpoint
2. Try loading DeepSpeed checkpoint with `load_optimizer_states=False`
3. Observe `FileNotFoundError`:
```
Traceback (most recent call last):
--
...
_, checkpoint_state_dict = model.load_checkpoint(
File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 2415, in load_checkpoint
load_path, client_states = self._load_checkpoint(load_dir,
File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 2489, in _load_checkpoint
optim_checkpoint = torch.load(optim_load_path,
File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 594, in load
with _open_file_like(f, 'rb') as opened_file:
File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
return _open_file(name_or_buffer, mode)
File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '<REDACTED>/expp_rank_0_mp_rank_00_optim_states.pt'

```

**Expected behavior**
Loading checkpoints loads all specified state dicts, but for optimizer - it's initialized from model weights. `client_state` should reflect this.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  using untested triton version (1.0.1), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib64/python3.7/site-packages/torch']
torch version .................... 1.12.1+cu113
deepspeed install path ........... ['/home/$USER/DeepSpeed/deepspeed']
deepspeed info ................... 0.8.1+8df50a26, 8df50a26, master
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.0
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.3
```

**Screenshots**
N/A

**System info (please complete the following information):**
 - OS: `Amazon Linux 2 4.14.200-155.322.amzn2.x86_64`
 - GPU count and types `8 x A100`
 - Interconnects (if applicable) `N/A`
 - Python version: `3.8.10`
 - Any other relevant info about your setup

**Launcher context**
DeepSpeed launcher / pytest

**Docker context**
`N/A`

**Additional context**
`N/A`

**Comment by clumsy** [comment]
Ok, this could be a misunderstanding on my part. Maybe @tjruwase you can help me understand.

I thought `load_optimizer_states` effectively does not load/apply `optim_states.pt` files (especially for ZeRO 1-2), e.g. if the user wants to try a different world_size.

But as far as I can see it is only controlling loading optimizer `state_dict`, but other content from `optim_states.pt` are still loaded, isn't it? E.g. `dynamic_loss_scale` etc.

If that's the case I'm not sure what are the recommendations for loading a checkpoint with different world_size. Is the user expected to create dummy `optim_states.pt` for all the new ranks even if what I want is to, say, load LR schedules in addition to all model parameters.

**Comment by bestbzw** [comment]
I also meet this problem.
Besides, if I increases some nodes during fine-tuning, it will also raise an FileNotFoundError.

**Comment by clumsy** [comment]
@tjruwase could you please correct my understanding about ZeRO3 checkpoint format? Asking because my fix works for ZeRO 0-2, but in ZeRO3 it seems like we colocate optimizer states with `param_groups` (probably because they are sharded the same way, while model states files are actually empty) and thus we can't really not have optimizer states files when loading a ZeRO3 checkpoint, right?

**Comment by tjruwase** [comment]
@clumsy, your observation and analysis are correct. We made the decision not to checkpoint the fp16 parameters in the model states files. Instead, we assumed that during loading, fp16 parameters would be initialized using the fp32 parameters in the optimizer state files. This created a difference the model state files content of zero 3 vs other stages. However, it seems this decision is causing quite a number of issues lately. We are actively rethinking this design decision so that model state files for zero 3 should include the appropriate fp16 parameter partitions instead of zero sized tensors.

**Comment by clumsy** [comment]
I see, thanks @tjruwase. In this case I'll slightly modify my contribution here. The only thing I'll make sure does not happen is that we avoid loading MoE optimizer `state_dict`s from `_optim_states.pt` files when `load_optimizer_states=False` (it's currently unconditional if `load_modules_only=False`). This should speed up the process of loading the checkpoint in this case. One should not delete `_optim_states.pt` files for now and we will make sure they are not loaded/applied when not needed.
