### ISSUE TITLE
[REQUEST] Allow larger tokens for inference (input+output)

### ISSUE THREAD

**Issue by lanking520** [microsoft/DeepSpeed#2740]
Currently DeepSpeed by default is setting maximum total tokens to 1024. Is there any reason behind it? Could we set for larger input tokens. Considering chatGPT related work is using 4096 as the input sequence length, it is way over the limit. The model could be small, but the generation could be large. Ideas?

cc: @RezaYazdaniAminabadi in case you know

**Comment by RezaYazdaniAminabadi** [comment]
Here is the config parameter: https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/inference/config.py#L240, which you can pass to the `init_inference` when adding DeepSpeed-inference to optimize your model.

**Comment by lanking520** [comment]
Thanks for the info @RezaYazdaniAminabadi . Why do we want to set a limit for max_tokens here? Is this helpful to boost inference peroformance or reduce the latency? Or simply a pre-calculation to estimate memory cost.

**Comment by RezaYazdaniAminabadi** [comment]
It is for pre-calculation purpose as you said. We just set a default to 1024 tokens, however this is configurable.

**Comment by lanking520** [comment]
Got it, thank you!
