### ISSUE TITLE
Question about section Ⅳ.C.(3) ”Communication Optimization“  in the paper “DeepSpeed Inference”

### ISSUE THREAD

**Issue by Eutenacity** [microsoft/DeepSpeed#2751]
Dear authors,

I am reading the paper "DeepSpeed Inference: Enabling Efficient Inference of Transformer Models at Unprecedented Scale“ which inspires me a lot.  However,  I feel confused about " odd-numbered GPUs offload activations for odd-numbered layers, while even-numbered GPUs offload activation for even-numbered layers"  in section Ⅳ.C.(3) ”Communication Optimization“. I would like to know more details about this. Could you claim it with an example or more details? Thank you. If possible, could you also point out the code files related to this?

I am eager for your quickly reply. Thank you very much.

best wishes, 
Eutenacity

**Comment by duli2012** [comment]
Hi Eutenacity,

[https://www.microway.com/wp-content/uploads/NVIDIA-DGX-A100-Block-Diagram.png](url)
By looking at the graph in the above link, the communication optimization is to avoid data movement in the same PICe switch at the same time. Therefore, odd/even numbered GPUs offload odd/even numbered layer activations separately.
