### ISSUE TITLE
[BUG] GPT-J inference on DeepSpeed using too much RAM and giving garbage results

### ISSUE THREAD

**Issue by sridhardev07** [microsoft/DeepSpeed#2755]
I am using GPT-J Inference on DeepSpeed to speed up my inference, first thing I noticed that it is taking too much RAM.
for eg: GPT-J FP16 takes 12GB RAM normally, but with deepspeed it takes around 22GB RAM, same for GPT-Neo-2.7B, normally the FP32 takes 11GB RAM but with deepspeed it takes around 20GB RAM.
2. The result are good and fast on smaller results 10-30 tokens. But for larger output 300-500 tokens, it keeps repeating garbage values.

**To Reproduce**
1. I am simply using the code:
# gpt_inference.py
```
# gpt_inference.py
import os
import deepspeed
import torch
from transformers import pipeline

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))
generator = pipeline('text-generation', model='EleutherAI/gpt-j-6B',
                     device=local_rank)



generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.float,
                                           replace_method='auto',
					   replace_with_kernel_inject=True)

string = generator("DeepSpeed is", do_sample=True, min_length=50)
print(string)
```
and I run it directly using 
`python gpt_inference.py`

**Expected behavior**
1. The RAM usage should be equivalent to normal model loading, which is 12GB for GPT-J fp16 and 10GB for GPT-Neo-2.7B
2. The results for larger tokens should also be same and meaningful. for this I also checked the already opened issue, but it says that it fixed but I am still facing this issue.: [Issue Link](https://github.com/microsoft/DeepSpeed/issues/2300)

Is there anything wrong with the code or the issue the way I am running the file as all example says to run it with deepspeed <file_name>, but I have to use it with gunicorn, so I am going with this approach.

Ubuntu 22.04
Python 3.10
PyTorch 1.13.1
deepspeed==0.8.0

**Docker context**
NO DOCKER

.

**Comment by molly-smith** [comment]
Hi @sridhardev07, what version of DeepSpeed are you using?

**Comment by sridhardev07** [comment]
Hi @molly-smith I am using latest version: deepspeed==0.8.0

**Comment by molly-smith** [comment]
Hi @sridhardev07, I was able to recreate your issue. I'm not sure why this is the case, but you can use DSPipeline instead of transformers pipeline as in this example https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/text-generation/inference-test.py. 
You should not see this issue with DSPipeline.
