### ISSUE TITLE
[BUG] wrong `overlapping_partition_gradients_reduce_epilogue` comment?

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#2785]
**Describe the bug**

It says it runs only for stage 2,
https://github.com/microsoft/DeepSpeed/blob/c5b983e92ec71d0bbd1deb110537db4eafbe1fb5/deepspeed/runtime/engine.py#L1907-L1909
but I see it running for stage 3 as well when stepping with debugger.

**Comment by tjruwase** [comment]
Yes, the comment was true when only stage 1 and 2 existed, and should have been deleted since stage 3 includes stage 2.

**Comment by stas00** [comment]
thank you, Tunji: suggested PR here: https://github.com/microsoft/DeepSpeed/pull/2786
