### ISSUE TITLE
[Question] training vit with zero doesnt reduce gpu memory usage. 

### ISSUE THREAD

**Issue by rxqy** [microsoft/DeepSpeed#2787]
Hi, many thanks for the excellent framework!

From the tutorial, I understand that deepspeed is designed for super large models on multinode machines, but here we are just doing a small test to check the memory usage and throughput of deep speed framework. So we are only training a vision transformer( [ViT-B-16](https://github.com/jeonsworld/ViT-pytorch), 85M params) model on a single node with a 20-core cpu and 2 Nvidia V100 GPUs. 

However, I observe a very similar memory usage, both around 20G per gpu, between zero (stage-1) adam and pytorch ddp adam. Is this ideal because of the model size? or num of gpus? If this is the case, then to which scale should we be able to observe a difference?

ENV: pytorch=1.13.1, deepspeed = 0.8.0 (via pip), cuda 11.7
deepspeed config:
```
{
  "train_batch_size": 256,
  "steps_per_print": 2000,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.001,
      "betas": [
        0.8,
        0.999
      ],
      "eps": 1e-8,
      "weight_decay": 3e-7
    }
  },
  "scheduler": {
    "type": "WarmupLR",
    "params": {
      "warmup_min_lr": 0,
      "warmup_max_lr": 0.001,
      "warmup_num_steps": 1000
    }
  },
  "gradient_clipping": 1.0,
  "prescale_gradients": false,
  "wall_clock_breakdown": false,
  "zero_optimization": {
      "stage": 1,
      "reduce_bucket_size": 5e8
  }
}
```

Many thanks in advance.

**Comment by tjruwase** [comment]
Yes, zero was designed for multi-billion parameter models, and so does not provide much help for 85M model. 

You might find the following discussion on memory usage of zero useful: https://github.com/microsoft/DeepSpeed/issues/467

**Comment by rxqy** [comment]
I see. Many thanks!
