### ISSUE TITLE
Make optional tensorflow dependency

### ISSUE THREAD

**Issue by vfdev-5** [microsoft/DeepSpeed#279]
Hi 

I was wondering whether it could be possible to make tensorflow dependency optional (in `requirements.txt`) as it seems like not to be explicitly used in the package. But by default when installing tensorflow, it installs a lot of side packages that pytorch user's probably wont use...

Thanks 

EDIT: 
maybe, it even would make more sense to introduce `requirements-dev.txt` as current requirement and keep essentials in `requirements.txt`

**Comment by jeffra** [comment]
Thanks @vfdev-5 for pointing this out. We've removed it from our requirements in PR #282.
