### ISSUE TITLE
[BUG] For pytorch transformers, do the linear layer hidden sizes need to be divisible by the world size?

### ISSUE THREAD

**Issue by jihan-yin** [microsoft/DeepSpeed#2793]
**Describe the bug**
I'm reading through the deepspeed code, and for wrapping a model without kernel inject (in my case, T5), I see many instances in the code where the model's parameters are split into contiguous chunks according to the world size. However, in each case, it seems like if the split dimension is not divisible by the world size, we simply ignore the remainder parameters? [ex1](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/module_inject/replace_module.py#L413), [ex2](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/module_inject/replace_module.py#L466). 

If I'm working with T5 (qkv hidden dim = 4096), using deepspeed with 3 devices, it seems like there's a single weight for each layer that is not copied over (4096 mod 3 = 1). What happens to this weight? It seems to cause errors down the line when running inference, so is it a hard requirement that everything (linear dim, num heads, embedding size, hidden state dimension, etc) needs to be divisible by the world size (or `mp_size`)?

**To Reproduce**
1. Run the T5 code from https://www.deepspeed.ai/tutorials/inference-tutorial/  with `CUDA_VISIBLE_DEVICES=0,1,2` on a >=3 gpu machine

**Expected behavior**
Either for inference to work as intended, or for some assertion error. However, we get
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/src/models/spellbook_celery/spellbook_celery/deepspeed/testing/run_sanity_test.py", line 82, in run_test_suite
    run_default_test()
  File "/home/ubuntu/src/models/spellbook_celery/spellbook_celery/deepspeed/testing/run_sanity_test.py", line 55, in run_default_test
    resp = get_response()
  File "/home/ubuntu/src/models/spellbook_celery/spellbook_celery/deepspeed/router.py", line 79, in get_response
    raise Exception(f"Deepspeed server encountered error: {data[ERROR_FIELD]}")
Exception: Deepspeed server encountered error: Traceback (most recent call last):
  File "/home/ubuntu/src/models/spellbook_celery/spellbook_celery/deepspeed/server.py", line 157, in start_server
    result = model.generate(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1276, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/transformers/generation_utils.py", line 528, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1040, in forward
    layer_outputs = layer_module(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 673, in forward
    self_attention_outputs = self.layer[0](
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 579, in forward
    attention_output = self.SelfAttention(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 498, in forward
    query_states = shape(self.q(hidden_states))  # (batch_size, n_heads, seq_length, dim_per_head)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 470, in shape
    return states.view(batch_size, -1, self.n_heads, self.key_value_proj_dim).transpose(1, 2)
RuntimeError: shape '[2, -1, 21, 64]' is invalid for input of size 611520
```

**ds_report output**
Please run `ds_report` to give us details about your setup.

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU count and types: 4 A10s
 - Transformers version: '4.23.0.dev0'
 - Python version: 3.8.12

**Additional context**

**Comment by molly-smith** [comment]
Hi @jihan-yin, I am not seeing the error you describe when trying to recreate the issue. Can you please provide the exact script you are running and the output of running ds_report?

**Comment by jihan-yin** [comment]
Hey @molly-smith, I realize I actually do something a little special here. I rewrote the deepspeed launcher code to be more lightweight for inference, to enable me to pass the model object directly to the processes on each GPU. This allows me to share the memory weights in cpu, lowering the amount of RAM needed for running inference with larger models.

Here is a single runnable script that encapsulates this issue:
```
from transformers.models.t5.modeling_t5 import T5Block
import os
import deepspeed
import torch
import multiprocessing


from collections import OrderedDict, defaultdict

from transformers import T5Tokenizer, T5ForConditionalGeneration

TORCH_DISTRIBUTED_DEFAULT_PORT = 29500
PID_FILE_BASEPATH = "/tmp"


def test_inference(env, model):
    for k in env:
        os.environ[k] = env[k]

    local_rank = int(os.getenv("LOCAL_RANK", "0"))
    world_size = int(os.getenv("WORLD_SIZE", "1"))

    tokenizer = T5Tokenizer.from_pretrained('google/flan-t5-xxl')
    model = deepspeed.init_inference(
            model,
            mp_size=world_size,
            dtype=model.dtype,
            injection_policy={
                T5Block: ("SelfAttention.o", "EncDecAttention.o", "DenseReluDense.wo")
            },
        )

    input_tokens = tokenizer.encode('What is the age of Michael Jackson? He is', return_tensors='pt').to(f"cuda:{local_rank}")
    out = model.generate(input_tokens, max_new_tokens=10)[0]
    if local_rank == 0:
        print(tokenizer.decode(out))



def parse_inclusion_exclusion(resource_pool):
    active_resources = OrderedDict()
    for hostname, slots in resource_pool.items():
        active_resources[hostname] = list(range(slots))

    return active_resources


if __name__ == "__main__":
    model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-xxl")
    model.share_memory()

    ###################### START Deepspeed launcher code #####################
    node_rank = 0
    current_env = os.environ.copy()
    master_addr = "127.0.0.1"
    master_port = TORCH_DISTRIBUTED_DEFAULT_PORT

    resource_pool = {}
    device_count = torch.cuda.device_count()
    if device_count == 0:
        raise RuntimeError("Unable to proceed, no GPU resources available")
    resource_pool["localhost"] = device_count
    world_info = parse_inclusion_exclusion(resource_pool)

    node_list = list(world_info.keys())
    nnodes = len(node_list)
    local_node = node_list[node_rank]
    local_gpu_ids = world_info[local_node]
    num_local_procs = len(local_gpu_ids)

    global_rank_mapping = defaultdict(list)
    curr_global_rank = 0
    dist_world_size = 0
    for node_id in node_list:
        gids = world_info[node_id]
        dist_world_size += len(gids)
        for gid in gids:
            global_rank_mapping[node_id].append(curr_global_rank)
            curr_global_rank += 1
    current_env["CUDA_VISIBLE_DEVICES"] = ",".join(map(str, local_gpu_ids))

    # set PyTorch distributed related environmental variables
    current_env["MASTER_ADDR"] = master_addr
    current_env["MASTER_PORT"] = str(master_port)
    current_env["WORLD_SIZE"] = str(dist_world_size)
    current_env["CROSS_RANK"] = str(node_rank)
    current_env["CROSS_SIZE"] = str(nnodes)
    current_env["LOCAL_SIZE"] = str(num_local_procs)

    processes = []
    cmd = []

    for local_rank in range(0, num_local_procs):
        # each process's rank
        dist_rank = global_rank_mapping[local_node][local_rank]
        current_env["RANK"] = str(dist_rank)
        current_env["LOCAL_RANK"] = str(local_rank)
        # spawn the processes. Must use spawn to support shared memory for the cpu model!
        context = multiprocessing.get_context("spawn")
        process = context.Process(
            target=test_inference,
            args=(current_env, model),
        )
        process.start()
        processes.append(process)
```

Running with
`CUDA_VISIBLE_DEVICES=0,1,2,3 python script.py`
gives an output of `<pad> 57</s>`.

Running with 
`CUDA_VISIBLE_DEVICES=0,1,2 python script.py`
gives an output of 
```
RuntimeError: shape '[1, -1, 21, 64]' is invalid for input of size 15015
RuntimeError: shape '[1, -1, 21, 64]' is invalid for input of size 15015
RuntimeError: shape '[1, -1, 21, 64]' is invalid for input of size 15015
```.

The output of ds_report:
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
```
but it gets cutoff with an error, where the culprit is `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda-11.1/bin/nvcc'`. This is probably due to a faulty path somewhere as I recently upgraded my cuda version.

**Comment by molly-smith** [comment]
@jihan-yin Do you know what version of deepspeed you're running? I'm still not seeing your issue. Can you please try running this simplified version of your script and letting me know what you see?

`from transformers.models.t5.modeling_t5 import T5Block
import os
import deepspeed
import torch
import multiprocessing


from collections import OrderedDict, defaultdict

from transformers import T5Tokenizer, T5ForConditionalGeneration


local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))

model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-xxl")

tokenizer = T5Tokenizer.from_pretrained('google/flan-t5-xxl')
model = deepspeed.init_inference(
        model,
        mp_size=world_size,
        dtype=model.dtype,
        injection_policy={
            T5Block: ("SelfAttention.o", "EncDecAttention.o", "DenseReluDense.wo")
        },
    )

input_tokens = tokenizer.encode('What is the age of Michael Jackson? He is', return_tensors='pt').to(f"cuda:{local_rank}")
out = model.generate(input_tokens, max_new_tokens=10)[0]
if local_rank == 0:
    print(tokenizer.decode(out))
`

**Comment by molly-smith** [comment]
Hi @jihan-yin, I've recreated your issue and you may be right that all of these attributes need to be divisible by mp_size. I'm not sure if there is any other work-around. If not, we will need to add a check to enforce this requirement. Thank you for bringing up the issue.

**Comment by molly-smith** [comment]
@RezaYazdaniAminabadi can you verify that linear dim, num heads, embedding size, hidden state dimension, etc. need to be divisible by mpsize? We divide these values by mpsize [here](https://github.com/microsoft/DeepSpeed/blob/10f3c301a00984f039f1c5d0ee90134eedac2181/deepspeed/module_inject/replace_module.py#L457) but when they do not divide nicely it causes tensor shape errors.
