### ISSUE TITLE
[QUESTION] when using ZeRO-Offload,,,

### ISSUE THREAD

**Issue by macto94** [microsoft/DeepSpeed#2817]
I want to do text-generation using GPT3-like model. (175B which is huge)
And my device is A100 80GB.  with 1TB cpu memory

When I found out about ZeRO-Offload, as I understood, it is designed for inference (or train) of huge model that doesn't fit on single gpu.
So I applied it to simple small model first, the offloading process is the same as following steps:
1. Put the model on gpu memory.
2. Offload to cpu memory.
3. fetching and releasing the modules during forward.

At this point, if the model cannot be located on a gpu from the beginning (step 1), I wonder if it can't be offloaded.
(actually, i tried and OOM error raised)
Then what does zero-offload exist for? Is it right that it can only be applied to models that fit on single gpu memory in the first place?

any reply would be very helpful.

**Comment by tjruwase** [comment]
@macto94, apologies for the delayed response. Did you get an answer to your question? 

Please take a look at these links on the relevant zero-inference technique 

Blog: https://www.deepspeed.ai/2022/09/09/zero-inference.html

BLOOM Inference blog: https://github.com/huggingface/transformers-bloom-inference/tree/main/bloom-inference-scripts#deepspeed-zero-inference

BLOOM Inference script: https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-zero-inference.py
