### ISSUE TITLE
[Fail with install.sh] No module named 'deepspeed_transformer_cuda'

### ISSUE THREAD

**Issue by chenghuige** [microsoft/DeepSpeed#283]
sh  ./install.sh -d -r

adding 'deepspeed-0.2.0.dist-info/METADATA'
adding 'deepspeed-0.2.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Installing deepspeed
Found existing installation: deepspeed 0.2.0
Can't uninstall 'deepspeed'. No files were found to uninstall.
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-3mli2hd3
Created temporary directory: /tmp/pip-req-tracker-bt28p51b
Initialized build tracking at /tmp/pip-req-tracker-bt28p51b
Created build tracker: /tmp/pip-req-tracker-bt28p51b
Entered build tracker: /tmp/pip-req-tracker-bt28p51b
Created temporary directory: /tmp/pip-install-zls2vzit
Requirement already satisfied: deepspeed==0.2.0 from file:///search/odin/chenghuige/other/DeepSpeed/dist/deepspeed-0.2.0-cp36-cp36m-linux_x86_64.whl in /search/odin/chenghuige/other/DeepSpeed (0.2.0)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-bt28p51b'
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/home/gezi/env/anaconda3/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "basic_install_test.py", line 8, in <module>
    raise err
  File "basic_install_test.py", line 5, in <module>
    import deepspeed as ds
  File "/search/odin/chenghuige/other/DeepSpeed/deepspeed/__init__.py", line 9, in <module>
    from deepspeed.pt.deepspeed_cuda import DeepSpeedTransformerLayer, DeepSpeedTransformerConfig
  File "/search/odin/chenghuige/other/DeepSpeed/deepspeed/pt/deepspeed_cuda.py", line 6, in <module>
    import deepspeed_transformer_cuda as ds_transformer_cuda
ModuleNotFoundError: No module named 'deepspeed_transformer_cuda'
Error on line 208
Fail to install deepspeed

**Comment by tjruwase** [comment]
@chenghuige Are you still seeing this problem?

**Comment by hjmshi** [comment]
I'm running into this problem as well when trying to do a manual install on my machine.

**Comment by RezaYazdaniAminabadi** [comment]
Hi,

Can you please uninstall deepspeed and try running "bash install -s" to reinstall it? This issues normally come from not having the kernels installed correctly!
Thanks.

Best regards
Reza

**Comment by chenghuige** [comment]
@tjruwase  Facing this problem right now.
![image](https://user-images.githubusercontent.com/6323467/92581034-bbb48000-f2c1-11ea-9a94-206bc0184537.png)

**Comment by tjruwase** [comment]
@chenghuige, I notice in the error message that apex is not installed. Did you try running "bash install.sh -s" as suggested by  @RezaYazdaniAminabadi ?

**Comment by chenghuige** [comment]
@tjruwase  seems threre are some problem installing apex.
Tried install.sh -s -l -r 
Installing apex locally so that deepspeed will build
Cannot uninstall requirement apex, not installed
You are using pip version 9.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Error on line 190
Fail to install deepspeed

**Comment by tjruwase** [comment]
@chenghuige, the command in error line 190 is actually to uninstall apex, before reinstallation. It is not obvious to me why this line is failing, even if there is no pre-existing apex installation. So my thought now for debugging this problem is to separate installation of 3rd party libs (e.g., apex) from installation of deepspeed. So can you try the following:

1) Install 3rd party libs (including apex): `bash -x install.sh -s -t -l`

2) Install deepspeed alone: `bash -x install.sh -s -d -l`

And please share the log of the first command to fail.

**Comment by tjruwase** [comment]
@chenghuige There are some new improvements to installation process. Can you please check if you still have this issue?

**Comment by chenghuige** [comment]
@tjruwase well interesting it tried to download torch-1.4 py2.7 version..
Collecting psutil
  Created temporary directory: /tmp/pip-unpack-ok7Xqo
  Looking up "https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz" in the cache
  Current age based on date: 77
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 77
  Using cached psutil-5.7.2.tar.gz (460 kB)
  Added psutil from https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz#sha256=90990af1c3c67195c44c9a889184f84f5b2320dce3ee3acbd054e3ba0b4a7beb (from -r requirements/requirements.txt (line 4)) to build tracker '/tmp/pip-req-tracker-Nhhgw2'
    Running setup.py (path:/tmp/pip-install-tTZL1i/psutil/setup.py) egg_info for package psutil
    Running command python setup.py egg_info
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in psutil setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
Cleaning up...
  Removing source in /tmp/pip-install-tTZL1i/psutil
Removed psutil from https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz#sha256=90990af1c3c67195c44c9a889184f84f5b2320dce3ee3acbd054e3ba0b4a7beb (from -r requirements/requirements.txt (line 4)) from build tracker '/tmp/pip-req-tracker-Nhhgw2'
Removed build tracker: '/tmp/pip-req-tracker-Nhhgw2'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/req/req_install.py", line 544, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/operations/build/metadata_legacy.py", line 118, in generate_metadata
    command_desc='python setup.py egg_info',
  File "/usr/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error on line 169
Fail to install deepspeed

**Comment by chenghuige** [comment]
@tjruwase  Verified ok on colab. But some problem for my local env tried to install py2 version.

**Comment by tjruwase** [comment]
@chenghuige If I understand correctly, are you still running into issues or is it now working?

**Comment by tjruwase** [comment]
@chenghuige Are you still seeing these issues with the latest code? We recently improved the installation process.

**Comment by loadams** [comment]
This issue is stale, closing now given the recent changes in pip install and setup.py.
