### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'ReduceOp'

### ISSUE THREAD

**Issue by SreehariSankar** [microsoft/DeepSpeed#2830]
Cannot import DeepSpeed. Above mentioned error obtained when I tried both "Import deepspeed" and "ds_report".

Mac OSX 12.3
Conda 22.9.0
Python 3.8.16
pytorch 1.12.1
pytorch-ignite 0.4.10
pytorch-lightning 1.9.0
transformers 4.21.3

installed using "pip install deepspeed"

please help

**Comment by tjruwase** [comment]
@SreehariSankar, can you please share a stack trace of the failure during deepspeed install? We are not aware of deepspeed working on OSX because of the current CUDA dependency. This could be the reason, but would like to confirm. Thanks!

**Comment by SreehariSankar** [comment]
DS installed properly. The above error was returned 
<img width="1431" alt="Screen Shot 2023-02-16 at 1 05 55 PM" src="https://user-images.githubusercontent.com/54915320/219451053-3d1dfb88-05d3-4f6e-803a-99e602d276ce.png">

Just to clarify, I think you are right, because I tried this on a CUDA-installed CentOS machine and everything was OK.
So i am inclined to believe that this is a MacOS issue.

**Comment by tjruwase** [comment]
@SreehariSankar, do you think this issue should remain opened? Thanks!
