### ISSUE TITLE
[BUG] Cumbersome and misleading optimizer configuration

### ISSUE THREAD

**Issue by nirda7** [microsoft/DeepSpeed#2840]
There is a discrepancy between the optimizer type (name) given in the DeepSpeedConfig json file to the optimizer chosen in the _configure_basic_optimizer function in .../deepspeed/runtime/engine.py
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/engine.py
![image](https://user-images.githubusercontent.com/124874956/217774513-1af01723-f805-4325-8138-37c1b32a65e9.png)

* When initializing DeepSpeed engine one can configure the basic optimizer by supplying an optimizer object or by using the model_parameters from the DeepSpeedConfig json file: https://www.deepspeed.ai/docs/config-json/
When the optimizer type is Adam/AdamW/Adagrad we get the following branched decision tree for the optimizer which consist of many discrepancies between the given optimizer type and the chosen basic optimizer:
![image](https://user-images.githubusercontent.com/124874956/217777330-21bdaa2b-9bc4-4ded-92e9-ae85ca60620e.png)

It is written that:
# Optimizer name of Adam forces AdamW logic unless adam_w_mode is explicitly set
And yet there are too many variables allowing the above discrepancies, especially for the "adagrad" optimizer.

As can be seen from the table above, the optimizer configuration is cumbersome, non-trivial, confusing and in some cases the optimizer chosen is not what the user asked for. For example, user asks for adagrad but get adam or adamw. Please check whether this configuration can be simplified, and maybe reduce the amount of args.

**Comment by jomayeri** [comment]
@nirda7 Thanks for investigating this and creating the table. A solution for the Adagrad is in development and I'll link it here when ready. As for the other config options we are looking at ways to reduce the complexity. Thanks again!
