### ISSUE TITLE
Does deepspeed support IterableDataset ?

### ISSUE THREAD

**Issue by chenghuige** [microsoft/DeepSpeed#285]
Since input dataset is large , we need to use IterableDataset, does deepspeed support this ?

**Comment by tjruwase** [comment]
@chenghuige Thanks for your interest in DeepSpeed.

DeepSpeed supports the use of arbitrary data loaders. Please the [BingBert ](https://github.com/microsoft/DeepSpeedExamples/tree/fd6fb5148ccf5c9ce222432006f1d93806187cd9/bing_bert)model for an example.

**Comment by chenghuige** [comment]
@tjruwase Thanks! I will have a try.

**Comment by Santosh-Gupta** [comment]
I'm looking at the example right now, it looks like we do Not include the IterableDataset in deepspeed.initialize ? We just feed the batch into the model? When I try to include the IterableDataset in deepspeed.initialize, I get 

>TypeError: object of type 'IterableDataset' has no len()
