### ISSUE TITLE
[BUG] multi-node training can not get state dict from `get_fp32_state_dict_from_zero_checkpoint`

### ISSUE THREAD

**Issue by guozhiyao** [microsoft/DeepSpeed#2859]
**Describe the bug**
I train the model with zero-2 for multi-node training, and save the model by `model.save_checkpoint`. When I want to get the state dict from `get_fp32_state_dict_from_zero_checkpoint`, it report the error below. 
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/21999339/220000482-396315d2-83ac-41c6-b84c-ed08971f7bb6.png">
I have add the config below, but it seems not working.
```
"checkpoint": {
    "use_node_local_storage":true
  }
```
Here is my ds_config.json
```
{
    "train_micro_batch_size_per_gpu": 10,
    "gradient_accumulation_steps": 2,
    "steps_per_print": 100,
    "gradient_clipping": 1,
    "optimizer": {
        "type": "Adam",
        "params": {
          "lr": 6e-4,
          "betas": [
            0.9,
            0.95
          ],
          "eps": 1e-8,
          "weight_decay": 1e-1
        }
  },
    "fp16": {
        "enabled": true
    },
    "zero_optimization": {
        "stage": 2,
        "overlap_comm": true,
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        }
    },
  "checkpoint": {
    "use_node_local_storage":true
  }
}
```
The version of deepspeed is 0.7.5.

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by ShijieZZZZ** [comment]
Hi @guozhiyao, do you have a small example for reproducing this?

**Comment by ShijieZZZZ** [comment]
Close for now. Feel free to reopen when there is update.
