### ISSUE TITLE
[BUG]  `"comms_logger": "enabled": false` makes `overlap_comm` invalid

### ISSUE THREAD

**Issue by ashe-shi** [microsoft/DeepSpeed#2861]
**Describe the bug**

**To Reproduce**
1. use config below to train
```
  "train_batch_size": 64,
  "gradient_accumulation_steps": 1,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.00015
    }
  },
  "fp16": {
    "enabled": true,
    "auto_cast": true,
    "initial_scale_power": 8
  },
  "zero_optimization": {
    "stage": 2,
    "contiguous_gradients": true,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 5e8,
    "allgather_bucket_size": 5e9
  },
  "steps_per_print": 50,
  "zero_allow_untested_optimizer": false,
  "comms_logger": {
    "enabled": false,
    "verbose": false,
    "prof_all": true,
    "debug": false
  }
}
```

**Expected behavior**
as `comms_logger` is not enabled, this config should not influence ZeRO2 behavior, the reduce should be overlapped by compute.

**Bug description**
however, the `reduce` became not overlapped by compute due to `comms_logger enable=False`
![image](https://user-images.githubusercontent.com/13433751/220051715-5d2a02a8-8b34-43cf-8e25-885e8599b8ca.png)

- pytorch 1.12
- deepspeed 0.77

**Comment by xiexbing** [comment]
@ashe-shi , thanks for the report. To reproduce the error, please provide the sample code and the specific deepspeed command you ran.

**Comment by xiexbing** [comment]
@ashe-shi , another thing is: to help debug and identify the issue, can you do me a favor to run some more configurations. e.g., 1) set "comm_logger": true and "overlap_comm": true; 2) set  "comm_logger": true and "overlap_comm": false. Please let me know if "overlap_comm" is enabled/disabled appropriately in these two cases. thanks.

**Comment by tjruwase** [comment]
Closing for lack of response. Please re-open as needed.

**Comment by JamiePlur** [comment]
I have the same issue here： https://github.com/microsoft/DeepSpeed/issues/4599
