### ISSUE TITLE
Unable to install deepspeed

### ISSUE THREAD

**Issue by GYKgamer** [microsoft/DeepSpeed#2871]
I am using WSL and whenever I try to install deepspeed I get this error

└─$ pip install deepspeed==0.7.7
Defaulting to user installation because normal site-packages is not writeable
Collecting deepspeed==0.7.7
  Downloading deepspeed-0.7.7.tar.gz (712 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 712.3/712.3 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8dk9ctwc/deepspeed_e99856966e414886a60f93690955ec23/setup.py", line 78, in <module>
          cupy = f"cupy-cuda{''.join(map(str,installed_cuda_version()))}"
        File "/tmp/pip-install-8dk9ctwc/deepspeed_e99856966e414886a60f93690955ec23/op_builder/builder.py", line 41, in installed_cuda_version
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I tried just using pip install deepspeed but I got the same error

**Comment by mrwyattii** [comment]
@GYKgamer could you share some more information about your system? What version of pytorch do you have installed? Are you able to use pytorch with your GPU?
```
pip list | grep torch
python3 -c "import torch; torch.Tensor([0]).to('cuda:0')"
```

**Comment by GYKgamer** [comment]
Hi sorry, I fixed it by installing CUDA

**Comment by DengNingyuan** [comment]
Could you please share the CUDA version you used
