### ISSUE TITLE
Trainig 1.5B gpt-2 model using DeepSpeed is slower than naive pytorch, the backward and optimizer seems weird [BUG]

### ISSUE THREAD

**Issue by huqinghao** [microsoft/DeepSpeed#2879]
**Describe the bug**

Training a 1.5B gpt-2 model using deepspeed is slower than naive  pytorch. And the optimizer_allgather and backward_microstep cost too much time. But for smaller models, such as 20M gpt-2, deepspeed is faster than pytorch. ZeRo stage1 or stage2 
The training speed of deepspeed in first 18 training steps looks good, but the logs shows that there's no optimizer_allgather operation logging. After 18 steps, the speed of deepspeed slows down because of the optimizer_allgather.  

There are several problems that I don't understand.
1. Why is  optimizer_allgather not showing in the first 18 steps?
2. ZeRO with stage 1 or stage 2  is supposed to have the same communication volume,  is it possible that ZeRO will slow down the training speed. 
**To Reproduce**
I use a gpt-2 like model with the following setting 
``` 
    n_layer = 48
    n_head = 20
    n_embd = 1600

```
The parameters of the model is about 1.5B.

Here is the deepspeed configuration:
```{
  "train_batch_size": 64,
  "steps_per_print": 1000,
  "gradient_accumulation_steps": 1,
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": 0.00015,
      "betas":[0.9, 0.999]
    }
  },
  "gradient_clipping":1.0,
  "fp16": {
    "enabled": true
  },
  "zero_optimization": {
    "stage": 1,
    "reduce_bucket_size": 5e8,
    "contiguous_gradients" :  false
  },
  "tensorboard": {
    "enabled": true,
    "output_path": "output/ds_logs/",
    "job_name": "train_bert"
},
"wall_clock_breakdown":true,
"flops_profiler": {
  "enabled": false,
  "profile_step": 1,
  "module_depth": -1,
  "top_modules": 1,
  "detailed": true,
  "output_file": null
  }
}
 ```
The training script looks like this:
```
deepspeed  ds_main.py --print-freq 10 --deepspeed  --deepspeed_config ds_config_zero2.json
```
For the ds_main.py, I set the batch-size of each GPU to 8, the total effective batch-size is 64 for 8gpus.
**Expected behavior**
 Deepspeed has less or the same training speed as the pytorch. 

**ds_report output**
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/XXXX/anaconda3/envs/XXX/lib/python3.8/site-packages/torch']
torch version .................... 1.12.1+cu113
deepspeed install path ........... ['/home/XXXX/anaconda3/envs/XXX/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.8.0, unknown, unknown
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.1
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.3

**Screenshots**
![image](https://user-images.githubusercontent.com/10703339/220874165-29545875-81f7-4497-8488-f7244b0d9be4.png)
![image](https://user-images.githubusercontent.com/10703339/220874200-50f96706-b2f7-4b96-9c19-54afe6c181da.png)
**The step_microstep is also weird.**
![image](https://user-images.githubusercontent.com/10703339/220888230-568a43f1-221d-4c73-9d23-b019798955b1.png)

**System info (please complete the following information):**
 - OS: [ Centos 8]
 - GPU count and types [single machine with x8 A100s]
 - Interconnects (if applicable) [machines connected with 100 Gbps IB]
 - Python version: 3.8 

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
Yes, deepspeed launcher
**Docker context**
This problem  exists no matter whether I use Docker or not, I tried both situation. 

**Additional context**
 None

**Comment by tjruwase** [comment]
@huqinghao, thanks for your question. Please note the following points. 
1. ZeRO is designed for models that cannot fit in GPU memory and so cannot be trained using regular DDP (e.g., pytorch). A 1.5B gpt-2 model fits easily on a A100, and so this is not the target ZeRO scenario. 
2. For models that can be trained using DDP, ZeRO can offer higher throughput by supporting larger batch sizes. Please see the autotuning results [here](https://github.com/microsoft/DeepSpeedExamples/tree/master/autotuning/hf) for more details. 
3. I notice a number of OVERFLOW messages in your log. It is not possible to make meaningful performance measurements in such circumstances.

**Comment by tjruwase** [comment]
@huqinghao, do you still need this issue opened?

**Comment by tjruwase** [comment]
Closing for now. Please re-open if needed. Thanks.
