### ISSUE TITLE
Error in load_state_dict() when not using zero-optimizer

### ISSUE THREAD

**Issue by hinthornw** [microsoft/DeepSpeed#288]
Related to this [comment ](https://github.com/microsoft/DeepSpeed/commit/936117b589e848318c44deb3ce128659afde6580#r40574993).

For the line:
self.optimizer.load_state_dict(checkpoint['optimizer'],
                                           load_optimizer_states=load_optimizer_states)

The signature of load_state_dict for torch.optim.Optimizer is  `def load_state_dict(self, state_dict):`. Loading from a checkpoint throws a TypeError when using certain non-zero optimizers (e.g., FusedAdam) for an unrecognized keyword argument.

**Comment by tjruwase** [comment]
@hinthornw Thanks for reporting this issue. This happens to be a problem for all fp32 optimizers, which are not wrapper optimizers.
