### ISSUE TITLE
[BUG] run_clm.py with deepspeed show  Number of trainable parameters = 0

### ISSUE THREAD

**Issue by mhamzeh** [microsoft/DeepSpeed#2882]
**Describe the bug**
Running fine-tuning using DeepSpeed 0.8 and transformers 4.26.1 returns 0 trainable parameters, here is an example output:

fine-tuning runs, however the model weights are not updated

**To Reproduce**
Have the following installed
```
deepspeed==0.8.1
deepspeed-mii==0.0.5+fae3029
transformers==4.26.1
accelerate==0.16.0
torch==1.13.1
```

**Expected behavior**
Number of trainable parameters  should show the actual number of parameters we want to train 

**ds_report output**

```
[INFO|trainer.py:1650] 2023-02-23 17:53:14,454 >> ***** Running training *****
[INFO|trainer.py:1651] 2023-02-23 17:53:14,454 >>   Num examples = 64938
[INFO|trainer.py:1652] 2023-02-23 17:53:14,454 >>   Num Epochs = 5
[INFO|trainer.py:1653] 2023-02-23 17:53:14,454 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1654] 2023-02-23 17:53:14,454 >>   Total train batch size (w. parallel, distributed & accumulation) = 64
[INFO|trainer.py:1655] 2023-02-23 17:53:14,454 >>   Gradient Accumulation steps = 16
[INFO|trainer.py:1656] 2023-02-23 17:53:14,454 >>   Total optimization steps = 5070
[INFO|trainer.py:1657] 2023-02-23 17:53:14,456 >>   Number of trainable parameters = 0 <---
```  

**Screenshots**

**System info (please complete the following information):**
 - OS:  (Ubuntu 20.04)
 - GPU: 4x NVIDIA A10G GPU's
- CUDA Version: 11.6

**Launcher context**
Yes, this is an example:

```
deepspeed --num_gpus=4 run_clm.py \
--deepspeed ds_config_gptneo.json \
   --model_name_or_path EleutherAI/gpt-neo-2.7B \
    --train_file sv_train.csv \
    --validation_file sv_validation.csv \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --per_gpu_eval_batch_size 1 \
    --do_train \
    --do_eval \
    --bf16 \
    --max_eval_samples 500 \
    --learning_rate 5e-06 \
    --num_train_epochs 5 \
    --save_total_limit 1 \
    --evaluation_strategy epoch \
    --output_dir /tmp/test-clm
```

**Docker context**
Issue is reproducible on both docker on and instance.

**Additional context**

Also faced the issue when training seq2seq translation models

**Comment by jomayeri** [comment]
@mhamzeh Can you share the contents of your config `ds_config_gptneo.json`.

**Comment by jomayeri** [comment]
Closing for now. Please reopen as needed.
