### ISSUE TITLE
Automatic adjustment of ZeRO's optimizer state partitioning with a new world size is not currently supported.

### ISSUE THREAD

**Issue by cdj0311** [microsoft/DeepSpeed#2898]
hi,
I have trained a GPT model with 4 nodes (8 gpus per node), but when I load the checkpoint with 6 nodes, I get the follows error:
````
deepspeed.runtime.zero.utils.ZeRORuntimeException: The checkpoint being loaded used a DP world size of 4 but the current world size is 6. Automatic adjustment of ZeRO's optimizer state partitioning with a new world size is not currently supported.
````

**Comment by chenzhanyiczy** [comment]
> hi, I have trained a GPT model with 4 nodes (8 gpus per node), but when I load the checkpoint with 6 nodes, I get the follows error:
> 
> ```
> deepspeed.runtime.zero.utils.ZeRORuntimeException: The checkpoint being loaded used a DP world size of 4 but the current world size is 6. Automatic adjustment of ZeRO's optimizer state partitioning with a new world size is not currently supported.
> ```

hi, can you share your experience? I also encountered the same problem

**Comment by sasaadi** [comment]
Hi, Can you share your solution to this? thanks

**Comment by zhao0306** [comment]
Hi, can you share your solution to this problem? thanks. @cdj0311

**Comment by JinmingZhao** [comment]
Same problem.

**Comment by liutaocode** [comment]
Same Issue

**Comment by tommy-qichang** [comment]
Same here.

**Comment by cmstudyscode** [comment]
same here +1

**Comment by Rafa-zy** [comment]
same here + 1

**Comment by xjwang4** [comment]
same here + 1

**Comment by gugarosa** [comment]
Same here. Is there any guidance on how to proceed?

**Comment by young-chao** [comment]
can you share your solution to me? thanks. @cdj0311

**Comment by macabdul9** [comment]
Any update on this? @cdj0311

**Comment by young-chao** [comment]
你好，你的邮件已收到，谢谢！

**Comment by kxgong** [comment]
The problem is caused by the ckpt is saved on 6 gpus but is reloaded with 4 gpus.

Try torch.load(..., map_location=[torch.device('cpu'))

**Comment by young-chao** [comment]
你好，你的邮件已收到，谢谢！

**Comment by ybdesire** [comment]
same issue + 1

**Comment by timpal0l** [comment]
Same here;
```
deepspeed.runtime.zero.utils.ZeRORuntimeException: The checkpoint being loaded used a DP world size of 7 but the current world size is 8. Automatic adjustment of ZeRO's optimizer state partitioning with a new world size is not currently supported.
```
