### ISSUE TITLE
Getting OOM for using deepspeed training a 30b model 

### ISSUE THREAD

**Issue by Richard-LZ-Zhang** [microsoft/DeepSpeed#2900]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by lavaaa7** [comment]
did you solve the problem, I'm facing a similar problem here...

**Comment by Richard-LZ-Zhang** [comment]
Nope, this post is mistakenly put. Please see issue #2899. Though I still did not solve the issue. Would you please do me a favor to say you have a similar issue in post #2899? Maybe increase the change the deepspeed team will take a look.
