### ISSUE TITLE
[BUG] Can not install - getting error - "unable to compile cuda/cpp extensions without a matching cuda version"

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/DeepSpeed#2902]
After running `pip install depspeed` getting the below error

OS - Windows 11
Python 3.10.9

```
Collecting deepspeed
  Using cached deepspeed-0.8.1.tar.gz (759 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\PC60\AppData\Local\Temp\pip-install-7aimsv5v\deepspeed_b92cc522763946a986a0e569e5e169e0\setup.py", line 166, in <module>
          ext_modules.append(builder.builder())
        File "C:\Users\PC60\AppData\Local\Temp\pip-install-7aimsv5v\deepspeed_b92cc522763946a986a0e569e5e169e0\op_builder\builder.py", line 623, in builder
          self.build_for_cpu = not assert_no_cuda_mismatch(self.name)
        File "C:\Users\PC60\AppData\Local\Temp\pip-install-7aimsv5v\deepspeed_b92cc522763946a986a0e569e5e169e0\op_builder\builder.py", line 105, in assert_no_cuda_mismatch
          raise Exception(
      Exception: >- DeepSpeed Op Builder: Installed CUDA version 12.0 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mrwyattii** [comment]
@rohan-paul could you please share which version of torch you have installed and also nvcc/cuda versions?

**Comment by rohan-paul** [comment]
> @rohan-paul could you please share which version of torch you have installed and also nvcc/cuda versions?

My locally installed CUDA toolkit is CUDA 12.0) 

And torch is '1.13.1+cu117'

**Comment by huyphan168** [comment]
Hi, your CUDA Toolkit need to have the same version with your pytorch cuda tookit attached with it. Here, you should downgrade CUDA toolkit to 11.7 version. This is due to deepspeed kernel and custom CUDA code need to be compiled with same cuda toolkit version with its pytorch.

**Comment by rohan-paul** [comment]
> Hi, your CUDA Toolkit need to have the same version with your pytorch cuda tookit attached with it. Here, you should downgrade CUDA toolkit to 11.7 version. This is due to deepspeed kernel and custom CUDA code need to be compiled with same cuda toolkit version with its pytorch.

Thanks for that. will have to do that then. Closing issue.

**Comment by MSDNAndi** [comment]
Running into the same problem. My OS level CUDA install is 12.1 (and I need it for other things at that level).

**Comment by mrwyattii** [comment]
@MSDNAndi if you must use CUDA 12.1 on your system you have two options:
1. Build torch from source and compile with 12.1 (see more here: https://github.com/pytorch/pytorch#from-source)
2. Remove the restriction on CUDA major version matching in DeepSpeed. You can do that by cloning the DeepSpeed Repo and modifying `op_builder/builder.py` to [remove the exception](https://github.com/microsoft/DeepSpeed/blob/b4b63f521f3d12118a0240a6b46dd35ba79f5534/op_builder/builder.py#L88). Then install DeepSpeed from source with `pip install .` in the cloned repo.

_Please note that if you go with option (2), we cannot guarantee correctness of the DeepSpeed code. We do not test with unmatched CUDA versions, and I recommend going with option (1)._

**Comment by MSDNAndi** [comment]
I did 2).
1) does not seem to be very logical. Compiling the behemoth (torch) could introduce a lot of other problems instead of "hacking" the dependency.
To throw an exception with no alternative to ignore/change to a warning is not ideal.

Are you considering changing the exception to a warning or provide an option during install to ignore it?

**Comment by chintan-donda** [comment]
@mrwyattii I'm having the same issue.
```
Exception: >- DeepSpeed Op Builder: Installed CUDA version 10.0 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp ex
tensions without a matching cuda version
```

Here are my CUDA version details:
`nvcc --version`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

`nvidia-smi`
```
Wed May 17 17:32:53 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
```

Can you please help me fix the issue?

**Comment by mrwyattii** [comment]
> Option 1) does not seem to be very logical. Compiling the behemoth (torch) could introduce a lot of other problems instead of "hacking" the dependency. To throw an exception with no alternative to ignore/change to a warning is not ideal.
> 
> Are you considering changing the exception to a warning or provide an option during install to ignore it?

We recently added an environment variable that allows users to skip this check: #3436

**Comment by mrwyattii** [comment]
@chintan-donda I cannot give you *exact* commands as I do not know what operating system, torch version, etc. that you have. Please see the NVIDIA CUDA installation guide: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

You will want to upgrade the nvcc version to be version `11.x`
