### ISSUE TITLE
[BUG] inference a 176 B bloom model and the process is killed .

### ISSUE THREAD

**Issue by lambda7xx** [microsoft/DeepSpeed#2917]
- my deepspeed is 0.8.1 and my transformers is 4.21.2 and my  cuda_11.8.r11.8/compiler.31833905_0. I use the 8 32GB-V100 and my CPU memory is 500GB.
- I try the code [bloom-ds-inference.py](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-inference.py#L42) and change the num_tokens = 50. The below is my command 
```
     deepspeed --num_gpus 8 bloom-inference-scripts/bloom-ds-zero-inference-0301.py --name bigscience/bloom --batch_size  2 --cpu_offload --benchmark

```
the below is my log
```
[2023-03-01 05:13:31,385] [INFO] [utils.py:825:see_memory_usage] start-of-generate
[2023-03-01 05:13:31,392] [INFO] [utils.py:826:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 20.1 GB         Max_CA 20 GB 
[2023-03-01 05:13:31,393] [INFO] [utils.py:834:see_memory_usage] CPU Virtual Memory:  used = 502.63 GB, percent = 99.8%
*** Starting to generate 50 tokens with bs=2
Generate args {'max_new_tokens': 50, 'do_sample': False}
*** Running generate
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
[2023-03-01 05:14:14,124] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2155
[2023-03-01 05:14:23,560] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2158
[2023-03-01 05:14:32,237] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2162
[2023-03-01 05:14:41,401] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2163
[2023-03-01 05:14:50,590] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2165
[2023-03-01 05:14:59,455] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2167
[2023-03-01 05:14:59,456] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2169
[2023-03-01 05:15:09,210] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2171
[2023-03-01 05:15:20,673] [ERROR] [launch.py:324:sigkill_handler] ['/usr/bin/python3', '-u', 'bloom-inference-scripts/bloom-ds-zero-inference-0301.py', '--local_rank=7', '--name', 'bigscience/bloom', '--batch_size', '2', '--cpu_offload', '--benchmark'] exits with return code = -9

```

**Comment by lambda7xx** [comment]
I have try the code several times with different batch size. All rthe

> * my deepspeed is 0.8.1 and my transformers is 4.21.2 and my  cuda_11.8.r11.8/compiler.31833905_0. I use the 8 32GB-V100 and my CPU memory is 500GB.
> * I try the code [bloom-ds-inference.py](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-inference.py#L42) and change the num_tokens = 50. The below is my command
> 
> ```
>      deepspeed --num_gpus 8 bloom-inference-scripts/bloom-ds-zero-inference-0301.py --name bigscience/bloom --batch_size  2 --cpu_offload --benchmark
> ```
> 
> the below is my log
> 
> ```
> [2023-03-01 05:13:31,385] [INFO] [utils.py:825:see_memory_usage] start-of-generate
> [2023-03-01 05:13:31,392] [INFO] [utils.py:826:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 20.1 GB         Max_CA 20 GB 
> [2023-03-01 05:13:31,393] [INFO] [utils.py:834:see_memory_usage] CPU Virtual Memory:  used = 502.63 GB, percent = 99.8%
> *** Starting to generate 50 tokens with bs=2
> Generate args {'max_new_tokens': 50, 'do_sample': False}
> *** Running generate
> /home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
>   warnings.warn(
> /home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
>   warnings.warn(
> /home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
>   warnings.warn(
> /home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
>   warnings.warn(
> /home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
>   warnings.warn(
> /home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
>   warnings.warn(
> /home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
>   warnings.warn(
> /home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
>   warnings.warn(
> [2023-03-01 05:14:14,124] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2155
> [2023-03-01 05:14:23,560] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2158
> [2023-03-01 05:14:32,237] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2162
> [2023-03-01 05:14:41,401] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2163
> [2023-03-01 05:14:50,590] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2165
> [2023-03-01 05:14:59,455] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2167
> [2023-03-01 05:14:59,456] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2169
> [2023-03-01 05:15:09,210] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2171
> [2023-03-01 05:15:20,673] [ERROR] [launch.py:324:sigkill_handler] ['/usr/bin/python3', '-u', 'bloom-inference-scripts/bloom-ds-zero-inference-0301.py', '--local_rank=7', '--name', 'bigscience/bloom', '--batch_size', '2', '--cpu_offload', '--benchmark'] exits with return code = -9
> ```

**Comment by stainswei** [comment]
I have the same error, did you resolve it?
