### ISSUE TITLE
TypeError: 'float' object is not callable

### ISSUE THREAD

**Issue by MikalaiDrabovich** [microsoft/DeepSpeed#292]
https://github.com/microsoft/DeepSpeed/blob/7ccc9daf9ec909b71c7261f8e77876774b1633af/deepspeed/pt/deepspeed_zero_optimizer.py#L614

  if self.gradient_predivide_factor() != dp_world_size:

self.gradient_predivide_factor is float, () should be removed

**Comment by tjruwase** [comment]
Closed by PR #385.
