### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by XiaoyaWang-gh** [microsoft/DeepSpeed#2925]
**Describe the bug**
I set tensor-model-parallel-size to 16, then I begin to pretrain. But the log shows that the tensor-model-parallel size: 4.

**To Reproduce**

**Expected behavior**
the log shows that the tensor-model-parallel size: 16.

**ds_report output**
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/data2/chaoni/miniconda3/envs/yoyopy38/lib/python3.8/site-packages/torch']
torch version .................... 1.11.0
deepspeed install path ........... ['/data2/chaoni/miniconda3/envs/yoyopy38/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.8.1, unknown, unknown
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.2

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by tjruwase** [comment]
@XiaoyaWang-gh, to help the investigation, can you please share details such as command line, and logs? Thanks!

**Comment by XiaoyaWang-gh** [comment]
> @XiaoyaWang-gh, to help the investigation, can you please share details such as command line, and logs? Thanks!

Sorry for disturbing, I've solve the problem. Before

**Comment by XiaoyaWang-gh** [comment]
I've known that the  most tensor-model-parallel-size is constricted by the number of cuda devices. Thanks reply.

**Comment by XiaoyaWang-gh** [comment]
I've known that the  most tensor-model-parallel-size is constricted by the number of cuda devices. Thanks reply.

**Comment by tjruwase** [comment]
@XiaoyaWang-gh, do you still need this issue opened?

**Comment by tjruwase** [comment]
Closing as it seems to be resolved. Please feel free to re-open. Thanks.
