### ISSUE TITLE
deepspeed: command not found

### ISSUE THREAD

**Issue by remarkableJ** [microsoft/DeepSpeed#2934]
![image](https://user-images.githubusercontent.com/45261220/222686853-e1ca76c6-cc00-4f3d-9a37-9685a45408a7.png)

**Comment by UranusYu** [comment]
Hello, I would like to know how you solved the problem

**Comment by remarkableJ** [comment]
> Hello, I would like to know how you solved the problem

My python with deepspeed installed is not added to the environment variables,  maybe you can try:
`vim ~/.bashrc`
add:
`export PYTHONPATH=$PATH:{yourPythonDir}/bin`
and run:
`source ~/.bashrc`

**Comment by UranusYu** [comment]
> > Hello, I would like to know how you solved the problem
> 
> My python with deepspeed installed is not added to the environment variables, maybe you can try: `vim ~/.bashrc` add: `export PYTHONPATH=$PATH:{yourPythonDir}/bin` and run: `source ~/.bashrc`

Thank you for your reply.
