### ISSUE TITLE
AttributeError: 'PipelineEngine' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by suiyan538** [microsoft/DeepSpeed#2978]
**Describe the bug**
AttributeError: 'PipelineEngine' object has no attribute 'flatten'

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by suiyan538** [comment]
![image](https://user-images.githubusercontent.com/120363294/223911331-7767444f-e43c-4ec2-9ae1-71263d9addfd.png)

**Comment by tjruwase** [comment]
@suiyan538, can you share a repro for this issue? Thanks!

**Comment by tohtana** [comment]
@suiyan538 Hi, thank you for your report.

`flatten` of `DeepSpeedEngine` (the superclass of `PipelineEngine`) is expected to be set at the constructor: https://github.com/microsoft/DeepSpeed/blob/43d58d99eba800a809f16efa30a90eb25f7a7003/deepspeed/runtime/engine.py#L393

Can you give us a reproducing code?

**Comment by tjruwase** [comment]
Closing for now. Please re-open as needed.
