### ISSUE TITLE
[REQUEST] sync FusedAdam with the upstream

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#3006]
https://github.com/microsoft/DeepSpeed/blob/43d58d99eba800a809f16efa30a90eb25f7a7003/deepspeed/ops/adam/fused_adam.py#L4-L5

needs to be synced with https://github.com/NVIDIA/apex/blob/master/apex/optimizers/fused_adam.py as since it was forked several fixes were made and BF16 support was added https://github.com/NVIDIA/apex/commits/master/apex/optimizers/fused_adam.py

the fork happened at: https://github.com/NVIDIA/apex/commit/a109f85 Sep 28, 2020

@jeffra

**Comment by jeffra** [comment]
A small update on this thread @stas00, @awan-10 just discovered an issue with the latest version of FusedAdam from apex that has to do with this PR: https://github.com/NVIDIA/apex/pull/1560.

Once we have that resolved though i think the path towards updating this will become easier. We'll keep you posted and update this thread.

**Comment by stas00** [comment]
Thank you, Jeff

And FYI pytorch-2.0 now has a built-in fused version as well! we have just integrated it into transformers:
https://github.com/huggingface/transformers/pull/22144
