### ISSUE TITLE
[BUG] ZERO3

### ISSUE THREAD

**Issue by guozhiyao** [microsoft/DeepSpeed#3014]
**Describe the bug**
I trained the gpt 13B model and used zero3, but it seems that the gpu usage will not decrease as the number of gpus increases? In addition, I enabled offload, but it shows `CPU Virtual Memory: used = 0.0 GB, percent = 0.0%`. Could it be related to I enabled the `activation_checkpointing`?
```
"zero_optimization": {
     "stage": 3,
     "overlap_comm": true,
     "contiguous_gradients": true,
     "offload_param": {
       "device": "cpu",
       "pin_memory": false
     },
     "offload_optimizer": {
       "device": "cpu",
       "pin_memory": false
     }
   }
```

**Comment by xiexbing** [comment]
Hello @guozhiyao, thanks for your use of DeepSpeed. We haven't seen anything similar to this. Can you please provide more detailed information to help me repeat this issue. e.g., the hardware setting, the specific application, and your specific configurations on DeepSpeed.

**Comment by xiexbing** [comment]
cannot reproduce the bug, may reopen later once requested.
