### ISSUE TITLE
[BUG] Model running OOM after calling deepspeed.init_inference

### ISSUE THREAD

**Issue by agademic** [microsoft/DeepSpeed#3028]
Hi all,

I am trying to replicate the DeepSpeed Inference basic tutorial with the following script on a VM with 1x 40GB A100:

```
model = AutoModelForCausalLM.from_pretrained(
    "EleutherAI/gpt-neox-20b",
    torch_dtype=torch.float16,
    #load_in_8bit=True,
    device_map="auto",
)

ds_model = deepspeed.init_inference(
    model=model,  
    mp_size=1, 
    dtype=torch.float16, 
    replace_method="auto", 
    replace_with_kernel_inject=True,
)
```

Model loads fine and consumes ~ 39GB out of ~ 41GB. But after calling deepspeed.init_inference I get a CUDA OOM error.
Is there something I am missing? Does deepspeed need a bit overhead and thus, my VRAM is too low? How much additional VRAM do I need to be able to load the model for deepspeed inference?

Thanks a lot!

**Comment by f-lng** [comment]
Just found your issue while looking for something, and as nobody responded yet:

I might be totally wrong as I am just exploring deepspeed_inference but as far as I understood both device_map="auto" and deepspeed.init_inference will try to load your model onto your GPU(s). Try to load the model onto CPU by not using the device_map and leave it to deepspeed to move it to GPU.

**Comment by don-tpanic** [comment]
> AFAIK, you should not use both `device_map="auto"` and `deepspeed.init_inference()` together. The former is supported by [Accelerate](https://huggingface.co/docs/transformers/main_classes/model#large-model-loading) while the latter is supported by DeepSpeed Inference.
> 
> I have not gotten DeepSpeed Inference to work for models where model size > GPU memory (which is the case for your setup), so you might wanna make do with Accelerate (`device_map="auto"`) or try [DeepSpeed ZeRO-3](https://huggingface.co/docs/transformers/main_classes/deepspeed).
> 
> You can find the size of `EleutherAI/gpt-neox-20b` [here](https://huggingface.co/EleutherAI/gpt-neox-20b/tree/main).

Thanks, it sounds like (device_map="auto") and DeepSpeed ZeRO-3 (which is for training) are not compatible solutions for parallel training?

**Comment by f-lng** [comment]
As far as I remember they are not, and it is also not needed, as they both can load one big model on multiple GPUs.
