### ISSUE TITLE
[BUG] Explicit Optimizer naming in logs

### ISSUE THREAD

**Issue by tjruwase** [microsoft/DeepSpeed#3050]
DeepSpeed log should explicitly state the optimizer details including
 1. Provider: Torch vs DeepSpeed vs Apex
 2. Variant: AdamW vs Adam
 3. Fused vs NonFused

Example: https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L122-L131

**Comment by tjruwase** [comment]
@stas00, FYI

**Comment by tjruwase** [comment]
@xiexbing, DS currently prints out optimizer name [here](https://github.com/microsoft/DeepSpeed/blob/5c2a81c2c1be8b6308781c01226d56df3ead2c1f/deepspeed/runtime/engine.py#L1291-L1293). We need to update printed name to be more informative.

**Comment by xiexbing** [comment]
the function is added and this PR is merged to the master
