### ISSUE TITLE
[BUG] INFLIGHT parameters after evaluation

### ISSUE THREAD

**Issue by xiamengzhou** [microsoft/DeepSpeed#3068]
**Describe the bug**
I adapted my training process from the hugging face trainer.py, so most of my trainer is similar to theirs. My model includes a language model and an external module for learning other parameters using information from the main model. I put the main and external parameters in separate groups in the optimizer. While testing the code on larger models with deepspeed, I encountered an assertion error after 50 training steps and 1 evaluation round. The error is related to the embedding matrix, which remains in "INFLIGHT" status after resuming training, while all other parameters are "AVAILABLE".

> AssertionError: {'id': 786, 'status': 'INFLIGHT', 'numel': 38603520, 'ds_numel': 38603520, 'shape':
> (50265, 768), 'ds_shape': (50265, 768), 'requires_grad': False, 'grad_shape': None, 'persist': False,
> 'active_sub_modules': {3}}

The program runs fine if I simply train a language model without an external module. 

**To Reproduce**
I can provide the code if necessary, but hope that I can get some help on how to further debug this issue :) 

**Expected behavior**
I expected the training runs fine after evaluation. 

**Screenshots**

**System info (please complete the following information):**
 - OS: Linux  4.18.0-425.13.1.el8_7.x86_64
 - GPU count and types: 1 machine x2 A100s 
 - Interconnects (if applicable)
 - Python version: python 3.8

**Launcher context**
I am using deepspeed to launch my program.

**Comment by vlievin** [comment]
I am experiencing the same issue on a single node using `lightning` and a `transformers.BertModel` at the second epoch of lightning's "sanity checking":

> assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary()
AssertionError: {'id': 0, 'status': 'INFLIGHT', 'numel': 0, 'ds_numel': 23440896, 'shape': (0,), 'ds_shape': (30522, 768), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': {702}}

**system info**
- OS: Ubuntu 20.04.5 LTS, kernel: Linux 5.15.0-1030-gcp, arch: x86-64
- GPU count and types: 1 x A100-SXM4-40GB
- Python version: 3.9.16

**Relevant dependencies**
- `lightning==2.0.0`
- `transformers==4.27.1`
- `deepspeed==0.8.3`
- `torch==2.0.0`

**Comment by HeyangQin** [comment]
Hello @xiamengzhou @vlievin. Thank you for reporting the issue to us! This issue seems related to the parameter partitioning in ZeRO-3. Could you provide some scripts for us to reproduce this issue?

**Comment by vlievin** [comment]
Hi @HeyangQin, my issue is definitely related with stage 3. I don't experience it using stage 2. I will try to isolate the bug in a small script next week.

**Comment by kisseternity** [comment]
Same issue encountered, I use pure DeepSpeed without lightning.

**Comment by vlievin** [comment]
Any update or temporary workaround regarding this issue?

**Comment by xiongma** [comment]
same issue encountered, this was happen when I use `accelerator.backward(loss)`

**Comment by pclucas14** [comment]
Same issue.

**Comment by xiongma** [comment]
@HeyangQin can u pay attention about this? thx very much

**Comment by tgaddair** [comment]
I've been trying to come up with a small standalone repro for this, but unfortunately it's not entirely clear what triggers the behavior. A few things I've noticed though the seem consistent with what others have said:

- Only happens when using zero stage 3
- Is triggered specifically when the model is trained for an epoch, then evaluated, then trained for the next epoch (on the first batch of the second epoch)
- Is triggered in the forward pass when calling an embedding

A couple things that I was able to do to workaround the issue:

- Vary the batch size. Some batch sizes seem to trigger the issue, others don't.
- Avoid calling `model.eval()`. For some reason this will consistently prevent the error from happening for me.

**Comment by vlievin** [comment]
Thank you @HeyangQin, this fix is super helpful!

**Comment by tgaddair** [comment]
Thanks for the fix @HeyangQin! Are there plans to release a patch release next week containing this fix?

**Comment by pretzel583** [comment]
I was still getting this error after updating to deep speed 0.9.3 and lightning 2.0.3.

it seems to be fixed when I forced my dataset (both train and Val!) size to be an exact multiple of batch size. This is consistent with one of @tgaddair observations.

**Comment by HeyangQin** [comment]
Hi @pretzel583. Could you share a reproduce script for us to better investigate the issue? Thank you

**Comment by cxjtju** [comment]
> Same issue.

What should be the values of batch_size and mini_batch_size respectively? @ pretzel583
