### ISSUE TITLE
[BUG]DeepSpeed 0.8.0 consuming upto 20% higher CUDA memory compared to 0.7.5

### ISSUE THREAD

**Issue by dhawalkp** [microsoft/DeepSpeed#3076]
**Describe the bug**
Tested serving togethercomputer/GPT-NeoXT-Chat-Base-20B model using DeepSpeed 0.75 over 0.8.0 and noticed the 0.8.0 throws CUDA OOM on the same GPU that loaded the same model on DeepSpeed 0.75
 
**To Reproduce**
1. Load togethercomputer/GPT-NeoXT-Chat-Base-20B on host with 4 A10Gs with 24 GB per GPU memory using DeepSpeed 0.75 and the model will successfully load with Tensor Parallel Degree to 4.
2. Load the same togethercomputer/GPT-NeoXT-Chat-Base-20B on host with 4 A10Gs with 24 GB per GPU memory using DeepSpeed 0.8.0 and it will throw out of memory with Tensor Parallel Degree to 4.

**Expected behavior**
DeepSpeed 0.8.0 should not throw OOM error by loading togethercomputer/GPT-NeoXT-Chat-Base-20B on host with 4 A10Gs with 24 GB per GPU memory  with Tensor Parallel Degree to 4.

**ds_report output**
Please run `ds_report` to give us details about your setup.
NA

**Screenshots**
NA

**System info (please complete the following information):**
 - OS:  Ubuntu 20.04
 - GPU count and types: 1 host with 4 A10G GPUs with 24GB Memory each GPU.
 - Interconnects (if applicable) NA
 - Python version: 3.8
 - Any other relevant info about your setup

**Launcher context**
Launching with MPI

**Docker context**
NA
**Additional context**
NA

**Comment by lanking520** [comment]
Similar observation also appears in the following models:
- BLOOM-176B (10%) more memory overall
- OPT (15%) more memory
- GPT-NeoX (17%) more memory

This issue start from upgrading from 0.7.5 to 0.8.0 and still valid in 0.8.2.

Currently we are trying to limit the max_input_output token length to save the memory

@HeyangQin @RezaYazdaniAminabadi did you have any better way to resolve this?

**Comment by hzwer** [comment]
Thank you very much, I lowered the deepspeed version when deploying bloom3B training on v100, it really worked.
