### ISSUE TITLE
[BUG] unable to convert fp16 to fp32 with zero_to_fp32.py

### ISSUE THREAD

**Issue by raomanohar** [microsoft/DeepSpeed#3089]
**Describe the bug**
Unable to convert fp16 checkpoints to fp32

I am trying to finetune GPTJ model with deepspeed I can train the model with deepspeed stage 1 once the checkpoints are saved I am unable to convert the fp16 model into fp32 I get the error

` ValueError(f"unknown zero stage {zero_stage}") `

**To Reproduce**
1. Go to '[This finetuning repo](https://github.com/mallorbc/Finetune_LLMs)'
2. following the finetuning steps mentioned : https://www.youtube.com/watch?v=usz8JOxgQFs&t=48s'
3. Once the finetuning is completed the checkpoints are saved and when I try to convert the fp16 checkpoints to fp32 i get the below error
4. ` ValueError(f"unknown zero stage {zero_stage}") `

**ds_report output**

`
DeepSpeed C++/CUDA extension op report

NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.

JIT compiled ops requires ninja
ninja .................. [OKAY]

op name ................ installed .. compatible

async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]

DeepSpeed general environment info:
torch install path ............... ['/home/manoharrao/miniconda3/envs/cuda11/lib/python3.8/site-packages/torch']
torch version .................... 1.9.0+cu111
deepspeed install path ........... ['/home/manoharrao/miniconda3/envs/cuda11/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.8.3, unknown, unknown
torch cuda version ............... 11.1
torch hip version ................ None
nvcc version ..................... 11.1
deepspeed wheel compiled w. ...... torch 1.9, cuda 11.1

`

**System info (please complete the following information):**
 - OS:  Ubuntu 20.04
 - GPU : 1x A100 80GB
 - Python version : 3.8

**Comment by raomanohar** [comment]
> Hi @raomanohar, zero_to_fp32.py is used based on a zero 2 and 3 DeepSpeed checkpoints, see top comments [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/utils/zero_to_fp32.py#:~:text=%23%20This%20script%20extracts,%23%20application.) You used stage 1 and that is the reason.

@ShijieZZZZ thanks for pointing it out. Should I convert the fp16 values to fp32 if I train in zero 1? Secondly when I try to train with zero 2 I always run into exits with return code = -9 could you please tell me what this error even mean?
i'm using this config : https://github.com/huggingface/transformers/blob/main/tests/deepspeed/ds_config_zero2.json

**Comment by ShijieZZZZ** [comment]
Hi @raomanohar, for 1st, yes, should convert. Could you try the change in this [PR](https://github.com/microsoft/DeepSpeed/pull/3149/files). The idea is zero_stage 1 and 2 could be converted in the same fashion. 

For 2nd, could you open a new issue and describe more? Better with traces/logs, etc

**Comment by raomanohar** [comment]
@ShijieZZZZ thank you for your response. I'll try  that but now the model doesnt even train for some reason. Because of the second error. I'll raise a new issue for the same.

**Comment by davidvblumenthal** [comment]
Hi @raomanohar 
Were you able to reconstruct the fp32 weights from your stage 1 checkpoint? If so how did you do it? Any help would be appreciated :)

**Comment by raomanohar** [comment]
@davidvblumenthal Sorry I haven't tried converting the Stage 1 reconstruction.
