### ISSUE TITLE
[BUG] model created out of `zero.Init` context cause OOM on a large model trained with ZeRO3

### ISSUE THREAD

**Issue by bigeagle** [microsoft/DeepSpeed#3125]
**Describe the bug**

In-context model creation:
```py
model_config = AutoConfig.from_pretrained(EleutherAI/pythia-6.9b-deduped)
with deepspeed.zero.Init(config_dict_or_path=ds_config, remote_device='cpu', enabled=True):
    model = GPTNeoXForCausalLM(model_config)
```
Out-of-context model creation:
```py
model = GPTNeoXForCausalLM(model_config)
deepspeed.zero.Init(module=model, config_dict_or_path=ds_config, remote_device='cpu', enabled=True):
```

According to the [docs](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/partition_parameters.py#L535) the out-of-context model creation should behave just-like the model was created in context.

However, in-context model creation leads to expected training, but out-of-context results to CUDA OOM.

**Expected behavior**

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/wangyuzhi/venvs/gpt/lib/python3.8/site-packages/torch']
torch version .................... 2.0.0+cu117
deepspeed install path ........... ['/home/wangyuzhi/venvs/gpt/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.8.3, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
```

**Screenshots**
Smooth training (in-context creation)  
- The "Mem" in logging text stands for (allocated/reserved/used for nvidia-smi )
![image](https://user-images.githubusercontent.com/548512/229367264-a4054dfc-79cc-4d56-8b4d-58c54c4fecc3.png)

CUDA OOM (out-of-context creation): 
- p.s. It seems not a single forward-backward has passed , I can see a rapid memory increasement from nvidis-smi. I suspect cpu-offloading was not working as expected
![image](https://user-images.githubusercontent.com/548512/229367059-f0470136-0cd1-42aa-ae8c-fb8321bb6745.png)

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - 4x 2080Ti
 - Python 3.8

**Launcher context**
```bash
deepspeed --num_gpus=4 test_deepspeed.py --deepspeed_config ds_config.json
```

**Additional context**
The purpose of my out-of context model creation is for fine-tuning a large model. In this case, if I use in-context model creation, for example
```python
with zero.Init(...):
    model = GPTNeoXForCausalLM.from_pretrained(...)
```
this would simply fail because `meta` parameters cannot be loaded from a pretrained model.

Therefore, I have to first load a pretrained model before partition it with `zero.Init`. 

It would be very helpful if a better solution for finetuning with zero3 is availible.

**Comment by bigeagle** [comment]
Here is my `ds_config.json`

```json
{
    "fp16": {
        "enabled": true,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 1e-4
        }
    },
    // "memory_breakdown": true,
    "zero_optimization": {
        "stage": 3,
        "stage3_gather_16bit_weights_on_model_save": false,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": false,
        "contiguous_gradients": true,
        "sub_group_size": 1e8,
        "stage3_max_live_parameters": 2e8,
        "stage3_max_reuse_distance": 2e8,
        "stage3_prefetch_bucket_size": 1e8,
        "stage3_param_persistence_threshold": 1e5,
        "reduce_bucket_size": 1e7
    },
    "gradient_clipping": 1.0,
    "train_micro_batch_size_per_gpu": 1,
    "gradient_accumulation_steps": 1,
    "steps_per_print": 2000000
}
```

**Comment by bigeagle** [comment]
I've found the right path for param initialization from a normal `state_dict`, so the background target of this issue no longer exist.  Basically `zero.GatheredParameters` is required to init weights.

Here is the code peice, modified from [huggingface/transformer](https://github.com/huggingface/transformers/blob/c612628045822f909020f7eb6784c79700813eda/src/transformers/modeling_utils.py#L449)
```python
def zero3_load_state_dict_into_model(model_to_load: nn.Module, state_dict: Dict[str, torch.Tensor], start_prefix: str = ''):
    # copy state_dict so _load_from_state_dict can modify it
    metadata = getattr(state_dict, "_metadata", None)
    state_dict = state_dict.copy()
    if metadata is not None:
        state_dict._metadata = metadata

    error_msgs = []

    # PyTorch's `_load_from_state_dict` does not copy parameters in a module's descendants
    # so we need to apply the function recursively.
    def load(module: nn.Module, state_dict, prefix=""):
        local_metadata = {} if metadata is None else metadata.get(prefix[:-1], {})
        args = (state_dict, prefix, local_metadata, True, [], [], error_msgs)
        # Parameters of module and children will start with prefix. We can exit early if there are none in this
        # state_dict
        if len([key for key in state_dict if key.startswith(prefix)]) > 0:
            # In sharded models, each shard has only part of the full state_dict, so only gather
            # parameters that are in the current state_dict.
            named_parameters = dict(module.named_parameters(prefix=prefix[:-1], recurse=False))
            params_to_gather = [named_parameters[k] for k in state_dict.keys() if k in named_parameters]
            if len(params_to_gather) > 0:
                # because zero3 puts placeholders in model params, this context
                # manager gathers (unpartitions) the params of the current layer, then loads from
                # the state dict and then re-partitions them again
                with deepspeed.zero.GatheredParameters(params_to_gather, modifier_rank=0):
                    if torch.distributed.get_rank() == 0:
                        module._load_from_state_dict(*args)
            else:
                module._load_from_state_dict(*args)

        for name, child in module._modules.items():
            if child is not None:
                load(child, state_dict, prefix + name + ".")

    load(model_to_load, state_dict, prefix=start_prefix)
    # Delete `state_dict` so it could be collected by GC earlier. Note that `state_dict` is a copy of the argument, so
    # it's safe to delete it.
    del state_dict

    return error_msgs
```

**Comment by tjruwase** [comment]
@bigeagle, apologies for the delayed response. The out-of-context model construction does not work because the model would already be created and OOMed before zero gets a chance to partition the parameters. Apologies if our docs suggested otherwise, please point out these docs so they can be fixed. 

I don't fully understand the issue you experienced with finetuning and `meta` parameters. However, zero3 has been well used for [finetuning](https://www.philschmid.de/fine-tune-flan-t5-deepspeed) and [inference](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-zero-inference.py), so it would be good to understand how your scenario is different. 

It sounds like you may have workaround already. However, if you want us to repro this issue, could you please share the failing finetuning code and stack trace?

**Comment by bigeagle** [comment]
> I don't fully understand the issue you experienced with finetuning and meta parameters. However, zero3 has been well used for [finetuning](https://www.philschmid.de/fine-tune-flan-t5-deepspeed) and [inference](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-zero-inference.py), so it would be good to understand how your scenario is different.

Basically I want to avoid using any `Trainer` classes and use vanilla pytorch and deepspeed as much as possible. 

`transformer`'s `from_pretrain` method has the correct state_dict loading when zero3 is enabled, but it ONLY works with it's own `Trainer`. I cherry-picked the correct code, so my problem got solved.

My device is 2080Ti with 11GB memory, so I guess many existing examples (tested with at least 24GB memory) may fail in my environment.  :smile:

Up to now, I have successfully fine-tuned Llama-13B on 2080Ti at fp16+zero3+cpu_offload with batch_size=8 and block_size=512, this may be helpful to many other folks. I will tidy up the code and start a PR on DeepspeedExamples.

**Comment by tjruwase** [comment]
> So far I have successfully fine-tuned Llama-13B on 2080Ti at fp16+zero3+cpu_offload with batch_size=8 and block_size=512, this may be helpful to many other folks. I will tidy up the code and start a PR on DeepspeedExamples.

Wow!!! That is amazing! We would definitely appreciate this significant contribution.
