### ISSUE TITLE
[Inference] mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by satpalsr** [microsoft/DeepSpeed#3130]
During Inference with Auto Tensor Parallelism, the inference may fail for Multi GPUs with error: 
```
output = torch.matmul(input, self.weight.transpose(-1, -2))
RuntimeError: mat1 and mat2 shapes cannot be multiplied
```
A possible cause for which is wrong policy determined by ATP.

Example
```
import os
import deepspeed
import torch
from transformers import pipeline
from transformers import GPTNeoXLayer

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))
generator = pipeline('text-generation', model = "EleutherAI/pythia-70m-deduped-v0",
                     device=local_rank)

generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.float,
                                           replace_with_kernel_inject=False,
                                           )

string = generator("DeepSpeed is", do_sample=True, min_length=20)
if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(string)
```
run this with
`deepspeed --num_gpus 2 pythiagen.py`

This gives the same above error because injection policy determined by ATP is only `mlp.dense_4h_to_h`
However correct policy should also include `attention.dense`.
This works fine with custom policy `injection_policy= {GPTNeoXLayer: ('attention.dense','mlp.dense_4h_to_h')}`

**Expected behavior**
ATP should work fine or  raise error message on failure to determine correct policy.

**Comment by sooftware** [comment]
I have a same problem too.

```python
from deepspeed.module_inject.replace_policy import GPTNEOXLayerPolicy

model = deepspeed.init_inference(
    model,
    mp_size=2,
    dtype=torch.float16,
    injection_policy={GPTNeoXLayer: (GPTNEOXLayerPolicy, )}
).module
```

**Comment by satpalsr** [comment]
I have shared a workaround
`injection_policy= {GPTNeoXLayer: ('attention.dense','mlp.dense_4h_to_h')}`

This doesn't works?

**Comment by sooftware** [comment]
It works. Thank you!

**Comment by molly-smith** [comment]
Hi @satpalsr and @sooftware, it seems this issue was fixed. The latest version of DeepSpeed produces the correct injection policy. 

`AutoTP:  [(<class 'transformers.models.gpt_neox.modeling_gpt_neox.GPTNeoXLayer'>, ['mlp.dense_4h_to_h', 'attention.dense'])]`
