### ISSUE TITLE
[BUG]zero3 in torch.nn.functional.linear

### ISSUE THREAD

**Issue by fengyh3** [microsoft/DeepSpeed#3144]
using zero3 report an error when zero1 and 2 work:
TypeError: apply() takes no keyword arguments.

the final position of trace log:
import torch.nn.functional.linear as F
...
result = F.linear(x, T(self.weights), bias=self.bias)

version: deepspeed 0.8.3

**Comment by tjruwase** [comment]
Closing due to no response. Please re-open as needed.
