### ISSUE TITLE
[BUG] Unable to pre-compile async_io

### ISSUE THREAD

**Issue by littleshao** [microsoft/DeepSpeed#3211]
pip install setup.py

but

`Processing d:\python\deepspeed
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\python\DeepSpeed\setup.py", line 157, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "D:\python\DeepSpeed\setup.py", line 51, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
      [93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
      [93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      [93m [WARNING] [0m One can disable async_io with DS_BUILD_AIO=0
      [31m [ERROR] [0m Unable to pre-compile async_io`

**Comment by mrwyattii** [comment]
@littleshao are you installing on a Windows OS? asyncio is not supported on Windows.

**Comment by littleshao** [comment]
> async_io

oh，，，thx

**Comment by tjruwase** [comment]
Closing for now.
