### ISSUE TITLE
[BUG]pip install deepspeed install fail

### ISSUE THREAD

**Issue by expresschen** [microsoft/DeepSpeed#3213]
**Describe the bug**
pip install deepspeed install fail
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/18161256/231719396-f9681f64-e0b3-4380-862e-48c9a653a98b.png">
<img width="961" alt="image" src="https://user-images.githubusercontent.com/18161256/231719969-abb95239-a1d7-4a67-892a-340a3485a98e.png">

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [centos]
 - GPU count and types 4*v100
 - Python version 3.10
 - cuda 12.0

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by expresschen** [comment]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/18161256/231719742-3cb9e0fe-a0ab-4979-b396-28f7a96bf35f.png">

**Comment by mrwyattii** [comment]
Hi @expresschen, could you please check if you are able to use CUDA with pytorch in your environment?
`python3 -c "import torch; print(torch.Tensor([0]).to('cuda:0'))"`

**Comment by z-x-x136** [comment]
> 你好@expresschen，请检查您是否能够在您的环境中将CUDA与pytorch一起使用？ `python3 -c "import torch; print(torch.Tensor([0]).to('cuda:0'))"`

I'm going to start with python3 -c "import torch; print(torch.Tensor([0]).to('cuda:0'))" and enter pip install deepspeed, but this is still an error

**Comment by expresschen** [comment]
cuda_home path configuration error
