### ISSUE TITLE
[REQUEST] Please spend more time on the usability of the project, especially the doc.

### ISSUE THREAD

**Issue by tbwork** [microsoft/DeepSpeed#3220]
Why is the documentation for such a great project so poor? It's just like the Windows operating system - it took decades of updates before Windows 11 finally caught up a little bit with MacOS. Your documentation lacks any logical structure, it's like a bunch of emotionally unintelligent engineers wrote it. I strongly suggest studying the open-source project Alpaca: https://github.com/cocktailpeanut/dalai. Spend more time on the usability of the project, because releasing something half-baked will only make all users suffer.

**Comment by mrwyattii** [comment]
We appreciate the feedback and we recognize that our documentation could be improved. Could you provide some examples of where our documentation is the worst? We love working on improving all aspects of DeepSpeed!

**Comment by ianpurton** [comment]
I can provide some feedback. Go to https://www.deepspeed.ai/ it's just a list of news.

It doesn't say what the project does or how to work with it.

Then if I click tutorials there doesn't seem to be a structure you have to scroll down to find a 'Getting Started' tutorial.

Hope this helps.
