### ISSUE TITLE
[BUG] Megatron-LM with DeepSpeed training, get stuck in the _exec_schedule function

### ISSUE THREAD

**Issue by Zhang-kg** [microsoft/DeepSpeed#3241]
**Describe the bug**
When training the Megatron-LM model with DeepSpeed, if I set the global batch size to 16, it will get stuck in the _exec_schedule function in deepspeed/runtime/pipeline/engine.py. However, if I set the global batch size to 8, the training will start normally.
**To Reproduce**
envirment:
python==3.9.7
pip ==21.2.4
torch==1.10.1
torchvision==0.11.2
deepspeed==0.5.10
apex==0.1

**ds_report output**
Please run `ds_report` to give us details about your setup.
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/zkg/anaconda3/envs/megatron/lib/python3.9/site-packages/torch']
torch version .................... 1.10.1
torch cuda version ............... 11.3
nvcc version ..................... 11.3
deepspeed install path ........... ['/home/zkg/anaconda3/envs/megatron/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.5.10, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.10, cuda 11.3
```
**Screenshots**
debugging info in `deepspeed/runtime/pipe/engine.py` 
![image](https://user-images.githubusercontent.com/70781420/232185010-2f184b05-a24e-42b7-b597-079f8ff63bb0.png)
when traning with global batch size == 16
![image](https://user-images.githubusercontent.com/70781420/232184479-e223a9bc-1d99-4a07-9298-487ea287f049.png)
but when training with global batch size == 8(both changing the deepspeed.json and the sh file), the training will start normally
![image](https://user-images.githubusercontent.com/70781420/232185327-59f4f6e5-0018-4a6a-bbda-27c65b9e4321.png)

**System info (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - GPU count and types: two machines with 2 A100s each
 - Interconnects: two machines connected with IB
 - Python version: 3.9.7

**Launcher context**
sh file:
```sh
#! /bin/bash
NODE_RANK=0
NNODES=2
GPUS_PER_NODE=2
MASTER_PORT=22
MASTER_ADDR=10.xx.xx.19
DISTRIBUTED_ARGS="--nproc_per_node $GPUS_PER_NODE --nnodes $NNODES --node_rank $NODE_RANK --master_addr $MASTER_ADDR --master_port $MASTER_PORT"

DATETIME=`date +'date_%y-%m-%d_time_%H-%M-%S'`
TENSORBOARD_PATH=./tensorboard/$DATETIME

config_json="deepspeed.json"
VOCAB_FILE=vocab.txt
DATASET_1="xxx/001.txt_document_context"
DATASET_2="xxx/002.txt_document_context"
DATASET_3="xxx/003.txt_document_context"
DATASET_4="xxx/004.txt_document_context"
DATASET_5="xxx/005.txt_document_context"
DATASET_6="xxx/006.txt_document_context"
DATASET_7="xxx/007.txt_document_context"
DATASET_8="xxx/008.txt_document_context"
DATASET_9="xxx/009.txt_document_context"
DATASET_10="xxx/010.txt_document_context"
DATA_PATH=" \
        0.1 ${DATASET_1} \
        0.1 ${DATASET_2} \
        0.1 ${DATASET_3} \
        0.1 ${DATASET_4} \
        0.1 ${DATASET_5} \
        0.1 ${DATASET_6} \
        0.1 ${DATASET_7} \
        0.1 ${DATASET_8} \
        0.1 ${DATASET_9} \
        0.1 ${DATASET_10}"

gpt_options="\
        --distributed-backend nccl \
        --tokenizer-type EncDecTokenizer \
        --optimizer lamb \
        --lr-decay-style cosine \
        --vocab-file $VOCAB_FILE \
        --tensor-model-parallel-size 2 \
        --num-layers 40 \
        --train-samples 10024 \
        --hidden-size 3072 \
        --num-attention-heads 24 \
        --seq-length 2048 \
        --max-position-embeddings 2048 \
        --micro-batch-size 1 \
        --global-batch-size 16 \
        --lr-warmup-samples 1024 \
        --lr 5e-3 \
        --min-lr 1e-05 \
        --weight-decay 0.0005 \
        --adam-beta1 0.9 \
        --adam-beta2 0.95 \
        --log-interval 1 \
        --eval-iters -1 \
        --data-path ${DATA_PATH} \
        --save-interval 2000 \
        --split 100,0,0 \
        --init-method-std 0.002 \
        --fp16 \
        --DDP-impl local \
        --checkpoint-num-layers 1 \
        --log-num-zeros-in-grad \
        --log-params-norm \
        --tensorboard-dir $TENSORBOARD_PATH \
        --tensorboard-log-interval 1 \
        --num-workers 8 \
        --pipeline-model-parallel-size 2
"
deepspeed_options=" \
        --deepspeed \
        --deepspeed_config ${config_json} \
        --zero-stage 1 \
        --deepspeed-activation-checkpointing
"
full_options="${gpt_options} ${deepspeed_options}"
deepspeed --hostfile="xxx/model/hostfile" --num_nodes ${NNODES} --num_gpus ${GPUS_PER_NODE}  ./pretrain_gpt.py ${full_options}
```
deepspeed json file:
``` json
{
  "train_batch_size": 8,
  "steps_per_print": 1,
  "zero_optimization": {
     "stage": 1
  },
  "aio": {
    "block_size": 1048576,
    "queue_depth": 8,
    "thread_count": 1,
    "single_submit": false,
    "overlap_events": true
  },
  "gradient_clipping": 1.0,
  "bf16": {
    "enabled": false
  },
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "tensorboard": {
    "enabled": false,
    "output_path": "./tensorboard/test",
    "job_name": "train_bert"
  },
  "wall_clock_breakdown": false,
  "zero_allow_untested_optimizer": true
}
```
**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by hemangjoshi37a** [comment]
Here is a suggested solution:

1. Verify resource availability: Ensure that there are enough resources (such as GPU memory) to handle a global batch size of 16. Since training is working with a batch size of 8, it could be an indication of insufficient resources.

2. Check for bottlenecks: It's possible that certain pipeline stages are causing a bottleneck when the global batch size is increased to 16. You can try profiling the execution of the pipeline stages to identify any potential bottlenecks.

3. Adjust the pipeline model parallelism: The current configuration has a pipeline-model-parallel-size of 2. You can experiment with different values for this parameter to see if it helps with the training when using a global batch size of 16.

4. Update DeepSpeed: Make sure you're using the latest version of DeepSpeed. Update the package if necessary, as newer versions may have bug fixes or performance improvements.

5. Monitor GPU utilization: You can use tools like NVIDIA's nvidia-smi or nvtop to monitor GPU utilization during training. This can help you identify any potential issues with GPU utilization when using a global batch size of 16.

6. Check for deadlocks: DeepSpeed uses various synchronization primitives like barriers and events. It's possible that a deadlock is occurring with a global batch size of 16. To debug this, you can add print statements or use a debugger to monitor the execution flow of the _exec_schedule function and identify where it is getting stuck.

After trying these steps, if the issue persists, it would be helpful to provide more information in this GitHub issue, such as detailed logs, profiling results, and any additional observations made during debugging. This will help the DeepSpeed maintainers in identifying the root cause and providing a more specific solution.

**Comment by Zhang-kg** [comment]
@hemangjoshi37a Thank you very much. I will try your suggestions, and if there are any further questions, I will provide more information in the issue

**Comment by Yuhanleeee** [comment]
Thank you for your efforts @Zhang-kg and @hemangjoshi37a, may I ask how to solve this problem? I meet the same issue with CUDA 12.2, NCCL 2.20.5, GCC 10.2, PyTorch 2.3.1, Deepspeed 0.12.4+02e2ebf, Python 3.8.19, GPU 4xA100-SXM4-40GB, CPU AMD EPYC 7543 32-Core  Processor, Memory 195607748 kB(free).

Thanks again for your time and patience. Looking forward to your reply.
