### ISSUE TITLE
希望有大神可以做出AI版的系统盘，方便普通用户安装使用

### ISSUE THREAD

**Issue by cloudheap** [microsoft/DeepSpeed#3252]
感觉 DeepSpeed Chat 框架部署太复杂，普通用户使用困难。希望有大神可以做出AI版的系统盘，方便普通用户安装使用。
可以搞个社区，像Kali Linux一样，社区高手负责DeepSpeed Chat 框架的维护，解决硬件兼容性问题、软件依赖问题，简化安装部署。
将框架与套件分开，类似Android一样，框架只负责基本功能，套件负责扩展，像Android APP一样。安装文字处理套件，可以处理文字，最好可以支持API功能，方便其它平台的APP调用AI文字处理功能。安装图片处理套件，可以处理图片。安装视频套件，可以处理视频。这样一来方便套件更新迭代，二来减少系统安装后的体积。
AI系统中也可以集成模型商店，方便用户出售、购买他人的AI模型。
希望能有云服务器商可以支持这套AI系统。大家共用一套硬件降低成本，软件使用虚拟环境分隔，用户可以自由增减套件定制符合自己需求的AI。

**Comment by cyborg42** [comment]
docker pull deepspeed/deepspeed
