### ISSUE TITLE
Effect of if(model_engine.device==torch.device('cuda:0'))

### ISSUE THREAD

**Issue by rsn870** [microsoft/DeepSpeed#328]
Hi , 

Consider the following snippet 
losses , encode_lst = model_engine(inputs,mean_style,latent_rnd,mode='train')
if(model_engine.device==torch.device('cuda:0')):
			writer.add_scalar('Loss/Latent_Style', losses[0], i+1)
			writer.add_scalar('Loss/Image' , losses[1] , i+1)
			writer.add_scalar('Loss/Self_Consistent_Encoder' , losses[2] , i+1)

Does setting model_engine.device = 0 give only the the losses computed from GPU :0 or the losses avaeraged from all GPUs ?

**Comment by tjruwase** [comment]
@rsn870 Is it okay to close this issue?

**Comment by rsn870** [comment]
Sure , thanks for your response . I have confirmed your assertion
