### ISSUE TITLE
[BUG] Unable to use sharded checkpoints with LoRA model

### ISSUE THREAD

**Issue by shaankhosla** [microsoft/DeepSpeed#3291]
**Describe the bug**
When using [LoRA](https://github.com/huggingface/peft) and DeepSpeed, there is an error loading converting the checkpoint weights into a single model file, and loading in the state dict.

**To Reproduce**
1. Clone https://github.com/shaankhosla/NLP_with_LLMs/tree/load_deepspeed_ckpt
2. Run `python train.py` after downloading requirements
3. Error is on line 187 when trying to load the state dict

**Expected behavior**
The state dict should be returned from `load_state_dict_from_zero_checkpoint`

**Error**

Generating synthetic dataset (100 train, 20 val)...
/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5_fast.py:155: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-small automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(
trainable params: 294912 || all params: 60801536 || trainable%: 0.4850403779272945
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
initializing deepspeed distributed: GLOBAL_RANK: 0, MEMBER: 1/2
Generating synthetic dataset (100 train, 20 val)...
/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5_fast.py:155: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-small automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(
trainable params: 294912 || all params: 60801536 || trainable%: 0.4850403779272945
initializing deepspeed distributed: GLOBAL_RANK: 1, MEMBER: 2/2
Enabling DeepSpeed FP16.
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Using /home/paperspace/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Using /home/paperspace/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Emitting ninja build file /home/paperspace/.cache/torch_extensions/py39_cu117/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.22510743141174316 seconds
Loading extension module utils...
Time to load utils op: 0.10208249092102051 seconds
Parameter Offload: Total persistent parameters: 311808 in 106 params
Using /home/paperspace/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0005269050598144531 seconds
Using /home/paperspace/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.00046634674072265625 seconds

  | Name  | Type                  | Params | Params per Device
--------------------------------------------------------------------
0 | model | PeftModelForSeq2SeqLM | 60.8 M | 30.4 M           
--------------------------------------------------------------------
294 K     Trainable params
60.5 M    Non-trainable params
60.8 M    Total params
243.206   Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                | 0/4 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Epoch 0: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.66s/it, v_num=151]/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py:761: UserWarning: When saving the DeepSpeed Stage 3 checkpoint, each worker will save a shard of the checkpoint within a directory. If a single file is required after training, see https://lightning.ai/docs/pytorch/stable/advanced/model_parallel.html#deepspeed-zero-stage-3-single-file for instructions.
  warning_cache.warn(
/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py:1802: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py:1802: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
`Trainer.fit` stopped: `max_epochs=1` reached.
Epoch 0: 100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.68s/it, v_num=151]
Device 0 : b'Quadro RTX 4000'
GPU memory occupied: 1716 MB.
Device 1 : b'Quadro RTX 4000'
GPU memory occupied: 1425 MB.
Processing zero checkpoint './output/logs/t5-small/version_151/checkpoints/epoch=0-step=1.ckpt/checkpoint'
Detected checkpoint of type zero stage 3, world_size: 2
Device 0 : b'Quadro RTX 4000'
GPU memory occupied: 1716 MB.
Device 1 : b'Quadro RTX 4000'
GPU memory occupied: 1425 MB.
Processing zero checkpoint './output/logs/t5-small/version_151/checkpoints/epoch=0-step=1.ckpt/checkpoint'
Detected checkpoint of type zero stage 3, world_size: 2
Parsing checkpoint created by deepspeed==0.9.0
Traceback (most recent call last):
  File "/home/paperspace/NLP_with_LLMs/train.py", line 213, in <module>
  File "/home/paperspace/NLP_with_LLMs/train.py", line 188, in start_training
    model = load_state_dict_from_zero_checkpoint(trainer.model, ckpt_path)
  File "/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 437, in load_state_dict_from_zero_checkpoint
    state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
  File "/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 388, in get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
  File "/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 180, in _get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero3_checkpoint(world_size, param_shapes, fp32_flat_groups, buffers,
  File "/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 335, in _get_fp32_state_dict_from_zero3_checkpoint
    state_dict[pair[0]] = state_dict[pair[1]]
KeyError: '_forward_module.model.base_model.model.encoder.embed_tokens.weight'
Parsing checkpoint created by deepspeed==0.9.0
Traceback (most recent call last):
  File "/home/paperspace/NLP_with_LLMs/train.py", line 213, in <module>
  File "/home/paperspace/NLP_with_LLMs/train.py", line 188, in start_training
    model = load_state_dict_from_zero_checkpoint(trainer.model, ckpt_path)
  File "/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 437, in load_state_dict_from_zero_checkpoint
    state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
  File "/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 388, in get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
  File "/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 180, in _get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero3_checkpoint(world_size, param_shapes, fp32_flat_groups, buffers,
  File "/home/paperspace/.cache/pypoetry/virtualenvs/nlp-with-llms-sfgRzLAF-py3.9/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 335, in _get_fp32_state_dict_from_zero3_checkpoint
    state_dict[pair[0]] = state_dict[pair[1]]
KeyError: '_forward_module.model.base_model.model.encoder.embed_tokens.weight'

**Comment by shaankhosla** [comment]
@tjruwase

**Comment by ShijieZZZZ** [comment]
Looks like similar issue observed [here](https://github.com/microsoft/DeepSpeed/pull/3295#issuecomment-1513800129). Will take a look.

**Comment by ShijieZZZZ** [comment]
Hi @shaankhosla, with this [PR](https://github.com/microsoft/DeepSpeed/pull/3149) merged, could you try again?
