### ISSUE TITLE
[REQUEST] Can I use this method to load pretrained weights for the PipelineModule before deepspeed.initialize()

### ISSUE THREAD

**Issue by zte-tcb** [microsoft/DeepSpeed#3297]
hello, i want to load pretrained weights for PipelineModule. i build a PipelineModule model, and **i only have layer_*-model_states.pt in chpt_path** (not have mp_rank_*_model_states.pt), so i use load_state_dir(chpt_path) to load pretrained weights, and not use load_checkpoint(). Next i do deepspedd.initialize. The code like this:

net = PipelineModule()
net.load_state_dir(chpt_path, torch_checkpoint_engine)
engine, _, _, _ = deepspeed.initialize(
        args=args,
        model=net,
        model_parameters=[p for p in net.parameters() if p.requires_grad],
        training_data=trainset)

i want to know:
1、This way to load pretrained weights for PipelineModule is right? I am worried that this method is loaded without using information in mp_rank_*_model_states.pt.
2、If I also use this method to load pretrained weights, is this method still right?  this i worried that i not load weights without  zero_pp_rank_*_optim_states.pt

**Comment by tjruwase** [comment]
@zte-tcb, it depends on whether you are doing inference, finetuning, or training. 

It is probably okay to omit `mp_rank*` files since the weights are in `layer_*` files. However, the optimizer state is in `zero_pp*` files, so excluding those could be a problem if you need optimizer state for training.

**Comment by zte-tcb** [comment]
@tjruwase After experiments, I found that executed net.load_state_dir first before deepSpeed.initialize, The weight in Optimizer will be loaded weights. Otherwise, the weight is random.   This means that when loading Pretraied Weights, you can not need to load zero_pp_rank_optim_states.pt. DeepSpeed has already clone the current weight in the model to Optimizer.
