### ISSUE TITLE
[BUG] Unstable output for text generation

### ISSUE THREAD

**Issue by frankxyy** [microsoft/DeepSpeed#3301]
It seems that for deepspeed inference the beam size is 1. However, when I run opt-30b for inference, the generated text changed for the same input.

**Comment by mrwyattii** [comment]
Hi @frankxyy - could you please provide some code to replicate this behavior? One thing to note is that you should set `do_sample=False` when making calls to `model.generate()` or `pipeline()` objects. This will ensure that the same output is produced each time an input is encountered.

**Comment by frankxyy** [comment]
@mrwyattii  get it, thanks
