### ISSUE TITLE
Mention default launcher value in the help menu

### ISSUE THREAD

**Issue by zois-tasoulas** [microsoft/DeepSpeed#3326]
Could you please add the launcher default value in the help menu?

https://github.com/microsoft/DeepSpeed/blob/ab1d2f826b5e1365b9e68b59e4d13e27c6f1065e/deepspeed/launcher/runner.py#L117

**Comment by mrwyattii** [comment]
@zois-tasoulas I've added the defaults to the message printed with `deepspeed --help` in #3347. Can you confirm that works for you?

**Comment by zois-tasoulas** [comment]
Installed from source, the default values are now present on the help menu.
Thanks for implementing this!
