### ISSUE TITLE
[BUG] AssertionError: Unable to pre-compile ops without torch installed. 

### ISSUE THREAD

**Issue by JerryAllison** [microsoft/DeepSpeed#3329]
Issue with installing DeepSpeed, "pip install deepspeed" resulted in the following error:

![image](https://user-images.githubusercontent.com/5206758/233519640-f59e04b8-60e8-41cd-be6d-bb43e7adeee7.png)

**System info (please complete the following information):**
 - OS: [Windows 11 22H2]
 - GPU count and types [GTX 1060 6GB]

 - Python 3.10.5
torch                  2.0.0+cu118
torchaudio         2.0.1+cu118
torchvision         0.15.1+cu118

pls help me.

**Comment by JerryAllison** [comment]
add:
![image](https://user-images.githubusercontent.com/5206758/233572474-b582b9ee-a1f9-4289-a851-4d53c897968d.png)
My PyTorch can be imported normally, but when I try to pip install DeepSpeed, it always prompts that it cannot import torch.

**Comment by tjruwase** [comment]
Typo:  im**n**port -> import

<img width="164" alt="image" src="https://user-images.githubusercontent.com/4271600/233713147-2f26e3f6-f8b8-4f49-9556-d8b2fe403cd8.png">

**Comment by mrwyattii** [comment]
@JerryAllison I suspect you are using `pip>=23.1`? A recent change in pip makes it so the default behavior is to build in an isolated environment. This means DeepSpeed will not find `torch`. You can fix this by doing `pip install . --no-build-isolation`. We will update our docs to reflect this.

**Comment by JerryAllison** [comment]
thank, But there were other warnings appearing.

![image](https://user-images.githubusercontent.com/5206758/233757365-f5a84a2a-f0da-455a-b28a-0bef4b19f190.png)

**Comment by AngelTs** [comment]
> pip install . --no-build-isolation

Same error here

**Comment by KbKev78** [comment]
Can confirm. I had the same torch error, then used  --no-build-isolation to get past it. The deepspeed install then couldn't find libaio, so I installed that. Now I get the same error as JerryAllison.

For me, pip -V returns "pip 23.1.1"

**Comment by mrwyattii** [comment]
@JerryAllison It looks like you are trying to install on Windows? It can be a little tricky to get DeepSpeed installed on Windows (but it is possible). We highly recommend using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) and installing DeepSpeed in that environment.

However, if you don't want to use WSL: The error you are seeing now is related to libaio not being available for Windows. You must disable pre-compilation of these features with `set DS_BUILD_AIO=0`.

**Comment by mrwyattii** [comment]
@AngelTs and @KbKev78 can you please provide some additional information about your environments? Are you also trying to install on Windows? Thanks

**Comment by KbKev78** [comment]
> @JerryAllison It looks like you are trying to install on Windows? It can be a little tricky to get DeepSpeed installed on Windows (but it is possible). We highly recommend using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) and installing DeepSpeed in that environment.
> 
> However, if you don't want to use WSL: The error you are seeing now is related to libaio not being available for Windows. You must disable pre-compilation of these features with `set DS_BUILD_AIO=0`.

Correct. In my case I am installing in Windows. Where does the "set DS_BUILD_AIO=0" option go/ Is it an environment variable?

**Comment by KbKev78** [comment]
I found a resource elsewhere with this syntax: $env:DS_BUILD_OPS = 0, which appeared to do the trick.

This has got me to the next issue: sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0

So I'm off to try and arrange that.

**Comment by AngelTs** [comment]
> @AngelTs and @KbKev78 can you please provide some additional information about your environments? Are you also trying to install on Windows? Thanks

Windows 10 Pro [22H2] [19045.2846], GTX 1060 6GB, pip 23.1, python 3.10.150.0

**Comment by mrwyattii** [comment]
> I found a resource elsewhere with this syntax: $env:DS_BUILD_OPS = 0, which appeared to do the trick.
> 
> This has got me to the next issue: sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
> 
> So I'm off to try and arrange that.

@KbKev78 If you don't need sparse attention for your install, you can also disable that with `DS_BUILD_SPARSE_ATTN=0` (similar to what you did with `DS_BUILD_AIO=0`). You can find the full list of environment variables that change installation behavior here: https://www.deepspeed.ai/tutorials/advanced-install/

**Comment by mrwyattii** [comment]
@alnrott and @AngelTs can you please try setting the following environment variables and try installing again?
```
DS_BUILD_AIO=0
DS_BUILD_SPARSE_ATTN=0
```

**Comment by AngelTs** [comment]
> @alnrott and @AngelTs can you please try setting the following environment variables and try installing again?
> 
> ```
> DS_BUILD_AIO=0
> DS_BUILD_SPARSE_ATTN=0
> ```

After executing of "python setup.py bdist_wheel" the error is:

csrc/transformer/inference/csrc/pt_binding.cpp(536): error C2398: Element '1': conversion from 'size_t' to '_Ty' requires a narrowing conversion
        with
        [
            _Ty=int64_t
        ]
csrc/transformer/inference/csrc/pt_binding.cpp(1809): note: see reference to function template instantiation 'std::vector<at::Tensor,std::allocator<at::Tensor>> ds_softmax_context<float>(at::Tensor &,at::Tensor &,int,bool,bool,int,float,bool,bool,int,bool,unsigned int,unsigned int,at::Tensor &)' being compiled
csrc/transformer/inference/csrc/pt_binding.cpp(537): error C2398: Element '2': conversion from 'size_t' to '_Ty' requires a narrowing conversion
        with
        [
            _Ty=int64_t
        ]
csrc/transformer/inference/csrc/pt_binding.cpp(545): error C2398: Element '1': conversion from 'size_t' to '_Ty' requires a narrowing conversion
        with
        [
            _Ty=int64_t
        ]
csrc/transformer/inference/csrc/pt_binding.cpp(546): error C2398: Element '2': conversion from 'size_t' to '_Ty' requires a narrowing conversion
        with
        [
            _Ty=int64_t
        ]
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

C:\DeepSpeed-master>

**Comment by AngelTs** [comment]
The not so good but working solution about above errors if use already created [deepspeed-0.8.3+6eca037c-cp310-cp310-win_amd64.whl](https://github.com/microsoft/DeepSpeed/issues/2588#issuecomment-1502628005). In this case i succeeded to install DeepSpeed on Windows 10 without WSL or Anaconda, Miniconda, Maxiconda, bonbona  and other shits ...
pip install deepspeed-0.8.3+6eca037c-cp310-cp310-win_amd64.whl

**Comment by AngelTs** [comment]
Here is a quick tutorial how to compile on clean Windows 10 without any shits like WSL, XXXconda, dockers, mokers, fuckers, etc.:
1.Copy the DeepSpeed-master.zip in the root of C dirve
2.In file pt_binding.cpp must replace four lines:
present
                                     {hidden_dim * InferenceContext::Instance().GetMaxTokenLenght(),
                                      k * InferenceContext::Instance().GetMaxTokenLenght(),
                         {hidden_dim * InferenceContext::Instance().GetMaxTokenLenght(),
                          k * InferenceContext::Instance().GetMaxTokenLenght(),
with
                                     {static_cast<int64_t>(hidden_dim * InferenceContext::Instance().GetMaxTokenLenght()),
                                      static_cast<int64_t>(k * InferenceContext::Instance().GetMaxTokenLenght()),
                         {static_cast<int64_t>(hidden_dim * InferenceContext::Instance().GetMaxTokenLenght()),
                          static_cast<int64_t>(k * InferenceContext::Instance().GetMaxTokenLenght()),
3.Then start build_win.bat
4.Go in dist directory and install just created whl file. In my case the synaxis is:
pip install deepspeed-0.9.2+unknown-cp310-cp310-win_amd64.whl

**Comment by GalaxyHe2023** [comment]
Deepspeed do not support windows,please use wsl.I got the same error ,and very easy to fix it by use wsl. https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by llaichiyu** [comment]
> Deepspeed do not support windows,please use wsl.I got the same error ,and very easy to fix it by use wsl. https://docs.microsoft.com/en-us/windows/wsl/install-win10

Thanks,I have tried to download wsl on windows and install.I hope wsl can work.

**Comment by llaichiyu** [comment]
> installing DeepSpeed
i have already install wsl and how can i use wsl to install DeepSpeed ?thank you~

**Comment by llaichiyu** [comment]
> @JerryAllison It looks like you are trying to install on Windows? It can be a little tricky to get DeepSpeed installed on Windows (but it is possible). We highly recommend using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) and installing DeepSpeed in that environment.
> 
> However, if you don't want to use WSL: The error you are seeing now is related to libaio not being available for Windows. You must disable pre-compilation of these features with `set DS_BUILD_AIO=0`.

i have already install wsl and how can i use wsl to install DeepSpeed ?thank you~

**Comment by llaichiyu** [comment]
> DS_BUILD_AIO=0
> DS_BUILD_SPARSE_ATTN=0

where should i set the two params?

**Comment by llaichiyu** [comment]
> @alnrott and @AngelTs can you please try setting the following environment variables and try installing again?
> 
> ```
> DS_BUILD_AIO=0
> DS_BUILD_SPARSE_ATTN=0
> ```

DS_BUILD_AIO=0
DS_BUILD_SPARSE_ATTN=0

**where should i set the two params?**

**Comment by llaichiyu** [comment]
> Issue with installing DeepSpeed, "pip install deepspeed" resulted in the following error:
> 
> ![image](https://user-images.githubusercontent.com/5206758/233519640-f59e04b8-60e8-41cd-be6d-bb43e7adeee7.png)
> 
> **System info (please complete the following information):**
> 
> * OS: [Windows 11 22H2]
> * GPU count and types [GTX 1060 6GB]
> * Python 3.10.5
>   torch                  2.0.0+cu118
>   torchaudio         2.0.1+cu118
>   torchvision         0.15.1+cu118
> 
> pls help me.

**i can use this command to solve : pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118**

**Comment by maxbrunet** [comment]
I think this might be fixable by adding `torch` as a build requirement to DeepSpeed by following [PEP-518](https://peps.python.org/pep-0518/#build-system-table). Concretely, adding a `pyproject.toml` to this repo with:

```toml
[build-system]
requires = [
    "setuptools",
    "torch",
]
build-backend = "setuptools.build_meta"
```

I have not tested that yet

**Comment by ChaiJinhao** [comment]
> > Deepspeed do not support windows,please use wsl.I got the same error ,and very easy to fix it by use wsl. https://docs.microsoft.com/en-us/windows/wsl/install-win10
> 
> **Thanks,I have tried to download wsl on windows and install.I hope wsl can work.**



> > Deepspeed do not support windows,please use wsl.I got the same error ,and very easy to fix it by use wsl. https://docs.microsoft.com/en-us/windows/wsl/install-win10
> 
> **Thanks,I have tried to download wsl on windows and install.I hope wsl can work.**



> > @JerryAllison It looks like you are trying to install on Windows? It can be a little tricky to get DeepSpeed installed on Windows (but it is possible). We highly recommend using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) and installing DeepSpeed in that environment.
> > However, if you don't want to use WSL: The error you are seeing now is related to libaio not being available for Windows. You must disable pre-compilation of these features with `set DS_BUILD_AIO=0`.
> 
> **i have already install wsl and how can i use wsl to install DeepSpeed ?thank you~**

请问一下，您用这个方法下载成了吗？

**Comment by jomayeri** [comment]
Please check out the latest version of DeepSpeed for Windows compatibility.

**Comment by xingyouxin** [comment]
> Please check out the latest version of DeepSpeed for Windows compatibility.

works for me

**Comment by xirotech** [comment]
OS: Windows Server 2022 21H2
GPU: RTX 2080 Ti

------------------------------------------------------------------------------------------------------------------------
curl https://www.python.org/ftp/python/3.12.8/python-3.12.8-amd64.exe -o python.exe

python -m pip install --upgrade pip virtualenv
python -m venv DeepSpeed
DeepSpeed/Scripts/activate

pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu126
pip install deepspeed-mii

or

pip install deepspeed
------------------------------------------------------------------------------------------------------------------------

(DeepSpeed) D:\DeepSpeed\Scripts>python --version
Python 3.12.8

(DeepSpeed) D:\DeepSpeed\Scripts>pip list
Package           Version
----------------- ------------------------
filelock          3.16.1
fsspec            2024.10.0
Jinja2            3.1.4
MarkupSafe        2.1.5
mpmath            1.3.0
networkx          3.4.2
numpy             2.1.2
pillow            11.0.0
pip               24.3.1
setuptools        70.2.0
sympy             1.13.1
torch             2.7.0.dev20250120+cu126
torchaudio        2.6.0.dev20250121+cu126
torchvision       0.22.0.dev20250121+cu126
typing_extensions 4.12.2

(DeepSpeed) D:\DeepSpeed\Scripts>pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu126
Looking in indexes: https://download.pytorch.org/whl/nightly/cu126
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cu126/torch-2.7.0.dev20250120%2Bcu126-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/nightly/cu126/torchvision-0.22.0.dev20250121%2Bcu126-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/nightly/cu126/torchaudio-2.6.0.dev20250121%2Bcu126-cp312-cp312-win_amd64.whl.metadata (6.5 kB)
Collecting filelock (from torch)
  Using cached https://download.pytorch.org/whl/nightly/filelock-3.16.1-py3-none-any.whl (16 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Using cached https://download.pytorch.org/whl/nightly/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting networkx (from torch)
  Using cached https://download.pytorch.org/whl/nightly/networkx-3.4.2-py3-none-any.whl (1.7 MB)
Collecting jinja2 (from torch)
  Using cached https://download.pytorch.org/whl/nightly/jinja2-3.1.4-py3-none-any.whl (133 kB)
Collecting fsspec (from torch)
  Using cached https://download.pytorch.org/whl/nightly/fsspec-2024.10.0-py3-none-any.whl (179 kB)
Collecting setuptools (from torch)
  Using cached https://download.pytorch.org/whl/nightly/setuptools-70.2.0-py3-none-any.whl (930 kB)
Collecting sympy==1.13.1 (from torch)
  Using cached https://download.pytorch.org/whl/nightly/sympy-1.13.1-py3-none-any.whl (6.2 MB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch)
  Using cached https://download.pytorch.org/whl/nightly/mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting numpy (from torchvision)
  Downloading https://download.pytorch.org/whl/nightly/numpy-2.1.2-cp312-cp312-win_amd64.whl (12.6 MB)
     ---------------------------------------- 12.6/12.6 MB 7.3 MB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Downloading https://download.pytorch.org/whl/nightly/pillow-11.0.0-cp312-cp312-win_amd64.whl (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 905.1 kB/s eta 0:00:00
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading https://download.pytorch.org/whl/nightly/MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl (17 kB)
Downloading https://download.pytorch.org/whl/nightly/cu126/torch-2.7.0.dev20250120%2Bcu126-cp312-cp312-win_amd64.whl (2500.2 MB)
   ---------------------------------------- 2.5/2.5 GB 7.1 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/nightly/cu126/torchvision-0.22.0.dev20250121%2Bcu126-cp312-cp312-win_amd64.whl (6.3 MB)
   ---------------------------------------- 6.3/6.3 MB 7.1 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/nightly/cu126/torchaudio-2.6.0.dev20250121%2Bcu126-cp312-cp312-win_amd64.whl (4.2 MB)
   ---------------------------------------- 4.2/4.2 MB 8.4 MB/s eta 0:00:00
Installing collected packages: mpmath, typing-extensions, sympy, setuptools, pillow, numpy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision, torchaudio
Successfully installed MarkupSafe-2.1.5 filelock-3.16.1 fsspec-2024.10.0 jinja2-3.1.4 mpmath-1.3.0 networkx-3.4.2 numpy-2.1.2 pillow-11.0.0 setuptools-70.2.0 sympy-1.13.1 torch-2.7.0.dev20250120+cu126 torchaudio-2.6.0.dev20250121+cu126 torchvision-0.22.0.dev20250121+cu126 typing-extensions-4.12.2
------------------------------------------------------------------------------------------------------------------------

(DeepSpeed) D:\DeepSpeed\Scripts>pip install deepspeed-mii
Collecting deepspeed-mii
  Using cached deepspeed_mii-0.3.1-py3-none-any.whl.metadata (21 kB)
Collecting Flask-RESTful (from deepspeed-mii)
  Using cached Flask_RESTful-0.3.10-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: Pillow in d:\deepspeed\lib\site-packages (from deepspeed-mii) (11.0.0)
Collecting Werkzeug (from deepspeed-mii)
  Using cached werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Collecting accelerate (from deepspeed-mii)
  Using cached accelerate-1.3.0-py3-none-any.whl.metadata (19 kB)
Collecting asyncio (from deepspeed-mii)
  Using cached asyncio-3.4.3-py3-none-any.whl.metadata (1.7 kB)
INFO: pip is looking at multiple versions of deepspeed-mii to determine which version is compatible with other requirements. This could take a while.
Collecting deepspeed-mii
  Using cached deepspeed_mii-0.3.0-py3-none-any.whl.metadata (21 kB)
  Using cached deepspeed_mii-0.2.4-py3-none-any.whl.metadata (21 kB)
  Using cached deepspeed_mii-0.2.3-py3-none-any.whl.metadata (21 kB)
  Using cached deepspeed_mii-0.2.2-py3-none-any.whl.metadata (21 kB)
  Using cached deepspeed_mii-0.2.1-py3-none-any.whl.metadata (21 kB)
  Using cached deepspeed_mii-0.2.0-py3-none-any.whl.metadata (20 kB)
  Using cached deepspeed_mii-0.1.3-py3-none-any.whl.metadata (19 kB)
INFO: pip is still looking at multiple versions of deepspeed-mii to determine which version is compatible with other requirements. This could take a while.
  Using cached deepspeed_mii-0.1.2-py3-none-any.whl.metadata (19 kB)
  Using cached deepspeed_mii-0.1.1-py3-none-any.whl.metadata (17 kB)
  Using cached deepspeed_mii-0.1.0-py3-none-any.whl.metadata (15 kB)
  Using cached deepspeed_mii-0.0.9-py3-none-any.whl.metadata (24 kB)
Collecting deepspeed>=0.7.6 (from deepspeed-mii)
  Using cached deepspeed-0.16.3.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      [93m [WARNING] [0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "D:\DeepSpeed\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\DeepSpeed\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\DeepSpeed\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-build-env-4txuk6_u\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-build-env-4txuk6_u\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-build-env-4txuk6_u\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-build-env-4txuk6_u\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 156, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
------------------------------------------------------------------------------------------------------------------------

(DeepSpeed) D:\DeepSpeed\Scripts>pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.16.3.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      [93m [WARNING] [0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "D:\DeepSpeed\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\DeepSpeed\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\DeepSpeed\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-build-env-585yw7k0\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-build-env-585yw7k0\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-build-env-585yw7k0\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-build-env-585yw7k0\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 156, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
