### ISSUE TITLE
[BUG]: NVCC build error

### ISSUE THREAD

**Issue by tohneecao** [microsoft/DeepSpeed#3360]
**Describe the bug**

When build transformer inference:
/usr/local/cuda-12.1/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/usr/lib/python3.7/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/usr/lib/python3.7/site-packages/deepspeed/ops/csrc/includes -isystem /usr/lib/python3.7/site-packages/torch/include -isystem /usr/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /usr/lib/python3.7/site-packages/torch/include/TH -isystem /usr/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-12.1/include -isystem /usr/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -std=c++14 -c /usr/lib/python3.7/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/apply_rotary_pos_emb.cu -o apply_rotary_pos_emb.cuda.o
/usr/lib/python3.7/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/apply_rotary_pos_emb.cu(89): error: no suitable conversion function from "__half" to "float" exists
              float q = (float)mixed_query[offset + lane];

**To Reproduce**
1. Simple inference script to reproduce
2. What packages are required and their versions
3. How to run the script
4. ...

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [YES] ...... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/lib/python3.7/site-packages/torch']
torch version .................... 1.13.1+cu117
deepspeed install path ........... ['/usr/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.9.2+297cd9ed, 297cd9ed, master
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7

**Screenshots**
![image](https://user-images.githubusercontent.com/118186560/233837267-6fcd10aa-fd44-41f4-9306-f92bfaca0829.png)

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by mrwyattii** [comment]
@tohneecao what model are you using when you see this error? Do you have a script that you can share to help us reproduce this error? Thanks!

**Comment by nieallen** [comment]
same error.

**Comment by tohneecao** [comment]
The running model is microsoft/bloom-deepspeed-inference-fp16.@mrwyattii
The problem maybe cuda version, my CUDA version is 12.1, while torch version 1.13.1+cu117。Change my cuda verison to 11.7，same as torch，problem solved.

The error happens when -D__CUDA_NO_HALF_OPERATORS -D__CUDA_NO_HALF_CONVERSIONS_ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__  are using when compile，which determined in ./usr/lib/python3.7/site-packages/torch/utils/cpp_extension.py
<img width="569" alt="截屏2023-04-26 13 54 21" src="https://user-images.githubusercontent.com/118186560/234482143-fd0b4e71-5b01-466b-86c1-c89236c6b74a.png">

**Comment by tohneecao** [comment]
> same error.

换下cuda版本，保持和torch内使用的cuda版本一致；
或者修改./usr/lib/python3.7/site-packages/torch/utils/cpp_extension.py 宏设置

**Comment by nieallen** [comment]
> > > same error.
> > 
> > 
> > 换下cuda版本，保持和torch内使用的cuda版本一致； 或者修改./usr/lib/python3.7/site-packages/torch/utils/cpp_extension.py 宏设置
> 
> 请问需要改动cpp_extension.py宏设置的什么？改成什么样子呢

注释掉COMMON_NVCC_FLAGS吗

**Comment by tohneecao** [comment]
> > > same error.
> > 
> > 
> > 换下cuda版本，保持和torch内使用的cuda版本一致； 或者修改./usr/lib/python3.7/site-packages/torch/utils/cpp_extension.py 宏设置
> 
> 请问需要改动cpp_extension.py宏设置的什么？改成什么样子呢

把-D去掉试一下

**Comment by nieallen** [comment]
> > > > same error.
> > > 
> > > 
> > > 换下cuda版本，保持和torch内使用的cuda版本一致； 或者修改./usr/lib/python3.7/site-packages/torch/utils/cpp_extension.py 宏设置
> > 
> > 
> > 请问需要改动cpp_extension.py宏设置的什么？改成什么样子呢
> 
> 把-D去掉试一下

Hi，这是我目前torch版本：
![image](https://user-images.githubusercontent.com/33852772/234514836-840c63a7-8e93-4398-a57a-c93b2987d726.png)
我的cuda版本是：
![image](https://user-images.githubusercontent.com/33852772/234515114-d4df13d2-166d-49d9-af4b-5f85b3d27fa3.png)
我应该把我torch升级成多少版本的呢？

**Comment by mrwyattii** [comment]
> The running model is microsoft/bloom-deepspeed-inference-fp16.@mrwyattii The problem maybe cuda version, my CUDA version is 12.1, while torch version 1.13.1+cu117。Change my cuda verison to 11.7，same as torch，problem solved.

Great to hear this solved your problem. We require that the CUDA major versions (e.g., 11.x or 12.x) match for compiling the custom kernels.

**Comment by nieallen** [comment]
> > > > > > same error.
> > > > > 
> > > > > 
> > > > > 换下cuda版本，保持和torch内使用的cuda版本一致； 或者修改./usr/lib/python3.7/site-packages/torch/utils/cpp_extension.py 宏设置
> > > > 
> > > > 
> > > > 请问需要改动cpp_extension.py宏设置的什么？改成什么样子呢
> > > 
> > > 
> > > 把-D去掉试一下
> > 
> > 
> > Hi，这是我目前torch版本： ![image](https://user-images.githubusercontent.com/33852772/234514836-840c63a7-8e93-4398-a57a-c93b2987d726.png) 我的cuda版本是： ![image](https://user-images.githubusercontent.com/33852772/234515114-d4df13d2-166d-49d9-af4b-5f85b3d27fa3.png) 我应该把我torch升级成多少版本的呢？
> 
> 你把cuda版本降到11.3吧，我就是这么做的

非常谢谢你！我也解决了！

**Comment by tohneecao** [comment]
> > The running model is microsoft/bloom-deepspeed-inference-fp16.@mrwyattii The problem maybe cuda version, my CUDA version is 12.1, while torch version 1.13.1+cu117。Change my cuda verison to 11.7，same as torch，problem solved.
> 
> Great to hear this solved your problem. We require that the CUDA major versions (e.g., 11.x or 12.x) match for compiling the custom kernels.

OK! Thanks for reply. I have another question, how many shm-size should i give when running ds-inference while it need NCCL

**Comment by SunQiDong1999** [comment]
> sr/lib/python3.7/site-packages/torch/utils/cpp_extension.

请问是怎么解决的呢？降级cuda？

**Comment by nieallen** [comment]
> > sr/lib/python3.7/site-packages/torch/utils/cpp_extension.
> 
> 请问是怎么解决的呢？降级cuda？

yes, cuda11.3

**Comment by mrwyattii** [comment]
Error was resolved so I'm closing this issue, please reopen or create a new issue if necessary. Thank you
