### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sequential-circuits** [microsoft/DeepSpeed#3366]
python train.py --actor-model facebook/opt-13b --reward-model facebook/opt-350m --deployment-type single_node
---=== Running Step 1 ===---
Running:
bash /root/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/training_scripts/single_node/run_13b.sh /root/DeepSpeedExamples/applications/DeepSpeed-Chat/output/actor-models/13b
Traceback (most recent call last):
  File "/root/DeepSpeedExamples/applications/DeepSpeed-Chat/train.py", line 210, in <module>
    main(args)
  File "/root/DeepSpeedExamples/applications/DeepSpeed-Chat/train.py", line 195, in main
    launch_cmd(args, step_num, cmd)
  File "/root/DeepSpeedExamples/applications/DeepSpeed-Chat/train.py", line 175, in launch_cmd
    raise RuntimeError('\n\n'.join((
RuntimeError: Step 1 exited with non-zero status 1

Launch command: bash /root/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/training_scripts/single_node/run_13b.sh /root/DeepSpeedExamples/applications/DeepSpeed-Chat/output/actor-models/13b

Log output: /root/DeepSpeedExamples/applications/DeepSpeed-Chat/output/actor-models/13b/training.log

Please see our tutorial at https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat/training/step1_supervised_finetuning

Please check that you have installed our requirements: `pip install -r requirements.txt`

If you are seeing an OOM error, try modifying /root/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/training_scripts/single_node/run_13b.sh:

  - Reduce `--per_device_*_batch_size`

  - Increase `--zero_stage {0,1,2,3}` on multi-gpu setups

**Comment by mrwyattii** [comment]
@Sequential-circuits Can you please share the output of the log file?
`Log output: /root/DeepSpeedExamples/applications/DeepSpeed-Chat/output/actor-models/13b/training.log`

**Comment by molly-smith** [comment]
Please reopen if issue still exists
