### ISSUE TITLE
How to use torch.compile in DeepSpeed?

### ISSUE THREAD

**Issue by noob-ctrl** [microsoft/DeepSpeed#3375]
If I want to use the new feature of Pytorch2.0——torch.compile, what should I do? Where should I put the following code or just pass a command line parameter?
```
model = torch.compile(model)
```

**Comment by noob-ctrl** [comment]
@c-maxey Sorry, I still don't quite get it, can you show me a simple example？

**Comment by c-maxey** [comment]
> @c-maxey Sorry, I still don't quite get it, can you show me a simple example？

Hey no problem.  Where your forward function is for your model, make it looks like the following:

@torch.compile
def forward(self, <all your other parameters here> )

**Comment by Cherryjingyao** [comment]
> > @c-maxey Sorry, I still don't quite get it, can you show me a simple example？
> 
> Hey no problem. Where your forward function is for your model, make it looks like the following:
> 
> @torch.compile def forward(self, )

did this work? I use this way, but got a bug. I guess maybe the my cuda version is 11.4 which can't surpport torch2.0 compile?
