### ISSUE TITLE
[ERROR] AttributeErrorAttributeErrorAttributeError:  'NoneType' object has no attribute 'get_tensor_model_parallel_group'

### ISSUE THREAD

**Issue by sunhaohai** [microsoft/DeepSpeed#3454]
https://github.com/microsoft/DeepSpeed/blob/d10b8ca011b18eba3a6ca56f4208a732d7fbb744/deepspeed/runtime/hybrid_engine.py#LL321C16-L321C37

Should the judgment condition be "self.mpu is None"?

**Comment by mrwyattii** [comment]
@sunhaohai yes I believe you are correct. This should be `if self.mpu is None`. I will add a PR to fix this. Thank you!

**Comment by A-baoYang** [comment]
But if change line 320 to `if self.mpu is None`, this will cause another AttributeError 
`AttributeError: 'DeepSpeedHybridEngine' object has no attribute 'mp_group'`
