### ISSUE TITLE
[BUG] Deepspeed Training with Stage 3 job hang and fail 

### ISSUE THREAD

**Issue by shaowei-su** [microsoft/DeepSpeed#3483]
**Describe the bug**

DeepSpeed training with staging 3 led to job hanging randomly with empty GPU usage on certain workers:

<img width="370" alt="Screenshot 2023-05-07 at 10 10 55" src="https://user-images.githubusercontent.com/7682657/236706113-d020fe0b-e4bb-4e45-a5e8-f5983b994d74.png">

and then later failed with runtime error:

```
7650  File "/usr/local/lib/python3.8/dist-packages/accelerate/data_loader.py", line 369, in __iter__7651    synchronize_rng_states(self.rng_types, self.synchronized_generator)7652  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/random.py", line 89, in synchronize_rng_states7653    synchronize_rng_state(RNGType(rng_type), generator=generator)7654  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/random.py", line 84, in synchronize_rng_state7655    generator.set_state(rng_state)7656RuntimeError: Invalid mt19937 state
```

**To Reproduce**

Train HF model (https://huggingface.co/docs/transformers/model_doc/gpt_neox) with 2 P4 nodes and 8 A100 each.

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

```
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch']
torch version .................... 1.13.1+cu117
deepspeed install path ........... ['/usr/local/lib/python3.8/dist-packages/deepspeed']
deepspeed info ................... 0.9.2, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7
```

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by stgzr** [comment]
Same issue.

**Comment by shaowei-su** [comment]
Thanks @loadams for helping on this issue - I did some investigation in the last few weeks and I think the root cause is related to the orchestrator (Ray Air: https://docs.ray.io/en/latest/ray-air/getting-started.html) setting the `ACCELERATE_TORCH_DEVICE` and `LOCAL_RANK` that occasionally does not match what deepspeed expects.

**Comment by shaowei-su** [comment]
Could you point me to the fixes you mentioned above?

**Comment by shaowei-su** [comment]
Hi @loadams , to reproduce the failure it requires a multi-node & multi-gpu Ray cluster setup (https://github.com/ray-project/ray). Usually the issue occurs with > 16 GPUs (a100 or a10g, this is not GPU model specific). Closing this issue since it's not rooted in deepspeed, thanks!
