### ISSUE TITLE
commerical use

### ISSUE THREAD

**Issue by janglichao** [microsoft/DeepSpeed#3496]
the chat example seems base on Facebook models，I mean,if I worked on those default steps to build own models is that allowed commercial use? What if I want to train own model

**Comment by jeffra** [comment]
Hi @janglichao, our [DeepSpeed Chat pipeline is licensed under Apache](https://github.com/microsoft/DeepSpeedExamples/blob/master/LICENSE), please see the license for more details but my understanding is that it does allow commercial use.

Our current example training recipes use OPT models which I believe would inherit the OPT license for any trained models:  https://huggingface.co/facebook/opt-1.3b/blob/main/LICENSE.md

If you use our DeepSpeed Chat pipeline with a model like [GPT-J](https://huggingface.co/EleutherAI/gpt-j-6b) that combination would produce an artifact that is (as far as I understand) commercial compatible.

This all being said, I am not a lawyer and you should review the individual licenses carefully :)

**Comment by janglichao** [comment]
> 
 thanks。
