### ISSUE TITLE
DeepSpeed not using all available GPUs

### ISSUE THREAD

**Issue by sarrahbbh** [microsoft/DeepSpeed#3515]
**Describe the bug**
Hello,
I'm trying to train a 13b language model on 2 A100 80GB GPUs using ZeRO-2, but DeepSpeed doesn't seem to be using both GPUs for the training as CUDA immediately runs out of memory after loading the model and starting the training loop.

**Expected behavior**
160GB should be more than enough to train a 13b model especially in a ZeRO-2 setting

**ds_report output**
Here's the ds_report output:
![ds report](https://github.com/microsoft/DeepSpeed/assets/128068271/1d013f33-992e-491d-815e-aa014e0a7ee6)

**Screenshots**
Here's a screenshot of the deepspeed initial logs, which indicate that indeed two CUDA devices are set:
![logs](https://github.com/microsoft/DeepSpeed/assets/128068271/a236a66c-496a-4750-b56a-777006d8fa3c)

Here's a screenshot of the CUDA memory error which indicate that not even the first GPU is used to its full capacity
![cuda](https://github.com/microsoft/DeepSpeed/assets/128068271/f41508f4-e84f-43a5-b31a-06f3a6c2ea5e)

**System info (please complete the following information):**
 - GPU count and types: one machine with 2 A100s
 - Environment: Jupyter notebook

**Launcher context**
The experiment is launched using deepspeed (`deepspeed finetune_model.py`, as all other arguments including the config file are set by default in the training file)

**Docker context**
Are you using a specific docker image that you can share? No

Your help is most appreciated! x(

**Comment by samadejacobs** [comment]
Closing, please reopen if needed.
