### ISSUE TITLE
[BUG]AttributeError: 'DeepSpeedZeRoOffload' object has no attribute 'backward'

### ISSUE THREAD

**Issue by lizhidomg** [microsoft/DeepSpeed#3516]
When I reproduce the supervised training of MOSS, the code runs to “accelerator.backward(loss)” and reports an error。
![QQ截图20230511210649](https://github.com/microsoft/DeepSpeed/assets/55686901/7492f1c9-a354-48e1-8e06-effbca7dcf0c)

**Comment by xiexbing** [comment]
@lizhidomg, can you please more detailed information about the application and the hardware/software environment you're running? thanks.

**Comment by xiexbing** [comment]
close as no response from the user, will open if requested further.
