### ISSUE TITLE
[BUG] step1 - main.py, torch.distributed.barrier() leads to "[launch.py:428:sigkill_handler] Killing subprocess 39607"

### ISSUE THREAD

**Issue by xubuvd** [microsoft/DeepSpeed#3524]
**Describe the bug**
A clear and concise description of what the bug is. Please include which training step you are using and which model you are training.

**Log output**
If you used `train.py` to launch the application, please include the contents of the output log file.

**To Reproduce**
1. Command/Script to reproduce
2. What packages are required and their versions
3. How to run the script
4. ...

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by Meimin-Wang** [comment]
I have the same problem.
Base image: pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

**Comment by molly-smith** [comment]
Hi @xubuvd, can you please fill out the template information?
