### ISSUE TITLE
[BUG]"deepspeed: command not found". Use a replicated Python environment

### ISSUE THREAD

**Issue by H9990HH969** [microsoft/DeepSpeed#3530]
My development environment could not be connected to the Internet, so I equipped the deepspeed environment on my computer and copied the python environment under the env directory directly to the development environment . But the command deepspeed is not work. 

![1683885492896](https://github.com/microsoft/DeepSpeed/assets/133352113/0753930b-3b65-40a3-8252-8881ff75201b)

**Comment by jeffra** [comment]
@H9990HH969 another option is you can download the whl directly from pypi and transfer it over to your dev machine from here: https://pypi.org/project/deepspeed/#files.

**Comment by H9990HH969** [comment]
@loadams @jeffra Thank you both. In the end, I found a way to use the deepspeed directly in the bin directory. 
Like： 
![1684114691189](https://github.com/microsoft/DeepSpeed/assets/133352113/0640b69f-3b85-45d0-9179-5e51d2c92a16)
