### ISSUE TITLE
[BUG] Failed to backward twice with ZeRO-3

### ISSUE THREAD

**Issue by KaiLv69** [microsoft/DeepSpeed#3539]
**Describe the bug**
Size mismatch when trying backward twice with ZeRO-3.

**To Reproduce**
Simple code to reproduce the behavior:
```python
config = AutoConfig.from_pretrained(args.model_name_or_path)
model = AutoModelForCausalLM.from_config(config=config)

engine, _, _, _ = deepspeed.initialize(
    config=ds_config,
    model=model,
)

tknz = AutoTokenizer.from_pretrained(args.model_name_or_path, local_files_only=True)
text = 'We are thrilled to announce the arrival of DGL 1.0'
inp = tknz(text, return_tensors='pt')

input_ids, attn_mask = inp['input_ids'].cuda(), inp['attention_mask'].cuda()
res = engine(
  input_ids=input_ids,
  attention_mask=attn_mask,
  labels=input_ids
)
res['loss'].backward(retain_graph=True)
res['loss'].backward(retain_graph=False)
```

**Screenshots**
I enabled print in ```deepspeed/runtime/zero/linear.py``` and get
<img width="1108" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/39761308/e9152348-bd74-45b0-b5e3-b5f32f962ad9">
<img width="938" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/39761308/e9ba3c3f-fd7e-4f7c-a968-9c1c63c0aac5">

Thankks in advance.

**Comment by tjruwase** [comment]
@KaiLv69, we have not tested zero-3 for scenarios of calling `backward()` multiple times on the same loss. Can you explain your scenario a bit more since it is unusual. Thanks!

**Comment by KaiLv69** [comment]
@tjruwase Thanks for your quick reply.
Well, it's a long story. I know the official backward method is to call ```engine.backward(loss)```, and I believe that I need to call ```loss.backward()``` in my scenario because I didn't define an optimizer for ```deepspeed.initialize()```. That's to say, I didn't define an optimizer and need to process with gradients (twice backward is also needed).

**Comment by tjruwase** [comment]
Try setting the following zero config to false in your ds_config:
https://deepspeed.readthedocs.io/en/latest/zero3.html#deepspeed.runtime.zero.config.DeepSpeedZeroConfig.memory_efficient_linear

**Comment by KaiLv69** [comment]
When setting memory_efficient_linear to false, it raise an error like 
```ValidationError: 1 validation error for DeepSpeedZeroConfig
memory_efficient_linear
  extra fields not permitted (type=value_error.extra)
```
And I searched the project found no param named ```memory_efficient_linear```. There is nothing about ```memory_efficient_linear ``` at https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training either.

**Comment by KaiLv69** [comment]
@tjruwase My config file looks like
<img width="557" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/39761308/255fbe2a-8348-460f-aba1-b9a22488923c">

**Comment by KaiLv69** [comment]
@tjruwase I tried to set ```memory_efficient_linear``` to False and get another error like
<img width="1019" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/39761308/0f4f4230-d46a-47d9-93e2-d0bb356a2e71">

**Comment by tjruwase** [comment]
I see that does not help. It seems to be failing for similar reason of a second backward call.

What are your expectations for the second backward call? Do you expect the same gradient values or are you expecting gradient accumulation?

**Comment by KaiLv69** [comment]
I expect the same gradient values.

**Comment by KaiLv69** [comment]
Got it. Maybe I can use
```
res = engine(
  input_ids=input_ids,
  attention_mask=attn_mask,
  labels=input_ids
)
res['loss'].backward()
res = engine(
  input_ids=input_ids,
  attention_mask=attn_mask,
  labels=input_ids
)
res['loss'].backward()
```
It costs one more forward pass.

**Comment by tjruwase** [comment]
In ZeRO-3, sharded parameters have to be reassembled (gathered) before usage on forward/backward passes. This gathering is automatically done using pytorch hooks which has a runtime cost. To hide this cost, we use prefetching to gather parameters ahead of actual usage, however this assumes a defined sequence of forward and backward. Typically, parameter shape issues in ZeRO-3 are due to failure of these hooks, which happens when any of our execution assumptions are violated.

**Comment by KaiLv69** [comment]
> In ZeRO-3, sharded parameters have to be reassembled (gathered) before usage on forward/backward passes. This gathering is automatically done using pytorch hooks which has a runtime cost. To hide this cost, we use prefetching to gather parameters ahead of actual usage, however this assumes a defined sequence of forward and backward. Typically, parameter shape issues in ZeRO-3 are due to failure of these hooks, which happens when any of our execution assumptions are violated.

Thanks a lot and I will close this issue.
