### ISSUE TITLE
Having issue with multi node training

### ISSUE THREAD

**Issue by dittops** [microsoft/DeepSpeed#3546]
**Describe the bug**
I'm running finetuning script of Alpca Lora in 2 A100 nodes with 4 GPUs each of 80GB. I have set up the hostfile and the script is initiating the model in the 2 nodes. But the train function is not getting initiated. I can see some logs related NCCL not connecting properly.

I'm using the following command to run.

`NCCL_DEBUG=INFO deepspeed --num_nodes=2 --num_gpus=2 finetune.py --base_model huggyllama/llama-7b --data_path alpaca_data.json --output_dir output/convo-12-may --batch_size 128 --micro_batch_size 4 --learning_rate 6e-4 --num_epochs 1 --val_set_size 50 --deepspeed --deepspeed_config configs/ds_config.json`

**Screenshots**
<img width="1630" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/12937285/465efa37-4c68-4a32-8e34-cfc032b8c513">

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Two machines with x4 A100s each
 - Python 3.8

**Comment by jeffra** [comment]
Hi @dittops, there may be something wrong with your environment or setup here. Can you try running something like this: https://gist.github.com/jeffra/b5e80466b4c86be00ea3b6f130fb7a36 or https://github.com/nvidia/nccl-tests to ensure that NCCL is setup and working in your environment?

**Comment by jomayeri** [comment]
@dittops in addition to Jeff's suggestion, DeepSpeed also has suggested environment variables for multi-node training [here](https://www.deepspeed.ai/getting-started/#multi-node-environment-variables)

**Comment by dittops** [comment]
@jeffra Thanks for the response. https://gist.github.com/jeffra/b5e80466b4c86be00ea3b6f130fb7a36 - I'm getting the same socket issue here.

https://github.com/nvidia/nccl-tests  - mpirun is showing firewall issue.  But I couldn't find any firewall active in the OS. I'm checking that.

**Comment by jomayeri** [comment]
Closing this thread. Please reopen if necessary.

**Comment by dittops** [comment]
@jomayeri I have tried the same setup in the AWS ec2 instance, but I still face a similar issue with mpirun. Any thoughts on how I could solve this?
