### ISSUE TITLE
[BUG] `<class 'transformers_modules.local.quantization.QuantLinear'>' was not properly set up for sharding by zero.Init(). A subclass of torch.nn.Module must be defined before zero.Init() where an instance of the class is created.

### ISSUE THREAD

**Issue by lhtpluto** [microsoft/DeepSpeed#3549]
/home/ai/MOSS/finetune_moss.py:305 in <module>                                                   │
│                                                                                                  │
│   302 │   os.makedirs(args.output_dir, exist_ok=True)                                            │
│   303 │                                                                                          │
│   304 │   set_seed(args.seed)                                                                    │
│ ❱ 305 │   train(args)                                                                            │
│   306                                                                                            │
│                                                                                                  │
│ /home/ai/MOSS/finetune_moss.py:180 in train                                                      │
│                                                                                                  │
│   177 │   tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path, trust_remote_code   │
│   178 │   tokenizer.eos_token_id = 106068 # The eos_token_id of base model is 106028. We need    │
│   179 │                                                                                          │
│ ❱ 180 │   model = AutoModelForCausalLM.from_pretrained(args.model_name_or_path, trust_remote_c   │
│   181 │                                                                                          │
│   182 │   model.transformer.gradient_checkpointing = True                                        │
│   183 │   assert model.transformer.gradient_checkpointing is True                                │
│                                                                                                  │
│ /root/anaconda3/envs/moss/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py:4 │
│ 58 in from_pretrained                                                                            │
│                                                                                                  │
│   455 │   │   │   model_class = get_class_from_dynamic_module(                                   │
│   456 │   │   │   │   pretrained_model_name_or_path, module_file + ".py", class_name, **hub_kw   │
│   457 │   │   │   )                                                                              │
│ ❱ 458 │   │   │   return model_class.from_pretrained(                                            │
│   459 │   │   │   │   pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs,   │
│   460 │   │   │   )                                                                              │
│   461 │   │   elif type(config) in cls._model_mapping.keys():                                    │
│                                                                                                  │
│ /root/anaconda3/envs/moss/lib/python3.8/site-packages/transformers/modeling_utils.py:2276 in     │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   2273 │   │   │   init_contexts.append(init_empty_weights())                                    │
│   2274 │   │                                                                                     │
│   2275 │   │   with ContextManagers(init_contexts):                                              │
│ ❱ 2276 │   │   │   model = cls(config, *model_args, **model_kwargs)                              │
│   2277 │   │                                                                                     │
│   2278 │   │   if load_in_8bit:                                                                  │
│   2279 │   │   │   from .utils.bitsandbytes import get_keys_to_not_convert, replace_8bit_linear  │
│                                                                                                  │
│ /root/anaconda3/envs/moss/lib/python3.8/site-packages/transformers/utils/generic.py:344 in       │
│ __exit__                                                                                         │
│                                                                                                  │
│   341 │   │   │   self.stack.enter_context(context_manager)                                      │
│   342 │                                                                                          │
│   343 │   def __exit__(self, *args, **kwargs):                                                   │
│ ❱ 344 │   │   self.stack.__exit__(*args, **kwargs)                                               │
│   345                                                                                            │
│   346                                                                                            │
│   347 def can_return_loss(model_class):                                                          │
│                                                                                                  │
│ /root/anaconda3/envs/moss/lib/python3.8/contextlib.py:525 in __exit__                            │
│                                                                                                  │
│   522 │   │   │   │   # bare "raise exc_details[1]" replaces our carefully                       │
│   523 │   │   │   │   # set-up context                                                           │
│   524 │   │   │   │   fixed_ctx = exc_details[1].__context__                                     │
│ ❱ 525 │   │   │   │   raise exc_details[1]                                                       │
│   526 │   │   │   except BaseException:                                                          │
│   527 │   │   │   │   exc_details[1].__context__ = fixed_ctx                                     │
│   528 │   │   │   │   raise                                                                      │
│                                                                                                  │
│ /root/anaconda3/envs/moss/lib/python3.8/contextlib.py:510 in __exit__                            │
│                                                                                                  │
│   507 │   │   │   is_sync, cb = self._exit_callbacks.pop()                                       │
│   508 │   │   │   assert is_sync                                                                 │
│   509 │   │   │   try:                                                                           │
│ ❱ 510 │   │   │   │   if cb(*exc_details):                                                       │
│   511 │   │   │   │   │   suppressed_exc = True                                                  │
│   512 │   │   │   │   │   pending_raise = False                                                  │
│   513 │   │   │   │   │   exc_details = (None, None, None)                                       │
│                                                                                                  │
│ /root/anaconda3/envs/moss/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameter │
│ s.py:447 in __exit__                                                                             │
│                                                                                                  │
│    444 │   │   if not self.enabled:                                                              │
│    445 │   │   │   return                                                                        │
│    446 │   │                                                                                     │
│ ❱  447 │   │   self.remove_wrappers()                                                            │
│    448 │   │                                                                                     │
│    449 │   │   # Exiting the top level context                                                   │
│    450 │   │   global zero_init_context                                                          │
│                                                                                                  │
│ /root/anaconda3/envs/moss/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameter │
│ s.py:511 in remove_wrappers                                                                      │
│                                                                                                  │
│    508 │   │   │   for subclass in get_all_subclasses(torch.nn.modules.module.Module):           │
│    509 │   │   │   │   if subclass not in all_wrapped_classes:                                   │
│    510 │   │   │   │   │   msg = f"`{subclass}' was not properly set up for sharding by zero.In  │
│ ❱  511 │   │   │   │   │   raise RuntimeError(msg)                                               │
│    512 │   │   │   all_wrapped_classes.clear()                                                   │
│    513                                                                                           │
│    514                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: `<class 'transformers_modules.local.quantization.QuantLinear'>' was not properly set up for sharding by
zero.Init(). A subclass of torch.nn.Module must be defined before zero.Init() where an instance of the class is created.

**Comment by tohtana** [comment]
@lhtpluto This issue was solved by #3592. Can you try with the latest revision on master branch?

**Comment by tohtana** [comment]
Closing because the issue was solved by #3592. Feel free to reopen if the issue still exists.
