### ISSUE TITLE
[BUG] Deepspeed prints all the print statements N times, N=num_gpus.

### ISSUE THREAD

**Issue by djaym7** [microsoft/DeepSpeed#3552]
Deepspeed prints all the print statements N times, N=num_gpus. Any way to stop it from printing things N times ? Is there deepspeed loglevel environ parameter ?

**Comment by tjruwase** [comment]
@djaym7, this probably a bug as the expected behavior is to print on rank 0. Can you please share log to help locate this issue? Thanks!

**Comment by samadejacobs** [comment]
Closing for lack of response, please reopen if needed.
