### ISSUE TITLE
[Question] why the data of step2 in deepspeed-chat training only two sample with same prompt in a batch?

### ISSUE THREAD

**Issue by PeiqinSun** [microsoft/DeepSpeed#3558]
Is for simplify? Because there are K response for one prompt. K should be greater than 2, and the all pair combinations of K should in a batch, right?

**Comment by conglongli** [comment]
This is simply because most (if not all) of the public datasets we found only have at most 2 responses. If you do have data with > 2 responses, then yes it could be reasonable to put all pair combinations into a single batch as mentioned in InstructGPT work.
