### ISSUE TITLE
[BUG] `RuntimeError: stack expects a non-empty TensorList` when using ZeRO Stage3 with mpu

### ISSUE THREAD

**Issue by eggiter** [microsoft/DeepSpeed#3564]
**Describe the bug**
+ When using zero stage 3 with mpu(Tensor Parallelism), an error occurs during optimizer step(stack trace was shown below).
```
Traceback (most recent call last):
  ...
    model.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1930, in step
    self._take_model_step(lr_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1831, in _take_model_step
    self.optimizer.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2352, in step
    norm_groups = self._get_norm_groups()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2145, in _get_norm_groups
    self.get_grad_norm_direct(self.averaged_gradients[i],
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2028, in get_grad_norm_direct
    total_norm_cuda = torch.sum(torch.pow(torch.stack(grad_norms), 2))
RuntimeError: stack expects a non-empty TensorList
```
+ More specifically, the error occurs at the beginning of stage3.step where deepspeed is trying to get grad norm of gradients.
+ Seems it doesn't correctly handle the scenario where some TP processes(model_parallel_rank > 0 ) has sub_group in self.fp16_groups which doesn't have parameters in model parallel.
```python
    def get_grad_norm_direct(self, gradients, params, norm_type=2):
        norm_type = float(norm_type)
        if norm_type == inf:
            ...
        else:
            grad_norms = []
            for g, p in zip(gradients, params):
                if is_model_parallel_parameter(p) or (self.model_parallel_rank == 0):
                    grad_norms.append(g.cuda(non_blocking=True).double().norm(2))

            # Sum across all model parallel GPUs.
            total_norm_cuda = torch.sum(torch.pow(torch.stack(grad_norms), 2)) # <--- RuntimeError raised here
``` 

**To Reproduce**
1. Using 1node with 4gpus. TP(model parallelism)=2.

| - | - |
| --- | --- |
| GPU0(TP=0, DP=0) | GPU1(TP=1, DP=0) |
| GPU2(TP=0, DP=1) | GPU3(TP=1, DP=1) |

2. Set self.optimizer.param_groups = [[p1, p2], [p3, p4]], where `p1.model_parallel=True`,`p2.model_parallel=True`,`p3.model_parallel=False`,`p4.model_parallel=False`.
3. Then, on GPU1 and GPU3, function `get_grad_norm_direct` will raise `RuntimeError` while processing sub_group [p3, p4].

**Expected behavior**
+ No error occurs and `total_norm_cuda` shoud be `0.` while processing sub_group [p3, p4] on GPU1 and GPU3.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.8/site-packages/torch']
torch version .................... 1.13.0+cu117
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed install path ........... ['/opt/conda/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.6.5, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.3
```

**Screenshots**
N/A

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - GPU count and types: 1 machines with x4 A100s
 - Python version: 3.8.8

**Launcher context**
`deepspeed` launcher

**Docker context**
custom docker image built on ngc official pytorch image

**Additional context**
+ Seems this bug was introduced firstly by https://github.com/microsoft/DeepSpeed/commit/4912e0ad7efcaf97389ae944259aa0e9f331038a in `v0.6.0`, and still exists in current master branch.

**Comment by samadejacobs** [comment]
@eggiter, thank you for your contributions. Before approving the PR, we will like to understand a bit about the scenario highlighted above. Why do you have a sub_group in self.fp16_groups which doesn't have parameters in model parallel? Our understanding of TP is that all GPUs we have appropriate tensor-sliced of all parameters, all parameters are expected to have same model parallel degree or properties. These TP parameters are further partitioned by ZeRO3 relative to data parallel degree. In your example, each GPU would have 1/4 of p1, p2, p3 and p4. Could you please explain why the scenario you presented deviates from expectation? Thanks.

**Comment by eggiter** [comment]
> Why do you have a sub_group in self.fp16_groups which doesn't have parameters in model parallel?

@samadejacobs 
- self.optimizer.param_groups = [[p1, p2], [p3, p4]], where:
    - we apply weight decay to param group [p1, p2], and NO weight decay to [p3, p4];
    - param group [p3, p4] hold weights of layer norm belongs to transformer layer;
    - param group [p1, p2] holds other weights belongs to transformer attention/feed-forward block;
    - currently weights of layer norm are NOT sliced by TP processes in TP implementation such as megatron;
- So in my example, each GPU would have 1/4 of p1 & p2, but 1/2 of p3 and p4 since they are only been partitioned by ZeRO3.
