### ISSUE TITLE
About 3D parallelism when using Megatron Deepspeed[BUG]

### ISSUE THREAD

**Issue by etoilestar** [microsoft/DeepSpeed#3589]
**Describe the bug**
When I was trying to use TP/PP in Megatron-Deepspeed, it raise an error: ZeRO-2 and ZeRO-3 are incompatible with pipline parallelism. could you tell me how to use TP/PP with zero stage 1?

**To Reproduce**
1. Go to the link 'https://github.com/microsoft/Megatron-DeepSpeed' and git clone.
2. Modify the hyper parameter PP=2 in example/run_deepspeed_example.sh.
3. run the script amentioned above
4. you will get the error
5. if you set ZERO_STAGE=1, another bug about optimizer will occur.

**Expected behavior**
I just want to try to do 3D parallelism, which is mentioned in https://arxiv.org/pdf/2201.11990.pdf. in this paper, you said your system software stack combines pipeline parallelism and data parallelism from DeepSpeed with tensorslicing from Megatron to create a flexible 3D-parallelism implementation at section 2.2, but I don't success.

**Comment by tjruwase** [comment]
@etoilestar, it is correct that we don't currently support PP with zero stage > 1. 

Can you please share stack trace of the optimizer error from using zero_stage=1. 

In terms of combining PP with zero stage 1, please use this [Megatron-DeepSpeed](https://github.com/bigscience-workshop/Megatron-DeepSpeed) version that was used to train [BLOOM-176B](https://huggingface.co/blog/bloom-megatron-deepspeed).

**Comment by etoilestar** [comment]
Okay, I just ran this code successfully with zero stage 1 ,thanks, i will go on to learn more about deepspeed.

**Comment by tjruwase** [comment]
Closing as resolved.

**Comment by etoilestar** [comment]
hello，it seems that you did not finish vit model with PP/TP in https://github.com/microsoft/Megatron-DeepSpeed, I recently tried to write this code, can you give me some advice?

**Comment by JanryPei** [comment]
But when I set pp=1 zero_stage=2, it still can't run and shows " ZeRO-2 and ZeRO-3 are incompatible with pipeline parallelism"

**Comment by samadejacobs** [comment]
@JanryPei, please add flag `--no_pipeline_parallel` to your command line.

**Comment by JanryPei** [comment]
> @JanryPei, please add flag `--no_pipeline_parallel` to your command line.

Thanks! I run zero-2 successfully with this flag.
