### ISSUE TITLE
AttributeError: 'DeepSpeedZeRoOffload' object has no attribute 'checkpoint_event_prologue' [BUG]

### ISSUE THREAD

**Issue by wj210** [microsoft/DeepSpeed#3601]
during inference, the error "AttributeError: 'DeepSpeedZeRoOffload' object has no attribute 'checkpoint_event_prologue'" occur, similar to #2449.

**To Reproduce**

```
train_params = dict(
                strategy = DeepSpeedStrategy(
        stage=3,
        offload_optimizer=args.cpu_offload,
        offload_parameters=args.cpu_offload,
    ) if args.strategy == 'deepspeed_stage_3' else args.strategy,
                accumulate_grad_batches=args.gradient_accumulation_steps,
                accelerator='gpu' if args.n_gpu > 0 else None,
                devices = [args.gpu_no] if args.n_gpu <= 1 else args.n_gpu,
                # num_nodes = args.n_gpu,
                max_epochs=args.num_train_epochs,
                precision='bf16' if args.fp_16 else 32,
                gradient_clip_val=args.max_grad_norm, # default args.max_grad_norm
                enable_checkpointing =False,
                callbacks=callbacks,
                # log_every_n_steps = sum([len(t[0]) for t in curr_train_ids])//args.train_batch_size
                )
    trainer = pl.Trainer(**train_params)
    ckpt_path = os.path.join(args.output_dir,'best.ckpt')
    
    
    # Train model
    trainer.fit(model)
    trainer.save_checkpoint(ckpt_path)
    ## Test phase
    test_metrics = trainer.test() 
```error happened here, the trainer loads the ckpt_path saved in the logs and somehow has that error.

I was able to mitigate it by setting ckpt_path to 'last' but it started printing an extremely long list of weird numbers like
`1017, 1024, 1018, 1019, 1023, 1020, 1022, 1021, 1025, 1026, 1028, 1034, 1029, 1030, 1031, 1032, 1033, 1035, 1036, 1042, 1037, 1038, 1041, 1043, 1044, 1051, 1045, 1046, 1050, 
1047, 1049, 1048, 1052, 1053, 1055, 1061, 1056, 1057, 1058, 1059, 1060, 1062, 1063, 1069, 1064, 1065, 1068, 1070, 1071, 1078, 1072, 1073, 1077, 1074, 1076, 1075, 1079, 1080, 
1082, 1088, 1083, 1084, 1085, 1086, 1087, 1089, 1090, 1096, 1091, 1092, 1095, 1097, 1098, 1105, 1099, 1100, 1104, 1101, 1103, 1102, 1106, 1107, 1109, 1115, 1110, 1111, 1112, 
1113, 1114, 1116, 1117, 1123, 1118, 1119, 1122, 1124, 1125, 1132, 1126, 1127, 1131, 1128, 1130, 1129, 1133, 1134, 1135, 1136]`

**ds_report output**
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/weijie/anaconda3/envs/flan/lib/python3.10/site-packages/torch']
torch version .................... 1.12.1+cu113
deepspeed install path ........... ['/home/weijie/anaconda3/envs/flan/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.8.2, unknown, unknown
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.3

**Comment by tjruwase** [comment]
@wj210, can you please share full repro steps, including full script and command line? Thanks!

**Comment by wj210** [comment]
sure.

Heres the script for running the code:
`class T5FineTuner(pl.LightningModule):
    def __init__(self, hparams):
        super(T5FineTuner, self).__init__()
        self.save_hyperparameters(hparams)
        
        self.model = T5ForConditionalGeneration.from_pretrained(hparams.model_name_or_path)
        self.tokenizer = T5Tokenizer.from_pretrained(hparams.tokenizer_name_or_path,model_max_length = hparams.max_seq_length)
        if self.hparams.special_tokens != '':
            s = {'sep_token':self.hparams.special_tokens}
            self.tokenizer.add_special_tokens(s)
            self.model.resize_token_embeddings(len(self.tokenizer))
            self.skip_special_tokens = False
        else:
            self.skip_special_tokens = True
        self.decode_length = self.hparams.max_seq_length 
        self.test_step_number = 0
        allowed_tokens = []
        for tok in ['positive','negative']:
            allowed_tokens.extend(self.tokenizer.tokenize(tok))
        self.allowed_sentiment_ids = self.tokenizer.convert_tokens_to_ids(allowed_tokens)
def is_logger(self):
        return True
    
    def forward(
        self, input_ids, attention_mask=None, decoder_input_ids=None, decoder_attention_mask=None, labels=None
    ):
        return self.model(
            input_ids,
            attention_mask=attention_mask,
            decoder_input_ids=decoder_input_ids,
            decoder_attention_mask=decoder_attention_mask,
            labels=labels,
        )

    def _step(self, batch):
        labels = batch["target_ids"]
        labels[labels[:, :] == self.tokenizer.pad_token_id] = -100
    
        decoder_attention_mask = batch['target_mask'].to(torch.long)
        outputs = self(
            input_ids=batch["source_ids"].to(torch.long),
            attention_mask=batch["source_mask"].to(torch.long),
            labels=labels.to(torch.long),
            decoder_attention_mask=decoder_attention_mask
        )

        loss = outputs[0]

        return loss

    def training_step(self, batch, batch_idx):
        loss = self._step(batch)
        self.log("train_loss",loss,on_epoch=True,prog_bar=True,sync_dist=True if self.hparams.n_gpu > 1 else False) 
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self._step(batch)
        self.log("val_loss",loss,on_epoch=True,prog_bar=True,sync_dist=True if self.hparams.n_gpu > 1 else False)
        self.log("epoch",int(self.current_epoch))
        return {"val_loss": loss}

    
    def test_step(self, batch, batch_idx,dataloader_idx=0):
if dataloader_idx == 0:
            ds_name = 'movie'
        elif dataloader_idx == 1:
            ds_name = 'fiqa'        
            
        outs = self.model.generate(
            input_ids=batch["source_ids"].to(torch.long),
            attention_mask=batch["source_mask"].to(torch.long),
            return_dict_in_generate=True,
            output_scores=True,
            max_length=self.hparams.max_seq_length,
            eos_token_id = self.tokenizer.eos_token_id
        )   
        
        out_seq_list = outs.sequences.tolist()
        pre_scores_n_class = [detect_sentiment_probs(o_id,outs.scores,i,self.tokenizer,self.allowed_sentiment_ids) for i,o_id in enumerate(out_seq_list)]
        random_ids = np.random.randint(0, batch['target_ids'].shape[0], size = 1)[0]
        
        input_text_no_padding = [token_id for token_id in batch['source_ids'][random_ids] if token_id != self.tokenizer.pad_token_id] # remove <pad> token
        target_text_no_padding = [token_id for token_id in batch['target_ids'][random_ids] if token_id != self.tokenizer.pad_token_id] # remove <pad> token
        pred_rationales_no_padding = [token_id for token_id in outs.sequences[random_ids] if token_id != self.tokenizer.pad_token_id] # remove <pad> token
        pred_text = self.tokenizer.decode(pred_rationales_no_padding, skip_special_tokens=self.skip_special_tokens)
        target_text = self.tokenizer.decode(target_text_no_padding, skip_special_tokens=self.skip_special_tokens)
        input_text = self.tokenizer.decode(input_text_no_padding, skip_special_tokens=self.skip_special_tokens)
        display_outputs = [input_text,target_text,pred_text] # input,target,pred
        
        # ## plausibility score
        
        b_scores,b_tar_s,b_pred_s = {"micro_f1":[],"macro_f1":[],"iou":[]},[],[]
        predict_rationales = []
        pre_ids = []
        full_match_instances = []
        pre_rat_ids = []
        for idd, target_rationale in enumerate(batch['target_ids']):
            target_r,target_s = preprocess_rationales(target_rationale,self.tokenizer)
            pred_rationale = outs.sequences[idd]
            pred_r,pred_s = preprocess_rationales(pred_rationale,self.tokenizer) # rationales are list of list of ids, sentiment is string
            if len(target_r) > 0:
                if len(pred_r) > 0:
                    scores = compute_scores(target_r, pred_r,threshold=0.5)
                    predict_rationales.append(pred_r) # list of rationales 
                    if scores['micro_f1'] == 1.0: # if f1 is 1.0, then rationales match perfectly
                        full_match_instances.append((target_r,idd))
                    pre_rat_ids.append(idd) ## for sufficiency score
                    for k,v in scores.items():
                        b_scores[k].append(v)
                else:
                    for k in b_scores.keys():
                        b_scores[k].append(0.)
                    predict_rationales.append([])
            else:
                for k in b_scores.keys():
                    b_scores[k].append(0.)
                predict_rationales.append([])
            if pred_s is not None:
                b_tar_s.append(target_s)
                b_pred_s.append(pred_s)
                pre_ids.append(idd)

def configure_optimizers(self):
        "Prepare optimizer and schedule (linear warmup and decay)"
        if self.hparams.strategy == 'fsdp': # using fsdp requires to call self.trainer.model.parameters() instead of self.model.parameters()
            model = self.trainer.model
        else:
            model = self.model
        no_decay = ["bias", "LayerNorm.weight"]
        optimizer_grouped_parameters = [
            {
                "params": [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)],
                "weight_decay": self.hparams.weight_decay,
            },
            {
                "params": [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)],
                "weight_decay": 0.0,
            },
        ]
        if "deepspeed" in self.hparams.strategy:
            if self.hparams.cpu_offload:
                optimizer = DeepSpeedCPUAdam(optimizer_grouped_parameters, lr=self.hparams.learning_rate, eps=self.hparams.adam_epsilon)
            else:
                optimizer = FusedAdam(optimizer_grouped_parameters, lr=self.hparams.learning_rate, eps=self.hparams.adam_epsilon)
        else:
            optimizer = AdamW(optimizer_grouped_parameters, lr=self.hparams.learning_rate, eps=self.hparams.adam_epsilon)
        self.opt = optimizer
        return [optimizer]
    
    def optimizer_step(self, epoch, batch_idx, optimizer, optimizer_closure,optimizer_idx=None):
        
        optimizer.step(closure=optimizer_closure)
        optimizer.zero_grad()
        self.lr_scheduler.step()
    
    def get_tqdm_dict(self):
        tqdm_dict = {"loss": "{:.3f}".format(self.trainer.avg_loss), "lr": self.lr_scheduler.get_last_lr()[-1]}

        return tqdm_dict

    def train_dataloader(self):
        train_dataset = RationaleDataset(tokenizer=self.tokenizer, data_path = self.hparams.data_dir,max_len=self.hparams.max_seq_length,label = 'train',model_name = self.hparams.model_name_or_path)

        dataloader = DataLoader(train_dataset, batch_size=self.hparams.train_batch_size, drop_last=True, shuffle=True, num_workers=4)

        t_total = (
            (len(dataloader.dataset) // (self.hparams.train_batch_size * max(1, self.hparams.n_gpu)))
        // self.hparams.gradient_accumulation_steps * float(self.hparams.num_train_epochs)
        )
        warmup_steps = (
            (len(dataloader.dataset) // (self.hparams.train_batch_size * max(1, self.hparams.n_gpu)))
        // self.hparams.gradient_accumulation_steps * float(self.hparams.warmup_steps)
        )
        
        scheduler = get_linear_schedule_with_warmup(
            self.opt, num_warmup_steps=warmup_steps, num_training_steps=t_total
        )
        self.lr_scheduler = scheduler
        return dataloader

    def val_dataloader(self):
        test_dataset = RationaleDataset(tokenizer=self.tokenizer, data_path = self.hparams.data_dir,max_len=self.hparams.max_seq_length,
                                        label = 'val',model_name = self.hparams.model_name_or_path)
        val_dataloader = DataLoader(test_dataset, batch_size=self.hparams.eval_batch_size, num_workers=4)
        return val_dataloader
    
    def test_dataloader(self):
        test_dataset = RationaleDataset(tokenizer=self.tokenizer, data_path=self.hparams.data_dir, max_len=self.hparams.max_seq_length, 
                                        label='test',model_name = self.hparams.model_name_or_path)
        test_dataloader = DataLoader(test_dataset, batch_size=self.hparams.eval_batch_size, num_workers=4)
        
        ## for ood financial fiqa dataset
        if self.hparams.ood_data_dir != '':
            ood_dataset = FiQARationale(tokenizer=self.tokenizer, data_path=self.hparams.ood_data_dir, 
                                        max_len=self.hparams.max_seq_length,model_name = self.hparams.model_name_or_path)
            
            ood_dataloader = DataLoader(ood_dataset, batch_size=self.hparams.eval_batch_size, num_workers=4)
            return [test_dataloader,ood_dataloader]
        else:
            return test_dataloader
class LoggingCallback(pl.Callback):
    def __init__(self,logger,kfold=0,task="classification",expl_label='f',file_path=None,args=None):
        self.kfold = kfold
        self.task = task
        self.logger = logger
        self.expl_label = expl_label
        self.args = args
        self.file_path = file_path
        
    def on_validation_end(self, trainer, pl_module):
        self.logger.info("***** Validation results *****")
        if pl_module.is_logger():
            metrics = trainer.callback_metrics
        if metrics['epoch'] == 0:
            writer_mode = "w"
        else:
            writer_mode = "a"
        file_path= self.file_path[0] # set to movie as ood dataset only used for test
            
        with open(file_path, writer_mode) as writer:
            if writer_mode == "w":
                writer.write("***** Validation results *****\n")
            writer.write(f"Epoch: {metrics['epoch']}\n")
            for key in sorted(metrics):
                if key !="epoch":
                    self.logger.info("{} = {}\n".format(key, str(metrics[key])))
                    writer.write("{} = {}\n".format(key, str(metrics[key])))

    def on_test_end(self, trainer, pl_module):
        self.logger.info("***** Test results *****")

        if pl_module.is_logger():
            metrics = trainer.callback_metrics
        writer_mode = "a"
        if 'movie_test_sentiment_accuracy' in metrics.keys():
            file_path= self.file_path[0]
            ds_name = "Movie"
        else:
            file_path= self.file_path[1]
            ds_name = "Fiqa"
        with open(file_path, writer_mode) as writer:
            writer.write(f"***** Test results - {ds_name}-Dataset *****\n\n")
            for key in sorted(metrics):
                if key !="epoch" or "ds_name":
                    self.logger.info("{} = {}\n".format(key, str(metrics[key])))
                    writer.write("{} = {}\n".format(key, str(metrics[key])))
def main():
    set_seed(42)
    logger = logging.getLogger(__name__)
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_dir", nargs ='+',type=str, required=True, default = 'data/expl_sentiment_data/seed_expl.json')
    parser.add_argument("--ood_data_dir",type=str, required=False, default = '')
    parser.add_argument("--labels", nargs ='+',type=str, required=False, default = 'f')
    parser.add_argument("--output_dir", type=str, required=False, default="results")
    parser.add_argument("--special_tokens", type=str, required=False, default="<sep>") ## for separating
    parser.add_argument("--model_name_or_path",type=str, required=False, default='t5-base')
    parser.add_argument("--tokenizer_name_or_path", type=str, required=False, default='t5-base')
    parser.add_argument("--max_seq_length", type=int, required=False, default=512)
    parser.add_argument("--learning_rate",  type=float, required=False, default=3e-4)
    parser.add_argument("--adam_epsilon",  type=float, required=False, default=1e-8)
    parser.add_argument("--warmup_steps", type=int, required=False, default=1)
    parser.add_argument("--train_batch_size",  type=int, required=False, default=8)
    parser.add_argument("--eval_batch_size",  type=int, required=False, default=8)
    parser.add_argument("--num_train_epochs", type=int, required=False, default=4)
    parser.add_argument("--gradient_accumulation_steps", type=int, required=False, default=1)
    parser.add_argument("--n_gpu", type=int, required=False, default=1)
    parser.add_argument("--fp_16",  type=bool, required=False, default=False,help = "if you want to enable 16-bit training then install apex and set this to true")
    parser.add_argument("--max_grad_norm",  type=float, required=False, default=1.0)
    parser.add_argument("--temperature",  type=float, required=False, default=0.5, help = 'lower = greedy sampling, higher = diverse sampling')
    parser.add_argument("--seed",type=int, required=False, default=42)
    parser.add_argument("--num_seq", type=int, required=False, default=5)
    parser.add_argument("--gpu_no", type=int, required=False, default=1)
    parser.add_argument("--task", type=str, required=False, default='classification')
    parser.add_argument("--data_explanation", type=bool, required=False, default=False)
    parser.add_argument("--weight_decay",  type=float, required=False, default=0.0)
    parser.add_argument("--kfold_on",  type=bool, required=False, default=False) # use kfold cv
    parser.add_argument("--inference",  type=bool, required=False, default=False)
    parser.add_argument("--inference_dataset",  type=str, required=False, default='')
    parser.add_argument("--fs",  type=int, required=False, default=0) # how many few-shot examples
    parser.add_argument("--strategy",  type=str, required=False, default='ddp') # how many few-shot examples
    parser.add_argument("--cpu_offload",  type=bool, required=False, default=False) # how many few-shot examples
    args = parser.parse_args()
n_devices = torch.cuda.device_count()
    if args.n_gpu > n_devices:
        args.n_gpu = n_devices
    
    if args.n_gpu <= 1:
        args.strategy = 'auto'

    ## define dataloader and tokenizer
    if args.data_explanation:
        args.output_dir = os.path.join(args.output_dir,'expl')
    else:
        args.output_dir = os.path.join(args.output_dir,'non_expl')
        # args.fs = 3 # set to 3 to test fs on model not trained with expl, can explicting set fs > 0 for model trained with expl to see few-shot performance, but default is 0-shot
    
    if not os.path.exists(args.output_dir):
        os.mkdir(path=args.output_dir)

    checkpoint_callback = pl.callbacks.ModelCheckpoint(
        dirpath=args.output_dir, filename=f"{args.model_name_or_path}_FIQA", monitor="val_loss", mode="min", save_top_k=1
    )
    
    k_fold_name = '10-fold' if args.kfold_on else '1-fold'
    if '/' in args.model_name_or_path:
        model_name = args.model_name_or_path.split('/')[-1]
    else:
        model_name = args.model_name_or_path
        
    output_num_file = [os.path.join(args.output_dir,'movie',f"{model_name}_num_movie.txt")]    
    output_txt_file = [os.path.join(args.output_dir,'movie',f"{model_name}_text_movie.txt")]        
    if not os.path.exists(os.path.join(args.output_dir,'movie')):
        os.mkdir(path=os.path.join(args.output_dir,'movie'))
    if args.ood_data_dir != '':
        if not os.path.exists(os.path.join(args.output_dir,'fiqa')):
            os.mkdir(path=os.path.join(args.output_dir,'fiqa'))
        output_num_file.append(os.path.join(args.output_dir,'fiqa',f"{model_name}_num_fiqa.txt"))
        output_txt_file.append(os.path.join(args.output_dir,'fiqa',f"{model_name}_text_fiqa.txt"))
    args.text_file = output_txt_file
    
    model = T5FineTuner(args) # define model
    
    
    
    ## define training params
    early_stop_callback = pl.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=3,
        verbose=False,
        mode='min')
    
    # if args.kfold_on:
    callbacks = [LoggingCallback(logger = logger,task = args.task,file_path = output_num_file,args=args),early_stop_callback]
    

    # else:
    #     callbacks = [LoggingCallback(logger = logger,task = args.task,expl_label = expl_label,args=args),checkpoint_callback]
    
    train_params = dict(
                strategy = DeepSpeedStrategy(
        stage=3,
        offload_optimizer=args.cpu_offload,
        offload_parameters=args.cpu_offload,
    ) if args.strategy == 'deepspeed_stage_3' else args.strategy,
                accumulate_grad_batches=args.gradient_accumulation_steps,
                accelerator='gpu' if args.n_gpu > 0 else None,
                devices = [args.gpu_no] if args.n_gpu <= 1 else args.n_gpu,
                # num_nodes = args.n_gpu,
                max_epochs=args.num_train_epochs,
                precision='bf16' if args.fp_16 else 32,
                # gradient_clip_val=args.max_grad_norm, # default args.max_grad_norm
                enable_checkpointing =True,
                callbacks=callbacks,
                # log_every_n_steps = sum([len(t[0]) for t in curr_train_ids])//args.train_batch_size
                )
    trainer = pl.Trainer(**train_params)
    ckpt_path = os.path.join(args.output_dir,'best_ckpt')
    
    
    # Train model
    trainer.fit(model)
    # trainer.save_checkpoint(ckpt_path)
    ## Test phase
    test_metrics = trainer.test()
    
   
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Interrupted by user")
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
`
command line :
```
torchrun \
--standalone \
--nnodes=1 \
--nproc_per_node=4 train_t5.py \
--model_name_or_path 'google/flan-t5-base' \
--tokenizer_name_or_path 'google/flan-t5-base' \
--data_dir '../data/expl_sentiment_data/movies' \
--n_gpu 4 \
--data_explanation True \
--num_train_epochs 20 \
--strategy 'deepspeed_stage_3' \
--train_batch_size 16 \
--eval_batch_size 16 \
--fp_16 True 
```

The script is kinda long, but the thing was that the error has to do with loading the checkpoint from the saved dict after model.fit. As the error did not happen when the ckpt_path was set to "last".

**Comment by wj210** [comment]
The code is kinda long, but it mainly happens due to the fact that during testing, trainer.test ckpt_path was set to the default which is best and involves loading from the saved ckptpoint, as you can see when ckpt_path was set to "last", the error did not occurred, tho something else happened, which was the printing of numerical digits shown above.

`train_params = dict(
                strategy = DeepSpeedStrategy(
        stage=3,
        offload_optimizer=args.cpu_offload,
        offload_parameters=args.cpu_offload,
    ) if args.strategy == 'deepspeed_stage_3' else args.strategy,
                accumulate_grad_batches=args.gradient_accumulation_steps,
                accelerator='gpu' if args.n_gpu > 0 else None,
                devices = [args.gpu_no] if args.n_gpu <= 1 else args.n_gpu,
                # num_nodes = args.n_gpu,
                max_epochs=args.num_train_epochs,
                precision='bf16' if args.fp_16 else 32,
                # gradient_clip_val=args.max_grad_norm, # default args.max_grad_norm
                enable_checkpointing =True,
                callbacks=callbacks,
                # log_every_n_steps = sum([len(t[0]) for t in curr_train_ids])//args.train_batch_size
                )
    trainer = pl.Trainer(**train_params)
    ckpt_path = os.path.join(args.output_dir,'best_ckpt')
    
    
    # Train model
    trainer.fit(model)
    # trainer.save_checkpoint(ckpt_path) # if set to last, no error.
    ## Test phase`

**Comment by RoyJames** [comment]
Can confirm this happens. This is a huge inconvenience.

**Comment by iamlockelightning** [comment]
👀

**Comment by iamlockelightning** [comment]
Same situation, waiting to get a solution to this problem. The official doc is taking [deepspeed_stage_3](https://lightning.ai/docs/pytorch/stable/advanced/model_parallel.html#deepspeed) as an example. I don't know why **deepspeed_stage_3_offload** is not working.

My environment:
```shell
torch                     2.0.1
torchaudio                2.0.2
torchmetrics              0.11.4
torchvision               0.15.2
lightning                 2.0.2
```

**Comment by tjruwase** [comment]
@wj210, @iamlockelightning, @RoyJames, FYI
