### ISSUE TITLE
[BUG]  A segmentation fault happened when calling utils op flatten

### ISSUE THREAD

**Issue by vipcxj** [microsoft/DeepSpeed#3614]
**Describe the bug**
A segmentation fault happened when calling utils op flatten. The utils op is in JIT mode. I have try to delete the cache, and rerun, Nothing help. Finally, I clone the DeepSpeed repo, install it locally. The error still happen. But when I install it with utils op built, The error disappear. I donot know the difference between JIT and built with package. The issue only triggered in former

**To Reproduce**
call deepspeed init, and flatten is called int allreduce_bucket.

**Expected behavior**
no error

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ps/mambaforge/envs/videomae/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1
deepspeed install path ........... ['/home/ps/mambaforge/envs/videomae/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.9.2, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
```

**Screenshots**

**System info (please complete the following information):**
 - Ubuntu 22.04
 - x2 RTX4090
 - Python 3.10

**Launcher context**
using python function

**Docker context**
no docker

**Additional context**

**Comment by loadams** [comment]
Hi @vipcxj - were you using the git tag from the version you intalled from pip when building from source?  That's the only immediate difference I can think of.  If not, could you try again and see if you can repro this with the latest DeepSpeed and can get a repro case for us to try out?

**Comment by loadams** [comment]
Hi @vipcxj - closing this issue for now, if you're still having issues with this, please re-open.  

More info on pre-installing DeepSpeed ops can be found [here](https://www.deepspeed.ai/tutorials/advanced-install/#pre-install-deepspeed-ops) as well.
