### ISSUE TITLE
[REQUEST] Support Training with Quantized model, e.g., qlora

### ISSUE THREAD

**Issue by lz1oceani** [microsoft/DeepSpeed#3620]
I have tried qlora with deepspeed zero3. It seems that deepspeed will create the model in the original data type, e.g., float16 and the create the quantized model. Thus, it will use more GPU memory than qlora.

Are there any ways to fix this?

**Comment by Nisoka** [comment]
@lz1oceani have you try zero stage 2 for the qlora training?

**Comment by zjwzcnjsy** [comment]
你好，我已经接收到你的邮件！

**Comment by zhangjunyi111** [comment]
解决了吗？qlora+deepspeed2能训练llama-2-70B吗

**Comment by lz1oceani** [comment]
It always works with stage-2.

**Comment by noobmaster29** [comment]
It works with stage 2 but stage 2 does not allow for parameter offloading so having zero3 work with qlora/lora models would be extremely powerful.

**Comment by momozzing** [comment]
> It works with stage 2 but stage 2 does not allow for parameter offloading so having zero3 work with qlora/lora models would be extremely powerful.

Hi, I've experimented with QLoRA + zero2 and QLoRA + zero3.

But using zero2 saves the model well
The use of zero3 is as follows.

model.save_pretrained(my_model) -> adapter_model.bin size -> 163KB.

Have you ever seen an error like this?

**Comment by TheBlackHacker** [comment]
> > It works with stage 2 but stage 2 does not allow for parameter offloading so having zero3 work with qlora/lora models would be extremely powerful.
> 
> Hi, @noobmaster29 I've experimented with QLoRA + zero2 and QLoRA + zero3.
> 
> But using zero2 saves the model well The use of zero3 is as follows.
> 
> model.save_pretrained(my_model) -> adapter_model.bin size -> 163KB.
> 
> Have you ever seen an error like this?

You must use **deepspeed.save_fp16_model()** on all rank, instead of **model.save_pretrained()**, zero-3 need to collect params from all rank and combine it to save the model.

**Comment by lz1oceani** [comment]
> It works with stage 2 but stage 2 does not allow for parameter offloading so having zero3 work with qlora/lora models would be extremely powerful.

Yes. But I guess it is not easy to combine the weight splitting and quantization in deepspeed. Every large weight is sharded equally and stored over all gpus, while the current quantization in transformers will replace the full weight with a quantized version.

**Comment by momozzing** [comment]
> > > It works with stage 2 but stage 2 does not allow for parameter offloading so having zero3 work with qlora/lora models would be extremely powerful.
> > 
> > 
> > Hi, @noobmaster29 I've experimented with QLoRA + zero2 and QLoRA + zero3.
> > But using zero2 saves the model well The use of zero3 is as follows.
> > model.save_pretrained(my_model) -> adapter_model.bin size -> 163KB.
> > Have you ever seen an error like this?
> 
> You must use **deepspeed.save_fp16_model()** on all rank, instead of **model.save_pretrained()** on rank0, zero-3 need to collect params from all rank and combine it to save the model.


Hi, @TheBlackHacker
I've solved this problem. See this link

https://github.com/microsoft/DeepSpeed/issues/4295#issuecomment-1815803016

**Comment by oushu1zhangxiangxuan1** [comment]
Dose stage-3  support lora quantization training?
I got error like this:
```
ValueError: DeepSpeed ZeRO-3 is incompatible with quantization.
```

**Comment by tjruwase** [comment]
> [@TheBlackHacker](https://github.com/TheBlackHacker) But in this case, if we train the model with quantization or bf16, then we will not be able to save as fp16 model right?

@BiEchi, use `deepspeed.save_16bit_model()` instead
https://github.com/deepspeedai/DeepSpeed/blob/1f706621f15b5df83f3bcff1e21dd0bbcfc1614b/deepspeed/runtime/engine.py#L3794
