### ISSUE TITLE
[BUG]Problems with running the run_clm.py file in the transformer library (official example) 

### ISSUE THREAD

**Issue by mh8859** [microsoft/DeepSpeed#3623]
**Describe the bug**

This is the first time for me to ask a question on github. I'm sorry if the description is unclear.  I really need your help. 

Download url: https://github.com/microsoft/DeepSpeedExamples 

location： /DeepSpeedExamples-master/training/autotuning/hf/gpt2-large

I run the command on a node with four Gpus: bash test_tune.sh z0

The following error occurred：

> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] g++ -MMD -MF flatten_unflatten.o.d -DTORCH_EXTENSION_NAME=utils -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/torch/include -isystem /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/torch/include/TH -isystem /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/torch/include/THC -isystem /home/gjq/soft/Conda/soft/envs/fint/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/deepspeed/ops/csrc/utils/flatten_unflatten.cpp -o flatten_unflatten.o 
FAILED: flatten_unflatten.o 
g++ -MMD -MF flatten_unflatten.o.d -DTORCH_EXTENSION_NAME=utils -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/torch/include -isystem /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/torch/include/TH -isystem /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/torch/include/THC -isystem /home/gjq/soft/Conda/soft/envs/fint/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /home/gjq/soft/Conda/soft/envs/fint/lib/python3.8/site-packages/deepspeed/ops/csrc/utils/flatten_unflatten.cpp -o flatten_unflatten.o 
/public1/softwares/gcc-8.4.0/libexec/gcc/x86_64-pc-linux-gnu/8.4.0/cc1plus: error while loading shared libraries: libmpfr.so.6: cannot open shared object file: No such file or directory
ninja: build stopped: subcommand failed.

……

> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
……
RuntimeError: Error building extension 'utils'
    module = importlib.util.module_from_spec(spec)    
module = importlib.util.module_from_spec(spec)  File "<frozen importlib._bootstrap>", line 556, in module_from_spec

**Screenshots**
![image](https://github.com/microsoft/DeepSpeed/assets/70998832/c5613d5a-238a-404d-99e2-58c603f31f26)
![image](https://github.com/microsoft/DeepSpeed/assets/70998832/8fd618ab-3815-4f58-ae22-a089c4482031)

**System info (please complete the following information):**
 - OS: CentOS
 - GPU count and types： one machines with x4 3090s each
 - Python version： python 3.8.1
 - torch version: 2.0.1+cu117
 - deepspeed: 0.9.2
 - ds_report:
 
![image](https://github.com/microsoft/DeepSpeed/assets/70998832/334409a1-37e7-472b-a1df-94c74df5ecae)

**Launcher context**
Currently I only test on a single node, in the future I will use slurm system to submit tasks and run across multiple Gpus across nodes.

**Additional context**
I don't know what happened, I'm sure I installed ninja and gcc, and their versions are shown below.  Is my installed version incompatible with the environment? I really need help.

> gcc (GCC) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> 1.11.1.git.kitware.jobserver-1

```[tasklist]
### Tasks
```

**Comment by jomayeri** [comment]
It appears you have missing packages on the system.
