### ISSUE TITLE
Unable to Install DeepSpeed

### ISSUE THREAD

**Issue by Lionel98** [microsoft/DeepSpeed#3635]
**To Reproduce**
!git clone https://github.com/microsoft/DeepSpeed -b v0.4.0
!DS_BUILD_OPS=1 pip install . (failed at this step)
Followed the steps from this --> (https://github.com/mallorbc/GPT_Neo_fine-tuning_notebook/blob/main/GPT_Neo_Fine-tune.ipynb)

**Expected behavior**
Succefully Installation

**Screenshots**

**System info (please complete the following information):**
 - OS: WSL Linux 22.04.2 LTS running on Windows 10 Machine
 - RTX 3070 GPU
 - Python 3.7.16
 - Torch 1.13.1
 - Conda Version 23.3.1

![image](https://github.com/microsoft/DeepSpeed/assets/92796786/c1cac205-71ae-4f16-ade4-451d8f8ec607)

**Additional context**
Trying to Train GPT-Neo via DeepSpeed. Any help will be welcomed Thank You

**Comment by junrong1** [comment]
Do you install the pytorch with cuda version

**Comment by eureka336** [comment]
you should first install torch.

**Comment by Lionel98** [comment]
Tyvm for your help. Much appreciated
