### ISSUE TITLE
[BUG] Model * GPU size memory required for tensor parallel inference

### ISSUE THREAD

**Issue by zhch12121** [microsoft/DeepSpeed#3644]
**Describe the bug**
If we set num_gpus to N, deepspeed will start N thread to load model, and each thread will take the full size of model memory. For example, if the model takes 80Gb memory, then if we set num_gpus to 8, the total memory needed is 80*8 = 640Gb. This is not a accessible volume even for most ML servers. Can I check if there's any workaround?

**To Reproduce**
```
deepspeed --num_gpus 8 DeepSpeedExamples/inference/huggingface/text-generation/inference-test.py --name decapoda-research/llama-65b-hf --batch_size 4 --test_performance --ds_inference
```
**Expected behavior**
Each thread shouldn't consume memory of full model size.

**Comment by henryxiao1997** [comment]
encounter the same issue, expecting the workaround

**Comment by molly-smith** [comment]
Hi @zhch12121, what version of DeepSpeed are you using?

**Comment by yangsp5** [comment]
encounter the same issue, I think this maybe work, but i don't konw which api can do:

```
loading the model on one thread, predshard the model and save. 
```

**Comment by liding1992** [comment]
encounter the same issue, expecting the workaround

**Comment by molly-smith** [comment]
Hi @liding1992 and all, you should be able to run using --use_meta_tensor flag and using checkpoints. I tested this on my side. Let know if that works for you.

**Comment by liding1992** [comment]
> Hi @liding1992 and all, you should be able to run using --use_meta_tensor flag and using checkpoints. I tested this on my side. Let know if that works for you.

I tested LLAMA-7B and LLAMA-13B and DeepSpeed worked.
### **here is my gpu info**
![image](https://github.com/microsoft/DeepSpeed/assets/125174298/732dd6d6-d939-4169-9cd1-350da2e7cf00)
### **here is my ds_report info**
![image](https://github.com/microsoft/DeepSpeed/assets/125174298/25900725-3e54-4baf-b627-65fd79c86601)
### **here is my package info**
centos 7.9
python 3.10.9
cuda 11.7
transformers 4.28.1
torch 1.13.1+cu117
### **here is my code**
```python
import sys
import time
import os
# New deepspeed path
sys.path.insert(0, '/Code/DeepSpeed')
import torch
import deepspeed
from transformers import LlamaForCausalLM, LlamaTokenizer
import argparse
from utils import Performance
from deepspeed.runtime.utils import see_memory_usage
from arguments import parser

args = parser.parse_args()
# here
deepspeed.init_distributed()

local_rank = int(os.environ.get('LOCAL_RANK', 0))
world_size = int(os.environ.get('WORLD_SIZE', 1))

print(f'local_rank: {local_rank}, world_size: {world_size}')

if args.local_rank == 0:
    see_memory_usage("before init", True)

t0 = time.time()
tokenizer = LlamaTokenizer.from_pretrained(args.model)
model = LlamaForCausalLM.from_pretrained(args.model)
if args.local_rank == 0:
    print(f"initialization time: {(time.time()-t0) * 1000}ms")
    see_memory_usage("after init", True)


model = deepspeed.init_inference(
    model,
    mp_size=world_size,
    dtype=torch.half,
    replace_with_kernel_inject=True
)
if args.local_rank == 0:
    see_memory_usage("after init_inference", True)


batch = tokenizer(
    #"The primary use of LLaMA is research on large language models, including",
    "DeepSpeed is a machine learning framework",
    return_tensors="pt",
    add_special_tokens=False
)
# here
batch = {k: v.cuda(local_rank) for k, v in batch.items()}
generated = model.generate(batch["input_ids"], max_length=args.max_new_tokens)

if args.local_rank == 0:
    print(f'in:{batch["input_ids"]}\nout:{tokenizer.decode(generated[0])}')
```
1*A10 
```shell
after init_inference
MA 12.81 GB         Max_MA 12.81 GB         CA 13.45 GB         Max_CA 13 GB
CPU Virtual Memory:  used = 8.83 GB, percent = 2.4%
```

2*A10
```shell
after init_inference
MA 6.65 GB         Max_MA 6.65 GB         CA 7.71 GB         Max_CA 8 GB
CPU Virtual Memory:  used = 11.04 GB, percent = 3.0%
```

**Comment by molly-smith** [comment]
Thanks @liding1992 for confirming. Closing this issue for now.
