### ISSUE TITLE
Partition activations brings no activation memory reduction in zero3

### ISSUE THREAD

**Issue by andrasiani** [microsoft/DeepSpeed#3652]
Hi, I am trying to run a gpt2 model with blocksize 2048, and I cannot use batchsize larger than 16 because activation memory becomes too large.

To reduce activation memory I already use deepspeed activation checkpointing on each transformer block +amp.

I saw there is an option to partition / shard activations too, advertized by megatron and presented in the zero paper under section 6.1. But when I try it I see no effect at all.
I tried partition_activations + cpu_activations + deepspeed act ckpt. No effect.

Can anyone help please or show some proof that this feature actually works. I am using lightning 1.9.4. Is there a particular version of deepspeed I should use?
I also posted this question on the lightning forum.

**Comment by andrasiani** [comment]
Related issue with github repo attached:
https://github.com/microsoft/DeepSpeed/issues/3779

**Comment by jomayeri** [comment]
Closing in preference to the other issue.
