### ISSUE TITLE
chatglm-6b can not use deepspeed inference[BUG]

### ISSUE THREAD

**Issue by zuocebianpingmao** [microsoft/DeepSpeed#3690]
Model * GPU size memory required for tensor parallel inference and it does not reduce latency
Are there any plans to support it?

**Comment by molly-smith** [comment]
Hi @guifeiwork , can you please provide more information about your setup and any errors you are seeing? And please provide a reproducer script. 

ds_report output
Please run ds_report to give us details about your setup.

System info (please complete the following information):
OS: [e.g. Ubuntu 18.04]
GPU count and types [e.g. two machines with x8 A100s each]
(if applicable) Hugging Face Transformers/Accelerate/etc. versions
Python version
Any other relevant info about your setup
