### ISSUE TITLE
[BUG] We cannot Use BF16 + ZeRO Stage 1

### ISSUE THREAD

**Issue by Desein-Yang** [microsoft/DeepSpeed#3693]
When I use bf16 + zero stage 1, the traceback is 'value''DeepSpeedZeroOptimizer' object has no attribute 'clear_lp_grads'.

I have print the optimizer and found it is a <deepspeed.runtime.zero.stage_1_and_2.DeepSpeedZeroOptimizer object> rather than the expected <deepspeed.runtime.bf16_optimizer.BF16_Optmizer object>. 

I think the bug results from runtime/engine.py

```
        if has_optimizer:
            self._configure_optimizer(optimizer, model_parameters)
            self._configure_lr_scheduler(lr_scheduler)
            self._report_progress(0)
        elif self.zero_optimization():
            # no optim selected but zero is enabled
            self.optimizer = self._configure_zero_optimizer(optimizer=None)
        elif self.bfloat16_enabled():
            self.optimizer = self._configure_bf16_optimizer(optimizer=None)
```
Here the optimizer is setting to ZeRO when the stage is 1 and cannot proceed, the the bf16 is incompatible with stage1 .

**Comment by jomayeri** [comment]
Hi @Desein-Yang can you provide 3 things.
1. A stacktrace of the error.
2. Your ds_config
3. What version of DeepSpeed you are running.

Thanks.

**Comment by Desein-Yang** [comment]
> Hi @Desein-Yang can you provide 3 things.
> 
> 1. A stacktrace of the error.
> 2. Your ds_config
> 3. What version of DeepSpeed you are running.
> 
> Thanks.

traceback
```
Traceback (most recent call last):
  File "/cognitive_comp/yangqi/project/gpt-neox/train.py", line 39, in <module>
    pretrain(neox_args=neox_args)    pretrain(neox_args=neox_args)

  File "/cognitive_comp/yangqi/project/gpt-neox/megatron/training.py", line 248, in pretrain
  File "/cognitive_comp/yangqi/project/gpt-neox/megatron/training.py", line 248, in pretrain
    iteration = train(
  File "/cognitive_comp/yangqi/project/gpt-neox/megatron/training.py", line 858, in train
    iteration = train(
    loss_dict, skipped_iter = train_step(  File "/cognitive_comp/yangqi/project/gpt-neox/megatron/training.py", line 858, in train

  File "/cognitive_comp/yangqi/project/gpt-neox/megatron/training.py", line 764, in train_step
    loss_dict, skipped_iter = train_step(
    reduced_loss = train_step_pipe(  File "/cognitive_comp/yangqi/project/gpt-neox/megatron/training.py", line 764, in train_step
    loss = model.train_batch(data_iter=data_iterator)
  File "/home/yangqi/anaconda3/envs/BBT2/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 336, in train_batch
    self._exec_schedule(sched)
    self._exec_schedule(sched)  File "/home/yangqi/anaconda3/envs/BBT2/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 1307, in _exec_schedule

  File "/home/yangqi/anaconda3/envs/BBT2/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 1307, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
    self._exec_instr(**cmd.kwargs)  File "/home/yangqi/anaconda3/envs/BBT2/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 727, in _exec_backward_pass

    self.optimizer.clear_lp_grads()  File "/home/yangqi/anaconda3/envs/BBT2/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 246, in _exec_reduce_grads

    if self.zero_optimization_stage() < ZeroStageEnum().gradients:AttributeError:
'DeepSpeedZeroOptimizer' object has no attribute 'clear_lp_grads'
TypeError: __call__() missing 1 required positional argument: 'value'
```

relevant ds_config  
```  
  "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True
  },
"precision": "bfloat16",
  "bf16": {
      "enabled": true
  },
  "fp32_allreduce": true, # without a patch to torch, bf16 models have to do the allreduce in fp32
  "gradient_accumulation_dtype":"fp16",
```


deepspeed 0.8.3 , 0.9.2 (I've tried 2 version but failed)

**Comment by zhangyipin** [comment]
I have run gpt-neox to pp + bf16 + zero1.
I meet similar mistake.
<img width="964" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/15236844/bbe35a27-54ba-4e85-8136-b75da7e34166">

ds_config:
"zero_optimization": {
    "stage": 1,
   },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 4,
   "data_impl": "mmap",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,

   # precision settings
   #"fp16": {
   "precision": "bfloat16",
   "bf16": {
     "enabled": true,
   },
   "gradient_accumulation_dtype": "bf16",
   "fp32_allreduce": true,

deepspeed == 0.9.2

**Comment by L-hongbin** [comment]
Hi @zhangyipin @Desein-Yang 
My deepspeed version == 0.9.3.
This problem is mainly because the optimizer is not BF16_Optmizer，and make optimizer_wrapper == bf16 need to meet three conditions: model_dtype == torch.bfloat16 and grad_accum_dtype == torch.float32 and zero_optimization_stage() == 1，so you can set `"data_types": {
    "grad_accum_dtype": "fp32"
  }` in deepspeed config to make the grad_accum_dtype == torch.float32

**Comment by zhangyipin** [comment]
thank you it works!

**Comment by SefaZeng** [comment]
> Hi @zhangyipin @Desein-Yang My deepspeed version == 0.9.3. This problem is mainly because the optimizer is not BF16_Optmizer，and make optimizer_wrapper == bf16 need to meet three conditions: model_dtype == torch.bfloat16 and grad_accum_dtype == torch.float32 and zero_optimization_stage() == 1，so you can set `"data_types": { "grad_accum_dtype": "fp32" }` in deepspeed config to make the grad_accum_dtype == torch.float32

Would this parameter occupy more GPU memory? It will raise CUDA OOM error with a 7B LLAMA model in TP=2 with 32 40G A100. As my opinion, the GPU memory only need (7/2) * 2 * 4 = 28 GB memory?
