### ISSUE TITLE
[BUG] Connection closed by localRank 1

### ISSUE THREAD

**Issue by Guodong0712** [microsoft/DeepSpeed#3712]
**Describe the bug**
I use deepspeed to train my model using 2 2080 Ti GPUs (no open bf16 mode) , but get the follow errors. And have no OOM error report.   The error log is shown as follow.
IP:52740:52806 [1] NCCL INFO [Service thread] Connection closed by localRank 1
IP:52740:52740 [1] NCCL INFO comm 0x55f4fcd08540 rank 1 nranks 2 cudaDev 1 busId 89000 - Abort COMPLETE
[2023-06-08 07:22:41,280] [INFO] [launch.py:350:main] Process 52740 exits successfully.

**Screenshots**
After training for a period of time, one of the GPUs will start having problems with its task, even though I am sure the GPU is not faulty. The red box in the screenshot shows the status of the two GPUs I used.
![image](https://github.com/microsoft/DeepSpeed/assets/46486353/5c7838af-c06d-4397-a319-f42df7270f77)

@wjessup @dfyz @manuelciosici @kobindra Excuse me, can anyone help me take a look at this issue? Or teach me how to display more log information. Many thanks.

**Comment by Guodong0712** [comment]
![image](https://github.com/microsoft/DeepSpeed/assets/46486353/1a1fa9f6-6cd5-4979-b6d2-ceba2e481cc4)

**Comment by Guodong0712** [comment]
At first, the program was alternating between printing log messages for 0  and 1 GPU, but later on, for some reason, the log messages for 1 GPU got stuck and there was no GPU OOM error reported. The problem screenshot is as follows:
![image](https://github.com/microsoft/DeepSpeed/assets/46486353/4863ffe9-351d-42f2-99d5-872233a04032)

**Comment by Guodong0712** [comment]
have solved it using the newest ds version.

**Comment by wnzhyee** [comment]
Hi, i use deepspeed 0.9.2 and meet same problems, which version do u use?

**Comment by yyyyyt123** [comment]
@wnzhyee Hi, have you find the correct version to avoid this problem? I met the same problem, the version I used is 0.10.2.
