### ISSUE TITLE
[REQUEST]can deepspeed support hybrid shard

### ISSUE THREAD

**Issue by QingruiSun** [microsoft/DeepSpeed#3721]
pytorch fsdp support hybrid shard which and reduce communication across machine, does deepspeed has similar config.
Thanks!

**Comment by samadejacobs** [comment]
Please check out recently released [ZeRO++](https://www.microsoft.com/en-us/research/blog/deepspeed-zero-a-leap-in-speed-for-llm-and-chat-model-training-with-4x-less-communication/) -- communication efficient ZeRO.

**Comment by najeeb5** [comment]
Hi, it seems that the newly released ZeRO++ is enabled only when using stage 3? 
In FSDP there's also a mode named "_HYBRID_SHARD_ZERO2" which is the same strategy but for stage 2 which doesn't seem to be supported in ZeRO++. 
I tried activating it via the config but it seemed to make no difference. Any help or pointers would be appreciated thanks!
