### ISSUE TITLE
gradient accumulation for stage 2

### ISSUE THREAD

**Issue by eric-haibin-lin** [microsoft/DeepSpeed#373]
> ZeRO stage 2 does not support gradient accumulation, if you need gradient accumulation please use stage 1

Stage 2 significantly reduces the memory footprint. Is there a plan to support gradient accumulation for stage 2? Thanks.

**Comment by ShadenSmith** [comment]
Thank you for you interest in DeepSpeed! We [just added](https://github.com/microsoft/DeepSpeed/pull/338) support for gradient accumulation in ZeRO-2. Please let us know if you run into any issues!

**Comment by gongjingcs** [comment]
hi, I see in ZeRO-2, communicates during non gradient accumulation boundaries as well
![image](https://user-images.githubusercontent.com/15030497/101722305-e7bfe700-3ae4-11eb-95b7-56a80e4a009b.png)
Is it for some reason? could you help me understand this? 
Looking forward to your reply

**Comment by woolpeeker** [comment]
I have the same question. why zero-2 need communicate gradient whether it is on the grad acc boundary?
