### ISSUE TITLE
Can you provide a startup script for deepspeed inference  llama 65B MP=8?

### ISSUE THREAD

**Issue by zcuuu** [microsoft/DeepSpeed#3744]

**Comment by lekurile** [comment]
Hi @zcuuu,

Can you please try the following command in our [text-generation inference examples](https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/text-generation/inference-test.py):

```
deepspeed --num_gpus 8 inference-test.py --name <model_name> --ds_inference
```

There is also a corresponding [README](https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/text-generation/README.md).

Thanks,
Lev
