### ISSUE TITLE
deepspeed installation [errno 20] not a directory "hipconfig"

### ISSUE THREAD

**Issue by haixpham** [microsoft/DeepSpeed#3814]
I have used Deepspeed successfully on local cluster before, and never ran into a problem But now I try to install deepspeed in a docker instance on a server farm, and it always fails with the message:
```
$ pip install deepspeed
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting deepspeed
  Downloading deepspeed-0.9.5.tar.gz (809 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 809.9/809.9 kB 681.1 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ib07ha2h/deepspeed_cc9082090f0746c4a17f9072a74b64be/setup.py", line 82, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-ib07ha2h/deepspeed_cc9082090f0746c4a17f9072a74b64be/op_builder/builder.py", line 39, in installed_cuda_version
          import torch.utils.cpp_extension
        File "/home/work/.conda/miniconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
          from .hipify import hipify_python
        File "/home/work/.conda/miniconda3/lib/python3.10/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
          from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
        File "/home/work/.conda/miniconda3/lib/python3.10/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
          rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
        File "/home/work/.conda/miniconda3/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/work/.conda/miniconda3/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/work/.conda/miniconda3/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/work/.conda/miniconda3/lib/python3.10/subprocess.py", line 1847, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I checked:
- CUDA is valid
- torch is valid, 1.13.1+cu11.7
- nvcc version = 11.7

Can anyone help explain to me what could go wrong?

TIA

**Comment by haixpham** [comment]
> Do you have a `CUDA_HOME` variable set?

Yes $CUDA_HOME was set correctly

**Comment by haixpham** [comment]
the error is raised right from this statement `import torch.utils.cpp_extension` so I think it's not a problem of any library but the container itself. I will ask the admin to check what you suggested about nvidia container toolkit and other options. Docker container is hidden behind a frontend so unfortunately I can't figure out how it was set up.

**Comment by jeffra** [comment]
Thanks for using DeepSpeed @haixpham, please re-open if you have further questions/issues on this. I'm optimistic this will be resolved via an environment update :)

**Comment by sdake** [comment]
This issue remains. I dug through hip, ugh, very difficult to install. I found this workaround:

https://github.com/pytorch/pytorch/issues/98629#issuecomment-1622954078

**Comment by wjmZZZ** [comment]
In conda's current environment, find the file **`cuda_to_hip_mappings.py`**, specifically `anaconda3/envs/llm/lib/python3.10/site-packages/torch/utils/hipify/cuda_to_hip_ mappings.py`

Modify **line 37** to add a **`NotADirectoryError`**
```
try.
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
except subprocess.
    print(f "Warning: hipconfig --rocmpath failed, assuming {rocm_path}")
except (FileNotFoundError, PermissionError, NotADirectoryError):: # Do not print warning.
    # This is okay. This file can also be imported for non-ROCm builds.
    This file can also be imported for non-ROCm builds. pass
```
This works for me.

**Comment by joslefaure** [comment]
I solved it with the following: 
`git clone https://github.com/ROCm-Developer-Tools/HIP.git`
`export PATH=$PATH:path/to/HIP/bin`

**Comment by master-chou** [comment]
> In conda's current environment, find the file **`cuda_to_hip_mappings.py`**, specifically `anaconda3/envs/llm/lib/python3.10/site-packages/torch/utils/hipify/cuda_to_hip_ mappings.py`
> 
> Modify **line 37** to add a **`NotADirectoryError`**
> 
> ```
> try.
>     rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
> except subprocess.
>     print(f "Warning: hipconfig --rocmpath failed, assuming {rocm_path}")
> except (FileNotFoundError, PermissionError, NotADirectoryError):: # Do not print warning.
>     # This is okay. This file can also be imported for non-ROCm builds.
>     This file can also be imported for non-ROCm builds. pass
> ```
> 
> This works for me.

Thanks, it's helpful to me!

**Comment by kkkwjr** [comment]
> 我通过以下方法解决了这个问题： `git clone https://github.com/ROCm-Developer-Tools/HIP.git` `export PATH=$PATH:path/to/HIP/bin`

that works ,thanks
