### ISSUE TITLE
`all_reduce_coalesced` used in MiCS is deprecated in PyTorch

### ISSUE THREAD

**Issue by learning-chip** [microsoft/DeepSpeed#3862]
MiCS uses `dist.all_reduce_coalesced` if available:

https://github.com/microsoft/DeepSpeed/blob/fc9e1ee00e673b2ce2a433c4e34c5440e76c9f3e/deepspeed/runtime/zero/mics.py#L435-L446

However in recent PyTorch this collective primitive [is deprecated](https://github.com/pytorch/pytorch/blob/v2.0.1/torch/distributed/distributed_c10d.py#L1743-L1747): `"torch.distributed.all_reduce_coalesced will be deprecated."`

Is the manually coalescing one (under `else`) equally fast and can be used as default?

Related: https://github.com/pytorch/pytorch/issues/64744, #2964

**Comment by jomayeri** [comment]
Thanks for the heads up. We currently check the torch version and that the attribute exists before we use that version of all_reduce. 

[See Here](https://github.com/search?q=repo%3Amicrosoft/DeepSpeed%20has_all_reduce_coalesced&type=code#:~:text=def%20has_all_reduce_coalesced()%3A,and%20torch_ver_ge_1_13())
