### ISSUE TITLE
[BUG] DeepSpeedGPTInference object has no attribute `dtype`

### ISSUE THREAD

**Issue by guifeiwork** [microsoft/DeepSpeed#3877]
Hello, I just started trying to learn to use DeepSpeed.

**Shouldn't `self.dtype` be `self.config.dtype`**

```py
DeepSpeed/deepspeed/model_implementations/transformers/ds_transformer.py

...
if (self.config.dtype in [torch.float16, torch.bfloat16, torch.int8]) \
    and input.dtype == torch.float:
    target_dtype = torch.half if self.dtype == torch.int8 else self.dtype # self.config.dtype
    input = input.to(target_dtype)
...
```
Thank you for your help!

**Comment by notoschord** [comment]
I meet the same issue, and try to set the dtype:
```
from deepspeed.model_implementations.transformers.ds_gpt import DeepSpeedGPTInference

engine = deepspeed.init_inference(model, dtype=torch.int8, use_triton=True, triton_autotune=True)
for layer in engine.module.model.layers:
    if isinstance(layer, DeepSpeedGPTInference):
        setattr(layer, 'dtype', torch.int8)
```
It works for me.

**Comment by molly-smith** [comment]
Hi @guifeiwork , can you please provide more information about your setup?

Which gpt model are you running?

ds_report output
Please run ds_report to give us details about your setup.

System info (please complete the following information):
OS: [e.g. Ubuntu 18.04]
GPU count and types [e.g. two machines with x8 A100s each]
(if applicable) Hugging Face Transformers/Accelerate/etc. versions
Python version
Any other relevant info about your setup
