### ISSUE TITLE
[REQUEST] Add timeout as entry-point option or environment variable

### ISSUE THREAD

**Issue by BramVanroy** [microsoft/DeepSpeed#3905]
**Is your feature request related to a problem? Please describe.**
I am using Hugging Face `transformers` for my deep learning, and it has a nice option to restrict specific processing to the main process only. This is useful if a function caches the result: the main process does the processing while the other processes wait, and when main is done, the other processes can just load from the cache. That's pretty neat.

The problem arises when these are long running processes. In distributed environment (torch or deepspeed, for instance), the communication between processes has a default timeout. If no communication has occurred for `timeout` seconds, the whole program will exit. 

**Describe the solution you'd like**

Both [`torch`](https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group) and [`deepspeed`](https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group) provide options in the Python init methods to set the timeout parameter to a higher value than the default 30 minutes, but this option is not available from the command-line or through an environment, which is what I would like.

**Describe alternatives you've considered**
I could make a custom fork but I think that this is something that more people might need as soon as they scale to larger projects.

**Additional context**

I can work on this, depending on what you suggest as a solution (CLI argument for the `deepspeed` command or as environment variable).

**Comment by BramVanroy** [comment]
I think the solution can be as simple as turning this line

https://github.com/microsoft/DeepSpeed/blob/60bf78454c976c59eb9a77ea9ef92ca863669886/deepspeed/constants.py#L18

Into 

```python
default_pg_timeout = timedelta(minutes=os.getenv("DEEPSPEED_TIMEOUT", default=30))
```

Any thoughts on this?

**Comment by phalexo** [comment]
This is actually causing quite a problem for me. I am investigating  "LongLora" repo, and it takes longer than 30 minutes to process the training dataset than 30 minutes, so the barrier on rank 0 process cannot rejoin the process group in time.

Unfortunately simply changing "default_pg_timeout" to a different value, does not appear to solve the problem. The constant is being passed in somewhere else, it appears.

I changed the source of that file, and I can print out the new value in the training script, but it still times out at 30 minutes.

**Comment by BramVanroy** [comment]
Maybe @mrwyattii knows where else the timeout is being set/overridden?

**Comment by phalexo** [comment]
> Maybe @mrwyattii knows where else the timeout is being set/overridden?

I posted a bug issue with deepspeed.com.com.monitored_barrier() that, if fixed, may allow to pass a timeout into it.

**Comment by phalexo** [comment]
Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00)
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from torch._C._distributed_c10d import _DEFAULT_PG_TIMEOUT
>>> print(_DEFAULT_PG_TIMEOUT)
0:30:00
>>>

A candidate from where the 30 minute timeout comes, despite the modification in deepspeed.

**Comment by BramVanroy** [comment]
@mrwyattii Can we reopen this so that the default from c10d can also be addressed?

**Comment by phalexo** [comment]
#pragma once

#include <condition_variable>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <unordered_map>
#include <utility>
#include <vector>

#include <ATen/ATen.h>
#include <c10/macros/Macros.h>

#include <torch/csrc/distributed/c10d/Work.hpp>
#include <torch/csrc/distributed/c10d/Types.hpp>
#include <torch/csrc/distributed/c10d/Utils.hpp>
#include <torch/csrc/distributed/c10d/debug.h>
#include <torch/csrc/distributed/c10d/sequence_num.hpp>

constexpr auto kBackendDefaultTimeout =
    std::chrono::milliseconds(30 * 60 * 1000);

namespace c10d {

class TORCH_API Backend : public torch::CustomClassHolder {
 public:

  // Backend Options is a base struct that defines the basic options
  // when constructing a Backend. Each Backend subclass should
  // extend this struct and define its options if it wants to provide more
  // config options (beyond basic ones defined here) to end user.

**Comment by phalexo** [comment]
> @mrwyattii Can we reopen this so that the default from c10d can also be addressed?

I just tried your fix for the timeout. It only works to the extent that I can print different settings in the training script.

The program still died around 31 minutes.  

It looks like the backend relies on the constant in the Backend,hpp and the env variable only changes it in one place, in Python.

**Comment by phalexo** [comment]
> @mrwyattii Can we reopen this so that the default from c10d can also be addressed?

There is yet another file ProcessGroup.hpp that defines yet another timeout with a different constant name.

**Comment by zpx01** [comment]
@phalexo were you able to resolve this issue, i'm having a similar problem with the longlora repo

**Comment by phalexo** [comment]
Not directly. I spent a bit of time debugging it and it seems that timeouts
are not respected by the code buried in C++.


Eventually I had

**Comment by phalexo** [comment]
I am responding from my phone, once I get back I will describe what was
causing the issue in my case. Maybe it is similar.

**Comment by phalexo** [comment]
The basic problem is dataset.map relies on the multiprocessing module. And
the multiprocessing module relies on "fork" to spawn processes. When "fork"
spawns
processes, depending on timing, it may copy locks in a locked state,
causing deadlocks. So the rank 0 thread/process can lock up and stop
responding to ranks > 0.
At some point they decide that rank == 0 died and cause a timeout exception.

The first thing you can do, is use non-threaded, NOT fast tokenizers. If
this is not enough, then you may have to change dataset.map  to code that
uses process pool
directly, but use "forkserver" instead of "fork" to avoid deadlocks.

**Comment by phalexo** [comment]
One more thing, barriers with a timeout are not implemented for NCCL
backend, just GLOO. It wouldn't help anyway because of the deadlocks.

**Comment by kdcyberdude** [comment]
Any updates on this?
