### ISSUE TITLE
[BUG] DeepSpeedEngine _load_zero_checkpoint

### ISSUE THREAD

**Issue by mypydl** [microsoft/DeepSpeed#3910]
**Describe the bug**
[DeepSpeedEngine._get_all_zero_checkpoints](https://github.com/microsoft/DeepSpeed/blob/fc9e1ee00e673b2ce2a433c4e34c5440e76c9f3e/deepspeed/runtime/engine.py#L2827-L2838)
In this function, `zero_ckpt_names` will never be `None`, at least `[]`. So this function will never return `None`, at least `[]`.

So, the variable `zero_sd_list` in [DeepSpeedEngine._load_zero_checkpoint](https://github.com/microsoft/DeepSpeed/blob/fc9e1ee00e673b2ce2a433c4e34c5440e76c9f3e/deepspeed/runtime/engine.py#L2762C21-L2762C21) will never be `None`, at least `[]`.
Then it will raise error, When there is no `zero_checkpoint` in the `checkpoint`.

**Expected behavior**
Fix this bug.

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU: 2080Ti x8 
 - Python version: 3.9
 - deepspeed version: 0.9.5

**Comment by tjruwase** [comment]
@mypydl, thanks for raising this issue. Do you currently have a repro that could help us investigate further?

**Comment by tjruwase** [comment]
Closing for lack of response. Please re-open if needed.
