### ISSUE TITLE
[BUG] single_node running example code meet error, 'The server socket has failed to bind to 0.0.0.0:29600 (errno: 98 - Address already in use).'

### ISSUE THREAD

**Issue by yeegnauh** [microsoft/DeepSpeed#3916]
**Describe the bug**
```
RuntimeError: The server socket has failed to listen on any local network
address. The server socket has failed to bind to [::]:29600 (errno: 98 - Address
already in use). The server socket has failed to bind to 0.0.0.0:29600 (errno:
98 - Address already in use).
```

**To Reproduce**
1 
in `training/step1_supervised_finetuning/training_scripts/single_node/run_1.3b.sh`
I set `deepspeed --master_port 29600 main.py \ ... `

2 
`nohup srun -p pat_rd --gres=gpu:8 -n 8 --ntasks-per-node 8 --exclusive python train.py --actor-model facebook/opt-1.3b --reward-model facebook/opt-350m --deployment-type single_node --step 1 --output ./output_fourDatasets_reproduce_withDropout_8gpu 2>&1 > single_node.log &`

**Expected behavior**

**ds_report output**
`[2023-07-10 15:48:56,237] [INFO] [comm.py:594:init_distributed] cdb=None
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /mnt/lustre/parrots.tester.s.02/huangye/DeepSpeedExamples/applications/DeepS │
│ peed-Chat/training/step1_supervised_finetuning/main.py:341 in <module>       │
│                                                                              │
│   338                                                                        │
│   339                                                                        │
│   340 if __name__ == "__main__":                                             │
│ ❱ 341 │   main()                                                             │
│   342                                                                        │
│                                                                              │
│ /mnt/lustre/parrots.tester.s.02/huangye/DeepSpeedExamples/applications/DeepS │
│ peed-Chat/training/step1_supervised_finetuning/main.py:186 in main           │
│                                                                              │
│   183 │   │   device = torch.device("cuda", args.local_rank)                 │
│   184 │   │   # Initializes the distributed backend which will take care of  │
│   185 │   │   # torch.distributed.init_process_group(backend='nccl')         │
│ ❱ 186 │   │   deepspeed.init_distributed()                                   │
│   187 │                                                                      │
│   188 │   args.global_rank = torch.distributed.get_rank()                    │
│   189                                                                        │
│                                                                              │
│ /mnt/cache/share/platform/env/miniconda3.7/envs/pt1.12v2/lib/python3.7/site- │
│ packages/deepspeed/comm/comm.py:627 in init_distributed                      │
│                                                                              │
│   624 │   │   │   if int(os.getenv('RANK', '0')) == 0:                       │
│   625 │   │   │   │   utils.logger.info('Initializing TorchBackend in DeepSp │
│   626 │   │   │   # Create a torch backend object, initialize torch distribu │
│ ❱ 627 │   │   │   cdb = TorchBackend(dist_backend, timeout, init_method, ran │
│   628                                                                        │
│   629                                                                        │
│   630 def mpi_discovery(distributed_port=TORCH_DISTRIBUTED_DEFAULT_PORT, ver │
│                                                                              │
│ /mnt/cache/share/platform/env/miniconda3.7/envs/pt1.12v2/lib/python3.7/site- │
│ packages/deepspeed/comm/torch.py:71 in __init__                              │
│                                                                              │
│    68 │   │   # The idea is to fake that dist backend is initialized even wh │
│    69 │   │   # it is not so we can run on a single GPU without doing any in │
│    70 │   │   self.single_gpu_mode = True                                    │
│ ❱  71 │   │   self.init_process_group(backend, timeout,init_method, rank, w │
│    72 │                                                                      │
│    73 │   @classmethod                                                       │
│    74 │   def get_all_gather_function(self):                                 │
│                                                                              │
│ /mnt/cache/share/platform/env/miniconda3.7/envs/pt1.12v2/lib/python3.7/site- │
│ packages/deepspeed/comm/torch.py:101 in init_process_group                   │
│                                                                              │
│    98 │   │   │   │   │   │   │   │   │   │   │   │    timeout=timeout,      │
│    99 │   │   │   │   │   │   │   │   │   │   │   │    init_method=init_meth │
│   100 │   │   │   │   │   │   │   │   │   │   │   │    rank=rank,            │
│ ❱ 101 │   │   │   │   │   │   │   │   │   │   │   │    world_size=world_size │
│   102 │   │   self.using_mpi = torch.distributed.get_backend() == 'mpi'      │
│   103 │                                                                      │
│   104 │   def all_reduce(self, tensor, op=torch.distributed.ReduceOp.SUM, gr │
│                                                                              │
│ /mnt/cache/share/platform/env/miniconda3.7/envs/pt1.12v2/lib/python3.7/site- │
│ packages/torch/distributed/distributed_c10d.py:595 in init_process_group     │
│                                                                              │
│    592 │   │   │   rendezvous_iterator = rendezvous(                         │
│    593 │   │   │   │   init_method, rank, world_size, timeout=timeout        │
│    594 │   │   │   )                                                         │
│ ❱  595 │   │   │   store, rank, world_size = next(rendezvous_iterator)       │
│    596 │   │   │   store.set_timeout(timeout)                                │
│    597 │   │   │                                                             │
│    598 │   │   │   # Use a PrefixStore to avoid accidental overrides of keys │
│                                                                              │
│ /mnt/cache/share/platform/env/miniconda3.7/envs/pt1.12v2/lib/python3.7/site- │
│ packages/torch/distributed/rendezvous.py:257 in _env_rendezvous_handler      │
│                                                                              │
│   254 │   master_addr = _get_env_or_raise("MASTER_ADDR")                     │
│   255 │   master_port = int(_get_env_or_raise("MASTER_PORT"))                │
│   256 │                                                                      │
│ ❱ 257 │   store = _create_c10d_store(master_addr, master_port, rank, world_s │
│   258 │                                                                      │
│   259 │   yield (store, rank, world_size)                                    │
│   260                                                                        │
│                                                                              │
│ /mnt/cache/share/platform/env/miniconda3.7/envs/pt1.12v2/lib/python3.7/site- │
│ packages/torch/distributed/rendezvous.py:189 in _create_c10d_store           │
│                                                                              │
│   186 │   else:                                                              │
│   187 │   │   start_daemon = rank == 0                                       │
│   188 │   │   return TCPStore(                                               │
│ ❱ 189 │   │   │   hostname, port, world_size, start_daemon, timeout, multi_t │
│   190 │   │   )                                                              │
│   191                                                                        │
│   192                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The server socket has failed to listen on any local network
address. The server socket has failed to bind to [::]:29600 (errno: 98 - Address
already in use). The server socket has failed to bind to 0.0.0.0:29600 (errno:
98 - Address already in use).
[2023-07-10 15:48:57,314] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 67159
`

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
`deepspeed` launcher

**Docker context**
slurm

**Additional context**

**Comment by yeegnauh** [comment]
it seems that still `TORCH_DISTRIBUTED_DEFAULT_PORT = 29500` take effect ....
this default master_port has already used by other people, so I want to specify a new port number , tried `deepspeed --master_port 29600 main.py ...`  doesn't work . (29600 has not been used yet)
who can help me ?

**Comment by mrwyattii** [comment]
@yeegnauh `--master_port 29600` is working. Your error message indicates that it's trying to connect on this port and is unable to:
`The server socket has failed to bind to [::]:29600`

Can you ensure that no other processes are using this port?

**Comment by yeegnauh** [comment]
> @yeegnauh `--master_port 29600` is working. Your error message indicates that it's trying to connect on this port and is unable to: `The server socket has failed to bind to [::]:29600`
> 
> Can you ensure that no other processes are using this port?

` lsof -i:29600` returns nothing. No other processes are using this port. 
If it's not this problem, what could be the reason？

**Comment by yeegnauh** [comment]
> take effect ....
> this default master_port has already used by other people, so I want to specify a new port number , tried `deepspeed --master_port 29600 main.py ...` doesn't w

@loadams 
nothing odd happening with 29600. 

after default port 29500 available, I tried the following operations separately：

1. run single_node with 29600 port：`The server socket has failed to bind to 0.0.0.0:29600 (errno:98 - Address already in use). `
2. single_gpu with 29600 port： normal training
3. single_node with default port：`The server socket has failed to bind to 0.0.0.0:29500 (errno:98 - Address already in use)`
4. single_gpu with default port：normal training

from the above👆 test results, problem seems unrelated to port, but can not training on `single node` machine。log only states  `The server socket has failed to bind to 0.0.0.0:29500 (errno:98 - Address already in use)`， how can I troubleshot the problem？

**Comment by yeegnauh** [comment]
My complete startup command is：
nohup srun -p partition --gres=gpu:$GPU -n $GPU --ntasks-per-node $GPU --exclusive python train.py --actor-model facebook/opt-1.3b --reward-model facebook/opt-350m --deployment-type single_node --step 1 --output ./test_single_node_29600_4gpu 2>&1 > test_single_node_29600_4gpu.log &

After extensive search, inspired by a torch document, I attempted to remove the parameters of train.py one by one。Finally, it can successfully train !
srun -p partition --exclusive python train.py --actor-model facebook/opt-1.3b --reward-model facebook/opt-350m --deployment-type single_node --step 1 --output ./test_single_node_29600_4gpu

It was the non essential srun parameters that caused the interference.
But I don't know why the single card situation hasn't been affected.

**Comment by Z-MU-Z** [comment]
same problem!  I remove --ntasks-per-node, and it works

**Comment by tonight-is-you** [comment]
--master_port 29600 works for me

**Comment by kxgong** [comment]
> ver socket has faile

Thank you, you solved my problem.

**Comment by huanranchen** [comment]
--master_port 29600 works for me, too
