### ISSUE TITLE
How do I resume training from stage1 with different GPUs ？

### ISSUE THREAD

**Issue by iMountTai** [microsoft/DeepSpeed#3924]
https://github.com/microsoft/DeepSpeed/pull/2284 probably supports this, but doesn't know how to use it.

**Comment by tjruwase** [comment]
@iMountTai, apologies for extremely delayed. Please reference the following guide: 
https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/universal_checkpointing/README.md
