### ISSUE TITLE
Deepspeed inference not support for chatglm 6b

### ISSUE THREAD

**Issue by Link-Li** [microsoft/DeepSpeed#3945]
I am using DeepSpeed for accelerating the inference process of my NLP tasks. I found that it works well with several popular models like GPT, BERT, etc. However, I noticed that it does not have support for the ChatGLM model. I would like to use DeepSpeed Inference with ChatGLM, but currently, it seems not to be supported.

chatglm: https://github.com/THUDM/ChatGLM-6B

Thank you!

**Comment by shyustc** [comment]
Which step encountered a problem, and what is the error message?

**Comment by molly-smith** [comment]
Hi @Link-Li, we currently support GLM with AutoTP but do not have plans to add ChatGLM support. You may be able to add AutoTP support easily if the architecture differences between GLM and ChatGLM are minor. Here's where GLM was added: https://github.com/microsoft/DeepSpeed/pull/3844
