### ISSUE TITLE
[REQUEST] Provide a list of Error codes

### ISSUE THREAD

**Issue by tpcgold** [microsoft/DeepSpeed#3949]
Provide a list of Error codes.
(or at least return something useful not like -9, -11 or another number nobody knows what error it is)

**Comment by mrwyattii** [comment]
Hi @tpcgold I understand your frustration, but it's not so straightforward to do this. The error codes that pop up are often coming from libraries we use or python itself and an exit code may not always mean the same thing, depending on its source! We try to provide useful error messages where we can. Is there an error that you are experiencing that we could help resolve?
