### ISSUE TITLE
[BUG] Build DeepSpeed wheel with torch nightly build v2.1.0.x+cu121 fails at asyn_io with std=c++14

### ISSUE THREAD

**Issue by wengyao04** [microsoft/DeepSpeed#3968]
**Describe the bug**
A clear and concise description of what the bug is. Please include which training step you are using and which model you are training.

We try to build DeepSpeed wheel with latest DeepSpeed release and nightly build torch2.1.0+cu121 and try to use it on H100 GPUs. 

However, we see error when build async_io
```
$PYTHON setup.py bdist_wheel

/opt/rh/devtoolset-12/root/usr/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -march=westmere -fno-semantic-interposition -fdebug-prefix-map=/tmp/python3.8-3.8.17-0=/opt/bb/src/python/python3.8 -g3 -frecord-gcc-switches -D_FORTIFY_SOURCE=2 -fstack-clash-protection -fstack-protector-strong -Wformat -Werror=format-security -I/opt/bb/include/ -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/opt/bb/lib/python3.8/site-packages/torch/include -I/opt/bb/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/bb/lib/python3.8/site-packages/torch/include/TH -I/opt/bb/lib/python3.8/site-packages/torch/include/THC -I/opt/bb/include/python3.8 -c csrc/aio/common/deepspeed_aio_utils.cpp -o build/temp.linux-x86_64-cpython-38/csrc/aio/common/deepspeed_aio_utils.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__SCALAR__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
```

```
/opt/bb/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.
    4 | #error C++17 or later compatible compiler is required to use PyTorch.
      |  ^~~~~
```
We need to override `-std=c++14` with `--std=c++17`, but async_io only have `std=c++14` as build options https://github.com/microsoft/DeepSpeed/blob/master/op_builder/async_io.py#L42

How could we bypass this and allow `-std=c++17` override ?

**Log output**
If you used `train.py` to launch the application, please include the contents of the output log file.

**To Reproduce**
1. Command/Script to reproduce
2. What packages are required and their versions
3. How to run the script
4. ...

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by wengyao04** [comment]
Hi @loadams Thank you very much, I am able to build deepspeed wheel (with torch nightly build v2.1.0.x+cu121) using your branch in the linked PR.

My gcc version is
```
bash-4.2# /opt/rh/devtoolset-12/root/usr/bin/gcc --version
gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by wengyao04** [comment]
Hi @loadams Could we merge your PR and create a patch for 0.9.5 ? Thx

**Comment by loadams** [comment]
Hi @wengyao04 - sorry for the delay, this should be fixed now from this [PR](https://github.com/microsoft/DeepSpeed/pull/4452/files#diff-e3311e3f399ceddcf3678ff196fe29a754a730e898471ae8129c6ba6ce6af637).  Please let us know if you are still having any problems with this.  We've also updated our torch-nightly CI to catch these issues sooner.

**Comment by wengyao04** [comment]
@loadams Thank you very much, I will remove our hack and pick up the fix from upstream !
