### ISSUE TITLE
[BUG] Using LOCAL_SIZE with CPU accelerator crashes on startup 

### ISSUE THREAD

**Issue by javsalgar** [microsoft/DeepSpeed#3970]
**Describe the bug**
When using `deepspeed` with CPU Accelerator and LOCAL_SIZE, the application crashes with this error

```
'str' object cannot be interpreted as an integer
```
This is because in this snippet we are not converting LOCAL_SIZE to integer.

`deepspeed/accelerator/cpu_accelerator.py`

```
    def device_count(self):
        device_count = int(os.environ.get('LOCAL_SIZE', 0))
        if device_count > 0:
            return os.environ.get('LOCAL_SIZE')

```

**To Reproduce**
1. Launch deepspeed with any example using `DS_ACCELERATOR=cpu` accelerator and setting `LOCAL_SIZE`
2. See error

**Expected behavior**
Training should take place

**System info (please complete the following information):**
 - OS: Debian 11
 - GPU count and types [e.g. two machines with x8 A100s each] 0
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB] 0
 - Python version 3.8
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else? Deepspeed launcher

**Docker context**
Are you using a specific docker image that you can share? Custom

**Additional context**

Created PR to fix it https://github.com/microsoft/DeepSpeed/pull/3971

**Comment by jomayeri** [comment]
Closing becasue PR fixed it.
