### ISSUE TITLE
how to using fusedadam in ds_config.json?

### ISSUE THREAD

**Issue by YooSungHyun** [microsoft/DeepSpeed#3990]
if i write down like this,
``` json
"optimizer": {
    "type": "FusedAdam"
},
```

error accur, "FusedAdam" is not supported optimizer_name()

if i use cuda and just "Adam", it automatically setting?

i'm using latest deepspeed version and A100 80GB 2EA, cuda 11.8

**Comment by tjruwase** [comment]
@YooSungHyun, yes, you just need to set as "Adam" to get FusedAdam on "cuda". Please more in this doc: https://www.deepspeed.ai/docs/config-json/#optimizer-parameters

**Comment by YooSungHyun** [comment]
oh thx!
