### ISSUE TITLE
[FAQ] how to install and run deepspeed with CPU only just to play and study purpose

### ISSUE THREAD

**Issue by gaowayne** [microsoft/DeepSpeed#4014]
**Describe the bug**
A clear and concise description of what the bug is. Please include which training step you are using and which model you are training.
just one FAQ question as title
**Log output**
If you used `train.py` to launch the application, please include the contents of the output log file.

**To Reproduce**
1. Command/Script to reproduce
2. What packages are required and their versions
3. How to run the script
4. ...

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by gaowayne** [comment]
> Hi @gaowayne - you'll install DeepSpeed the same way as if you had GPUs on your system. More instructions on that [here](https://www.deepspeed.ai/tutorials/advanced-install/). If you have problems/issues, please re-open this issue and let us know.

thank you so much I will try.

**Comment by Boltzmachine** [comment]
Did you work it out? I cannot find a way to do so and deepspeed does not work with `CUDA_VISIBLE_DEVICES=-1`.
