### ISSUE TITLE
[BUG] Inference errors with Llama2 

### ISSUE THREAD

**Issue by jnp** [microsoft/DeepSpeed#4027]
**Describe the bug**
I tried llama2-13b-chat model on 2 GPUs. The inference fails with error 
`
File "/opt/conda/envs/py39/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 310, in forward
key_states = key_states.view(bsz, q_len, self.num_key_value_heads, self.head_dim).transpose(1, 2)
RuntimeError: shape '[1, 8, 40, 128]' is invalid for input of size 20480"
`
I think the root cause of the issue is that llama2 is implemented for grouped-query attention (GQA, https://arxiv.org/pdf/2305.13245.pdf). Therefore it has a  new configuration for key value heads (num_key_value_heads) separate from num_heads which is used for query heads. Deepspeed doesn't handle this new configuration.

**To Reproduce**
`model_name = 'meta-llama/Llama-2-13b-chat-hf'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16)
ds_engine = deepspeed.init_inference(model,
                                 mp_size=2,
                                 dtype=torch.half,
                                 replace_with_kernel_inject=False)
model = ds_engine.module.to(f'cuda:{local_rank}')
input_string = ['The water came gushing down the']

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, device=local_rank, torch_dtype=torch.float16)
output = pipe(input_string)
`

**Expected behavior**
The inference should work correctly.

**ds_report output**

`---------------------------------------------`
DeepSpeed C++/CUDA extension op report
`---------------------------------------------`

NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
`--------------------------------------------------`
JIT compiled ops requires ninja
ninja .................. [OKAY]
`--------------------------------------------------`
op name ................ installed .. compatible
`--------------------------------------------------`
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
`--------------------------------------------------`
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/envs/py39/lib/python3.9/site-packages/torch']
torch version .................... 2.0.1+cu117
deepspeed install path ........... ['/opt/conda/envs/py39/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.10.0, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.0
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.1

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. 1 machine with 2 Nvidia-T4 ]
 - DeepSpeed version 0.10.0, transformers==4.31.0, torch==2.0.1
 - Python-3.9

**Comment by jnp** [comment]
I created a PR https://github.com/microsoft/DeepSpeed/pull/4028 which has a fix. It might help in clarifying the issue.

**Comment by mrwyattii** [comment]
Closing as this was resolved in #4022
