### ISSUE TITLE
[BUG]docker swarm cluster DeepSpeedExample training with multi-node unable to execute

### ISSUE THREAD

**Issue by sunxiaoyu12** [microsoft/DeepSpeed#4034]
When the code runs to ”deepspeed.initialize(model=model, model_parameters=model.parameters(), config=ds_config)“，the program unable to execute.
![65ce7f178d293a5e62d5de23950b141](https://github.com/microsoft/DeepSpeed/assets/38753856/dbaae252-3655-4f11-9b28-0fbbd8533912)

**Comment by mrwyattii** [comment]
@sunxiaoyu12 could you share a bit more information about your setup? In particular you will need to ensure that there is ssh access between cluster nodes for the DeepSpeed launcher to run multi-node.

Could you try a simple script and share if you are able to run that?
```python
# hello_world.py
import os
print(os.getenv("LOCAL_RANK"), os.getenv("WORLD_SIZE"))
```

Launch with `deepspeed --num_nodes 2 --num_gpus 2 hello_world.py` (please update the node and gpu count to match your hardware)

**Comment by sunxiaoyu12** [comment]
> 

Thank you for your reply, the problem has been solved, it is caused by the communication between nodes！Now I can run multi-node training normally
