### ISSUE TITLE
[BUG && REQUEST] Runnable examples of MoE GPT and PR-MoE GPT inference

### ISSUE THREAD

**Issue by YJHMITWEB** [microsoft/DeepSpeed#4038]
Hi, currently with several releases on the `DeepSpeed` branch and the `Megatron-DeepSpeed` branch, I find it very hard to run those examples provided in the repo due to compatibility issues. And I am also not sure at this moment, what are the compatible branches of `DeepSpeed` and `Megatron-DeepSpeed` that come with runnable examples of MoE GPT train/inference. 

For example, currently under `Megatron-DeepSpeed/examples_deepspeed/MoE`, those `MoE` training scripts actually do not use MoE at all, instead, they just leave the `num_experts=1` unchanged. 

Also, I am also wondering if there will be any runnable example of the PR-MoE GPT as described in the paper [https://arxiv.org/abs/2201.05596](url).

**Comment by conglongli** [comment]
This is not true. Under https://github.com/microsoft/Megatron-DeepSpeed/tree/main/examples_deepspeed/MoE, any script with "MoE" in their file names are MoE examples, any script with "PR-MoE" in their file names are PR-MoE examples, any script with "dense" in their file names are non-MoE dense model examples for comparison.
