### ISSUE TITLE
[BUG] CPU Adam failing

### ISSUE THREAD

**Issue by avivbrokman** [microsoft/DeepSpeed#4050]
**Describe the bug**
When I try to train using `deepspeed` and the huggingface `Trainer`, I get an error that cpu_adam.o failed.  It is possible this is not a `deepspeed` issue, but a `ninja` issue—this is far outside my expertise.

I can paste the entire error message, but I don't want to overwhelm any respondents.  I believe the relevant parts of the error are here:

Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -I/home/ubuntu/.local/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/usr/include -isystem /usr/lib/python3/dist-packages/torch/include -isystem /usr/lib/python3/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/lib/python3/dist-packages/torch/include/TH -isystem /usr/lib/python3/dist-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/usr/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX512__ -D__ENABLE_CUDA__ -DBF16_AVAILABLE -c /home/ubuntu/.local/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o 
FAILED: cpu_adam.o 
c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -I/home/ubuntu/.local/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/usr/include -isystem /usr/lib/python3/dist-packages/torch/include -isystem /usr/lib/python3/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/lib/python3/dist-packages/torch/include/TH -isystem /usr/lib/python3/dist-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/usr/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX512__ -D__ENABLE_CUDA__ -DBF16_AVAILABLE -c /home/ubuntu/.local/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o 
In file included from /usr/lib/python3/dist-packages/torch/include/torch/csrc/api/include/torch/python.h:11,
                 from /usr/lib/python3/dist-packages/torch/include/torch/extension.h:6,
                 from /home/ubuntu/.local/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp:7:
/usr/lib/python3/dist-packages/torch/include/torch/csrc/Exceptions.h:14:10: fatal error: pybind11/pybind11.h: No such file or directory
   14 | #include <pybind11/pybind11.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torch/utils/cpp_extension.py", line 1901, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**To Reproduce**
1. Install `transformers`: `pip install git+https://github.com/huggingface/transformers.git`
2. Clone `transformers` repo to use example scripts: `git clone https://github.com/huggingface/transformers.git`
3. Navigate to transformers repo: `cd transformers`
4. Run pytorch translation example with deepspeed:

```
deepspeed examples/pytorch/translation/run_translation.py \
    --model_name_or_path t5-small \
    --do_train \
    --source_lang en \
    --target_lang ro \
    --dataset_name wmt16 \
    --dataset_config_name ro-en \
    --output_dir /tmp/tst-translation \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir \
    --predict_with_generate \
    --max_train_samples 16 \
    --deepspeed tests/deepspeed/ds_config_zero3.json
```

**Expected behavior**
I expected the program to run

**ds_report output**

[2023-07-26 22:15:58,265] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-07-26 22:15:59.204933: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-26 22:15:59.245840: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX512F AVX512_VNNI, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING: No preset parameters were found for the device that Open MPI
detected:

  Local host:            192-9-138-111
  Device name:           mlx5_0
  Device vendor ID:      0x02c9
  Device vendor part ID: 4126

Default device parameters will be used, which may result in lower
performance.  You can edit any of the files specified by the
btl_openib_device_param_files MCA parameter to set values for your
device.

NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_no_device_params_found to 0.

No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           192-9-138-111
  Local device:         mlx5_0
  Local port:           1
  CPCs attempted:       udcm

/home/ubuntu/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

DeepSpeed C++/CUDA extension op report

NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.

JIT compiled ops requires ninja
ninja .................. [OKAY]

op name ................ installed .. compatible

 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]

DeepSpeed general environment info:
torch install path ............... ['/usr/lib/python3/dist-packages/torch']
torch version .................... 2.0.1
deepspeed install path ........... ['/home/ubuntu/.local/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.10.0, unknown, unknown
torch cuda version ............... 12.2
torch hip version ................ None
nvcc version ..................... 12.2
deepspeed wheel compiled w. ...... torch 2.0, cuda 12.2

**Screenshots**
Not applicable, I think.

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - GPU count and types: one machine with one A10
 - Interconnects (if applicable): N/A
 - Python version: 3.8.10
 - Any other relevant info about your setup: I'm using an instance from Lambda Labs using the Lambda Stack.

**Launcher context**
deepspeed launcher

**Docker context**
No Docker used

**Additional context**
I removed dashes from the `ds_report` output, as it does not play nice with Markdown.  You may want to change the format of the output so that it does play nicely.

**Comment by 4906772467937080** [comment]
{ "_links": { "self": { "href": "https://horizon.kuknos.org/transactions/9ecbb47c6078a44265a9b0b77fade490de7d7275e32cf09f0320d47b19bed179" }, "account": { "href": "https://horizon.kuknos.org/accounts/GCLP66FFKNYAZMZ2PTBBGFDQ67V5JBN7VPZ7KM54P3DXQ2BAD6ZX4I7G" }, "ledger": { "href": "https://horizon.kuknos.org/ledgers/20350505" }, "operations": { "href": "https://horizon.kuknos.org/transactions/9ecbb47c6078a44265a9b0b77fade490de7d7275e32cf09f0320d47b19bed179/operations{?cursor,limit,order}", "templated": true }, "effects": { "href": "https://horizon.kuknos.org/transactions/9ecbb47c6078a44265a9b0b77fade490de7d7275e32cf09f0320d47b19bed179/effects{?cursor,limit,order}", "templated": true }, "precedes": { "href": "https://horizon.kuknos.org/transactions?order=asc\u0026cursor=87404753432088576" }, "succeeds": { "href": "https://horizon.kuknos.org/transactions?order=desc\u0026cursor=87404753432088576" }, "transaction": { "href": "https://horizon.kuknos.org/transactions/9ecbb47c6078a44265a9b0b77fade490de7d7275e32cf09f0320d47b19bed179" } }, "id": "9ecbb47c6078a44265a9b0b77fade490de7d7275e32cf09f0320d47b19bed179", "paging_token": "87404753432088576", "successful": true, "hash": "9ecbb47c6078a44265a9b0b77fade490de7d7275e32cf09f0320d47b19bed179", "ledger": 20350505, "created_at": "2022-11-19T06:42:59Z", "source_account": "GCLP66FFKNYAZMZ2PTBBGFDQ67V5JBN7VPZ7KM54P3DXQ2BAD6ZX4I7G", "source_account_sequence": "85635437359530010", "fee_account": "GCLP66FFKNYAZMZ2PTBBGFDQ67V5JBN7VPZ7KM54P3DXQ2BAD6ZX4I7G", "fee_charged": "100000", "max_fee": "100000", "operation_count": 2, "envelope_xdr": "AAAAAgAAAACW/3ilU3AMszp8whMUcPfr1IW/q/P1M7x+x3hoIB+zfgABhqABMDz6AAAAGgAAAAEAAAAAAAAAAAAAAABjeHtoAAAAAAAAAAIAAAAAAAAABgAAAAFJUlJQAAAAAJ/3RgSJS9ocCZWqhTmpV1i6nKahsdFwfnpRjMF4ZXKXAAAAAABMS0AAAAAAAAAAAQAAAACDKBOhch9bmbbBkZpVhxvNq2+aWwdwWujnbrIQU+OvIgAAAAAAAAAAAvrwgAAAAAAAAAABIB+zfgAAAEAYo3DeWyYYdCKbs6I1KSJxieoxpwZtDDKdyL1TkgaWvIRGDVoJaYFI22h93mE9H7EgLF3zgOwclv2OlDA5hCcC", "result_xdr": "AAAAAAABhqAAAAAAAAAAAgAAAAAAAAAGAAAAAAAAAAAAAAABAAAAAAAAAAA=", "result_meta_xdr": "AAAAAgAAAAIAAAADATaGKQAAAAAAAAAAlv94pVNwDLM6fMITFHD369SFv6vz9TO8fsd4aCAfs34AAAAAB74d4AEwPPoAAAAZAAAABAAAAAEAAAAAjX8c2+eLhdarLC7vKRL4r29MGqdXjpanAj1KLGmKNWYAAAAAAAAADXd3dy5rdWtub3MuaXIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQE2hikAAAAAAAAAAJb/eKVTcAyzOnzCExRw9+vUhb+r8/UzvH7HeGggH7N+AAAAAAe+HeABMDz6AAAAGgAAAAQAAAABAAAAAI1/HNvni4XWqywu7ykS+K9vTBqnV46WpwI9SixpijVmAAAAAAAAAA13d3cua3Vrbm9zLmlyAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAIAAAADAAAAAwE2hikAAAAAAAAAAJb/eKVTcAyzOnzCExRw9+vUhb+r8/UzvH7HeGggH7N+AAAAAAe+HeABMDz6AAAAGgAAAAQAAAABAAAAAI1/HNvni4XWqywu7ykS+K9vTBqnV46WpwI9SixpijVmAAAAAAAAAA13d3cua3Vrbm9zLmlyAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEBNoYpAAAAAAAAAACW/3ilU3AMszp8whMUcPfr1IW/q/P1M7x+x3hoIB+zfgAAAAAHvh3gATA8+gAAABoAAAAFAAAAAQAAAACNfxzb54uF1qssLu8pEvivb0wap1eOlqcCPUosaYo1ZgAAAAAAAAANd3d3Lmt1a25vcy5pcgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAATaGKQAAAAEAAAAAlv94pVNwDLM6fMITFHD369SFv6vz9TO8fsd4aCAfs34AAAABSVJSUAAAAACf90YEiUvaHAmVqoU5qVdYupymobHRcH56UYzBeGVylwAAAAAAAAAAAAAAAABMS0AAAAAAAAAAAAAAAAAAAAAEAAAAAwE2evMAAAAAAAAAAIMoE6FyH1uZtsGRmlWHG82rb5pbB3Ba6OdushBT468iAAAACohp+4AAf3sHAAAACAAAAAQAAAABAAAAAI1/HNvni4XWqywu7ykS+K9vTBqnV46WpwI9SixpijVmAAAAAAAAAA13d3cua3Vrbm9zLmlyAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEBNoYpAAAAAAAAAACDKBOhch9bmbbBkZpVhxvNq2+aWwdwWujnbrIQU+OvIgAAAAqLZOwAAH97BwAAAAgAAAAEAAAAAQAAAACNfxzb54uF1qssLu8pEvivb0wap1eOlqcCPUosaYo1ZgAAAAAAAAANd3d3Lmt1a25vcy5pcgAAAAEAAAAAAAAAAAAAAAAAAAAAAAADATaGKQAAAAAAAAAAlv94pVNwDLM6fMITFHD369SFv6vz9TO8fsd4aCAfs34AAAAAB74d4AEwPPoAAAAaAAAABQAAAAEAAAAAjX8c2+eLhdarLC7vKRL4r29MGqdXjpanAj1KLGmKNWYAAAAAAAAADXd3dy5rdWtub3MuaXIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQE2hikAAAAAAAAAAJb/eKVTcAyzOnzCExRw9+vUhb+r8/UzvH7HeGggH7N+AAAAAATDLWABMDz6AAAAGgAAAAUAAAABAAAAAI1/HNvni4XWqywu7ykS+K9vTBqnV46WpwI9SixpijVmAAAAAAAAAA13d3cua3Vrbm9zLmlyAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA=", "fee_meta_xdr": "AAAAAgAAAAMBNoYaAAAAAAAAAACW/3ilU3AMszp8whMUcPfr1IW/q/P1M7x+x3hoIB+zfgAAAAAHv6SAATA8+gAAABkAAAAEAAAAAQAAAACNfxzb54uF1qssLu8pEvivb0wap1eOlqcCPUosaYo1ZgAAAAAAAAANd3d3Lmt1a25vcy5pcgAAAAEAAAAAAAAAAAAAAAAAAAAAAAABATaGKQAAAAAAAAAAlv94pVNwDLM6fMITFHD369SFv6vz9TO8fsd4aCAfs34AAAAAB74d4AEwPPoAAAAZAAAABAAAAAEAAAAAjX8c2+eLhdarLC7vKRL4r29MGqdXjpanAj1KLGmKNWYAAAAAAAAADXd3dy5rdWtub3MuaXIAAAABAAAAAAAAAAAAAAAAAAAA", "memo_type": "none", "signatures": [ "GKNw3lsmGHQim7OiNSkicYnqMacGbQwynci9U5IGlryERg1aCWmBSNtofd5hPR+xICxd84DsHJb9jpQwOYQnAg==" ], "valid_after": "1970-01-01T00:00:00Z", "valid_before": "2022-11-19T06:44:56Z" }

**Comment by tjruwase** [comment]
@avivbrokman, your error log suggests a missing dependency: pybind11
![image](https://github.com/microsoft/DeepSpeed/assets/4271600/eea4aa7e-1799-4b0a-bdbe-5dcf3c03f72c)
