### ISSUE TITLE
Deepspeed Multinode training doesnt reduce memory usage

### ISSUE THREAD

**Issue by VRSupriya** [microsoft/DeepSpeed#4066]
I am attempting Multi-node training of Falcon 7B with Peft using DeepSpeed and Accelerate. During single node training, it takes up 39GB of GPU memory. However, in multi-node training, both machines consume 40GB of memory. Shouldn't it reduce memory usage?

**Expected behavior**
Reduce the memory usage 

**ds_report output**

[2023-07-31 08:56:06,593] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [YES] ...... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [YES] ...... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.1.0+9e3e10c5ed), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/anaconda3/envs/venv/lib/python3.10/site-packages/torch']
torch version .................... 2.0.0+cu117
deepspeed install path ........... ['/anaconda3/envs/venv/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.0, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 12.0
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7

**System info (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server 7.8 (Maipo)
 - 2 machines with 1 GPU in each (A100-80GB)
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version = 3.10.12
 

**Launcher context**

accelerate launch --config_file ds_zero3_multinode.yaml run_clm_no_trainer_lora.py --model_name_or_path "tiiuae/falcon-7b" --dataset_name "train.json" --block_size 2048 --learning_rate 3e-5 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --num_train_epochs 10 --num_warmup_steps 2000 --checkpointing_steps 1000 --preprocessing_num_workers 8 --with_tracking --output_dir "output/lora_test" --report_to "tensorboard"

** The accelerate congiruation file **

compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: zero_stage3_offload_config.json
  deepspeed_hostfile: /path/to/hostfile
  deepspeed_multinode_launcher: pdsh
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_process_ip: <machine1>
main_process_port: <port>
main_training_function: main
num_machines: 2
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**host file**
machine1 slots=1
machine2 slots=1

**Deepspeed conf file** : ds_zero3_multinode.yaml 

  {
      "fp16": {
          "enabled": false,
          "loss_scale": 1024,
          "loss_scale_window": 1000,
          "initial_scale_power": 4,
          "hysteresis": 2,
          "min_loss_scale": 1
      },
      "bf16": {
          "enabled":true
      },
      "optimizer": {
          "type": "Adamw",
          "params": {
              "lr": "auto",
              "weight_decay": "auto"
          }
      },
      "scheduler": {
          "type": "WarmupLR",
          "params": {
              "warmup_min_lr": "auto",
              "warmup_max_lr": "auto",
              "warmup_num_steps": "auto"
          }
      },
      "zero_optimization": {
          "stage": 3,
          "offload_optimizer": {
              "device": "cpu",
              "pin_memory": true
          },
          "offload_param": {
              "device": "cpu",
              "pin_memory": true
          },
          "overlap_comm": true,
          "contiguous_gradients": true,
          "sub_group_size": 1e9,
          "reduce_bucket_size": "auto",
          "stage3_prefetch_bucket_size": "auto",
          "stage3_param_persistence_threshold": "auto",
          "stage3_max_live_parameters": 1e7,
          "stage3_max_reuse_distance": 1e7,
          "stage3_gather_16bit_weights_on_model_save": true
      },
      "gradient_accumulation_steps": "auto",
      "gradient_clipping": "auto",
      "steps_per_print": 1,
      "train_batch_size": "auto",
      "train_micro_batch_size_per_gpu": "auto",
      "wall_clock_breakdown": true
  }

**code**
  
  import argparse
  import json
  import logging
  import math
  import os
  import random
  from itertools import chain
  from pathlib import Path
  
  import datasets
  import torch
  from accelerate import Accelerator, DistributedType
  from accelerate.logging import get_logger
  from accelerate.utils import set_seed
  from datasets import load_dataset
  from huggingface_hub import Repository, create_repo
  from torch.utils.data import DataLoader
  from tqdm.auto import tqdm
  import psutil
  import gc
  import threading
  import transformers
  from transformers import (
      CONFIG_MAPPING,
      MODEL_MAPPING,
      AutoConfig,
      AutoModelForCausalLM,
      AutoTokenizer,
      SchedulerType,
      default_data_collator,
      get_scheduler,
  )
  from transformers.utils import check_min_version, get_full_repo_name, send_example_telemetry
  from transformers.utils.versions import require_version
  from peft import LoraConfig, TaskType, get_peft_model
  from peft.utils.other import fsdp_auto_wrap_policy
  from accelerate.utils import DummyOptim,DummyScheduler
  from deepspeed.runtime.utils import see_memory_usage
  
  logger = get_logger(__name__)

  MODEL_CONFIG_CLASSES = list(MODEL_MAPPING.keys())
  MODEL_TYPES = tuple(conf.model_type for conf in MODEL_CONFIG_CLASSES)
  
  def b2mb(x):
      return int(x / 2**20)
  
  def parse_args():
      parser = argparse.ArgumentParser(description="Finetune a transformers model on a causal language modeling task")
      parser.add_argument(
          "--dataset_name",
          type=str,
          default=None,
          help="The name of the dataset to use (via the datasets library).",
      )
      parser.add_argument(
          "--dataset_config_name",
          type=str,
          default=None,
          help="The configuration name of the dataset to use (via the datasets library).",
      )
      parser.add_argument(
          "--train_file", type=str, default=None, help="A csv or a json file containing the training data."
      )
      parser.add_argument(
          "--validation_file", type=str, default=None, help="A csv or a json file containing the validation data."
      )
      parser.add_argument(
          "--validation_split_percentage",
          default=1,
          help="The percentage of the train set used as validation set in case there's no validation split",
      )
      parser.add_argument(
          "--model_name_or_path",
          type=str,
          help="Path to pretrained model or model identifier from huggingface.co/models.",
          required=False,
      )
      parser.add_argument(
          "--config_name",
          type=str,
          default=None,
          help="Pretrained config name or path if not the same as model_name",
      )
      parser.add_argument(
          "--tokenizer_name",
          type=str,
          default=None,
          help="Pretrained tokenizer name or path if not the same as model_name",
      )
      parser.add_argument(
          "--use_slow_tokenizer",
          action="store_true",
          help="If passed, will use a slow tokenizer (not backed by the 🤗 Tokenizers library).",
      )
      parser.add_argument(
          "--per_device_train_batch_size",
          type=int,
          default=8,
          help="Batch size (per device) for the training dataloader.",
      )
      parser.add_argument(
          "--per_device_eval_batch_size",
          type=int,
          default=8,
          help="Batch size (per device) for the evaluation dataloader.",
      )
      parser.add_argument(
          "--learning_rate",
          type=float,
          default=5e-5,
          help="Initial learning rate (after the potential warmup period) to use.",
      )
      parser.add_argument("--weight_decay", type=float, default=0.0, help="Weight decay to use.")
      parser.add_argument("--num_train_epochs", type=int, default=3, help="Total number of training epochs to perform.")
      parser.add_argument(
          "--max_train_steps",
          type=int,
          default=None,
          help="Total number of training steps to perform. If provided, overrides num_train_epochs.",
      )
      parser.add_argument(
          "--gradient_accumulation_steps",
          type=int,
          default=1,
          help="Number of updates steps to accumulate before performing a backward/update pass.",
      )
      parser.add_argument(
          "--lr_scheduler_type",
          type=SchedulerType,
          default="linear",
          help="The scheduler type to use.",
          choices=["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"],
      )
      parser.add_argument(
          "--num_warmup_steps", type=int, default=0, help="Number of steps for the warmup in the lr scheduler."
      )
      parser.add_argument("--output_dir", type=str, default=None, help="Where to store the final model.")
      parser.add_argument("--seed", type=int, default=None, help="A seed for reproducible training.")
      parser.add_argument(
          "--model_type",
          type=str,
          default=None,
          help="Model type to use if training from scratch.",
          choices=MODEL_TYPES,
      )
      parser.add_argument(
          "--block_size",
          type=int,
          default=None,
          help=(
              "Optional input sequence length after tokenization. The training dataset will be truncated in block of"
              " this size for training. Default to the model max input length for single sentence inputs (take into"
              " account special tokens)."
          ),
      )
      parser.add_argument("--use_group_texts",action="store_true")
      parser.add_argument(
          "--preprocessing_num_workers",
          type=int,
          default=None,
          help="The number of processes to use for the preprocessing.",
      )
      parser.add_argument(
          "--overwrite_cache", action="store_true", help="Overwrite the cached training and evaluation sets"
      )
      parser.add_argument(
          "--no_keep_linebreaks", action="store_true", help="Do not keep line breaks when using TXT files."
      )
      parser.add_argument("--push_to_hub", action="store_true", help="Whether or not to push the model to the Hub.")
      parser.add_argument(
          "--hub_model_id", type=str, help="The name of the repository to keep in sync with the local `output_dir`."
      )
      parser.add_argument("--hub_token", type=str, help="The token to use to push to the Model Hub.")
      parser.add_argument(
          "--checkpointing_steps",
          type=str,
          default=None,
          help="Whether the various states should be saved at the end of every n steps, or 'epoch' for each epoch.",
      )
      parser.add_argument(
          "--resume_from_checkpoint",
          type=str,
          default=None,
          help="If the training should continue from a checkpoint folder.",
      )
      parser.add_argument(
          "--with_tracking",
          action="store_true",
          help="Whether to enable experiment trackers for logging.",
      )
      parser.add_argument(
          "--report_to",
          type=str,
          default="all",
          help=(
              'The integration to report the results and logs to. Supported platforms are `"tensorboard"`,'
              ' `"wandb"`, `"comet_ml"` and `"clearml"`. Use `"all"` (default) to report to all integrations.'
              "Only applicable when `--with_tracking` is passed."
          ),
      )
      args = parser.parse_args()
      # Sanity checks
      if args.dataset_name is None and args.train_file is None and args.validation_file is None:
          raise ValueError("Need either a dataset name or a training/validation file.")
      else:
          if args.train_file is not None:
              extension = args.train_file.split(".")[-1]
              assert extension in ["csv", "json", "txt"], "`train_file` should be a csv, json or txt file."
          if args.validation_file is not None:
              extension = args.validation_file.split(".")[-1]
              assert extension in ["csv", "json", "txt"], "`validation_file` should be a csv, json or txt file."
  
      if args.push_to_hub:
          assert args.output_dir is not None, "Need an `output_dir` to create a repo when `--push_to_hub` is passed."
  
      return args
  def main():
      args = parse_args()

      # Sending telemetry. Tracking the example usage helps us better allocate resources to maintain them. The
      # information sent is the one passed as arguments along with your Python/PyTorch versions.
      send_example_telemetry("run_clm_no_trainer", args)
  
      # Initialize the accelerator. We will let the accelerator handle device placement for us in this example.
      # If we're using tracking, we also need to initialize it here and it will by default pick up all supported trackers
      # in the environment
      accelerator_log_kwargs = {}
  
      if args.with_tracking:
          accelerator_log_kwargs["log_with"] = args.report_to
          # accelerator_log_kwargs["logging_dir"] = args.output_dir
  
      accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, **accelerator_log_kwargs)
  
      # Make one log on every process with the configuration for debugging.
      logging.basicConfig(
          format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
          datefmt="%m/%d/%Y %H:%M:%S",
          level=logging.INFO,
      )
      logger.info(accelerator.state, main_process_only=False)
      if accelerator.is_local_main_process:
          datasets.utils.logging.set_verbosity_warning()
          transformers.utils.logging.set_verbosity_info()
      else:
          datasets.utils.logging.set_verbosity_error()
          transformers.utils.logging.set_verbosity_error()
  
      # If passed along, set the training seed now.
      if args.seed is not None:
          set_seed(args.seed)
  
      # Handle the repository creation
      if accelerator.is_main_process:
          if args.push_to_hub:
              if args.hub_model_id is None:
                  repo_name = get_full_repo_name(Path(args.output_dir).name, token=args.hub_token)
              else:
                  repo_name = args.hub_model_id
              create_repo(repo_name, exist_ok=True, token=args.hub_token)
              repo = Repository(args.output_dir, clone_from=repo_name, token=args.hub_token)
  
              with open(os.path.join(args.output_dir, ".gitignore"), "w+") as gitignore:
                  if "step_*" not in gitignore:
                      gitignore.write("step_*\n")
                  if "epoch_*" not in gitignore:
                      gitignore.write("epoch_*\n")
          elif args.output_dir is not None:
              os.makedirs(args.output_dir, exist_ok=True)
      accelerator.wait_for_everyone()
  
      # Get the datasets: you can either provide your own CSV/JSON/TXT training and evaluation files (see below)
      # or just provide the name of one of the public datasets available on the hub at https://huggingface.co/datasets/
      # (the dataset will be downloaded automatically from the datasets Hub).
      #
      # For CSV/JSON files, this script will use the column called 'text' or the first column if no column called
      # 'text' is found. You can easily tweak this behavior (see below).
      #
      # In distributed training, the load_dataset function guarantee that only one local process can concurrently
      # download the dataset.
      if args.dataset_name is not None:
          # Downloading and loading a dataset from the hub.
          raw_datasets = load_dataset("json",data_files=args.dataset_name)
          if "validation" not in raw_datasets.keys():
              raw_datasets["validation"] = load_dataset(
                  "json",
                  data_files=args.dataset_name,
                  split=f"train[:{args.validation_split_percentage}%]",
              )
              raw_datasets["train"] = load_dataset(
                  "json",
                  data_files=args.dataset_name,
                  split=f"train[{args.validation_split_percentage}%:]",
              )
      else:
          data_files = {}
          dataset_args = {}
          if args.train_file is not None:
              data_files["train"] = args.train_file
          if args.validation_file is not None:
              data_files["validation"] = args.validation_file
          extension = args.train_file.split(".")[-1]
          if extension == "txt":
              extension = "text"
              dataset_args["keep_linebreaks"] = not args.no_keep_linebreaks
          raw_datasets = load_dataset(extension, data_files=data_files, **dataset_args)
          # If no validation data is there, validation_split_percentage will be used to divide the dataset.
          if "validation" not in raw_datasets.keys():
              raw_datasets["validation"] = load_dataset(
                  extension,
                  data_files=data_files,
                  split=f"train[:{args.validation_split_percentage}%]",
                  **dataset_args,
              )
              raw_datasets["train"] = load_dataset(
                  extension,
                  data_files=data_files,
                  split=f"train[{args.validation_split_percentage}%:]",
                  **dataset_args,
              )
  
      # See more about loading any type of standard or custom dataset (from files, python dict, pandas DataFrame, etc) at
      # https://huggingface.co/docs/datasets/loading_datasets.html.
  
      # Load pretrained model and tokenizer
      #
      # In distributed training, the .from_pretrained methods guarantee that only one local process can concurrently
      # download model & vocab.
      if args.config_name:
          config = AutoConfig.from_pretrained(args.config_name,trust_remote_code=True)
      elif args.model_name_or_path:
          config = AutoConfig.from_pretrained(args.model_name_or_path,trust_remote_code=True)
      else:
          config = CONFIG_MAPPING[args.model_type]()
          logger.warning("You are instantiating a new config instance from scratch.")
  
      if args.tokenizer_name:
          tokenizer = AutoTokenizer.from_pretrained(args.tokenizer_name, use_fast=not args.use_slow_tokenizer,trust_remote_code=True,cache_dir = "../cache",)
      elif args.model_name_or_path:
          tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path, use_fast=not args.use_slow_tokenizer,trust_remote_code=True,cache_dir = "../cache",)
      else:
          raise ValueError(
              "You are instantiating a new tokenizer from scratch. This is not supported by this script."
              "You can do it from another script, save it, and load it from here, using --tokenizer_name."
          )
      tokenizer.pad_token = tokenizer.eos_token
      if args.model_name_or_path:
          model = AutoModelForCausalLM.from_pretrained(
              args.model_name_or_path,
              from_tf=bool(".ckpt" in args.model_name_or_path),
              config=config,
              trust_remote_code=True,
              cache_dir = "../cache",
          )
      else:
          logger.info("Training new model from scratch")
          model = AutoModelForCausalLM.from_config(config)
  
  
      # Preprocessing the datasets.
      # First we tokenize all the texts.
      column_names = raw_datasets["train"].column_names
      #text_column_name = "text" if "text" in column_names else column_names[0]
  
      def generate_prompt(data_point):
          data_point["full_prompt"]= f"""Below is an instruction that describes a task, paired with context and input. Write a response that appropriately completes the request.  # noqa: E501
      ### Instruction:
      {data_point["instruction"]}
      ### Context:
      {data_point["context"]}
      ### Input:
      {data_point["input"]}
      ### Response:
      {data_point["output"]}"""
          return data_point
  
      raw_datasets =raw_datasets.map(generate_prompt)
          
      def tokenize_function(examples):
          result = tokenizer(examples["full_prompt"],
                           padding='max_length' if not args.use_group_texts else False,
                           truncation=True if not args.use_group_texts else False,
                           max_length = args.block_size)
          result["labels"] = result["input_ids"].copy()
          return result
  
      with accelerator.main_process_first():
          tokenized_datasets = raw_datasets.map(
              tokenize_function,
              batched=True,
              num_proc=args.preprocessing_num_workers,
              remove_columns=column_names,
              load_from_cache_file=not args.overwrite_cache,
              desc="Running tokenizer on dataset",
          )
  
      if args.block_size is None:
          block_size = tokenizer.model_max_length
          # if block_size > 1024:
          #     logger.warning(
          #         "The chosen tokenizer supports a `model_max_length` that is longer than the default `block_size` value"
          #         " of 1024. If you would like to use a longer `block_size` up to `tokenizer.model_max_length` you can"
          #         " override this default with `--block_size xxx`."
          #     )
          # block_size = 1024
      else:
          if args.block_size > tokenizer.model_max_length:
              logger.warning(
                  f"The block_size passed ({args.block_size}) is larger than the maximum length for the model"
                  f"({tokenizer.model_max_length}). Using block_size={tokenizer.model_max_length}."
              )
          block_size = min(args.block_size, tokenizer.model_max_length)
  
      # Main data processing function that will concatenate all texts from our dataset and generate chunks of block_size.
      def group_texts(examples):
          # Concatenate all texts.
          concatenated_examples = {k: list(chain(*examples[k])) for k in examples.keys()}
          total_length = len(concatenated_examples[list(examples.keys())[0]])
          # We drop the small remainder, we could add padding if the model supported it instead of this drop, you can
          # customize this part to your needs.
          if total_length >= block_size:
              total_length = (total_length // block_size) * block_size
          # Split by chunks of max_len.
          result = {
              k: [t[i : i + block_size] for i in range(0, total_length, block_size)]
              for k, t in concatenated_examples.items()
          }
          result["labels"] = result["input_ids"].copy()
          return result
  
      # Note that with `batched=True`, this map processes 1,000 texts together, so group_texts throws away a remainder
      # for each of those groups of 1,000 texts. You can adjust that batch_size here but a higher value might be slower
      # to preprocess.
      #
      # To speed up this part, we use multiprocessing. See the documentation of the map method for more information:
      # https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasets.Dataset.map
  
      with accelerator.main_process_first():
          if args.use_group_texts:
              lm_datasets = tokenized_datasets.map(
                  group_texts,
                  batched=True,
                  num_proc=args.preprocessing_num_workers,
                  load_from_cache_file=not args.overwrite_cache,
                  desc=f"Grouping texts in chunks of {block_size}",
              )
          else:
              lm_datasets = tokenized_datasets
      train_dataset = lm_datasets["train"]
      eval_dataset = lm_datasets["validation"]
      train_dataset =train_dataset.remove_columns(["token_type_ids"])
      eval_dataset =eval_dataset.remove_columns(["token_type_ids"])
      # Log a few random samples from the training set:
      for index in random.sample(range(len(train_dataset)), 3):
          logger.info(f"Sample {index} of the training set: {train_dataset[index]}.")
  
      # DataLoaders creation:
      train_dataloader = DataLoader(
          train_dataset, shuffle=True, collate_fn=default_data_collator, batch_size=args.per_device_train_batch_size
      )
      
      eval_dataloader = DataLoader(
          eval_dataset, collate_fn=default_data_collator, batch_size=args.per_device_eval_batch_size
      )
      LORA_TARGET_MODULES = [
          "query_key_value",
          "dense"
      ]
      peft_config = LoraConfig(
          task_type=TaskType.CAUSAL_LM, inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1,target_modules=LORA_TARGET_MODULES,bias="none"
      )
      model = get_peft_model(model, peft_config)
  
      # Optimizer
      # Split weights in two groups, one with weight decay and the other not.
      # no_decay = ["bias", "layer_norm.weight"]
      # optimizer_grouped_parameters = [
      #     {
      #         "params": [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)],
      #         "weight_decay": args.weight_decay,
      #     },
      #     {
      #         "params": [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)],
      #         "weight_decay": 0.0,
      #     },
      # ]
  
      # Creates Dummy Optimizer if `optimizer` was spcified in the config file else creates Adam Optimizer
      optimizer_cls = (
          torch.optim.AdamW
          if accelerator.state.deepspeed_plugin is None
             or "optimizer" not in accelerator.state.deepspeed_plugin.deepspeed_config
          else DummyOptim
      )
      optimizer = optimizer_cls(model.parameters(), lr=args.learning_rate)
  
      # Scheduler and math around the number of training steps.
      overrode_max_train_steps = False
      num_update_steps_per_epoch = math.ceil(len(train_dataloader) / args.gradient_accumulation_steps)
      if args.max_train_steps is None:
          args.max_train_steps = args.num_train_epochs * num_update_steps_per_epoch
          overrode_max_train_steps = True
  
          # Creates Dummy Scheduler if `scheduler` was spcified in the config file else creates `args.lr_scheduler_type` Scheduler
      if (
              accelerator.state.deepspeed_plugin is None
              or "scheduler" not in accelerator.state.deepspeed_plugin.deepspeed_config
      ):
          lr_scheduler = get_scheduler(
              name=args.lr_scheduler_type,
              optimizer=optimizer,
              num_warmup_steps=args.num_warmup_steps * args.gradient_accumulation_steps,
              num_training_steps=args.max_train_steps * args.gradient_accumulation_steps,
          )
      else:
          lr_scheduler = DummyScheduler(
              optimizer, total_num_steps=args.max_train_steps, warmup_num_steps=args.num_warmup_steps
          )
  
  
      is_ds_zero_3 = False
      if getattr(accelerator.state, "deepspeed_plugin", None):
          is_ds_zero_3 = accelerator.state.deepspeed_plugin.zero_stage == 3
  
      # Prepare everything with our `accelerator`.
      model, optimizer, train_dataloader, eval_dataloader, lr_scheduler = accelerator.prepare(
          model, optimizer, train_dataloader, eval_dataloader, lr_scheduler
      )
      accelerator.print(model.print_trainable_parameters())
      # On TPU, the tie weights in our model have been disconnected, so we need to restore the ties.
      if accelerator.distributed_type == DistributedType.TPU:
          model.tie_weights()
  
      # We need to recalculate our total training steps as the size of the training dataloader may have changed.
      num_update_steps_per_epoch = math.ceil(len(train_dataloader) / args.gradient_accumulation_steps)
      if overrode_max_train_steps:
          args.max_train_steps = args.num_train_epochs * num_update_steps_per_epoch
      # Afterwards we recalculate our number of training epochs
      args.num_train_epochs = math.ceil(args.max_train_steps / num_update_steps_per_epoch)
  
      # Figure out how many steps we should save the Accelerator states
      checkpointing_steps = args.checkpointing_steps
      if checkpointing_steps is not None and checkpointing_steps.isdigit():
          checkpointing_steps = int(checkpointing_steps)
  
      # We need to initialize the trackers we use, and also store our configuration.
      # The trackers initializes automatically on the main process.
      if args.with_tracking:
          experiment_config = vars(args)
          # TensorBoard cannot log Enums, need the raw value
          experiment_config["lr_scheduler_type"] = experiment_config["lr_scheduler_type"].value
          accelerator.init_trackers("clm_no_trainer", experiment_config)
  
      # Train!
      total_batch_size = args.per_device_train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps
  
      logger.info("***** Running training *****")
      logger.info(f"  Num examples = {len(train_dataset)}")
      logger.info(f"  Num Epochs = {args.num_train_epochs}")
      logger.info(f"  Instantaneous batch size per device = {args.per_device_train_batch_size}")
      logger.info(f"  Total train batch size (w. parallel, distributed & accumulation) = {total_batch_size}")
      logger.info(f"  Gradient Accumulation steps = {args.gradient_accumulation_steps}")
      logger.info(f"  Total optimization steps = {args.max_train_steps}")
      # Only show the progress bar once on each machine.
      progress_bar = tqdm(range(args.max_train_steps), disable=not accelerator.is_local_main_process)
      completed_steps = 0
      starting_epoch = 0
  
      # Potentially load in the weights and states from a previous save
      if args.resume_from_checkpoint:
          if args.resume_from_checkpoint is not None or args.resume_from_checkpoint != "":
              accelerator.print(f"Resumed from checkpoint: {args.resume_from_checkpoint}")
              accelerator.load_state(args.resume_from_checkpoint)
              path = os.path.basename(args.resume_from_checkpoint)
          else:
              # Get the most recent checkpoint
              dirs = [f.name for f in os.scandir(os.getcwd()) if f.is_dir()]
              dirs.sort(key=os.path.getctime)
              path = dirs[-1]  # Sorts folders by date modified, most recent checkpoint is the last
          # Extract `epoch_{i}` or `step_{i}`
          training_difference = os.path.splitext(path)[0]
  
          if "epoch" in training_difference:
              starting_epoch = int(training_difference.replace("epoch_", "")) + 1
              resume_step = None
          else:
              # need to multiply `gradient_accumulation_steps` to reflect real steps
              resume_step = int(training_difference.replace("step_", "")) * args.gradient_accumulation_steps
              starting_epoch = resume_step // len(train_dataloader)
              resume_step -= starting_epoch * len(train_dataloader)
  
      # update the progress_bar if load from checkpoint
      progress_bar.update(starting_epoch * num_update_steps_per_epoch)
      completed_steps = starting_epoch * num_update_steps_per_epoch
      with accelerator.main_process_first():
          torch.cuda.empty_cache()
      for epoch in range(starting_epoch, args.num_train_epochs):
          model.train()
          if args.with_tracking:
              total_loss = 0
          for step, batch in enumerate(train_dataloader):
              # We need to skip steps until we reach the resumed step
              if args.resume_from_checkpoint and epoch == starting_epoch:
                  if resume_step is not None and step < resume_step:
                      if step % args.gradient_accumulation_steps == 0:
                          progress_bar.update(1)
                          completed_steps += 1
                      continue
              # with accelerator.accumulate(model):
              see_memory_usage(f'before forward {model.global_steps}', force=True)
              outputs = model(**batch)
              loss = outputs.loss
              # We keep track of the loss at each epoch
              if args.with_tracking:
                  total_loss += loss.detach().cpu().float()
              see_memory_usage(f'before backward {model.global_steps}', force=True)
              accelerator.backward(loss)
              see_memory_usage(f'before optimizer {model.global_steps}', force=True)
              optimizer.step()
              lr_scheduler.step()
              optimizer.zero_grad()
              see_memory_usage(f'after optimizer {model.global_steps}', force=True)
              # Checks if the accelerator has performed an optimization step behind the scenes
              # if accelerator.sync_gradients:
              progress_bar.update(1)
              completed_steps += 1
              if isinstance(checkpointing_steps, int):
                  if completed_steps % checkpointing_steps == 0:
                      output_dir = f"step_{completed_steps }"
                      if args.output_dir is not None:
                          output_dir = os.path.join(args.output_dir, output_dir)
                      accelerator.save_state(output_dir)
              if completed_steps >= args.max_train_steps:
                  break
  
          model.eval()
          losses = []
          for step, batch in enumerate(eval_dataloader):
              with torch.no_grad():
                  outputs = model(**batch)
  
              loss = outputs.loss
              losses.append(accelerator.gather_for_metrics(loss.repeat(args.per_device_eval_batch_size)))
  
          losses = torch.cat(losses)
          try:
              eval_loss = torch.mean(losses)
              perplexity = math.exp(eval_loss)
          except OverflowError:
              perplexity = float("inf")
  
          logger.info(f"epoch {epoch}: perplexity: {perplexity} eval_loss: {eval_loss}")
  
          if args.with_tracking:
              accelerator.log(
                  {
                      "perplexity": perplexity,
                      "eval_loss": eval_loss,
                      "train_loss": total_loss.item() / len(train_dataloader),
                      "epoch": epoch,
                      "step": completed_steps,
                  },
                  step=completed_steps,
              )
  
          if args.push_to_hub and epoch < args.num_train_epochs - 1:
              accelerator.wait_for_everyone()
              unwrapped_model = accelerator.unwrap_model(model)
              unwrapped_model.save_pretrained(
                  args.output_dir, is_main_process=accelerator.is_main_process, save_function=accelerator.save
              )
              if accelerator.is_main_process:
                  tokenizer.save_pretrained(args.output_dir)
                  repo.push_to_hub(
                      commit_message=f"Training in progress epoch {epoch}", blocking=False, auto_lfs_prune=True
                  )
  
          if args.checkpointing_steps == "epoch":
              output_dir = f"epoch_{epoch}"
              if args.output_dir is not None:
                  output_dir = os.path.join(args.output_dir, output_dir)
              accelerator.save_state(output_dir)
  
      if args.with_tracking:
          accelerator.end_training()
  
      if args.output_dir is not None:
          accelerator.wait_for_everyone()
          unwrapped_model = accelerator.unwrap_model(model)
          unwrapped_model.save_pretrained(
              args.output_dir, is_main_process=accelerator.is_main_process, save_function=accelerator.save
          )
          if accelerator.is_main_process:
              tokenizer.save_pretrained(args.output_dir)
              if args.push_to_hub:
                  repo.push_to_hub(commit_message="End of training", auto_lfs_prune=True)
  
              with open(os.path.join(args.output_dir, "all_results.json"), "w") as f:
                  json.dump({"perplexity": perplexity}, f)
  if __name__ == "__main__":
      main()

** Log**
[log.txt](https://github.com/microsoft/DeepSpeed/files/12214044/log.txt)

**Comment by jomayeri** [comment]
The optimizer states and parameters make up the bulk of the model state. Because you have offloaded both to the CPU the added benefit you will get by training across multiple GPUs is not memory reduction but an ability to increase batch size.

**Comment by deanpeterson** [comment]
This question deserves a better answer. I've been trying to do exactly the same thing and it appears deepspeed just makes the memory requirements larger. I've been trying for months to do distributed training with things like falcon-7b with no luck. I have 6 nodes each with a 24gb gpu. I found a model that would work but it's tiny and even though the deepspeed calculator says it should only need 34gb total, all 6 nodes use over 20gb of vram for a total of 120gb. I also feel like I am missing something obvious. I don't think deepspeed zero3 actually saves any memory consumption.
