### ISSUE TITLE
Pipeline throughput is incorrect

### ISSUE THREAD

**Issue by aveni** [microsoft/DeepSpeed#407]
I think the throughput should be ```tput = self.train_batch_size() * self.steps_per_print() / elapsed ```. Right now it is not taking into account the logging frequency.

https://github.com/microsoft/DeepSpeed/blob/4ac9bf60a740a5a8433ee256c48527c0fba63beb/deepspeed/runtime/pipe/engine.py#L277

**Comment by ShadenSmith** [comment]
Good catch, thanks! I added that status line at the last minute and must have only tested with logging frequency 1.

This should be fixed in #408 .
