### ISSUE TITLE
[QUESTION] Do not understand the meaning of the formula estimate_zero2_model_states_mem_needs

### ISSUE THREAD

**Issue by KevinNuNu** [microsoft/DeepSpeed#4076]
from [this](https://deepspeed.readthedocs.io/en/latest/memory.html#deepspeed.runtime.zero.stage_1_and_2.estimate_zero2_model_states_mem_needs_all_live)

![image](https://github.com/microsoft/DeepSpeed/assets/34083603/59cf0626-7061-4a09-b6f1-654d5b82e0ed)

I'm confuse about:
question1: when zero-2 offload=False,
（1）why params is fp32(4 bytes，use  `4 * params`)？If it's calculated as non-amp training, why the gradient and optimizer states partition use ` 16 * params/ (total number of gpus)`，  Isn't it 4+8？
（2）On the contrary， if  ` 16 * params/ (total number of gpus)` stand for amp training ( 4bytes gradient + 8bytes optimizer states + 4bytes params)，how to understand ``4 * params`？

question2: when zero-3 offload=False,
largest_layer_memory = 4*largest_layer_params is because `2 bytes fp16 params are gathered and 2 bytes fp16 grads are computed (total 4x)`.  But i can‘t understand why `The optimizer states and fp32 parameters are updated in partitioned form and copied to fp16 params in partitioned form` (8bytes + 4bytes + 2bytes) will use `18 * params `？

I am looking forward to your reply， thank u~

**Comment by tjruwase** [comment]
Question 1
 `4 * params`: This is 2 bytes of parameter and 2 bytes for gradient.
`16 * params`:  This is 4 bytes of parameter, 8 bytes of optimizer state, and 4 bytes of gradient partitioned across all GPUs.  Required for fp32 optimizer computation. 

Question 2
`18 * params`: The optimizer state is 16 bytes, as shown above. Case 3, where the entire optimizer state is offloaded, helps to show that the extra 2 bytes is a temporary fp16 param buffer for copying the updates to the main fp16 param. This is an implementation convenience.

**Comment by KevinNuNu** [comment]
> This is an implementation convenience.

Thank you for your reply.

The question 2 i understand, but the question 1 i am still confused：
If 4 params represent 2bytes param and 2bytes gradient, where is the gradient partition reflected? Doesn’t each GPU here still load the full fp16 gradient for total params, only optimizer states partition?

**Comment by KevinNuNu** [comment]
> Question 1 `4 * params`: This is 2 bytes of parameter and 2 bytes for gradient. `16 * params`: This is 4 bytes of parameter, 8 bytes of optimizer state, and 4 bytes of gradient partitioned across all GPUs. Required for fp32 optimizer computation.
> 
> Question 2 `18 * params`: The optimizer state is 16 bytes, as shown above. Case 3, where the entire optimizer state is offloaded, helps to show that the extra 2 bytes is a temporary fp16 param buffer for copying the updates to the main fp16 param. This is an implementation convenience.

Thank you for your reply.

The question 2 i understand, but the question 1 i am still confused：
If 4 params represent 2bytes param and 2bytes gradient, where is the gradient partition reflected? Doesn’t each GPU here still load the full fp16 gradient for total params, only optimizer states partition?

**Comment by tjruwase** [comment]
I think I see your point. `4 * params` should either be:
-  `2 * params` if we ignore partitioned gradients or 
- `2 * params + 2 * params / (total number of gpus)` if we consider partitioned gradients.

**Comment by KevinNuNu** [comment]
I read the document again and found such a description：
<img width="749" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/34083603/e5d146fa-ff0e-4aaf-b60b-90faff9784c7">

Does this mean the formula of ZeRO-2 w/o cpu_offload should be `2 * params + 20 * params / total number of gpus`?
`2 * params `: This is 2 bytes of parameter ( do not partition）
`20 * params / total number of gpus`:  2 bytes of gradients(stored) + 4 bytes of gradients(converted into fp32 during optimizer step) + 8 bytes of optimizer states + 4 bytes of params + 2 bytes of params (you mentioned above the temporary fp16 param buffer for copying the updates to the main fp16 param)？
