### ISSUE TITLE
[BUG]How to compile without NCCL dependency?

### ISSUE THREAD

**Issue by hzrlsd** [microsoft/DeepSpeed#4104]
On my hardware platform Jeton Orin, the system does not support NCCL libraries。So how to compile this library?

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU :Jetson AGX Orin 
 - CPU: ARM64v8
 - Python :3.8.10
 - CUDA:11.4

**Comment by tjruwase** [comment]
A communication collective library, such as NCCL, is a requirement for distributed deep learning, and for the Pytorch framework. DeepSpeed can be ported to any accelerator and communication library by following this [guide](https://github.com/microsoft/DeepSpeed/blob/master/docs/_tutorials/accelerator-abstraction-interface.md).

**Comment by hzrlsd** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法亲自回复您的邮件。我会尽快给您回复。
