### ISSUE TITLE
Is --deepspeed argument in use?

### ISSUE THREAD

**Issue by gameveloster** [microsoft/DeepSpeed#4109]
I'm using the `deepspeed` command from deepspeed 0.10.0. How do I know if the `--deepspeed` argument is actually loading the json config file and using it?

I do not see `--deepspeed` argument in `deepspeed --help`.

Running the following code with a non-existant `ds_config.json` file does not throw any errors

    deepspeed foo.py --deepspeed ds_config.json

I see several places where `--deepspeed` argument is used together with `deepspeed` command. For example, in this [markdown page](https://github.com/lm-sys/FastChat/blob/bdac99a6b877320bd22241be68b4cb7b568a1830/docs/training.md):
```
deepspeed fastchat/train/train_lora.py \
    # ...
    --deepspeed playground/deepspeed_config_s2.json \
```

**Comment by mrwyattii** [comment]
@gameveloster If you looks into the `train_lora.py` script you linked, they are using the `HfArgumentParser` from `transformers` which provides the `--deepspeed` command line option: https://github.com/lm-sys/FastChat/blob/5b245e8b01af59b409ab4cdb98d9b8f4078956ef/fastchat/train/train_lora.py#L105

Commands specific to `deepspeed` must come before the python script you are running. For example:
```bash
deepspeed --num_nodes 1 --num_gpus 2 example.py
```

Any options after the script name will need to be parsed by the script itself:
```bash
deepspeed --num_nodes 1 --num_gpus 2 example.py --my-script-opt1 --my-script-opt2
```
