### ISSUE TITLE
[REQUEST] Reducing CPU Memory Footprint during Model and Optimizer Initialization 

### ISSUE THREAD

**Issue by Line290** [microsoft/DeepSpeed#4148]
Is there a method to mitigate the initial memory overhead during the start of training?

Here are my observations while using DeepSpeed stage 2:

> 

Loading the N B model on nGPUs in the DeepSpeed stage-2 process:

1. Each GPU starts a process that constructs the network in memory, with network parameters occupying a certain amount of memory per process: 4N GB or 2N GB (fp32 or fp16). In the case of fp16, it occupies nGPUs * 2N GB of memory space.

2. nGPUs divide the entire optimizer state, gradients, and fp32 parameter copies, utilizing DeepSpeed to initialize optimizer states (first-order, second-order), gradient, and fp32 parameter copies in memory. This requires a total of (4 + 4 + 2 + 4) * N = 14N GB of memory space, where each card or process occupies 14/nGPUs GB of memory space.

3. Distribute the 2*N GB parameters and 14N/nGPUs GB optimizer components to different GPUs.

Hence, the memory requirement is at least nGPUs * 2N GB + 14N GB of space.

For example, when training a 13B model using 8 GPUs, 
- each card occupies 26GB of space in memory to store fp16 parameters, totaling 208 GB for all 8 cards. 
- The "optimizer state, gradients, and fp32 parameter copies" on the 8 cards together occupy 14 * 13 = 182 GB of memory space. 

Therefore, the total memory space required is 208 GB + 182 GB = 390 GB.

>

**Comment by Honesty-of-the-Cavernous-Tissue** [comment]
@Line290 Actually it's not DeepSpeed bug!
i'm faced exactly the same question when using Zero-stage2, when loading Llama-2-7b takes 220+gb RAM and Llama-2-13b going up to OOM (my device only have 250gb RAM)
in my case, The questions is LlamaForCausalLM.from_pretrained(model_name_or_path) loading  shards on cpu by default, adding the parameter `device_map`=`auto` will resolve it
moreover, the loading weights is defaulted on fp32, u need set `torch_dtype`=`torch.float16` see at [https://discuss.huggingface.co/t/llama-7b-gpu-memory-requirement/34323](url)
Additional, i also set `low_cpu_mem_usage`=`True`
Last, `device_map`=`auto` and `low_cpu_mem_usage`=`True` mismatch with Zero-stage3
Hope it works for you😛

**Comment by samadejacobs** [comment]
Thanks @Honesty-of-the-Cavernous-Tissue for your input. Closing as resolved.

**Comment by Line290** [comment]
@Honesty-of-the-Cavernous-Tissue I tried it but failed.
