### ISSUE TITLE
multi-node training error

### ISSUE THREAD

**Issue by yangzhipeng1108** [microsoft/DeepSpeed#4149]
![image](https://github.com/microsoft/DeepSpeed/assets/33448441/5b3834f6-1cde-4d35-9048-dafc45ffa6bb)

**Comment by yangzhipeng1108** [comment]
this is the DeepSpeed config, thanks
![image](https://github.com/microsoft/DeepSpeed/assets/33448441/b7aa7d07-1682-4c72-820a-74bd8c3046d1)

**Comment by mrwyattii** [comment]
@yangzhipeng1108 What are the values of `GLOBAL_BATCH_SIZE` and `MICRO_BATCH_SIZE`? You are not setting `gradient_accumulation_steps` in the config, which means that the value will be computed based on those other 2 values here:
https://github.com/microsoft/DeepSpeed/blob/19e9a7c0284cc886d84afd7ec58721af5e045811/deepspeed/runtime/config.py#L911

Please ensure that those are integer values, perhaps by doing `int(GLOBAL_BATCH_SIZE)` and `int(MICRO_BATCH_SIZE)`.

**Comment by yangzhipeng1108** [comment]
thanks
