### ISSUE TITLE
Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: ds_config_zero2.json

### ISSUE THREAD

**Issue by AderonHuang** [microsoft/DeepSpeed#4156]
![image](https://github.com/microsoft/DeepSpeed/assets/43173636/5d9ac173-82cd-498f-a2d6-6a3fd7a4d8d0)
It happen this error, anyone konw how to solve?

**Comment by EeyoreLee** [comment]
maybe the relative path of deepspeed config json is incorrect. try the absolute path or fixing the relative path.

**Comment by pengjayson** [comment]
how did you solve this problem?

**Comment by loadams** [comment]
I would check the relative path, or try specifying an absolute path.  If those aren't able to fix it, can you share your ds_config and the command you are specifying?

**Comment by loadams** [comment]
No, the path of the ds_config that you are specifying in your command.  If you are still having issues, please open a new issue and we can take a look at your issue.  Thanks!

**Comment by AderonHuang** [comment]
Thanks, I solved it


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/10/23,
08:51:44 AM

Logan Adams ***@***.***> 于2023年10月9日周一 22:51写道：

**Comment by zhmingzhaung** [comment]
how to solve the problem？

**Comment by loadams** [comment]
@zhmingzhaung - if you are still hitting an issue like this one, can you please share the full error here or open a new issue?  Thanks!

**Comment by Elizabeth819** [comment]
I had the same error using deepspeed in axolotl, how did you solve the problem？

**Comment by crispchris** [comment]
Make sure the path is correct and the file actually exists. Relative folders do work, even "../path/to/theconf.json" I got this error just because the file was in another path.
