### ISSUE TITLE
[REQUEST] How to use inference

### ISSUE THREAD

**Issue by UncleFB** [microsoft/DeepSpeed#4166]
If I have a server for inference, how can I use DS to do inference on multiple GPUs at the same time. The example can only start a script through the command line, but I need to integrate it into the server code.
![image](https://github.com/microsoft/DeepSpeed/assets/38581531/1dae8597-a1d7-41b7-8c1a-5f2c285fab37)

**Comment by mrwyattii** [comment]
@UncleFB We have documentation and example code for how to use DeepSpeed-Inference here: https://www.deepspeed.ai/tutorials/inference-tutorial/

**Comment by mrwyattii** [comment]
I think this is beyond the scope of help that I can provide.

You may find our project [DeepSpeed-MII](https://github.com/microsoft/DeepSpeed-mii) useful. It allows you to setup an inference server running a model using DeepSpeed. It also provides the capability to load multiple model replicas and a load balancer to interface with. So you can stand up an MII deployment and have your server processes send/receive requests with the MII load balancer.
