### ISSUE TITLE
FusedLamb error

### ISSUE THREAD

**Issue by Soroushmehr1** [microsoft/DeepSpeed#4187]
I am running large Bert model from HuggingFace on AzureML. When I defined "FusedLamb" as an optimizer in ds_config.json, I had this error: AssertionError: FusedLamb is not a supported DeepSpeed Optimizer. Then I used "Lamb" (according to https://huggingface.co/docs/transformers/main_classes/deepspeed) but had this error: (AssertionError: You are using an untested ZeRO Optimizer. Please add <"zero_allow_untested_optimizer": true> in the configuration file to use it.). 
I added zero_allow_untested_optimizer to the config and didn't have the error again. 
Which optimizer (Lamb vs FusedLamb) should I use, and why do I get those errors while Lamb and FusedLamb are listed as optimizers?

**Comment by jomayeri** [comment]
The optimizer you should use depends on your hardware and performance requirements. The FusedLamb optimizer is a faster and more memory-efficient version of the Lamb optimizer, which implements the fusion of some operations to reduce the communication overhead and memory footprint. However, the FusedLamb optimizer requires a custom CUDA kernel to run, which means you need to have a compatible GPU and CUDA version to use it. The Lamb optimizer is a more general and compatible version, which can run on any device that supports PyTorch, but it may be slower and consume more memory than the FusedLamb optimizer.

The errors you encountered are related to the compatibility and configuration of the optimizers. The first error (AssertionError: FusedLamb is not a supported DeepSpeed Optimizer) indicates that you did not install the FusedLamb op when you installed DeepSpeed. [To use the FusedLamb optimizer, you need to install DeepSpeed with the DS_BUILD_FUSED_LAMB environment variable set to 1](https://www.deepspeed.ai/tutorials/advanced-install/)[1](https://www.deepspeed.ai/tutorials/advanced-install/). [Alternatively, you can use the ds_report tool to check which ops are installed and compatible with your machine](https://www.deepspeed.ai/tutorials/advanced-install/)[1](https://www.deepspeed.ai/tutorials/advanced-install/).

The second error (AssertionError: You are using an untested ZeRO Optimizer) indicates that you are using an optimizer that is not officially tested and supported by the ZeRO-Offload feature of DeepSpeed. ZeRO-Offload is a technique that offloads some of the optimizer states and gradients to the CPU memory, which reduces the GPU memory consumption and enables training larger models. However, not all optimizers are compatible with this technique, and some may cause errors or performance degradation. Therefore, DeepSpeed only allows using tested and supported optimizers with ZeRO-Offload by default, such as Adam and AdamW. [To use other optimizers, such as Lamb, you need to add “zero_allow_untested_optimizer”: true in the configuration file, as you did](https://github.com/microsoft/DeepSpeed/issues/182)[2](https://github.com/microsoft/DeepSpeed/issues/182). However, this does not guarantee that the optimizer will work correctly and efficiently with ZeRO-Offload, so you need to be careful and monitor your training progress

**Comment by Soroushmehr1** [comment]
Thanks for the explanation and guidance. I added "RUN DS_BUILD_FUSED_LAMB=1 pip install deepspeed" when I was building the environment (AzureML) and after that had "RUN python -m deepspeed.env_report" which shows that fused_lamb is compatible, but it is not installed. Uninstalling and installing deepspeed didn't help and I still get the same error as before (AssertionError: FusedLamb is not a supported DeepSpeed Optimizer) when I use "FusedLamb" as an optimizer in ds_config.json, I should mention that there is no error in the log file after building the environment. I use single A100 VM as a compute cluster. How should I install deepspeed so that FusedLamb is also installed?

**Comment by jomayeri** [comment]
It is odd that opt is not building, but your first comment about using `'Lamb'` in the config is correct is correct.
As you can see from the code
![image](https://github.com/microsoft/DeepSpeed/assets/114769929/3e457eee-15f6-494f-bd72-b84985a267c0)
![image](https://github.com/microsoft/DeepSpeed/assets/114769929/769a9e4f-53c3-46e1-8943-992620f6f273)

The name `'Lamb'` in the config instantiates the `'FusedLamb'` optimizer. Sorry for the confusion.
