### ISSUE TITLE
How to load a 130G model

### ISSUE THREAD

**Issue by yangzhipeng1108** [microsoft/DeepSpeed#4208]

**Comment by mrwyattii** [comment]
Hi @yangzhipeng1108 could you please provide some more details so that we can assist you? What is your hardware setup? Which model are you trying to load? What have you tried already?

**Comment by yangzhipeng1108** [comment]
Thanks,   I have two A800 servers with 8 cards. I want to use lora fine-tune llama-2-70b. I would like to ask whether peft supports deepspeed stage3, how to load the model separately on the GPU，and make the following settings:

model = AutoModelForCausalLM.from_pretrained(
    model_args.model_name_or_path,
    config=config,
    torch_dtype=torch.float16,
    # device_map={"": int(training_args.global_rank or 0)}
)  # .half().cuda()
    lora_config = LoraConfig(
        r=model_args.lora_r,
        lora_alpha=model_args.lora_alpha,
        target_modules=model_args.target_modules,
        fan_in_fan_out=False,
        lora_dropout=0.05,
        inference_mode=False,
        bias="none",
        task_type="CAUSAL_LM",
    )
model = get_peft_model(model, lora_config)
parameters = filter(lambda p: p.requires_grad, model.parameters())
model, optimizer, _, lr_scheduler = deepspeed.initialize(
        model=model,
        args=training_args,
        config=ds_config,
        model_parameters=parameters)
![image](https://github.com/microsoft/DeepSpeed/assets/33448441/28c1bfeb-e6b4-4472-9f82-b85f5e1fa330)

**Comment by mrwyattii** [comment]
@yangzhipeng1108 if you want to load the 70B Llama model for training across 8GPUs, you have a few options:

1. Load the model on CPU before doing `deepspeed.initialize`. This will require you to change how you are currently loading the model and will require a large amount of system memory (8 copies of the model will be loaded):
```python
model = AutoModelForCausalLM.from_pretrained(model_name, config=config, torch_dtype=torch.float16, device_map="cpu")
```

2. If you are planning to use ZeRO stage 3, you can easily load very large models from HuggingFace by passing the DeepSpeed config to HuggingFace before loading the model:
```python
import torch
import deepspeed
from transformers.deepspeed import HfDeepSpeedConfig
from transformers import AutoModelForCausalLM

ds_config = {
    "fp16": {"enabled": True},
    "bf16": {"enabled": False},
    "zero_optimization": {
        "stage": 3,
        "offload_param": {
            "device": "cpu",
        },
    },
    "train_micro_batch_size_per_gpu": 1,
}
# Share the DeepSpeed config with HuggingFace so we can properly load the
# large model with zero stage 3
hfdsc = HfDeepSpeedConfig(ds_config)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16)
```

**Comment by yangzhipeng1108** [comment]
Thanks
