### ISSUE TITLE
[REQUEST] Cannot fully understand the analysis of communication volume reduction of DeepSpeed Ulysses

### ISSUE THREAD

**Issue by aoyulong** [microsoft/DeepSpeed#4217]
Form [the blog](https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-ulysses), we get:

>  In contrast, the existing approaches like Megatron-LM incur communication volume that **increases linearly with N regardless of P**, resulting in the communication complexity of O(N). For instance, Megatron-LM performs two all-gather with the message volume of Nh and two reduce-scatter with the volume of Nh for each transformer layer. However, the cost of each all-gather and reduce-scatter of size M remains M when P >> 1, instead of M/P. Therefore, Megatron-LM sequence parallelism incurs a communication volume per link of 4Nh which is P times larger than that for DeepSpeed sequence parallelism. 

According to my knowledge, each process from the tensor parallel group when using the sequence parallelism of Megatron-LM has 1/P of the original activation Nh and this  is why we need an all-gather before computing the Q/K/V.  If I understand right, Megatron-LM **should not** incur communication volume that **increases linearly with N regardless of P**.

Besides, I think the two implementations may complement each other since they affect different parts of the transformer. For example, we may first do the Megatron-LM sequence parallel  and then do the DeeepSpeed sequence parallel as the following figure shows (the original picture from [paper](https://arxiv.org/pdf/2205.05198)).
![image](https://github.com/microsoft/DeepSpeed/assets/3069790/545cf997-6eb3-439f-92aa-716b459461da)

**Comment by MetaBlues** [comment]
I'm confused about this analysis of communication volume right now. Why does the all2all of size M have the cost of O(M/P) instead of O(M)?

**Comment by MetaBlues** [comment]
I'm also confused about this analysis of communication volume. Megatron-LM Seq-para partitions activation among all the processes so that each all-gather or reduce-scatter should incur an O(M/P) communication volume per link and O(M) in the whole system. Did I get it wrong?

**Comment by aoyulong** [comment]
@tohtana Thanks for the detailed explanation. However, the communication time of all_to_all that I find is `t = M *(P-1) / (B*P)` given M=3Nh and the bandwidth B according to [the formula](https://github.com/microsoft/DeepSpeedExamples/blob/master/benchmarks/communication/utils.py#L113).  Is this formula wrong?

**Comment by tohtana** [comment]
Hi @aoyulong,

That depends on the network environment. The formula assumes that all GPUs share a bus and the bandwidth `B`. 

As I cited above, however, each GPU pair has a dedicated link in some environments.
> On modern clusters with intra-node NVSwitch interconnect and inter-node fat tree IB topology,

In such a network, each GPU needs to send only `t = M / P`. Given the bandwidth of a link between two GPUs as `B`,   t = M / (B*P)`.

**Comment by Sakura-gh** [comment]
@tohtana hi, i wonder how ulysess deal with the variable grads, like layernorm grads. for megatron sequence parallel, it will do allreduce for layernorm weight grads, but i couldn't find the part in ulysess code.
