### ISSUE TITLE
Exit with code -7 When trarining LLama-2-7b-hf

### ISSUE THREAD

**Issue by zzkcaesar** [microsoft/DeepSpeed#4218]
**Describe the bug**
I intended to use deepspeed to training the Llama-2-7b-hf. I encounterd this problem without more information:
![image](https://github.com/microsoft/DeepSpeed/assets/37184407/7c768304-b0b5-4255-9e63-24fe8c8362fc)
And I have checked the GPU mem and the CPU mem，they all looked good. 

**To Reproduce**
Here is the training script and config I use:
[testScript.zip](https://github.com/microsoft/DeepSpeed/files/12437240/testScript.zip)

**Expected behavior**
Please help me identify the problem or give me some advice, This problem strictly block my work!

**ds_report output**
ds_report
[2023-08-25 16:24:04,916] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ray/anaconda3/lib/python3.9/site-packages/torch']
torch version .................... 2.0.0+cu118
deepspeed install path ........... ['/home/ray/anaconda3/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.10.1, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
shared memory (/dev/shm) size .... 64.00 MB
  [WARNING] /dev/shm size might be too small, if running in docker increase to at least --shm-size='1gb'
  [WARNING] see more details about NCCL requirements: https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#sharing-data
**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - GPU count and types: 8*H800
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version : Python 3.9.15
 - Any other relevant info about your setup

**Launcher context**
deepspeed --num_gpus=8 ds_training1.py --local_model_path /home/ray/zk/llama-2-7b-hf --data_path /home/ray/zk/dataset/databricks-dolly-15k/databricks-dolly-15k.jsonl --deepspeed ds_config3.json

**Docker context**
[anyscale/ray:latest-py39-cu118](https://docs.anyscale.com/reference/base-images/overview)

**Additional context**
Here is the dataset I use:
https://huggingface.co/datasets/databricks/databricks-dolly-15k

**Comment by tjruwase** [comment]
This is likely caused by insufficient shared memory in your docker. Please see the following snippet of your `ds_report`:

<img width="521" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/4271600/c8a06e40-b020-426e-81dd-75d555d80fad">

**Comment by zzkcaesar** [comment]
> This is likely caused by insufficient shared memory in your docker. Please see the following snippet of your `ds_report`:
> 
> <img alt="image" width="521" src="https://user-images.githubusercontent.com/4271600/263286476-c8a06e40-b020-426e-81dd-75d555d80fad.png">

Thanks for your reply!  Tomorrow I’ll try to increase the shm to see the impact.

**Comment by zzkcaesar** [comment]
> > This is likely caused by insufficient shared memory in your docker. Please see the following snippet of your `ds_report`:
> > <img alt="image" width="521" src="https://user-images.githubusercontent.com/4271600/263286476-c8a06e40-b020-426e-81dd-75d555d80fad.png">
> 
> Thanks for your reply! Tomorrow I’ll try to increase the shm to see the impact.

Update! After expanding shm of the container, the deepspeed run correctly! And the problem finally been sovled.
