### ISSUE TITLE
[QUESTION]exits with return code = -9, but there seems to be enough memory

### ISSUE THREAD

**Issue by RickMeow** [microsoft/DeepSpeed#4239]
**Describe the bug**
"exits with return code = -9."
I'm fine-tuning the llama-2-70B using 3 sets of machines containing 8 A100s (40G), and this error reported at first seemed like it should be an out-of-memory issue, but a large enough amount of memory has been used in the calculations. So it's not clear exactly why the error is being reported.

**To Reproduce**
1. For three machines (8*A100-40G):
conda create -n llamax python=3.10
conda activate llamax
git clone https://github.com/AetherCortex/Llama-X.git
cd Llama-X/src
conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.3 -c pytorch
pip install transformers==4.31.0
cd ... /...
pip install -r requirements.txt
2. set hostfile.txt:
192.168.0.6 slots=8
192.168.0.32 slots=8
192.168.0.23 slots=8
3. using deepspeed:
deepspeed --num_gpus 8 \
    --num_nodes 3 \
    --master_addr 192.168.0.6 \
    --master_port 34545 \
    --hostfile /mnt/download/configs/hostfile.txt \
    train.py \
    --model_name_or_path /mnt/model/Llama-2-70b-hf  \
    --data_path  /mnt/merged_data_3.json \
    --output_dir  /mnt/output/70B/\
    --num_train_epochs 1 \
    --model_max_length 256 \
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 100 \
    --save_total_limit 2 \
    --learning_rate 2e-5 \
    --warmup_steps 2 \
    --logging_steps 2 \
    --lr_scheduler_type "cosine" \
    --gradient_checkpointing True \
    --deepspeed /mnt/download/configs/deepspeed_config_transformers4.31.json \
    --fp16 True

**Expected behavior**
When typing the command: "nvidia-smi" I can see that the A100 utilization is basically 100%, but the memory usage is only half of that, which is one of the things I'm skeptical about, I think it should be running out of memory.

**ds_report output**
[2023-08-31 14:38:03,772] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/mnt/anaconda/envs/llamax/lib/python3.10/site-packages/torch']
torch version .................... 1.12.0
deepspeed install path ........... ['/mnt/anaconda/envs/llamax/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.0, unknown, unknown
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.3

**Screenshots**
<img width="633" alt="Question_1" src="https://github.com/microsoft/DeepSpeed/assets/122031049/01bcf031-2948-460a-a4fe-be3eef16056a">
<img width="637" alt="Question_2" src="https://github.com/microsoft/DeepSpeed/assets/122031049/8e80149b-6992-4d0a-99d0-f13e9bc00875">

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Configured as 3 groups with 8 A100 graphics cards (total of 24 A100-40G graphics cards)
 - Python = 3.10

**Additional context**
deepspeed_config_transformers4.31.json:
{
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 0,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 0,
        "stage3_max_reuse_distance": 0,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "fp16": {
        "enabled": true,
        "auto_cast": false,
        "loss_scale": 0,
        "initial_scale_power": 32,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
          "lr": 2e-5,
          "betas": [
            0.9,
            0.999
          ],
          "eps": 1e-8,
          "weight_decay": 0
        }
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto",
            "total_num_steps": "auto"
        }
    },
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false

}

**Comment by jomayeri** [comment]
-9 is system out of memory. You are running stage 3 and offloading both optimizer states and parameters which is overflowing the DRAM on the servers (the offloading is also the reason the GPU memory is not at full capacity). If you want to prove this to yourself launch a run and watch htop on one of the nodes, as soon as the memory is consumed it will start killing processes.

You can:
1. Try to put parameters back onto the GPU and see if they fit (you may have to reduce batch size for this).
2. Offload to NVME instead of CPU.

**Comment by RickMeow** [comment]
> -9 is a system error. You are running stage 3 and offloading both optimizer states and parameters which is overflowing the DRAM on the servers (the offloading is also the reason the GPU memory is not at full capacity). If you want to prove this to yourself launch a run and watch htop on one of the nodes, as soon as the memory is consumed it will start killing processes.
> 
> You can:
> 
> 1. Try to put parameters back onto the GPU and see if they fit (you may have to reduce batch size for this).
> 2. Offload to NVME instead of CPU.

I monitored htop and did find memory exhaustion and have modified the training strategy.

**Thank you very much!**

**Comment by AmrinKareem** [comment]
Hi, @RickMeow can you please share more details of how you changed the strategy? I have the same issue with exit code -9. I am not using offload though.
