### ISSUE TITLE
[BUG] nn.Parameter can't load model weight when the model trained by zero-offload

### ISSUE THREAD

**Issue by iamsile** [microsoft/DeepSpeed#4246]
**Describe the bug**
Hi, @mrwyattii . If I use zero-offload to train a model. Can I use this code to inference ? I have encountered a very strange problem that when I used my custom code to inference that some weight of layers always random initialization.

this is my custom class:
<img width="817" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/2016205/0a966ca0-f5f1-487c-aacc-bee5cdfd0237">

When I use it to train a model that can train and save the model in zero-offload. But when I use model to inference, I find self.bias_k and self.bias_v can't load the model weight.

When load model finish, the weight of self.bias_v like this ( it seems both of them load fail):
![image](https://github.com/microsoft/DeepSpeed/assets/2016205/ac1801fc-4edf-4d80-be16-287c2ab8f53f)

The weight of self.bias_v's in the model file(pytorch.bin):
![image](https://github.com/microsoft/DeepSpeed/assets/2016205/8bf9b423-bddc-4c07-a552-e62b387d52d6)

This is my load code:
<img width="1086" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/2016205/225d25e4-c745-4fc9-b7ec-acb3cba3a6e1">

In zero-offload mode, I use load_state_dict_into_model to load model.
```
def load_state_dict_into_model(model_to_load=None, state_dict=None, start_prefix="", zero_stage=0):

    # copy state_dict so _load_from_state_dict can modify it
    metadata = getattr(state_dict, "_metadata", None)
    state_dict = state_dict.copy()
    if metadata is not None:
        state_dict._metadata = metadata

    error_msgs = []

    # PyTorch's `_load_from_state_dict` does not copy parameters in a module's descendants
    # so we need to apply the function recursively.
    def load(module: nn.Module, state_dict, prefix=""):
        local_metadata = {} if metadata is None else metadata.get(
            prefix[:-1], {})
        args = (state_dict, prefix, local_metadata, True, [], [], error_msgs)
        # Parameters of module and children will start with prefix. We can exit early if there are none in this
        # state_dict
        if len([key for key in state_dict if key.startswith(prefix)]) > 0:
            if zero_stage == 3:
                # In sharded models, each shard has only part of the full state_dict, so only gather
                # parameters that are in the current state_dict.
                named_parameters = dict(
                    module.named_parameters(prefix=prefix[:-1], recurse=False))
                params_to_gather = [
                    named_parameters[k] for k in state_dict.keys()
                    if k in named_parameters
                ]
                if len(params_to_gather) > 0:
                    # because zero3 puts placeholders in model params, this context
                    # manager gathers (unpartitions) the params of the current layer, then loads from
                    # the state dict and then re-partitions them again
                    with deepspeed.zero.GatheredParameters(params_to_gather,
                                                           modifier_rank=0):
                        if torch.distributed.get_rank() == 0:
                            module._load_from_state_dict(*args)
            else:
                module._load_from_state_dict(*args)

        for name, child in module._modules.items():
            if child is not None:
                load(child, state_dict, prefix + name + ".")

    load(model_to_load, state_dict, prefix=start_prefix)
    # Delete `state_dict` so it could be collected by GC earlier. Note that `state_dict` is a copy of the argument, so
    # it's safe to delete it.
    del state_dict

    return error_msgs```

**Comment by iamsile** [comment]
I have fix it, close this issue.

**Comment by ZaVang** [comment]
> I have fix it, close this issue.

Hi, can you tell me how to solve this problem? I think I have encountered a similar problem. It seems that the model weight are not loaded correctly.

**Comment by iamsile** [comment]
> > I have fix it, close this issue.
> 
> Hi, can you tell me how to solve this problem? I think I have encountered a similar problem. It seems that the model weight are not loaded correctly.

Check whether the layer names of the model are the same as ckpt.
