### ISSUE TITLE
[BUG] Unable to specify arbitrary GPUs using CUDA_VISIBLE_DEVICES 

### ISSUE THREAD

**Issue by vinod-sarvam** [microsoft/DeepSpeed#4248]
I am trying to run LoRA finetuning with DeepSpeed-Chat. The nature of the finetuning process is that it can be done within 2 to 4 GPUs. So the plan is to partition the compute available and utilise it across experiments. However, I am not able to specify any arbitrary GPU using CUDA_VISIBLE_DEVICES. How to circumvent this error as this is extremely vital to get started. Please share remedies. The error is catalogued below: 

I ran: CUDA_VISIBLE_DEVICES=2 ./run_llama2_7b_lora.sh 

[2023-09-01 02:53:59,301] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-01 02:54:00,246] [WARNING] [runner.py:201:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=2: setting --include=localhost:2
Traceback (most recent call last):
  File "/.local/bin/deepspeed", line 6, in <module>
    main()
  File "/.local/lib/python3.8/site-packages/deepspeed/launcher/runner.py", line 428, in main
    active_resources = parse_inclusion_exclusion(resource_pool, args.include, args.exclude)
  File "/.local/lib/python3.8/site-packages/deepspeed/launcher/runner.py", line 349, in parse_inclusion_exclusion
    return parse_resource_filter(active_resources, include_str=inclusion, exclude_str=exclusion)
  File "/.local/lib/python3.8/site-packages/deepspeed/launcher/runner.py", line 301, in parse_resource_filter
    raise ValueError(f"No slot '{slot}' specified on host '{hostname}'")
ValueError: No slot '2' specified on host 'localhost'

**Comment by vinod-sarvam** [comment]
To add on to this comment, a prefix selection of GPUs (0,1 or 0,1,2 or just 0) seems to work, but an arbitrary selection of GPUs say 2,3 does not work.

**Comment by loadams** [comment]
Hi @vinod-sarvam - this is detailed more on the Getting Started page for Resource Configuration on a single node [here](https://www.deepspeed.ai/getting-started/#resource-configuration-single-node).  In short, we recommend using a hostfile for this, not `CUDA_VISIBLE_DEVICES`

**Comment by loadams** [comment]
Hi @vinod-sarvam - closing this issue for now assuming you've been able to resolve this.  If not, please reply and we can re-open if you are having any issues, thanks!

**Comment by Pabloo0610** [comment]
1

**Comment by Pabloo0610** [comment]
First you need to reset the CUDA_VISIBLE_DEVICES to 0,1,2,3, I think this is the issue.

**Comment by arnold-jr** [comment]
> First you need to reset the CUDA_VISIBLE_DEVICES to 0,1,2,3, I think this is the issue.

This doesn't actually address the issue, since @vinod-sarvam mentions that prefix selection works, but not arbitrary selection.

**Comment by arnold-jr** [comment]
https://github.com/microsoft/DeepSpeed/blob/4f9506729fda0e9b178761f58f5316018d77990b/deepspeed/launcher/runner.py#L358
This line erases the device numbering for the active_resources but not for the include string. When slots are [subsequently parsed from the include string](https://github.com/microsoft/DeepSpeed/blob/4f9506729fda0e9b178761f58f5316018d77990b/deepspeed/launcher/runner.py#L305), they are converted to int. In my estimation, one should check that the number of slots specified in the include string does not exceed the number found in the actitve_resources.

**Comment by loadams** [comment]
Hi @arnold-jr, we can, though if you have a more full explanation or summary of your issue, would you make a new issue and link this one?  That way it will be fresher in the list of issues to track.

**Comment by shizhengLi** [comment]
replacing `CUDA_VISIBLE_DEVICES=0,2 deepspeed red_train.py` with `deepspeed --include localhost:0,2 red_train.py`  works for me.
