### ISSUE TITLE
[BUG] mode.language_model can't load model weight when the model trained by zero-offload and lora.

### ISSUE THREAD

**Issue by iamsile** [microsoft/DeepSpeed#4249]
**Describe the bug**
Hi, @mrwyattii , If I use zero-offload + lora to train a model. I have encountered a very strange problem that when I used my custom code to inference that the weight of language_model always [] weight. I don't know why lora_A layer of language_model has weight but language_model layer not.

**Screenshots**
<img width="1095" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/2016205/886868df-b9f9-4a70-a956-319c6d4a55a1">

`
language_model.model.layers.39.self_attn.v_proj.weight Parameter containing:
tensor([], device='cuda:0', dtype=torch.bfloat16)

language_model.model.layers.39.self_attn.v_proj.lora_A.default.weight Parameter containing:
tensor([[ 0.0049, -0.0113,  0.0009,  ...,  0.0041,  0.0065,  0.0108],
        [ 0.0045, -0.0134,  0.0084,  ...,  0.0068,  0.0002, -0.0098],
        [-0.0020,  0.0120, -0.0073,  ...,  0.0053,  0.0120, -0.0062],
        ...,
        [-0.0134,  0.0102, -0.0089,  ..., -0.0038,  0.0082, -0.0028],
        [-0.0009, -0.0032,  0.0072,  ..., -0.0047,  0.0101,  0.0027],
        [ 0.0008, -0.0026, -0.0051,  ...,  0.0095,  0.0126, -0.0102]],
       device='cuda:0', requires_grad=True)

language_model.model.layers.39.self_attn.v_proj.lora_B.default.weight Parameter containing:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', requires_grad=True)`

**Comment by wangwenhaoxiaotie** [comment]
I met the same question, have you already addressed it?

**Comment by iamsile** [comment]
fixed and close

**Comment by rodolfovalentim** [comment]
How did you solved?
