### ISSUE TITLE
Is there a way to change python path for deepspeed?

### ISSUE THREAD

**Issue by jiacheng-ye** [microsoft/DeepSpeed#4254]
Hi, I installed an conda environment (say py310) in a place (say place1) and now I want to access this environment from another place (say place2) which parse the python path differently. I can run python in place2 well but when I run deepspeed, it use the python in place1:
```
(py310) place2:~$ which python
/data/envs/py310/bin/python
(py310) place2:~$ which deepspeed
/data/envs/py310/bin/deepspeed
(py310) place2:~$ deepspeed
bash: /data/envs/py310/bin/deepspeed: /home/envs/py310/bin/python: bad interpreter: No such file or directory
```
Here `/home/envs/py310/bin/python` is the python in place1. I hope this to be `/data/envs/py310/bin/python` which is also in place2 so I can run deepspeed successfully. How should I do in this situation?

Thanks a lot for your help in advance.

**Comment by loadams** [comment]
Transient failure.

**Comment by jiacheng-ye** [comment]
Hi Logan, I installed deepseed in place 1 with `pip install deepspeed`, and both place1 and place2 can run python successfully. Place1 is a remote disk and I mount it on place2 so place2 can access the environment in place1.

**Comment by loadams** [comment]
I see, can you run both `pip list`, `pip show deepspeed`, and `echo $PYTHONPATH`?

**Comment by loadams** [comment]
Hi @jiacheng-ye - following up on this

**Comment by loadams** [comment]
Closing this for now, if you're still hitting this problem please let me know and we can re-open this issue.

**Comment by downeykking** [comment]
I met the same question.
The reason is deepspeed will defaultly write the install python path in https://github.com/microsoft/DeepSpeed/blob/master/bin/ds
For example, my conda env is `/data/miniconda3/envs/py39`, and deepspeed will write the path to the above file.
```python
#!/data/miniconda3/envs/py39/bin/python

from deepspeed.launcher.runner import main

if __name__ == '__main__':
    main()
```
So if you want to run deepspeed in another env, you would better delete the path like 


```python
from deepspeed.launcher.runner import main

if __name__ == '__main__':
    main()
```
