### ISSUE TITLE
[REQUEST]Need I load data to memory at all stages when I use pipiline engine ?

### ISSUE THREAD

**Issue by janelu9** [microsoft/DeepSpeed#4255]
why not only read data at the node of the pipeline's first stage?

**Comment by ShadenSmith** [comment]
Hi there, do you mean the incoming batch data? The first and last pipeline stages require data loaders. The last stage uses it to supply labels for the loss calculation.

Totally agreed with you that it would be nicer if only the first pipeline stage needs the input data! I wanted to implement this initially and just have the first pipeline stage communicate the batch for the loss calculation.

There's no fundamental reason we can't only load on the first stage. The tricky bit is just that the shapes/formats of the incoming data are only known on the first stage and requires some additional coordination and/or restrictions on the batch format. We actually already have some utilities that could enable those communications in `runtime/pipe/p2p.py`, but they should be rewritten as they're slow and also use `pickle` which is insecure.

**Comment by janelu9** [comment]
> Hi there, do you mean the incoming batch data? The first and last pipeline stages require data loaders. The last stage uses it to supply labels for the loss calculation.
> 
> Totally agreed with you that it would be nicer if only the first pipeline stage needs the input data! I wanted to implement this initially and just have the first pipeline stage communicate the batch for the loss calculation.
> 
> There's no fundamental reason we can't only load on the first stage. The tricky bit is just that the shapes/formats of the incoming data are only known on the first stage and requires some additional coordination and/or restrictions on the batch format. We actually already have some utilities that could enable those communications in `runtime/pipe/p2p.py`, but they should be rewritten as they're slow and also use `pickle` which is insecure.

Additional,can we distribute the pipeline engine's first and last stage at different nodes，my model requires memory fewer but data needs much more

**Comment by ShadenSmith** [comment]
If you're training with multiple nodes, the first and last pipeline stages will be placed on different nodes.

We don't have any mechanisms for sharing memory allocations across pipeline stages. There's a `TiedLayer` utility for keeping model parameters in sync across stages (e.g., an embedding layer at the start/end), but both stages will ultimately have to allocate that memory. There are other pipeline parallelism approaches that instead map the reused layer to the same stage.

**Comment by janelu9** [comment]
> If you're training with multiple nodes, the first and last pipeline stages will be placed on different nodes.
> 
> We don't have any mechanisms for sharing memory allocations across pipeline stages. There's a `TiedLayer` utility for keeping model parameters in sync across stages (e.g., an embedding layer at the start/end), but both stages will ultimately have to allocate that memory. There are other pipeline parallelism approaches that instead map the reused layer to the same stage.

Up to now, the first and last pipeline stages are placed on same nodes.
I have 8 nodes with 64 gpus, my topo strategy is :
```
topo = PipeModelDataParallelTopology(
        num_pp = 8,
        num_mp = 1,
        num_dp = 8)
```

**Comment by ShadenSmith** [comment]
Hm, with that topology each pipeline stage should get its own node so that the data-parallel communications can stay intra-node. Can you share the log with the mappings? Perhaps there is something strange happening.

**Comment by janelu9** [comment]
It distributes stages according to the topology  

> Hm, with that topology each pipeline stage should get its own node so that the data-parallel communications can stay intra-node. Can you share the log with the mappings? Perhaps there is something strange happening.

Firstly, global_ rank=local_ rank+8 * node_ id.
Then, it distributes the stage based on the topology , prioritizing the data dimension. so global_ rank=data_ id+8 * pipe_ id, which means that the first stage (pipe_id=0) are all on a node whose global_ rank is from 0 to 7.

I load my data to the memory with local_rank 0, but it still costs 8x memory of the data during trainning:
```
def read_data(local_rank,path):
    torch.distributed.barrier()
    if local_rank !=0:
        torch.distributed.barrier()
    data = pyarrow.parquet.read_table(path)
    if local_rank ==0:
         torch.distributed.barrier()
    return data
```

**Comment by janelu9** [comment]
> Firstly, global_ rank=local_ rank+8 * node_ id. PipelineEngine distributes stages according to the topology , while the `PipeModelDataParallelTopology`'s axis is `[pipe,model,data]`. It prioritizes the data dimension. so global_ rank=data_ id+8 * pipe_ id, which means that the first stage (pipe_id=0) are all on the first node whose global_ rank is from 0 to 7.
> 
> Now I load my data to the memory by parquet, it costs 8x memory of the data on all nodes during trainning:
> 
> ```
> data = pyarrow.parquet.read_table(path)
> ```
> 
> Maybe I should pass `aixs=[data,model,pipe]` to `ProcessTopology`, and use some fake dataset in the ranks who is neither the first stage nor the last stage to reduce the usage of memory to 2x .

Firstly, global_ rank=local_ rank+8 * node_ id.
PipelineEngine distributes stages according to the topology , while the PipeModelDataParallelTopology's axis is [pipe,model,data]. It prioritizes the data dimension. so global_ rank=data_ id+8 * pipe_ id, which means that the first stage (pipe_id=0) are all on the first node whose global_ rank is from 0 to 7.

Now I load my data to the memory by parquet, it costs 8x memory of the data on all nodes during trainning:

data = pyarrow.parquet.read_table(path)
Maybe I should pass aixs=[data,model,pipe] to ProcessTopology, and use some fake dataset in the ranks who is neither the first stage nor the last stage to reduce the usage of memory to 2x .

**Comment by janelu9** [comment]
> Hm, with that topology each pipeline stage should get its own node so that the data-parallel communications can stay intra-node. Can you share the log with the mappings? Perhaps there is something strange happening.

Firstly, global_ rank=local_ rank+8 * node_ id.
PipelineEngine distributes stages according to the topology , while the `PipeModelDataParallelTopology`'s axis is `[pipe,model,data]`. It prioritizes the data dimension. so global_ rank=data_ id+8 * pipe_ id, which means that the first stage (pipe_id=0) are all on the first node whose global_ rank is from 0 to 7.

Now I load my data to the memory by parquet, it costs 8x memory of the data on all nodes during trainning:
```
data = pyarrow.parquet.read_table(path)
```
Maybe I should pass `aixs=[data,model,pipe]` to `ProcessTopology`, and use some fake dataset in the ranks who is neither the first stage nor the last stage to reduce the usage of memory to 2x .

**Comment by janelu9** [comment]
> Hm, with that topology each pipeline stage should get its own node so that the data-parallel communications can stay intra-node. Can you share the log with the mappings? Perhaps there is something strange happening.

Can I pass label from first stage to last stage which may reduce the usage of memory to 1x .

**Comment by janelu9** [comment]
> Hm, with that topology each pipeline stage should get its own node so that the data-parallel communications can stay intra-node. Can you share the log with the mappings? Perhaps there is something strange happening.

Can I pass label from first stage to last stage which may reduce the usage of memory to 1x ?

**Comment by ShadenSmith** [comment]
@janelu9 , not out of the box but that should be possible with some modifications to the pipeline schedule! I think it would make a great improvement.
