### ISSUE TITLE
Can't train despite having 320 Gb VRAM

### ISSUE THREAD

**Issue by tekntrash** [microsoft/DeepSpeed#4256]
I am trying to finetune a Falcon model using deepspeed and happytransformer

We have a server with 4 NVIDIA A100-SXM4 with 80GB each, totalling 320 Gb VRAM

The command is GENTrainArgs(fp16=True,deepspeed="ZERO-2",max_length = 256)

Still, despite our efforts, we always hit the error OutOfMemoryError: : CUDA out of memory. Tried to allocate 19.23 GiB (GPU 1; 79.15 GiB total capacity; 76.93 GiB already allocated; 1.03 GiB free; 76.93 GiB reserved in total by PyTorch)

I mean really? Even 4 top of the line GPU's can train a model? :/

**Comment by DonMiller9294** [comment]
Hello, Training large models like Falcon on multiple high-end GPUs can still encounter memory issues. Here are some tips to help with this problem:

- Reduce batch size: Smaller batches consume less memory.
- Use gradient accumulation to effectively use larger batch sizes without increasing memory.
- Consider a smaller model version if available.
- Implement data parallelism to distribute the model across GPUs.
- Ensure you're using mixed-precision training (fp16=True).
- Reduce the maximum sequence length.
- Review your Deepspeed configuration for optimization.
- If possible, upgrade to GPUs with larger VRAM.
- Save checkpoints to resume training in case of crashes.
- Use GPU profiling tools to identify memory bottlenecks.

Large models can be memory-intensive, so you may need to combine these techniques to train effectively.

**Comment by tekntrash** [comment]
Thank you for the thoughtful feedback: we are now trying  deepspeed train.py --per_device_train_batch_size 100 --max_train_samples 500 --num_train_epochs 1000 which is basically what you are saying

However, now encountering "AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'"

**Comment by DonMiller9294** [comment]
Thanks for your feedback! You're currently using the 'deepspeed train.py' command with these settings: '--per_device_train_batch_size 100', '--max_train_samples 500', and '--num_train_epochs 1000,' which matches our earlier suggestion. However, you're encountering an error, 'AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam.''

To fix this:

1. Check DeepSpeed version compatibility.
2. Verify your configuration and watch for typos.
3. Review DeepSpeed initialization in your code.
4. Update your code if needed.
5. Consult DeepSpeed documentation.
6. Seek help from the DeepSpeed community.

These steps should help resolve the error. Please share more details if you need further assistance.

**Comment by tekntrash** [comment]
Thanks, but my code does not have that command at all. Either way, created another thread for it

**Comment by DonMiller9294** [comment]
Sorry about that. let me know if there is any way I can help.

**Comment by loadams** [comment]
Hi @tekntrash - you can also try with Zero stage 3 for additional memory optimizations.

**Comment by loadams** [comment]
Hi @tekntrash - could you also share the stacktrace that you are seeing before/when you hit the OOM error?

**Comment by loadams** [comment]
Hi @tekntrash - closing this thread for now, if you have other questions please re-open or link this thread and we can take a look, thanks!
