### ISSUE TITLE
[BUG]BF16_Optimizer.load_state_dict() got an unexpected keyword argument 'load_serial'

### ISSUE THREAD

**Issue by janelu9** [microsoft/DeepSpeed#4272]
deepseed >=0.10.1
I train my model with bfloat16
when I load checkpoint , errors occured!
```
-> 2869 self.optimizer.load_state_dict(state_dict_list=zero_sd_list,
   2870                                load_optimizer_states=load_optimizer_states,
   2871                                load_from_fp32_weights=self.zero_load_from_fp32_weights(),
   2872                                checkpoint_folder=checkpoint_folder,
   2873                                load_serial=load_serial)
   2875 if self.load_universal_checkpoint():
   2876     logger.info(f'loaded universal zero checkpoints from {checkpoint_folder} for rank {self.global_rank}')

TypeError: BF16_Optimizer.load_state_dict() got an unexpected keyword argument 'load_serial'
```

**Comment by janelu9** [comment]
deepspeed==0.10.3 still has the bug

**Comment by ShijieZZZZ** [comment]
Hello @janelu9, @passaglia, do you have a small example to reproduce this issue?
It will be very helpful to know the configs used to train the bfloat model.

**Comment by janelu9** [comment]
> Hello @janelu9, @passaglia, do you have a small example to reproduce this issue? It will be helpful to know the configs used to train the bfloat model.

my ds_config:
`"bf16": {"enabled": True}"`

**Comment by ShijieZZZZ** [comment]
Hello @janelu9, could you please try this [PR](https://github.com/microsoft/DeepSpeed/pull/4434) to see if it fixes this issue.

**Comment by passaglia** [comment]
@ShijieZZZZ Yes, https://github.com/microsoft/DeepSpeed/pull/4434 fixed the issue for me! 🥳

**Comment by ShijieZZZZ** [comment]
Thanks for confirming. I will close the issue then.
