### ISSUE TITLE
[REQUEST] Clarify behavior when doing generation with DeepSpeed inference

### ISSUE THREAD

**Issue by Epliz** [microsoft/DeepSpeed#4276]
**Is your feature request related to a problem? Please describe.**
Reading https://www.deepspeed.ai/tutorials/inference-tutorial/ , it is not clear what is the behavior of DeepSpeed inference when generating text.
Are we supposed to pass the same prompt on the different ranks and they collaborate to give an answer?
Or are each rank doing their own thing and we can leverage it to pass different prompts to the different ranks for extra performance?

**Describe the solution you'd like**
I would appreciate a clarification in the documentation about what is happening, and whether I am supposed to pass the same prompt to each rank,
Bonus point explaining the behavior when for example using HuggingFace pipeline and using beam-search or generating several sentences out.

**Describe alternatives you've considered**
Trying myself, guessing what is the expected behavior.

**Additional context**

**Comment by mrwyattii** [comment]
> Are we supposed to pass the same prompt on the different ranks and they collaborate to give an answer?

Yes, the same prompt should be passed on all ranks when you are using tensor parallelism (i.e., the model is split across multiple GPUs).  If you are running a model that is small enough to fit entirely on one GPU, you may also try doing data parallelism rather than tensor parallelism. In the case of data parallelism, each GPU would have its own copy of the model and different prompts could be sent to each. Consider the code below that demonstrates this:

```python
import torch
import deepspeed
import os
import time
from transformers import pipeline

local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))

task_name = "text-generation"
model_name = "bigscience/bloom-560m"
input_strs = ["DeepSpeed is", "Microsoft is"]


def run_tensor_parallel():
    pipe = pipeline(task_name, model_name, torch_dtype=torch.float16, device=local_rank)

    # Initialize DeepSpeed
    pipe.model = deepspeed.init_inference(
        pipe.model,
        replace_with_kernel_inject=True,
        mp_size=world_size,
        dtype=torch.float16,
    )

    # Run inference
    print(f"Rank {local_rank} sending input '{input_strs}' to the pipeline.")
    torch.cuda.synchronize()
    start_time = time.time()
    output = pipe(input_strs)
    torch.cuda.synchronize()
    end_time = time.time()
    print(f"Rank {local_rank} output: {output}")
    if local_rank == 0:
        print(f"Tensor Parallel Time: {end_time-start_time}s")


def run_data_parallel():
    pipe = pipeline(task_name, model_name, torch_dtype=torch.float16, device=local_rank)

    # Initialize DeepSpeed
    pipe.model = deepspeed.init_inference(
        pipe.model,
        replace_with_kernel_inject=True,
        mp_size=1,
        dtype=torch.float16,
    )
    pipe.model.to(
        torch.device(f"cuda:{local_rank}")
    )  # Required to keep models on the correct device

    # Run inference
    print(
        f"Rank {local_rank} sending input '{input_strs[local_rank]}' to the pipeline."
    )
    torch.cuda.synchronize()
    start_time = time.time()
    output = pipe(input_strs[local_rank])
    torch.cuda.synchronize()
    end_time = time.time()
    print(f"Rank {local_rank} output: {output}")
    if local_rank == 0:
        print(f"Data Parallel Time: {end_time-start_time}s")


if __name__ == "__main__":
    run_tensor_parallel()
    run_data_parallel()
```

If I run this script with `deepspeed --num_gpus 2 inference_example.py` on 2xA6000 setup:
```bash
Rank 0 sending input '['DeepSpeed is', 'Microsoft is']' to the pipeline.
Rank 1 sending input '['DeepSpeed is', 'Microsoft is']' to the pipeline.
Rank 1 output: [[{'generated_text': 'DeepSpeed is a new feature in the game. The game is now able to use the new speed'}], [{'generated_text': 'Microsoft is a free software that allows you to create and edit video and audio files. It is a'}]]
Rank 0 output: [[{'generated_text': 'DeepSpeed is a new feature in the game. The game is now able to use the new speed'}], [{'generated_text': 'Microsoft is a free software that allows you to create and edit video and audio files. It is a'}]]
Tensor Parallel Time: 0.7914915084838867s

Rank 0 sending input 'DeepSpeed is' to the pipeline.
Rank 1 sending input 'Microsoft is' to the pipeline.
Rank 0 output: [{'generated_text': 'DeepSpeed is a new feature in the game. The game is now able to use the new speed'}]
Rank 1 output: [{'generated_text': 'Microsoft is a free software that can be used to create and edit and edit images.'}]
Data Parallel Time: 0.16255569458007812s
```

Please note that this is not a proper benchmark and you should do your own experimentation to determine if tensor parallelism or data parallelism is better for your particular hardware/model/etc.

> Bonus point explaining the behavior when for example using HuggingFace pipeline and using beam-search or generating several sentences out.

We do not support beam-search with DeepSpeed-Inference. You can find a discussion and the latest updates on development of this feature here: #2506 

Also, you may find additional examples of DeepSeed-Inferece usage in another of our repositories: https://github.com/microsoft/DeepSpeedExamples/tree/master/inference/huggingface

**Comment by Epliz** [comment]
thank you @mrwyattii for the answer, very much appreciated!
it would be great if you could add that information at https://www.deepspeed.ai/tutorials/inference-tutorial/, for future users

**Comment by sarathkondeti** [comment]
> > Are we supposed to pass the same prompt on the different ranks and they collaborate to give an answer?
> 
> Yes, the same prompt should be passed on all ranks when you are using tensor parallelism (i.e., the model is split across multiple GPUs). If you are running a model that is small enough to fit entirely on one GPU, you may also try doing data parallelism rather than tensor parallelism. In the case of data parallelism, each GPU would have its own copy of the model and different prompts could be sent to each. Consider the code below that demonstrates this:
> 
> ```python
> import torch
> import deepspeed
> import os
> import time
> from transformers import pipeline
> 
> local_rank = int(os.getenv("LOCAL_RANK", "0"))
> world_size = int(os.getenv("WORLD_SIZE", "1"))
> 
> task_name = "text-generation"
> model_name = "bigscience/bloom-560m"
> input_strs = ["DeepSpeed is", "Microsoft is"]
> 
> 
> def run_tensor_parallel():
>     pipe = pipeline(task_name, model_name, torch_dtype=torch.float16, device=local_rank)
> 
>     # Initialize DeepSpeed
>     pipe.model = deepspeed.init_inference(
>         pipe.model,
>         replace_with_kernel_inject=True,
>         mp_size=world_size,
>         dtype=torch.float16,
>     )
> 
>     # Run inference
>     print(f"Rank {local_rank} sending input '{input_strs}' to the pipeline.")
>     torch.cuda.synchronize()
>     start_time = time.time()
>     output = pipe(input_strs)
>     torch.cuda.synchronize()
>     end_time = time.time()
>     print(f"Rank {local_rank} output: {output}")
>     if local_rank == 0:
>         print(f"Tensor Parallel Time: {end_time-start_time}s")
> 
> 
> def run_data_parallel():
>     pipe = pipeline(task_name, model_name, torch_dtype=torch.float16, device=local_rank)
> 
>     # Initialize DeepSpeed
>     pipe.model = deepspeed.init_inference(
>         pipe.model,
>         replace_with_kernel_inject=True,
>         mp_size=1,
>         dtype=torch.float16,
>     )
>     pipe.model.to(
>         torch.device(f"cuda:{local_rank}")
>     )  # Required to keep models on the correct device
> 
>     # Run inference
>     print(
>         f"Rank {local_rank} sending input '{input_strs[local_rank]}' to the pipeline."
>     )
>     torch.cuda.synchronize()
>     start_time = time.time()
>     output = pipe(input_strs[local_rank])
>     torch.cuda.synchronize()
>     end_time = time.time()
>     print(f"Rank {local_rank} output: {output}")
>     if local_rank == 0:
>         print(f"Data Parallel Time: {end_time-start_time}s")
> 
> 
> if __name__ == "__main__":
>     run_tensor_parallel()
>     run_data_parallel()
> ```
> 
> If I run this script with `deepspeed --num_gpus 2 inference_example.py` on 2xA6000 setup:
> 
> ```shell
> Rank 0 sending input '['DeepSpeed is', 'Microsoft is']' to the pipeline.
> Rank 1 sending input '['DeepSpeed is', 'Microsoft is']' to the pipeline.
> Rank 1 output: [[{'generated_text': 'DeepSpeed is a new feature in the game. The game is now able to use the new speed'}], [{'generated_text': 'Microsoft is a free software that allows you to create and edit video and audio files. It is a'}]]
> Rank 0 output: [[{'generated_text': 'DeepSpeed is a new feature in the game. The game is now able to use the new speed'}], [{'generated_text': 'Microsoft is a free software that allows you to create and edit video and audio files. It is a'}]]
> Tensor Parallel Time: 0.7914915084838867s
> 
> Rank 0 sending input 'DeepSpeed is' to the pipeline.
> Rank 1 sending input 'Microsoft is' to the pipeline.
> Rank 0 output: [{'generated_text': 'DeepSpeed is a new feature in the game. The game is now able to use the new speed'}]
> Rank 1 output: [{'generated_text': 'Microsoft is a free software that can be used to create and edit and edit images.'}]
> Data Parallel Time: 0.16255569458007812s
> ```
> 
> Please note that this is not a proper benchmark and you should do your own experimentation to determine if tensor parallelism or data parallelism is better for your particular hardware/model/etc.
> 
> > Bonus point explaining the behavior when for example using HuggingFace pipeline and using beam-search or generating several sentences out.
> 
> We do not support beam-search with DeepSpeed-Inference. You can find a discussion and the latest updates on development of this feature here: #2506
> 
> Also, you may find additional examples of DeepSeed-Inferece usage in another of our repositories: https://github.com/microsoft/DeepSpeedExamples/tree/master/inference/huggingface

Below gpu allocation doesn't seem to work as both instances of model are loaded into the same gpu and throwing a OOM.
This is happening from init_inference. So, model.to() is never reached.

Please help with a work around for this.
I don't understand how to deploy DP without using MII's load balancer.

```
    # Initialize DeepSpeed
    pipe.model = deepspeed.init_inference(
        pipe.model,
        replace_with_kernel_inject=True,
        mp_size=1,
        dtype=torch.float16,
    )
    pipe.model.to(
        torch.device(f"cuda:{local_rank}")
    )
```
