### ISSUE TITLE
[BUG] error when using DeepSpeed with fp16

### ISSUE THREAD

**Issue by weafo** [microsoft/DeepSpeed#4293]
I tried to implement with the DeepSpeed to train model. (Without using DeepSpeed everything is fine)

**Script:**
`deepspeed_plugin = DeepSpeedPlugin(zero_stage=2,  gradient_accumulation_steps=2)`
`accelerator = Accelerator(deepspeed_plugin=deepspeed_plugin, mixed_precision='fp16')`

**DeepSpeed config:**
<img width="552" alt="Desktop Screenshot 2023 09 08 - 13 47 15 99" src="https://github.com/microsoft/DeepSpeed/assets/144443931/adbe28a8-c8a6-4af9-b66a-4d4fd1434dcd">

**Error:**
<img width="658" alt="Desktop Screenshot 2023 09 08 - 13 52 31 72" src="https://github.com/microsoft/DeepSpeed/assets/144443931/2576839d-59b0-4b15-8dd9-7d82acee4d8e">

**ds_report output:**
<img width="992" alt="Desktop Screenshot 2023 09 10 - 19 54 56 17 — копия" src="https://github.com/microsoft/DeepSpeed/assets/144443931/a07c0d91-35ab-466f-9b68-a2fe66f23185">
<img width="315" alt="Desktop Screenshot 2023 09 10 - 19 57 33 71" src="https://github.com/microsoft/DeepSpeed/assets/144443931/41021c6e-1aee-459a-8329-1c8a81ce215e">
<img width="402" alt="Desktop Screenshot 2023 09 10 - 19 56 21 29" src="https://github.com/microsoft/DeepSpeed/assets/144443931/67faf3a6-9bcf-4681-9628-70ccd27f071e">

**System info:**
 - deepspeed 0.10.2
 - accelerate 0.22.0
 - gpu: 1 machine with x4 V100 each
 - python 3.11.4

**Launcher context:**
`accelerate-launch --num_processes=3 ds_plugin.py`

What should I do to resolve this problem?
Thanks for the help!

**Comment by jomayeri** [comment]
@weafo Can you post a large stack trace as well as reproduction code? Thanks.
