### ISSUE TITLE
[BUG] Can ZeRO++ be used for LLM pretraining?

### ISSUE THREAD

**Issue by Double-bear** [microsoft/DeepSpeed#4309]
**Describe the bug**
I tried to use zero++ to pretrain full parameters of Llama2-70b and Llama2-7b, but I got an assert error: 
AssertionError: Qantized weight requires the number of weights be a multiple of 8
I tried to modify the param buffer before running CUDAQuantizer.quantize，and got another error:
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
So are there any solutions can solve this problem?
Or is it that ZeRO++ cannot be used for pretraining？

**Comment by GuanhuaWang** [comment]
Hi @Double-bear,

Our quantization kernels need to consume multiple of 8 values concurrently to achieve good computation efficiency. So to use zero++ for llama2,  you may need to do add some value padding for layers that does not have multiple of 8 values.

**Comment by Double-bear** [comment]
> Hi @Double-bear,
> 
> Our quantization kernels need to consume multiple of 8 values concurrently to achieve good computation efficiency. So to use zero++ for llama2, you may need to do add some value padding for layers that does not have multiple of 8 values.

Hi @GuanhuaWang, I tried to do some padding process as follow:
```
                    if hasattr(param_ds_tensor, "ds_quant_scale"):
                        scales = param_ds_tensor.ds_quant_scale
                        quantized_param = param_ds_tensor.data
                    else:
                        # print('check_data: ', param.numel(), world_size, buffer_size, param_ds_tensor.numel())
                        padding_flag = False
                        original_size = param_ds_tensor.numel()
                        if param_ds_tensor.numel() % 8 != 0:
                            print('need_padding!')
                            padding_flag = True
                            padding_size = (8 - param_ds_tensor.numel() % 8) % 8
                            param_ds_tensor = torch.cat([param_ds_tensor, torch.zeros(padding_size).to(param_ds_tensor.device)])
                            param_buffer = torch.empty(
                                param_ds_tensor.numel() * world_size,
                                dtype=param_ds_tensor.dtype if not quantize else torch.int8,
                                device=get_accelerator().current_device_name(),
                                requires_grad=False,
                            )
                            # print('check_data:', padding_flag, original_size, param_ds_tensor.numel())
                        quantized_param, scales = self.quantizer_module.quantize(param_ds_tensor)
```
this part is in _convert_to_deepspeed_param function in partition_parameters.py. This modification could get rid of the Qantized weight AssertionError, but another error appeared: 
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
I think my modification is error, would you please give me some suggestions about how to add value padding? Thank you!

**Comment by GuanhuaWang** [comment]
Hi @Double-bear ,

it would be great if there is a small sample python script to reproduce your error. Btw, what data type are you using fp16 or bf16?

**Comment by Double-bear** [comment]
> Hi @Double-bear ,
> 
> it would be great if there is a small sample python script to reproduce your error. Btw, what data type are you using fp16 or bf16?

I used bf16.

**Comment by GuanhuaWang** [comment]
Hi @Double-bear ,

I think that is the issue. Currently ZeRO++ only support FP16 training.

**Comment by Double-bear** [comment]
> Hi @Double-bear ,
> 
> I think that is the issue. Currently ZeRO++ only support FP16 training.

hi @GuanhuaWang ，I tried to use fp16, but the problem also occured. So will there be a script for zero++ training suitable for llama2 in the future that doesn't require manual padding?

**Comment by GuanhuaWang** [comment]
> > Hi @Double-bear ,
> > I think that is the issue. Currently ZeRO++ only support FP16 training.
> 
> hi @GuanhuaWang ，I tried to use fp16, but the problem also occured. So will there be a script for zero++ training suitable for llama2 in the future that doesn't require manual padding?

Hi @Double-bear,

Yes, there will be. I will keep you posted for this llama2 script

**Comment by Double-bear** [comment]
> > > Hi @Double-bear ,
> > > I think that is the issue. Currently ZeRO++ only support FP16 training.
> > 
> > 
> > hi @GuanhuaWang ，I tried to use fp16, but the problem also occured. So will there be a script for zero++ training suitable for llama2 in the future that doesn't require manual padding?
> 
> Hi @Double-bear,
> 
> Yes, there will be. I will keep you posted for this llama2 script

Thank you！
