### ISSUE TITLE
How to train GAN on specified GPUs

### ISSUE THREAD

**Issue by SophieOstmeier** [microsoft/DeepSpeed#4315]
I am trying to train a GAN following the example here https://github.com/microsoft/DeepSpeedExamples/tree/master/training/gan on a shared workstation where I want to use GPUs 2 and 3 (out of 4 total).

How can I tell deepspeed.initialize to use GPUs 2 and 3? I am able to specify the GPU for each engine by setting the rank, but it is unclear how to set up the distributed engine so it is able to fully utilize both of the GPUs I want to use. 

Thanks in advance!

**Comment by loadams** [comment]
Hi @SophieOstmeier - I believe you're looking for something like [this](https://www.deepspeed.ai/getting-started/#resource-configuration-single-node)?  Basically you want a hostfile that will specify to DeepSpeed to use only 2 of the 3 GPUs on the system.

**Comment by loadams** [comment]
Hi @SophieOstmeier - was that able to resolve your issue?

**Comment by loadams** [comment]
@SophieOstmeier - closing this issue for now as I believe the solution above should resolve your issue.  If you still have any issues with this, please let us know and we can re-open this and work on the issue.  Thanks!

**Comment by SophieOstmeier** [comment]
Sorry for the late reply. Yes, thank you!
