### ISSUE TITLE
Error during build of csrc/sparse_attention/utils.cpp

### ISSUE THREAD

**Issue by e-sha** [microsoft/DeepSpeed#432]
I've got the following error during build of `csrc/sparse_attention/utils.cpp`
`csrc/sparse_attention/utils.cpp:87:71: error: converting to 'std::vector<std::tuple<int, at::Tensor> >::value_type {aka std::tuple<int, at::Tensor>}' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = int&; _U2 = at::Tensor; <template-parameter-2-3> = void; _T1 = int; _T2 = at::Tensor]'`
`     if (!to_cat.empty()) ret.push_back({max_width, torch::cat(to_cat)});`

Ubuntu16.04
Cuda10.1
PyTorch 1.6.0
DeepSpeed v0.3.0

**Comment by tjruwase** [comment]
@e-sha which compiler are you using?

**Comment by arashashari** [comment]
@e-sha: As @tjruwase asked for your compiler version, I think it could be an issue with your g++ compiler; as you are using Ubuntu-16.04. I just double checked a successful install on Ubuntu-18.04 with g++ 7.5.0. Please provide us with you compiler version and if possible, do a test with an updated version.

**Comment by e-sha** [comment]
```
x86_64-linux-gnu-gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```

**Comment by tjruwase** [comment]
@e-sha, we recently made some improvements to installation. Can you please check to see if this problem still exists? Thanks.

**Comment by jorie-peng** [comment]
> @e-sha, we recently made some improvements to installation. Can you please check to see if this problem still exists? Thanks.

@tjruwase  Hi, I have the same error with ubuntu 16.04.6 and g++ 5.4,do you know the reason? thanks!

```
(py3.6) powerop@jupyter-with-pytorch-1-tr002056-0:/tmp/Deepspeed$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
```
