### ISSUE TITLE
Sequence Parallel

### ISSUE THREAD

**Issue by yingtongxiong** [microsoft/DeepSpeed#4359]
**Describe the bug**
I have recently read the source code of Ulysses. There is a all-to-all communication between qkv and attention. However, when I read the code, I have some questions about the scatter_idx and gather_idx in [here](https://github.com/microsoft/DeepSpeed/blob/78c3b148a8a8b6e60ab77a5c75849961f52b143d/deepspeed/sequence/layer.py#L51). I don't know whether my understanding is correct. In [here](https://github.com/microsoft/DeepSpeed/blob/78c3b148a8a8b6e60ab77a5c75849961f52b143d/deepspeed/sequence/layer.py#L26), we will split the input alone scatter_idx dimension into seq_world_size group. And I consider that the scatter_idx is hidden_size dimension. And in [here](https://github.com/microsoft/DeepSpeed/blob/78c3b148a8a8b6e60ab77a5c75849961f52b143d/deepspeed/sequence/layer.py#L30), I consider the gather_idx is sequence dimension. Therefore, I consider the difference between scatter_idx and gather_idx should be one, but it is two in your code. So, can you explain it? Or, the input shape is (s, b, h), but I see [here](https://github.com/microsoft/DeepSpeed/blob/78c3b148a8a8b6e60ab77a5c75849961f52b143d/deepspeed/sequence/layer.py#L74), it seems that the input shape is (s, h). 

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by samadejacobs** [comment]
@yingtongxiong, yes, for all2all comm, we mostly care about sequence (s) and number of heads (h) dimensions. Assumption here is that s and h are indexed at 0 and 2 respectively (in most cases b will be at 1). However, client code can replace them as appropriate.

**Comment by yingtongxiong** [comment]
Thanks for your reply. And I notice that the sequence parallel in Deepspeed does not support pipeline parallel. So, why? I consider that there may be some extra communications like all-gather and scatter if I combine it with pipeline parallel.

**Comment by samadejacobs** [comment]
@yingtongxiong, combo of DeepSpeed sequence parallel and pipeline parallel are currently not supported/tested.

**Comment by yingtongxiong** [comment]
Okay，I want to know when do you support the combo of deepspeed sequence and pipeline ? Thank you very much.

**Comment by puppet101** [comment]
@samadejacobs Hi, I am finetuning Llama2, in which the input shape is (b, s, head_number, head_dim). So could you please help to set the scatter_idx and gather_idx?

**Comment by samadejacobs** [comment]
@puppet101 , for your use case: gather_idx=s=1, scatter_idx=head_num =2
