### ISSUE TITLE
installation process error

### ISSUE THREAD

**Issue by 18813187393** [microsoft/DeepSpeed#4365]
gcc: error: /tmpxft_00032e09_00000000-6_multi_tensor_adam.compute_86.cudafe1.cpp: No such file or directory
gcc: warning: ‘-x c++’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
error: command '/usr/local/cuda-11.7/bin/nvcc' failed with exit code 1

**Comment by loadams** [comment]
Hi @18813187393 - can you please share the installation command you are using to install along with your installed cuda and torch versions?

```
python -c "import torch; print('torch:', torch.__version__, torch)"
python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
```

**Comment by loadams** [comment]
Hi @18813187393 - following up on this.  I'm almost certain that this is an environment setup issue, if you're able to reinstall cuda/torch/gcc this should be resolved.  If you're still having issues please reply here or re-open and we can take a look.
