### ISSUE TITLE
Connection Refused Error when running Azure Quick Start Guide

### ISSUE THREAD

**Issue by Enumaris** [microsoft/DeepSpeed#438]
Hello,

I am following the guide to get DeepSpeed running on Azure found here: https://www.deepspeed.ai/tutorials/azure/ 

I created two vms, set them up, and set up the docker containers in them exactly as the guide suggested by using the `create_vms.sh`, `setup_vms.sh`, and `setup_docker.sh` files respectively. 

However, after I ssh into vm 0, attach to the container, and attempt `ssh worker-1 hostname` I get the following error:
`deepspeed@deepspeed0:~$ ssh worker-1 hostname`
`ssh: connect to host 10.0.0.5 port 2222: Connection refused`

I noticed that I can `ssh` if I specify port 22:

`deepspeed@deepspeed0:~$ ssh -p 22 worker-1 hostname`
`Warning: Permanently added '10.0.0.5' (ECDSA) to the list of known hosts.`
`deepspeed1`

But then I end up in the vm rather than inside the docker container. I've been unable to successfully `ssh` into the docker container. I've tried quite a bit of debugging but I can't seem to solve this issue. Please help.

**Comment by jeffra** [comment]
@Enumaris, so sorry you're having issues here. Have you made any progress here? If not I would first check to make sure your ssh server is running properly on port 2222 inside the docker container.

Inside the container: `sudo service ssh status` and also check to see if your `Port` is set to 2222 inside /etc/ssh/sshd_config

**Comment by Enumaris** [comment]
Hi @jeffra thanks for looking into this!

Running `sudo service ssh status` from inside the container reveals it is not running:

`deepspeed@01d1b2ac4605:~$ sudo service ssh status                                 
* sshd is not running`

I guess the set up scripts didn't start the ssh server within the container and only started the ssh in the vm? 

Looking at `/etc/ssh/sshd_config` reveals that the port is set to 22. I am not sure why this wasn't set to 2222 with the scripts used set up the container? 

Changing the port in `/etc/ssh/sshd_config` to 2222 and starting the ssh server inside the container with `sudo service ssh start` has appeared to work. If these steps are necessary to get things working, it would probably be good to mention them inside the tutorial? I think my main confusion was in managing the ssh of the vm vs the ssh of the container.

**Comment by jeffra** [comment]
Hi @Enumaris,

Glad to hear it's working now. That's really odd, these things should all be happening already.

The ssh port set to 2222 is done in the docker image: https://github.com/microsoft/DeepSpeed/blob/95575579b3304f3cdd6bc1f9715535d424768b87/docker/Dockerfile#L149-L154

The starting of the ssh service should be done when the container is started here:
https://github.com/microsoft/DeepSpeed/blob/95575579b3304f3cdd6bc1f9715535d424768b87/azure/setup_docker.sh#L32

Which calls: 
https://github.com/microsoft/DeepSpeed/blob/95575579b3304f3cdd6bc1f9715535d424768b87/azure/start_container.sh#L6-L11

**Comment by Enumaris** [comment]
That's very odd indeed... all I can say is I followed the tutorial and ran all the scripts maybe 3-4 times, starting from scratch each time, and it never worked for me until I manually changed the port and started the ssh service within the container.

**Comment by jeffra** [comment]
Gotcha, again so sorry you had to spend this much time. Glad it's working now. We will run through the steps again on our side and see if we can repro the issue. It's possible something has changed since we last tried these steps and one of the steps is silently failing.

**Comment by jeffra** [comment]
Closing for now, feel free to re-open if you have any further issues/questions.

**Comment by rivalset** [comment]
I'm had the same problem. The problem seems to be that the ssh port is set 22 and not 2222 in /etc/ssh/sshd_config

Another change I had to make was to change the instance type from Standard_NV6_Promo to Standard_NV6.

**Comment by jeffra** [comment]
@rivalset Not sure if this is applicable in your setup but we've recently been creating new documentation to get started with DeepSpeed on AzureML which is a lot less work to setup than running bare Azure VMs. Here's a video my colleague @awan-10 created: https://youtu.be/yBVXR8G8Bg8

**Comment by rivalset** [comment]
Thanks for the pointer. I will take a look.
