### ISSUE TITLE
Installation error: '/usr/bin/gcc' failed with exit code 1

### ISSUE THREAD

**Issue by luan-xiaokun** [microsoft/DeepSpeed#4381]
Hi, I get an error when installing DeepSpeed using pip:

```
      /home/luan/miniconda3/envs/llm4tp/lib/python3.10/site-packages/torch/include/c10/util/string_view.h: In instantiation of ‘std::basic_ostream<CharT>& c10::operator<<(std::basic_ostream<CharT>&, c10::basic_string_view<CharT>) [with CharT = char]’:
      /home/luan/miniconda3/envs/llm4tp/lib/python3.10/site-packages/torch/include/c10/util/typeid.h:600:34:   required from here
      /home/luan/miniconda3/envs/llm4tp/lib/python3.10/site-packages/torch/include/c10/util/string_view.h:577:35: error: ‘std_string_type’ was not declared in this scope
        577 |   return stream << std_string_type(sv.data(), sv.size());
            |                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> deepspeed

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

I tried installing `python3-dev` (using apt) but still get the same error.

The command I used:

```
DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed
```

Here is some related environment information: 

- OS: Ubuntu 22.04
- Python: 3.10 (conda environment)
- gcc: 11.4
- nvcc: 12.1
- cuDNN: 8.9.5
- NVIDIA driver: 535.104.35
- torch: 2.2.0.dev20230920+cu121

**Comment by luan-xiaokun** [comment]
Here is the complete error message: [log.txt](https://github.com/microsoft/DeepSpeed/files/12679997/log.txt)

**Comment by loadams** [comment]
Hi @luan-xiaokun - I see a few different issues in your log, but this one does stand out: 

```
error: #error You need C++17 to compile PyTorch
         27 | #error You need C++17 to compile PyTorch
```

I'd guess something is wrong with your setup on that part.  Also, could you try installing deepspeed without [precompiling the ops](https://www.deepspeed.ai/tutorials/advanced-install/#pre-install-deepspeed-ops)?  That would be just running `pip install deepspeed` since that will result in a smaller error log as it won't be trying to build all the ops now and we can see if this is a problem with compiling the ops which would still need to be addressed or with torch/c++?

**Comment by luan-xiaokun** [comment]
Hi @loadams, thanks for your reply.

Installing deepspeed without precompiling the ops using `pip install deepspeed` succeeds with no errors, and the output of `ds_report` also seems fine:

```
[2023-09-22 11:41:02,429] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.2
 [WARNING]  using untested triton version (2.1.0+6e4932cda8), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/luan/miniconda3/envs/llm4tp/lib/python3.10/site-packages/torch']
torch version .................... 2.2.0.dev20230920+cu121
deepspeed install path ........... ['/home/luan/miniconda3/envs/llm4tp/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.3, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.2, cuda 12.1
shared memory (/dev/shm) size .... 15.61 GB
```

With regard to torch/C++, since I want to use cuda 12.1, I installed a nightly build of torch using the following command (following [pytorch's instruction](https://pytorch.org/get-started/locally/)):

```
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
```

**Comment by loadams** [comment]
Hi @luan-xiaokun - the pip command should be fine.  If you wanted to try with Conda, we have a rough environment.yml [here](https://github.com/microsoft/DeepSpeed/blob/master/environment.yml), that you'd want to update with your torch/cuda/etc.

But for this, if you try to run once you've installed DeepSpeed without pre-compiling ops, do you see the same issue?  And are you able to tell which op, if any is causing the error?

I'd also recommend maybe trying to reinstall gcc since the 11.4 version you have should be the right one that has c++17 support, but its not finding something.

**Comment by luan-xiaokun** [comment]
> But for this, if you try to run once you've installed DeepSpeed without pre-compiling ops, do you see the same issue? And are you able to tell which op, if any is causing the error?

I see no error if I install DeepSpeed without pre-compiling ops, and I'm afraid I can't tell which op is causing the error.

> If you wanted to try with Conda, we have a rough environment.yml [here](https://github.com/microsoft/DeepSpeed/blob/master/environment.yml), that you'd want to update with your torch/cuda/etc.

Thanks for the reference, I've downgraded cuda to 11.8 from 12.1 and reinstalled the packages, and now everything works fine.

**Comment by loadams** [comment]
@luan-xiaokun - I see, you could try one at a time enabling `DS_BUILD_*=1` but that's perhaps overkill here.  Since it seems like an environment issue, are you okay with closing this issue?

**Comment by luan-xiaokun** [comment]
@loadams Sure, it seems like an environment issue. For anyone who has similar errors, try downgrading cuda.

**Comment by tdye24** [comment]
> @loadams Sure, it seems like an environment issue. For anyone who has similar errors, try downgrading cuda.

Downgrade the cuda toolkit (nvcc) or including the driver?
There are multiple cuda toolkit version in my machine, including 11.8 and 12.0.

**Comment by luan-xiaokun** [comment]
Hi @tdye24

> Downgrade the cuda toolkit (nvcc) or including the driver?

I can't remember if I downgraded the driver or not as it's been a while, but maybe you can first try just downgrading the toolkit. If you are not getting the same problem as I was, I suggest you open another issue.
