### ISSUE TITLE
DeepSpeed & TortoiSETTS [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by darkphyre** [microsoft/DeepSpeed#4392]
For a little background I have a windows 10 machine with a nvidia driver. I've download and isntalled the cuda 11.7 drivers in order to use deepspeed==0.8.3

I've followed the TortoisSe install here https://github.com/neonbjb/tortoise-tts and now I am getting this error:

`` Using cached deepspeed-0.8.3.tar.gz (765 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [16 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "C:\Users\CallMeRed\AppData\Local\Temp\pip-install-0hsn19a7\deepspeed_911510a3fdf342e8b834ae4e0e5dc915\setup.py", line 78, in
cupy = f"cupy-cuda{''.join(map(str,installed_cuda_version()))}"
File "C:\Users\CallMeRed\AppData\Local\Temp\pip-install-0hsn19a7\deepspeed_911510a3fdf342e8b834ae4e0e5dc915\op_builder\builder.py", line 46, in installed_cuda_version
output = subprocess.check_output([cuda_home + "/bin/nvcc",
File "C:\miniconda3\envs\tortoise\lib\subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "C:\miniconda3\envs\tortoise\lib\subprocess.py", line 505, in run
with Popen(*popenargs, **kwargs) as process:
File "C:\miniconda3\envs\tortoise\lib\subprocess.py", line 951, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\miniconda3\envs\tortoise\lib\subprocess.py", line 1436, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.``

I'm not entirely sure of what file cannot be found, any help is appreciated

**Comment by loadams** [comment]
Hi @darkphyre - we know DeepSpeed is not well supported on Windows, but the main steps we have, other than those that can be found in similar issues in this repo are [here](https://github.com/microsoft/DeepSpeed#windows).  Also, we'd recommend using a newer version of DeepSpeed if you're able to, since 0.8.3 is quite old.  

Also, for ease of install and to use all features of DeepSpeed as some are not supported on Windows, we recommend using [WSL](https://learn.microsoft.com/en-us/windows/wsl/about).

**Comment by loadams** [comment]
Hi @darkphyre - closing this issue as it is stale, but this other issue looks to be [similar](https://github.com/microsoft/DeepSpeed/issues/4470).
