### ISSUE TITLE
[BUG] 10 errors detected in the compilation of "csrc/quantization/dequantize.cu" when I install deepspeed==0.10.3

### ISSUE THREAD

**Issue by iamsile** [microsoft/DeepSpeed#4400]
**Describe the bug**
When I install deepspeed from pip. I meet a bug like this:
10 errors detected in the compilation of "csrc/quantization/dequantize.cu".
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1

**log report**
building 'deepspeed.ops.quantizer.quantizer_op' extension
      creating build/temp.linux-x86_64-cpython-38/csrc/quantization
      /usr/local/cuda/bin/nvcc -Icsrc/includes -I/vq_ssd/taowei03/env/new_test/lib/python3.8/site-packages/torch/include -I/vq_ssd/taowei03/env/new_test/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/vq_ssd/taowei03/env/new_test/lib/python3.8/site-packages/torch/include/TH -I/vq_ssd/taowei03/env/new_test/lib/python3.8/site-packages/torch/include/THC -I/vq_ssd/taowei03/env/new_test/include/python3.8 -c csrc/quantization/dequantize.cu -o build/temp.linux-x86_64-cpython-38/csrc/quantization/dequantize.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=quantizer_op -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
      csrc/includes/reduction_utils.h(178): error: no operator "+" matches these operands
                  operand types are: const __half + const __half
      
      csrc/includes/reduction_utils.h(188): error: no operator ">" matches these operands
                  operand types are: const __half > const __half
      
      csrc/includes/reduction_utils.h(199): error: no operator "<" matches these operands
                  operand types are: const __half < const __half
      
      csrc/includes/reduction_utils.h(207): error: no operator "+" matches these operands
                  operand types are: const __half2 + const __half2
      
      csrc/includes/reduction_utils.h(217): error: no operator ">" matches these operands
                  operand types are: const __half > const __half
      
      csrc/includes/reduction_utils.h(218): error: no operator ">" matches these operands
                  operand types are: const __half > const __half
      
      csrc/includes/reduction_utils.h(230): error: no operator "<" matches these operands
                  operand types are: const __half < const __half
      
      csrc/includes/reduction_utils.h(231): error: no operator "<" matches these operands
                  operand types are: const __half < const __half
      
      csrc/includes/dequantization_utils.h(166): warning: constexpr if statements are a C++17 feature
                detected during:
                  instantiation of "void dequantize_kernel<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=__half, numBits=8, qType=quantize::Type::Symmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(46): here
                  instantiation of "void launch_dequantize_kernel(T *, const int8_t *, const float *, quantize::Type, int, int, int, cudaStream_t) [with T=__half]"
      csrc/quantization/dequantize.cu(56): here
      
      csrc/includes/quantization_utils.h(125): error: no suitable conversion function from "__half" to "float" exists
                detected during:
                  instantiation of "T quantize::Params<quantize::Type::Asymmetric, numBits>::dequantize<T>(int8_t) [with numBits=8, T=float]"
      csrc/includes/dequantization_utils.h(76): here
                  instantiation of "void dequantize::chunk(T *, const int8_t *, dequantize::Params<qType, numBits>) [with T=float, numBits=8, qType=quantize::Type::Asymmetric]"
      csrc/includes/dequantization_utils.h(152): here
                  instantiation of "void dequantize::_to_global<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=8, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/includes/dequantization_utils.h(168): here
                  instantiation of "void dequantize::to_global<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=8, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(19): here
                  instantiation of "void dequantize_kernel<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=8, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(48): here
                  instantiation of "void launch_dequantize_kernel(T *, const int8_t *, const float *, quantize::Type, int, int, int, cudaStream_t) [with T=float]"
      csrc/quantization/dequantize.cu(65): here
      
      csrc/includes/quantization_utils.h(125): error: no suitable conversion function from "__half" to "float" exists
                detected during:
                  instantiation of "T quantize::Params<quantize::Type::Asymmetric, numBits>::dequantize<T>(int8_t) [with numBits=4, T=float]"
      csrc/includes/dequantization_utils.h(79): here
                  instantiation of "void dequantize::chunk(T *, const int8_t *, dequantize::Params<qType, numBits>) [with T=float, numBits=4, qType=quantize::Type::Asymmetric]"
      csrc/includes/dequantization_utils.h(152): here
                  instantiation of "void dequantize::_to_global<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=4, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/includes/dequantization_utils.h(168): here
                  instantiation of "void dequantize::to_global<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=4, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(19): here
                  instantiation of "void dequantize_kernel<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=4, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(52): here
                  instantiation of "void launch_dequantize_kernel(T *, const int8_t *, const float *, quantize::Type, int, int, int, cudaStream_t) [with T=float]"
      csrc/quantization/dequantize.cu(65): here
      
      10 errors detected in the compilation of "csrc/quantization/dequantize.cu".
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

**ds_report output**
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
async_io ............... [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.7/site-packages/torch']
torch version .................... 1.8.2+cu111
torch cuda version ............... 11.1
nvcc version ..................... 11.1
deepspeed install path ........... ['/opt/conda/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.5.7, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.8, cuda 11.1

**pip list:**
Package                     Version
--------------------------- -----------
annotated-types             0.5.0
cmake                       3.27.5
filelock                    3.12.4
hjson                       3.1.0
intel-extension-for-pytorch 2.0.100
mpi4py                      3.1.4
ninja                       1.11.1
numpy                       1.24.4
packaging                   23.1
Pillow                      10.0.1
pip                         23.2.1
psutil                      5.9.5
py-cpuinfo                  9.0.0
pydantic                    1.10.12
pydantic_core               2.6.3
scipy                       1.10.1
setuptools                  68.0.0
tabulate                    0.9.0
torch                       1.8.1+cu101
torchaudio                  0.8.1
torchvision                 0.9.1+cu101
tqdm                        4.66.1
triton                      2.0.0
typing_extensions           4.8.0
wheel                       0.38.4
xgboost                     2.0.0

**command:**
DS_BUILD_OPS=1 DS_BUILD_QUANTIZER=1 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed==0.10.3

# CUDA 10.1
pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by loadams** [comment]
Hi @iamsile - just to confirm your cuda version is 10.1 and torch version is 1.8?  Those are both quite old, is it possible to update those?  The latest torch version we support is 1.10.

**Comment by iamsile** [comment]
> Hi @iamsile - just to confirm your cuda version is 10.1 and torch version is 1.8? Those are both quite old, is it possible to update those? The latest torch version we support is 1.10.

yes, my cuda version is 10.1 and  torch version is 1.8. I think it's hard to update. Is there any other way to install quantizer?

**Comment by loadams** [comment]
@iamsile - thanks for updating those, it will make it much easier to debug hopefully.  

However, now your issue looks to be either:

```
/vq_ssd/xxxx/env/mplug_owl/lib/python3.10/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
#include <Python.h>
```

or this:

```
nvcc fatal : Unknown option '-Wno-reorder'
```

Which would be issues with either the torch installation or cuda.  It also looks like you have a few torch verisons installed on this machine from the ds_report, I see 1.10 and 1.8.2+cu111.  So can you run `pip list` and share that output?

Also it looks like you are missing setuptools, so please run `pip install setuptools` and try to install deepspeed after that too.

Thanks!

**Comment by iamsile** [comment]
> @iamsile - thanks for updating those, it will make it much easier to debug hopefully.
> 
> However, now your issue looks to be either:
> 
> ```
> /vq_ssd/xxxx/env/mplug_owl/lib/python3.10/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
> #include <Python.h>
> ```
> 
> or this:
> 
> ```
> nvcc fatal : Unknown option '-Wno-reorder'
> ```
> 
> Which would be issues with either the torch installation or cuda. It also looks like you have a few torch verisons installed on this machine from the ds_report, I see 1.10 and 1.8.2+cu111. So can you run `pip list` and share that output?
> 
> Also it looks like you are missing setuptools, so please run `pip install setuptools` and try to install deepspeed after that too.
> 
> Thanks!

@loadams Thanks very much. I found thad after update cuda, my colleague installed another torch. now I have delete torch 1.10.
This is my new pip list:
Package                     Version
--------------------------- -----------
annotated-types             0.5.0
cmake                       3.27.5
filelock                    3.12.4
hjson                       3.1.0
intel-extension-for-pytorch 2.0.100
mpi4py                      3.1.4
ninja                       1.11.1
numpy                       1.24.4
packaging                   23.1
Pillow                      10.0.1
pip                         23.2.1
psutil                      5.9.5
py-cpuinfo                  9.0.0
pydantic                    1.10.12
pydantic_core               2.6.3
scipy                       1.10.1
setuptools                  68.0.0
tabulate                    0.9.0
torch                       1.8.1+cu101
torchaudio                  0.8.1
torchvision                 0.9.1+cu101
tqdm                        4.66.1
triton                      2.0.0
typing_extensions           4.8.0
wheel                       0.38.4
xgboost                     2.0.0

Then I use this command to try to install deepspeed and get the error like this:
command:
DS_BUILD_OPS=1 DS_BUILD_QUANTIZER=1 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed==0.10.3

error report:
/vq_ssd/xxxxxx/env/new_test/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:398:1: note: declared here
         T * data() const {
       ^ ~~
      csrc/lamb/fused_lamb_cuda_kernel.cu:428:583: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
               AT_DISPATCH_FLOATING_TYPES(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^
      /vq_ssd/xxxxxx/env/new_test/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:398:1: note: declared here
         T * data() const {
       ^ ~~
      g++ -pthread -B /vq_ssd/xxxxxx/env/new_test/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /vq_ssd/xxxxxx/env/new_test/compiler_compat -L/vq_ssd/xxxxxx/env/new_test/lib -Wl,-rpath=/vq_ssd/xxxxxx/env/new_test/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-cpython-38/csrc/lamb/fused_lamb_cuda.o build/temp.linux-x86_64-cpython-38/csrc/lamb/fused_lamb_cuda_kernel.o -L/vq_ssd/xxxxxx/env/new_test/lib/python3.8/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-38/deepspeed/ops/lamb/fused_lamb_op.cpython-38-x86_64-linux-gnu.so
      building 'deepspeed.ops.quantizer.quantizer_op' extension
      creating build/temp.linux-x86_64-cpython-38/csrc/quantization
      /usr/local/cuda/bin/nvcc -Icsrc/includes -I/vq_ssd/xxxxxx/env/new_test/lib/python3.8/site-packages/torch/include -I/vq_ssd/xxxxxx/env/new_test/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/vq_ssd/xxxxxx/env/new_test/lib/python3.8/site-packages/torch/include/TH -I/vq_ssd/xxxxxx/env/new_test/lib/python3.8/site-packages/torch/include/THC -I/vq_ssd/xxxxxx/env/new_test/include/python3.8 -c csrc/quantization/dequantize.cu -o build/temp.linux-x86_64-cpython-38/csrc/quantization/dequantize.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=quantizer_op -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
      csrc/includes/reduction_utils.h(178): error: no operator "+" matches these operands
                  operand types are: const __half + const __half
      
      csrc/includes/reduction_utils.h(188): error: no operator ">" matches these operands
                  operand types are: const __half > const __half
      
      csrc/includes/reduction_utils.h(199): error: no operator "<" matches these operands
                  operand types are: const __half < const __half
      
      csrc/includes/reduction_utils.h(207): error: no operator "+" matches these operands
                  operand types are: const __half2 + const __half2
      
      csrc/includes/reduction_utils.h(217): error: no operator ">" matches these operands
                  operand types are: const __half > const __half
      
      csrc/includes/reduction_utils.h(218): error: no operator ">" matches these operands
                  operand types are: const __half > const __half
      
      csrc/includes/reduction_utils.h(230): error: no operator "<" matches these operands
                  operand types are: const __half < const __half
      
      csrc/includes/reduction_utils.h(231): error: no operator "<" matches these operands
                  operand types are: const __half < const __half
      
      csrc/includes/dequantization_utils.h(166): warning: constexpr if statements are a C++17 feature
                detected during:
                  instantiation of "void dequantize_kernel<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=__half, numBits=8, qType=quantize::Type::Symmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(46): here
                  instantiation of "void launch_dequantize_kernel(T *, const int8_t *, const float *, quantize::Type, int, int, int, cudaStream_t) [with T=__half]"
      csrc/quantization/dequantize.cu(56): here
      
      csrc/includes/quantization_utils.h(125): error: no suitable conversion function from "__half" to "float" exists
                detected during:
                  instantiation of "T quantize::Params<quantize::Type::Asymmetric, numBits>::dequantize<T>(int8_t) [with numBits=8, T=float]"
      csrc/includes/dequantization_utils.h(76): here
                  instantiation of "void dequantize::chunk(T *, const int8_t *, dequantize::Params<qType, numBits>) [with T=float, numBits=8, qType=quantize::Type::Asymmetric]"
      csrc/includes/dequantization_utils.h(152): here
                  instantiation of "void dequantize::_to_global<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=8, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/includes/dequantization_utils.h(168): here
                  instantiation of "void dequantize::to_global<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=8, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(19): here
                  instantiation of "void dequantize_kernel<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=8, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(48): here
                  instantiation of "void launch_dequantize_kernel(T *, const int8_t *, const float *, quantize::Type, int, int, int, cudaStream_t) [with T=float]"
      csrc/quantization/dequantize.cu(65): here
      
      csrc/includes/quantization_utils.h(125): error: no suitable conversion function from "__half" to "float" exists
                detected during:
                  instantiation of "T quantize::Params<quantize::Type::Asymmetric, numBits>::dequantize<T>(int8_t) [with numBits=4, T=float]"
      csrc/includes/dequantization_utils.h(79): here
                  instantiation of "void dequantize::chunk(T *, const int8_t *, dequantize::Params<qType, numBits>) [with T=float, numBits=4, qType=quantize::Type::Asymmetric]"
      csrc/includes/dequantization_utils.h(152): here
                  instantiation of "void dequantize::_to_global<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=4, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/includes/dequantization_utils.h(168): here
                  instantiation of "void dequantize::to_global<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=4, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(19): here
                  instantiation of "void dequantize_kernel<T,numBits,qType,unroll,threads>(T *, const int8_t *, const float *, int, int) [with T=float, numBits=4, qType=quantize::Type::Asymmetric, unroll=8, threads=512]"
      csrc/quantization/dequantize.cu(52): here
                  instantiation of "void launch_dequantize_kernel(T *, const int8_t *, const float *, quantize::Type, int, int, int, cudaStream_t) [with T=float]"
      csrc/quantization/dequantize.cu(65): here
      
      10 errors detected in the compilation of "csrc/quantization/dequantize.cu".
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for deepspeed
  Running setup.py clean for deepspeed
Failed to build deepspeed


I had delete everything about deepspeed, so I can't print my ds_report:
bash: /opt/conda/bin/ds_report: No such file or directory

Thanks. Looking forward to your reply.

**Comment by loadams** [comment]
Also, what GPU are you targetting here?  It looks like compute_70 so Volta?

**Comment by iamsile** [comment]
> I see, I believe you'll still need to update the cuda version and torch version, since I still see torch built for an old cuda verison:
> 
> ```
> torch 1.8.1+cu101
> ```
> 
> I suspect this is a compilation issue/mismatch with torch/cuda/nvcc and the supported version DeepSpeed expects.

thanks very much, I'll go check it out.

**Comment by iamsile** [comment]
> Also, what GPU are you targetting here? It looks like compute_70 so Volta?

my gpu is 8*v100 32g

**Comment by iamsile** [comment]
@loadams thank you very much ! thank you very much ! As you say, when I update pytorch to 1.10 and install it successfully.
<img width="791" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/2016205/a08e89c9-f533-41aa-9891-9a905574f124">
