### ISSUE TITLE
Is torch 2.0 or above currently supported? Where can I find the version compatibility correspondence between DeepSpeed and torch?

### ISSUE THREAD

**Issue by cooper190113** [microsoft/DeepSpeed#4476]
Is torch 2.0 or above currently supported? Where can I find the version compatibility correspondence between DeepSpeed and torch?

**Comment by mrwyattii** [comment]
Hi @cooper190113 we support torch 2.0+. Older versions of DeepSpeed (i.e., those pre-dating torch 2.0 release) may not be compatible.
