### ISSUE TITLE
[BUG]Must the number of nodes trained be a multiple of 2？

### ISSUE THREAD

**Issue by nicosouth** [microsoft/DeepSpeed#4478]
hi

when i use deepspeed to train my model, a strange phenomenon appeared. 

i have some 8*A800 servers. 
i find that when I train with nodes that are not multiples of 2 (such as 3 nodes, 24 A800 GPUs), the overall communication efficiency will be very low. Even, the training speed of three nodes is slower than that of two nodes.

i have read the paper and the code carefully, but i can't find why is it.

can you provide some explanation?
thank you!

**Comment by GuanhuaWang** [comment]
Hi @nicosouth , Based on your description, I believe it is a communication/network issue and  maybe should be raised on nvidia/NCCL side.
