### ISSUE TITLE
[BUG] `RuntimeError: element 0 of tensors does not require grad` when running activation checkpointing with pipeline parallelism

### ISSUE THREAD

**Issue by brunomaga** [microsoft/DeepSpeed#4479]
**Describe the bug**

This bug may be related to https://github.com/microsoft/DeepSpeed/issues/4274 .

When I run activation checkpointing with pipeline parallelism, I get the following error:
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**To Reproduce**

- extract the train loop in `train.py`, the ML model and dataset in `benchmark.py`, and the ds config in `ds_config.json`, all zipped inside [code.zip](https://github.com/microsoft/DeepSpeed/files/12845179/code.zip)
  - this is a model of 2048 very-simple perfectly-balanced linear layers;
- run `deepspeed --num_gpus=8 train.py --deepspeed --deepspeed_config ds_config.json --activation_checkpoint_interval 8 --pipeline_num_stages 4 --pipeline_spec_layers` 
  - `--pipeline_spec_layers` runs the memory efficient pipeline, with `SpecLayer`. Remove it to run the non-`SpecLayer` implementation, and this issue is still visible;
  - `--pipeline_num_stages` defines the number of stages. The issue is visible for any number of stages (2, 4, 8);

**Expected behaviour**

You should get the following traceback and error:
```
Traceback (most recent call last):
  File "~/train.py", line 110, in <module>
    main_deepspeed()
  File "~/tests/train.py", line 91, in main_deepspeed
    loss = engine.train_batch()
  File "~/.local/lib/python3.10/site-packages/deepspeed/runtime/pipe/engine.py", line 355, in train_batch
    self._exec_schedule(sched)
  File "~/.local/lib/python3.10/site-packages/deepspeed/runtime/pipe/engine.py", line 1336, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "~/.local/lib/python3.10/site-packages/deepspeed/runtime/pipe/engine.py", line 756, in _exec_backward_pass
    torch.autograd.backward(tensors=(outputs, ), grad_tensors=(grad_tensors, ))
  File "~/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "~/train.py", line 110, in <module>
    main_deepspeed()
  File "~/train.py", line 91, in main_deepspeed
    loss = engine.train_batch()
  File "~/.local/lib/python3.10/site-packages/deepspeed/runtime/pipe/engine.py", line 355, in train_batch
    self._exec_schedule(sched)
  File "~/.local/lib/python3.10/site-packages/deepspeed/runtime/pipe/engine.py", line 1336, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "~/.local/lib/python3.10/site-packages/deepspeed/runtime/pipe/engine.py", line 756, in _exec_backward_pass
    torch.autograd.backward(tensors=(outputs, ), grad_tensors=(grad_tensors, ))
  File "~/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**ds_report output**

```
[2023-10-09 10:53:47,040] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  NVIDIA Inference is only supported on Pascal and newer architectures
transformer_inference .. [NO] ....... [NO]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['~/.local/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1+cu117
deepspeed install path ........... ['~/.local/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.3, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 12.2
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
shared memory (/dev/shm) size .... 125.89 GB
```

**System info:**

- Ubuntu 20.04.6 LTS
- `deepspeed=0.10.3`, `torch==2.0.1` and `torch.version.cuda==11.7`
- 1 single compute node, with 8x NVIDIA GeForce GTX TITAN X.

**Comment by MetaBlues** [comment]
maybe same as https://github.com/microsoft/DeepSpeed/issues/4332

**Comment by brunomaga** [comment]
Im using `deepspeed==0.12.6` and that issue is still there. The issue in my case was that I was doing a transpose of the final logits with `torch.swapaxes(logits,1,2)`. This was then passed to the loss module, that fails. I fixed it by forcing loss to compute gradients in the output array by adding:

```
outputs = model(inputs)
outputs = outputs.requires_grad_(True)   # <----- added this
loss = criterion(output, logits)
```

**Comment by janelu9** [comment]
I meet the same problem, and I am using `LayerSpec`, I solved it by setting `checkpointable_layers` to filter the layers who needn't been activated, such as the `Embedding layer`.

**Comment by janelu9** [comment]
> Im using `deepspeed==0.12.6` and that issue is still there. The issue in my case was that I was doing a transpose of the final logits with `torch.swapaxes(logits,1,2)`. This was then passed to the loss module, that fails. I fixed it by forcing loss to compute gradients in the output array by adding:
> 
> ```
> outputs = model(inputs)
> outputs = outputs.requires_grad_(True)   # <----- added this
> loss = criterion(output, logits)
> ```
> 
> when using pipeline parallelism, then the change has to be at the loss level instead, e.g.:
> 
> ```
> class CrossEntropyLoss_TransposedLogits(torch.nn.Module):
>   def forward(self, logits, labels):
>     # from shape (B,T,C) to (B,C,T)
>     logits = torch.swapaxes(logits,1,2)
>     # fix RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
>     logits = logits.requires_grad_(True)
>     return torch.nn.functional.cross_entropy(logits, labels)
> ```
> 
> even though this worked for the standard pipeline definition (using `list[nn.Module]` or `nn.Sequential[nn.Module]`) but not the one using `list[LayerSpec]` or `nn.Sequential[LayerSpec]`.

Though no errors happend, but the loss is not decreased for my model
