### ISSUE TITLE
[REQUEST] Support for converting zero sharded checkpoint files with MoE layers trained with stage 2 to fp32 state dict

### ISSUE THREAD

**Issue by SOUMAJYOTI** [microsoft/DeepSpeed#4497]
**Is your feature request related to a problem? Please describe.**
The current implementation in [zero_to_fp32.py](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/utils/zero_to_fp32.py) results in an error when using saved zero2 checkpoints of a model that includes the deepspeed [mixture of experts layer](https://github.com/microsoft/DeepSpeed/blob/bbfd0a6a3e7bd43d816b250b4cecb67504c0c340/deepspeed/moe/layer.py). Specifically, it cannot handle the extra optimizer states corresponding to the expert parallel groups and the model states for MoE layers.

**Describe the solution you'd like**
Modify [zero_to_fp32.py ](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/utils/zero_to_fp32.py) to extend the functionality that converts deepspeed stage 2 models with MoE layers to an fp32 state dict similar to models without MoE layers.

**Describe alternatives you've considered**
An alternative would be to consider using the deepspeed engine to load the checkpoints without the optimizer states (https://deepspeed.readthedocs.io/en/latest/model-checkpointing.html) but I cannot confirm.

**Additional context**
The below shows the extra files saved with MoE layers (example below shows a model with 2 MoE layers trained with expert parallelism of size 8 and trained on 1 node with 8 GPUs).

![Screenshot 2023-10-10 at 11 30 35 PM](https://github.com/microsoft/DeepSpeed/assets/1736405/453c3175-03e6-4c53-a087-8913513e09aa)

**Comment by SOUMAJYOTI** [comment]
Closing

**Comment by BinZhu-ece** [comment]
Have you solved this problem? I have encountered the same problem and look forward to your reply

**Comment by suu990901** [comment]
> Have you solved this problem? I have encountered the same problem and look forward to your reply

Have you solved it? I also encountered this problem.
