### ISSUE TITLE
[BUG] gemm_test uses rocblas instead of hipblas, but dose not include rocblas

### ISSUE THREAD

**Issue by IMbackK** [microsoft/DeepSpeed#4507]
With rocm 5.7 deepspeed no longer compiles as rocblas is use directly here:
https://github.com/microsoft/DeepSpeed/blob/4fc181b01077521ba42379013ce91a1c294e5d8e/csrc/includes/gemm_test.h#L68
instead of hipblas.

hipify translates to, and will only include, hip headers and thus this will fail to compile.
Previously in AMD's rocm implementation of hip, rocblas was indirectly included here, this is no longer the case in 5.7, thus any translation unit with this header in it will fail to compile

additionally __HIP_PLATFORM_HCC__ is deprecated and should be replaced with __HIP_PLATFORM_AMD__ in code paths that are intended to target the rocm hip implementation only

**Comment by ahmedashraf093** [comment]
got the same issue, is there any workarounds ?

**Comment by IMbackK** [comment]
sure just include rocblas:

```
diff --git a/csrc/includes/gemm_test.h b/csrc/includes/gemm_test.h
index cd9fbb5a..2567615e 100644
--- a/csrc/includes/gemm_test.h
+++ b/csrc/includes/gemm_test.h
@@ -8,6 +8,7 @@
 #include <cuda_fp16.h>
 #ifndef __HIP_PLATFORM_HCC__
 #include <cuda_profiler_api.h>
+#include <rocblas/rocblas.h>
 #endif
 #include <array>
 #include <cstdio>
```

**Comment by ahmedashraf093** [comment]
Worked like a charm, ty @IMbackK

**Comment by loadams** [comment]
CC: @rraminen and @jithunnair-amd for feedback on this?

**Comment by rraminen** [comment]
Checking this issue

**Comment by jithunnair-amd** [comment]
@IMbackK You mentioned "Previously in AMD's rocm implementation of hip, rocblas was indirectly included here, this is no longer the case in 5.7". Can you please specify which ROCm/HIP header you are referring to?

**Comment by IMbackK** [comment]
@jithunnair-amd unfortunately i can not, besides empirically observing that the subject header here compiles against rocm 5.5 but not 5.7

**Comment by rraminen** [comment]
Filed https://github.com/microsoft/DeepSpeed/pull/4538

**Comment by loadams** [comment]
@IMbackK - can you please test with the linked PR?

**Comment by jithunnair-amd** [comment]
@IMbackK Also, which extension were you building that ran into this error?
And just to clarify, afaik, this issue is not exactly coming from ROCm5.6->5.7 changes, but instead from a recent PyTorch commit where we switched to hipifying `cublas_v2.h` -> `hipblas.h` (instead of `rocblas.h`):
https://github.com/pytorch/pytorch/pull/105881/files#diff-85bd10d67a85149584e7d7a8cba533241f7ad14450e5d54ffec23da34032429aR609

**Comment by IMbackK** [comment]
@jithunnair-amd 
Surprisingly i first encountered this while building cpu_adam 
the object that fails to build is built with:

`/opt/rocm/bin/hipcc  -DWITH_HIP -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1017\" -Ivenv/lib/python3.11/site-packages/deepspeed/ops/csrc/includes -I/opt/rocm/include -I/opt/rocm/include/rocrand -I/opt/rocm/include/hiprand -I/usr/lib/python3.11/site-packages/torch/include -I/usr/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/usr/lib/python3.11/site-packages/torch/include/TH -I/usr/lib/python3.11/site-packages/torch/include/THC -I/usr/lib/python3.11/site-packages/torch/include/THH -I/opt/rocm/include -I/usr/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -L/opt/rocm/lib -lcudart -lcublas -g -march=native -fopenmp -D__AVX256__ -D__DISABLE_CUDA__ -fPIC -D__HIP_PLATFORM_HCC__=1 -DUSE_ROCM=1 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -O3 -std=c++17 -U__HIP_NO_HALF_OPERATORS__ -U__HIP_NO_HALF_CONVERSIONS__ -U__HIP_NO_HALF2_OPERATORS__ -DROCM_VERSION_MAJOR=5 -DROCM_VERSION_MINOR=6 --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx1030 -fno-gpu-rdc -c venv/lib/python3.11/site-packages/deepspeed/ops/csrc/common/custom_hip_kernel.hip -o custom_hip_kernel.cuda.o`

I can confirm that the above pr solves the intimidate issue of the extensions failing to build, however the resulting extension dose not function when loaded, its use immidatly resulting in a gpu page fault derefrecing a nullptr at least when compiled for GFX906, the gfx900 version seams to work fine.

I will try see if this also shows on deepspeed examples, or try and create a more minimal repoducer and report this new problem as a separate bug.

**Comment by loadams** [comment]
Thanks @IMbackK and @jithunnair-amd!
