### ISSUE TITLE
Not compatible Torch version 2.1.0 ...Torch 2.0 is needed!

### ISSUE THREAD

**Issue by mdhont** [microsoft/DeepSpeed#4514]
Bitnami developer here. I'm trying to compile DeepSpeed which according to documentation can be built with PyTorch >= 1.9 but I'm getting this error using PyTorch 2.1:

```
18:26:47  -- Found Torch: /opt/bitnami/python/lib/python3.8/site-packages/torch/lib/libtorch.so (Required is at least version "2.0") 
18:26:47  -- Configuring incomplete, errors occurred!
18:26:47  
18:26:47  STDERR: CMake Warning at /opt/bitnami/python/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
18:26:47    static library kineto_LIBRARY-NOTFOUND not found.
18:26:47  Call Stack (most recent call first):
18:26:47    /opt/bitnami/python/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
18:26:47    CMakeLists.txt:20 (find_package)
18:26:47  
18:26:47  
18:26:47  CMake Error at CMakeLists.txt:27 (message):
18:26:47    Not compatible Torch version 2.1.0 at
18:26:47    /opt/bitnami/python/lib/python3.8/site-packages/torch!
18:26:47  
18:26:47    Torch 2.0 is needed!
```

Does this mean the maximum Torch version should be 2.0? In that case, could you give an indication of when 2.1 will be supported?

**Comment by mrwyattii** [comment]
Hi @mdhont we use torch 2.1.0 in several of our CI workflows and DeepSpeed _should_ be compatible. With the release of 2.1.0 a few weeks ago, we saw a couple things break and had to make some changes. Can you confirm you are on the latest release of DeepSpeed and also share any steps to reproduce this error? Thank you

**Comment by phalexo** [comment]
Looks like your environment is still looking at 3.8. It is looking at the modules you installed for 3.8.
