### ISSUE TITLE
[BUG] Rocblas include

### ISSUE THREAD

**Issue by IMbackK** [microsoft/DeepSpeed#4551]
https://github.com/microsoft/DeepSpeed/blob/4fc181b01077521ba42379013ce91a1c294e5d8e/csrc/includes/cublas_wrappers.h#L30

same issue as #4507 just a different file

This one was discovered running pytest on mi50 in order to track down a gpu pagefault

**Comment by IMbackK** [comment]
That is incorrect #4538 dose not fix this one, as a unit test compiles a translation unit that includes this header, but not gemm_test.h thus causing the compile of that translation unit to fail

**Comment by loadams** [comment]
@IMbackK - can you please try building with the linked PR - the fix is the same but to another file as you mentioned?
