### ISSUE TITLE
[BUG] zero3 offload has suboptimal throughput because gradient overflow check is on CPU

### ISSUE THREAD

**Issue by yundai424** [microsoft/DeepSpeed#4561]
**Describe the bug**

We observe suboptimal performance in terms of throughput when using zero3 offload and we identify the bottleneck being the overflow check on the gradient partition flat buffer [here](https://github.com/microsoft/DeepSpeed/blob/869629c2108f31e25803cd9e66c7ec76db3e5923/deepspeed/runtime/zero/stage3.py#L2020). When using CPU offload, the buffer is placed [on CPU](https://github.com/microsoft/DeepSpeed/blob/869629c2108f31e25803cd9e66c7ec76db3e5923/deepspeed/runtime/zero/stage3.py#L474) so we'll spend a lot of time performing the `torch.isinf` and `torch.isnan` (observed >10s per op for llama2-70b on bf16)  

**To Reproduce**
train with any open source model / dataset with zero3 offload

**Expected behavior**
the computation should take place on GPU

**ds_report output**
```
[jobuser@f0c766992c6874303b22-n0-0-master-0 ~]$ ds_report
[2023-10-23 23:33:10,153] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/jobuser/.local/lib/python3.10/site-packages/torch']
torch version .................... 2.0.0+cu117
deepspeed install path ........... ['/home/jobuser/.local/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.11.1, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
shared memory (/dev/shm) size .... 1007.71 GB
[jobuser@f0c766992c6874303b22-n0-0-master-0 ~]$
```

**Screenshots**
![Screenshot 2023-08-14 at 2 44 56 PM](https://github.com/microsoft/DeepSpeed/assets/43726198/ae869242-84b9-445b-8500-75e343919bd0)

**System info (please complete the following information):**
 - OS: RHEL 7.9
 - GPU count and types: 1 machine with x8 A100s
 - Interconnects (if applicable): 100Gbps nvswitch
 - Python version: 3.10

**Launcher context**
using `torchrun`

**Comment by npz7yyk** [comment]
Yes, it is better to check overflow in distributed manner in _partition_gradient() when it is gradient_accumulation_boundary. Every time computing the overflow of the grad_buffer and OR the result to the tracker.

**Comment by npz7yyk** [comment]
By the way, I am using Nsight to visualize the resource usage but the experience is not so good. Can you share the method of obtaining that timeline graph?

**Comment by gongjingcs** [comment]
We have also encountered the same problem. It takes too long to check the overflow on the CPU. Do you have any optimization methods?

**Comment by yundai424** [comment]
think it's partially solved in https://github.com/microsoft/DeepSpeed/pull/4512 at least for bf16 and fp32
