### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by FurkanGozukara** [microsoft/DeepSpeed#4564]
It is 2023 and it is sad that still no Triton for Windows

**Comment by loadams** [comment]
Hi @FurkanGozukara - agreed, unfortunately this is out of our control.  There are a few open requests on the triton repository, with some folks claiming workarounds/ways to build on Windows.  You may want to try some of those, but there are none that are officially supported to my knowledge.  

Closing this for now as unrelated to DeepSpeed and we are unable to assist on this.

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara - agreed, unfortunately this is out of our control. There are a few open requests on the triton repository, with some folks claiming workarounds/ways to build on Windows. You may want to try some of those, but there are none that are officially supported to my knowledge.
> 
> Closing this for now as unrelated to DeepSpeed and we are unable to assist on this.

do you know the latest fork that claims working on windows? i would like to try

**Comment by loadams** [comment]
This is the one that I was aware of: https://github.com/openai/triton/pull/2465/files

But it was linked [here](https://github.com/openai/triton/issues/1640), on a thread that it appears you already commented on, so they may not have any new progress.
