### ISSUE TITLE
The best speed performance

### ISSUE THREAD

**Issue by zhoumengbo** [microsoft/DeepSpeed#4575]
Which framework in DeepSpeed has the best speed performance, and is there anything faster than DeepSpeed?

**Comment by loadams** [comment]
@zhoumengbo - this depends on a lot of factors, are you asking about training or inference?  Available hardware?  Model size?

Overall, I'd recommend reading more about deepspeed [here](https://www.deepspeed.ai/), to get a sense of the features provided (Zero, Inference, DeepSpeed-Chat, etc) and what might apply to your situation.
