### ISSUE TITLE
[BUG]Process deadlock occurs during distributed training

### ISSUE THREAD

**Issue by gavin-gqzhang** [microsoft/DeepSpeed#4579]
When using distributed training, if the number of data sets on different processes is different, the training process will fall into a deadlock state, and the GPU utilization rate will be 100% and will not proceed to the next step. Is there a Join method like pytorch to solve the problem of process deadlock caused by unbalanced data sets?

**Comment by loadams** [comment]
Hi @Gavin-Zhang-Code - do you have a small repro you can share with us?

**Comment by Gavin-Zhang-Code** [comment]
Hello, thank you for your reply. I'm sorry that I can only describe the problem through language at present. In my training process, the amount of data for each batch is different on different cuda. As a result, some processes complete the forward process ahead of schedule, while some processes continue to calculate. This leads to the problem of waiting between processes and deadlocks. Pytorch of torch, distributed algorithms. Join, join can solve the problem of process is out of sync, so I want to ask, deepspeed solution to this problem?
Finally, thank you very much for your reply, I wish you a happy life!

**Comment by loadams** [comment]
Hi @gavin-gqzhang - I'm not quite sure what you mean, and we've yet to find anything that could be causing this.  

Could you test with the latest deepspeed and let us know if you're still hitting this?  Otherwise we can close the issue, thanks for your help in letting us track down any bugs!

**Comment by loadams** [comment]
Closing as stale for now, please let us know if you are still hitting this.
