### ISSUE TITLE
Where to find the results when setting "profile": true in activation_checkpointing config?

### ISSUE THREAD

**Issue by tangjiasheng** [microsoft/DeepSpeed#4600]
Like the title. Can anyone point out this? Thanks a lot!

**Comment by loadams** [comment]
It looks like these are printed here:

https://github.com/microsoft/DeepSpeed/blob/de96e18ad5c6c58b21b906249296ca45ff46a24f/deepspeed/runtime/activation_checkpointing/checkpointing.py#L769C1-L777C79

This looks like they should be logged to the main console output, do you see it there?

**Comment by tangjiasheng** [comment]
> It looks like these are printed here:
> 
> https://github.com/microsoft/DeepSpeed/blob/de96e18ad5c6c58b21b906249296ca45ff46a24f/deepspeed/runtime/activation_checkpointing/checkpointing.py#L769C1-L777C79
> 
> This looks like they should be logged to the main console output, do you see it there?

Thanks, found it on such a messy screen😂.
