### ISSUE TITLE
[Build] nvcc install issue

### ISSUE THREAD

**Issue by caterpillarpants** [microsoft/DeepSpeed#4614]
**Is your feature request related to a problem? Please describe.**
Usually, I have trouble installing.

**Describe the solution you'd like**
I want to say "pip install deepspeed" and it installed regardless of configuration and works perfectly, as if by magic.
alternatively, I would like a list of requirements placed in a conspicuous place to compile this project.

**Describe alternatives you've considered**
I'm thinking the nvcc or pytorch version is wrong.

**Additional context**
here is the whole error message. I'm trying to install to work with text-generation webui, nvcc 11.5.119, pytorch 2.1.0+cu121.

pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.12.0.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      [2023-11-03 20:46:01,220] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      [2023-11-03 20:46:02,248] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-lwqkuh2k/deepspeed_bdb8978ed1ae4b77a62277851ae7de45/setup.py", line 100, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-lwqkuh2k/deepspeed_bdb8978ed1ae4b77a62277851ae7de45/op_builder/builder.py", line 43, in installed_cuda_version
          output = subprocess.check_output([cuda_home + "/bin/nvcc", "-V"], universal_newlines=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ana/text-generation-webui-main/installer_files/env/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ana/text-generation-webui-main/installer_files/env/lib/python3.11/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ana/text-generation-webui-main/installer_files/env/lib/python3.11/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/ana/text-generation-webui-main/installer_files/env/lib/python3.11/subprocess.py", line 1950, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/home/ana/text-generation-webui-main/installer_files/env/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Here is my complete...
pip list
Package                   Version
------------------------- ------------
absl-py                   2.0.0
accelerate                0.24.1
aiofiles                  23.2.1
aiohttp                   3.8.6
aiosignal                 1.3.1
altair                    5.1.2
antlr4-python3-runtime    4.9.3
anyio                     3.7.1
appdirs                   1.4.4
asttokens                 2.4.0
async-timeout             4.0.3
attributedict             0.3.0
attrs                     23.1.0
auto-gptq                 0.4.2+cu121
autoawq                   0.1.4
backcall                  0.2.0
backoff                   2.2.1
beautifulsoup4            4.12.2
bitsandbytes              0.41.1
blessings                 1.7
blinker                   1.6.3
cachetools                5.3.2
certifi                   2022.12.7
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        2.1.1
chromadb                  0.3.18
click                     8.1.7
clickhouse-connect        0.6.18
codecov                   2.1.13
colorama                  0.4.6
coloredlogs               15.0.1
colour-runner             0.1.1
contourpy                 1.1.1
coverage                  7.3.2
cramjam                   2.7.0
ctransformers             0.2.27+cu121
cycler                    0.12.1
DataProperty              1.0.1
datasets                  2.14.6
decorator                 5.1.1
deep-translator           1.9.2
deepdiff                  6.6.1
dill                      0.3.7
diskcache                 5.6.3
distlib                   0.3.7
docker-pycreds            0.4.0
docopt                    0.6.2
duckdb                    0.9.1
einops                    0.7.0
elevenlabs                0.2.24
executing                 2.0.0
exllama                   0.0.18+cu121
exllamav2                 0.0.6+cu121
fastapi                   0.104.0
fastparquet               2023.10.0
ffmpeg                    1.4
ffmpy                     0.3.1
filelock                  3.12.4
flash-attn                2.3.2
Flask                     3.0.0
flask-cloudflared         0.0.12
fonttools                 4.43.1
frozenlist                1.4.0
fsspec                    2023.10.0
gitdb                     4.0.11
GitPython                 3.1.40
google-auth               2.23.3
google-auth-oauthlib      1.1.0
gptq-for-llama            0.1.1+cu121
gradio                    3.50.2
gradio_client             0.6.1
grpcio                    1.59.0
h11                       0.14.0
hjson                     3.1.0
hnswlib                   0.7.0
httpcore                  0.18.0
httptools                 0.6.1
httpx                     0.25.0
huggingface-hub           0.17.3
humanfriendly             10.0
idna                      3.4
importlib-resources       6.1.0
inspecta                  0.1.3
ipython                   8.16.1
itsdangerous              2.1.2
jedi                      0.19.1
Jinja2                    3.1.2
joblib                    1.3.2
jsonlines                 4.0.0
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
kiwisolver                1.4.5
llama_cpp_python          0.2.11
llama_cpp_python_cuda     0.2.11+cu121
llvmlite                  0.41.1
lm-eval                   0.3.0
lxml                      4.9.3
lz4                       4.3.2
Markdown                  3.5.1
MarkupSafe                2.1.2
matplotlib                3.8.0
matplotlib-inline         0.1.6
mbstrdecoder              1.1.3
monotonic                 1.6
more-itertools            10.1.0
mpmath                    1.3.0
multidict                 6.0.4
multiprocess              0.70.15
networkx                  3.0
ngrok                     0.12.0
ninja                     1.11.1.1
nltk                      3.8.1
num2words                 0.5.13
numba                     0.58.1
numexpr                   2.8.7
numpy                     1.24.4
oauthlib                  3.2.2
omegaconf                 2.3.0
openai                    0.28.1
openai-whisper            20230918
optimum                   1.13.1
ordered-set               4.1.0
orjson                    3.9.9
packaging                 23.2
pandas                    2.0.3
parso                     0.8.3
pathtools                 0.1.2
pathvalidate              3.2.0
peft                      0.5.0
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    10.1.0
pip                       23.3
platformdirs              3.11.0
pluggy                    1.3.0
portalocker               2.8.2
posthog                   2.4.2
prompt-toolkit            3.0.39
protobuf                  4.23.4
psutil                    5.9.6
ptyprocess                0.7.0
pure-eval                 0.2.2
py-cpuinfo                9.0.0
pyarrow                   13.0.0
pyasn1                    0.5.0
pyasn1-modules            0.3.0
pybind11                  2.11.1
pycountry                 22.3.5
pycparser                 2.21
pydantic                  1.10.13
pydub                     0.25.1
Pygments                  2.16.1
pynvml                    11.5.0
pyparsing                 3.1.1
pyproject-api             1.6.1
pytablewriter             1.2.0
python-dateutil           2.8.2
python-dotenv             1.0.0
python-multipart          0.0.6
pytz                      2023.3.post1
PyYAML                    6.0.1
pyzmq                     25.1.1
referencing               0.30.2
regex                     2023.10.3
requests                  2.31.0
requests-oauthlib         1.3.1
rootpath                  0.1.1
rouge                     1.0.1
rouge-score               0.1.2
rpds-py                   0.10.6
rsa                       4.9
sacrebleu                 1.5.0
safetensors               0.4.0
scikit-learn              1.3.2
scipy                     1.11.3
semantic-version          2.10.0
sentence-transformers     2.2.2
sentencepiece             0.1.99
sentry-sdk                1.32.0
setproctitle              1.3.3
setuptools                68.0.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
soundfile                 0.12.1
soupsieve                 2.5
SpeechRecognition         3.10.0
sqlitedict                2.1.0
stack-data                0.6.3
starlette                 0.27.0
sympy                     1.12
tabledata                 1.3.3
tabulate                  0.9.0
tcolorpy                  0.1.4
tensorboard               2.15.0
tensorboard-data-server   0.7.2
termcolor                 2.3.0
texttable                 1.7.0
threadpoolctl             3.2.0
tiktoken                  0.3.3
tokenizers                0.14.1
toml                      0.10.2
toolz                     0.12.0
torch                     2.1.0+cu121
torch-grammar             0.3.3
torchaudio                2.1.0+cu121
torchvision               0.16.0+cu121
tox                       4.11.3
tqdm                      4.66.1
tqdm-multiprocess         0.0.11
traitlets                 5.12.0
transformers              4.34.1
triton                    2.1.0
typepy                    1.3.2
typing_extensions         4.8.0
tzdata                    2023.3
urllib3                   1.26.13
uvicorn                   0.23.2
uvloop                    0.19.0
virtualenv                20.24.6
wandb                     0.15.12
watchfiles                0.21.0
wcwidth                   0.2.8
websockets                11.0.2
Werkzeug                  3.0.1
wheel                     0.41.2
xxhash                    3.4.1
yarl                      1.9.2
zstandard                 0.21.0

**Comment by loadams** [comment]
Hi @caterpillarpants - DeepSpeed is meant to work with a [wide variety of CUDA/ROCm/PyTorch versions](https://github.com/microsoft/DeepSpeed#requirements) and will print an error if an invalid combination is encountered.  The full list of requirements that can be installed via pip are listed in the requirements folder, but not everything can be installed that way.

Your error appears to be this:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/ana/text-generation-webui-main/installer_files/env/bin/nvcc'
[end of output]
```

Which means it is possible you don't have nvcc installed or set to that path.  Can you run the following: `nvcc --version` and `which nvcc` to see where your nvcc installation is located?

**Comment by caterpillarpants** [comment]
Thank you for helping! I'm trying to train with low VRAM and deepspeed or 4bit seem to be my only options.

nvcc --version
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0`

which nvcc
`/usr/bin/nvcc`

So I'm pretty sure that nvcc is in the path, because I can type nvcc from anywhere, but the error seems to complain about it.

**Comment by loadams** [comment]
Does anything exist at this path?

``` 
/home/ana/text-generation-webui-main/installer_files/env/bin/nvcc
```

I'm trying to see what might be looking for nvcc at this location, perhaps a conda env?

**Comment by caterpillarpants** [comment]
To answer your question, there is no nvcc at /home/ana/text-generation-webui-main/installer_files/env/bin/ although that path does exist.

Some progress...

Thanks to you, loadams, I discovered that nvcc was located at /usr/bin/nvcc
the error was looking for nvcc in /home/ana/text-generation-webui-main/installer_files/env/bin/nvcc

so I did:
`export PATH=/usr/bin:$PATH`
which puts nvcc in the path. This is a little confusing to me as I seem to be able to use nvcc as if it were in the path, except when compiling.... so I don't get it completely, but this allowed deepspeed to compile. Of course, upon using it I now I have a different error to investigate, but this particular issue appears solved.

Should I mark solve or do you want to continue troubleshooting the new error?
`NameError: name 'deepspeed' is not defined`
possibly this is a user error as I am still experimenting with the settings of the text-generation-webui program to load with deepspeed. If I remember correctly, 4bit doesn't work and possibly 8bit. I can't quite remember, but I feel deja vu in the air.

**Comment by loadams** [comment]
Hi @caterpillarpants - lets close this issue since this is resolved, and that way if other folks see this they can get the fix for their issue, and then if you could open a new issue that would be great.
