### ISSUE TITLE
[REQUEST] Has DeepSpeed used PyTorch 2.1?

### ISSUE THREAD

**Issue by zhoumengbo** [microsoft/DeepSpeed#4616]
I would like to know in which modules DeepSpeed has utilized the latest PyTorch 2.1. Has it incorporated features related to PyTorch 2.1, and has there been any enhancement in performance?

**Comment by loadams** [comment]
Hi @zhoumengbo - some of our CI tests run with PyTorch 2.1/PyTorch latest, so DeepSpeed builds with and support this.  Performance will depend on your use case, could you let us know more about what you are specifically looking for?

**Comment by advancingsweet** [comment]
when running python setup.py bdist_wheel, I'm facing the error :ModuleNotFoundError: No module named 'torch' ,  but I had installed the import.  Could you please help me deal with it ?

**Comment by loadams** [comment]
@advancingsweet 

Can you please run the following commands to confirm you have torch installed?

```
         python -c "import torch; print('torch:', torch.__version__, torch)"
          python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
```

**Comment by loadams** [comment]
Hi @advancingsweet - going to go ahead and close this for now.  Please reply or re-open if needed.  Thanks!
