### ISSUE TITLE
[BUG] Home Page UI Improvement

### ISSUE THREAD

**Issue by Roshan-Singh-07** [microsoft/DeepSpeed#4630]
**Describe the bug**
When I first visited the website provided in the repository link, I encountered a user experience issue. The content on the home page is not displayed properly, requiring me to scroll horizontally to see the content on the left and right sides. This makes for a suboptimal user experience, as it's expected that all content should be visible within the same viewport without the need for horizontal scrolling.

1. Navigate to the home page of the website using the provided link. https://www.deepspeed.ai/
2. Observe the need to scroll horizontally to see the content on the left and right sides of the page.

**Expected behavior**
The expected behavior is that the content should be fully visible within the viewport, ensuring a smooth and comfortable user experience.

**Screenshots**
![Screenshot 2023-11-06 160618](https://github.com/microsoft/DeepSpeed/assets/110438835/d3b2fbc7-b583-41db-8367-707845911216)

![Screenshot 2023-11-06 160653](https://github.com/microsoft/DeepSpeed/assets/110438835/84783425-9a7a-4d53-b572-ae74f34d83fa)

**Comment by mrwyattii** [comment]
Hi @Roshan-Singh-07 this is an unusual bug. Could you share a bit of information on which browser and operating system you observed this?

**Comment by Roshan-Singh-07** [comment]
**Browser:**
- Google Chrome
- Version: 119.0.6045.105 (Official Build) (64-bit)

**Operating System:**
- Windows 11 Home Single Language
- Version: 23H2

**Comment by Roshan-Singh-07** [comment]
> Hi @Roshan-Singh-07 this is an unusual bug. Could you share a bit of information on which browser and operating system you observed this?

**Browser:**
- Google Chrome
- Version: 119.0.6045.105 (Official Build) (64-bit)

**Operating System:**
- Windows 11 Home Single Language
- Version: 23H2

**Comment by loadams** [comment]
Hi @Roshan-Singh-07 - we should have updated this now, could you confirm if you are still hitting this?
