### ISSUE TITLE
missing ssh_port if master_addr and master_port not set

### ISSUE THREAD

**Issue by Alienfeel** [microsoft/DeepSpeed#4649]
https://github.com/microsoft/DeepSpeed/blob/00df0c1998ab84aaa7ceaae2b9e04857923c7fa2/deepspeed/launcher/runner.py#L450C1-L451C1

when in K8S environment, this check would incur error like:

subprocess.CalledProcessError: Command '['ssh deepspeed-helloworld-worker-0 hostname -I']' returned non-zero exit status 255.

**Comment by loadams** [comment]
@Alienfeel - I believe error 255 is an [error with the ssh connection](https://docs.platform.sh/development/ssh/troubleshoot-ssh.html), rather than the command it is forming is bad.  Or could you explain why you need this change?

**Comment by Alienfeel** [comment]
> @Alienfeel - I believe error 255 is an [error with the ssh connection](https://docs.platform.sh/development/ssh/troubleshoot-ssh.html), rather than the command it is forming is bad. Or could you explain why you need this change?

here's my environment:

1. K8S clusters provided by clouding computing company, e.g.  alibabacloud.com
2. submit deepspeedjob to k8s clusters, using ``arena``(https://github.com/kubeflow/arena), like this: https://www.alibabacloud.com/blog/how-does-deepspeed-%2B-kubernetes-easily-implement-large-scale-distributed-training_600402
3. arena automatically fills the  k8s POD "hostnames GPU-slots" into /job/hostfile, which is provided to deepspeed; and furthermore, we can't provide the --master-addr / --master-port in this way, and **runner.py** will automatically treat the first line in /job/hostfile as the master, and try to check the connection is ok or not
4. in HPC computing settings, it's suggested that, POD using hostNetwork, and, ssh port in POD(e.g. 2222) should be different with host ssh port(e.g. 22).
5. and in deepspeed command line, we should provide ``--ssh_port 2222 `` in the POD

so, when runner.py checks the connection of the ``master``, it fails like the example provided, because the POD ssh_port settings.

**Comment by mrwyattii** [comment]
#4650 merged. Thank you for the fix!
