### ISSUE TITLE
Asynchronous Data Loading

### ISSUE THREAD

**Issue by david-macleod** [microsoft/DeepSpeed#466]
Hi

I was just looking in the DeepSpeed repo for the data prefetching code referenced below, but was unable to find it. Is it available?

https://github.com/microsoft/DeepSpeed/blob/29c5fe26112f417c25955baab8e9dc7d7f33c5e4/docs/_posts/2020-05-28-fastest-bert-training.md#overlapping-io-with-computation-through-asynchronous-prefetching-queue

Many thanks
David

**Comment by tjruwase** [comment]
This [optimization ](https://github.com/microsoft/DeepSpeedExamples/blob/master/bing_bert/data_worker.py)was implemented in the [BingBert example model](https://github.com/microsoft/DeepSpeedExamples/tree/master/bing_bert).
