### ISSUE TITLE
ModuleNotFoundError: No module named 'dskernels'

### ISSUE THREAD

**Issue by shuaidan0412** [microsoft/DeepSpeed#4669]
1. env:
win11 and win10
conda 
pytorch 

2. step
set DS_BUILD_AIO=0   
set DS_BUILD_SPARSE_ATTN=0
python setup.py bdist_wheel

error: 

 [WARNING]  cpu_adagrad requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
 [WARNING]  cpu_adagrad cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
The system cannot find the file specified.
 [WARNING]  cpu_lion requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_lion attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
The system cannot find the file specified.
 [WARNING]  cpu_lion requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_lion attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
 [WARNING]  cpu_lion cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
Traceback (most recent call last):
  File "setup.py", line 192, in <module>
    ext_modules.append(builder.builder())
  File "E:\qzd-idea-code\github\DeepSpeed-master\op_builder\builder.py", line 627, in builder
    extra_link_args=self.strip_empty_entries(self.extra_ldflags()))
  File "E:\qzd-idea-code\github\DeepSpeed-master\op_builder\inference_cutlass_builder.py", line 71, in extra_ldflags
    import dskernels
ModuleNotFoundError: No module named 'dskernels'

**Comment by loadams** [comment]
Hi @shuaidan0412 - are you trying to use the DS Kernels features/those ops released in DeepSpeed-FastGen?  If not, you should be able to simply not use those ops, disabling them as listed here:

```
DS_BUILD_CUTLASS_OPS=0 DS_BUILD_RAGGED_DEVICE_OPS=0 DS_BUILD_EVOFORMER_ATTN=0 
```

If you are trying to build with them, the requirements file [here](https://github.com/microsoft/DeepSpeed/blob/6ea44d02c674393c524ada811ea376c55438a913/requirements/requirements-dev.txt#L4)lists the package you need that will help set that.
