### ISSUE TITLE
[REQUEST] Does deepspeed support xla/TPU?

### ISSUE THREAD

**Issue by bmeoaountiful** [microsoft/DeepSpeed#4676]
I could not found any answer for training a PyTorch model using XLA. Does deepspeed support xla/TPU?

**Comment by loadams** [comment]
Hi @bmeoaountiful - no, we do not support TPUs, though as was true from [this comment](https://github.com/microsoft/DeepSpeed/issues/210), we welcome outside contributions to add new features.

**Comment by radna0** [comment]
Any updates on this? @loadams

**Comment by radna0** [comment]
Got it @loadams , I will open Feature Requests on both the Pytorch XLA and DeepSpeed repo, to integrate XLA as a backend for Deepspeed.
