### ISSUE TITLE
[REQUEST] inference.v2 HuggingFaceCheckpointEngine add safetensors support.

### ISSUE THREAD

**Issue by is** [microsoft/DeepSpeed#4680]
**Is your feature request related to a problem? Please describe.**
The new version of HF Transformers supports weight files in safetensors format, and more and more new models also use the safetensors format.

**Describe the solution you'd like**
The new version of HF Transformers supports weight files in safetensors format, and more and more new models also use the safetensors format.

**Comment by mrwyattii** [comment]
We currently have a PR in the pipeline to support the safetensor format: #4659

**Comment by mrwyattii** [comment]
PR has been merged, please use `deepspeed>=0.12.4` and `deepspeed-mii>=0.1.2`. Closing.
