### ISSUE TITLE
[Question] FastGen Benchmarks

### ISSUE THREAD

**Issue by jeromeku** [microsoft/DeepSpeed#4691]
Is the code for the benchmarking studies from the [`FastGen` blogpost](https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-fastgen) available in this repo (or the DS MII repo)?

**Comment by twaka** [comment]
I found it here https://github.com/microsoft/DeepSpeedExamples/tree/master/benchmarks/inference/mii

**Comment by jeromeku** [comment]
@twaka - Thanks!
