### ISSUE TITLE
After wrapped by DeepSpeedEngine, most of my model's weights are empty using named_parameters()

### ISSUE THREAD

**Issue by zyh3826** [microsoft/DeepSpeed#4720]
**Describe the bug**

I think is not a bug, I didn't find the correct way.
I have an LLM and trained it using transformers with DeepSpeed, I found that After being wrapped by `DeepSpeedEngine`, most of my model's weights are empty using `named_parameters()`, see figure below:
![image](https://github.com/microsoft/DeepSpeed/assets/31238754/36056bff-e466-4d6d-8d5f-f38ddf6031bf)

 Could you tell me what is the correct way to get all model `{name: param}` dict after being wrapped by `DeepSpeedEngine`, thanks a lot

**Comment by mklf** [comment]
it seems that you are using ds zero3, you can try this code to collect all the aprams of model:
```python
 def collect_state_dict(self, model):

      def _z3_params_to_fetch(param_list):
          return [p for p in param_list if hasattr(p, "ds_id") and p.ds_status == ZeroParamStatus.NOT_AVAILABLE]

      state_dict = OrderedDict()
      for k, v in model.named_parameters():
          if hasattr(v, "ds_id"):
              with deepspeed.zero.GatheredParameters(_z3_params_to_fetch([v]), enabled=self.stage == 3):
                  v_p = v.data.cpu()
          else:
              v_p = v.cpu()

          if dist_env.rank == 0:
              state_dict[k] = v_p

      return state_dict
```

**Comment by zyh3826** [comment]
> it seems that you are using ds zero3, you can try this code to collect all the aprams of model:
> 
> ```python
>  def collect_state_dict(self, model):
> 
>       def _z3_params_to_fetch(param_list):
>           return [p for p in param_list if hasattr(p, "ds_id") and p.ds_status == ZeroParamStatus.NOT_AVAILABLE]
> 
>       state_dict = OrderedDict()
>       for k, v in model.named_parameters():
>           if hasattr(v, "ds_id"):
>               with deepspeed.zero.GatheredParameters(_z3_params_to_fetch([v]), enabled=self.stage == 3):
>                   v_p = v.data.cpu()
>           else:
>               v_p = v.cpu()
> 
>           if dist_env.rank == 0:
>               state_dict[k] = v_p
> 
>       return state_dict
> ```
Hi @mklf thanks for your reply, could you tell me what is `dist_env`?

**Comment by mklf** [comment]
you can replace `dist_env.rank` with `torch.distributed.get_rank()`

**Comment by tjruwase** [comment]
@zyh3826, for zero stage 3, you can use these APIs to access model state: https://deepspeed.readthedocs.io/en/latest/zero3.html#debugging
