### ISSUE TITLE
Update dockerfile to use more recent version of pytorch

### ISSUE THREAD

**Issue by jackshi0912** [microsoft/DeepSpeed#473]
Right now deepspeed/deepspeed:latest uses pytorch version 1.2.0 which is fairly old. Is there a validation process for upgrading the pytorch version to something more recent? Thanks!

**Comment by Santosh-Gupta** [comment]
For me it's showing 1.6.0

**Comment by jackshi0912** [comment]
![Screenshot from 2020-10-15 23-06-23](https://user-images.githubusercontent.com/10685803/96219167-171a0380-0f3b-11eb-860c-fb933f87b925.png)
This is the master branch. The dockerfile specifies that PYTORCH_VERSION=1.2.0

Same here in docker hub for tag deepspeed/deepspeed:latest, PYTORCH_VERSION=1.2.0
https://hub.docker.com/layers/deepspeed/deepspeed/latest/images/sha256-2dcca3af7a9c2156bb2f282a2d0b1a4dbf42adca2a8955356889d842a842a2f8?context=explore

**Comment by jackshi0912** [comment]
ping

**Comment by loadams** [comment]
This has been updated now - please check out the latest dockerfile in our repo.
