### ISSUE TITLE
MiCS training is broken in v0.12.3 [BUG]

### ISSUE THREAD

**Issue by rich-junwang** [microsoft/DeepSpeed#4731]
**Describe the bug**
During training I saw the following error 
```
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage3.py", line 253, in __init__
    self.model_parallel_group = mpu.get_model_parallel_group()
AttributeError: 'float' object has no attribute 'get_model_parallel_group'
```
This is a bug introduced by the latest change of adding `offload_ratio` parameter in optimizer class. I can create a PR to fix it if needed. Thanks.

**Comment by tongjizzy** [comment]
@rich-junwang I have the same error!!  Please tell me how to fix this bug?

**Comment by rich-junwang** [comment]
@tongjizzy just add that `offload_ratio` to the mics optimizer class signature.

**Comment by GuanhuaWang** [comment]
Hi @rich-junwang & @tongjizzy , thx for reporting this issue.

I just did a quick fix PR https://github.com/microsoft/DeepSpeed/pull/4749

**Comment by GuanhuaWang** [comment]
PR https://github.com/microsoft/DeepSpeed/pull/4749 merged into master branch. close this issue now.
