### ISSUE TITLE
Why can't deepspeed V2 use the original model structure?

### ISSUE THREAD

**Issue by JiesongMa** [microsoft/DeepSpeed#4744]

**Comment by loadams** [comment]
@JiesongMa - can you elaborate more on the question?

**Comment by JiesongMa** [comment]
When V2 adapts to the llama model, it writes a new method llama_v2_model.py for inference. Why can't it use llama's own py file? Is it simply because the input types are inconsistent?

**Comment by mrwyattii** [comment]
Hi @JiesongMa I'm not sure I entirely understand your question. But I will try to clarify: 

In the original DeepSpeed-Inference, we would inject layers / kernels into a huggingface model that was passed in by the user to `deepspeed.init_inference`. This was sometimes a difficult thing to maintain and expand. From this, we decided to have DeepSpeed "own" the model. We still use the HuggingFace hosted weights and model architectures, but we represent it in our own code (e.g., `Llama2InferenceModel` in the `llama_v2_model.py` file). This provides us a lot more flexibility and a more robust model to apply our custom kernels to.
