### ISSUE TITLE
DeepSpeed CI failures in Transformers with the latest version 0.12.4 but works with 0.12.3

### ISSUE THREAD

**Issue by pacman100** [microsoft/DeepSpeed#4795]
DeepSpeed integration CI test suites is failing with ~80+ tests being impacted. https://github.com/huggingface/transformers/actions/runs/7155087776/job/19483398901

It is because the runner is changing the below command:

> stdout: [2023-12-11 14:03:02,193] [INFO] [runner.py:570:main] cmd = /raid/sourab/miniconda3/envs/hf/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=10999 --enable_each_rank_log=None /raid/sourab/transformers/examples/pytorch/translation/run_translation.py --model_name_or_path t5-small --train_file /raid/sourab/transformers/tests/deepspeed/../fixtures/tests_samples/wmt_en_ro/train.json --validation_file /raid/sourab/transformers/tests/deepspeed/../fixtures/tests_samples/wmt_en_ro/val.json --output_dir /tmp/tmpd708_3kl --overwrite_output_dir --max_source_length 32 --max_target_length 32 --val_max_target_length 32 --warmup_steps 8 --predict_with_generate --save_steps 0 --eval_steps 10 --group_by_length --label_smoothing_factor 0.1 --source_lang en --target_lang ro --report_to none --source_prefix "translate English to Romanian: " --fp16 --do_train --num_train_epochs 1 --max_train_samples 16 --per_device_train_batch_size 2 --learning_rate 3e-3 --do_eval --max_eval_samples 16 --per_device_eval_batch_size 2 --deepspeed /raid/sourab/transformers/tests/deepspeed/ds_config_zero2.json

to 

> stdout: [2023-12-11 14:03:02,193] [INFO] [runner.py:570:main] cmd = /raid/sourab/miniconda3/envs/hf/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=10999 --enable_each_rank_log=None /raid/sourab/transformers/examples/pytorch/translation/run_translation.py --model_name_or_path t5-small --train_file /raid/sourab/transformers/tests/deepspeed/../fixtures/tests_samples/wmt_en_ro/train.json --validation_file /raid/sourab/transformers/tests/deepspeed/../fixtures/tests_samples/wmt_en_ro/val.json --output_dir /tmp/tmpd708_3kl --overwrite_output_dir --max_source_length 32 --max_target_length 32 --val_max_target_length 32 --warmup_steps 8 --predict_with_generate --save_steps 0 --eval_steps 10 --group_by_length --label_smoothing_factor 0.1 --source_lang en --target_lang ro --report_to none --source_prefix translate English to Romanian:  --fp16 --do_train --num_train_epochs 1 --max_train_samples 16 --per_device_train_batch_size 2 --learning_rate 3e-3 --do_eval --max_eval_samples 16 --per_device_eval_batch_size 2 --deepspeed /raid/sourab/transformers/tests/deepspeed/ds_config_zero2.json

Notice no `"` around `translate English to Romanian:  `. Becuase of this HF Argument parser fails leading to many tests being impacted.

Maybe the cause: https://github.com/microsoft/DeepSpeed/pull/4660

**Comment by pacman100** [comment]
Reverting the PR https://github.com/microsoft/DeepSpeed/pull/4660 resolves the issue (tested it).

**Comment by loadams** [comment]
Thanks @pacman100 - I've created a PR to revert it [here](https://github.com/microsoft/DeepSpeed/pull/4797).  Will work on getting that merged. 

We also know that our nv-transformers-v100 tests are failing with the latest transformers version, we are working on that as well.
