### ISSUE TITLE
Fix getting started on AzureML link

### ISSUE THREAD

**Issue by johnbradley** [microsoft/DeepSpeed#4821]
I am getting a 404 error when visiting the [AzureML Examples GitHub](https://github.com/Azure/azureml-examples/tree/main/python-sdk/workflows/train/deepspeed) link in the [Getting Started documentation](https://www.deepspeed.ai/getting-started/#installation).
I think this is the problematic markdown:
https://github.com/microsoft/DeepSpeed/blob/7914b195c0a41ed01823ceac469b58407d9de021/docs/_tutorials/getting-started.md?plain=1#L11

Perhaps one of these links is where the documentation should link to:
https://github.com/Azure/azureml-examples/tree/main/best-practices/largescale-deep-learning
https://github.com/Azure/azureml-examples/tree/main/best-practices/largescale-deep-learning/Training

**Comment by johnbradley** [comment]
Or perhaps https://github.com/Azure/azureml-examples/tree/main/cli/jobs/deepspeed is a more appropriate link.

**Comment by mrwyattii** [comment]
Hi @johnbradley, thanks for reporting this. Here is what the link originally pointed to: https://github.com/Azure/azureml-examples/tree/346567801b38012f0cb4d175601073cf4ccfac29/python-sdk/workflows/train/deepspeed

I believe your suggestion for https://github.com/Azure/azureml-examples/tree/main/cli/jobs/deepspeed is the most appropriate place for this link to point now. I've updated that in #4822
