### ISSUE TITLE
[BUG] zero3 offload_optimizer error when set ratio

### ISSUE THREAD

**Issue by ShaoxunZeng** [microsoft/DeepSpeed#4872]
When I enable zero3 offload_optimizer, and set ratio to 0.5, error occurs when initiate optimizer

RuntimeError: expected input to be on cuda

config:
```json
{
  "train_batch_size": 8,
  "gradient_accumulation_steps": 1,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.00015
    }
  },
  "zero_optimization": {
    "stage": 3,
    "offload_param": {
      "device": "cpu"
    },
    "offload_optimizer": {
      "device": "nvme",
      "nvme_path": "/mnt/nvme",
      "ratio": 0.5
    }
  }
}
```

**Comment by Trangle** [comment]
same issue

**Comment by GuanhuaWang** [comment]
Hi thx @ShaoxunZeng & @Trangle  for raising this issue. the config for `offload_optimizer` below is incorrect.

device should be cpu, not nvme, thus no nvme_path needed. also please set pin_memory: True. In short correct `offload_optimizer` config look like this:

```
         "offload_optimizer": {
            "device": "cpu",
            "pin_memory": True,
            "ratio": 0.5
        }
```


> When I enable zero3 offload_optimizer, and set ratio to 0.5, error occurs when initiate optimizer
> 
> RuntimeError: expected input to be on cuda
> 
> config:
> 
> ```json
> {
>   "train_batch_size": 8,
>   "gradient_accumulation_steps": 1,
>   "optimizer": {
>     "type": "Adam",
>     "params": {
>       "lr": 0.00015
>     }
>   },
>   "zero_optimization": {
>     "stage": 3,
>     "offload_param": {
>       "device": "cpu"
>     },
>     "offload_optimizer": {
>       "device": "nvme",
>       "nvme_path": "/mnt/nvme",
>       "ratio": 0.5
>     }
>   }
> }
> ```
