### ISSUE TITLE
Has the default partition algorithm of pipline parallelism been changed? I found training speed becomed a little slower than previous versions

### ISSUE THREAD

**Issue by janelu9** [microsoft/DeepSpeed#4881]
deespeed==0.12.6
I do believe that the distribution of parameters is more reasonable, but why slower the training speed becomed?

**Comment by loadams** [comment]
@janelu9 - which versions are you comparing between?

**Comment by janelu9** [comment]
> @janelu9 - which versions are you comparing between?

deepspeed version between 0.12.4 and 0.12.5 before the partition method was modified and after the zero loss bug was fixed

**Comment by loadams** [comment]
In looking through the code, I don't see any changes to the pipeline parallelism, and the release notes list of PRs doesn't show anything new as of [0.12.5](https://github.com/microsoft/DeepSpeed/releases/tag/v0.12.5).  So I'm not sure what in there could be causing training to be slower.  

Could you enable either the flops profiler or the wall_clock_breakdown and we could see if we can identify where things might be slower?

**Comment by janelu9** [comment]
> In looking through the code, I don't see any changes to the pipeline parallelism, and the release notes list of PRs doesn't show anything new as of [0.12.5](https://github.com/microsoft/DeepSpeed/releases/tag/v0.12.5). So I'm not sure what in there could be causing training to be slower.
> 
> Could you enable either the flops profiler or the wall_clock_breakdown and we could see if we can identify where things might be slower?

@loadams  try this old version that has a faster training

[Uploading deepspeed-0.12.4.zip…]()

**Comment by janelu9** [comment]
> In looking through the code, I don't see any changes to the pipeline parallelism, and the release notes list of PRs doesn't show anything new as of [0.12.5](https://github.com/microsoft/DeepSpeed/releases/tag/v0.12.5). So I'm not sure what in there could be causing training to be slower.
> 
> Could you enable either the flops profiler or the wall_clock_breakdown and we could see if we can identify where things might be slower?

Did you have any ideas？I think the new partition method should be faster than the old

**Comment by loadams** [comment]
Hi @janelu9 - I don't have any ideas, as I agree the newer version should be faster than the old.  I'll try to make time this week to test this out and see if it is slower when I run as well or not.

**Comment by janelu9** [comment]
> Hi @janelu9 - I don't have any ideas, as I agree the newer version should be faster than the old. I'll try to make time this week to test this out and see if it is slower when I run as well or not.

@loadams Maybe it was not caused by the new partitioning method, I found deepspeed>=0.12.5 slower than before, even though the old and new partitioning strategies are the same.

**Comment by janelu9** [comment]
The real reason was found here. https://github.com/microsoft/DeepSpeed/issues/5175

**Comment by inkcherry** [comment]
@janelu9  Thanks for the verification!  I will add a fix soon.
