### ISSUE TITLE
Does pip install deepspeed default to including all build options

### ISSUE THREAD

**Issue by xvanQ** [microsoft/DeepSpeed#4884]
Does pip install deepspeed default to including all build options without configuring environment variables？Or do I have to add AIO_ BUILD_ AIO=1 during installation if I need to use AIO

**Comment by loadams** [comment]
@xvanQ - all you need to install deepspeed is the pip install.  However, if you need other dependencies that are not contained within pip. you will need to install those too (installing the libaio-dev package for example).  

This will not pre-compile the ops, which can be done by adding the environment variables for specific ones as needed.  However, if you just pip install, these will be JIT compiled as needed.  More information on this is [here](https://www.deepspeed.ai/tutorials/advanced-install/#pre-install-deepspeed-ops).

**Comment by loadams** [comment]
Closing this issue as the question should be answered.  @xvanQ - if you still have any questions, please reply/re-open.
