### ISSUE TITLE
[BUG] Does DeepSpeed init_inference allow two engines?

### ISSUE THREAD

**Issue by MinghaoYan** [microsoft/DeepSpeed#4893]
**Describe the bug**
DeepSpeed inference does not work when starting two engines, is this expected? When I comment out model2, this works just fine.

**To Reproduce**
model1 = AutoModelForCausalLM.from_pretrained("yahma/llama-7b-hf", torch_dtype=torch.float16")
model1 = deepspeed.init_inference(
                model1,
                replace_with_kernel_inject=False,
                tp={"tp_size": 2,},
                dtype=torch.float16,
                )

model2= AutoModelForCausalLM.from_pretrained("yahma/llama-13b-hf", torch_dtype=torch.float16")
model2 = deepspeed.init_inference(
                model2,
                replace_with_kernel_inject=False,
                tp={"tp_size": 4,},
                dtype=torch.float16,
                )

model1.generate(random_sequence, max_new_tokens=5) would return a shape error.

**Expected behavior**
Does DeepSpeed inference support two inference engines?

I suspect this is due to different models having different tp_size. Is there a way to run two models on two engines with different tp_size?

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count and types One machine with 4 A100s

 - Python version 3.9

**Comment by mrwyattii** [comment]
Closing due to no response from user. Please reopen if this solution does not work for you.
