### ISSUE TITLE
[BUG] Training hang on when use zero2+cpu offload

### ISSUE THREAD

**Issue by boundles** [microsoft/DeepSpeed#4905]
**Describe the bug**
When I use deepseed zero2+cpu offload to train 14b qwen, it hangs on after some steps, any help would be appriciated.

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**
![image](https://github.com/microsoft/DeepSpeed/assets/3818060/2c2e05d6-3c62-448d-be8f-68afe74514ed)

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by GuanhuaWang** [comment]
Hi @boundles , 

Can you please provide your deepspeed configuration details? thx

**Comment by GuanhuaWang** [comment]
no updates after a week, close it for now, feel free to reopen if needed.
