### ISSUE TITLE
Confused about multi-node training

### ISSUE THREAD

**Issue by Rainbowman0** [microsoft/DeepSpeed#4907]
Hi, I successfully ran the ['cifar10_deepspeed.py' ](https://www.deepspeed.ai/tutorials/cifar-10/) example on a single node (2xNVIDIA 3090). Now I want to run the same program on multi-nodes (2 nodes each have 2 3090s.). I refer to the example [here ](https://nlp.stanford.edu/mistral/tutorials/deepspeed.html)to run my program.

my hostfile:
```bash
# 192.168.3.100 & 192.168.3.101 are LAN IP address
192.168.3.100 slots=2
192.168.3.101 slots=2
```

then I ran the command:
```bash
deepspeed --num_gpus 2 --num_nodes 2 --master_addr 192.168.3.100 --hostfile hostfile cifar10_deepspeed.py --deepspeed_config ds_config.json
```

I met the error:

```bash
[2024-01-06 11:41:34,489] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/root/anaconda3/envs/DS/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 437, in main
    subprocess.check_call(ssh_check_cmd, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, shell=True)
  File "/root/anaconda3/envs/DS/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -o PasswordAuthentication=no 192.168.3.100 hostname' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/DS/bin/deepspeed", line 6, in <module>
    main()
  File "/root/anaconda3/envs/DS/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 439, in main
    raise RuntimeError(
RuntimeError: Using hostfile at hostfile but host=192.168.3.100 was not reachable via ssh. If you are running with a single node please remove hostfile or setup passwordless ssh.
```
Do you have any suggestions? :)

In addition, I'm new to deepspeed and confused about multi-node training:
1.  Can I use the LAN IP in the hostfile? (If not, the WAN IP of these nodes are the same but the ports are different, how should I write the hostfile?)
2. I haven’t found a deepspeed multi-node training tutorial suitable for novices. Do you have any recommendations? 

Thank you so much!!

**Comment by tjruwase** [comment]
@Rainbowman0, try https://www.deepspeed.ai/getting-started/#resource-configuration-multi-node

**Comment by Rainbowman0** [comment]
> @Rainbowman0, try https://www.deepspeed.ai/getting-started/#resource-configuration-multi-node

Thanks Reply! I also referred to this tutorial, but I feel that it ignores a lot of details and is not suitable for novice users. It also doesn't answer my current query. :)

**Comment by tjruwase** [comment]
@Rainbowman0, are you able to do passwordless ssh between the nodes?

**Comment by Rainbowman0** [comment]
> @Rainbowman0, are you able to do passwordless ssh between the nodes?

Yep, 192.168.3.100 can do passwordless ssh with 192.168.3.101. But the error is:
```bash
[2024-01-07 11:21:11,775] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/root/anaconda3/envs/DS/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 437, in main
    subprocess.check_call(ssh_check_cmd, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, shell=True)
  File "/root/anaconda3/envs/DS/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -o PasswordAuthentication=no 192.168.3.100 hostname' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/DS/bin/deepspeed", line 6, in <module>
    main()
  File "/root/anaconda3/envs/DS/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 439, in main
    raise RuntimeError(
RuntimeError: Using hostfile at hostfile but host=192.168.3.100 was not reachable via ssh. If you are running with a single node please remove hostfile or setup passwordless ssh.
```
I don't kown why 192.168.3.100 was not reachable via ssh. I ran the code on 192.168.3.100. :)

**Comment by Rainbowman0** [comment]
> > @Rainbowman0, are you able to do passwordless ssh between the nodes?
> 
> Yep, 192.168.3.100 can do passwordless ssh with 192.168.3.101. But the error is:
> 
> ```shell
> [2024-01-07 11:21:11,775] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/DS/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 437, in main
>     subprocess.check_call(ssh_check_cmd, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, shell=True)
>   File "/root/anaconda3/envs/DS/lib/python3.9/subprocess.py", line 373, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command 'ssh -o PasswordAuthentication=no 192.168.3.100 hostname' returned non-zero exit status 255.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/DS/bin/deepspeed", line 6, in <module>
>     main()
>   File "/root/anaconda3/envs/DS/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 439, in main
>     raise RuntimeError(
> RuntimeError: Using hostfile at hostfile but host=192.168.3.100 was not reachable via ssh. If you are running with a single node please remove hostfile or setup passwordless ssh.
> ```
> 
> I don't kown why 192.168.3.100 was not reachable via ssh. I ran the code on 192.168.3.100. :)

I have solved it by running:
```bash
ssh-copy-id root@192.168.3.100
```
to add public key in the '~/.ssh/authorized_keys', but another  error occurred:
```bash
192.168.3.101: ncclRemoteError: A call failed possibly due to a network error or a remote process exiting prematurely.
```
Do you know how to fix it??

**Comment by Ali2500** [comment]
@Rainbowman0 did you find a soluition for this?

**Comment by shizhediao** [comment]
Same question...

**Comment by deema-A** [comment]
> Solved it by not using root. Instead, use user account.

can you please refer me to some code? thank you

**Comment by shizhediao** [comment]
I followed the instructions here: https://github.com/OptimalScale/LMFlow/blob/main/readme/multi_node.md

**Comment by whcjb** [comment]
> I followed the instructions here: https://github.com/OptimalScale/LMFlow/blob/main/readme/multi_node.md

hello, i followed the instructions, but meet the same error, i use two docker container from two different host (e.g. ip1, ip2), i ran master server in ip1, but it shows that ssh cannot reach ip1, but it is self environment. i am confused, someone can help me

**Comment by GuanhuaWang** [comment]
Hi I also saw similar errors

basically, you need to double check your  `/etc/ssh/sshd_config`, see which port is used for ssh/pdsh, if no port open would cause this failure. Also if you are using non-default port 22. Please add `--ssh_port`  argument with deepspeed launcher. (e.g. `deepspeed -H /code/hostfile --ssh_port 2222 PYTHON_SCRIPT.py`
