### ISSUE TITLE
[REQUEST] Set num_local_io_workers 

### ISSUE THREAD

**Issue by Yangr116** [microsoft/DeepSpeed#4925]
my initialize code:
```
    model_engine, optimizer, train_loader, scheduler = deepspeed.initialize(
        model=model, 
        model_parameters=model.parameters(), 
        training_data=train_dataset,
        collate_fn=collate_fn, 
        config=args.ds_config
    )
```
It can not set ```num_workers``` for the dataloader.

![image](https://github.com/microsoft/DeepSpeed/assets/73805072/a80832cc-b16c-4798-a923-c32b71a98db8)

**Comment by mrwyattii** [comment]
Hi @Yangr116 you should be able to set this value with `train_loader.num_local_io_workers = 0` after your `deepspeed.initialize` call.

**Comment by Yangr116** [comment]
thanks！

Michael Wyatt ***@***.***>于2024年1月27日 周六08:34写道：
