### ISSUE TITLE
[Queston] Deepspeed stage 3 OOM on 7B-model with A100-80GB memory card

### ISSUE THREAD

**Issue by candygocandy** [microsoft/DeepSpeed#4953]
I am trying to run this [example](https://github.com/huggingface/alignment-handbook/blob/main/recipes/zephyr-7b-beta/README.md): which trains a 7B model with a single A100-80GB GPU (https://github.com/huggingface/alignment-handbook/blob/main/scripts/run_dpo.py), but it is giving me OOM error even with gradient accmulation step = 1, train_batch = 1. But it works without deepspeed, am I doing anything wrong?

Full error logs: https://github.com/candygocandy/error/blob/main/Full-error-log

Should I use Deepspeed stage 2? It should work with only 1 GPU as far as I can tell... 

```
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

Command that I ran which gave me OOM: `ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero3.yaml scripts/run_dpo.py recipes/zephyr-7b-beta/dpo/config_full.yaml` (I already change the config to have single GPU and set all the batch size to 1, gradient accumulation step = 1).

**Comment by ShukantPal** [comment]
DeepSpeed ZeRO does not reduce your memory footprint on a single GPU workload. ZeRO works by partitioning model optimizer states, gradients, and parameters _across multiple_ GPUs.

You can try using [ZeRO Offload](https://www.deepspeed.ai/docs/config-json/#optimizer-offloading) to move the memory onto CPU memory to make DeepSpeed work.

**Comment by tjruwase** [comment]
@ShukantPal, thanks for providing the correct answer.
