### ISSUE TITLE
[BUG] ROCM Build DeepSpeed Inference failed

### ISSUE THREAD

**Issue by lhcalibur** [microsoft/DeepSpeed#4989]
**Describe the bug**

**Build with command:**  

DS_BUILD_SPARSE_ATTN=0 DS_BUILD_RAGGED_DEVICE_OPS=0 DS_BUILD_CUTLASS_OPS=0 DS_BUILD_EVOFORMER_ATTN=0 DS_BUILD_OPS=1 python setup.py develop

**Raise:**

In file included from deepspeed/inference/v2/kernels/core_ops/blas_kernels/blas_hip.h:12,
                 from deepspeed/inference/v2/kernels/core_ops/core_ops_hip.cpp:11:
deepspeed/inference/v2/kernels/core_ops/blas_kernels/blas_utils_hip.h:18:10: fatal error: mma.h: No such file or directory
   18 | #include <mma.h>

**System info (please complete the following information):**
 - ROCM 6.0
 - Ubuntu: 22.04
 - Pytorch: 2.3.0.dev20240121+rocm6.0

**Comment by loadams** [comment]
@rraminen and @jithunnair-amd - FYI on this.  I don't believe the inference v2 kernels support AMD yet.

**Comment by loadams** [comment]
Hi @jithunnair-amd - following up if you have any thoughts on this?
