### ISSUE TITLE
[BUG] Deepspeed help parameter typo

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [microsoft/DeepSpeed#4994]
![image](https://github.com/microsoft/DeepSpeed/assets/39079736/01335d38-0c23-4d0d-a46a-082536e73d67)

**Comment by loadams** [comment]
@oushu1zhangxiangxuan1 - this is the correct comment, as mentioned in my comment on your PR, the description of the behavior of --exclude references --include since it is mutually exclusive with it, meaning they cannot be used together.
