### ISSUE TITLE
module 'diffusers.models' has no attribute 'autoencoders'

### ISSUE THREAD

**Issue by mikob** [microsoft/DeepSpeed#5067]
**Describe the bug**
When running `deepspeed.init_inference` for stablediffusion models there is an error (only in deepspeed >= 0.13) 
```
if hasattr(diffusers.models.autoencoders.vae, "AutoencoderKL"):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'diffusers.models' has no attribute 'autoencoders'. Did you mean: 'AutoencoderKL'?
```

**To Reproduce**
I tried with a large variety of dependency versions, and they all seem affected. Here is one such example:
```
python = ">=3.10,<3.12"
distro-info = "1.0"
scikit-build = "^0.16.7"
pillow = "^10.2.0"
ninja = "^1.11.1"
diffusers = "^0.15.0"
triton = "^2.2.0"
transformers = "^4.37.2"
pynsq = "^0.9.1"
compel = "^2.0.2"
scipy = "^1.12.0"
torch = "^2.2.0"
xformers = "^0.0.24"
accelerate = "^0.26.1"
deepspeed = "^0.13.1"
```

**Expected behavior**
No error.

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: Linux Mint 21.2
 - GPU count and types: 1 Nvidia GeForce RTX 3070 NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3 
 - (if applicable) 0.13.1
 - (if applicable) 
 - 3.11

**Docker context**
Not using docker.

**Additional context**

**Comment by lekurile** [comment]
Hello @mikob,

This is due to the `diffusers` library changing the path to `vae` in diffusers version `>=0.25.0`. See this [PR here](https://github.com/microsoft/DeepSpeed/pull/4918/files).

What this means is that the latest versions of DeepSpeed support diffusers version `>=0.25.0` as seen in the `requirements.txt` in the PR linked above.

Can you please try updating your `diffusers` library to the latest and running again?

Thanks,
Lev

**Comment by mikob** [comment]
Hi @lekurile yes tried your fix_sd_cli branch and it got me closer to working, along with another change it was working but then hit another roadblock in inference: https://github.com/microsoft/DeepSpeed/issues/5091

**Comment by lekurile** [comment]
@mikob,

Glad you've made some progress. Since there's another issue opened now in #5091, shall we close this one?

Thanks,
Lev
