### ISSUE TITLE
[BUG] Does deepspeed MoE support dynamic network (with unused parameters)?

### ISSUE THREAD

**Issue by wjn922** [microsoft/DeepSpeed#5070]
**Describe the bug**
My network is a dynamic network, which means that the network would produce unused parameters.
I add the deepspeed MoE to the Llama model. And the output hidden states will forward different modules according to the inputs. Here is the sample forward code.

```
def forward(self, input_embeds, labels, flag):
    hidden_states = self.moe_llama(input_embeds)

    if flag == 1:
        outputs = self.net1(hidden_states)
    else:
        outputs = self.net2(hidden_states)

    loss = compute_loss(outputs, labels)
```

The code can run on 1 gpu, but fail on multiple gpus. 
When using multiple gpus, the training just got stuck without throwing any errors.

Could you please give me some instructions. Looking forward to your reply. Thank you!

**Comment by hanxiaotian** [comment]
try to add dummy grad result for unused part, solve the problem on my end

**Comment by wjn922** [comment]
Great! Could you please provide an example on how to add dummy grad results? Thank you! @hanxiaotian

**Comment by hanxiaotian** [comment]
> Great! Could you please provide an example on how to add dummy grad results? Thank you! @hanxiaotian

For your case, a simple and dirty fix would be something like:

```python
def forward(self, input_embeds, labels, flag):
    hidden_states = self.moe_llama(input_embeds)
    
    outputs1 = self.net1(hidden_states)
    loss1 = compute_loss(outputs1, labels)
    outputs2 = self.net2(hidden_states)
    loss2 = compute_loss(outputs2, labels)
    
    if flag == 1:
        return loss1 + 0*loss2
    else:
        return 0*loss1 + loss2
```

Hope this could help you

**Comment by wjn922** [comment]
I have tried in this way but it failled. Did you use deepspeed zero1 or zero2?

**Comment by hanxiaotian** [comment]
> I have tried in this way but it failled. Did you use deepspeed zero1 or zero2?

I use zero3
