### ISSUE TITLE
Training failing w/ certain parallelism degrees after PR #4974

### ISSUE THREAD

**Issue by lekurile** [microsoft/DeepSpeed#5145]
**Describe the bug**
After the introduction of #4974, certain degrees of parallelism fail in the `scaled_global_norm` function:
https://github.com/microsoft/DeepSpeed/blob/a37e59b590a42d425ef962640762c99ced17b752/deepspeed/runtime/zero/stage_1_and_2.py#L1789C8-L1789C65

with the following error:
```bash
Traceback (most recent call last):
  File "megatron/pretrain_gpt.py", line 356, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "megatron/megatron/training.py", line 226, in pretrain
    iteration = train(forward_step_func,
  File "megatron/megatron/training.py", line 1203, in train
    train_step(forward_step_func,
  File "megatron/megatron/training.py", line 669, in train_step
    loss = model[0].train_batch(data_iter=data_iterator)
  File "ds/deepspeed/runtime/pipe/engine.py", line 371, in train_batch
    self._exec_schedule(sched)
  File "ds/deepspeed/runtime/pipe/engine.py", line 1371, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "ds/deepspeed/runtime/pipe/engine.py", line 1173, in _exec_optimizer_step
    self._take_model_step(lr_kwargs)
  File "ds/deepspeed/runtime/engine.py", line 2073, in _take_model_step
    self.optimizer.step()
  File "ds/deepspeed/runtime/zero/stage_1_and_2.py", line 1827, in step
    scaled_global_grad_norm = self.scaled_global_norm()
  File "ds/deepspeed/runtime/zero/stage_1_and_2.py", line 1777, in scaled_global_norm
    return torch.norm(torch.stack(norm_groups), p=norm_type)
RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [] at entry 1
```

The table below shows the specific parallelism degrees with failures:
| TP | PP | DP | Pass/Fail |
| -- | -- | -- | -- |
| 2 | 1 | 1 | PASS |
| 1 | 2 | 1 | PASS |
| 1 | 1 | 2 | PASS |
| 2 | 2 | 1 | PASS |
| 1 | 2 | 2 | FAIL |
| 2 | 1 | 2 | PASS |
| 2 | 2 | 2 | FAIL |

**To Reproduce**
To reproduce this behavior:
1. Go to the Universal Checkpointing [README](https://github.com/microsoft/Megatron-DeepSpeed/tree/main/examples_deepspeed/universal_checkpointing)
1. [Download and pre-process](https://github.com/microsoft/Megatron-DeepSpeed/tree/main/examples_deepspeed/universal_checkpointing#download-and-pre-process-training-dataset) GPT training data.
1. Configure `run_fp16.sh` to have `TP=1, PP=2, DP=2`.
1. Execute `bash examples_deepspeed/universal_checkpointing/run_fp16.sh`

**Expected behavior**
When detaching the head to one commit before #4974, training for all parallelism degrees is functional.

**ds_report output**
```bash
DeepSpeed general environment info:
torch install path ............... ['/venv/test_11.6/lib/python3.8/site-packages/torch']
torch version .................... 1.13.1+cu116
deepspeed install path ........... ['/ds/deepspeed']
deepspeed info ................... 0.13.3+d67d4e5b, d67d4e5b, master
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.6
shared memory (/dev/shm) size .... 755.29 GB
```

Hello @nelyahu,

We've discovered a training issue with certain degrees of parallelism after #4974 was committed to DeepSpeed. I've documented the issue and reproduction steps above. Would it be possible for you to kindly take a look at this issue?

Thanks,
Lev

**Comment by nelyahu** [comment]
Hi @lekurile,
Yes, i will fix this, seems like one of the norms is shapeless (i.e. shape of []) while the other has shape of [1]. both are single element.
Let me check a fix locally and create a PR.

**Comment by lekurile** [comment]
After merging #5148, this issue has been resolved. Thank you @nelyahu for your work on this.

Closing the issue now.
