### ISSUE TITLE
DeepSpeed command not recognized on Windows

### ISSUE THREAD

**Issue by aaronnat23** [microsoft/DeepSpeed#5152]
**Describe the bug**
I am having issues infering the model after installing deepspeed for windows. my configuration is mentioned below, is there anyway we can perform inference with just a python script. i tried to directly call python moellava/serve/cli.py but it looks like in the code still needs deepspeed. Also have no issues when i perform inference for base LLAVA model

**To Reproduce**

deepspeed --include localhost:0 moellava/serve/cli.py --model-path "LanguageBind/MoE-LLaVA-StableLM-1.6B-4e" --image-file "other/test2.jpg"

when i run the above i get this error:

'deepspeed' is not recognized as an internal or external command, 

even when i set the path to deepspeed lib from conda env, i still get this error

**System info**
 - OS: Windows 10
 - 1 GPU, Nvidia Quadro RTX 5000 16gb Vram
 - deepspeed installed from the windows instruction from here [https://github.com/microsoft/DeepSpeed]
 - Python version = 3.10
 - conda version torch==2.1.2 using cuda 12.1

**Comment by mrwyattii** [comment]
Hi @aaronnat23 the error `'deepspeed' is not recognized as an internal or external command` indicates that the deepspeed launcher script is not on your system path. When you install in a conda environment, there should be a `bin/deepspeed` installed as well. Can you please share the steps you used to setup your conda environment and install deepspeed?

**Comment by aaronnat23** [comment]
**setup for conda environment**
conda create -n moe_llava python=3.10
conda activate moe_llava
pip install --upgrade pip
conda install pytorch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 pytorch-cuda=12.1 -c pytorch -c nvidia
python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

**setup for deepspeed**
https://github.com/microsoft/DeepSpeed/issues/5152 from windows installation 
git clone repo
Launch cmd console with Administrator privilege for creating required symlink folders
set DS_BUILD_OPS=0
set DS_BUILD_SPARSE_ATTN=0
set DS_BUILD_EVOFORMER_ATTN=0
Run python setup.py bdist_wheel to build wheel in dist folder
pip install deepspeed-0.13.3+b20c4674-py3-none-any.whl from dist folder


i notice that in my conda env C:\Users\E\anaconda3\envs\moe_llava\bin, there is no deepspeed. 

However in C:\Users\E\anaconda3\envs\moe_llava\Lib\site-packages and in "pip freeze" i noticed that it is already installed

how can i add it to system path or what else do i need to do

**Comment by loadams** [comment]
Hi @aaronnat23 - if you still have this issue, I'd recommend using the latest Windows whl we have published since it appears you are on Windows.  The recent blog post on DeepSpeed on Windows should have the information you need, but please comment if you have more issues or if I can close this PR as stale.
