### ISSUE TITLE
NCCL error in test_checkpointing.py distributed tests

### ISSUE THREAD

**Issue by jithunnair-amd** [microsoft/DeepSpeed#518]
Many of the distributed tests in test_checkpointing.py seem to be incorrectly written: they end up using the same device 0 for the various ranks. One can verify this by setting the `NCCL_DEBUG_SUBSYS=INIT,COLL NCCL_DEBUG=INFO` environment variables while running the tests. Older versions of NCCL eg. 2.4.8 would allow this, but it causes errors with newer versions of NCCL  eg. 2.7.8. Attaching the run logs for both NCCL versions with above-mentioned environment variables set. DeepSpeed commit used is 7d4d742bf03f8e1707130391e0b39bd6d93a702a.
[test_checkpoint_unfused_optimizer.nccl_2.7.8.log](https://github.com/microsoft/DeepSpeed/files/5513800/test_checkpoint_unfused_optimizer.nccl_2.7.8.log)
[test_checkpoint_unfused_optimizer.nccl_2.4.8.log](https://github.com/microsoft/DeepSpeed/files/5513801/test_checkpoint_unfused_optimizer.nccl_2.4.8.log)

**Comment by ShadenSmith** [comment]
Thanks for the report and logs! As you can see, we test on older NCCL versions.

**Comment by jithunnair-amd** [comment]
Yes. However, this really seems to be an issue in the way the distributed test logic is written, because it ends up having multiple ranks on the same device (NCCL does not control the association of device to rank; it just uses the current CUDA device).

**Comment by ShadenSmith** [comment]
Yep, understood. I just meant we had not encountered the error before due to older NCCL versions.

I haven't had a chance to dig into specifics yet, but am curious why the ranks are all pinned to the same device. Our `distributed_test` helper assigns devices: https://github.com/microsoft/DeepSpeed/blob/eea1c285a8271b94e43070d058869fe9ef4576a8/tests/unit/common.py#L42

**Comment by jithunnair-amd** [comment]
Right, I noticed the same myself. However, when profiling the CUDA calls, I noticed that `cudaSetDevice(0)` was being called after the `cudaSetDevice(<device>)` call triggered from the line above. I wasn't able to narrow down where the subsequent `cudaSetDevice` calls were being triggered from.

**Comment by jeffra** [comment]
Hi @jithunnair-amd, this issue should now be resolved. Feel free to re-open if you're still seeing an issue though.
