### ISSUE TITLE
[BUG] 13.3 version pre-build Compilation error `fused_adam_frontend.o: No such file or directory` and `multi_tensor_adam.o: No such file or directory`

### ISSUE THREAD

**Issue by pacman100** [microsoft/DeepSpeed#5192]
**Describe the bug**
When prebuilding Fused Adam and CPU Adam ops using version 13.3 results in the below errors:

```
x86_64-linux-gnu-g++ -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /tmp/pip-install-1tlqmndk/deepspeed_71bbcb0520784a12951d9b2f40f00b0d/build/temp.linux-x86_64-3.10/csrc/adam/fused_adam_frontend.o /tmp/pip-install-1tlqmndk/deepspeed_71bbcb0520784a12951d9b2f40f00b0d/build/temp.linux-x86_64-3.10/csrc/adam/multi_tensor_adam.o -L/usr/local/lib/python3.10/dist-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.10/deepspeed/ops/adam/fused_adam_op.cpython-310-x86_64-linux-gnu.so
  /usr/bin/ld: cannot find /tmp/pip-install-1tlqmndk/deepspeed_71bbcb0520784a12951d9b2f40f00b0d/build/temp.linux-x86_64-3.10/csrc/adam/fused_adam_frontend.o: No such file or directory
  /usr/bin/ld: cannot find /tmp/pip-install-1tlqmndk/deepspeed_71bbcb0520784a12951d9b2f40f00b0d/build/temp.linux-x86_64-3.10/csrc/adam/multi_tensor_adam.o: No such file or directory
  collect2: error: ld returned 1 exit status
  error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```  

**To Reproduce**
1. Command:
```
DS_BUILD_CPU_ADAM=1 DS_BUILD_FUSED_ADAM=1 python3 -m pip install deepspeed --global-option="build_ext" --global-option="-j8" --no-cache -v --disable-pip-version-check
```
2. Adding `DS_DISABLE_NINJA=1` does resolve it, therefore this error is mostly related to the PR https://github.com/microsoft/DeepSpeed/pull/5088.

**Expected behavior**
No pre-build compilation errors

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - GPU count and types: One machine with x4 A100s
 - Python version: 3.10.13
 - PyTorch 2.2.1
 - Cuda 12.1

**Comment by mrwyattii** [comment]
@pacman100 can you please confirm that this is not a problem with #5194? We will do a 0.13.4 release after you are able to confirm that reverting back to disabling ninja by default fixes the error. Thanks!

**Comment by pacman100** [comment]
Yes,I can confirm that using the 0.13.2 version doesn't lead to any issues.

**Comment by mrwyattii** [comment]
@pacman100 we have done a 0.13.4 release that disables ninja by default (it can be re-enabled with `DS_ENABLE_NINJA=1`). We will work to debug why this error is popping up in some environments when ninja is enabled. Thanks!
