### ISSUE TITLE
Unable to find Transformer CUDA kernels

### ISSUE THREAD

**Issue by rgeorgej** [microsoft/DeepSpeed#521]
I  have build the DeepSpeed with with the following environment variables sets
export DS_BUILD_CUDA=1
export DS_BUILD_CPU_ADA=1
export DS_BUILD_LAMB=1
export DS_BUILD_TRANSFORMER=1
export DS_BUILD_SPARSE_ATTN=1

But when i try to test the installation with basic_install_test.py i receive that the transformer kernel is not installed
[INFO] using new-style apex
 [WARNING]  fused lamb is NOT installed.
 [WARNING]  transformer kernels are NOT installed.
 [WARNING]  sparse attention is NOT installed.
 [WARNING]  cpu-adam (used by ZeRO-offload) is NOT installed.

The way i have installed is as follows
DS_BUILD_CUDA=1 DS_BUILD_CPU_ADAM=1 DS_BUILD_LAMB=1 DS_BUILD_TRANSFORMER=1 DS_BUILD_SPARSE_ATTN=1 pip3 install -v ./
Am i missing something

**Comment by tjruwase** [comment]
@rgeorgej, are you still seeing this issue with the master branch?

**Comment by loadams** [comment]
@rgeorgej - these are older variables now, so I'll close this issue as it is out of date.  If you are having any issues with the newest master branch of previous releases, please open a new issue and link this one or re-open this issue and we would be happy to take a look.

Thanks!
