### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Yathin-KN** [microsoft/DeepSpeed#5246]
I want to configure a custom offloading mechanism in Deepseed Zero.

I would like to have the ability to configure a custom offloading mechanism within Deepseed Zero. This would allow users to tailor the offloading process according to their specific needs and requirements. rn there is only provisions for NVme ssds .

Any reference to a similar implemention would be great !

**Comment by jomayeri** [comment]
@Yathin-KN feel free to branch or fork the repo and modify the offloading as you see fit. As far as references the current offloading in deepspeed is all I can offer.
