### ISSUE TITLE
[BUG]Problems with model initialization when using PipelineModule

### ISSUE THREAD

**Issue by Crispig** [microsoft/DeepSpeed#5262]
I was training my model using PipelineModule and noticed that I was having problems with model initialization, I noticed that my dataset was initialized on the GPU but the model seemed to be initialized to the CPU.
![image](https://github.com/microsoft/DeepSpeed/assets/56068245/d1233fea-b76b-4733-a436-6ca8bfd649db)

[bug.txt](https://github.com/microsoft/DeepSpeed/files/14572082/bug.txt)

**Comment by jomayeri** [comment]
Pass all the parameters instead of only those requiring gradients.
