### ISSUE TITLE
[BUG] Deepspeed zero-3 giving an OOM error

### ISSUE THREAD

**Issue by mmarouen** [microsoft/DeepSpeed#5265]
**Describe the bug**
- OOM error while trying to SFT llama-7b using peft on a 4 GPU cluster each 16Gb.
- Basically running: https://github.com/huggingface/peft/blob/main/examples/sft/train.py and adapting it to another input dataset.
- Total trainable parameters: `79,953,920` --> ca `80M paramters`
- Is the cluster memory too low for the task? 
-- Total memory requirements should be something like:
-- ~28Gb VRAM for model inference + less than 1Gb for paramters training
- ps: Im not using mixed precision or float16 + Im using zero3

**Setup**:
- 4 x Machines, each has a single GPU 16Gb VRAM
- Launcher: `SFTTrainer` from `trl` powered by `accelerate`
- Training configuration
```
    token_max_length: 256
    learning_rate: 0.001
    train_batch_size: 2
    eval_batch_size: 2
    block_size: 512
    num_epochs: 5
    gradient_accumulation_steps: 4
    weight_decay: 0.01
    gradient_checkpt: True
    num_warmup_steps: 5
```
- Docker image: `mcr.microsoft.com/aifx/acpt/stable-ubuntu2004-cu121-py38-torch212:biweekly.202402`
- Launch script:
```
  TOKENIZERS_PARALLELISM=false
  accelerate launch \
  --num_processes=4 \
  --num_machines=4 \
  --mixed_precision=no \
  --machine_rank=$NODE_RANK \
  --use_deepspeed \
  --deepspeed_config_file config/deepspeed_zero3.json \
  --dynamo_backend=no \
  --rdzv_backend=static \
  --main_process_ip=$MASTER_ADDR \
  --main_process_port=$MASTER_PORT \
  scripts/translation_trainer_3.py
```
- Running on Azure ML Virtual machine, here's an overview of the environment
```
azureml-core==1.55.0.post1
azureml-dataset-runtime==1.55.0
azureml-defaults==1.55.0
azure-ml==0.0.1
azure-ml-component==0.9.18.post2
azureml-mlflow==1.55.0
azureml-contrib-services==1.55.0
azureml-contrib-services==1.55.0
azureml-automl-common-tools==1.55.0
torch-tb-profiler~=0.4.0
azureml-inference-server-http
inference-schema
MarkupSafe==2.1.2
regex
pybind11
urllib3>=1.26.18
cryptography>=42.0.4
aiohttp>=3.8.5
evaluate
lxml
pandas
huggingface_hub
PyQt5
torch
sentencepiece
protobuf
PyYAML
sphinx_rtd_theme
deepspeed
git+https://github.com/huggingface/transformers
git+https://github.com/huggingface/accelerate
git+https://github.com/huggingface/peft
git+https://github.com/huggingface/trl
```

**Expected behavior**
The model's weighs should split across the GPUs not resulting in a OOM error

**ds_report output**
```
{
    "fp16": {
        "enabled": false,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "sub_group_size": 1e9,
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": "auto"
    },
    "gradient_accumulation_steps": 4,
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```
**Screenshots**:
Here you can find the output from one worker node
[worker_output.txt](https://github.com/microsoft/DeepSpeed/files/14580687/worker_output.txt)

**Comment by tjruwase** [comment]
@mmarouen, thanks for reporting this issue. Below are my initial observations. 

The attached log shows the runs is on 1 GPU not 4 GPUs
<img width="730" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/4271600/b82d6927-5ea6-4142-b856-4e545805ba1c">

From your description, it seems that for distributed training run with 4 GPUs on 1 machine, the command line should: 
1. Include --multi_gpu 
<img width="468" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/4271600/e0ac3db1-e04b-4338-910d-65ce768c6f45">

2. Set --num_machines=1, instead of 4

**Comment by mmarouen** [comment]
@tjruwase Thanks for the answer:) 
The setup is 4 machines each with a single GPU: The attached file is the log from `machine_0`, so it would be normal to have `world size=0` right?

**Comment by tjruwase** [comment]
> so it would be normal to have `world size=0` right?
You mean `dist_world_size=1`, right? Regardless, the correct behavior is `dist_world_size=4` because that represents the number of training ranks, i.e., GPUs.

Another clue of misconfiguration is that `nnodes=1; ...` instead of the expected `nnodes=4, ...`, since `nnodes` represents the number of machines or nodes.

**Comment by mmarouen** [comment]
Thanks for the catch! Indeed seems like a cluster misconfiguration issue. In that case i suppose the question becomes:
**Is it possible to run `accelerate` and `deepspeed` on an azure cluster?**
As you can be seen from the launch script, i specified the number of machines and launched a `command job` on a compute cluster containing the aforementioned configuration.
Could it be that deepspeed is simply ran on each instance without connection to the next instance?
Any help on who should be the right forum to post this question?
Thanks

**Comment by mmarouen** [comment]
Misconfiguration of the cluster.
