### ISSUE TITLE
RuntimeError: Error building extension 'fused_adam'[BUG]

### ISSUE THREAD

**Issue by chenchen333-dev** [microsoft/DeepSpeed#5277]
File "/home/nbicc/data/anaconda3/envs/visualglm/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'

**Comment by chenchen333-dev** [comment]
怎么解决呢

**Comment by loadams** [comment]
Hi @chenchen333-dev - can you please share your deepspeed version, torch version and cuda version, as well as the command you are running and the full error message?  Thanks.

**Comment by AlongWY** [comment]
hi, the [repo](https://github.com/AlongWY/deepspeed_wheels) build different deepspeed wheels.

**Comment by loadams** [comment]
Hi @AlongWY - thanks, but some users will need to either build wheels locally or use from a known PyPI index.  

@chenchen333-dev if you have a chance, please let us know more about your environment.

**Comment by zzyzeyuan** [comment]
Hi, @loadams , I got the same issue as @chenchen333-dev .
When I run `finetune_qlora_single_gpu.sh` command, I got this error:
```
RuntimeError: Error building extension 'fused_adam'
```
This is my environment info:
```
[2024-03-26 12:28:08,970] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ubuntu/miniconda3/envs/glm/lib/python3.10/site-packages/torch']
torch version .................... 1.13.1+cu117
deepspeed install path ........... ['/home/ubuntu/miniconda3/envs/glm/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.14.1+0529eac, 0529eac, master
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.5
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7
shared memory (/dev/shm) size .... 47.15 GB
```
Any help? Thanks !

**Comment by zzyzeyuan** [comment]
And I also notice that there are many ops that are compatible with my env but they are not installed. So how can I install these ops ?

**Comment by AlongWY** [comment]
the [page](https://www.deepspeed.ai/tutorials/advanced-install/) say you can use to install the ops:

```
DS_BUILD_OPS=1 pip install deepspeed --global-option="build_ext" --global-option="-j8"
```

**Comment by zzyzeyuan** [comment]
> the [page](https://www.deepspeed.ai/tutorials/advanced-install/) say you can use to install the ops:
> 
> ```
> DS_BUILD_OPS=1 DS_BUILD_EVOFORMER_ATTN=0 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed --global-option="build_ext" --global-option="-j8"
> ```

I uninstall `deepspped`, and then use the given command `DS_BUILD_OPS=1 DS_BUILD_EVOFORMER_ATTN=0 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed --global-option="build_ext" --global-option="-j8"` to install `deepspeed`. Sadly, it doesn't work for me, there is nothing changed about the results of `ds_report`.

**Comment by loadams** [comment]
Hi @zzyzeyuan - you do not need to pre-compile the ops, if they are used/needed in your model, DeepSpeed will JIT compile them, more info [here](https://www.deepspeed.ai/tutorials/advanced-install/#pre-install-deepspeed-ops).  Typically you only need to do this if you are building an instance of the wheel that you need to distribute across a number of nodes.

**Comment by loadams** [comment]
Closing this issue since we are off the original topic.  @chenchen333-dev - if you are still hitting this issue, please open a new issue and link this one.
