### ISSUE TITLE
[REQUEST] Ada-Lovelace support

### ISSUE THREAD

**Issue by orbisAI** [microsoft/DeepSpeed#5284]
Are there plans to support ada-lovelace architecture in the future?

We tested DeepSpeed on L4 and 4090, which are on the ada-lovelace architecture, and it sporadically creates faulty outputs that otherwise would be fine on an Ampere architecture GPU like RTX A6000.

**Comment by tjruwase** [comment]
@orbisAI, thanks for your question. Unfortunately, we don't have access to L4 or 4090 and so unable to debug issues. If you are able to share logs or stack traces, perhaps we can collaborate to resolve the issues.

**Comment by loadams** [comment]
Closing this as stale for now, @orbisAI - let us know if you are able to share a stacktrace and we can try to help.
