### ISSUE TITLE
PipelineParallelGrid' object has no attribute 'slice_parallel_size'

### ISSUE THREAD

**Issue by gongwei-130** [microsoft/DeepSpeed#530]
https://github.com/microsoft/DeepSpeed/blob/9941ce75225868ef9222a0360683a563d05d87ad/deepspeed/runtime/pipe/topology.py#L452

AttributeError: 'PipelineParallelGrid' object has no attribute 'slice_parallel_size'

**Comment by mrwyattii** [comment]
This was resolved in #1091. Closing
