### ISSUE TITLE
Confusion about Inference

### ISSUE THREAD

**Issue by ZekaiGalaxy** [microsoft/DeepSpeed#5310]
Hi, I read the deepspeed docs and have the following confusion:

**(1) What's the difference between these methods when in inferencing LLMs?**
a. deepspeed.initialize and then write code to generate text
b. deepspeed.init_inference then write code to generate
c. use mii to inference

**(2) Which of them are friendly for memory? For example, I want to inference 70b models, which of them support model parallelism that separates model parameters across gpus?**

**(3) For inference, what's the best practice now for inferencing 70b llama?**
a. zero3 + cpu offload (1*a100)
b. zero3 (2*a100)
...

Thank you!

**Comment by tjruwase** [comment]
1. Inference methods
   a. **deepspeed.initialize** enables zero-inference which uses offloading and zero3 sharding and is designed for throughput-oriented or low-budget scenarios.  See [this](https://www.deepspeed.ai/2022/09/09/zero-inference.html) and [this](https://github.com/microsoft/DeepSpeedExamples/tree/master/inference/huggingface/zero_inference). 
  b. **deepspeed.init_inference** enables a highly optimized inference computation based on CUDA kernels and automatic tensor-parallelism. 
 c. **mii** is an e2e inference server solution that integrates our latest fast inference engine called [FastGen](https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-fastgen). Our future efforts in this space will target mii and FastGen. 
 
2. All the methods are memory friendly in different ways: zero-inference (offloading, zero3 sharding), and FastGen (tensor-parallelism). 

3. 70b llama inference: The two options you list fall under zero-inference and represent different tradeoffs: zero3 sharding (2xa100) is faster but costs more than offload(1xa100).
