### ISSUE TITLE
Issue with cpufeature not working when installing cpu-adam

### ISSUE THREAD

**Issue by dblakely** [microsoft/DeepSpeed#533]
Hi,

We were trying to install cpu-adam with `install.sh`, but we were given the following exception:
```
Building deepspeed wheel
DS_BUILD_OPS=0
./install.sh: line 148:  4387 Floating point exception(core dumped) python3.8 setup.py $VERBOSE bdist_wheel
Error on line 148
Fail to install deepspeed
```
This seems to be occurring because the `cpufeature` package isn't working on my system. For example, whenever I try to import `cpufeature`, I get:
```
Floating point exception (core dumped)
```

Is there a way to install cpu-adam without using `cpufeature` or any known fixes to this problem? For reference, my CPU is a Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz.

**Comment by tjruwase** [comment]
Hi @dblakely, thanks for using DeepSpeed. Sorry for this annoying issue. But we recently fixed it and removed this dependency from our build. Can you please give it a try?
