### ISSUE TITLE
[BUG] cannot import name 'log' from elastic agent 

### ISSUE THREAD

**Issue by amathews-amd** [microsoft/DeepSpeed#5337]
**Describe the bug**
Logging api changes : https://github.com/pytorch/pytorch/commit/b6201a60c57f79d081ecde66e1ce70e6614a3052
breaks https://github.com/microsoft/DeepSpeed/blob/ffb53c25cc8c7beeb0d4c092fb70d7352a1032e3/deepspeed/elasticity/elastic_agent.py#L9
`ImportError: cannot import name 'log' from 'torch.distributed.elastic.agent.server.api' (/root/miniconda3/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py)` 

`log` was renamed as `logger`

**Comment by cyrusradfar** [comment]
I just hit this and edited the source locally to get past it to train. Watching for this fix :) 

Deepest gratitude to you for reporting @amathews-amd. Saved me a lot of time.

**Comment by loadams** [comment]
Hi @amathews-amd and @cyrusradfar - can you confirm that this PR fixes the issue?

https://github.com/microsoft/DeepSpeed/pull/5346

**Comment by loadams** [comment]
This should be fixed in the latest master, if you can confirm that would be great, but closing this issue for now.
