### ISSUE TITLE
[BUG] Dynamically switching freeze layers during the training process

### ISSUE THREAD

**Issue by Dominic789654** [microsoft/DeepSpeed#5341]
I would like to ask a question about **dynamically switching freeze layers during the training process**. For example, during steps 0-10, only train layers 3-5, and during steps 11-20, only train layers 8-10. In this way, only three layers would require memory for backpropagation at each step. However, in my tests, I found that DeepSpeed does not save memory in this type of training process. DeepSpeed still occupies memory equal to the total model parameters (forward and backward), only reducing the training time, which I suspect is due to the time saved as only the activated parameters are updated during backpropagation.   
So, my question is whether DeepSpeed supports dynamic **switching of freeze layers** during training, and when this feature might be available.

ref: https://github.com/microsoft/DeepSpeed/issues/2615
I believe this issue has been resolved regarding saving memory for training with fixed freeze layers, but it seems that the dynamic memory management has not yet been addressed.

**Comment by OpenMOSE** [comment]
for me solved if i add it in steps

param.grad = None
