### ISSUE TITLE
How to use DeepSpeed-Ulysses with the Pure Deepspeed Zero (i.e., deepspeed.initialize)

### ISSUE THREAD

**Issue by ShomyLiu** [microsoft/DeepSpeed#5348]
Thanks a lot for the effort in long context training with DeepSpeed-Ulysses. However, the examples are only based on the Megatron-Deepspeed framework;  Are there any tutorials or examples that use only Deepspeed Zero3? 

As the example in the  [documents](https://www.deepspeed.ai/tutorials/ds-sequence/#2-how-to-use-deepspeed-ulysses-in-your-application), one should create a new dist group for each sequence parallel group, will the following initialize_model_parallel method  be incompatible with the `deepspeed.initialize(model=model,..)`
```
def initialize_model_parallel(
    ...
    sequence_parallel_size,
    ...
):
    ...
    num_sequence_parallel_groups: int = world_size // sequence_parallel_size
    num_sequence_data_parallel_groups: int = world_size // sequence_parallel_size // data_parallel_size
    ...
    global _SEQUENCE_PARALLEL_GROUP
    for i in range(num_sequence_parallel_groups):
        ranks = range(i * sequence_parallel_size,
                      (i + 1) * sequence_parallel_size)
        group = torch.distributed.new_group(ranks)
        if rank in ranks:
            _SEQUENCE_PARALLEL_GROUP = group

def get_sequence_parallel_group():
    """Get the sequence parallel group the caller rank belongs to."""
    return _SEQUENCE_PARALLEL_GROUP

```
So where and how should I set and place the `get_sequence_parallel_group()` function, to use the DistAttn as below:
```
self.dist_attn = DistributedAttention(self.local_attn, parallel_state.get_sequence_parallel_group())
```

Would you mind taking care of this issue, thanks @RezaYazdaniAminabadi  @samadejacobs

**Comment by ShomyLiu** [comment]
I find the following related functions in
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/utils/groups.py#L452C5-L497

however, all of them are based on `mpu`

**Comment by samadejacobs** [comment]
@ShomyLiu, yes, something similar to Megatron parallel state/mpu would be needed to set/get sequence group. We are working on a general solution. Contributions are welcome!

**Comment by ShomyLiu** [comment]
@samadejacobs  Thanks for the effort! Also, do we have a current schedule or timeline for this?

**Comment by jinec** [comment]
@ShomyLiu  最后咋解决的啊？怎么得到这个get_sequence_parallel_group()？

**Comment by zhangjiewu** [comment]
same question, any update?
