### ISSUE TITLE
RuntimeError: no GPU resources available

### ISSUE THREAD

**Issue by khangt1k25** [microsoft/DeepSpeed#535]
I have faced this problem: RuntimeError: Unable to proceed, no GPU resources available. Is it possible to run deepspeed without GPUs?

**Comment by 201577D0212** [comment]
Hello, I also met this problem in the process of deploying the environment, I would like to ask you how to solve this problem?

**Comment by Flonixcorn** [comment]
Same Problem here

**Comment by samadejacobs** [comment]
@khangt1k25 @201577D0212 @Flonixcorn, thank you for your interest in deepspeed, CPU-only (non-GPU) training/deployment is currently not supported.

**Comment by Quentin-Anthony** [comment]
@khangt1k25 @201577D0212 @Flonixcorn -- Feel free to test (unofficial, experimental) CPU support with https://github.com/microsoft/DeepSpeed/pull/2245

**Comment by nevakrien** [comment]
different issue same error I have 4 pvc gpus and it dosent seem to detect them but pytorch does detect them just fine
