### ISSUE TITLE
Cannot install DeepSpeed without CUDA

### ISSUE THREAD

**Issue by harrydrippin** [microsoft/DeepSpeed#537]
## Problem

I tried to install DeepSpeed above torch-preinstalled `virtualenv`, and saw this error:

```text
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/04/wv3vnq8n3ns_3h3b5f8rn23r0000gn/T/pip-install-z1zw2ddb/deepspeed/setup.py", line 147, in <module>
        cuda_version = ".".join(torch.version.cuda.split('.')[:2])
AttributeError: 'NoneType' object has no attribute 'split'
[WARNING] Torch did not find cuda available, if cross-compling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
```

## Why?

I found that warning message at [Line 60 of setup.py](https://github.com/microsoft/DeepSpeed/blob/ca9ab1201ff56815652b7b85496d262c2d89d6c1/setup.py#L60):

```python
if not torch.cuda.is_available():
    # Fix to allow docker buils, similar to https://github.com/NVIDIA/apex/issues/486
    print(
        "[WARNING] Torch did not find cuda available, if cross-compling or running with cpu only "
        "you can ignore this message. Adding compute capability for Pascal, Volta, and Turing "
        "(compute capabilities 6.0, 6.1, 6.2)")
```

So we can confirm that it was intentional to allow installation above no-CUDA environment to support cross-compiling or run framework with CPU only (e.g. CI environment). But at [Line 147 of setup.py](https://github.com/microsoft/DeepSpeed/blob/ca9ab1201ff56815652b7b85496d262c2d89d6c1/setup.py#L147), you can see the code trying to obtain CUDA version from torch without logical branch:

```python
torch_version = ".".join([TORCH_MAJOR, TORCH_MINOR])
cuda_version = ".".join(torch.version.cuda.split('.')[:2])
torch_info = {"version": torch_version, "cuda_version": cuda_version}
```

In this case, `torch.version.cuda` will produce `None` and the installation fails.

## Possible Fix

I think we have to add a guard for that line to prevent installation failure. I can send a PR for this if it is a bug.

Thank you for your support!

**Comment by jeffra** [comment]
Thanks for your contribution @harrydrippin! We have been slowly starting to remove many cuda dependencies that DeepSpeed has, but I am sure there are more remaining. I just approved PR #538 which is a great fix in this direction. We are super excited for PRs like this though, so if you find additional gaps in terms of cpu-only support we will try to promptly review any PRs like this :)

**Comment by khangt1k25** [comment]
@jeffra  Can we setup DeepSpeed for CPU-only environment?
