### ISSUE TITLE
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `enabled = True`. All model fields require a type annotation; if `enabled` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

### ISSUE THREAD

**Issue by littlelobberster** [microsoft/DeepSpeed#5400]
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `enabled = True`. All model fields require a type annotation; if `enabled` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

The problem occured when I was training the model,I use
deepspeed==0.7.7
pydantic==1.10.12

`Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/deepspeed", line 3, in <module>
    from deepspeed.launcher.runner import main
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/__init__.py", line 17, in <module>
    from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 82, in <module>
    from deepspeed.inference.config import DtypeEnum
  File "/home/ubuntu/.local/lib/python3.10/site-packages/deepspeed/inference/config.py", line 88, in <module>
    class BaseQuantConfig(DeepSpeedConfigModel):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 92, in __new__
    private_attributes = inspect_namespace(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 384, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `enabled = True`. All model fields require a type annotation; if `enabled` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.`

I have tried many versions of pydantic,but  it didn't work.

And I have tried to add  `ClassVar` into the code,didn't work.
```[tasklist]
### Tasks
```

**Comment by littlelobberster** [comment]
Ubuntu 20.04
Python3.9

**Comment by loadams** [comment]
Hi @littlelobberster - can you try with a newer DeepSpeed version?  0.7.7 is quite old and we've made a number of changes since then.

**Comment by loadams** [comment]
Hi @littlelobberster - closing this issue as stale for now.  I suspect this is due to a very old DeepSpeed version, and updating DeepSpeed/using the pydantic version in the requirements-dev.txt should resolve your issues.  If not, feel free to comment here and we can re-open and debug.  Thanks.
