### ISSUE TITLE
[REQUEST] Deepspeed support finetune extra large model with lora + pipeline ? 

### ISSUE THREAD

**Issue by wanghongqu** [microsoft/DeepSpeed#5404]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rosario-purple** [comment]
@wanghongqu This repo supports this: https://github.com/tdrussell/qlora-pipe

it is not part of DeepSpeed itself, but it uses DeepSpeed's pipeline parallelism to train LoRAs
