### ISSUE TITLE
Why is CPU Checkpointing only available with partitioned activations?

### ISSUE THREAD

**Issue by sshleifer** [microsoft/DeepSpeed#541]
I am trying to better understand offloading activations to CPU (`PA_TO_CPU`) here https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/activation_checkpointing/checkpointing.py#L730 and wondering why
> "CPU Checkpointing/Contiguous Checkpointing is only available with partitioned activations."

It seems to me like one could be implemented without the other? Or am I missing something.
This is not an issue with the code, just a question to firm up my understanding. 
Thanks in advance!

Tagging @jeffra based on git-blame.

**Comment by jomayeri** [comment]
Please try the latest version of DeepSpeed.
