### ISSUE TITLE
[REQUEST]I do not understand the meaning of   ' reduction '   in the ZERO++ paper.

### ISSUE THREAD

**Issue by laladong** [microsoft/DeepSpeed#5440]
in 3.3.1 All-to-all based implementation.  
' Once a GPU receives gradients from its predecessor, we dequantize it to recover full precision and conduct a local reduction. '
I would like to know what is the specific operation of reduction?

**Comment by loadams** [comment]
@laladong - this is an all reduce, what more/specifically were you looking for?

**Comment by loadams** [comment]
Closing as stale for now, please re-open if you have more questions.
