### ISSUE TITLE
Content window is blocking text on deepspeed.ai

### ISSUE THREAD

**Issue by sorenwacker** [microsoft/DeepSpeed#5494]
Is it somehow possible to remove or move the Content window on deepspeed.ai?

<img width="934" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/3391614/b4919371-d278-442c-b1aa-65a39010b7c0">

**Comment by loadams** [comment]
Good catch @sorenwacker - I'll take a stab at getting this moved to the side.  We thought this was fixed [here](https://github.com/microsoft/DeepSpeed/pull/5293), but seems not to be?

**Comment by loadams** [comment]
This should be fixed now, let us know if you're still seeing this, but I see it fixed on my side now.
