### ISSUE TITLE
[REQUEST] pynvml package seems to be deprecated in favor of nvidia-ml-py

### ISSUE THREAD

**Issue by elistevens** [microsoft/DeepSpeed#5517]
**Is your feature request related to a problem? Please describe.**
Managing package dependencies is complicated by deepspeed having a requirement of pynvml instead of nvidia-ml-py.

It seems that pynvml has been folded back into the nvidia-ml-py project, as both seem to have nearly identical pypi pages, but nvidia-ml-py has been updated recently while pynvml has been dormant for a year.

https://pypi.org/project/pynvml/#history
https://pypi.org/project/nvidia-ml-py/#history

**Describe the solution you'd like**
Please replace the pynvml entry in requirements.txt with nvidia-ml-py.

**Describe alternatives you've considered**
N/A

**Additional context**
At some point, it's likely that pynvml 11.5 will stop working with updated nvidia drivers unless it starts getting updates again.

**Comment by loadams** [comment]
Hi @elistevens - thanks for the reminder, I'll take a look at this.
