### ISSUE TITLE
[BUG] fp_quantizer is not correctly built when non-jit installation

### ISSUE THREAD

**Issue by twaka** [microsoft/DeepSpeed#5535]
**Describe the bug**
fp_quantizer is not correctly built when non-jit installation.

**To Reproduce**
```
DS_BUILD_FP_QUANTIZER=1 pip install deepspeed
```
install will succeed but
```
from deepspeed.ops.fp_quantizer import FP_Quantize
FP_Quantize()
```
will raise `ImportError: dynamic module does not define module export function (PyInit_fp_quantizer_op)`

**Expected behavior**

Renaming csrc/fp_quantizer/quantize.cu may solve the issue.
This restriction seems to be cause of the bug.
> Note that setuptools cannot handle files with the same name but different extensions
https://pytorch.org/tutorials/advanced/cpp_extension.html

**Comment by loadams** [comment]
Thanks for pointing this out @twaka - we will take a look

**Comment by loadams** [comment]
Can you try #5577?
