### ISSUE TITLE
[BUG] Error with nn.transformers layer size with Zero stage 3

### ISSUE THREAD

**Issue by q737645224** [microsoft/DeepSpeed#5543]
**Describe the bug**
The size of the nn.Transformers layer does not match, and parameters cannot be loaded after stage3 is used。But stage2 is capable of loading parameters normally

**To Reproduce**

**Expected behavior**
![image](https://github.com/microsoft/DeepSpeed/assets/42614579/11969520-6154-4520-85e6-0eadd0744379)

**ds_report output**
Please run `ds_report` to give us details about your setup.
![image](https://github.com/microsoft/DeepSpeed/assets/42614579/32e6fa86-8013-4aa5-b4a1-657c78e7198e)

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by loadams** [comment]
Can you please add a description and title?

**Comment by tjruwase** [comment]
Closing due to lack of response. Please reopen if needed.
