### ISSUE TITLE
[BUG] when use 'DS_BUILD_FUSED_ADAM=1 pip3 install deepspeed',it cant install fused_adam

### ISSUE THREAD

**Issue by MinFFFF** [microsoft/DeepSpeed#5554]
This may be due to issues with the latest version，when i use the command 'DS_BUILD_FUSED_ADAM=1 pip install deepspeed==0.14.1' it works

**Comment by loadams** [comment]
Hi @MinFFFF - can you please share the full error that you see when you run `DS_BUILD_FUSED_ADAM=1 pip install deepspeed`?

**Comment by loadams** [comment]
Hi @MinFFFF - following up on this, are you able to share more information and the error?

**Comment by loadams** [comment]
Hi @MinFFFF - I'm going to close this issue as stale, if you do come back to this, please comment and I can re-open it.
