### ISSUE TITLE
[REQUEST] Supporting custom generation loop (outlines, LMQL, guidance) in DeepSpeedHybridEngine

### ISSUE THREAD

**Issue by Atry** [microsoft/DeepSpeed#5595]
**Is your feature request related to a problem? Please describe.**

Currently, `DeepSpeedHybridEngine.generate` internally calls `self._generate` to run inference loop, which is intialized as the module's `generate` method (usually it's `transformers.PreTrainedModel.generate`):
https://github.com/microsoft/DeepSpeed/blob/2fc702ed9f84f3c88179cb713bb9f4effbbdba33/deepspeed/runtime/hybrid_engine.py#L358

However, `transformers.PreTrainedModel.generate` does not support generation loops other than `module.generate`, for example, guided generation in [outlines](https://github.com/outlines-dev/outlines), [LMQL](https://github.com/eth-sri/lmql) or [guidance](https://github.com/guidance-ai/guidance) does, making it impossible to perform guided generation with `DeepSpeedHybridEngine`.

**Describe the solution you'd like**

Extract the code to set up and clear up generation from `DeepSpeedHybridEngine.generate` into a new context manager `DeepSpeedHybridEngine.generating`. Then `DeepSpeedHybridEngine.generate` can be implemented as:

```python
def generate(self, *inputs, **kwargs):
    with self.generating(*inputs, **kwargs):
        return self._generate(*inputs, **kwargs)
```

With the help of the proposed `generating` context manager, users can run custom generation like this:

```python
    with self.generating(*inputs, **kwargs):
        yield from streaming_generator_from_guidance_or_outlines_or_lmql(self.module, ...)
```

**Describe alternatives you've considered**
Alternatively, users can monkey-patch `PreTrainedModel.generate` to perform custom generation, like what [transformers-stream-generator](https://github.com/LowinLi/transformers-stream-generator/) does:

https://github.com/LowinLi/transformers-stream-generator/blob/f3866b70d6fd1718eb04e84b2420b80c1688ab0c/transformers_stream_generator/main.py#L1005-L1006

However, since `transformers-stream-generator`'s `NewGenerationMixin.generate` function returns a generator instead of a tensor, `DeepSpeedHybridEngine.generate` would clean up the generation too soon, even before `NewGenerationMixin.generate` finishing, which is not safe.

**Additional context**

**Comment by Irene-123** [comment]
Hi I went through this enhancement, and would be more safe to return a tensor instead of a generator
Wanted to know if I can take this up as my good-first-issue ?

**Comment by Atry** [comment]
Some library returning a generator is on purpose for streaming generation.

**Comment by Atry** [comment]
Hi Joe, could you add a link to the pull request completing this issue?
