### ISSUE TITLE
[BUG] 1 line logic issue: flipped sign/direction in `_partition_param_sec` of `partition_parameters.py`? 

### ISSUE THREAD

**Issue by dukleryoni** [microsoft/DeepSpeed#5642]
**Describe the bug**
Running Zero++ training leads to error from this [line](https://github.com/microsoft/DeepSpeed/blob/a41729f6a5b27b9df324b735bd3b16f387414272/deepspeed/runtime/zero/partition_parameters.py#L1698)

```
RuntimeError: narrow(): length must be non-negative.
```
This seems like it is a typo in the logic of the if statement, quoting the linked line above here.
```
sec_numel = param.ds_numel - secondary_start if secondary_end > param.ds_numel else secondary_partition_size
```
With the current logic, When the if-statement condition is `True` `sec_numel` will be negative which leads to a runtime error when it is used by `torch.narrow()`

Not sure if this is intended and I am missing something or the line should be revised to ensure non-negative `sec_numel`.

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by samadejacobs** [comment]
Please take a look at this [PR](https://github.com/microsoft/DeepSpeed/pull/5652).
