### ISSUE TITLE
Inference with the MoE based GPT model trained by ds_pretrain_gpt_345M_MoE128.sh [BUG]

### ISSUE THREAD

**Issue by haoranlll** [microsoft/DeepSpeed#5647]
The existing scripts failed to  inference with the MoE based GPT model. The MoE policy provided in the source code [https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/module_inject/containers/megatron_gpt_moe.py](url) can't handle the MoE model at all. Is there a quick way to fix this problem?

**Comment by jomayeri** [comment]
The link appears to be broken. Please open a new issue if it persists.
