### ISSUE TITLE
does DeepSpeed support AMSP (a new DP shard strategy)

### ISSUE THREAD

**Issue by guoyejun** [microsoft/DeepSpeed#5661]
there's a new DP shard strategy which is more flexible and general, see more detail at https://arxiv.org/abs/2311.00257 AMSP: Reducing Communication Overhead of ZeRO for Efficient LLM Training

Does DeepSpeed support similar feature? If not, any plan to support it? thanks.

**Comment by jomayeri** [comment]
We don't have this on our road map but please feel free to create a pull request with the feature and we will review it.
