### ISSUE TITLE
Running out of CPU memory. Dataset is loaded for each created process

### ISSUE THREAD

**Issue by MikeMitsios** [microsoft/DeepSpeed#5689]
**Describe the bug**
I want to pretrain a BERT model on 8 A100 40G GPUS. The problem which I have is that I run out of CPU memory (not GPU memory). I cannot understand why. I am trying to load a 75G dataset and deepspeed will load it as many times as the created processes. **Is there a way to load the dataset only once in the CPU?** My setup covers up to 500G CPU memory.
Also,  what would be the optimal parameters for such training? Also why do I not have a larger batch size when I am using zero optimizer stage 2?

**To Reproduce**
deepspeed config file:
{
    "train_batch_size": 2048,   
    "gradient_accumulation_steps" : 32,
    "optimizer": {
       &emsp; "type": "AdamW",
        &emsp;"params": {
            &emsp;&emsp;"lr": 1.0e-04,
            &emsp;&emsp;"betas": [0.9, 0.98],
            &emsp;&emsp;"eps": 1e-6,
            &emsp;&emsp;"weight_decay": 0.01
        &emsp;}
    },
    &emsp;"fp16": {
        &emsp;&emsp;"enabled": true,
        &emsp;&emsp;"loss_scale": 0,
       &emsp;&emsp; "loss_scale_window": 1000,
        &emsp;&emsp;"initial_scale_power": 16,
        &emsp;&emsp;"hysteresis": 2,
        &emsp;&emsp;"min_loss_scale": 1
      },
    &emsp;"zero_optimization": {
        &emsp;"stage": 2,
        &emsp;"offload_optimizer": {
            &emsp;&emsp;"device": "cpu",
           &emsp;&emsp; "pin_memory": true
        },
        "contiguous_gradients": true,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "allgather_bucket_size": 2e8,
        "allgather_partitions": true
    },
    "zero_allow_untested_optimizer": true   
}

model = BertForMaskedLM(config=config).to(device)
 if self.deepspeed_conf is not None:
            &emsp;self.model, self.optimizer, _, _ = deepspeed.initialize(
                &emsp;&emsp;model=model,
                &emsp;&emsp;model_parameters=model.parameters(),
                &emsp;&emsp;config_params=self.deepspeed_conf
            )

for b in tqdm(self.dataloader):
            &emsp; data = {k:v.to(self.device) for k, v in b.items()}
            &emsp; labels = data.pop("labels")
            &emsp; output = self.model(**data)
            &emsp; loss = self.criterion(output["logits"],labels)
            &emsp; self.model.backward(loss)
            &emsp; self.model.step()

**Expected behavior**
1) Train without running out of memory
2) expected to be able to have larger batch size with the zero stage 2 optimization, but it will run out of memory.

**ds_report output**
8 40G A100 GPUs
64 CPU
500G memory

**Launcher context**
running: deepspeed train.py

Thanks a lot in advance!

**Comment by jomayeri** [comment]
Don't attempt to load the entire dataset into memory. Use a [memory map](https://numpy.org/devdocs/reference/generated/numpy.memmap.html) instead.
