### ISSUE TITLE
[BUG] Deepspeed does not seem to work using GPUDirect, should it?

### ISSUE THREAD

**Issue by m-harmonic** [microsoft/DeepSpeed#5693]
**Describe the bug**
When using Deepspeed, multi-node training does not train correctly when using GPUDirect for internode communication (specifically GPUDirect-TCPX on Google Cloud). The model seems to drastically undertrain, and the only indication of an issue in our output is a NCCL timeout warning of the form:

```tcpxResult_t tcpxCommProgress(tcpxComm*):1126 NCCL WARN 0x..., nic 3, enp6s0, ... rx rx ctrl timeout cnt 21311883, nanos 10000000217```

Is Deepspeed expected to work in this situation and if so are there any settings or environment variables necessary for training to work correctly?

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.6
 - GPU count and types: 2 machines with H100's
 - Interconnects (if applicable): GPUDirect  / GPUDirect-TCPX on Google Cloud
 - Python version: 3.10.13

**Launcher context**
Pytorch Lightning via `Trainer(strategy="deepspeed_stage_2")`

**Comment by GuanhuaWang** [comment]
Hi @m-harmonic , thx for reaching out.

Could you provide more detailed info (e.g., config file), as well as what is the difference between Google cloud's TCPX v.s. vanilla Nvidia GPUDirect? Generally, we are mostly using our own cloud env without TCPX support.

**Comment by m-harmonic** [comment]
> Member



> Hi @m-harmonic , thx for reaching out.
> 
> Could you provide more detailed info (e.g., config file), as well as what is the difference between Google cloud's TCPX v.s. vanilla Nvidia GPUDirect? Generally, we are mostly using our own cloud env without TCPX support.

@GuanhuaWang Hi, so it sounds like vanilla GPUDirect should work with deepspeed then? We are not too familiar with the difference with TCPX, however this is the configuration we are using supplied by Google, which sets many `NCCL_` environment variables: https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/examples/machine-learning/a3-highgpu-8g/nccl-tests/run-nccl-tests.sh#L41

Are there any configuration settings necessary to get deepspeed to work on GPUDirect? Thanks.

**Comment by GuanhuaWang** [comment]
> > Member
> 
> > Hi @m-harmonic , thx for reaching out.
> > Could you provide more detailed info (e.g., config file), as well as what is the difference between Google cloud's TCPX v.s. vanilla Nvidia GPUDirect? Generally, we are mostly using our own cloud env without TCPX support.
> 
> @GuanhuaWang Hi, so it sounds like vanilla GPUDirect should work with deepspeed then? We are not too familiar with the difference with TCPX, however this is the configuration we are using supplied by Google, which sets many `NCCL_` environment variables: https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/examples/machine-learning/a3-highgpu-8g/nccl-tests/run-nccl-tests.sh#L41
> 
> Are there any configuration settings necessary to get deepspeed to work on GPUDirect? Thanks.

Hi @m-harmonic ,

For nvidia GPUs, we rely on NCCL for GPUDirect. Basically, NCCL will automatically enable such feature. Given the code piece you provided, I believe it might be an issue of NCCL's TCPX support on Nvidia/nccl side.
