### ISSUE TITLE
[request] faster multi-core build and cleanup

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#573]
Would it be possible to support an equivalent of `make -j` (parallel multi-core compilation) to build all the features - it takes quite some time to build one .so at a time.

I currently do:
```
DS_BUILD_OPS=1 pip install --no-cache -v --disable-pip-version-check .
```
-----------------------

Also a `clean` target would be helpful. `python setup.py clean` doesn't currently handle binary files clean up.

I guess deleting `./build` should do the trick. I was doing:
```
find build -name "*\.so" -exec rm {} \;
```
A `Makefile` with `clean` target would have been awesome.

Thank you!

**Comment by stas00** [comment]
That's an old ticket, I had it resolved with `--global-option="-j8"`, but currently build script is:
```
rm -rf build
time TORCH_CUDA_ARCH_LIST="6.1;8.6" DS_BUILD_OPS=1 pip install -e . --global-option="build_ext" --global-option="-j8" --no-cache -v --disable-pip-version-check 2>&1 | tee build.log
```

**Comment by edward-io** [comment]
It would be useful to have this automatically set to the number of available cores, right now building custom ops quite some time (10+ minutes).
