### ISSUE TITLE
Unit tests should be runnable with < 4 GPUs

### ISSUE THREAD

**Issue by jeffra** [microsoft/DeepSpeed#574]
Currently our unit tests assume that we have up to 4 GPUs available at runtime. However, there are a lot of cases when it would be nice for end-users to run our unit tests in environments where they may only have 1 or 2 GPUs available. Currently we don't handle this gracefully and essentially no unit tests will run. (e.g., #570, #536).

Short term: skip unit tests if they require more than the available GPUs on the system. 

Longer term: refactor unit tests that currently require >1 GPUs to either run on a single GPU or even better run on CPU using the `gloo` distributed backend. This will require some work since it means all of deepspeed would need to be compatible with different devices (e.g., CPU and GPU).

**Comment by loadams** [comment]
Hey Jeff, closing since this has been significantly refactored - if we still need to do this, can I get some context?
