### ISSUE TITLE
Question: OneBitAdam on Eth/TCP

### ISSUE THREAD

**Issue by peteriz** [microsoft/DeepSpeed#575]
I'm interested in training BERT using multiple nodes with multiple GPUs (Titan-V). Our cluster is Kubernetes-based and we dont have Infiniband interconnects but rather 10Gb eth.
Using the provided Dockerfile (with up-to-date Deepspeed code) we're unable to run it. It is missing `mpiname`, other functionalities from openmpi and `mvapich` launcher is missing.
Does Onebitadam support such setup? if so could you please provide details on how to enable OneBitAdam on TCP/eth based networking?
Thanks

**Comment by awan-10** [comment]
@peteriz, thanks for reaching out. Can you please try by changing your ds_config.json file and your run script? Set cuda_aware to False in the ds_config.json file and change launcher from mvapich to openmpi. This is in the run script (e.g. deepsped --launcher=mvapich). Please let me know if this works on your setup.

**Comment by peteriz** [comment]
Thanks for the reply.
I tried what you suggested and got the following:
```
File "deepspeed_train.py", line 618, in main
    model, optimizer, lr_scheduler = prepare_model_and_optimizer(args)
  File "deepspeed_train.py", line 502, in prepare_model_and_optimizer
    lr_scheduler=lr_scheduler,
  File "/home/pizsak/.local/lib/python3.6/site-packages/deepspeed/__init__.py", line 118, in initialize
    config_params=config_params)
  File "/home/pizsak/.local/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 181, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/pizsak/.local/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 624, in _configure_optimizer
    self.optimizer = self._configure_fp16_optimizer(basic_optimizer)
  File "/home/pizsak/.local/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 690, in _configure_fp16_optimizer
    timers=timers)
  File "/home/pizsak/.local/lib/python3.6/site-packages/deepspeed/runtime/fp16/fused_optimizer.py", line 104, in __init__
    self.initialize_optimizer_states()
  File "/home/pizsak/.local/lib/python3.6/site-packages/deepspeed/runtime/fp16/fused_optimizer.py", line 112, in initialize_optimizer_states
    self.optimizer.step()
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pizsak/.local/lib/python3.6/site-packages/deepspeed/runtime/fp16/onebit_adam.py", line 346, in step
    self.deepspeed.local_rank))
AttributeError: 'NoneType' object has no attribute 'local_rank'
```

**Comment by awan-10** [comment]
Hi @peteriz. It looks like deepspeed is not initialized.

Can you please confirm if you can run BERT or any other example in DeepSpeedExamples (e.g. CIFAR) without 1-bit Adam? e.g. can you run ```bash ds_train_bert_bsz64k_seq128.sh``` in your bing_bert folder?

**Comment by peteriz** [comment]
Deepspeed is initialized. However, I'm providing the optimizer via the `deepspeed.initialize(...,optimizer=opt, ..)` method and initialize OneBitAdam optimizer via: 
```python
def get_1bitadam(optimizer_args, lr, model_params):
    return onebitadam(
        model_params,
        lr=lr,
        max_grad_norm=1.0,
        freeze_step=23000,
        cuda_aware=False,
        weight_decay=optimizer_args.weight_decay,
        bias_correction=False,
    )
```
Can this be the issue? Do I have to use DS json config for 1bit Adam?

**Comment by awan-10** [comment]
I have not tried this method. 

If it is not too much trouble, can you please check if the ds_config method works for you for 1-bit Adam? 

DeepSpeed will initialize the 1-bit optimizer for you like this: https://github.com/microsoft/DeepSpeedExamples/blob/master/bing_bert/deepspeed_train.py#L401

Simply use a config file like this to specify 1-bit adam as your optimizer: https://github.com/microsoft/DeepSpeedExamples/blob/master/bing_bert/deepspeed_bsz4k_onebit_config_seq128.json

**Comment by awan-10** [comment]
@peteriz, just checking if you got a chance to try this out?

**Comment by peteriz** [comment]
Hi @awan-10, I'm sorry but I haven't checked what you suggested yet since we abandoned the multi-node setup we had.
Last time I benchmarked the machines in our cluster I got ~7GB/sec (ethernet) link between the machine. 
Do you think we could achieve a faster rate with this kind of link speed and 1-Bit Adam? I'm trying to figure out if to pursue the multi-node direction again 
Thanks

**Comment by awan-10** [comment]
Hi @peteriz, yes 7 GB/sec is actually good. 1-bit Adam will help you so please give it a shot on a multi-node setup. We had used an older version of InfiniBand (QDR) for some experiments and we got good speedups on that so your Ethernet setup is definitely interesting to try out. Do let us know how it goes.

**Comment by peteriz** [comment]
Thanks for the reply. I'll take a look at it again and report back with info or issues we might encounter.

**Comment by awan-10** [comment]
@peteriz - closing this for now but feel free to reopen when you have some updates.

**Comment by peteriz** [comment]
> Hey @peteriz, were you able to try this out? I am setting up an academic lab and not sure if 10G ETH interconnects are sufficient.

Hi, I'm sorry but I didn't have a chance. Its definitely on my todo list and I'll update once I get to run such setup.
