### ISSUE TITLE
How to silence warning when import deepseed without change the source code?

### ISSUE THREAD

**Issue by sean-wade** [microsoft/DeepSpeed#5801]
![image](https://github.com/user-attachments/assets/cd270192-c7d8-4664-8f22-10a1dfa81459)

I just don't want to print the warning and infos.

**Comment by loadams** [comment]
@sean-wade - this PR has done some work on this, would this be enough for now?  

https://github.com/microsoft/DeepSpeed/pull/5917

**Comment by loadams** [comment]
Closing this for now as the PR above is merged
