### ISSUE TITLE
[BUG] build cpu_adam.so with wrong build.ninja file, missing the necessary ldflags

### ISSUE THREAD

**Issue by zydmtaichi** [microsoft/DeepSpeed#5813]
**Describe the bug**
run any model-training program with deepspeed, gen build.ninja file to compile cpu_adam.so. the build.ninja miss the graph driver lib path like -L/usr/local/cuda/lib64 in ldflags. the incorrect build.ninja config file cause the process of compile failed. please fix it soon
```[tasklist]
### Tasks
```

**Comment by zydmtaichi** [comment]
@tjruwase @loadams it's a deepspeed framework bug. the lib gen a wrong build config file. and it lead the compilation always fail

**Comment by zydmtaichi** [comment]
#3488

**Comment by zydmtaichi** [comment]
#889

**Comment by zydmtaichi** [comment]
[build.ninja.txt](https://github.com/user-attachments/files/16435580/build.ninja.txt)

**Comment by zydmtaichi** [comment]
the above file `build.ninja.txt` is generated by deepspeed automatic, miss the dir in ldflag

**Comment by zydmtaichi** [comment]
@stas00

**Comment by loadams** [comment]
@zydmtaichi - have you taken a look at this PR and if not, can you try this in your environment to see if this fixes your issues?

https://github.com/microsoft/DeepSpeed/pull/5780

**Comment by loadams** [comment]
@zydmtaichi - #5780 is now merged, can you test with that and we can then close this?

**Comment by zydmtaichi** [comment]
> @zydmtaichi - #5780 is now merged, can you test with that and we can then close this?

hi @loadams ,
Actually, I manually create a soft link for `/usr/local/cuda/lib64/`libcurand.so to my torch lib path `/miniconda3/envs/llmtest/lib/python3.10/site-packages/torch/lib` in conda env. the problem is solved temporarily. I will test the fixed version of deepspeed later and come back if necessary. for now, this issue can be closed.

Thanks a lot for your selfless help
