### ISSUE TITLE
[REQUEST] can we load a deepspeed ckpt without deepspeed?

### ISSUE THREAD

**Issue by exnx** [microsoft/DeepSpeed#5895]
Hello, is there a way to load the deepspeed checkpoint without deepspeed?  I'd like to somehow just load it with standard Pytorch.  Or do we somehow need to convert it first?  Deepspeed has some overhead that I'd like to get around for doing zero-shot evals downstream.

**Comment by tjruwase** [comment]
@exnx, please see https://deepspeed.readthedocs.io/en/latest/model-checkpointing.html#zero-checkpoint-fp32-weights-recovery

**Comment by exnx** [comment]
Thanks for sharing this!

More specifically, I was wondering if there's a way to load the deepspeed checkpoint without need to initializing deepspeed?  ie without `deepspeed.init_distributed()`.

Sometimes I get errors using deepspeed, like mpi issues, and for just loading ckpts it would be nice not need to do all that.

**Comment by exnx** [comment]
Also, what if you use a zero stage 1, or not at all, ie zero stage 0?

**Comment by ycool** [comment]
```
from deepspeed.utils.zero_to_fp32 import get_fp32_state_dict_from_zero_checkpoint

# remove all the deepspeed magic data
state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir) 

model = model.cpu() # move to cpu
model.load_state_dict(state_dict)

MODEL_PATH = "your_model_without_DS.pth"

# Save the model's state_dict
torch.save(model.state_dict(), MODEL_PATH)

# Load the model's state_dict
model.load_state_dict(torch.load(MODEL_PATH))

```

**Comment by exnx** [comment]
My understanding is that it `get_fp32_state_dict_from_zero_checkpoint` only works on zero 2 or 3 optimizers?  (not 0 or 1)?

**Comment by ycool** [comment]
zero 0 or zero 1, the model parameters are not partitioned. It means the full FP32 state dictionary is readily accessible without additional reconstruction steps.

**Comment by tjruwase** [comment]
@ycool, thanks for providing a workaround. 

Closing this issue.
