### ISSUE TITLE
Unable to install DeepSpeed using "pip install deepspeed" command in Windows 11

### ISSUE THREAD

**Issue by S-Kathirvel** [microsoft/DeepSpeed#5899]
My system configs (if needed) - Single 3060 gpu with vram of 6gb
Python 3.12 (primary) and python 3.11 (for virtual environments)
torch                                   2.2.2+cu121
CUDA - nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:36:51_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0

![image](https://github.com/user-attachments/assets/24fd23ed-179d-4391-a3a1-534dafb7994a)

tried setting set DS_BUILD_OPS=0 but that didnt work either.

**Comment by loadams** [comment]
Hi @S-Kathirvel - with the latest 0.14.5 release we have published a Windows whl as well.  Could you please give installing it a try?

![image](https://github.com/user-attachments/assets/8907b5f6-4fe5-4d66-aad3-77918c228bcc)

**Comment by S-Kathirvel** [comment]
Is it compatible with python 3.12 and cuda 12.5, if not can you tell me the version of them that works so that i can downgrade to try again

**Comment by S-Kathirvel** [comment]
So it worked on my python311 which i use to create virtual environments, so currently deepspeed is not available for python 3.12?

**Comment by loadams** [comment]
@S-Kathirvel - we haven't built the whl with python 3.12 yet, we're working on getting support added to our python workflows.

With 3.11 were you able to see DeepSpeed installed on Windows and able to run ds_report?

**Comment by S-Kathirvel** [comment]
@loadams i can see the package being downloaded thru pip list in my virtual environment but when i run ds_report

(deepspeed) E:\Deepspeed>ds_report
Traceback (most recent call last):
  File "E:\Deepspeed\deepspeed\Scripts\\ds_report", line 3, in <module>
    from deepspeed.env_report import cli_main
  File "E:\Deepspeed\deepspeed\Lib\site-packages\deepspeed\__init__.py", line 10, in <module>
    import torch
  File "E:\Deepspeed\deepspeed\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "E:\Deepspeed\deepspeed\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

I get this error

**Comment by S-Kathirvel** [comment]
@loadams 
![image](https://github.com/user-attachments/assets/d63725ad-67dd-49ce-ba75-844ce110ddcd)
I think it worked but can you help me with these warnings explaining what and why are they appearing

**Comment by loadams** [comment]
Hi @S-Kathirvel - thanks, that is the ds_report I was looking for.  It looks like DeepSpeed is installed properly then via pip, which is great to see.  The warnings are for ops that are currently not supported on Windows due to incompatibilities in other libraries they use (cutlass or async_io for example).  So you can ignore those warnings for now if you're just trying to use DeepSpeed on Windows.

**Comment by loadams** [comment]
Hi @S-Kathirvel - could you also run with `ds_report --hide_errors_and_warnings`?  That should remove these warnings, we are working on getting them cleaned up.

**Comment by S-Kathirvel** [comment]
what these dependcies for and based on what you said, does it affect any functionalities that deepspeed provide and how the windows and linux libraries differ or do they diifer

**Comment by loadams** [comment]
They are built from the same git tag, the windows whl is just built for windows, and contains the ops pre-built.  More information on the Windows whl and Windows support can be found here: https://github.com/microsoft/DeepSpeed/blob/master/blogs/windows/08-2024/README.md

**Comment by S-Kathirvel** [comment]
@loadams Thanks for the support man, I hope good things of this project.
