### ISSUE TITLE
Turing NLG

### ISSUE THREAD

**Issue by Immortalin** [microsoft/DeepSpeed#59]
Are there any plans to release the Turing NLG pre-trained model?

**Comment by selfReference** [comment]
Hi, we are currently only releasing a controlled demonstration of the model as we continue to test it. This decision is in line with Microsoft’s AI ethical principles and our goal is to not just build technology but to also ensure it is distributed and used in a responsible way.  See More: https://www.microsoft.com/en-us/AI/our-approach-to-ai

**Comment by loretoparisi** [comment]
+1 to release the LM!
In the meantime, the second best LM model freely available (NVIDIA Megatron 11 billions parameters) can be downloaded from Facebook Research fair (11b, 19GB model!)
https://github.com/pytorch/fairseq/blob/master/examples/megatron_11b/README.md

**Comment by loretoparisi** [comment]
> Hi, we are currently only releasing a controlled demonstration of the model as we continue to test it. This decision is in line with Microsoft’s AI ethical principles and our goal is to not just build technology but to also ensure it is distributed and used in a responsible way.  See More: https://www.microsoft.com/en-us/AI/our-approach-to-ai

After the giant GPT-3 has been released I assume Turing-NLG can be proposed as a reasonable alternative to academic research.
