### ISSUE TITLE
++(full video!!)FOTOS DO AVIAO QUE CAIU EM VINHEDO PORTAL ZACARIAS

### ISSUE THREAD

**Issue by leonebarnett** [microsoft/DeepSpeed#5909]
FOTOS DO AVIAO QUE CAIU EM VINHEDO PORTAL ZACARIAS
Veja imagens do avião que caiu em Vinhedo (SP)

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://viralleakedvideos.com/leaked.html?b)

[🔴 ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://viralleakedvideos.com/leaked.html?b)

Um avião da Voepass, antiga Passaredo, caiu no início da tarde desta sexta-feira (9) em Vinhedo, no interior de São Paulo. Ainda não há informações sobre vítimas.

O voo 2283 saiu de Cascavel (PR) e iria para Guarulhos. O avião acidentado, prefixo PS-VPB, é um ATR 72-500, cuja capacidade total é de 74 pessoas.

O acidente deixou 62 pessoas mortas –sendo 58 passageiros e quatro tripulantes. Inicialmente, a Voepass informou que 62 pessoas estavam a bordo. Posteriormente, passou a divulgar a lista com 61 ocupantes. Neste sábado (10), a companhia voltou a informar que 62 pessoas morreram na queda do avião em Vinhedo (SP).

O Corpo de Bombeiros informa que foi acionado por volta das 13h25. O avião caiu na rua Edueta, altura do número 2.500.

Segundo a Defesa Civil, a aeronave caiu em cima de algumas casas.

Tragédia em SP: imagens revelam como ficou residencial após queda de avião em Vinhedo

Um avião com 62 pessoas - 58 passageiros e quatro tripulantes - que saiu de Cascavel, no Paraná, com destino ao Aeroporto de Guarulhos, São Paulo, caiu no início da tarde desta sexta-feira (9) na cidade de Vinhedo, interior de São Paulo.

Autoridades já confirmam que todos os passageiros morreram, incluindo a tripulação da aeronave.  

LEIA TAMBÉM: O que se sabe sobre avião que caiu em Vinhedo, em SP? Veja vídeo

Segundo informações também do Corpo de Bombeiros de Vinhedo, todos os tripulantes da aeronave que caiu morreram.

FOTOS
Foto: Reprodução/X @choquei
Foto: reprodução de video
Foto: Reprodução/ X/Reprodução / Instagram
VÍDEO

O QUE SE SABE ATÉ AGORA?

*Entre os 62 ocupantes do avião estavam 58 passageiros e quatro tripulantes, informou a Voepass, responsável pelo voo.

*A aeronave tinha capacidade para 68 pessoas. Aeronave saiu de Cascavel (PR) com destino a Guarulhos (SP).

*O avião teria caído no quintal de uma das casas e atingido pelo menos parte de uma outra casa.

*O avião do modelo ATR-72 pertencia à Voepass Linhas Aéreas (antiga Passaredo). Em nota, a companhia informou que não há confirmação sobre como o acidente ocorreu nem sobre a situação atual das pessoas que estavam no voo.

*A companhia aérea diz que está prestando pelo telefone 0800 9419712, disponível 24h, informações a todos os seus passageiros, familiares e colaboradores.

*Sete equipes do Corpo de Bombeiros foram enviadas ao local. A ocorrência foi recebida às 13h25, segundo a corporação.

*Vídeo mostra momento da queda. Nas imagens, gravadas por moradores da região do Distrito Industrial, é possível ver a aeronave despencando.

*A Força Aérea Brasileira (FAB) informa que, por meio do Centro de Investigação e Prevenção de Acidentes Aeronáuticos (CENIPA), foi acionada para atuar na investigação.

**Comment by tysonrony** [comment]
**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**
**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**
**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**

**https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/

https://kayotvs.store/Leaked-video/**
