### ISSUE TITLE
Install DeepSpeed with cpu-only

### ISSUE THREAD

**Issue by khangt1k25** [microsoft/DeepSpeed#609]
Can we install DeepSpeed without cuda? and if yes, so how can i do that, I don't see that in documentations. Thanks

**Comment by a0n** [comment]
i know this is not an issue per se: 
but for me its also not clear yet if deepspeed is cuda only or if it can be used to scale a training task to multiple cpu only hosts

**Comment by haruya-umemoto** [comment]
any updates?

**Comment by AbhayGoyal** [comment]
Could this be done?

**Comment by tjruwase** [comment]
Yes, it is possible to install in cpu-only environment. Currently, only CPUAdam and CPUAdagrad features are available. However, more features will be enabled some thanks to Intel [contributions](https://github.com/microsoft/DeepSpeed/pull/3041).

**Comment by AbhayGoyal** [comment]
Could you point me to the code for that? I could not find it.

**Comment by tjruwase** [comment]
Earlier PRs
https://github.com/microsoft/DeepSpeed/pull/2507
https://github.com/microsoft/DeepSpeed/pull/2775

CI: https://github.com/microsoft/DeepSpeed/blob/master/.github/workflows/nv-torch-latest-cpu.yml

**Comment by AbhayGoyal** [comment]
Hi,
I meant example of how to use it.

**Comment by AbhayGoyal** [comment]
Thank you very much for your reply. Also, would this work in case of
inference? So if 8 want to use a LLM model and want to do only inference
using DeepSpeed? Is there an example code sample for it as well?

**Comment by tjruwase** [comment]
@AbhayGoyal, yes, the intel PRs would enable CPU inference. Please keep an eye on those. You can also ask questions directly on those PRs.

**Comment by loadams** [comment]
Hi @AbhayGoyal - closing this issue for now, since we've recommended the right way to follow up on, there are also CI tests linked.

If you have other questions, please open a new issue and link this one and we would be happy to answer it.
