### ISSUE TITLE
pip pre-built binary?

### ISSUE THREAD

**Issue by szha** [microsoft/DeepSpeed#613]
Hi,

A self-contained, pre-built binary would be very useful for adoption. From reading [advanced installation guide](https://github.com/microsoft/DeepSpeed/blame/master/docs/_tutorials/advanced-install.md#L121) from #496 it seems that pre-built binary in PyPI is planned for DeepSpeed. What's the plan for it?

Thanks,
Sheng

**Comment by loadams** [comment]
Hi @szha - this issue is quite old, but we provide binaries on PyPi now, closing this issue.  Let us know if you have any other questions, thanks!
