### ISSUE TITLE
1-bit Adam installation dependencies

### ISSUE THREAD

**Issue by g-karthik** [microsoft/DeepSpeed#614]
I want to try out 1-bit Adam, and I believe it requires some special installation that's present in the pre-built Docker image.

Could you please point me to the specific lines in the [Dockerfile](https://github.com/microsoft/DeepSpeed/blob/master/docker/Dockerfile) that would be needed for this feature?

I have my own custom Docker image in which I've been installing DeepSpeed from source, and I'd like to add the relevant lines directly to my Dockerfile.

**Comment by g-karthik** [comment]
@jeffra @tjruwase happy new year to you guys! Just bumping this back up your notifications!

**Comment by awan-10** [comment]
@g-karthik, happy new year! 

Do you want to try 1-bit Adam on a cluster with Ethernet or InfiniBand? If it is IB, then you need MVAPICH2 and I can share the specific lines you need to add to your Dockerfile. If it is Ethernet, there is nothing special that is needed and it shall just work with OpenMPI already included in the Dockerfile. Let me know and I will be happy to help you out.

**Comment by g-karthik** [comment]
Hi @awan-10 happy new year! Yes, my cluster is an InfiniBand cluster.

**Comment by awan-10** [comment]
@g-karthik -- please add the following lines to your Dockerfile and try it out. This is assuming CUDA 10.1. If you need another version of CUDA 10.1, please look at MVAPICH website for the right link. 

```
#### MVAPICH2
RUN apt update && sudo apt install alien -y
RUN wget http://mvapich.cse.ohio-state.edu/download/mvapich/gdr/2.3.5/mofed4.6/mvapich2-gdr-mcast.cuda10.1.mofed4.6.gnu7.5.0-2.3.5-1.el7.x86_64.rpm -P ${STAGE_DIR} && \
    cd ${STAGE_DIR} && \
    alien mvapich2-gdr-mcast.cuda10.1.mofed4.6.gnu7.5.0-2.3.5-1.el7.x86_64.rpm && \
    dpkg -i mvapich2-gdr-mcast.cuda10.1.mofed4.6.gnu7.5.0_2.3.5-2_amd64.deb && \
    ln -s /usr/bin/env /bin/env

ENV PATH=/opt/mvapich2/gdr/2.3.5/mcast/no-openacc/cuda10.1/mofed4.6/mpirun/gnu7.5.0/bin:${PATH}

ENV SAVE_LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/opt/mvapich2/gdr/2.3.5/mcast/no-openacc/cuda10.1/mofed4.6/mpirun/gnu7.5.0/lib64:${LD_LIBRARY_PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda-10.1/compat:/usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/:${SAVE_LD_LIBRARY_PATH}

RUN ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/libnvidia-ml.so /usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/libnvidia-ml.so.1

#RUN apt install libpciaccess-dev && \
RUN git clone https://github.com/mpi4py/mpi4py ${STAGE_DIR}/mpi4py && \
    cd ${STAGE_DIR}/mpi4py && \
    python setup.py build --mpicc=`which mpicc` && \
    python setup.py install

RUN ln -s /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
RUN unlink /usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/libnvidia-ml.so.1
ENV LD_LIBRARY_PATH=${SAVE_LD_LIBRARY_PATH}
```

**Comment by awan-10** [comment]
@g-karthik, did this work for you?

**Comment by g-karthik** [comment]
I'm trying to get my Docker image properly set up with libfabric at the
moment, so I didn't get to test this addition yet. Perhaps we can close
this until then, thanks for the detailed info though!

**Comment by awan-10** [comment]
You're welcome, @g-karthik. We can close this one for now. Feel free to reopen when you get to it.

**Comment by g-karthik** [comment]
Hi @awan-10 I was checking out [this](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/launcher/multinode_runner.py#L94) `mpirun` command underlying the deepspeed launcher, and I noticed that y'all don't assume InfiniBand by default (which makes sense).

Is there an equivalent `mpirun` command you'd recommend using with an InfiniBand cluster, with all the flags, etc.?
