### ISSUE TITLE
[user application] which deepspeed flags are required if any

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#616]
In the context of integrating DeepSpeed into transformers, I have a question to you wrt the deepspeed cl args

The paradigm you propose is:
```
deepspeed myprog myargs --deepspeed --deepspeed_config ds_config.js
```

but as we were discussing elsewhere there are too many cl args in ML apps, and we were considering if it might make sense to collapse `-deepspeed` and `--deepspeed_config` into a single cl arg for the transformers trainer and then re-construct it into 2 cl args before it goes into `deepspeed.initialize`.

context: https://github.com/huggingface/transformers/pull/9211#discussion_r546732810

Do you have a strong feeling that we should keep your proposed convention of 2 cl args facing users, or do you feel that it's fine to collapse the two? I may be just unaware of something important so I wanted to run this idea by you.

And secondly, do you by chance have any brilliant ideas on how to name a one-to-rule-them-all cl arg so that it reads nice and functionally unambiguous to users? I think `--deepspeed_config_file ds_config.js` isn't clear enough since it doesn't say deepspeed is activated, but I could be wrong.

One of devs also suggests that `--deepspeed_config` doesn't make it obvious that a file argument is expected.

I wonder if `--deepspeed ds_config.js` would do the trick - it's actually less obvious that it expects a file argument, but it's unambiguous about it activating deepspeed.

I totally understand that you may not have a strong opinion or want to spend any time on this since it's just our peculiar desire for succinctness and clarity, but if you do have suggestions I'm all ears.

Thank you.

**Comment by tjruwase** [comment]
Dropping `--deepspeed` is not a problem for DeepSpeed at all. As you can see [here](https://github.com/microsoft/DeepSpeed/blob/81aeea361da3936b875a678b9cb44596800510b5/deepspeed/__init__.py#L162), we added this flag as convenience for users to add a deepspeed code path to their existing code without having to write the associated parsing logic. It appears our good "intentions" has created a fair amount of confusion. So to clarify, `--deepspeed` flag is not a requirement for DeepSpeed engine.  Please let me know if does not work.

**Comment by stas00** [comment]
That's perfect. Thank you so much for clarifying this, @tjruwase - we will go with one cl arg then.

**Comment by tjruwase** [comment]
On the issue of handling config file argument, how about the following? Also I think this might address your other question about mismatches of cl and json clones of batch size related args.

The key observation to this proposal is that `--deepspeed_config`  is also not a requirement to DeepSpeed! Strange as it may sound, it is the reality. Also, it is possible that a few asserts might get fired with this approach because it is not well tested.

**Comment by stas00** [comment]
OK, as posted here: https://github.com/microsoft/DeepSpeed/issues/610#issuecomment-749871126 ideally we want to be able to use the config file as a base config and then to be able to augment what's not there and perhaps override.

So the ideal logic of configuration would be:

1. load config file if any defined in `args.deepspeed_config`
2. use `config_params` if any to override (1) (so here we could easily override or set the batch size arguments dynamically)

There are probably more nuances that I'm not aware about.

**Comment by stas00** [comment]
So reading your updated comment at https://github.com/microsoft/DeepSpeed/issues/616#issuecomment-750505646 do you propose that:

1. HF trainer 
   1. loads the json config file on its own, 
   2. converts it to dict 
   3. and then adjusts what it needs to adjust/add
   4. pass it as the `config_params` dict  
   
2. or would deepspeed support what I proposed in https://github.com/microsoft/DeepSpeed/issues/616#issuecomment-750534961 and then HF trainer can provide both the config file and the `config_params` dict to override/augment configuration?

I think we would prefer to stick to deepspeed convention of the config file since it'll make it easier for users who may be using your project elsewhere and we don't really want to create another huge set of cl args.

Everything else is loud and clear.  Thank you!

**Comment by g-karthik** [comment]
Hey @tjruwase @stas00 I use the `--deepspeed`, `--deepspeed_mpi` and `--deepspeed_config` flags when launching my train jobs with `mpirun` in a Kubernetes-based infrastructural setup. I do not use the `deepspeed` launcher. Seeing as you're referring to the removal of the `--deepspeed` flag, I presume you're also considering removing the `--deepspeed_mpi` flag.

I'd appreciate it if we could have discussions on breaking changes and loss of functionality in differing infrastructural setups as a result of flag removals. IMO, breaking changes to `deepspeed` for simplicity in `transformers` is okay until it leads to loss of functionality for some users.

**Comment by stas00** [comment]
@g-karthik, I think you may have understood the content of this thread. 

I was only asking for an advice of which flags would be best to used in HuggingFace `transformers` which will soon have DeepSpeed integrated.

I don't think there are any plans on removing support for flags in the DeepSpeed project itself.

Looking at the title of this Issue, I can see how you could have interpreted this - if you have suggestions to how I can rephrase it better please do let me know.

**Comment by tjruwase** [comment]
@g-karthik Thanks for eliciting this very important clarification regarding the discussion. Just to confirm, there are no breaking changes.
