### ISSUE TITLE
Does DeepSpeed currently support 3D parallelism for Megatron-LM?

### ISSUE THREAD

**Issue by kooyunmo** [microsoft/DeepSpeed#621]
Hi. I am trying to train GPT-2 with 3D parallelism described in [this link](https://www.deepspeed.ai/tutorials/pipeline/), but the only pipelined parallelism training example script provided in the repo is for AlexNet. Can I correctly train GPT-2 with 3D parallelism using the current DeepSpeed system (if I make a correct training script)? Or does DeepSpeed need a further system-level implementation to support 3D parallelism training for transformer-based models?

**Comment by loadams** [comment]
Hi @kooyunmo - the Megatron-DeepSpeed repo is significantly different than when you asked this question, so please see the updates there for the latest supported features.
