### ISSUE TITLE
[website] link to schedulers is broken

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#625]
https://www.deepspeed.ai/docs/config-json/#scheduler-parameters links to https://deepspeed.readthedocs.io/en/latest/deepspeed.pt.html which doesn't exist.

https://deepspeed.readthedocs.io itself doesn't have neither schedulers nor optimizers documented.

I derived from the source code that ds supports: LRRangeTest, OneCycle, WarmupLR, WarmupDecayLR

Thank you.

**Comment by stas00** [comment]
Would it be possible to fix that or at least tell me where that page is? 

I need to link to that hypothetical non-existing schedulers page from our integration docs.

Thank you!

@jeffra, @tjruwase?

**Comment by cli99** [comment]
https://github.com/microsoft/DeepSpeed/pull/799 fixes this.
