### ISSUE TITLE
fp16 config questions

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#634]
So in HF trainer we have 3 fp16 cl args. 
```
        fp16 (:obj:`bool`, `optional`, defaults to :obj:`False`):
            Whether to use 16-bit (mixed) precision training (through NVIDIA Apex) instead of 32-bit training.
        fp16_opt_level (:obj:`str`, `optional`, defaults to 'O1'):
            For :obj:`fp16` training, Apex AMP optimization level selected in ['O0', 'O1', 'O2', and 'O3']. See details
            on the `Apex documentation <https://nvidia.github.io/apex/amp.html>`__.
        fp16_backend (:obj:`str`, `optional`, defaults to :obj:`"auto"`):
            The backend to use for mixed precision training. Must be one of :obj:`"auto"`, :obj:`"amp"` or
            :obj:`"apex"`. :obj:`"auto"` will use AMP or APEX depending on the PyTorch version detected, while the
            other choices will force the requested backend.
```
I need help to know how to remap them to DS config

So looking at https://www.deepspeed.ai/docs/config-json/#fp16-training-options:
```
    "fp16": {
    "enabled": true,
    ...
    "opt_level": "O1",
    },
```

So the first 2 are straightforward.

What should I do about the backend? Do you not support the native pytorch amp? And if you do how does one tell DS whether to use apex or native amp?

But how do you get apex? I don't see you include apex in DeepSpeed, so does it use native amp if there is no apex and uses apex if it's installed? 

fwiw, it looks like apex is on its way out based on what I have been reading.

---------------------------------

and a related question:

If a user didn't supply the full `"fp16"` section in the config file, which defaults should we set on their behalf? As I explained above we only have those 3 options. And I see that the example shows:

```
    "fp16": {
        "enabled": true,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
```

Are those good defaults to use or perhaps these are the defaults if there aren't overridden by the user, so all I need to set is:

```
            config["fp16"] = {
                "enabled": True,
                "opt_level": args.fp16_opt_level,
            }
```
(plus sorting out the backend)

Thank you!

**Comment by tjruwase** [comment]
I have tried to distill specific questions, please let me know what I skipped

1. DS implements fp16 natively that roughly maps to amp opt_level = "02". 
2. DS does not support different opt_levels.
3. DS supports [amp](https://www.deepspeed.ai/docs/config-json/#automatic-mixed-precision-amp-training-options). 
4.  DS does not use apex.
5. Yes, those are the default fp16 options that are used when not specified by user.

**Comment by stas00** [comment]
> I have tried to distill specific questions

That's very helpful. Thank you!

I see I mixed amp and fp16 configs - my bad! Thank you for clarifying that, @tjruwase!

>     1. DS implements fp16 natively that roughly maps to amp opt_level = "02".

What would you recommend we do if a user passes opt_level=1 then? assert?

**Comment by tjruwase** [comment]
Actually, I used be more precise. You are right. DS delegates to apex for amp functionality, and user needs to install apex.

**Comment by stas00** [comment]
Oh, worry not, your support has been fantastic, @tjruwase. Thank you for the clarification!

**Comment by stas00** [comment]
found a little mismatch here, https://www.deepspeed.ai/docs/config-json/#fp16-training-options

The defaults are shown as:

```
fp16": {
    "enabled": true,
[...]
    "min_loss_scale": 1
}
```
but then later where each param is documented it goes:

```
min_loss_scale is  a fp16 parameter representing the minimum dynamic loss scale value. | 1000
```

So your example config doesn't match the default value for `min_loss_scale` (1 vs 1000). 

Perhaps, it doesn't have to match. But I noticed that all the other entries in the example are the same as defaults...

In any case I'm not going to pre-fill any of these and let the user to figure out the nuances, and will rely on the defaults instead.

**Comment by visionscaper** [comment]
Hello, I'm still confused about some details; is the "fp16" option using the native PyTorch AMP support (i.e. torch.cuda.amp)?
Is it using the autocast feature? Will your fp16 implementation work with any CUDA capable GPU?
