### ISSUE TITLE
how to restore a client_state from a saved checkpoint?

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#636]
According to this [doc](https://deepspeed.readthedocs.io/en/latest/model-checkpointing.html)

I can save a custom client_state:
```
 deepspeed.DeepSpeedEngine.save_checkpoint(self, save_dir, tag=None, client_state={}, save_latest=True)
```
but I don't see how to get it back:
```
deepspeed.DeepSpeedEngine.load_checkpoint(self, load_dir, tag=None, load_module_strict=True, load_optimizer_states=True, load_lr_scheduler_states=True)
```
What am I missing?

Unless it just calls `torch.save` behind the walls and then I just have to `torch.load` it manually. I guess the loader can't do anything with the client state since where would it put it. 

I trust I will see it in action tomorrow and it'll all become clear, I was just trying to understand the docs first before integrating it and was missing the counterpart.

Thank you!

**Comment by tjruwase** [comment]
load_checkpoint returns a [tuple ](https://github.com/microsoft/DeepSpeed/blob/46d2e2872b64ebccb8bf4eb5c8a3a55f9adaaa6c/deepspeed/runtime/engine.py#L1239-L1241) which includes the client state.

**Comment by stas00** [comment]
aha! that's why I failed to parse this sentence: 

> path of the loaded checkpoint. None if loading the checkpoint failed client_state: 

I couldn't make sense of "failed client_state".

It needs a dot and ideally a new line there, so it's easier to see that it returns 2 things. of course, best made into a bullet list like the incoming args.

Thank you, @tjruwase!

**Comment by tjruwase** [comment]
Actually, if you re-read that [doc link](https://deepspeed.readthedocs.io/en/latest/model-checkpointing.html) very carefully, **past the formatting mistakes :)**, you will see the following 


```
Returns:  Path of the loaded checkpoint. None if loading the checkpoint failed client_state: State dictionary used for loading required training states in the client code.
```
