### ISSUE TITLE
[BUG] How to manipulate the gradient during training

### ISSUE THREAD

**Issue by stonewst** [microsoft/DeepSpeed#6389]
**Describe the bug**
In some scenarios, it is necessary to customize the gradient of the parameters, such as modifying the gradient of some parameters. But in the deepspeed mode (especially z3), how to achieve this?

I notice that `safe_set_full_fp32_param` and `safe_set_full_optimizer_state` are supported. Could you support `safe_set_full_grad` as well?

**Expected behavior**
The gradient can be modified by any customed scheme during each training iteration.

**Comment by GuanhuaWang** [comment]
Hi @stonewst , thx for the feature request. 

Yes, we already have `safe_set_full_grad` and `safe_get_full_grad` in our latest branch now. You can imported as:

`from deepspeed.utils import safe_set_full_grad, safe_get_full_grad`

[Here](https://github.com/microsoft/DeepSpeed/blob/master/tests/unit/runtime/zero/test_zero_tensor_fragment.py#L201) is a simple example test code piece.
