### ISSUE TITLE
[REQUEST]Can we reload the model parameters after deepspeed.initialize?

### ISSUE THREAD

**Issue by obangw** [microsoft/DeepSpeed#6411]
Hello, I’m wondering if it’s possible to reload a model with new weights after `deepspeed.initialize`. During training with ZeRO3, I’d like to dynamically update the model’s weights with the one I want manually. For example, when training with a target module and a reference module, I want to substitute the weights of the reference module with the latest target module.

How can I achieve this? Thanks!

**Comment by tohtana** [comment]
Since we haven’t received any additional information, we’re closing this issue for now. Please feel free to reopen it if you have more details to share.
