### ISSUE TITLE
Can't building wheel for deepspeed

### ISSUE THREAD

**Issue by KhangLoveCat** [microsoft/DeepSpeed#6460]
[issue.txt](https://github.com/user-attachments/files/16797642/issue.txt)

**Comment by loadams** [comment]
Hi @KhangLoveCat - can you please share more information here?  The DeepSpeed version, information about your system, the commands you are running rather than linking a txt file?

**Comment by loadams** [comment]
Closing this for now, if you can provide more details, we can re-open.
