### ISSUE TITLE
Zero3 Partitioning Granularity

### ISSUE THREAD

**Issue by jeromeku** [microsoft/DeepSpeed#6469]
When using Zero-3, what is the equivalent of torch `FSDP`'s [auto-wrap policy](https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.FullyShardedDataParallel)?  

This policy lets users specify the bounds of each gathered unit.  I.e., one can specify that `transformer` blocks are treated as a single unit such that during the forwards / backwards passes an entire `transformer` block will be gathered at a time.

Reading the source of `partition_parameters`, my understanding is that each parameter is partitioned into a `ds_tensor` which represents each `gpu`'s "horizontal" slice of the param.  What determines how many of these params are gathered at a time "vertically"?  

E.g., if my model has 4 layers, with `sum(layer1.params + layer2.params + layer3.params) < layer4.params`, how can I gather `layer{1,2,3}` together as a unit and `layer4` as another unit during forward / backward?

**Comment by tohtana** [comment]
Hi @jeromeku ,

> one can specify that transformer blocks are treated as a single unit such that during the forwards / backwards passes an entire transformer block will be gathered at a time.

ZeRO3's leaf module should be able to do the same. You can find the example here:
https://github.com/microsoft/DeepSpeed/pull/5008#issuecomment-1910607845

**Comment by tohtana** [comment]
Since we haven’t received any additional information, we’re closing this issue for now. Please feel free to reopen it if you have more details to share.
