### ISSUE TITLE
requesting a new release and a doc review

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#648]
We are almost ready to merge the DeepSpeed integration into the HF trainer: https://github.com/huggingface/transformers/pull/9211

1. since the currently released package doesn't include the recent fixed required for the integration to work we ask if it'd be possible to make a new pypi release. This is the most important part of this request, since we instruct users to `pip install deepspeed`.

2. also if it's not too much trouble to have a quick peek at the initial doc that I wrote and perhaps make suggestions that would help HF users to have a better experience getting started with DeepSpeed. The idea behind that document is not to try to document DeepSpeed but to provide a way for users to discover it and redirect to your resources for everything they need. 

   It's the very first `.rst` file at https://github.com/huggingface/transformers/pull/9211/files, and you can skip over the short fairscale entry, which was there already, I just moved it so it appears as new.
   
   If you don't have the time, this is much less urgent, as we can easily improve that down the road, so the new release is the critical part.

Thank you very much for all of your awesome support!

**Comment by jeffra** [comment]
Regarding a new release, I was planning to push a new release today actually. Will update this thread when it's live.

**Comment by jeffra** [comment]
v0.3.10 should be live now on pypi: https://pypi.org/project/deepspeed/

**Comment by stas00** [comment]
Confirming that it works great! thank you very much for the speedy release, @jeffra!

**Comment by stas00** [comment]
Got some great feedback from @tjruwase - so I'll close this, but if others get a chance to read are integration doc please do! thank you!

**Comment by stas00** [comment]
btw, just noticed that you front page https://github.com/microsoft/DeepSpeed isn't getting updated with new releases: 
![snapshot](https://user-images.githubusercontent.com/10676103/104271198-2122a400-544f-11eb-8649-db649b7bc77d.png)
it shows 0.3.1 as the latest and Latest links to it, rather than 0.3.10

**Comment by jeffra** [comment]
Thanks for the ping on this, I believe this is because releases 0.3.2 -> 0.3.10 didn't have any release notes just tags and for some reason github doesn't show them there unless they have release notes. I've added release notes now for 0.3.10 and it seems to be showing okay.
