### ISSUE TITLE
[BUG] `GatheredParameters` resulting in NCCL mismatched collectives error

### ISSUE THREAD

**Issue by jeromeku** [microsoft/DeepSpeed#6492]
**Describe the bug**
I have constructed a ZeRO-3 model using `deepspeed.initialize`.

After initializing the model, I want to gather the parameters before training to log sharded metadata (basically what's stored in `ds_summary()`).  

To do this, I'm running `GatheredParameters(model.parameters())` on all ranks, then iterating through each parameter to collect the param  metadata:

```python
with deepspeed.zero.GatheredParameters(model.parameters()):
            for name, param in model.named_parameters():
                id_ = param.ds_id
                numel = param.numel()
                ds_numel = param.ds_numel
                shape = tuple(param.shape)
                ds_shape = tuple(param.ds_shape)
                requires_grad = param.requires_grad
                grad_shape = tuple(param.grad.shape) if param.grad is not None else None
                persist = param.ds_persist
                # active_sub_modules = param.ds_active_sub_modules
                ds_tensor_shape = tuple(param.ds_tensor.shape) if param.ds_tensor is not None else None

                print(f"{name=} {id_=} {numel=} {ds_numel=} {shape=} {ds_shape=} {requires_grad=} {grad_shape=} {persist=} {ds_tensor_shape=}")
```
However, this results in some variation of NCCL mismatched collective error, e.g.:
```
RuntimeError: Detected mismatch between collectives on ranks. Rank 1 is running collective: CollectiveFingerPrint(SequenceNumber=4, OpType=ALLREDUCE, TensorShape=[1], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))), but Rank 0 is running collective: CollectiveFingerPrint(SequenceNumber=0OpType=REDUCE).
```

When I remove the `GatheredParams` (skip logging sharded metadata), the program runs without issue.

I have tried placing barriers before and after the `GatheredParams` as well as gathering only a small set of the model parameters, no luck.

Also tried initializing the model using `zero.Init`, same error.

Are there caveats to using `GatheredParams` that I'm missing?

**Comment by tohtana** [comment]
@jeromeku Can you try [this example](https://github.com/tohtana/validate_zero) including `GatheredParameters`?

The fp16/bf16 path using mixed precision is not well maintained but I validated `deepspeed --num_gpus=2 compare_loss.py --use_torch_adam --dtype torch.float32 --zero_stage 3` works.

**Comment by tohtana** [comment]
Let me close this issue as we didn't have an activity for a while. Please feel free to reopen it when necessary.
