### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by helinyu** [microsoft/DeepSpeed#6499]
The Nightly CI for {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }} failed.
 正在生成代码
      已完成代码的生成
      running build_scripts
      creating build\scripts-3.10
      error: [Errno 2] No such file or directory: 'bin\\deepspeed.bat'

**Comment by loadams** [comment]
@helinyu - if this is a bug report, please do not use the CI failure template.  Please open a new issue and add your error.

**Comment by zn123** [comment]
How to fix it

**Comment by loadams** [comment]
Hi @zn123 - what error are you actually hitting?

**Comment by ransheng11** [comment]
> The Nightly CI for {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }} failed.{{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID '} 失败。 正在生成代码 已完成代码的生成 running build_scripts  运行 build_scripts creating build\scripts-3.10创建 build\scripts-3.10 error: [Errno 2] No such file or directory: 'bin\deepspeed.bat'错误：[Errno 2] 没有这样的文件或目录：'bin\deepspeed.bat'

你好请问你解决了吗，我也遇到类似的问题，我是error: [Errno 2] No such file or directory: 'bin/deepspeed'
