### ISSUE TITLE
Error while initializing multiple models

### ISSUE THREAD

**Issue by 1Konny** [microsoft/DeepSpeed#65]
Hi.

I'm trying to use deepspeed in my code with multiple models, but got an error like below. Do you have any idea to solve this issue? Thanks in advance.

```
  File "train_ds.py", line 98, in <module>
    solver = Solver(opt)
  File "/data2/1konny/svg/solver_ds.py", line 40, in __init__
    self.init_models_and_optimizers()
  File "/data2/1konny/svg/solver_ds.py", line 117, in init_models_and_optimizers
    self.decoder, self.decoder_optimizer, _, _ = ds.initialize(opt, model=decoder, model_parameters=decoder_params)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/__init__.py", line 87, in initialize
    collate_fn=collate_fn)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/pt/deepspeed_light.py", line 123, in __init__
    dist.init_process_group(backend="nccl")
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 372, in init_process_group
    raise RuntimeError("trying to initialize the default process group "
RuntimeError: trying to initialize the default process group twice!
```

ds_config.json
```
{
  "train_batch_size": 4,
  "gradient_accumulation_steps": 1,
  "steps_per_print": 1,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.0001,
      "max_grad_norm": 1.0,
      "betas": [
         0.9,
         0.999
       ]
    }
  }
}
```

command-line
```
deepspeed train_ds.py --deepspeed --deepspeed_config deepspeed_util/ds_config.json ...
```

code
```
training_data = load_dataset()
encoder_params = filter(lambda p: p.requires_grad, encoder.parameters())
decoder_params = filter(lambda p: p.requires_grad, decoder.parameters())
self.encoder, self.encoder_optim, train_loader, _ = deepspeed.initialize(opt, model=encoder, model_parameters=encoder_params, training_data=training_data)
self.decoder, self.decoder_optim, _, _ = deepspeed.initialize(opt, model=decoder, model_parameters=decoder_params)
```

**Comment by 1Konny** [comment]
Following a suggestion [here](https://github.com/ultralytics/yolov3/issues/255#issuecomment-514845470), I modified my code as below and the issue does not appear now, but I wonder this is fine.
```
training_data = load_dataset()
encoder_params = filter(lambda p: p.requires_grad, encoder.parameters())
decoder_params = filter(lambda p: p.requires_grad, decoder.parameters())
self.encoder, self.encoder_optim, train_loader, _ = deepspeed.initialize(opt, model=encoder, model_parameters=encoder_params, training_data=training_data)
dist.destroy_process_group()
self.decoder, self.decoder_optim, _, _ = deepspeed.initialize(opt, model=decoder, model_parameters=decoder_params)
dist.destroy_process_group()
```

Also, following [this tutorial](https://github.com/microsoft/DeepSpeed/blob/master/README.md#training), I changed my training code as below, which also throws as an error: `RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.`
```
loss = calculate_loss(output, target)
self.encoder.backward(loss)
self.decoder.backward(loss)
self.encoder.step()
self.decoder.step()
```

I couldn't find a way to set an option like `retrain_graph=True`, so now I changed my code as below and do not see any errors, but still wonder if this is the right way to use deepspeed. 
```
loss = calculate_loss(output, target)
loss.backward()
self.encoder.step()
self.decoder.step()
```

So I would greatly appreciate if you could provide us a tutorial when there are multiple models to be trained. Thanks!

**Comment by 1Konny** [comment]
sorry, but I find that `dist.destroy_process_group()` does not fix the first issue.
I added this line,  tested in a single-gpu setting and looked fine, but I just found that when I run the code in multi-gpu setting, the error `RuntimeError: trying to initialize the default process group twice!` still occurs. Any ideas?

**Comment by tjruwase** [comment]
>     raise RuntimeError("trying to initialize the default process group "
> RuntimeError: trying to initialize the default process group twice!

This error message suggests to me that nccl initialization had occurred earlier in your code before the first call to deepspeed.initialize(). Can you confirm that? If this is the case, can you try setting dist_init_required=False in all the deepspeed.initialize() calls?

**Comment by jeffra** [comment]
Hi @1Konny, have you tried anything further with this issue?

**Comment by 1Konny** [comment]
Hi all, sorry for the late response.

this initialization issue has been fixed in my case as I commented. I set `dist_init_required=True` when initializing the first model engine, and set `dist_init_required=False` for the rest. Now it works like a charm.

> I modified my code as below and the issue does not appear now, but I wonder this is fine.
> 
> ```
> training_data = load_dataset()
> encoder_params = filter(lambda p: p.requires_grad, encoder.parameters())
> decoder_params = filter(lambda p: p.requires_grad, decoder.parameters())
> self.encoder, self.encoder_optim, train_loader, _ = deepspeed.initialize(opt, model=encoder, model_parameters=encoder_params, training_data=training_data, dist_init_required=True)
> self.decoder, self.decoder_optim, _, _ = deepspeed.initialize(opt, model=decoder, model_parameters=decoder_params, dist_init_required=False)
> ```

when I set `dist_init_requires=False` in all deepspeed.initialize() calls, `raise RuntimeError("trying to initialize the default process group "` occurs since I conjecture there is no any other deepspeed.initialize() calls in my codes.
