### ISSUE TITLE
Training a 10B parameter GPT-2 model with Zero2 is much slower than expected

### ISSUE THREAD

**Issue by duzx16** [microsoft/DeepSpeed#650]
I am trying to reproduce the training of 10B model with 32 V100 GPUs following https://www.deepspeed.ai/tutorials/zero/. However, I find that it is much slower than expected. With `train_micro_batch_size_per_gpu=1`, it takes more than 40 seconds to go through a batch. The timer output is
```
time (ms) | forward: 207.71 | backward: 3509.10 | optimizer: 38738.77 | batch generator: 4.65 | data loader: 0.18
```
Obviously the Zero optimizer dominates the time cost. The issue does not exist for smaller models. For example, when I train a 2.6B model with Zero2 (`train_micro_batch_size_per_gpu=8`), the timer output is
```
time (ms) | forward: 435.93 | backward: 1830.95 | optimizer: 610.44 | batch generator: 1.17 | data loader: 0.19
```

**Comment by tjruwase** [comment]
@duzx16, can you please enable [wall clock breakdown](https://www.deepspeed.ai/docs/config-json/#logging) and report the output?

**Comment by duzx16** [comment]
@tjruwase Thank you. I switched to a GPU cluster with NVLink and the time of a batch drops to 18 seconds. The output with wall clock breakdown is
```
time (ms) | forward: 1370.73 | backward: 5053.64 | backward_inner: 5006.61 | backward_allreduce: 46.96 | step: 11437.30
time (ms) | forward_microstep: 1370.75 | backward_microstep: 5053.66 | backward_inner_microstep: 5006.62 | backward_allreduce_microstep: 46.98 | step_microstep: 11437.32
time (ms) | optimizer_gradients: 17.86 | optimizer_step: 15.67 | optimizer_allgather: 11391.31
```
The `allgather` operation dominates the time cost. Then I upgraded NCCL to 2.8.3 and the time of a batch drops to 9 seconds.
```
time (ms) | forward: 1288.45 | backward: 5159.90 | backward_inner: 5113.39 | backward_allreduce: 46.44 | step: 2953.98
time (ms) | forward_microstep: 1288.47 | backward_microstep: 5159.92 | backward_inner_microstep: 5113.42 | backward_allreduce_microstep: 46.46 | step_microstep: 2954.00
```
I think the issue has been resolved, although I don't know why the NVLink and the NCCL version matters so much.

**Comment by huqinghao** [comment]
@duzx16 hi, just wonder what days it take  to  train a 10B GPT-2 using 32 V100 GPUs
