### ISSUE TITLE
[BUG] No way to simply obtain optimizer state after training and w['optimizer'] is blank

### ISSUE THREAD

**Issue by ppalantir** [microsoft/DeepSpeed#6506]

**Comment by tohtana** [comment]
@ppalantir Unfortunately we don't have an API to extract optimizer states from a checkpoint.
I think you can use this API instead to save optimizer states separately.
https://deepspeed.readthedocs.io/en/latest/zero3.html#deepspeed.utils.safe_get_full_optimizer_state
