### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Swordfish1990** [microsoft/DeepSpeed#6534]
**Describe the bug**
When I use Transformers to train an embedding model with deepspeed zero2, I got this problem. 

**Traceback**
```python
[rank1]: Traceback (most recent call last):
[rank1]:   File "/root/miniconda3/envs/llama/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 513, in __getattr__
[rank1]:     return getattr(self, name)
[rank1]:   File "/root/miniconda3/envs/llama/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 513, in __getattr__
[rank1]:     return getattr(self, name)
[rank1]:   File "/root/miniconda3/envs/llama/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 513, in __getattr__
[rank1]:     return getattr(self, name)
[rank1]:   [Previous line repeated 195 more times]
[rank1]:   File "/root/miniconda3/envs/llama/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 512, in __getattr__
[rank1]:     if name in dir(self):
[rank1]:   File "/root/miniconda3/envs/llama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2543, in __dir__
[rank1]:     module_attrs = dir(self.__class__)
[rank1]: RecursionError: maximum recursion depth exceeded while calling a Python object
``` 
According to the traceback, it seems that the function 'getattr' was called too many times.

> [rank1]:   [Previous line repeated 195 more times]

The function getattr in engine.py fell into an infinite loop.

```python
def __getattr__(self, name):
        """
        Pass through attributes defined in the model if they are not overridden by ds-engine.
        """

        _module = {}
        if "module" in self.__dict__:
            _module = self.__dict__['module']
        if name in dir(self):
            return getattr(self, name)
        elif name in dir(_module):
            return getattr(_module, name)
        else:
            raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
``` 
I think maybe the Python interpreter treats __getattr__ and getattr as the same function, resulting in an infinite recursion.
How can I solve this problem?

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - GPU count and types [e.g. one machine with x4 P4s ]
 - Python version 3.10

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
Yes

**Docker context**
Are you using a specific docker image that you can share?
Not use docker

**Comment by tohtana** [comment]
Hi @Swordfish1990, the reason of the infinite recursion error in #4440 is the model is wrapped by both PyTorch's DataParallel and DeepSpeed. Can you validate that you are using only DeepSpeed?

**Comment by Swordfish1990** [comment]
@tohtana Yes, only Deepspeed. I am using SentenceTransformer with Deepspeed.
```python
args=SentenceTransformerTrainingArguments(     
output_dir='models/embed',     
num_train_epochs=2,     
warmup_ratio=0.05,     
bf16=True,     
batch_sampler=BatchSamplers.NO_DUPLICATES,    
eval_strategy='steps',     
eval_steps=100,     
save_strategy='steps',     
save_steps=100,     
save_total_limit=2,     
logging_steps=100,     
dataloader_drop_last=True,     
deepspeed='stage2_config.json',     
run_name=embedding_model_name+'-finetuning'
 )

model=SentenceTransformer('/workspace/Models/'+embedding_model_name)

trainer=SentenceTransformerTrainer(     
model=model,     
args=args,     
train_dataset=train_dataset,     
# eval_dataset=eval_dataset,     
loss=loss,     
evaluator=evaluator 
)

``` 

And the Deepspeed config is:

`

{
    "bfloat16": {
        "enabled": true
    },
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto"
        }
    },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "steps_per_print": 1e5
}
`

**Comment by tohtana** [comment]
Hi @Swordfish1990,

The [document](https://www.sbert.net/docs/package_reference/sentence_transformer/training_args.html) says you need to add `deepspeed` kwarg in `SentenceTransformerTrainingArguments`.

I made an [example](https://gist.github.com/tohtana/c8b66b90b7e3df91039a656c7b2a2c62) to enable deepspeed based on the [trainer's example](https://www.sbert.net/docs/sentence_transformer/training_overview.html#trainer) of Sequence Transformers.

I still needed to add this [commit](https://github.com/microsoft/DeepSpeed/commit/5c4b97f1092b798508dab4321b2ac79a9f554e72) to avoid converting input_ids and attention mask to fp16. After this change, the above example worked on my environment.

**Comment by tohtana** [comment]
Closing as we haven't had an activity for a while. The commit mentioned above is already in master.
