### ISSUE TITLE
[BUG] ACL stream synchronize failed, error  code 507015

### ISSUE THREAD

**Issue by janelu9** [microsoft/DeepSpeed#6555]
model llama3.1-8b
zero_stage=1
pipe_parallel_size=2
model_parallel_size=2
world_size = 16 npus

![image](https://github.com/user-attachments/assets/2dbd24ea-e750-42ed-ac4b-f370014b99a6)

The above error offen happens during training unpredictable if I use model parallel and zero1

**Comment by jomayeri** [comment]
@xuedinge233 & @hipudding

**Comment by hipudding** [comment]
Thanks for this bug report.

**Comment by loadams** [comment]
@hipudding - anything to add here?  Should we leave this open or close this?

**Comment by loadams** [comment]
@hipudding - let us know if we need to re-open this, otherwise closing for now since its not related to DeepSpeed

**Comment by hipudding** [comment]
@loadams Sorry for late reply, This is something wrong in torch_npu, and I think it's not relate to DeepSpeed. We will look into it. Please keep this issue as closed, Thanks.
