### ISSUE TITLE
[request] Install error on Windows

### ISSUE THREAD

**Issue by th10010** [microsoft/DeepSpeed#6563]
The Nightly CI for {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }} failed.
My computer is Windows. I have a project for stable diffusion, and its dependency is deepspeed. During the installation of deepspeed, an error message appears: python setup.py egg_info did not run successfully. How can I solve this problem?
![1](https://github.com/user-attachments/assets/9345d99d-0810-4ba9-81c6-34e68ebf941a)

**Comment by loadams** [comment]
Hi @th10010 - are you trying to use cmd.exe on Windows or WSL?  I cannot tell from your screenshot.

If you are using cmd.exe, be sure you are installing the Windows whl we publish now, which I don't see being installed, I see the linux whl being installed on your system.

**Comment by loadams** [comment]
@th10010 - closing due to no reply, please reply if you do see this and are still having issues, but this looks like you want to install the Windows version and are installing the Linux whl.
