### ISSUE TITLE
Undefined name: f --> bare except

### ISSUE THREAD

**Issue by cclauss** [microsoft/DeepSpeed#66]
https://github.com/microsoft/DeepSpeed/blob/master/tests/model/Megatron_GPT2/run_checkpoint_test.py#L113-L115

The variable `f` is an _undefined name_ in this context.  This will raise a NameError which will be caught by the [bare except](https://realpython.com/the-most-diabolical-python-antipattern) and `No old checkpoint` will be printed.  How should `f` be defined?

**Comment by ShadenSmith** [comment]
Hello! Thank you for reporting this. We submitted a quick fix and in the meantime I am working on the bare except that is another issue as you pointed out.

Thanks for catching this!
