### ISSUE TITLE
[BUG] Facing build error while comapiling FUSED_ADAM on ROCm

### ISSUE THREAD

**Issue by itej89** [microsoft/DeepSpeed#6600]
Hi, I would to report the below build error while compiling the DeepSpeech with Fused adam. Please let me know if any further information I can share to resolve this issue. Thanks you.

**Install command**
```
DS_BUILD_FUSED_ADAM=1 pip install .
```

**Error:** Log is huge so I've attached the file below
[failure_log.txt](https://github.com/user-attachments/files/17262422/failure_log.txt)

**Comment by jomayeri** [comment]
It looks like you already opened an issue about this topic. Please keep all information in the single issue.

**Comment by itej89** [comment]
> It looks like you already opened an issue about this topic. Please keep all information in the single issue.

This is a different error after applying my local patch to that.

**Comment by itej89** [comment]
> It looks like you already opened an issue about this topic. Please keep all information in the single issue.

This one is a different build error I've got after patching that issue with my resolution.

**Comment by jithunnair-amd** [comment]
@itej89 Both the issues have the same root cause: removal of the `shell=True` in the subprocess commands. This should also be fixed by https://github.com/microsoft/DeepSpeed/pull/6587. If it's not, please reopen the issue or commend and tag me and Jagadish (cc'ed below) here.

cc @jagadish-amd
