### ISSUE TITLE
[REQUEST] Could not install deepspeed successfully in NVIDIA L40S instance

### ISSUE THREAD

**Issue by xqun3** [microsoft/DeepSpeed#6608]
Could not install deepspeed successfully in NVIDIA L40S instance

## enviroment
CUDA Version: 12.4
python version: 3.12.7
torch version: 2.4.0+cu124

## install method
pip install deepspeed

## Screen shot
![image](https://github.com/user-attachments/assets/d41ffb94-30bd-420a-9682-3d8df54b812e)

**Comment by loadams** [comment]
@xqun3 - closing due to no reply, if you are able to, please try again with the latest DeepSpeed or share a full error log and I can investigate further..
