### ISSUE TITLE
when take --bind_cores_to_rank on，only half of CPUs is used

### ISSUE THREAD

**Issue by GensokyoLover** [microsoft/DeepSpeed#6629]
#!/bin/bash
NUM_NODES=1
NUM_GPUS=3
EXPERTS=3

deepspeed --num_nodes=${NUM_NODES}\
          --num_gpus=${NUM_GPUS} \
          --bind_cores_to_rank \
        train_autodirect_moe.py \
	--log-interval 100 \
	--noisy-gate-policy 'RSample' \
	--moe-param-group \
	--config ../configs/autoDirectFinal/XXX.json  \
	--gpus ${NUM_GPUS} \
	--lr 0.0003 \
	--clip 1.0 
this is my deepspeed sh，and when i take -bind_cores_to_rank on， only half of cpus is used
![Image](https://github.com/user-attachments/assets/4a244a61-044e-4392-9987-f3323d53ec97)

when take it off，all of cpus is used and it results in lower performance
![Image](https://github.com/user-attachments/assets/4b5ea223-78dc-494b-81bc-1bfdbe149a70)
is there anyway to control deepspeed to use more cpu？thanks

**Comment by jomayeri** [comment]
I'm unclear on the question. You have a scenario where it uses more CPU, what exactly are you looking for?

**Comment by GensokyoLover** [comment]
> I'm unclear on the question. You have a scenario where it uses more CPU, what exactly are you looking for?

thanks for your reply，now i found the lack of cpus resulted by the numactl which is used by deepspeed , and it can be overcame by adding ---bind_core_list in deepspeed sh.
