### ISSUE TITLE
[BUG] Deepspeed MoE Multi-GPU Expert-Parallel Training/Inference freezes when a process finishes generation first.

### ISSUE THREAD

**Issue by taehyunzzz** [microsoft/DeepSpeed#6634]
**Describe the bug**
I am using expert-parallel MoE implementation of Deepspeed-MoE for decoder model inference using Huggingface Trainer.
During inference, if the generation lengths of the evaluation dataset  distributed among the GPUs do not match,
one of the GPUs will finish the decoding inference for its batch, while the other GPU keeps running.

Because one of the GPU has finished the batch, it will not run.
The remaining running GPU will keep waiting for communication with the finished process.

Is there a way to deal with this other than feeding dummy inputs to the GPU that finishes early?
Forcing some generation lenghts could be a quick solution, too.
Has anyone dealt with this type of problem before?

**To Reproduce**
Run multi-gpu expert parallel inference without forcing any generation lengths

**Expected behavior**
Inference to run smoothly.

**ds_report output**
Don't think it's an issue with my environment, but here goes.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
evoformer_attn ......... [NO] ....... [OKAY]
fp_quantizer ........... [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
gds .................... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.4
 [WARNING]  using untested triton version (3.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]

**Screenshots**
![Image](https://github.com/user-attachments/assets/d128c3f0-eb36-4acd-a826-4bb6efbadc97)
![Image](https://github.com/user-attachments/assets/c5d169dd-bf35-49f0-829a-06fcc1e22d33)

**Comment by jomayeri** [comment]
Unfortunately different generation lengths will cause a communication deadlock in data parallel.
