### ISSUE TITLE
[BUG] if not install cuda，pip3 install deepspeed==0.14.0, failed in  installed_cuda_version()

### ISSUE THREAD

**Issue by hijeffwu** [microsoft/DeepSpeed#6636]
**Describe the bug**

not install cuda， and not cpu，gpu device.

pip3 install deepspeed==0.14.0， failed in  installed_cuda_version()

**To Reproduce**

not install cuda in sys,
pip3 install deepspeed==0.14.0

**Expected behavior**

**ds_report output**

 Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1kmwvije/deepspeed_6c20884bfa084655b99473b9abf58814/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1kmwvije/deepspeed_6c20884bfa084655b99473b9abf58814/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2j2fd59_
       cwd: /tmp/pip-install-1kmwvije/deepspeed_6c20884bfa084655b99473b9abf58814/
  Complete output (25 lines):
  [2024-10-17 08:56:34,510] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
.......................................
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-1kmwvije/deepspeed_6c20884bfa084655b99473b9abf58814/setup.py", line 100, in <module>
      cuda_major_ver, cuda_minor_ver = installed_cuda_version()
    File "/tmp/pip-install-1kmwvije/deepspeed_6c20884bfa084655b99473b9abf58814/op_builder/builder.py", line 50, in installed_cuda_version
      raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
  op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
  ----------------------------------------
..............................................................................

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by hijeffwu** [comment]
if torch.cuda.is_available():
    from op_builder.builder import installed_cuda_version

in setup.py

**Comment by yeshsurya** [comment]
Is there any reason you don't want to install cuda ? It would be needed.

**Comment by hijeffwu** [comment]
> Is there any reason you don't want to install cuda ? It would be needed.

We are not using NVIDIA hardware， deepspeed is working on a non-CUDA device with a non-cuda device plugin.

**Comment by tjruwase** [comment]
@hijeffwu, DeepSpeed works on non-cuda devices as reported here: https://github.com/microsoft/DeepSpeed?tab=readme-ov-file#contributed-hw-support

Can you do the following:
1. Share your installed torch version with `pip show torch`
2. Try latest deepspeed version `0.15.*`

**Comment by hijeffwu** [comment]
> [@hijeffwu](https://github.com/hijeffwu), DeepSpeed works on non-cuda devices as reported here: https://github.com/microsoft/DeepSpeed?tab=readme-ov-file#contributed-hw-support
> 
> Can you do the following:
> 
> 1. Share your installed torch version with `pip show torch`
> 2. Try latest deepspeed version `0.15.*`

Thanks @tjruwase , 0.15 ， build pass。
