### ISSUE TITLE
No module named 'op_builder'

### ISSUE THREAD

**Issue by hujiquan** [microsoft/DeepSpeed#6639]
deepspeed-0.15.2
AMD 5600x
Rtx 4060Ti

ERROR:
ModuleNotFoundError: No module named 'op_builder'

try install it ,but :
pip install op-builder
ERROR: Could not find a version that satisfies the requirement op-builder (from versions: none)
ERROR: No matching distribution found for op-builder

help!!!

**Comment by jomayeri** [comment]
op_builder is a module inside of deepspeed. Can you give the command you ran and the full error message?

**Comment by hujiquan** [comment]
G:\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts>pip3 install deepspeed
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting deepspeed
  Using cached https://mirrors.aliyun.com/pypi/packages/a2/f7/ecd834b9a02beef30104845a520c1d138e6e7398b0ed14e5d347f3c40486/deepspeed-0.15.2.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hujiquan\AppData\Local\Temp\pip-install-10936jam\deepspeed_9d819c49b4f14d149da1f9357021b332\setup.py", line 40, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
      ModuleNotFoundError: No module named 'op_builder'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

G:\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts>pip3 install op_builder
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement op_builder (from versions: none)
ERROR: No matching distribution found for op_builder

**Comment by hujiquan** [comment]
> op_builder is a module inside of deepspeed. Can you give the command you ran and the full error message?

G:\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts>pip3 install deepspeed
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting deepspeed
  Using cached https://mirrors.aliyun.com/pypi/packages/a2/f7/ecd834b9a02beef30104845a520c1d138e6e7398b0ed14e5d347f3c40486/deepspeed-0.15.2.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hujiquan\AppData\Local\Temp\pip-install-10936jam\deepspeed_9d819c49b4f14d149da1f9357021b332\setup.py", line 40, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
      ModuleNotFoundError: No module named 'op_builder'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

G:\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts>pip3 install op_builder
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement op_builder (from versions: none)
ERROR: No matching distribution found for op_builder

**Comment by numz** [comment]
Hi,
same here

**Comment by loadams** [comment]
Hi @numz and @hujiquan - it looks like you are both installing the linux whl based on the name of the whl.  To download the latest Windows whl we have published, please see the file listed here: 
deepspeed-0.15.0-cp311-cp311-win_amd64.whl on https://pypi.org/project/deepspeed/0.15.0/#files

If your system is not automatically picking this wheel, you will want to ensure you have the matching python version (3.11).

**Comment by loadams** [comment]
Hi @numz and @hujiquan - closing this issue for now.  If you are having issues with the Windows whl, please comment and we can follow up then.

**Comment by chrisirhc** [comment]
I'm seeing this same issue on a linux machine.

**Comment by loadams** [comment]
@chrisirhc - can you please share the full error log?  There is usually an error above this in the full log.

**Comment by chrisirhc** [comment]
Ack, created https://github.com/microsoft/DeepSpeed/issues/6716
