### ISSUE TITLE
OptimizedLinear, QuantizedParameter and FP_Quantizer behavior

### ISSUE THREAD

**Issue by oelayan7** [microsoft/DeepSpeed#6647]
In OptimizedLinear, two classes were introduced to be used inside of its implementation. I have a question about those classes behavior (the quantization to be specific)

In QuantizedParameter class, the quantization is always to uint8 as the dtype.
On the other hand, inside FP_Quantize class (which is a quantizer) it is handled as a float.  
Is this behavior ok (correctness wise)? i.e. Is it ok to use uint8 for fp8 tensors? 

Is this intended? Why uint8 was chosen? can it be generalized  (imho, it might be better if it was configurable)? 

BTW, I think it might be better if some documentation was added for the feature as well.

**Comment by loadams** [comment]
FYI @sfc-gh-reyazda and @sfc-gh-jrasley

**Comment by sfc-gh-reyazda** [comment]
Hi @oelayan7,

Sorry for the late reply here. You are right that there isn't sufficient documentation here.
The tensors are created using `uint8` to be compatible with different HW and we don't depend on any external library to support the FP8 format (such as PyTorch). However, the data is treated as fp8 internally when dequantizing to higher precision (i.e. BF16). You can find more information of the kernels for these conversions [here](https://github.com/microsoft/DeepSpeed/blob/master/csrc/fp_quantizer/fp_quantize.cu). By choosing this general way of representing this data you are able to use this format in different HWs (such as V100 and A100) without being worried of this format is support by the HW or not. We also added an [FP8 GeMM](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/ops/fp_quantizer/fp8_gemm.py) for this format using Triton which is in experimental mode and plan to release a much faster one using Cutlass.
Hope this clarifies this decision of choosing different format. 
Best,
Reza

**Comment by nelyahu** [comment]
> Hi [@oelayan7](https://github.com/oelayan7),
> 
> Sorry for the late reply here. You are right that there isn't sufficient documentation here. The tensors are created using `uint8` to be compatible with different HW and we don't depend on any external library to support the FP8 format (such as PyTorch). However, the data is treated as fp8 internally when dequantizing to higher precision (i.e. BF16). You can find more information of the kernels for these conversions [here](https://github.com/microsoft/DeepSpeed/blob/master/csrc/fp_quantizer/fp_quantize.cu). By choosing this general way of representing this data you are able to use this format in different HWs (such as V100 and A100) without being worried of this format is support by the HW or not. We also added an [FP8 GeMM](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/ops/fp_quantizer/fp8_gemm.py) for this format using Triton which is in experimental mode and plan to release a much faster one using Cutlass. Hope this clarifies this decision of choosing different format. Best, Reza

Hi @sfc-gh-reyazda , i can learn from your comment that current CUDA based implementation was targeting only NVIDIA HW, so uint8 is very specific to your use case and not so generic in a way that can be adapted to other platforms. 
Also, DeepSpeed is library designated to PyTorch, so it is not an "external library" it is the main library we rely on when executing, so allowing FP8 data type sounds more intuitive. 

Anyway, we are thinking on generalizing this code to allow this running on other accelerators besides V100 and A100, such as HPU, XPU and CPU. By using plain PyTorch implementation, if the accelerator does not support CUDA. 
Obviously for BWD compatibility we will keep current flow as default.

How does it sound?

**Comment by hwchen2017** [comment]
Hi @nelyahu, the current implementation is based on CUDA, but this method is generic and can be adapted on other platforms. It recovers the value of FP8 directly from the memory (or bits), and it will work even when Pytorch doesn't support FP8 data type. uint8_t has been supported by C++ and Pytorch for many years, while the support for FP8 is very limited. This makes uint8_t a more versatile choice.
