### ISSUE TITLE
How to benefit the most from ZeRO Offload on 1 GPU?

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#665]
Yesterday I got excited reading about DeepSpeed having gifts for us even on a single GPU. This is awesome since many users have just one GPU and if we could help them squeeze more onto their limited hardware. 

So I read https://www.deepspeed.ai/tutorials/zero-offload/ and after some trial and error (and some Issues filed) figured out what I needed to do.

I then managed to finetune the `t5-3b` `transformers` model on a single 24GB rtx-3090 GPU, which is unheard of. Wow! And thank you!

I documented my finding and the benchmarks here: https://github.com/huggingface/transformers/issues/8771#issuecomment-759176685

Here is the config I have used:

```
{
    "fp16": {
        "enabled": true,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },

    "zero_optimization": {
        "stage": 2,
       "allgather_partitions": true,
       "allgather_bucket_size": 2e8,
       "reduce_scatter": true,
       "reduce_bucket_size": 2e8,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "cpu_offload": true
    },

    "optimizer": {
        "type": "Adam",
        "params": {
            "adam_w_mode": true,
            "lr": 3e-5,
            "betas": [ 0.9, 0.999 ],
            "eps": 1e-8,
            "weight_decay": 3e-7
        }
    },

    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 3e-5,
            "warmup_num_steps": 500
        }
    }
}

```

I had to lower the ZeRO buffers from the default 5e8 to 2e8, otherwise it was OOM'ing even on BS=1.

Are there any recommendations on how to get even more out of it with 1 GPU?

It's very possible that I already squeezed the most of it, but I thought you'd ask if I have missed something

**Comment by samyam** [comment]
@stas00 All the work you have done in integrating DeepSpeed to HuggingFace is super cool. :) Thank you!

To squeeze more out of ZeRO Offload, I can think of two things:

1) Use the DeepSpeedCPUAdam Optimizer. Based on some of the other issues you have opened, seems like you might already be using it, or well on your way to trying it out. Using this optimizer should make a noticeable difference in performance, with the DeepSpeedCPUAdam being up to 5x faster than Torch CPU Adam.

2) Enabled DeepSpeed Activation Checkpointing. This is a bit more involved and requires changes in the model, but once you do that it can do two three things for you: 

i) it offers the same functionality as torch.utils.checkpoint to reduce your activation memory footprint, at the expense of 33% additional computation, 

ii) in presence of model parallelism, it can partition your activations to save more memory, and 

iii) it can offload the checkpointed activations to the CPU memory, greatly reducing the GPU memory requirement for activations.  

By combining ZeRO-Offload with deepspeed activation checkpoint with cpu offload, we have been able to train 13B parameter GPT-2 model on a 32GB V100 card.  

Resources and example of activation checkpoint:
https://www.deepspeed.ai/docs/config-json/#activation-checkpointing
https://www.deepspeed.ai/tutorials/megatron/#deepspeed-activation-checkpoints-optional
https://github.com/microsoft/DeepSpeedExamples/blob/2d4282b2062018c6862d8050cdd6bf793bec5f21/Megatron-LM/mpu/transformer.py#L411

**Comment by stas00** [comment]
Thank you very much, @samyam, for these suggestions.

Yes, I have already figured out `DeepSpeedCPUAdam` and it is fantastic!

So DeepSpeed Activation Checkpointing would probably good to look at next. 

I started compiling the list of other features to integrate/explore: https://github.com/huggingface/transformers/issues/9606
