### ISSUE TITLE
[BUG] Deepspeed launcher not picking up virtualenv --system-site-packages

### ISSUE THREAD

**Issue by VRehnberg** [microsoft/DeepSpeed#6664]
**Describe the bug**
`deepspeed` executable does not pick up packages installed in a `virtualenv --system-site-packages` even when regular python calls does. It only works if deepspeed is in the same virtualenvironment.

**To Reproduce**
1. Simple inference script to reproduce

```python
import sys
from dummy_pip_package.main import dummy
if __name__ == '__main__':
    sys.exit(dummy())
```
(this is a cleaned-up version of dummy-pip-package) 
4. What packages are required and their versions```
```bash
pip install deepspeed virtualenv
virtualenv --system-site-packages dummyvenv
source dummyvenv/bin/activate
pip install dummy-pip-package
```
5. How to run the script
```bash
deepspeed dummyvenv/bin/dummy-pip-package
```
7. ...**Expected behavior**A clear and concise description of what you expected to happen.
Not crashing, instead printing out one line of `OK` per launched process.

**ds_report output**
Please run `ds_report` to give us details about your setup.
```
[2024-10-24 12:14:08,537] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-10-24 12:14:08,544] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
deepspeed_not_implemented  [NO] ....... [OKAY]
deepspeed_ccl_comm ..... [NO] ....... [OKAY]
deepspeed_shm_comm ..... [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.10/dist-packages/torch']
torch version .................... 2.4.0a0+f70bd71a48.nv24.06
deepspeed install path ........... ['/usr/local/lib/python3.10/dist-packages/deepspeed']
deepspeed info ................... 0.15.2, unknown, unknown
deepspeed wheel compiled w. ...... torch 2.4 
shared memory (/dev/shm) size .... 125.51 GB
```
**Screenshots**

**System info (please complete the following information):**
 - OS: RockyLinux 8 and Ubuntu something (inside a container)
 - GPU count and types 4xA100, 2xT4, CPU-only
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version 3.10.12
 - Any other relevant info about your setup: first noticed with DeepSpeed installed as Lmod module (https://github.com/easybuilders/easybuild-easyconfigs/pull/21438) but confirmed that it also shows up when installing DeepSpeed on top-of [NGC PyTorch container](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-24-06.html)

**Docker context**
Are you using a specific docker image that you can share?

Apptainer
```
Bootstrap: docker
From: nvcr.io/nvidia/pytorch:24.06-py3

%post
    pip install virtualenv deepspeed
```
and then the virtualenv outside the container (or inside, doesn't matter)

**Additional context**

This would block most usage of DeepSpeed for any user on our cluster needing something outside the system installed packages. So not critical, but certainly annoying.

**Comment by VRehnberg** [comment]
Originally I thought it might have to do with some missing environment variable in `EXPORT_ENVS` https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/launcher/runner.py#L37 but not even adding the empty string to export the full environment solved the issue.

Any ideas for where to look would be helpful.

**Comment by VishalGawade1** [comment]
Hello @VRehnberg ,

This issue seems interesting. I think as a workaround, installing DeepSpeed inside the virtualenv solves the issue. Another idea might be tweaking the launcher to include system site-packages by adjusting environment variables like PYTHONPATH. Maybe one of these approaches could help make DeepSpeed more flexible with virtual environments?

I'm happy to help test any fixes or provide more details if needed :)

**Comment by VRehnberg** [comment]
> I think as a workaround, installing DeepSpeed inside the virtualenv solves the issue.
Yes, but then we can't provide DeepSpeed centrally and each user will have to have their own installation.

> Another idea might be tweaking the launcher to include system site-packages by adjusting environment variables like PYTHONPATH.
Hmm, yes there is something in this. This is a possible work-around:
```
PYTHONPATH=$(python -c 'import sys; print(":".join(sys.path))') deepspeed dummyvenv/bin/dummy-pip-package
```
don't know why this is needed, why is sys.path is different when launching Python via `deepspeed` compared to directly with `python`.

I will try to look into this.

**Comment by VRehnberg** [comment]
Ah, it was quite obvious in the end. The shebang in the `deepspeed` executable uses an absolute path to Python. It should be using `#!/usr/bin/env python`. Changing that or using
```
python $(which deepspeed) my_script.py
```
works.

Now I just need to figure out what to change in the build process.

**Comment by VRehnberg** [comment]
So the issue is (probably) coming from https://github.com/pypa/distutils/blob/main/distutils/command/build_scripts.py#L111-L117

Not sure what this means for DeepSpeed. Not seeing an easy way to patch this from DeepSpeed's side and there is a stable work-around. So if you feel like closing the issue I'd consider that acceptable.

**Comment by loadams** [comment]
Hi @VRehnberg - thanks for reporting this issue, I'll repro and take a look from our side.

Thanks @VishalGawade1 for your suggestions as well, I agree with @VRehnberg's thoughts, but it would be good to not need to work around this if we can

**Comment by loadams** [comment]
@VRehnberg - I've now read over the whole thread, everything you mentioned makes sense to me.  Though I'm not sure I follow your suggestions on what would need to be changed on the DeepSpeed side, could you elaborate more on that, even if it isn't easy?

**Comment by VRehnberg** [comment]
I didn't have anything specific in mind. Two things I can think of worth trying:

 - change to entry point console_scripts and see if that is handled correctly (I doubt it, bur worth trying)
 - use a post install hook to modify to revert the changed shebang
 - wrap the scripts as shell scripts

What should be done is file an issue with distutils or setuptools to make this handled upstream in the future.
