### ISSUE TITLE
[REQUEST] Support 8bit optimizer

### ISSUE THREAD

**Issue by fzyzcjy** [microsoft/DeepSpeed#6666]
Hi thanks for the library! It would be great if the AdamW cpu optimizer can have 8bit variant. For example, I would like to try adamw_8bit to full-finetune a 8B model on a 24GB GPU card (RTX4090). With deepspeed offload, the GPU memory is OK, but the CPU memory requirement is still very huge, partially because it uses normal adamw, thus needs 8x8=64GB for the optimizer itself. If we have 8bit adamw, then this part is reduced to 8x2=16GB.

**Comment by jomayeri** [comment]
If you are able please create a pull request for this enhancement and we will review it.

**Comment by fzyzcjy** [comment]
@jomayeri Thank you. Firstly, I would like to know whether this is reasonable (and not implemented simply because people did not have time doing that), or is it nonsense?

**Comment by jomayeri** [comment]
It is certainly reasonable and would be applicable in a finetuning scenario.

**Comment by jiosephlee** [comment]
@jomayeri I see that you marked this as completed; has this been implemented?
