### ISSUE TITLE
[REQUEST] The all-reduce overlap in ZeRO 1 and ZeRO 2

### ISSUE THREAD

**Issue by yingtongxiong** [microsoft/DeepSpeed#6685]
Hello, when I use DeepSpeed to train a GPT-Based Model by using zero1 or zero2, I found that there is no any overlap between all-reduce and backward computation. I don't know whether I set the config correctly, the following is my config

`{
    "train_batch_size": 8,
    "steps_per_print": 1,
    "gradient_accumulation_steps": 1,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.00015,
        }
    },
    "tensorboard": {
    "enabled": true,
    "output_path": "output/ds_logs/",
    "job_name": "train_internlm"
    },
    "bf16": {
        "enabled": true
    },
    "zero_optimization": {
        "stage": 1,
        "overlap_comm": true,
        "reduce_bucket_size": 536870912,
        "contiguous_gradients": false,
    }
}`
Then I profiled the kernel, the profiling results are the following
![Image](https://github.com/user-attachments/assets/eaa78abb-b61a-4ab4-b54a-16facd06e40f)

As the above figure, the all-reduce(which is in purple color) can not be overlapped with the backward. So I found out that the all-reduce is the function [allreduce_and_copy](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage_1_and_2.py#L1520), which has a  copy operation at the end of the function [here](https://github.com/microsoft/DeepSpeed/blob/9b7fc5452471392b0f58844219fcfdd14a9cdc77/deepspeed/runtime/zero/stage_1_and_2.py#L1545). 

![Image](https://github.com/user-attachments/assets/07c7bbb1-01fa-4230-aff0-2db21da76a31)
As we can see, it seems that these copy operation blocks the following backward. Therefore, can any body help me with this?

Aslo, I set the contiguous_gradients True, the all-reduce can overlap with backward
![Image](https://github.com/user-attachments/assets/5a157f1d-ecbb-4acd-9b07-006bd05c7c1e)

And there is no any copy operation. So I have some questions:
1. Does the copy operation in allreduce_and_copy can have effects in following backward computations, although they are in different stream?
2. It seems that the contiguous gradient could avoiding copy, but the avgsamples/sec doesn't increase.
3. What if I want to obtain the most efficient training performance in ZeRO1, how can I set the zero optimization config?

Looking forward to any replies.

**Comment by GuanhuaWang** [comment]
Hi @yingtongxiong ,

could you set your `contiguous_gradients` to true and profile the result again? I suspect because non-continuous memory region for gradients which leads to extra memcpy and no overlapping

**Comment by yingtongxiong** [comment]
> Hi [@yingtongxiong](https://github.com/yingtongxiong) ,
> 
> could you set your `contiguous_gradients` to `true` and profile the result again? I suspect because non-continuous memory region for gradients which leads to extra memcpy and no overlapping

Thanks for your reply. I have found the reason that I export the  CUDA_DEVICE_MAX_CONNECTIONS=1 environment variable, which cause no overlapping.

**Comment by GuanhuaWang** [comment]
Thanks for the update @yingtongxiong  close this issue for now.
