### ISSUE TITLE
Installing DeepSpeed in WSL.

### ISSUE THREAD

**Issue by anonymous-user803** [microsoft/DeepSpeed#6692]
I am using Windows 11. I have Windows Subsystem for Linux activated (Ubuntu) as well as installed CUDA, and Visual Studio C++ Build tools. I am trying to install deepspeed. However, I am getting the following 2 errors. Could anybody please help resolve this?

![Image](https://github.com/user-attachments/assets/cd4ae56a-5738-4cc5-bc1d-59db6be8a595)
![Image](https://github.com/user-attachments/assets/ffd310e3-e807-4371-b37d-96b8b0baa139)

**Comment by loadams** [comment]
Hi @anonymous-user803 - are you trying to install DeepSpeed in WSL or in Windows command prompt?  

Also can you please share the full error log as well as the command you used?  

From the error log I see that torch could not find cuda.  Could you please run these commands as well from the same venv/python env?

```
python -c "import torch; print('torch:', torch.__version__, torch)"
python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
```

**Comment by loadams** [comment]
Hi @anonymous-user803 - any updates on this?

**Comment by anonymous-user803** [comment]
@loadams 

I was trying using Git Bash, PowerShell as well as Command Prompt, neither worked. Then I tried using WSL, and it worked. Beyond this, I don't know for sure myself what I am trying to accomplish. I have been given some task by my research mentor.

**Comment by loadams** [comment]
Hi @anonymous-user803 - if you are installing PowerShell or Command Prompt, you would need to download and use the Windows whl we publish.  The most recently published one is [here](https://pypi.org/project/deepspeed/0.15.0/#files).  If you are able to use WSL for your project, you can install the Linux whl or build from source.  However, it depends which you want to use for your work.

**Comment by loadams** [comment]
Hi @anonymous-user803 - I'm going to close this issue now since you were able to install.  If you are still having issues, or need to install on Windows Command Prompt instead of WSL, please comment and we can help.
