### ISSUE TITLE
Clarification on Memory Representation in ZeRO Stages

### ISSUE THREAD

**Issue by yewentao256** [microsoft/DeepSpeed#6707]
The docs (https://deepspeed.readthedocs.io/en/latest/zero3.html) state ZeRO Stage 2 partitions 32-bit gradients

But the figure suggests both Stages 2 and 3 use FP16 (2Ψ) for gradients and parameters.

![Image](https://github.com/user-attachments/assets/f3d4e196-275d-4a65-83a9-0920418af00b)

Could you clarify what ZeRO Stage 2 really means for gradient partitioning? Does it refer to the FP32 gradients stored in the optimizer, the running FP16 gradients, or both?

Thanks for your help!

**Comment by jomayeri** [comment]
ZeRO stage 1 partitions the FP32 optimizer states. ZeRO stage 2 partitions the FP16 gradients. There is no stage 2 without stage 1, ie you can't partition the gradients without partitioning the optimizer states as well.

**Comment by yewentao256** [comment]
@jomayeri Thanks for clarifying! The partitioning of FP16 gradients in ZeRO Stage 2 makes sense to me. Would you like me to submit a PR to update the documentation accordingly?

The documentation currently states: "ZeRO Stage 2: The reduced 32-bit gradients for updating the model weights are also partitioned, so each process retains only the gradients corresponding to its portion of the optimizer states." (source: [ZeRO Stage 3 Documentation](https://deepspeed.readthedocs.io/en/latest/zero3.html))
