### ISSUE TITLE
[zero tutorial] unreadable image

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#675]
This tutorial https://www.deepspeed.ai/tutorials/zero/ has this image which gets scaled to fit the narrow width and as a result it gets rendered unreadable, here is a snapshot:
![snapshot_1](https://user-images.githubusercontent.com/10676103/104793947-9ba63900-5759-11eb-9f67-96921665e071.png)

The image is fine if I find a way to view its full size, which is 
https://www.deepspeed.ai/assets/images/oom_dp8_1.5B_log.png
but it's not clickable.

So either it needs to be made clickable, or perhaps the error can be just shown as code quote.

edit: it happens again later in the same tutorial.

-----------------

edit: very bottom of https://www.deepspeed.ai/tutorials/zero/ - prev/next navigation - there are more tutorials but [Next] is linking nowhere... you have added 3 more since then that can be seen in the menu on the left.

**Comment by tjruwase** [comment]
@stas00 Finally got around to this: #746. Can you please check if the images are better now?

**Comment by stas00** [comment]
It's impossible to tell until this is rendered on your website - but I see that you made them clickable, so that should do the trick I think.

Thank you for fixing that, @tjruwase

**Comment by tjruwase** [comment]
@stas00, I am reopening this to address the following issues

I have created PR #761 to address both issues. But below are the details. 

1) I presume you see an issue with the ZeRO-Offload [tutorial](https://www.deepspeed.ai/tutorials/zero-offload/)? Sorry, that was because I overlooked this tutorial and had only fixed the ZeRO [tutorial ](https://www.deepspeed.ai/tutorials/zero/). 

2) For the question below, the issue is a mismatch between the order of the menu on the left and the prev/next navigation. While the menu on the left is in arbitrary order (loosely creation order), the prev/next navigation is in alphabetical order. And so the ZeRO tutorials are rightfully the left ones on the prev/next navigation. I have tweaked the naming on the menu on the left to mitigate the mismatch. 
> edit: very bottom of https://www.deepspeed.ai/tutorials/zero/ - prev/next navigation - there are more tutorials but [Next] is linking nowhere... you have added 3 more since then that can be seen in the menu on the left.

**Comment by stas00** [comment]
>     1. I presume you see an issue with the ZeRO-Offload [tutorial](https://www.deepspeed.ai/tutorials/zero-offload/)? Sorry, that was because I overlooked this tutorial and had only fixed the ZeRO [tutorial ](https://www.deepspeed.ai/tutorials/zero/).

Aha, you're correct. I reported the other one, but thought it was that one instead. So your fix indeed worked and was online, I was just in the other tutorial and it looked similar so I mixed things up. Thank you for fixing this one too, @tjruwase 

>     2. For the question below, the issue is a mismatch between the order of the menu on the left and the prev/next navigation. While the menu on the left is in arbitrary order (loosely creation order), the prev/next navigation is in alphabetical order. And so the ZeRO tutorials are rightfully the left ones on the prev/next navigation. I have tweaked the naming on the menu on the left to mitigate the mismatch.

Excellent!

Well, unless there is a specific order to that tutorial sequence, might be easier to just remove prev/next since otherwise it's pointless - it doesn't even tell you what those previous / next ones are. Might as well, just replace them with "Find more tutorials in the menu". Just an idea of course.

**Comment by tjruwase** [comment]
@stas00  The PR is merged and ZeRO-Offload tutorial screenshots are now clickable. 

Regarding the prev/next buttons, I agree they are confusing in the circumstances.  Unfortunately, I don't have any better answers for now. But I will present the proposal to remove to the team. 

Please close this issue when appropriate or raise other issues. We really appreciate your help in identifying these doc problems.

**Comment by stas00** [comment]
Thank you, @tjruwase!

And please don't worry too much about prev/next - it's really a minor thing, especially now that you fixed it
