### ISSUE TITLE
Question about throughput numbers in blog post

### ISSUE THREAD

**Issue by rlanday** [microsoft/DeepSpeed#6781]
I'm currently reading through "DeepSpeed ZeRO++: A leap in speed for LLM and chat model training with 4X less communication":

https://www.microsoft.com/en-us/research/blog/deepspeed-zero-a-leap-in-speed-for-llm-and-chat-model-training-with-4x-less-communication/

Section "High efficiency with small batch per-GPU," subsection "High-bandwidth cluster" states:

> Figure 6: Throughput comparison of zero++ v.s. zero with 400 Gbps interconnect. Figure shows zero++ can achieve up to 1.56x speedup with 1k token per GPU, while achieving 1.41x speedup with 2k token per GPU.

> High-bandwidth cluster: As shown in Figure 6, we first show ZeRO++ throughput improvement over ZeRO for different model sizes and micro batch sizes with 400Gbps cross-node interconnects using 4x Infiniband (IB), each running at 100Gbps. With 1k token per GPU, ZeRO++ achieves 28% to 36% throughput improvement over ZeRO-3. For 2k micro batch sizes, ZeRO++ achieves 24% to 29% throughput gain over ZeRO-3.

Obviously 1.56x exceeds 28% to 36% and 1.41x exceeds 24% to 29%. I've been staring at this blog post and the paper for quite some time and can't make sense of this discrepancy. Is it possible to get some sort of clarification? Thanks!

**Comment by GuanhuaWang** [comment]
Hi @rlanday 

Thanks for the question. I think it is a typo on text. The text you quoted above is our throughput improvement numbers with 800 Gbps IBs (not 400Gbps IB as Figure 6). Later we changed the figure but did not update the text accordingly.
