### ISSUE TITLE
[BUG][IMPORTANT] zero_to_fp32.py consolidated weights are all zero after this commit

### ISSUE THREAD

**Issue by npuichigo** [microsoft/DeepSpeed#6791]
**Describe the bug**
After this commit https://github.com/microsoft/DeepSpeed/commit/dd40269426e129e6d65f8cda28d97f5ca31d1de0, specify `max_shard_size` to zero_to_fp32.py would generate empty weights

**To Reproduce**
Use deepspeed v0.16.0

**Reason**
According to the code https://github.com/microsoft/DeepSpeed/blob/f743feca033515fdded50a98093da5a48eb41e74/deepspeed/utils/zero_to_fp32.py#L513-L529, the state_dict is overrided instead of making a copy, that's why the original state_dict become empty

**Comment by npuichigo** [comment]
@xu-song @tjruwase @loadams

**Comment by xu-song** [comment]
How to reproduce your issue?

**Comment by npuichigo** [comment]
I think it will affect many models. Let's just see the code here, the state_dict passed in to `to_torch_tensor` is a shallow-copy. `state_dict[name] = torch.empty(tensor.shape, dtype=tensor.dtype) ` will override the original weights read from checkpoint.

**Comment by xu-song** [comment]
I got it

**Comment by loadams** [comment]
Thanks for identifying the bug @npuichigo and thanks for the quick fix @xu-song
