### ISSUE TITLE
[BUG] offload optmizer states in zero3

### ISSUE THREAD

**Issue by Hanqer** [microsoft/DeepSpeed#6833]
**Describe the bug**
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/engine.py#L3736  In offloading states of zero3 engine, the assertion  'self.zero_offload_param()' return a config class but not bool, why check it as not? 
'assert not self.zero_offload_param()' will always raise an error when the ds_config set as:

"offload_optimizer": {
            "device": "none"
}

**Comment by tohtana** [comment]
Good catch, thank you @Hanqer!
As long as I check the behaviors of DeepSpeed engine, it returns `None` when `offload_param` is not given. We need to cover the case the device for offloading is `none`. The same goes for offloading of optimizer states.

I submitted #6855 to address this issue. I would appreciate it if you could give us any feedback.

**Comment by tohtana** [comment]
Closing as #6855 resolved this.
