### ISSUE TITLE
Trained Model-Saving issue with DeepSpeed Zero-Stage 3

### ISSUE THREAD

**Issue by asifehmad** [microsoft/DeepSpeed#6836]
Hi, I am facing this model-saving issue with DeepSpeed Zero-Stage 3.

I am training a llama model using `deepspeed zero-stage 3`, the training goes well, but the model is not been saved properly in the checkpoints I have set, the model is around `3.2 B` occupies `~ 6 GiB` for `Tensor type BF16`, but is is been saved with size `138k Dec  7 19:54 model.safetensors`.

I have set the code as:

```
           # Save the model every `save_every_5K_steps`
            if step_count % save_every_5K_steps == 0:
                if accelerator.is_main_process:
                    accelerator.wait_for_everyone()
                    model.save_pretrained(step_checkpoint_dir, safe_serialization=True)
                    print(f"Model Saved at Step {step_count} to {step_checkpoint_dir}")
```

My deepspeed config file is:

```
[2024-12-07 19:26:52,746] [INFO] [config.py:989:print_user_config]   json = {
    "train_batch_size": 2,
    "train_micro_batch_size_per_gpu": 2,
    "gradient_accumulation_steps": 1,
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "nvme_path": null
        },
        "offload_param": {
            "device": "cpu",
            "nvme_path": null
        },
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "gradient_clipping": 1.0,
    "steps_per_print": inf,
    "bf16": {
        "enabled": true
    },
    "fp16": {
        "enabled": false
    },
    "zero_allow_untested_optimizer": true
}

```

I load the model as **torch_dtype=torch.bfloat16**.

**System info:**
 - OS: ubuntu22.04
 - GPU count and types: 1xA100
 - Python version: py3.11
 - PyTorch: torch==2.4.1+cu124
 - transformers==4.47.0
 - accelerate==1.2.0
 - deepspeed==0.16.1

**Launching Command**
accelerate launch script.py --config-commands

Any help would be appreciated, thanks!

**Comment by asifehmad** [comment]
For information, I tried unwrapping too but I still had the same issue:


```
if step_count % save_every_5K_steps == 0:
                if accelerator.is_main_process:
                    accelerator.wait_for_everyone()
                    unwrapped_model = accelerator.unwrap_model(model)
                    unwrapped_model.save_pretrained(step_checkpoint_dir, safe_serialization=True)
                    print(f"Model Saved at Step {step_count} to {step_checkpoint_dir}")
 

```

**Comment by asifehmad** [comment]
> [@asifehmad](https://github.com/asifehmad), with zero3, the checkpoint is partitioned across multiple files corresponding to the data parallelism degree. Can you please share directory listing of your checkpoint folder, something like `ls -lrt`?

Hi @tjruwase It doesn't save anything else other than one single `model.safetensor` related file to the model, and it is just `138k`. 

What I have found it directly doesn't support `save_pretrained()`.

**Comment by tjruwase** [comment]
> Hi [@tjruwase](https://github.com/tjruwase) It doesn't save anything else other than one single `model.safetensor` related file to the model, and it is just `138k`.

@asifehmad, this is very strange. Are you able to share a full repro?


> What I have found it directly doesn't support `save_pretrained()`.

Can you explain what this means and how you discovered this?

**Comment by asifehmad** [comment]
> > Hi [@tjruwase](https://github.com/tjruwase) It doesn't save anything else other than one single `model.safetensor` related file to the model, and it is just `138k`.
> 
> [@asifehmad](https://github.com/asifehmad), this is very strange. Are you able to share a full repro?
> 
> > What I have found it directly doesn't support `save_pretrained()`.
> 
> Can you explain what this means and how you discovered this?

For saving the trained model, it doesn't properly collect all the partitioned parts. Instead, I am now using `accelerator.save_state(checkpoint_model_dir)` and it now saves the model in pytorch `.bin` format, I then convert it to the `.safetensor`.
