### ISSUE TITLE
[REQUEST] Some questions about Domino

### ISSUE THREAD

**Issue by yingtongxiong** [microsoft/DeepSpeed#6858]
Hello I have some questions about the implementation of communication overlap in Domino. 
1. Forward: 
As the following figure shows:
![Image](https://github.com/user-attachments/assets/2506a25f-1d88-4c12-ad40-393ab58af54c)
The AllReduce(MLP1) should be overlapped with operations in next layer, however, I didn't find the relative code. In this [https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/domino/transformer.py#L428](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/domino/transformer.py#L428), which corresponds to the AllReduce(MLP1), I consider it is not overlapped. Maybe are there any extra consideration?
2. Backward:
As the following figure shows:
![Image](https://github.com/user-attachments/assets/a3a74627-9d80-4114-bf4e-ef1a14031199). It seems that I can't find any overlap code for AllReduce(attn1) and AllReduce(attn0) as in this code [https://github.com/microsoft/DeepSpeedExamples/blob/master/training/DeepSpeed-Domino/domino/tensor_parallel/partition.py#L302](https://github.com/microsoft/DeepSpeedExamples/blob/master/training/DeepSpeed-Domino/domino/tensor_parallel/partition.py#L302). I consider it only overlap the all-reduce of input_grad with the computation of weight_grad. 
3. The above questions are all about the row split on input, and I don't see any implementation for column split on weight. 

Can anyone help me with this? Thank you very much

**Comment by GuanhuaWang** [comment]
> Hello I have some questions about the implementation of communication overlap in Domino.
> 
> 1. Forward:
>    As the following figure shows:
>    ![Image](https://github.com/user-attachments/assets/2506a25f-1d88-4c12-ad40-393ab58af54c)
>    The AllReduce(MLP1) should be overlapped with operations in next layer, however, I didn't find the relative code. In this https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/domino/transformer.py#L428, which corresponds to the AllReduce(MLP1), I consider it is not overlapped. Maybe are there any extra consideration?
> 2. Backward:
>    As the following figure shows:
>    ![Image](https://github.com/user-attachments/assets/a3a74627-9d80-4114-bf4e-ef1a14031199). It seems that I can't find any overlap code for AllReduce(attn1) and AllReduce(attn0) as in this code https://github.com/microsoft/DeepSpeedExamples/blob/master/training/DeepSpeed-Domino/domino/tensor_parallel/partition.py#L302. I consider it only overlap the all-reduce of input_grad with the computation of weight_grad.
> 3. The above questions are all about the row split on input, and I don't see any implementation for column split on weight.
> 
> Can anyone help me with this? Thank you very much

Hi @yingtongxiong , thx for the detailed question! Really appreciate it!

For 1, our release version does not include overlap of AllReduce(MLP1) is for more general use cases. The key reason is a transformer block usually have to **Return all output** at the very end, which includes both u-batch0 and u-batch1 output return at same time. We have a prototype of next layer overlap and now working on using automatic codegen given user-defined transformer block implementation.

For 2, as we described in [our paper](https://arxiv.org/pdf/2409.15241) page 7, we use our newly defined _no-operation_ module (i.e., `no_oper` in code) to do overlap AllReduce(attn1) and AllReduce(attn0) in the backward. Code is [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/domino/transformer.py#L390C29-L390C36) and [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/domino/transformer.py#L403C29-L403C36)

For 3, we believe row-split on input is enough for most small model training (i.e. less than 30B or so). And we believe these small models are what our open-source community most focus one. For similar reason as this [issue](https://github.com/microsoft/DeepSpeed/issues/6605), we want to release only _Necessary_ features to our open-source community

Let me know if the above answers your questions. Also feel free to ping me at guanhuawang@microsoft.com if you are interested in our Domino project. We are now forming our small interest group for domino project and later on research lines.

**Comment by GoldenStain** [comment]
> > Hello I have some questions about the implementation of communication overlap in Domino.
> > 
> > 1. Forward:
> >    As the following figure shows:
> >    ![Image](https://github.com/user-attachments/assets/2506a25f-1d88-4c12-ad40-393ab58af54c)
> >    The AllReduce(MLP1) should be overlapped with operations in next layer, however, I didn't find the relative code. In this https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/domino/transformer.py#L428, which corresponds to the AllReduce(MLP1), I consider it is not overlapped. Maybe are there any extra consideration?
> > 2. Backward:
> >    As the following figure shows:
> >    ![Image](https://github.com/user-attachments/assets/a3a74627-9d80-4114-bf4e-ef1a14031199). It seems that I can't find any overlap code for AllReduce(attn1) and AllReduce(attn0) as in this code https://github.com/microsoft/DeepSpeedExamples/blob/master/training/DeepSpeed-Domino/domino/tensor_parallel/partition.py#L302. I consider it only overlap the all-reduce of input_grad with the computation of weight_grad.
> > 3. The above questions are all about the row split on input, and I don't see any implementation for column split on weight.
> > 
> > Can anyone help me with this? Thank you very much
> 
> Hi [@yingtongxiong](https://github.com/yingtongxiong) , thx for the detailed question! Really appreciate it!
> 
> For 1, our release version does not include overlap of AllReduce(MLP1) is for more general use cases. The key reason is a transformer block usually have to **Return all output** at the very end, which includes both u-batch0 and u-batch1 output return at same time. We have a prototype of next layer overlap and now working on using automatic codegen given user-defined transformer block implementation.
> 
> For 2, as we described in [our paper](https://arxiv.org/pdf/2409.15241) page 7, we use our newly defined _no-operation_ module (i.e., `no_oper` in code) to do overlap AllReduce(attn1) and AllReduce(attn0) in the backward. Code is [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/domino/transformer.py#L390C29-L390C36) and [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/domino/transformer.py#L403C29-L403C36)
> 
> For 3, we believe row-split on input is enough for most small model training (i.e. less than 30B or so). And we believe these small models are what our open-source community most focus one. For similar reason as this [issue](https://github.com/microsoft/DeepSpeed/issues/6605), we want to release only _Necessary_ features to our open-source community
> 
> Let me know if the above answers your questions. Also feel free to ping me at [guanhuawang@microsoft.com](mailto:guanhuawang@microsoft.com) if you are interested in our Domino project. We are now forming our small interest group for domino project and later on research lines.

I have thoroughly reviewed your code and noticed that in DominoTransformerLayer.forward(), you make extensive use of dist.all_reduce. However, to my knowledge, it does not have a corresponding backward implementation. Could you explain why the results are still correct?
