### ISSUE TITLE
Unable to Install DeepSpeed on Windows using pip

### ISSUE THREAD

**Issue by H4CK3R-5M4CK3R** [microsoft/DeepSpeed#6865]
Hello,

I am facing an issue while trying to install DeepSpeed on a Windows machine using `pip`. I have followed the installation instructions carefully, including installing the necessary dependencies, but I am encountering errors during the installation.

**System Specifications**:
- **OS**: Windows 10 (64-bit)
- **Python Version**: 3.9.6
- **PyTorch Version**: 2.5.1
- **CUDA Version**: 12.6
- **CUDA Driver**: nvcc version 12.6.85
- **Visual Studio**: Visual C++ Build Tools (installed as per the instructions)
- **DeepSpeed Installation**: Installed via `.whl` file since `pip install deepspeed` didn't work

**Steps Taken**:
1. Installed Python 3.9.6 and PyTorch 2.5.1 using `pip`.
2. Installed CUDA version 12.6 and verified the `nvcc` command works correctly.
3. Installed Visual C++ Build Tools and ensured that `cl` and other necessary components are available.
4. Attempted to install DeepSpeed using `pip install deepspeed`, but encountered the error.
5. As `pip install` wasn't working, I downloaded and installed DeepSpeed using the `.whl` file that matched my CUDA version but its not working either when i import it it shows errors.

**Error Message**:  
```
pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.16.1.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      [2024-12-14 01:52:07,089] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-12-14 01:52:07,100] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      [2024-12-14 01:52:08,091] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-12-14 01:52:08,094] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\pryan\AppData\Local\Temp\pip-install-7evsvyl5\deepspeed_1ed4e80276ba424e947cc565c335309d\setup.py", line 209, in <module>
          result = subprocess.check_output(git_hash_cmd)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pryan\miniconda3\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pryan\miniconda3\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pryan\miniconda3\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\pryan\miniconda3\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  Skip pre-compile of incompatible async_io; One can disable async_io with DS_BUILD_AIO=0
      Install Ops={'deepspeed_not_implemented': 1, 'async_io': False, 'deepspeed_ccl_comm': 1, 'deepspeed_shm_comm': 1, 'cpu_adam': 1, 'fused_adam': 1}
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

And here is Torch Cuda verification Output

```
>>> import torch
>>> torch.cuda.is_available()
True
>>>
```

**Comment by loadams** [comment]
Hi @H4CK3R-5M4CK3R - the reason for this is that we haven't published the latest version of DeepSpeed for Windows yet.  The most up to date Windows whl is version 0.15.0 (shown in files here: https://pypi.org/project/deepspeed/0.15.0/#files)

We are working on getting this pipeline fixed so we will publish Windows whls of newer versions too but aren't there yet.

This whl is also only built with python 3.11, so you'd need to have that, and I see from your information you're using python 3.9.

**Comment by loadams** [comment]
Hi @H4CK3R-5M4CK3R - following up on this, have you had a chance to try the above comment?

**Comment by loadams** [comment]
@H4CK3R-5M4CK3R - closing this issue for now.  If you come back to this and have follow up questions, please comment and we can re-open this.

**Comment by Kallamamran** [comment]
So installing Python 3.11 and DeepSpeed 0.15.0 should solve it then? 🤨

**Comment by loadams** [comment]
@Kallamamran yes, that will allow you to install the latest DeepSpeed whl we published that is built and tested on Windows.  We are working on getting more recent versions and more python support, but this is the best way to use that whl currently.

**Comment by Kallamamran** [comment]
It should really say on PyPi what version of Python is required

![Image](https://github.com/user-attachments/assets/d3ae44d9-3fd7-4210-8769-c09c187718d7)

It says a lot of Python versions, but according to this comment I guess that's not correct? 🤔😊

**Comment by loadams** [comment]
@Kallamamran - thanks for including this link, we should update this as certain parts of this are out of date.  

For the specific page, the python version is tagged in the Windows version specifically:

![Image](https://github.com/user-attachments/assets/27e7a99d-1a38-4620-925c-c7edcdfb9226)

But this is a good reminder to update this page as we being publishing more Windows whls.

**Comment by githendumukiri** [comment]
so deep speed will not work for windows?

**Comment by loadams** [comment]
> so deep speed will not work for windows?

Hi @githendumukiri - DeepSpeed runs on Windows in the following ways:

1) DeepSpeed whls for Windows are published for a few previous versions, 0.14.5 and 0.15.0 currently.  These contain all ops that support Windows pre-compiled. As a result of this, you'll need to use the same python version (3.11) and cuda major version (12).  You can also currently build the master branch locally if desired.  We are in the process of publishing whls for more recent DeepSpeed versions as well as for different python versions.
2) DeepSpeed can be run on Windows using [WSL](https://learn.microsoft.com/en-us/windows/wsl/) and then installed via building from source or installing any of the recent versions via pip.

**Comment by qinghai5060** [comment]
hi, my PC **has no GPU**, occured errors when install below:

```
PS D:\source_project> pip install deepspeed
Looking in indexes: https://mirrors.xxx.com/pypi/simple
Collecting deepspeed
  Downloading https://mirrors.xxx.com/pypi/packages/38/10/a7f63e086c1e1c12e290c98363c748ef5ddd6313fde739d2aeccd5ed0cd4/deepspeed-0.17.1.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 8.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      [2025-06-10 15:30:02,171] [WARNING] [real_accelerator.py:209:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2025-06-10 15:30:02,175] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      [2025-06-10 15:30:02,460] [WARNING] [real_accelerator.py:209:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2025-06-10 15:30:02,464] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 35, in <module>
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-vdfaqmdk\deepspeed_c9444406794a45c1ab56032da6101324\setup.py", line 210, in <module>
          result = subprocess.check_output(git_hash_cmd)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\miniconda3\envs\vita-a\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\miniconda3\envs\vita-a\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\miniconda3\envs\vita-a\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "D:\miniconda3\envs\vita-a\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  Skip pre-compile of incompatible async_io; One can disable async_io with DS_BUILD_AIO=0
      Install Ops={'deepspeed_not_implemented': 1, 'async_io': False, 'deepspeed_ccl_comm': 1, 'deepspeed_shm_comm': 1, 'cpu_adam': 1, 'fused_adam': 1}
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by loadams** [comment]
@qinghai5060 - this is because the most recent whls have not been built with Windows support.  Can you please try to install a previous wheel, `pip install deepspeed==0.16.4` and see if that works for you?  We will work on fixing our windows whl build flow for recent releases.

**Comment by dungdo123** [comment]
deepspeed==0.16.4 and python3.10 worked well!
