### ISSUE TITLE
Is there a clerical error in paper  《ZeRO-Offload: Democratizing Billion-Scale Model Training》?

### ISSUE THREAD

**Issue by zhiyongLiu1114** [microsoft/DeepSpeed#698]
![image](https://user-images.githubusercontent.com/47651345/105931164-ac25b000-6085-11eb-8308-0d08dbf2203a.png)
In Paper 《ZeRO-Offload: Democratizing Billion-Scale Model Training》, I saw that Figure 3: ZeRO-Offload training process on a single GPU has two GPU->CPU. should the p swap‘s GPU->CPU be CPU->GPU?

**Comment by minjiazhang** [comment]
Hi zhiyongLiu1114,

Thank you for point it out! Yes, the second "GPU->CPU" for p swap should be "CPU->GPU" instead. The figure was labeled correctly when we first published the ZeRO-Offload figure here "https://www.microsoft.com/en-us/research/blog/deepspeed-extreme-scale-model-training-for-everyone/", but we might accidentally put the wrong label when formatting the figure for the technical report.  We will fix it in a later version. 

Best,
Minjia

**Comment by minjiazhang** [comment]
Hi zhiyongLiu1114,

Thank you for point it out! Yes, the second "GPU->CPU" for p swap should be "CPU->GPU" instead. The updated parameters are swapped back from CPU to GPU for the next round of fw/bw computation. The figure was labeled correctly when we first published the ZeRO-Offload figure here "https://www.microsoft.com/en-us/research/blog/deepspeed-extreme-scale-model-training-for-everyone/", but we might accidentally put the wrong label when formatting the figure for the technical report. We will fix it in a later version.

Best,
Minjia

**Comment by HanGuo97** [comment]
Thanks for the great work! To follow up, is there a typo in Table 1 as well? Notably, the last row's memory is supposed to be `2M` instead of `4M`? Thanks!
