### ISSUE TITLE
how Can I enable pdb?

### ISSUE THREAD

**Issue by world2vec** [microsoft/DeepSpeed#703]
Hi,  
Normally I can enable pdb by:
```python -m pdb train.py```
now with deepspeed command:
```deepspeed train.py```
How can i enable the same as python?
Also how to enable it for pycharm?

**Comment by duchengyao** [comment]
+1

**Comment by loadams** [comment]
You should be able to do this via `import pdb` and then calling `pdb.set_trace()` inside the function or part of code you would like to have a breakpoint in.
