### ISSUE TITLE
Slow backward pass

### ISSUE THREAD

**Issue by e-sha** [microsoft/DeepSpeed#706]
I adapted bing_bert training for my purposes. I didn't change any files in turing or nvidia folders. I got very slow backward pass for deepspeed transformer kernel.
A hash of the git commit that I use is d720fdb6857f4b71d922ca1e8efbe5271b5fb7c2 (Oct 20 2020)
I got the following training profile with torch.autograd.profiler
![Screenshot from 2021-01-28 16-59-40](https://user-images.githubusercontent.com/6618622/106148614-4cfd9380-618a-11eb-9acc-6985dbf7e362.png)
Here forward pass is depicted in green and blue corresponds to backward pass.
I wonder why do some of the transformer kernels performs backward pass much slower backward than others?
Is there any way to look inside the profile of the backward pass of the transformer kernel?

The complete profile is here
[tracefile_0.zip](https://github.com/microsoft/DeepSpeed/files/5887830/tracefile_0.zip)

P.S. I don't use any of these flags
```
--normalize_invertible 
--attention_dropout_checkpoint 
--gelu_checkpoint 
--stochastic_mode 
```

**Comment by RezaYazdaniAminabadi** [comment]
Hi @e-sha 

Thanks for sending the profile. I will take a look at it. May I ask which model config (batch, hidden, sequence, heads), you are using here?
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
Another thing, I noticed in this profile is that only 2 backwards have very high latency and the rest are efficient. The strange this is that before both of these two there is some stall in which nothing is running. Could you please see if something is actually running at those places!? Also, I can test this on my side if you can provide me some script/configuration files?
Thanks,
Reza

**Comment by e-sha** [comment]
> Hi @e-sha
> 
> Thanks for sending the profile. I will take a look at it. May I ask which model config (batch, hidden, sequence, heads), you are using here?
> Thanks,
> Reza

This is a config of my model. I train the model on a host with 8 V100 GPUs.
```
{
   "attention_probs_dropout_prob": 0.1,
   "hidden_act": "gelu",
   "hidden_dropout_prob": 0.1,
   "hidden_size": 2048,
   "initializer_range": 0.02,
   "intermediate_size": 8192,
   "max_position_embeddings": 512,
   "num_attention_heads": 32,
   "num_hidden_layers": 24,
   "type_vocab_size": 10,
   "vocab_size_or_config_json_file": 103296
}
```
I also tried nvtx profiler and found two ncclAllReduceRingLLKernel_sum_fp16 kernels inside backward pass.
![Screenshot from 2021-02-01 08-25-22](https://user-images.githubusercontent.com/6618622/106452329-c520cd80-6498-11eb-9257-14bc46955ab8.png)

These operations are preceded and are the part of these ones
```{'kShortName': 'CatArrayBatchedCopy', 'kDuration': 4023862, 'layer': [], 'trace': [], 'reprMarker    s': [], 'marker': [], 'seqMarker': [], 'seqId': [], 'subSeqId': 0, 'altSeqId': [], 'dir': 'fprop'    , 'mod': ['na'], 'op': [], 'tid': 2916132608, 'device': 6, 'stream': 7, 'grid': (160, 127, 1), 'b    lock': (512, 1, 1), 'kLongName': 'void at::native::(anonymous namespace)::CatArrayBatchedCopy<c10    ::Half, unsigned int, 1>(c10::Half*, at::native::(anonymous namespace)::CatArrInputTensor<c10::Ha    lf, unsigned int>*, at::native::(anonymous namespace)::OutputTensorSizeStride<unsigned int, 4u>,     int, unsigned int)'}```
```{'kShortName': 'CatArrayBatchedCopy', 'kDuration': 3199038, 'layer': [], 'trace': [], 'reprMarker    s': [], 'marker': [], 'seqMarker': [], 'seqId': [], 'subSeqId': 0, 'altSeqId': [], 'dir': 'fprop'    , 'mod': ['na'], 'op': [], 'tid': 2916132608, 'device': 6, 'stream': 7, 'grid': (160, 119, 1), 'b    lock': (512, 1, 1), 'kLongName': 'void at::native::(anonymous namespace)::CatArrayBatchedCopy<c10    ::Half, unsigned int, 1>(c10::Half*, at::native::(anonymous namespace)::CatArrInputTensor<c10::Ha    lf, unsigned int>*, at::native::(anonymous namespace)::OutputTensorSizeStride<unsigned int, 4u>,     int, unsigned int)'}```

But I cannot understand from which place they came.

**Comment by e-sha** [comment]
More detailed analysis reveals that it is a part of this branch
from 
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage2.py#L594
to 
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage2.py#L1070

**Comment by e-sha** [comment]
It seems like a correct behaviour, but the profiler depicts it in a strange way.
