### ISSUE TITLE
NAN with binary cross entropy

### ISSUE THREAD

**Issue by benywon** [microsoft/DeepSpeed#715]
Hi, Recently I use ds to train a binary classifier. And only to find that the model always gets NAN after training some epochs. The model is based on BERT. Previously, I use the Nvidia apex O2 mode to train the model and without any issue. But when I switch to ds without any code modification, the model seems very stable.
PS: I have to turn on fp16=True and zero2 so that the model can fit the memory.

Thanks for your help!

**Comment by loadams** [comment]
Hi @benywon - this issue is fairly old, but if you are still hitting this issue, please re-open it and we would need repro steps in order to debug this on our side.

Thanks!
