### ISSUE TITLE
When can we expect the 3D parallelism release to be public?

### ISSUE THREAD

**Issue by sdtblck** [microsoft/DeepSpeed#717]
I've seen a few PRs relating to the 3D parallelism, and it seems Pipeline Parallelism has been quietly integrated into Nvidia's Megatron - when can we expect the 3D parallelism release in Deepspeed to be public?

**Comment by gongjingcs** [comment]
same question，could you provide a demo using Pipeline Parallelism likes bing bert , Thanks
