### ISSUE TITLE
docker sparse attention

### ISSUE THREAD

**Issue by irugina** [microsoft/DeepSpeed#725]
Hi, 

I wanted to install deepspeed for the sparse attention support and first tried to do pip install - which ran into the error here https://github.com/microsoft/DeepSpeed/issues/471. OP's solution did not work for me though. 

I then tried to use the docker image which raises ModuleNotFoundError: No module named 'deepspeed.ops.sparse_attention.cpp_utils'. 

Could you please point me to any solutions in either direction (i am assuming docker would probably be easier to fix)? 

Thank you!

**Comment by arashashari** [comment]
Please try following steps and report on the results. Also I would like to know your environment (tools versions) better (Cuda, Torch, LLVM, Triton, Python).
apt-get install llvm-9-dev
pip install cmake
pip install ninja
pip install triton=0.2.3
(get DeepSpeed and install manually)
cd DeepSpeed
export DS_BUILD_SPARSE_ATTN=1
bash install.sh -s

**Comment by irugina** [comment]
This did it, thank you!!
