### ISSUE TITLE
python-only-version

### ISSUE THREAD

**Issue by ConnollyLeon** [microsoft/DeepSpeed#729]
We're currently testing a python-only version of DeepSpeed that disables the cuda/cpp requirements for this case (Lamb and FusedAdam are not supported in this mode). Feel free and give it a try as a preview here: https://github.com/microsoft/DeepSpeed/tree/jeffra/python_only_version

HI, @jeffra I wonder where this version is. Or is there is a cpu-only version with c++?

**Comment by loadams** [comment]
Closing this issue as it is stale and the linked branch is not up to date with the current master branch.
