### ISSUE TITLE
Pip install support

### ISSUE THREAD

**Issue by jimdowling** [microsoft/DeepSpeed#73]
Hi. I looked at the install.sh file, and it looks like pip installation support is doable. It would be great before somebody nabs the pypi deepspeed module name.

**Comment by ShadenSmith** [comment]
This is a great idea and something we are evaluating now. Our initial hesitation comes from our various C++/CUDA dependencies which are [problematic](https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472) with PyPI. It's not something I am very knowledgeable about yet, so any feedback is appreciated on a good direction.

**Comment by jimdowling** [comment]
Conda would be great if pypi is problematic.

**Comment by ShadenSmith** [comment]
Hi @jimdowling,

We have a now have a conda package uploaded and we appreciate any feedback!

We have versions compiled for `cudatoolkit` versions 10.0 and 10.1 To install along with pytorch and other dependencies that are in the conda-forge channel:

```bash
conda install deepspeed cudatoolkit=10.1 -c deepspeed -c pytorch -c conda-forge
```

**Comment by saurabh-kataria** [comment]
installation fails for python 3.8
