### ISSUE TITLE
AttributeError: 'AdamW' object has no attribute 'half'

### ISSUE THREAD

**Issue by juliahane** [microsoft/DeepSpeed#738]
Hi
I am trying to make the minimal example work with deepspeed, here is my codes:

test_deepspeed.py
```
import io
import torch
import torch.nn as nn
import deepspeed
import json

class Model(nn.Module):
  def __init__(self):
       super(Model, self).__init__()
       self.classifier = nn.Linear(50, 3)
  def forward(self, x):
      return self.classifier(x)


if __name__ == "__main__":
   with io.open('ds_config.json', "r", encoding="utf-8") as f:
       config = json.load(f)

   deepspeed.init_distributed()
   model = Model().cuda()
   optimizer = torch.optim.AdamW(model.parameters(), lr=0.001)
   model = deepspeed.initialize(model, optimizer, config_params=config)
```

here is ds_config.json file's content:

```
{
    "train_batch_size": 10,
    "fp16": {
        "enabled": true,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "zero_optimization": {
        "stage": 2,
       "allgather_partitions": true,
       "allgather_bucket_size": 2e8,
       "reduce_scatter": true,
       "reduce_bucket_size": 2e8,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "cpu_offload": true
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 3e-5,
            "betas": [ 0.9, 0.999 ],
            "eps": 1e-8,
            "weight_decay": 3e-7
        }
    }
}
```

here is how I run the codes:
`deepspeed codes.py
`

here is the error I got 

```
  File "test_deepspeed.py", line 23, in <module>
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.001).half()
AttributeError: 'AdamW' object has no attribute 'half'
```
could you assist me please with helping me completing this minimal example? this is also helpful to share some working example such as this in the repo for the new comers such as me.

thanks

**Comment by lukasfolle** [comment]
I am not too familiar with DeepSpeed, but this seems to be a pytorch error as the AdamW cannot be combined with `half()`.
Please correct me if I am wrong.

**Comment by tjruwase** [comment]
@lukasfolle Thanks for  your response, which is correct. 

@juliahane AdamW is a [torch.optim.Optimizer](https://pytorch.org/docs/stable/optim.html) type which does not have `half() `method. On the other hand, `half()` is defined on other types such as [Modules](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.half) and [Tensors](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.half). With DeepSpeed, you don't need to worry about calling `half()` to enable mixed-precision training, the DeepSpeed engine will do that for you. 

@lukasfolle  Thanks for helping to resolve this. 

@juliahane I will close this now, please feel free to reopen if needed.
