### ISSUE TITLE
Batch loading in Pipeline Parallelism

### ISSUE THREAD

**Issue by kefirski** [microsoft/DeepSpeed#744]
I am trying to train a model using Pipeline Parallelism, but the topic's tutorial is a little bit frustrating. Could you please give more information regarding batch loading in the processes?

Consider that I have 2 nodes, each with 8 GPUs. Thus, in total, I have to run 16 processes. I will split these 16 processes into two parts of Data-Parallel so that I will run 8 processes on each node running Pipeline Parallelism (let's say that on the first node, I have local ranks from 0 to 7).

How should I perform batch loading on these 8 processes of each node? Having a batch loader at each process and running `engine.train_batch(batch)` seems to be an incorrect way to train a model since each process represents only a part of the model. 

Some base intuition says that I rather have to load the same batch in these 8 processes (which seems to be somewhat lame) or to run `train_batch` only in the process with the rank equal to 0: 

```python
if local_rank == 0:
    engine.train_batch(batch)
```

**Comment by vfdev-5** [comment]
I think this the answer to your question:
https://github.com/microsoft/DeepSpeed/blob/937c5ceec1906e1a8f8e21d2dd165f5280050b26/deepspeed/runtime/pipe/engine.py#L471-L481
