### ISSUE TITLE
Error with sparse attention

### ISSUE THREAD

**Issue by ShivanshuPurohit** [microsoft/DeepSpeed#754]
I get this error when I enable sparse attention: `RuntimeError: Unable to JIT load the sparse_attn op due to it not being compatible due to hardware/software issue.`
My `nvcc --version` says
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```
And I am running the script on 4 RTX 2080Ti's

**Comment by arashashari** [comment]
Sparse Attention kernels are written in Triton and currently only work on Tesla V100; we will be soon upgrading to handle Ampere as well. However, it is not compatible with GeForce RTX.

**Comment by ShivanshuPurohit** [comment]
I see. Thanks.

**Comment by ShivanshuPurohit** [comment]
Even with 4x V100, I get the same error.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @ShivanshuPurohit 

Can you please run the "ds_report" on your machine and see what compatibility exists for the sparse attention?

Thanks.
Reza

**Comment by ShivanshuPurohit** [comment]
Hi @RezaYazdaniAminabadi,
Here's what I get when I run `ds_report`:
```
/src/deepspeed/deepspeed/runtime/pipe/module.py:533: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if rank_repr is not '':
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch']
torch version .................... 1.7.1
torch cuda version ............... 10.2
nvcc version ..................... 10.2
deepspeed install path ........... ['/src/deepspeed/deepspeed']
deepspeed info ................... 0.3.10+5a45411, 5a45411, HEAD
deepspeed wheel compiled w. ...... torch 1.7, cuda 10.2
```
I see a bunch of [NO]'s in installed. Are they something you install separately from deepspeed?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @ShivanshuPurohit 

Thanks for sending the report. The sparse-attention code should be compiled through JIT and there is no need to be pre-installed. However, I am seeing that the CUDA version for torch is 10.2 and for the nvcc is 11.0. I think there might be some compatibility issue there! Can you make the CUDA versions similar and try it again?
Thanks.

**Comment by ShivanshuPurohit** [comment]
I think they are compatible?
```
torch cuda version ............... 10.2
nvcc version ..................... 10.2
```

**Comment by arashashari** [comment]
@ShivanshuPurohit: I wonder if triton and llvm has been installed manually; out of DeepSpeed. If so, could you please let report the version#?
@jeffra: wonder you may have any idea about this?

**Comment by ShivanshuPurohit** [comment]
It seems like the issue was local to only one node, as I can run sparsity:
"intersperesed" on a different node.

**Comment by kswamy15** [comment]
> Sparse Attention kernels are written in Triton and currently only work on Tesla V100; we will be soon upgrading to handle Ampere as well. However, it is not compatible with GeForce RTX.

Why is GeForce RTX being left out?  or are you working to handle RTX later?  Is RTX very different compute platform compared to V100?

**Comment by TheLustriVA** [comment]
> > Sparse Attention kernels are written in Triton and currently only work on Tesla V100; we will be soon upgrading to handle Ampere as well. However, it is not compatible with GeForce RTX.
> 
> Why is GeForce RTX being left out? or are you working to handle RTX later? Is RTX very different compute platform compared to V100?

Does this mean DeepSpeed and therefore gpt-neox won't run on cards like the 3090?
