### ISSUE TITLE
Best practice for scaling up

### ISSUE THREAD

**Issue by ShivanshuPurohit** [microsoft/DeepSpeed#770]
After discussing at length about the best ways to scale up using deepspeed, here's my understanding, about various features:
- ZeRO-2 and Pipeline Parallelism are not compatible
- Sparse-attention only works when model parallelism is disabled
- 1-bit adam requires MPI backend, which is unrelated to PyTorch's MPI/NCCL backend as mpi4py resolves the conflict

Opening a thread to clear the doubts furthur @conglongli @samyam @ShadenSmith @awan-10 
The main question I have now is that with mpi4py and openmpi installed, 1-bit adam _runs_, but even beyond the `freeze_steps`, it shows no speed-up. Maybe it is because we have PyTorch built on NCCL, but I'm not sure.
[Here](https://docs.google.com/document/d/1bRnHpUPxGnrDYPGQKPv70mPlxHRevmJ3wXrmlbaY5-E/edit) are some logs from our experiments.

**Comment by samyam** [comment]
@awan-10 ad @conglongli any ideas on the mp4 and openmpi?

@ShivanshuPurohit  one thing I notice from the results you collected is that your forward and backward time is decreasing with increase in GPU count, from which I am guess you are not scaling you batch size you are increasing the GPU count.  Is this correct? May I ask what is the aggregate batch size you are using for these runs? If you keep the batch size constant across all GPU counts, the communication would dominate the training time unless you started off with a pretty large batch size to begin with.

**Comment by ShivanshuPurohit** [comment]
We haven't changed the batch size from what the configs have in the megatron-3d repo. More specifically, we keep
```
  "train_batch_size": 256,
  "train_micro_batch_size_per_gpu": 4
```
unchanged. This is the config for 1 node, 8 GPUs. Should I scale it linearly for 2/4/8 nodes?

**Comment by samyam** [comment]
Yes, you should keep the micro_batch_size_per_gpu a constant, but scale the train_batch_size up linearly. That should significantly improve your performance.
