### ISSUE TITLE
Can I change the parameter "step" in /ops/sparse_attention/matmul.py ?

### ISSUE THREAD

**Issue by vick-wuwei** [microsoft/DeepSpeed#778]
```
#Line 632
step = 8 if dtype == torch.float32 else 16

#Line 280~282
div = block // step
xincs = xincs.view(-1, 1).repeat(1, div)
```
The input parameter “block” need to bigger than 8，otherwise throw the error.

and after I change the step, I found that something wrong with the parameters "TM" "TK  and "TN",
so, what should I do ?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @vick-wuwei 

I think the TM, TK, and TN are kernel-specific and based on the GPU architecture. However, I assume you may be able to change the step or block size as long as it is dividable by step. 
Could you please elaborate on the task you want to change these parameters for? For instance, what block size do you want to use that the step needs to be different?

Thanks,
Reza

**Comment by vick-wuwei** [comment]
> Hi @vick-wuwei
> 
> I think the TM, TK, and TN are kernel-specific and based on the GPU architecture. However, I assume you may be able to change the step or block size as long as it is dividable by step.
> Could you please elaborate on the task you want to change these parameters for? For instance, what block size do you want to use that the step needs to be different?
> 
> Thanks,
> Reza

Thanks, I see that
