### ISSUE TITLE
"No module named 'deepspeed.profiling'"

### ISSUE THREAD

**Issue by afogarty85** [microsoft/DeepSpeed#811]
I am hoping to use the FLOPs profiling function but I cannot get deepspeed to run on Google Colab. I am a Windows user so it precludes me, also, from running it, as torch yields this error: `cannot import name 'FileStore' from 'torch.distributed'`.

My steps on colab:

1. !pip install torch
2. !pip install deepspeed
3. !pip install transformers
4. Run BERT block here: https://github.com/microsoft/DeepSpeed/blob/e2dfe0d17be21ce08e759dab4712bc37debd44c4/docs/_tutorials/flops-profiler.md
5. Return error: `ModuleNotFoundError: No module named 'deepspeed.profiling'`

**Comment by cli99** [comment]
Can you please provide the deepspeed package information? You can find it under DEEPSPEED_INSTALL_PATH/deepspeed.egg-info. Thanks

**Comment by afogarty85** [comment]
> Can you please provide the deepspeed package information? You can find it under DEEPSPEED_INSTALL_PATH/deepspeed.egg-info. Thanks

I am not sure this is possible on colab? Instead I've returned this info if it is helpful:

```
import deepspeed
deepspeed.__version__
# 0.3.10
```

**Comment by cli99** [comment]
As you can see from here, https://github.com/microsoft/DeepSpeed/tree/v0.3.10/deepspeed, the profiling module is not available in that version. The profiler is available after v0.3.11. Thanks.

**Comment by afogarty85** [comment]
Thanks, this gets a little bit closer!

If I force install deepspeed to a version outside of what pip will give automatically by:
`!pip install deepspeed==0.3.11`

I can partially run the example given here: https://www.deepspeed.ai/tutorials/flops-profiler/

However, copy-pasting the example:

```
from functools import partial
import torch
from transformers import BertForSequenceClassification, BertTokenizer
from deepspeed.profiling.flops_profiler import get_model_profile


def bert_input_constructor(input_shape, tokenizer):
    fake_seq = ""
    for _ in range(input_shape[1] - 2):  # ignore the two special tokens [CLS] and [SEP]
      fake_seq += tokenizer.pad_token
    inputs = tokenizer([fake_seq] * input_shape[0],
                       padding=True,
                       truncation=True,
                       return_tensors="pt")
    labels = torch.tensor([1] * input_shape[0])
    inputs = dict(inputs)
    inputs.update({"labels": labels})
    return inputs


with torch.cuda.device(0):
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
    batch_size = 4
    seq_len = 128
    enable_profile = True
    if enable_profile:
      macs, params = get_model_profile(
          model,
          (batch_size, seq_len),
          input_constructor=partial(bert_input_constructor,
                                    tokenizer=tokenizer),
          print_profile=True,
          detailed=True,
      )
    else:
      inputs = bert_input_constructor((batch_size, seq_len), tokenizer)
      outputs = model(inputs)
```

Tells us that:

`TypeError: get_model_profile() got an unexpected keyword argument 'detailed'`

**Comment by g-karthik** [comment]
@cli99 can the flops profiler be extended to include backward as well? I have a model for which I see the flops profiler print 2.7 TFLOPS (looks like this is per GPU), but I want a realistic measure of the TFLOPS.

If it can't be extended, can you provide some pointers on how I can use that 2.7 TFLOPS to estimate the realistic TFLOPS per GPU?

**Comment by cli99** [comment]
Do you still have the issue "TypeError: get_model_profile() got an unexpected keyword argument 'detailed？

It can be extended to include backward (bwd), but we can just estimate the backward flops from the forward(fwd). As pointed in https://github.com/cli99/DeepSpeed/tree/master/deepspeed/profiling/flops_profiler#example-training-workflow, the flops of a backward pass can be roughly estimated from that of the forward pass (~2x).  The overall TFLOPS per GPU for bwd+fwd can be computed as fwd flops * 3/ (fwd latency + bwd latency).
