### ISSUE TITLE
Onebit_adam: Tensor can not cat with different dimensions

### ISSUE THREAD

**Issue by jacob1017** [microsoft/DeepSpeed#813]
https://github.com/microsoft/DeepSpeed/blob/937c5ceec1906e1a8f8e21d2dd165f5280050b26/deepspeed/runtime/fp16/onebit_adam.py#L120

here buffer_m with dimension same as parameters and always more than 1。

**Comment by conglongli** [comment]
Closing as this was fixed in https://github.com/microsoft/DeepSpeed/pull/817
