### ISSUE TITLE
KeyError: "Home" on Windows

### ISSUE THREAD

**Issue by carlomarxdk** [microsoft/DeepSpeed#814]
I get an KeyError: "Home"  error when importing the deepspeed package 
Windows does not have HOME variable, the solution is to change: 
`os.environ["HOME"]` to `os.path.expanduser('~')`

The change has to be done in engine.py script

**Comment by tjruwase** [comment]
@carlomarxdk can you please share your stack trace to help narrow down the code location?

Perhaps, it is this [code line](https://github.com/microsoft/DeepSpeed/blob/937c5ceec1906e1a8f8e21d2dd165f5280050b26/deepspeed/runtime/engine.py#L249).

**Comment by carlomarxdk** [comment]
I can't share the trace because of the nature of the project (e.g. security reasons). But yes, this is the line I was talking about.

**Comment by tjruwase** [comment]
I am glad you have a workaround. As an alternative that does not require code, can you try using .deepspeed_env in your home folder to set HOME environment variable, just as [here](https://www.deepspeed.ai/getting-started/#multi-node-environment-variables)?

**Comment by jeffra** [comment]
@carlomarxdk this commit https://github.com/microsoft/DeepSpeed/commit/49496364c05a52c2511937419294087f77e46610 should fix the issue i assume, I accidently pushed this directly to master and not a PR though.
