### ISSUE TITLE
Could you olease update triton support to 0.3.0, old version of that even do not have a doc.

### ISSUE THREAD

**Issue by PistonY** [microsoft/DeepSpeed#838]
I can't install triton==0.2.3, I can't know what version of LLVM does that need. They even do not have doc of old version.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @PistonY 

I have added some changes in this [PR ](https://github.com/microsoft/DeepSpeed/pull/902) that uses the new version of Triton. Can you please try it to see if it solves the LLVM issue?

Thanks,
Reza
