### ISSUE TITLE
Unable to detect local GPU Resources

### ISSUE THREAD

**Issue by zbloss** [microsoft/DeepSpeed#86]
After running deepspeed locally, from the deepspeed/deepspeed:latest docker container, it is unable to detect my local NVIDIA GTX 1080.

Edit: I am on Windows 10 which is complicating this issue

**Comment by jeffra** [comment]
Hi @zbloss, thanks for your interest! Unfortunately, last I tried gpu pass through to a Linux container from a windows host isn’t supported :( 

Related thread: https://stackoverflow.com/questions/49589229/is-gpu-pass-through-possible-with-docker-for-windows

**Comment by jeffra** [comment]
Closing this issue, feel free to reopen if needed though.
