### ISSUE TITLE
Zero optimzier for model/pipeline parallelism

### ISSUE THREAD

**Issue by sangkeun00** [microsoft/DeepSpeed#869]
Hello DeepSpeed!

I understand that Zero1-3 can significantly increase the memory efficiency for data parallel training where the model and optimizer states are (traditionally) replicated across all workers. However, I wonder if the same idea can also be applied in model/pipeline parallelism. In other words, when we have total N workers (GPUs), can we partition optimizer states/gradients/parameters among all workers regardless of parallelism types? If this is incompatible with model or pipeline parallelism, can someone explain why it is not possible? Thanks in advance!

**Comment by Jack47** [comment]
This sounds reasonable, so wandering if we can partition optimizer states across different pipelines
