### ISSUE TITLE
[zero3] How to load pretrained Massive Models (zero.Init())

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#874]
What is the approach to [Constructing Massive Models](https://deepspeed.readthedocs.io/en/latest/zero3.html#constructing-massive-models) for pretrained models?

Typically we load the state_dict with pre-trained weights, but clearly this can't work here, I gave it a quick try and no, it doesn't work, Getting size mismatch errors because the pre-trained weights are of a different dimension.

I think it's quite rare these days that someone starts training from scratch, so perhaps we can find a way to do this for pre-trained models? I think this again brings us back to a need of saving/loading non-deepspeed checkpoints.

Thank you.

**Comment by Quan-Sun** [comment]
@stas00 hi there! Is there any updates?

**Comment by stas00** [comment]
oh, I think this has been long long resolved. Closing this. Please open a new issue if you are still having a problem.
