### ISSUE TITLE
Triton 1.1 support

### ISSUE THREAD

**Issue by fYYw** [microsoft/DeepSpeed#900]
Could you add support for Triton 1.1? The triton.kernel now is requiring an additional argument "device". 
Thanks!

**Comment by RezaYazdaniAminabadi** [comment]
Hi @fYYw 

can you please use this [PR ](https://github.com/microsoft/DeepSpeed/pull/902)and see if it works on your side?

Thanks.
Reza

**Comment by loadams** [comment]
Hi @fYYw - the linked PR completed and we support up to Triton 2 now.
