### ISSUE TITLE
FPGA suitability

### ISSUE THREAD

**Issue by danlg** [microsoft/DeepSpeed#906]
Hi,

Do you think deepspeed would be a good candidate to be able to run on FPGA (vs GPU)? My intuition tells me it could be a very serious contender to GPU (and possibly yield even better perf) but do not have not hard data to prove it yet.

If so, are there some plans to do so ?

**Comment by awan-10** [comment]
Hi @danlg, thank you for your interest in deepspeed. We haven't run deepspeed on an FPGA but would love to hear more about it. 

Do you have a particular FPGA that you are trying it with? We depend on PyTorch so the FPGA being used will need to be first tested with PyTorch itself.
