### ISSUE TITLE
cpu_offload:false with RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by irfan11111111** [microsoft/DeepSpeed#936]
I am using deepspeed to pretrain the bert,
while using stage 2,if  I set "cpu_offload":true,the deepspeed could run,but it only run about 3 minutes, and it stop,but it do not report error,it just stop
the configue are as follows:
{
  "train_batch_size": 24,
  "train_micro_batch_size_per_gpu": 6,
  "steps_per_print": 100,
  "prescale_gradients": false,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 2e-3,
      "weight_decay": 0.01,
      "eps":2e-3,
      "betas":[
        0.8,
        0.999
      ]
    }
  },
  "gradient_clipping": 1.0,
  "wall_clock_breakdown": false,

  "fp16": {
    "enabled": true
  },
  "zero_optimization":{
    "stage":2,
    "cpu_offload":false
  }
}

100%|████████████████████████████████████████████████████████████████████████████████████████████████| 178/178 [01:58<00:00,  1.51it/s]
and it do not continue run,just stop here,no error
one GPU-util is 0,the other three are 100%

if I set cpu_offload:false, the program report the following error,and use stage 1 are the same:

RuntimeError: CUDA error: no kernel image is available for execution on the device
but the torch work well,the GPU are V100,all together is 4 

>>> import torch
>>> torch.cuda.is_available()
True
>>> a= torch.Tensor(5,3)
>>> a=a.cuda()
>>> a
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
>>> 

I do not know why?

the environments are as follows:
 
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
 [WARNING]  sparse_attn requires one of the following commands '['llvm-config', 'llvm-config-9']', but it does not exist!
sparse_attn ............ [NO] ....... [NO]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/gf3/home/yfchen/anaconda3/lib/python3.7/site-packages/torch']
torch version .................... 1.8.0+cu111
torch cuda version ............... 11.1
nvcc version ..................... 11.1
deepspeed install path ........... ['/gf3/home/yfchen/anaconda3/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.3.5+unknown, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.8, cuda 11.1

is there anyone  have met this problem?

**Comment by tjruwase** [comment]
@irfan11111111, are you using [bing_bert ](https://github.com/microsoft/DeepSpeedExamples/tree/master/bing_bert)from DeepSpeedExamples? 

Can you share more details of the log? 

Also, can you try running with 1-gpu?

**Comment by loadams** [comment]
Hi @irfan11111111 - this type of issue is usually related to the cuda install/compile and DeepSpeed trying to find them.  I'm going to close this since this is using a veyr old version of cuda I cannot repro with.  

If you are still hitting this issue, please open a new issue and link this one and we would be happy to take a look.
