### ISSUE TITLE
How to debug a deepspeed program?

### ISSUE THREAD

**Issue by TonyTangYu** [microsoft/DeepSpeed#938]
I succeeded running a deepspeed program and I want to try to debug this program. I am using VSCode but it doesn't support a non-python interpreter. I want to know how to debug a deepspeed program with VSCode.

**Comment by tjruwase** [comment]
@TonyTangYu, unfortunately I don't have the expertise of debugging deepspeed with VSCode. Have you previously debugged other python codes with VSCode? Have you tried using pdb on deepspeed?

**Comment by tjruwase** [comment]
Closing for lack of response. Please reopen as needed.

**Comment by linboqiao** [comment]
A manually debug setting is available here: https://github.com/WeSIG/PDLM

**Comment by RenzeLou** [comment]
I have the same problem. I try to write a `launch.json` to debug the deepspeed, but it doesn't work because there is no vscode plugin for deepspped. 

```
{   "cwd": "/home/xxx/code/project/",
            "env": {"CUDA_VISIBLE_DEVICES":"7",
                    "CUDA_DEVICE_ORDER":"PCI_BUS_ID",
                    "TRANSFORMERS_CACHE":"/home/xxx/.cache/huggingface"}, 
            "name": "deepspeed",
            //"type": "python",
            "type": "deepspeed",   // there is no supported interpreter for deepspeed
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "args": [
                "--master_port","10086",
                "--do_train",
                "--do_predict",
                "--predict_with_generate"
            ]
        },
```

Can the authors propose a correspondent plugin for the users of vscode? 
Thanks.

**Comment by Parskatt** [comment]
@NouamaneTazi thanks for the tip :)
I also found that you can replace "/home/nouamane/projects/llm/Megatron-DeepSpeed/pretrain_gpt.py" with just "${file}" in args, then you just debug the currently selected file, which I think is more convenient.

**Comment by fanxinwen** [comment]
Hello, with the same settings, my breakpoint cannot be stopped

> This worked for me
> 
> ```
>       {
>            "name": "Python: Debug DeepSpeed",
>            "type": "python",
>            "request": "launch",
>            "program": "/home/nouamane/miniconda3/envs/dev/bin/deepspeed",
>            "justMyCode": true,
>            "console": "integratedTerminal",
>            "args": [
>                "--num_nodes=1",
>                "--num_gpus=2",
>                "/home/nouamane/projects/llm/Megatron-DeepSpeed/pretrain_gpt.py",
>            ]
>        },
> ```

Hello, with the same settings, my breakpoint cannot be stopped

**Comment by pengyong94** [comment]
i use this launch.json， but i got this error: "No module named /data/xiaoming/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py"
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug DeepSpeed",
            "type": "python",
            "request": "launch",
            "program": "/usr/local/bin/deepspeed",
            "cwd": "${workspaceFolder}",
            "justMyCode": true,
            "console": "integratedTerminal",
            "args": [
                "--num_nodes", "1",
                "--num_gpus", "1",
                "/data/xiaoming/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py",
                // "--model_name_or_path", "/data/xiaoming/Pretrain_Model/opt-1.3b",
                // "--gradient_accumulation_steps", "8",
                // "--lora_dim", "128",
                // "--zero_stage", "2",
                // "--output_dir", "output",
            ]

        }
    ]
}

**Comment by pengyong94** [comment]
I got this error: "No module named /data/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py"
This is my launch.json file :
`{
    
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug DeepSpeed",
            "type": "python",
            "request": "launch",
            "program": "/usr/local/bin/deepspeed",
            "justMyCode": true,
            "console": "integratedTerminal",
            "args": [
                "--num_nodes", "1",
                "--num_gpus", "1",
                "/data/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py",

            ]

        }
    ]
}`

**Comment by microhu** [comment]
> I got this error: "No module named /data/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py" This is my launch.json file : `{
> 
> ```
> "version": "0.2.0",
> "configurations": [
>     {
>         "name": "Debug DeepSpeed",
>         "type": "python",
>         "request": "launch",
>         "program": "/usr/local/bin/deepspeed",
>         "justMyCode": true,
>         "console": "integratedTerminal",
>         "args": [
>             "--num_nodes", "1",
>             "--num_gpus", "1",
>             "/data/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py",
> 
>         ]
> 
>     }
> ]
> ```
> 
> }`

@pengyong94 Did you solve this problem finally? I got the same error

**Comment by Skywalker-Harrison** [comment]
I use the setting 

> > This worked for me
> > ```
> >       {
> >            "name": "Python: Debug DeepSpeed",
> >            "type": "python",
> >            "request": "launch",
> >            "program": "/home/nouamane/miniconda3/envs/dev/bin/deepspeed",
> >            "justMyCode": true,
> >            "console": "integratedTerminal",
> >            "args": [
> >                "--num_nodes=1",
> >                "--num_gpus=2",
> >                "/home/nouamane/projects/llm/Megatron-DeepSpeed/pretrain_gpt.py",
> >            ]
> >        },
> > ```
> 
> Hi, How could this debug config adapt hostfile args?

I used this setting and it yields No module named deepspeed error

**Comment by microhu** [comment]
> I use the setting
> 
> > > This worked for me
> > > ```
> > >       {
> > >            "name": "Python: Debug DeepSpeed",
> > >            "type": "python",
> > >            "request": "launch",
> > >            "program": "/home/nouamane/miniconda3/envs/dev/bin/deepspeed",
> > >            "justMyCode": true,
> > >            "console": "integratedTerminal",
> > >            "args": [
> > >                "--num_nodes=1",
> > >                "--num_gpus=2",
> > >                "/home/nouamane/projects/llm/Megatron-DeepSpeed/pretrain_gpt.py",
> > >            ]
> > >        },
> > > ```
> > 
> > 
> > Hi, How could this debug config adapt hostfile args?
> 
> I used this setting and it yields No module named deepspeed error

upgrade the vs code can solve this problem

**Comment by Skywalker-Harrison** [comment]
> > I use the setting
> > > > This worked for me
> > > > ```
> > > >       {
> > > >            "name": "Python: Debug DeepSpeed",
> > > >            "type": "python",
> > > >            "request": "launch",
> > > >            "program": "/home/nouamane/miniconda3/envs/dev/bin/deepspeed",
> > > >            "justMyCode": true,
> > > >            "console": "integratedTerminal",
> > > >            "args": [
> > > >                "--num_nodes=1",
> > > >                "--num_gpus=2",
> > > >                "/home/nouamane/projects/llm/Megatron-DeepSpeed/pretrain_gpt.py",
> > > >            ]
> > > >        },
> > > > ```
> > > 
> > > 
> > > Hi, How could this debug config adapt hostfile args?
> > 
> > 
> > I used this setting and it yields No module named deepspeed error
> 
> upgrade the vs code can solve this problem

Thank you, this problem is solved by changing the interpreter.

**Comment by dddraxxx** [comment]
for anyone who might find this, you could use debugpy to attach it using:
`python -m debugpy --wait-for-client --listen 5678 -m deepspeed.launcher.runner ${your args}`

**Comment by dddraxxx** [comment]
> > for anyone who might find this, you could use debugpy to attach it using: `python -m debugpy --wait-for-client --listen 5678 -m deepspeed.launcher.runner ${your args}`
> 
> Can you provide me with some examples of using debugpy to debug deepspeed? It seems that the command is not functioning properly for me. When I click the start button, it remains silent and exits immediately without any error messages.

You can use vscode debugger with config like: `{
                "name": "Python: all code",
                "type": "python",
                "request": "attach",
                "connect": {
                    "host": "localhost",
                    "port": 5678
                },
                "justMyCode": false
            },
` after running the python script.

**Comment by ZiangWu-77** [comment]
> Hello, with the same settings, my breakpoint cannot be stopped
> 
> > This worked for me
> > ```
> >       {
> >            "name": "Python: Debug DeepSpeed",
> >            "type": "python",
> >            "request": "launch",
> >            "program": "/home/nouamane/miniconda3/envs/dev/bin/deepspeed",
> >            "justMyCode": true,
> >            "console": "integratedTerminal",
> >            "args": [
> >                "--num_nodes=1",
> >                "--num_gpus=2",
> >                "/home/nouamane/projects/llm/Megatron-DeepSpeed/pretrain_gpt.py",
> >            ]
> >        },
> > ```
> 
> Hello, with the same settings, my breakpoint cannot be stopped

just try this:
```sh
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Debug DeepSpeed",
            "type": "debugpy",
            "request": "launch",
            "program": "/usr/local/bin/deepspeed",
            "justMyCode": true,
            "console": "integratedTerminal",
            "args": [
                "--include",
                "localhost:0",
                "${file}",
            ],
        }
    ]
}
```

**Comment by wanghanone** [comment]
> > I got this error: "No module named /data/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py" This is my launch.json file : `{
> > ```
> > "version": "0.2.0",
> > "configurations": [
> >     {
> >         "name": "Debug DeepSpeed",
> >         "type": "python",
> >         "request": "launch",
> >         "program": "/usr/local/bin/deepspeed",
> >         "justMyCode": true,
> >         "console": "integratedTerminal",
> >         "args": [
> >             "--num_nodes", "1",
> >             "--num_gpus", "1",
> >             "/data/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py",
> > 
> >         ]
> > 
> >     }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }`
> 
> @pengyong94 Did you solve this problem finally? I got the same error

Have you solved the problem?

**Comment by Ben-Schneider-code** [comment]
> > > I got this error: "No module named /data/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py" This is my launch.json file : `{
> > > ```
> > > "version": "0.2.0",
> > > "configurations": [
> > >     {
> > >         "name": "Debug DeepSpeed",
> > >         "type": "python",
> > >         "request": "launch",
> > >         "program": "/usr/local/bin/deepspeed",
> > >         "justMyCode": true,
> > >         "console": "integratedTerminal",
> > >         "args": [
> > >             "--num_nodes", "1",
> > >             "--num_gpus", "1",
> > >             "/data/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py",
> > > 
> > >         ]
> > > 
> > >     }
> > > ]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }`
> > 
> > 
> > @pengyong94 Did you solve this problem finally? I got the same error
> 
> Have you solved the problem?

Change the vscode interpretor to one that has deepspeed installed.
https://stackoverflow.com/questions/47602151/how-to-change-interpreter-in-visual-studio-code
