### ISSUE TITLE
Local Install Issue - Apex

### ISSUE THREAD

**Issue by kleingeo** [microsoft/DeepSpeed#94]
I noticed that in the install.sh file when doing a local install, `sh install.sh -l`, the installer seems to uninstall and reinstall apex twice. Is this normal behavior?

**Comment by jeffra** [comment]
Should be fixed now. We will be doing a complete refactoring of our install scripts soon, but this at least fixes this issue as I understand it for now. Please reopen if it doesn't fix the issue you describe.
