### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [microsoft/DeepSpeed#950]
[jw@cn05 deepspeed]$ ./install.sh
...
creating deepspeed.egg-info
writing deepspeed.egg-info/PKG-INFO
writing dependency_links to deepspeed.egg-info/dependency_links.txt
writing requirements to deepspeed.egg-info/requires.txt
writing top-level names to deepspeed.egg-info/top_level.txt
writing manifest file 'deepspeed.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cc' under directory 'deepspeed'
warning: no files found matching '*.tr' under directory 'csrc'
warning: no files found matching '*.cc' under directory 'csrc'
writing manifest file 'deepspeed.egg-info/SOURCES.txt'
error: can't copy 'deepspeed/ops/csrc': doesn't exist or not a regular file
Error on line 155
Fail to install deepspeed
[jw@cn05 deepspeed]$

**Comment by awan-10** [comment]
@LutzWeischerFujitsu - thanks for trying deepspeed. Can you please add some more details on this system? Also please try ./install.sh -s if you have sudo access on this system. Or you can try pip install .

**Comment by LutzWeischerFujitsu** [comment]
Using '-s' runs, but finally seems to require nvcc, CUDA. Can I build without it, too?: 
DeepSpeed general environment info:
torch install path ............... ['/home/jw/.local/lib/python3.9/site-packages/torch']
torch version .................... 1.8.0
torch cuda version ............... None
nvcc version .....................  [FAIL] cannot find CUDA_HOME via torch.utils.cpp_extension.CUDA_HOME=None
deepspeed install path ........... ['/home/jw/.local/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.3.14, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.8, cuda 0.0

Trying 'pip3 install .' finds (also) trouble: 
/bin/sh: line 0: type: llvm-config-9: not found
and
error: can't copy 'deepspeed/ops/csrc': doesn't exist or not a regular file

**Comment by awan-10** [comment]
Yes, we do need CUDA to be installed in order to build deepspeed.

**Comment by LutzWeischerFujitsu** [comment]
In that case we can close for now this issue. CUDA installation still fails on Arm, Fedora 33, trying the RHEL 8 version. Will re-try in the future again.
