### ISSUE TITLE
ZeRO Stage1 behaviour changed between v0.3.2 and v0.3.3

### ISSUE THREAD

**Issue by e-sha** [microsoft/DeepSpeed#967]
Hello,
I found significant difference in BERT training curves between versions v0.3.2 and v0.3.3. The [log](https://github.com/microsoft/DeepSpeed/commit/08c96a1bc6d9c0345b31889bba66d73f20d0b0b5#) doesn't help me to understand the reason. Is it an expected behaviour?

![Screenshot from 2021-04-16 17-08-02](https://user-images.githubusercontent.com/6618622/115036618-5a4b3400-9ed6-11eb-8cf3-84dd3946f53f.png)
![Screenshot from 2021-04-16 17-10-17](https://user-images.githubusercontent.com/6618622/115036990-ae561880-9ed6-11eb-9bcf-e0eae6aaa430.png)

I tried pretraining of a shallow BERT model. My deepspeed config:
```
{
  "train_batch_size": 384,
  "train_micro_batch_size_per_gpu": 48,
  "steps_per_print": 1000,
  "prescale_gradients": false,
  "zero_allow_untested_optimizer": true,
  "optimizer": {
    "type": "adam",
    "params": {
      "lr": 0.00152,
      "weight_decay": 0.01,
      "bias_correction": false
    }
  },
  "gradient_clipping": 1.0,

  "wall_clock_breakdown": false,

  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "initial_scale_power": 20
  },
  "zero_optimization": {
      "stage": 1
  }
}
```
My BERT config:
```
{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 512,
  "num_attention_heads": 32,
  "num_hidden_layers": 2,
  "type_vocab_size": 10,
  "vocab_size_or_config_json_file": 103296
}
```

**Comment by aced125** [comment]
uh oh

**Comment by tjruwase** [comment]
@e-sha, can you please try this [branch](https://github.com/microsoft/DeepSpeed/tree/olruwase/zero_optional_reduce_scatter)?

**Comment by e-sha** [comment]
Thank you for the reply. I will check it next week and will send you the results.

**Comment by e-sha** [comment]
Yes it fixes the problem. Please explain the problem in more details.
![Screenshot from 2021-05-01 00-20-02](https://user-images.githubusercontent.com/6618622/116755517-34b04580-aa13-11eb-81e5-1ff8705c6121.png)
![Screenshot from 2021-05-01 00-20-25](https://user-images.githubusercontent.com/6618622/116755520-35e17280-aa13-11eb-9e11-49a093a3486d.png)

**Comment by tjruwase** [comment]
@e-sha, thanks for confirming the fix. The problem was due to a bug in the reduce-scatter implementation of ZeRO-1, which is the default behavior. The current fix is a workaround to use all-reduce as default for reduction in ZeRO-1. We plan to address the underlying issue later. One thing for you to check is whether you are seeing perf loss because all-reduce is slower than reduce-scatter. Please share if you notice any perf loss. Thanks.

**Comment by tjruwase** [comment]
@e-sha, also can you please close this issue once you are satisfied with the resolution? Thanks.
