### ISSUE TITLE
_init_distributed does not use dist_init_required

### ISSUE THREAD

**Issue by kleingeo** [microsoft/DeepSpeed#97]
In the deepspeed_light.py script, the function `_init_distributed` gets passed `dist_init_required`, but this passed variable is not used. If dist_init_required is False this causes an AssetionError even know the functionality should be disabled.

**Comment by tjruwase** [comment]
Thanks for trying out DeepSpeed. 
Did you notice the use of dist_init_required [here](https://github.com/microsoft/DeepSpeed/blob/f2d7513561eb72f6b9c5188b5a227ecb7b05a2ee/deepspeed/__init__.py#L94)?

Can you share the observed AssertionError?

**Comment by tjruwase** [comment]
Hi, do you have further questions regarding this issue?

**Comment by kleingeo** [comment]
The issue was in the actual set-up itself. It seemed that DeepSpeed was set-up to force a distributed model even if `dist_init_required=False`.
