### ISSUE TITLE
Less strict dataset type check in DeepSpeedEngine

### ISSUE THREAD

**Issue by mariosasko** [microsoft/DeepSpeed#973]
Currently if the user tries to pass an object that implements `__getitem__` and `__len__` as the `training_data` argument to `deepspeed.initialize`, an error is raised if the object is not an instance of `torch.utils.data.Dataset` due to the following check:

https://github.com/microsoft/DeepSpeed/blob/2805c3935ae02558f18a71a115185632b087da70/deepspeed/runtime/engine.py#L823-L824

Internally the `training_data` object is used as a dataset for the `torch.utils.data.DataLoader`. Providing `__getitem__` and `__len__` is enough for an object to be considered a valid dataset for the DataLoader (**without subclassing the actual PyTorch Dataset**), which means the current type check is too strict (e.g. this works: `DataLoader([(torch.randn(3, 3), torch.tensor(i % 2)) for i in range(10)], batch_size=2))`).

HF Datasets is one of the biggest dataset hubs and relies on this behavior, but due to this type check, the user has to write a  wrapper for the dataset to successfully pass the check.

So I propose replacing the aforementioned type check with the following code (or smth along these lines):
```python
def is_map_style_dataset(obj):
    return hasattr(obj, "__getitem__") and hasattr(obj, "__len__")

def is_iterable_style_dataset(obj):
    return isinstance(obj, torch.utils.data.IterableDataset)  # hasattr(obj, "__iter__") should work as well

class DeepSpeedEngine:

    def deepspeed_io(self, dataset, ...):
        if not (is_map_style_dataset(dataset) or is_iterable_style_dataset(dataset)):
            raise ValueError("Training data is not a valid torch dataset")
        ...
```

[The relevant issue](https://github.com/huggingface/datasets/issues/2165) in the hf datasets repo that served as a motivation for this issue.

**Comment by cli99** [comment]
Thank you for the suggestion, we are addressing it at https://github.com/microsoft/DeepSpeed/pull/1012.
