### ISSUE TITLE
Sync b/w Eleuther AI's DeeperSpeed and DeepSpeed

### ISSUE THREAD

**Issue by g-karthik** [microsoft/DeepSpeed#987]
Can the added changes made in Eleuther AI's DeeperSpeed fork be merged back into DeepSpeed?

I see some critical differences, such as in `PipelineModule`: [former](https://github.com/EleutherAI/DeeperSpeed/blob/main/deepspeed/runtime/pipe/module.py#L191) and [latter](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/pipe/module.py#L192).

When using containerized setups, it's a lot cleaner to just install from one source rather than have multiple things going on.

@tjruwase @jeffra @ShadenSmith

**Comment by sdtblck** [comment]
Aside from that, this https://github.com/EleutherAI/DeeperSpeed/commit/0e9573776caf7227ecafdc8a3d57c7955165d8e2 (for running inference - majorly hacky and I'm sure there's a better way of doing it), they're mostly the same aside from some minor changes to timers / logging.

**Comment by loadams** [comment]
Closing as this is stale and not an active issue.  If there are other changes from a fork people want merged, please link this when you make a PR.
