### ISSUE TITLE
ZeRO 2 Assertion Error: Gradient computed twice for this partition for Siamese Model

### ISSUE THREAD

**Issue by szhengac** [microsoft/DeepSpeed#988]
If we use ZeRO 2 with activation checkpointing for the [Siamese model](https://arxiv.org/pdf/1908.10084.pdf) (the same model is applied to two inputs independently), we receive 

```
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 53, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/usr/local/lib64/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib64/python3.7/site-packages/torch/autograd/__init__.py", line 148, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/usr/local/lib64/python3.7/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/usr/local/lib64/python3.7/site-packages/torch/utils/checkpoint.py", line 138, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/usr/local/lib64/python3.7/site-packages/torch/autograd/__init__.py", line 148, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/stage2.py", line 572, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/stage2.py", line 990, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/stage2.py", line 628, in reduce_independent_p_g_buckets_and_remove_grads
    Multiple gradient reduction is currently not supported"
AssertionError: The parameter 1 has already been reduced.             Gradient computed twice for this partition.             Multiple gradient reduction is currently not supported
```

The reproducible code (`deepspeed test_twin_model.py --zero 2`):
```
import os
import json
import math
import argparse
import torch
import deepspeed
from torch import nn
from torch.utils import checkpoint
from torch.utils.data.distributed import DistributedSampler


class SimpleModel(torch.nn.Module):
    def __init__(self, hidden_dim, empty_grad=False, zero=0):
        super(SimpleModel, self).__init__()
        self.linear = torch.nn.Linear(hidden_dim, hidden_dim)
        mlp = [self.linear]
        mlp.append(torch.nn.Linear(hidden_dim, hidden_dim//2))
        for _ in range(6):
            l = torch.nn.Linear(hidden_dim//2, hidden_dim//2)
            mlp.append(l)
        mlp.append(torch.nn.Linear(hidden_dim//2, hidden_dim))
        l = torch.nn.Linear(hidden_dim, hidden_dim)
        l.weight = self.linear.weight
        l.bias = self.linear.bias
        mlp.append(l)
        if zero == 3:
            deepspeed.zero.register_external_parameter(self, self.linear.weight)
            deepspeed.zero.register_external_parameter(self, self.linear.bias)
        self.mlp = nn.Sequential(*mlp)
        if empty_grad:
            self.layers2 = torch.nn.ModuleList([torch.nn.Linear(hidden_dim, hidden_dim)])

    def forward(self, x, z):
        x = self.linear(x)
        z = self.linear(z)
        def custom(start, end):
            def custom_forward(*inputs):
                layers = self.mlp[start:end]
                x_ = inputs[0]
                z_ = inputs[1]
                for layer in layers:
                    x_ = layer(x_)
                    z_ = layer(z_)
                return x_, z_
            return custom_forward

        l = 0
        num_layers = len(self.mlp)
        chunk_length = math.ceil(math.sqrt(num_layers))
        while l < num_layers:
            x, z = checkpoint.checkpoint(
                        custom(l, l + chunk_length), x, z
                    )
            l += chunk_length

        c = (x + z) / 2
        return c


def create_config_from_dict(tmpdir, config_dict):
    config_path = os.path.join(tmpdir, 'temp_config.json')
    with open(config_path, 'w') as fd:
        json.dump(config_dict, fd)
    return config_path


def get_data_loader(model, total_samples, hidden_dim, device):
    batch_size = model.train_micro_batch_size_per_gpu()
    train_data = torch.randn(total_samples, hidden_dim, device=device, dtype=torch.half)
    train_label = torch.empty(total_samples,
                              dtype=torch.long,
                              device=device, requires_grad=False).random_(hidden_dim)
    train_dataset = torch.utils.data.TensorDataset(train_data, train_label)
    sampler = DistributedSampler(train_dataset)
    train_loader = torch.utils.data.DataLoader(train_dataset,
                                               batch_size=batch_size,
                                               sampler=sampler)
    return train_loader
def get_args(tmpdir, config_dict):
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int, default=0)
    parser.add_argument('--zero', type=int, default=0)
    args = parser.parse_args()  #args=''

    config_dict["zero_optimization"]["stage"] = args.zero
    print('config_dict["zero_optimization"]', config_dict["zero_optimization"])
    config_path = create_config_from_dict(tmpdir, config_dict)

    args.deepspeed_config = config_path
    return args


def print0(msg):
    if torch.distributed.get_rank() == 0:
        print(msg, flush=True)


rank = int(os.environ['RANK'])
print('seed:', 2222 + rank)
torch.random.manual_seed(2222 + rank)

config_dict = {
    "train_batch_size": 32,
    "train_micro_batch_size_per_gpu": 4,
    "steps_per_print": 1,
    "zero_allow_untested_optimizer": True,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.02,
            "weight_decay": 0.01,
            "bias_correction": True,
            "eps": 1e-6
        }
    },
    "gradient_clipping": 1.0,
    "fp16": {
        "enabled": True,
        "initial_scale_power": 10
    },
    "zero_optimization": {
        "stage": 1,
        "overlap_comm": True,
        "contiguous_gradients": False,
        "reduce_bucket_size": 20
    }
}

args = get_args('/tmp/', config_dict)
hidden_dim = 4

model = SimpleModel(hidden_dim, empty_grad=False, zero=args.zero)

model, _, _,_ = deepspeed.initialize(args=args,
                                     model=model,
                                     model_parameters=model.parameters(),
                                     dist_init_required=True)
cross_entropy_loss = torch.nn.CrossEntropyLoss()

def print_params(tag, model):
    if torch.distributed.get_rank() == 0:
        for n, p in model.named_parameters():
            print0("{} {}:{}".format(tag, n, p))


data_loader = get_data_loader(model=model,
                              total_samples=1000,
                              hidden_dim=hidden_dim,
                              device=model.device)
#print_params('pre-train', model)
for n, batch in enumerate(data_loader):
    x = model(batch[0], batch[0])
    loss = cross_entropy_loss(x, batch[1])
    #if torch.distributed.get_rank() == 0 and model.is_gradient_accumulation_boundary():
    model.backward(loss)
    model.step()
    if torch.distributed.get_rank() == 0 and model.is_gradient_accumulation_boundary():
        print("{}, LOSS: {}".format(n, loss.item()))
    #print_params('step={}'.format(n), model)
    if n == 8: break
```
If we use ZeRO 1 or disable activation checkpointing, the test case can pass. @tjruwase

**Comment by tjruwase** [comment]
@szhengac, thanks for sharing a convenient repro, this is greatly appreciated.

**Comment by tjruwase** [comment]
@szhengac, this issue is due to the fact that activation checkpointing causes backward hook to be invoked on each gradient of a shared weight, whereas without activation checkpointing backward hook is only invoked on the last gradient for shared weights. This creates a problem for zero 2 & 3 because we use the backward hook to trigger gradient reduction, and we expect at most one reduction per parameter in forward/backward sequence. 

We are thinking of ways of handling shared weights+activation checkpointing inside zero 2 & 3, but all the ideas so far are non-trivial. We also open to suggestions and/or contributions if you have bandwidth. Perhaps, pytorch might also be the best place to handle this, by guaranteeing that backward hook is invoked only on the last gradient of whether or not activation checkpointing is used,...

**Comment by szhengac** [comment]
This is what I thought, but I don't quite understand why backward hook has different behaviors when activation checkpointing is used.

**Comment by szhengac** [comment]
@tjruwase Perhaps an easy fix is to record a counter for each parameter during forward, and we skip the backward hook call until the last one. In this way, we can make sure that the behaviors of zero 2, 3 do not change and the reduced gradient is correct. What do you think?

**Comment by zijwang** [comment]
@tjruwase Are you aware of any solution for this issue now? There are also multiple related open issues: e.g. #2103 and #627

**Comment by tjruwase** [comment]
@zijwang, unfortunately, this remains an unsolved problem to my knowledge. Are you running into similar issues?

**Comment by zijwang** [comment]
> @zijwang, unfortunately, this remains an unsolved problem to my knowledge. Are you running into similar issues?

Yes, @tjruwase . I think folks were facing more or less the same issue, i.e., how to do gradient checkpointing with tied weights in DS

**Comment by zijwang** [comment]
Hi @tjruwase , I wonder whether there has been a solution to the problem mentioned above? There are a lot of similar cases pending in issues. Thanks.

**Comment by jomayeri** [comment]
@zijwang Please explicitly set `use_reentrant=False` in the torch checkpointing function and that should solve the issue. https://pytorch.org/docs/stable/checkpoint.html

**Comment by iFe1er** [comment]
> @zijwang Please explicitly set `use_reentrant=False` in the torch checkpointing function and that should solve the issue. https://pytorch.org/docs/stable/checkpoint.html

Help! i pass gradient_checkpointing_kwargs={'use_reentrant': False} to Trainer but if raise warning:
 You are using an old version of the checkpointing format that is deprecated (We will also silently ignore gradient_checkpointing_kwargs in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method _set_gradient_checkpointing in your model.

Same error occur: AssertionError: The parameter 195 has already been reduced.             Gradient computed twice for this partition.             Multiple gradient reduction is currently not supported

**Comment by iFe1er** [comment]
i tried downgrade transformers from 4.38.2 to 4.32.0, the warning become: /root/miniconda3/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.

**Comment by binhna** [comment]
> @zijwang Please explicitly set `use_reentrant=False` in the torch checkpointing function and that should solve the issue. https://pytorch.org/docs/stable/checkpoint.html

thank you, it works for me

**Comment by David-19940718** [comment]
> > @zijwang Please explicitly set `use_reentrant=False` in the torch checkpointing function and that should solve the issue. https://pytorch.org/docs/stable/checkpoint.html
> 
> thank you, it works for me

Excuse me, could you please guide me on how to configure the use_reentrant parameter to False?

**Comment by ZL315120310** [comment]
> @zijwang请`use_reentrant=False`在 torch 检查点功能中明确设置，这样可以解决问题。https [://pytorch.org/docs/stable/checkpoint.html](https://pytorch.org/docs/stable/checkpoint.html)



> @zijwang请`use_reentrant=False`在 torch 检查点功能中明确设置，这样可以解决问题。https [://pytorch.org/docs/stable/checkpoint.html](https://pytorch.org/docs/stable/checkpoint.html)

Help! i pass gradient_checkpointing_kwargs={'use_reentrant': False} to Trainer but if raise a new error: "RuntimeError: Attempt to retrieve a tensor saved by autograd multiple times without checkpoint recomputation being triggered in between, this is not currently supported. Please open an issue with details on your use case so that we can prioritize adding this."
Is there a good solution?
