### ISSUE TITLE
Request: Upgrade docker to cuda version 11

### ISSUE THREAD

**Issue by SantoshGuptaML** [microsoft/DeepSpeed#989]
We are running on a100s, which require cuda version 11. Currently, the deepseed docker only have version 10.

**Comment by ddomingof** [comment]
Any clues on the exact configuration to run DeepSpeed on CUDA11 and A100s?

**Comment by loadams** [comment]
This was updated to 11.7 and the Dockerfile in the root of the repo should work now.  Please open a new issue if you have any questions or concerns.
